%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
flowchart TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Access7{{"Access[7∈0]<br />ᐸ3.currentUserIdᐳ"}}:::plan
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value3 --> Access7
    Load8[["Load[8∈0]<br />ᐸuserByIdᐳ"]]:::plan
    Access7 --> Load8
    Load11[["Load[11∈0]<br />ᐸfriendshipsByUserIdᐳ"]]:::plan
    Access7 --> Load11
    __Value0["__Value[0∈0]"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    __Item15[/"__Item[15∈3]<br />ᐸ11ᐳ"\]:::itemplan
    Load11 ==> __Item15
    Access17{{"Access[17∈3]<br />ᐸ15.friend_idᐳ"}}:::plan
    __Item15 --> Access17
    Load18[["Load[18∈3]<br />ᐸuserByIdᐳ"]]:::plan
    Access17 --> Load18

    %% define steps

    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,Access7,Load8,Load11 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item15,Access17,Load18 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef unary fill:#fafffa,borderWidth:8px
    class Access7,Load8,Load11,__Value0,__Value3,__Value5 unary