%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection13{{"Connection[13∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection13
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant12{{"Constant[12∈0] ➊<br />ᐸ[Function: applyInputConstant]ᐳ"}}:::plan
    PgUnionAll14[["PgUnionAll[14∈1] ➊"]]:::plan
    Object11 & Constant12 & Connection13 & Constant6 & Constant6 & Constant6 --> PgUnionAll14
    Access18{{"Access[18∈1] ➊<br />ᐸ14.cursorDetailsᐳ"}}:::plan
    PgUnionAll14 --> Access18
    Access45{{"Access[45∈1] ➊<br />ᐸ14.itemsᐳ"}}:::plan
    PgUnionAll14 --> Access45
    __Item16[/"__Item[16∈2]<br />ᐸ45ᐳ"\]:::itemplan
    Access45 ==> __Item16
    PgUnionAllSingle17["PgUnionAllSingle[17∈2]"]:::plan
    __Item16 --> PgUnionAllSingle17
    PgCursor19{{"PgCursor[19∈3]"}}:::plan
    PgUnionAllSingle17 & Access18 --> PgCursor19
    Access20{{"Access[20∈3]<br />ᐸ17.1ᐳ"}}:::plan
    PgUnionAllSingle17 --> Access20
    PgSelect23[["PgSelect[23∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access22{{"Access[22∈4]<br />ᐸ21.0ᐳ"}}:::plan
    Object11 & Access22 --> PgSelect23
    PgSelect36[["PgSelect[36∈4]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access35{{"Access[35∈4]<br />ᐸ34.0ᐳ"}}:::plan
    Object11 & Access35 --> PgSelect36
    JSONParse21[["JSONParse[21∈4]<br />ᐸ20ᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access20 --> JSONParse21
    JSONParse21 --> Access22
    First27{{"First[27∈4]"}}:::plan
    PgSelectRows28[["PgSelectRows[28∈4]"]]:::plan
    PgSelectRows28 --> First27
    PgSelect23 --> PgSelectRows28
    PgSelectSingle29{{"PgSelectSingle[29∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First27 --> PgSelectSingle29
    PgClassExpression30{{"PgClassExpression[30∈4]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression30
    PgClassExpression31{{"PgClassExpression[31∈4]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression31
    PgClassExpression32{{"PgClassExpression[32∈4]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression32
    PgClassExpression33{{"PgClassExpression[33∈4]<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression33
    JSONParse34[["JSONParse[34∈4]<br />ᐸ20ᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access20 --> JSONParse34
    JSONParse34 --> Access35
    First38{{"First[38∈4]"}}:::plan
    PgSelectRows39[["PgSelectRows[39∈4]"]]:::plan
    PgSelectRows39 --> First38
    PgSelect36 --> PgSelectRows39
    PgSelectSingle40{{"PgSelectSingle[40∈4]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First38 --> PgSelectSingle40
    PgClassExpression41{{"PgClassExpression[41∈4]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression41
    PgClassExpression42{{"PgClassExpression[42∈4]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression42
    PgClassExpression43{{"PgClassExpression[43∈4]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression43
    PgClassExpression44{{"PgClassExpression[44∈4]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression44

    %% define steps

    subgraph "Buckets for queries/interfaces-via-union-all/vulnerabilitiesConnection"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access9,Access10,Object11,Constant12,Connection13 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 13, 6<br /><br />ROOT Connectionᐸ8ᐳ[13]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll14,Access18,Access45 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 18, 11<br /><br />ROOT __Item{2}ᐸ45ᐳ[16]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item16,PgUnionAllSingle17 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 17, 18, 11<br /><br />ROOT PgUnionAllSingle{2}[17]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor19,Access20 bucket3
    Bucket4("Bucket 4 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 20, 11, 17<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: JSONParse[21], JSONParse[34]<br />ᐳ: Access[22], Access[35]<br />2: PgSelect[23], PgSelect[36]<br />3: PgSelectRows[28], PgSelectRows[39]<br />ᐳ: 27, 29, 30, 31, 32, 33, 38, 40, 41, 42, 43, 44"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,JSONParse21,Access22,PgSelect23,First27,PgSelectRows28,PgSelectSingle29,PgClassExpression30,PgClassExpression31,PgClassExpression32,PgClassExpression33,JSONParse34,Access35,PgSelect36,First38,PgSelectRows39,PgSelectSingle40,PgClassExpression41,PgClassExpression42,PgClassExpression43,PgClassExpression44 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
