%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-via-union-all/vulnerabilitiesConnection"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 13, 25<br /><br />ROOT Connectionᐸ8ᐳ[13]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 18, 25, 11<br /><br />ROOT __Item{2}ᐸ65ᐳ[16]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 17, 18, 25, 11<br /><br />ROOT PgUnionAllSingle{2}[17]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 11, 29, 20<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: PgSelect[31], PgSelect[49]<br />2: PgSelectRows[40], PgSelectRows[54]<br />ᐳ: 39, 42, 53, 56, 57, 58, 59, 60, 61, 62, 63, 64"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant12{{"Constant[12∈0] ➊<br />ᐸ[Function: applyInputConstant]ᐳ"}}:::plan
    Connection13{{"Connection[13∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant25{{"Constant[25∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    PgUnionAll14[["PgUnionAll[14∈1] ➊<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ"]]:::plan
    Object11 & Constant12 & Connection13 --> PgUnionAll14
    Access18{{"Access[18∈1] ➊<br />ᐸ14.cursorDetailsᐳ"}}:::plan
    PgUnionAll14 --> Access18
    Access65{{"Access[65∈1] ➊<br />ᐸ14.itemsᐳ"}}:::plan
    PgUnionAll14 --> Access65
    __Item16[/"__Item[16∈2]<br />ᐸ65ᐳ"\]:::itemplan
    Access65 ==> __Item16
    PgUnionAllSingle17["PgUnionAllSingle[17∈2]"]:::plan
    __Item16 --> PgUnionAllSingle17
    List26{{"List[26∈3]<br />ᐸ20,23,25ᐳ"}}:::plan
    Access20{{"Access[20∈3]<br />ᐸ17.0ᐳ"}}:::plan
    Access23{{"Access[23∈3]<br />ᐸ17.1ᐳ"}}:::plan
    Access20 & Access23 & Constant25 --> List26
    PgCursor19{{"PgCursor[19∈3]"}}:::plan
    PgUnionAllSingle17 & Access18 --> PgCursor19
    PgUnionAllSingle17 --> Access20
    PgUnionAllSingle17 --> Access23
    Lambda27{{"Lambda[27∈3]<br />ᐸtoSpecifierᐳ"}}:::plan
    List26 --> Lambda27
    Access29{{"Access[29∈3]<br />ᐸ27.idᐳ"}}:::plan
    Lambda27 --> Access29
    PgSelect31[["PgSelect[31∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Object11 & Access29 --> PgSelect31
    PgSelect49[["PgSelect[49∈4]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Object11 & Access29 --> PgSelect49
    First39{{"First[39∈4]^"}}:::plan
    PgSelectRows40[["PgSelectRows[40∈4]^"]]:::plan
    PgSelectRows40 --> First39
    PgSelect31 --> PgSelectRows40
    PgSelectSingle42{{"PgSelectSingle[42∈4]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First39 --> PgSelectSingle42
    First53{{"First[53∈4]^"}}:::plan
    PgSelectRows54[["PgSelectRows[54∈4]^"]]:::plan
    PgSelectRows54 --> First53
    PgSelect49 --> PgSelectRows54
    PgSelectSingle56{{"PgSelectSingle[56∈4]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First53 --> PgSelectSingle56
    PgClassExpression57{{"PgClassExpression[57∈4]^<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression57
    PgClassExpression58{{"PgClassExpression[58∈4]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression58
    PgClassExpression59{{"PgClassExpression[59∈4]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈4]^<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression60
    PgClassExpression61{{"PgClassExpression[61∈4]^<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression61
    PgClassExpression62{{"PgClassExpression[62∈4]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression62
    PgClassExpression63{{"PgClassExpression[63∈4]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression63
    PgClassExpression64{{"PgClassExpression[64∈4]^<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression64

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access9,Access10,Object11,Constant12,Connection13,Constant25 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll14,Access18,Access65 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item16,PgUnionAllSingle17 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor19,Access20,Access23,List26,Lambda27,Access29 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect31,First39,PgSelectRows40,PgSelectSingle42,PgSelect49,First53,PgSelectRows54,PgSelectSingle56,PgClassExpression57,PgClassExpression58,PgClassExpression59,PgClassExpression60,PgClassExpression61,PgClassExpression62,PgClassExpression63,PgClassExpression64 bucket4

