compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@mermaid-js/mermaid-cli@*":
    peerDependenciesMeta:
      puppeteer:
        optional: true

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# re-enable a specific script by combining enableScripts and dependenciesMeta.
enableScripts: false
