# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

# Don't install anything that was released less than a week ago
npmMinimalAgeGate: "1w"
# Unless it's one of ours:
npmPreapprovedPackages:
  - "@graphile/*"

packageExtensions:
  "@mermaid-js/mermaid-cli@*":
    peerDependenciesMeta:
      puppeteer:
        optional: true

# ------------------------------------------------------------------------------

compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
