# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

# Don't install anything that was released less than a week ago
npmMinimalAgeGate: "1w"
# Unless it's one of ours:
npmPreapprovedPackages:
  - "@graphile/*"

packageExtensions:
  "@mermaid-js/mermaid-cli@*":
    peerDependenciesMeta:
      puppeteer:
        optional: true

# ------------------------------------------------------------------------------

# Use conventional `node_modules` layout, with files hardlinked from Yarn's
# global store to save disk usage between working trees.
# WARNING: editing a hardlinked file in place can also change it in other
# worktrees and in the global store. To do in place edits, first change this to
# `nmMode: classic`, remove `node_modules`, and run `yarn` again.
nodeLinker: node-modules
nmMode: hardlinks-global

yarnPath: .yarn/releases/yarn-4.12.0.cjs
