#!/bin/bash
set -e
echo "BOOTSTRAP"
npx lerna bootstrap
echo "CLEANING BUILT FILES"
rm -Rf packages/*/node8plus packages/*/dist
echo "PREPACKING"
./scripts/prepack-all
echo "TEST"
npx lerna run --concurrency 1 test

TAG="${1:-next}"
shift
npx lerna publish --exact --npm-tag="$TAG" "$@"
yarn run changelog
git add CHANGELOG.md
git commit -m"chore: update CHANGELOG"
git push && git push --tags
