%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Connection20{{"Connection[20∈0] ➊<br />ᐸ18ᐳ"}}:::plan
    Constant97{{"Constant[97∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Lambda21{{"Lambda[21∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    Constant97 & Lambda21 --> Connection20
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant97 --> Connection13
    Constant98{{"Constant[98∈0] ➊<br />ᐸ'WyIzNjY0MzE3ZDgwIixmYWxzZSwyLDFd'ᐳ"}}:::plan
    Constant98 --> Lambda21
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Object64{{"Object[64∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access59{{"Access[59∈1] ➊<br />ᐸ23.hasMoreᐳ"}}:::plan
    Constant97 & Access59 --> Object64
    PgSelect23[["PgSelect[23∈1] ➊<br />ᐸcompound_key+1ᐳ"]]:::plan
    Object12 & Connection13 & Constant97 --> PgSelect23
    Object60{{"Object[60∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant97 & Access59 --> Object60
    PgSelect25[["PgSelect[25∈1] ➊<br />ᐸcompound_key(aggregate)ᐳ"]]:::plan
    Object12 & Connection13 --> PgSelect25
    PgCursor50{{"PgCursor[50∈1] ➊"}}:::plan
    PgSelectSingle48{{"PgSelectSingle[48∈1] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    Access49{{"Access[49∈1] ➊<br />ᐸ23.cursorDetailsᐳ"}}:::plan
    PgSelectSingle48 & Access49 --> PgCursor50
    PgCursor56{{"PgCursor[56∈1] ➊"}}:::plan
    PgSelectSingle54{{"PgSelectSingle[54∈1] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    PgSelectSingle54 & Access49 --> PgCursor56
    PgPageInfo24{{"PgPageInfo[24∈1] ➊"}}:::plan
    Connection13 --> PgPageInfo24
    First26{{"First[26∈1] ➊"}}:::plan
    PgSelectRows27[["PgSelectRows[27∈1] ➊"]]:::plan
    PgSelectRows27 --> First26
    PgSelect25 --> PgSelectRows27
    PgSelectSingle28{{"PgSelectSingle[28∈1] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    First26 --> PgSelectSingle28
    PgClassExpression29{{"PgClassExpression[29∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle28 --> PgClassExpression29
    PgSelectRows31[["PgSelectRows[31∈1] ➊"]]:::plan
    PgSelect23 --> PgSelectRows31
    First46{{"First[46∈1] ➊"}}:::plan
    PgSelectRows31 --> First46
    First46 --> PgSelectSingle48
    PgSelect23 --> Access49
    Last52{{"Last[52∈1] ➊"}}:::plan
    PgSelectRows31 --> Last52
    Last52 --> PgSelectSingle54
    PgSelect23 --> Access59
    Lambda61{{"Lambda[61∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object60 --> Lambda61
    Lambda65{{"Lambda[65∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object64 --> Lambda65
    __Item32[/"__Item[32∈3]<br />ᐸ31ᐳ"\]:::itemplan
    PgSelectRows31 ==> __Item32
    PgSelectSingle33{{"PgSelectSingle[33∈3]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item32 --> PgSelectSingle33
    PgCursor67{{"PgCursor[67∈4]"}}:::plan
    PgSelectSingle33 & Access49 --> PgCursor67
    PgClassExpression91{{"PgClassExpression[91∈4]<br />ᐸ__compound...__.”extra”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression91
    PgClassExpression92{{"PgClassExpression[92∈4]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression92
    PgClassExpression93{{"PgClassExpression[93∈4]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression93
    PgSelect34[["PgSelect[34∈2] ➊<br />ᐸcompound_key+1ᐳ"]]:::plan
    Object12 & Connection20 & Lambda21 & Constant97 --> PgSelect34
    Object87{{"Object[87∈2] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access82{{"Access[82∈2] ➊<br />ᐸ34.hasMoreᐳ"}}:::plan
    Constant97 & Access82 --> Object87
    Object83{{"Object[83∈2] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant97 & Access82 --> Object83
    PgSelect36[["PgSelect[36∈2] ➊<br />ᐸcompound_key(aggregate)ᐳ"]]:::plan
    Object12 & Connection20 --> PgSelect36
    PgCursor73{{"PgCursor[73∈2] ➊"}}:::plan
    PgSelectSingle71{{"PgSelectSingle[71∈2] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    Access72{{"Access[72∈2] ➊<br />ᐸ34.cursorDetailsᐳ"}}:::plan
    PgSelectSingle71 & Access72 --> PgCursor73
    PgCursor79{{"PgCursor[79∈2] ➊"}}:::plan
    PgSelectSingle77{{"PgSelectSingle[77∈2] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    PgSelectSingle77 & Access72 --> PgCursor79
    PgPageInfo35{{"PgPageInfo[35∈2] ➊"}}:::plan
    Connection20 --> PgPageInfo35
    First37{{"First[37∈2] ➊"}}:::plan
    PgSelectRows38[["PgSelectRows[38∈2] ➊"]]:::plan
    PgSelectRows38 --> First37
    PgSelect36 --> PgSelectRows38
    PgSelectSingle39{{"PgSelectSingle[39∈2] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    First37 --> PgSelectSingle39
    PgClassExpression40{{"PgClassExpression[40∈2] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression40
    PgSelectRows42[["PgSelectRows[42∈2] ➊"]]:::plan
    PgSelect34 --> PgSelectRows42
    First69{{"First[69∈2] ➊"}}:::plan
    PgSelectRows42 --> First69
    First69 --> PgSelectSingle71
    PgSelect34 --> Access72
    Last75{{"Last[75∈2] ➊"}}:::plan
    PgSelectRows42 --> Last75
    Last75 --> PgSelectSingle77
    PgSelect34 --> Access82
    Lambda84{{"Lambda[84∈2] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object83 --> Lambda84
    Lambda88{{"Lambda[88∈2] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object87 --> Lambda88
    __Item43[/"__Item[43∈5]<br />ᐸ42ᐳ"\]:::itemplan
    PgSelectRows42 ==> __Item43
    PgSelectSingle44{{"PgSelectSingle[44∈5]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item43 --> PgSelectSingle44
    PgCursor90{{"PgCursor[90∈6]"}}:::plan
    PgSelectSingle44 & Access72 --> PgCursor90
    PgClassExpression94{{"PgClassExpression[94∈6]<br />ᐸ__compound...__.”extra”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression94
    PgClassExpression95{{"PgClassExpression[95∈6]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression95
    PgClassExpression96{{"PgClassExpression[96∈6]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression96

    %% define steps

    subgraph "Buckets for queries/v4/connections.boolean"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13,Connection20,Lambda21,Constant97,Constant98 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 13, 97, 7<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[23], PgSelect[25]<br />ᐳ: 24, 49, 59, 60, 61, 64, 65<br />2: PgSelectRows[27], PgSelectRows[31]<br />ᐳ: 26, 28, 29, 46, 48, 50, 52, 54, 56"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect23,PgPageInfo24,PgSelect25,First26,PgSelectRows27,PgSelectSingle28,PgClassExpression29,PgSelectRows31,First46,PgSelectSingle48,Access49,PgCursor50,Last52,PgSelectSingle54,PgCursor56,Access59,Object60,Lambda61,Object64,Lambda65 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 12, 20, 21, 97, 7<br /><br />ROOT Connectionᐸ18ᐳ[20]<br />1: PgSelect[34], PgSelect[36]<br />ᐳ: 35, 72, 82, 83, 84, 87, 88<br />2: PgSelectRows[38], PgSelectRows[42]<br />ᐳ: 37, 39, 40, 69, 71, 73, 75, 77, 79"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgSelect34,PgPageInfo35,PgSelect36,First37,PgSelectRows38,PgSelectSingle39,PgClassExpression40,PgSelectRows42,First69,PgSelectSingle71,Access72,PgCursor73,Last75,PgSelectSingle77,PgCursor79,Access82,Object83,Lambda84,Object87,Lambda88 bucket2
    Bucket3("Bucket 3 (listItem)<br />Deps: 49<br /><br />ROOT __Item{3}ᐸ31ᐳ[32]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item32,PgSelectSingle33 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 33, 49<br /><br />ROOT PgSelectSingle{3}ᐸcompound_keyᐳ[33]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgCursor67,PgClassExpression91,PgClassExpression92,PgClassExpression93 bucket4
    Bucket5("Bucket 5 (listItem)<br />Deps: 72<br /><br />ROOT __Item{5}ᐸ42ᐳ[43]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item43,PgSelectSingle44 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 44, 72<br /><br />ROOT PgSelectSingle{5}ᐸcompound_keyᐳ[44]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor90,PgClassExpression94,PgClassExpression95,PgClassExpression96 bucket6
    Bucket0 --> Bucket1 & Bucket2
    Bucket1 --> Bucket3
    Bucket2 --> Bucket5
    Bucket3 --> Bucket4
    Bucket5 --> Bucket6
    end
