%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection15{{"Connection[15∈0] ➊<br />ᐸ11ᐳ"}}:::plan
    Constant102{{"Constant[102∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Lambda16{{"Lambda[16∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    PgValidateParsedCursor18["PgValidateParsedCursor[18∈0] ➊"]:::plan
    Constant102 & Lambda16 & PgValidateParsedCursor18 & PgValidateParsedCursor18 & PgValidateParsedCursor18 & PgValidateParsedCursor18 & PgValidateParsedCursor18 --> Connection15
    Connection61{{"Connection[61∈0] ➊<br />ᐸ59ᐳ"}}:::plan
    Lambda62{{"Lambda[62∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    PgValidateParsedCursor64["PgValidateParsedCursor[64∈0] ➊"]:::plan
    Constant102 & Lambda62 & PgValidateParsedCursor64 & PgValidateParsedCursor64 & PgValidateParsedCursor64 & PgValidateParsedCursor64 & PgValidateParsedCursor64 --> Connection61
    Object14{{"Object[14∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access12 & Access13 --> Object14
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access12
    __Value2 --> Access13
    Constant113{{"Constant[113∈0] ➊<br />ᐸ''ᐳ"}}:::plan
    Constant113 --> Lambda16
    Lambda16 --> PgValidateParsedCursor18
    Constant115{{"Constant[115∈0] ➊<br />ᐸ'27'ᐳ"}}:::plan
    Constant115 --> Lambda62
    Lambda62 --> PgValidateParsedCursor64
    Lambda105{{"Lambda[105∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant116{{"Constant[116∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant116 --> Lambda105
    Lambda108{{"Lambda[108∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant114{{"Constant[114∈0] ➊<br />ᐸ§{ cursorLower: null, cursorUpper: null, first: null, last: ᐳ"}}:::plan
    Constant114 --> Lambda108
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant38{{"Constant[38∈0] ➊<br />ᐸfalseᐳ"}}:::plan
    PgSelect17[["PgSelect[17∈1] ➊<br />ᐸperson+1ᐳ"]]:::plan
    Access19{{"Access[19∈1] ➊<br />ᐸ16.1ᐳ"}}:::plan
    Object14 & Connection15 & Lambda16 & Access19 & Lambda105 --> PgSelect17
    PgSelect39[["PgSelect[39∈1] ➊<br />ᐸperson(aggregate)ᐳ"]]:::plan
    Object14 & Connection15 & Lambda108 --> PgSelect39
    Lambda16 --> Access19
    PgPageInfo20{{"PgPageInfo[20∈1] ➊"}}:::plan
    Connection15 --> PgPageInfo20
    First22{{"First[22∈1] ➊"}}:::plan
    PgSelect17 --> First22
    PgSelectSingle23{{"PgSelectSingle[23∈1] ➊<br />ᐸpersonᐳ"}}:::plan
    First22 --> PgSelectSingle23
    PgCursor24{{"PgCursor[24∈1] ➊"}}:::plan
    List27{{"List[27∈1] ➊<br />ᐸ26ᐳ"}}:::plan
    List27 --> PgCursor24
    PgClassExpression26{{"PgClassExpression[26∈1] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle23 --> PgClassExpression26
    PgClassExpression26 --> List27
    Last29{{"Last[29∈1] ➊"}}:::plan
    PgSelect17 --> Last29
    PgSelectSingle30{{"PgSelectSingle[30∈1] ➊<br />ᐸpersonᐳ"}}:::plan
    Last29 --> PgSelectSingle30
    PgCursor31{{"PgCursor[31∈1] ➊"}}:::plan
    List34{{"List[34∈1] ➊<br />ᐸ33ᐳ"}}:::plan
    List34 --> PgCursor31
    PgClassExpression33{{"PgClassExpression[33∈1] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression33
    PgClassExpression33 --> List34
    Access36{{"Access[36∈1] ➊<br />ᐸ17.hasMoreᐳ"}}:::plan
    PgSelect17 --> Access36
    First40{{"First[40∈1] ➊"}}:::plan
    PgSelect39 --> First40
    PgSelectSingle41{{"PgSelectSingle[41∈1] ➊<br />ᐸpersonᐳ"}}:::plan
    First40 --> PgSelectSingle41
    PgClassExpression42{{"PgClassExpression[42∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression42
    __Item45[/"__Item[45∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelect17 ==> __Item45
    PgSelectSingle46{{"PgSelectSingle[46∈2]<br />ᐸpersonᐳ"}}:::plan
    __Item45 --> PgSelectSingle46
    PgCursor47{{"PgCursor[47∈3]"}}:::plan
    List49{{"List[49∈3]<br />ᐸ48ᐳ"}}:::plan
    List49 --> PgCursor47
    PgClassExpression48{{"PgClassExpression[48∈3]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression48
    PgClassExpression48 --> List49
    PgClassExpression51{{"PgClassExpression[51∈3]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression51
    PgClassExpression52{{"PgClassExpression[52∈3]<br />ᐸ__person__.”email”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression52
    PgClassExpression53{{"PgClassExpression[53∈3]<br />ᐸ__person__.”config”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression53
    PgClassExpression54{{"PgClassExpression[54∈3]<br />ᐸ__person__...n_from_ip”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression54
    PgSelect63[["PgSelect[63∈4] ➊<br />ᐸperson+1ᐳ"]]:::plan
    Access65{{"Access[65∈4] ➊<br />ᐸ62.1ᐳ"}}:::plan
    Object14 & Connection61 & Lambda62 & Access65 & Lambda105 --> PgSelect63
    PgSelect85[["PgSelect[85∈4] ➊<br />ᐸperson(aggregate)ᐳ"]]:::plan
    Object14 & Connection61 & Lambda108 --> PgSelect85
    Lambda62 --> Access65
    PgPageInfo66{{"PgPageInfo[66∈4] ➊"}}:::plan
    Connection61 --> PgPageInfo66
    First68{{"First[68∈4] ➊"}}:::plan
    PgSelect63 --> First68
    PgSelectSingle69{{"PgSelectSingle[69∈4] ➊<br />ᐸpersonᐳ"}}:::plan
    First68 --> PgSelectSingle69
    PgCursor70{{"PgCursor[70∈4] ➊"}}:::plan
    List73{{"List[73∈4] ➊<br />ᐸ72ᐳ"}}:::plan
    List73 --> PgCursor70
    PgClassExpression72{{"PgClassExpression[72∈4] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression72
    PgClassExpression72 --> List73
    Last75{{"Last[75∈4] ➊"}}:::plan
    PgSelect63 --> Last75
    PgSelectSingle76{{"PgSelectSingle[76∈4] ➊<br />ᐸpersonᐳ"}}:::plan
    Last75 --> PgSelectSingle76
    PgCursor77{{"PgCursor[77∈4] ➊"}}:::plan
    List80{{"List[80∈4] ➊<br />ᐸ79ᐳ"}}:::plan
    List80 --> PgCursor77
    PgClassExpression79{{"PgClassExpression[79∈4] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle76 --> PgClassExpression79
    PgClassExpression79 --> List80
    Access82{{"Access[82∈4] ➊<br />ᐸ63.hasMoreᐳ"}}:::plan
    PgSelect63 --> Access82
    First86{{"First[86∈4] ➊"}}:::plan
    PgSelect85 --> First86
    PgSelectSingle87{{"PgSelectSingle[87∈4] ➊<br />ᐸpersonᐳ"}}:::plan
    First86 --> PgSelectSingle87
    PgClassExpression88{{"PgClassExpression[88∈4] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle87 --> PgClassExpression88
    __Item91[/"__Item[91∈5]<br />ᐸ63ᐳ"\]:::itemplan
    PgSelect63 ==> __Item91
    PgSelectSingle92{{"PgSelectSingle[92∈5]<br />ᐸpersonᐳ"}}:::plan
    __Item91 --> PgSelectSingle92
    PgCursor93{{"PgCursor[93∈6]"}}:::plan
    List95{{"List[95∈6]<br />ᐸ94ᐳ"}}:::plan
    List95 --> PgCursor93
    PgClassExpression94{{"PgClassExpression[94∈6]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle92 --> PgClassExpression94
    PgClassExpression94 --> List95
    PgClassExpression97{{"PgClassExpression[97∈6]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle92 --> PgClassExpression97
    PgClassExpression98{{"PgClassExpression[98∈6]<br />ᐸ__person__.”email”ᐳ"}}:::plan
    PgSelectSingle92 --> PgClassExpression98
    PgClassExpression99{{"PgClassExpression[99∈6]<br />ᐸ__person__.”config”ᐳ"}}:::plan
    PgSelectSingle92 --> PgClassExpression99
    PgClassExpression100{{"PgClassExpression[100∈6]<br />ᐸ__person__...n_from_ip”ᐳ"}}:::plan
    PgSelectSingle92 --> PgClassExpression100

    %% define steps

    subgraph "Buckets for queries/v4/connections-blankcursor"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 12, 13, 38, 102, 113, 114, 115, 116, 14, 16, 62, 105, 108<br />2: 18, 64<br />ᐳ: Connection[15], Connection[61]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access12,Access13,Object14,Connection15,Lambda16,PgValidateParsedCursor18,Constant38,Connection61,Lambda62,PgValidateParsedCursor64,Constant102,Lambda105,Lambda108,Constant113,Constant114,Constant115,Constant116 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 14, 15, 16, 105, 108, 38<br /><br />ROOT Connectionᐸ11ᐳ[15]<br />1: PgSelect[39]<br />ᐳ: 19, 20, 40, 41, 42<br />2: PgSelect[17]<br />ᐳ: 22, 23, 26, 27, 29, 30, 33, 34, 36, 24, 31"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect17,Access19,PgPageInfo20,First22,PgSelectSingle23,PgCursor24,PgClassExpression26,List27,Last29,PgSelectSingle30,PgCursor31,PgClassExpression33,List34,Access36,PgSelect39,First40,PgSelectSingle41,PgClassExpression42 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ17ᐳ[45]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item45,PgSelectSingle46 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 46<br /><br />ROOT PgSelectSingle{2}ᐸpersonᐳ[46]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor47,PgClassExpression48,List49,PgClassExpression51,PgClassExpression52,PgClassExpression53,PgClassExpression54 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 14, 61, 62, 105, 108, 38<br /><br />ROOT Connectionᐸ59ᐳ[61]<br />1: PgSelect[85]<br />ᐳ: 65, 66, 86, 87, 88<br />2: PgSelect[63]<br />ᐳ: 68, 69, 72, 73, 75, 76, 79, 80, 82, 70, 77"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect63,Access65,PgPageInfo66,First68,PgSelectSingle69,PgCursor70,PgClassExpression72,List73,Last75,PgSelectSingle76,PgCursor77,PgClassExpression79,List80,Access82,PgSelect85,First86,PgSelectSingle87,PgClassExpression88 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ63ᐳ[91]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item91,PgSelectSingle92 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 92<br /><br />ROOT PgSelectSingle{5}ᐸpersonᐳ[92]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor93,PgClassExpression94,List95,PgClassExpression97,PgClassExpression98,PgClassExpression99,PgClassExpression100 bucket6
    Bucket0 --> Bucket1 & Bucket4
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    end
