%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    Connection26{{"Connection[26∈0]<br />ᐸ22ᐳ"}}:::plan
    PgSelect27[["PgSelect[27∈1]<br />ᐸpersonᐳ"]]:::plan
    Object25{{"Object[25∈1]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant39{{"Constant[39∈1]<br />ᐸ'col_no_create1'ᐳ"}}:::plan
    Object25 & Constant39 & Connection26 --> PgSelect27
    Access23{{"Access[23∈1]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access24{{"Access[24∈1]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Access23 & Access24 --> Object25
    __Value3 --> Access23
    __Value3 --> Access24
    __Item28[/"__Item[28∈2]<br />ᐸ27ᐳ"\]:::itemplan
    PgSelect27 ==> __Item28
    PgSelectSingle29{{"PgSelectSingle[29∈2]<br />ᐸpersonᐳ"}}:::plan
    __Item28 --> PgSelectSingle29
    PgClassExpression30{{"PgClassExpression[30∈3]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression30
    PgClassExpression31{{"PgClassExpression[31∈3]<br />ᐸ__person__.”first_name”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression31
    PgClassExpression32{{"PgClassExpression[32∈3]<br />ᐸ__person__.”last_name”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression32
    PgClassExpression33{{"PgClassExpression[33∈3]<br />ᐸ__person__...no_create”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression33
    PgClassExpression34{{"PgClassExpression[34∈3]<br />ᐸ__person__...no_update”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression34
    PgClassExpression35{{"PgClassExpression[35∈3]<br />ᐸ__person__..._no_order”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression35
    PgClassExpression36{{"PgClassExpression[36∈3]<br />ᐸ__person__...no_filter”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression36
    PgClassExpression37{{"PgClassExpression[37∈3]<br />ᐸ__person__...te_update”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression37
    PgClassExpression38{{"PgClassExpression[38∈3]<br />ᐸ__person__...er_filter”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression38

    %% define steps

    subgraph "Buckets for queries/v4/d.filter"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value3,__Value5,Connection26 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 3, 26<br /><br />ROOT Connectionᐸ22ᐳ[26]<br />1: <br />ᐳ: 23, 24, 39, 25<br />2: PgSelect[27]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Access23,Access24,Object25,PgSelect27,Constant39 bucket1
    Bucket2("Bucket 2 (listItem)<br />ROOT __Item{2}ᐸ27ᐳ[28]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item28,PgSelectSingle29 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 29<br /><br />ROOT PgSelectSingle{2}ᐸpersonᐳ[29]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression30,PgClassExpression31,PgClassExpression32,PgClassExpression33,PgClassExpression34,PgClassExpression35,PgClassExpression36,PgClassExpression37,PgClassExpression38 bucket3
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    classDef unary fill:#fafffa,borderWidth:8px
    class __Value3,__Value5,Connection26,PgSelect27,Object25,Access23,Access24,Constant39 unary
    end
