%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object16{{"Object[16∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access14{{"Access[14∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access15{{"Access[15∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access14 & Access15 --> Object16
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access14
    __Value2 --> Access15
    __Value0["__Value[0∈0] ➊<br />ᐸvariableValuesᐳ"]:::plan
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection17{{"Connection[17∈0] ➊<br />ᐸ13ᐳ"}}:::plan
    Connection29{{"Connection[29∈0] ➊<br />ᐸ27ᐳ"}}:::plan
    Connection42{{"Connection[42∈0] ➊<br />ᐸ40ᐳ"}}:::plan
    PgSelect18[["PgSelect[18∈1] ➊<br />ᐸmy_tableᐳ"]]:::plan
    __InputDynamicScalar10{{"__InputDynamicScalar[10∈1] ➊"}}:::plan
    Object16 & __InputDynamicScalar10 & Connection17 --> PgSelect18
    Access11{{"Access[11∈1] ➊<br />ᐸ0.myValᐳ"}}:::plan
    Access11 --> __InputDynamicScalar10
    __Value0 --> Access11
    __Item19[/"__Item[19∈2]<br />ᐸ18ᐳ"\]:::itemplan
    PgSelect18 ==> __Item19
    PgSelectSingle20{{"PgSelectSingle[20∈2]<br />ᐸmy_tableᐳ"}}:::plan
    __Item19 --> PgSelectSingle20
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__my_table__.”id”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__my_table...json_data”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression22
    PgSelect30[["PgSelect[30∈4] ➊<br />ᐸmy_tableᐳ"]]:::plan
    __InputDynamicScalar26{{"__InputDynamicScalar[26∈4] ➊"}}:::plan
    Object16 & __InputDynamicScalar26 & Connection29 --> PgSelect30
    __Item31[/"__Item[31∈5]<br />ᐸ30ᐳ"\]:::itemplan
    PgSelect30 ==> __Item31
    PgSelectSingle32{{"PgSelectSingle[32∈5]<br />ᐸmy_tableᐳ"}}:::plan
    __Item31 --> PgSelectSingle32
    PgClassExpression33{{"PgClassExpression[33∈6]<br />ᐸ__my_table__.”id”ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression33
    PgClassExpression34{{"PgClassExpression[34∈6]<br />ᐸ__my_table...json_data”ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression34
    PgSelect43[["PgSelect[43∈7] ➊<br />ᐸmy_tableᐳ"]]:::plan
    Access38{{"Access[38∈7] ➊<br />ᐸ0.myVal2ᐳ"}}:::plan
    Object16 & Access38 & Connection42 --> PgSelect43
    __Value0 --> Access38
    __Item44[/"__Item[44∈8]<br />ᐸ43ᐳ"\]:::itemplan
    PgSelect43 ==> __Item44
    PgSelectSingle45{{"PgSelectSingle[45∈8]<br />ᐸmy_tableᐳ"}}:::plan
    __Item44 --> PgSelectSingle45
    PgClassExpression46{{"PgClassExpression[46∈9]<br />ᐸ__my_table__.”id”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression46
    PgClassExpression47{{"PgClassExpression[47∈9]<br />ᐸ__my_table...json_data”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression47

    %% define steps

    subgraph "Buckets for queries/v4/dynamic-json.condition-json-field-variable"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value2,__Value4,Access14,Access15,Object16,Connection17,Connection29,Connection42 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 0, 16, 17<br /><br />ROOT Connectionᐸ13ᐳ[17]<br />1: <br />ᐳ: Access[11], __InputDynamicScalar[10]<br />2: PgSelect[18]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__InputDynamicScalar10,Access11,PgSelect18 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ18ᐳ[19]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item19,PgSelectSingle20 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 20<br /><br />ROOT PgSelectSingle{2}ᐸmy_tableᐳ[20]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression21,PgClassExpression22 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 16, 29<br /><br />ROOT Connectionᐸ27ᐳ[29]<br />1: <br />ᐳ: __InputDynamicScalar[26]<br />2: PgSelect[30]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__InputDynamicScalar26,PgSelect30 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ30ᐳ[31]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item31,PgSelectSingle32 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 32<br /><br />ROOT PgSelectSingle{5}ᐸmy_tableᐳ[32]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression33,PgClassExpression34 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 0, 16, 42<br /><br />ROOT Connectionᐸ40ᐳ[42]<br />1: <br />ᐳ: Access[38]<br />2: PgSelect[43]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,Access38,PgSelect43 bucket7
    Bucket8("Bucket 8 (listItem)<br /><br />ROOT __Item{8}ᐸ43ᐳ[44]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item44,PgSelectSingle45 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 45<br /><br />ROOT PgSelectSingle{8}ᐸmy_tableᐳ[45]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression46,PgClassExpression47 bucket9
    Bucket0 --> Bucket1 & Bucket4 & Bucket7
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9
    end
