%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect311[["PgSelect[311∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant632{{"Constant[632∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant633{{"Constant[633∈0] ➊<br />ᐸ'test'ᐳ"}}:::plan
    Object11 & Constant632 & Constant633 & Constant632 & Constant633 & Constant633 --> PgSelect311
    PgSelect431[["PgSelect[431∈0] ➊<br />ᐸquery_output_two_rowsᐳ"]]:::plan
    Constant644{{"Constant[644∈0] ➊<br />ᐸ42ᐳ"}}:::plan
    Constant646{{"Constant[646∈0] ➊<br />ᐸ'Hi'ᐳ"}}:::plan
    Object11 & Constant644 & Constant632 & Constant646 --> PgSelect431
    PgSelect501[["PgSelect[501∈0] ➊<br />ᐸquery_output_two_rowsᐳ"]]:::plan
    Constant647{{"Constant[647∈0] ➊<br />ᐸ999999999ᐳ"}}:::plan
    Constant649{{"Constant[649∈0] ➊<br />ᐸ”Don't fail me now...”ᐳ"}}:::plan
    Object11 & Constant647 & Constant647 & Constant649 --> PgSelect501
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸfunc_in_inoutᐳ"]]:::plan
    Constant629{{"Constant[629∈0] ➊<br />ᐸ10ᐳ"}}:::plan
    Constant630{{"Constant[630∈0] ➊<br />ᐸ5ᐳ"}}:::plan
    Object11 & Constant629 & Constant630 --> PgSelect8
    PgSelect32[["PgSelect[32∈0] ➊<br />ᐸfunc_out_complexᐳ"]]:::plan
    Object11 & Constant632 & Constant633 --> PgSelect32
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect16[["PgSelect[16∈0] ➊<br />ᐸfunc_in_outᐳ"]]:::plan
    Object11 & Constant629 --> PgSelect16
    PgSelect158[["PgSelect[158∈0] ➊<br />ᐸfunc_out_out_compound_typeᐳ"]]:::plan
    Object11 & Constant629 --> PgSelect158
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    First12{{"First[12∈0] ➊"}}:::plan
    PgSelect8 --> First12
    PgSelectSingle13{{"PgSelectSingle[13∈0] ➊<br />ᐸfunc_in_inoutᐳ"}}:::plan
    First12 --> PgSelectSingle13
    PgClassExpression14{{"PgClassExpression[14∈0] ➊<br />ᐸ__func_in_inout__.vᐳ"}}:::plan
    PgSelectSingle13 --> PgClassExpression14
    First20{{"First[20∈0] ➊"}}:::plan
    PgSelect16 --> First20
    PgSelectSingle21{{"PgSelectSingle[21∈0] ➊<br />ᐸfunc_in_outᐳ"}}:::plan
    First20 --> PgSelectSingle21
    PgClassExpression22{{"PgClassExpression[22∈0] ➊<br />ᐸ__func_in_out__.vᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression22
    PgSelect23[["PgSelect[23∈0] ➊<br />ᐸfunc_outᐳ"]]:::plan
    Object11 --> PgSelect23
    First27{{"First[27∈0] ➊"}}:::plan
    PgSelect23 --> First27
    PgSelectSingle28{{"PgSelectSingle[28∈0] ➊<br />ᐸfunc_outᐳ"}}:::plan
    First27 --> PgSelectSingle28
    PgClassExpression29{{"PgClassExpression[29∈0] ➊<br />ᐸ__func_out__.vᐳ"}}:::plan
    PgSelectSingle28 --> PgClassExpression29
    First36{{"First[36∈0] ➊"}}:::plan
    PgSelect32 --> First36
    PgSelectSingle37{{"PgSelectSingle[37∈0] ➊<br />ᐸfunc_out_complexᐳ"}}:::plan
    First36 --> PgSelectSingle37
    PgSelect149[["PgSelect[149∈0] ➊<br />ᐸfunc_out_outᐳ"]]:::plan
    Object11 --> PgSelect149
    First153{{"First[153∈0] ➊"}}:::plan
    PgSelect149 --> First153
    PgSelectSingle154{{"PgSelectSingle[154∈0] ➊<br />ᐸfunc_out_outᐳ"}}:::plan
    First153 --> PgSelectSingle154
    First162{{"First[162∈0] ➊"}}:::plan
    PgSelect158 --> First162
    PgSelectSingle163{{"PgSelectSingle[163∈0] ➊<br />ᐸfunc_out_out_compound_typeᐳ"}}:::plan
    First162 --> PgSelectSingle163
    PgSelect194[["PgSelect[194∈0] ➊<br />ᐸfunc_out_out_unnamedᐳ"]]:::plan
    Object11 --> PgSelect194
    First198{{"First[198∈0] ➊"}}:::plan
    PgSelect194 --> First198
    PgSelectSingle199{{"PgSelectSingle[199∈0] ➊<br />ᐸfunc_out_out_unnamedᐳ"}}:::plan
    First198 --> PgSelectSingle199
    PgSelect220[["PgSelect[220∈0] ➊<br />ᐸfunc_out_tableᐳ"]]:::plan
    Object11 --> PgSelect220
    First224{{"First[224∈0] ➊"}}:::plan
    PgSelect220 --> First224
    PgSelectSingle225{{"PgSelectSingle[225∈0] ➊<br />ᐸfunc_out_tableᐳ"}}:::plan
    First224 --> PgSelectSingle225
    PgSelect253[["PgSelect[253∈0] ➊<br />ᐸfunc_out_unnamedᐳ"]]:::plan
    Object11 --> PgSelect253
    First257{{"First[257∈0] ➊"}}:::plan
    PgSelect253 --> First257
    PgSelectSingle258{{"PgSelectSingle[258∈0] ➊<br />ᐸfunc_out_unnamedᐳ"}}:::plan
    First257 --> PgSelectSingle258
    PgClassExpression259{{"PgClassExpression[259∈0] ➊<br />ᐸ__func_out_unnamed__.vᐳ"}}:::plan
    PgSelectSingle258 --> PgClassExpression259
    PgSelect260[["PgSelect[260∈0] ➊<br />ᐸfunc_out_unnamed_out_out_unnamedᐳ"]]:::plan
    Object11 --> PgSelect260
    First264{{"First[264∈0] ➊"}}:::plan
    PgSelect260 --> First264
    PgSelectSingle265{{"PgSelectSingle[265∈0] ➊<br />ᐸfunc_out_unnamed_out_out_unnamedᐳ"}}:::plan
    First264 --> PgSelectSingle265
    First315{{"First[315∈0] ➊"}}:::plan
    PgSelect311 --> First315
    PgSelectSingle316{{"PgSelectSingle[316∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First315 --> PgSelectSingle316
    First435{{"First[435∈0] ➊"}}:::plan
    PgSelect431 --> First435
    PgSelectSingle436{{"PgSelectSingle[436∈0] ➊<br />ᐸquery_output_two_rowsᐳ"}}:::plan
    First435 --> PgSelectSingle436
    First505{{"First[505∈0] ➊"}}:::plan
    PgSelect501 --> First505
    PgSelectSingle506{{"PgSelectSingle[506∈0] ➊<br />ᐸquery_output_two_rowsᐳ"}}:::plan
    First505 --> PgSelectSingle506
    PgSelect570[["PgSelect[570∈0] ➊<br />ᐸsearch_test_summariesᐳ"]]:::plan
    Object11 --> PgSelect570
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant56{{"Constant[56∈0] ➊<br />ᐸ'people'ᐳ"}}:::plan
    Constant79{{"Constant[79∈0] ➊<br />ᐸ'posts'ᐳ"}}:::plan
    Connection95{{"Connection[95∈0] ➊<br />ᐸ91ᐳ"}}:::plan
    Connection184{{"Connection[184∈0] ➊<br />ᐸ180ᐳ"}}:::plan
    Connection211{{"Connection[211∈0] ➊<br />ᐸ207ᐳ"}}:::plan
    Connection240{{"Connection[240∈0] ➊<br />ᐸ236ᐳ"}}:::plan
    Connection281{{"Connection[281∈0] ➊<br />ᐸ277ᐳ"}}:::plan
    Connection301{{"Connection[301∈0] ➊<br />ᐸ297ᐳ"}}:::plan
    Constant637{{"Constant[637∈0] ➊<br />ᐸ20ᐳ"}}:::plan
    PgClassExpression38{{"PgClassExpression[38∈1] ➊<br />ᐸ__func_out...plex__.”x”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression38
    PgSelectSingle45{{"PgSelectSingle[45∈1] ➊<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    RemapKeys580{{"RemapKeys[580∈1] ➊<br />ᐸ37:{”0”:1,”1”:2,”2”:3,”3”:4}ᐳ"}}:::plan
    RemapKeys580 --> PgSelectSingle45
    PgSelectSingle55{{"PgSelectSingle[55∈1] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys583{{"RemapKeys[583∈1] ➊<br />ᐸ37:{”0”:5,”1”:6,”2”:7}ᐳ"}}:::plan
    RemapKeys583 --> PgSelectSingle55
    PgSelectSingle37 --> RemapKeys580
    PgSelectSingle37 --> RemapKeys583
    Connection75{{"Connection[75∈1] ➊<br />ᐸ71ᐳ"}}:::plan
    PgClassExpression46{{"PgClassExpression[46∈2] ➊<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression46
    PgClassExpression47{{"PgClassExpression[47∈2] ➊<br />ᐸ__frmcdc_c...type__.”b”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression47
    PgClassExpression48{{"PgClassExpression[48∈2] ➊<br />ᐸ__frmcdc_c...type__.”c”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression48
    List58{{"List[58∈3] ➊<br />ᐸ56,57ᐳ"}}:::plan
    PgClassExpression57{{"PgClassExpression[57∈3] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression57 --> List58
    PgSelectSingle55 --> PgClassExpression57
    Lambda59{{"Lambda[59∈3] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List58 --> Lambda59
    PgClassExpression61{{"PgClassExpression[61∈3] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle55 --> PgClassExpression61
    Access582{{"Access[582∈3] ➊<br />ᐸ583.0ᐳ"}}:::plan
    RemapKeys583 --> Access582
    __Item77[/"__Item[77∈4]<br />ᐸ582ᐳ"\]:::itemplan
    Access582 ==> __Item77
    PgSelectSingle78{{"PgSelectSingle[78∈4]<br />ᐸpostᐳ"}}:::plan
    __Item77 --> PgSelectSingle78
    List81{{"List[81∈5]<br />ᐸ79,80ᐳ"}}:::plan
    PgClassExpression80{{"PgClassExpression[80∈5]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant79 & PgClassExpression80 --> List81
    PgSelectSingle78 --> PgClassExpression80
    Lambda82{{"Lambda[82∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List81 --> Lambda82
    PgSelect96[["PgSelect[96∈6] ➊<br />ᐸfunc_out_complex_setofᐳ"]]:::plan
    Object11 & Constant632 & Constant633 & Connection95 --> PgSelect96
    PgSelect145[["PgSelect[145∈6] ➊<br />ᐸfunc_out_complex_setof(aggregate)ᐳ"]]:::plan
    Object11 & Constant632 & Constant633 & Connection95 --> PgSelect145
    First146{{"First[146∈6] ➊"}}:::plan
    PgSelect145 --> First146
    PgSelectSingle147{{"PgSelectSingle[147∈6] ➊<br />ᐸfunc_out_complex_setofᐳ"}}:::plan
    First146 --> PgSelectSingle147
    PgClassExpression148{{"PgClassExpression[148∈6] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle147 --> PgClassExpression148
    Connection136{{"Connection[136∈6] ➊<br />ᐸ132ᐳ"}}:::plan
    __Item97[/"__Item[97∈7]<br />ᐸ96ᐳ"\]:::itemplan
    PgSelect96 ==> __Item97
    PgSelectSingle98{{"PgSelectSingle[98∈7]<br />ᐸfunc_out_complex_setofᐳ"}}:::plan
    __Item97 --> PgSelectSingle98
    PgSelect101[["PgSelect[101∈8]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression100{{"PgClassExpression[100∈8]<br />ᐸ__func_out...etof__.”y”ᐳ"}}:::plan
    Object11 & PgClassExpression100 --> PgSelect101
    PgSelect111[["PgSelect[111∈8]<br />ᐸpersonᐳ"]]:::plan
    PgClassExpression110{{"PgClassExpression[110∈8]<br />ᐸ__func_out...etof__.”z”ᐳ"}}:::plan
    Object11 & PgClassExpression110 --> PgSelect111
    PgClassExpression99{{"PgClassExpression[99∈8]<br />ᐸ__func_out...etof__.”x”ᐳ"}}:::plan
    PgSelectSingle98 --> PgClassExpression99
    PgSelectSingle98 --> PgClassExpression100
    First105{{"First[105∈8]"}}:::plan
    PgSelect101 --> First105
    PgSelectSingle106{{"PgSelectSingle[106∈8]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First105 --> PgSelectSingle106
    PgSelectSingle98 --> PgClassExpression110
    First115{{"First[115∈8]"}}:::plan
    PgSelect111 --> First115
    PgSelectSingle116{{"PgSelectSingle[116∈8]<br />ᐸpersonᐳ"}}:::plan
    First115 --> PgSelectSingle116
    PgClassExpression107{{"PgClassExpression[107∈9]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression107
    PgClassExpression108{{"PgClassExpression[108∈9]<br />ᐸ__frmcdc_c...type__.”b”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression108
    PgClassExpression109{{"PgClassExpression[109∈9]<br />ᐸ__frmcdc_c...type__.”c”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression109
    List119{{"List[119∈10]<br />ᐸ56,118ᐳ"}}:::plan
    PgClassExpression118{{"PgClassExpression[118∈10]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression118 --> List119
    PgSelectSingle116 --> PgClassExpression118
    Lambda120{{"Lambda[120∈10]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List119 --> Lambda120
    PgClassExpression122{{"PgClassExpression[122∈10]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle116 --> PgClassExpression122
    Access585{{"Access[585∈10]<br />ᐸ115.0ᐳ"}}:::plan
    First115 --> Access585
    __Item138[/"__Item[138∈11]<br />ᐸ585ᐳ"\]:::itemplan
    Access585 ==> __Item138
    PgSelectSingle139{{"PgSelectSingle[139∈11]<br />ᐸpostᐳ"}}:::plan
    __Item138 --> PgSelectSingle139
    List142{{"List[142∈12]<br />ᐸ79,141ᐳ"}}:::plan
    PgClassExpression141{{"PgClassExpression[141∈12]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant79 & PgClassExpression141 --> List142
    PgSelectSingle139 --> PgClassExpression141
    Lambda143{{"Lambda[143∈12]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List142 --> Lambda143
    PgClassExpression155{{"PgClassExpression[155∈13] ➊<br />ᐸ__func_out...first_out”ᐳ"}}:::plan
    PgSelectSingle154 --> PgClassExpression155
    PgClassExpression156{{"PgClassExpression[156∈13] ➊<br />ᐸ__func_out...econd_out”ᐳ"}}:::plan
    PgSelectSingle154 --> PgClassExpression156
    PgClassExpression164{{"PgClassExpression[164∈14] ➊<br />ᐸ__func_out...ype__.”o1”ᐳ"}}:::plan
    PgSelectSingle163 --> PgClassExpression164
    PgSelectSingle171{{"PgSelectSingle[171∈14] ➊<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    RemapKeys586{{"RemapKeys[586∈14] ➊<br />ᐸ163:{”0”:1,”1”:2,”2”:3,”3”:4}ᐳ"}}:::plan
    RemapKeys586 --> PgSelectSingle171
    PgSelectSingle163 --> RemapKeys586
    PgClassExpression172{{"PgClassExpression[172∈15] ➊<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle171 --> PgClassExpression172
    PgClassExpression173{{"PgClassExpression[173∈15] ➊<br />ᐸ__frmcdc_c...type__.”b”ᐳ"}}:::plan
    PgSelectSingle171 --> PgClassExpression173
    PgClassExpression174{{"PgClassExpression[174∈15] ➊<br />ᐸ__frmcdc_c...type__.”c”ᐳ"}}:::plan
    PgSelectSingle171 --> PgClassExpression174
    PgSelect185[["PgSelect[185∈16] ➊<br />ᐸfunc_out_out_setofᐳ"]]:::plan
    Object11 & Connection184 --> PgSelect185
    PgSelect190[["PgSelect[190∈16] ➊<br />ᐸfunc_out_out_setof(aggregate)ᐳ"]]:::plan
    Object11 & Connection184 --> PgSelect190
    First191{{"First[191∈16] ➊"}}:::plan
    PgSelect190 --> First191
    PgSelectSingle192{{"PgSelectSingle[192∈16] ➊<br />ᐸfunc_out_out_setofᐳ"}}:::plan
    First191 --> PgSelectSingle192
    PgClassExpression193{{"PgClassExpression[193∈16] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle192 --> PgClassExpression193
    __Item186[/"__Item[186∈17]<br />ᐸ185ᐳ"\]:::itemplan
    PgSelect185 ==> __Item186
    PgSelectSingle187{{"PgSelectSingle[187∈17]<br />ᐸfunc_out_out_setofᐳ"}}:::plan
    __Item186 --> PgSelectSingle187
    PgClassExpression188{{"PgClassExpression[188∈18]<br />ᐸ__func_out...tof__.”o1”ᐳ"}}:::plan
    PgSelectSingle187 --> PgClassExpression188
    PgClassExpression189{{"PgClassExpression[189∈18]<br />ᐸ__func_out...tof__.”o2”ᐳ"}}:::plan
    PgSelectSingle187 --> PgClassExpression189
    PgClassExpression200{{"PgClassExpression[200∈19] ➊<br />ᐸ__func_out....”column1”ᐳ"}}:::plan
    PgSelectSingle199 --> PgClassExpression200
    PgClassExpression201{{"PgClassExpression[201∈19] ➊<br />ᐸ__func_out....”column2”ᐳ"}}:::plan
    PgSelectSingle199 --> PgClassExpression201
    PgSelect212[["PgSelect[212∈20] ➊<br />ᐸfunc_out_setofᐳ"]]:::plan
    Object11 & Connection211 --> PgSelect212
    PgSelect216[["PgSelect[216∈20] ➊<br />ᐸfunc_out_setof(aggregate)ᐳ"]]:::plan
    Object11 & Connection211 --> PgSelect216
    First217{{"First[217∈20] ➊"}}:::plan
    PgSelect216 --> First217
    PgSelectSingle218{{"PgSelectSingle[218∈20] ➊<br />ᐸfunc_out_setofᐳ"}}:::plan
    First217 --> PgSelectSingle218
    PgClassExpression219{{"PgClassExpression[219∈20] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle218 --> PgClassExpression219
    __Item213[/"__Item[213∈21]<br />ᐸ212ᐳ"\]:::itemplan
    PgSelect212 ==> __Item213
    PgSelectSingle214{{"PgSelectSingle[214∈21]<br />ᐸfunc_out_setofᐳ"}}:::plan
    __Item213 --> PgSelectSingle214
    PgClassExpression215{{"PgClassExpression[215∈21]<br />ᐸ__func_out_setof__.vᐳ"}}:::plan
    PgSelectSingle214 --> PgClassExpression215
    List228{{"List[228∈22] ➊<br />ᐸ56,227ᐳ"}}:::plan
    PgClassExpression227{{"PgClassExpression[227∈22] ➊<br />ᐸ__func_out_table__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression227 --> List228
    PgSelectSingle225 --> PgClassExpression227
    Lambda229{{"Lambda[229∈22] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List228 --> Lambda229
    PgSelect241[["PgSelect[241∈23] ➊<br />ᐸfunc_out_table_setofᐳ"]]:::plan
    Object11 & Connection240 --> PgSelect241
    PgSelect249[["PgSelect[249∈23] ➊<br />ᐸfunc_out_table_setof(aggregate)ᐳ"]]:::plan
    Object11 & Connection240 --> PgSelect249
    First250{{"First[250∈23] ➊"}}:::plan
    PgSelect249 --> First250
    PgSelectSingle251{{"PgSelectSingle[251∈23] ➊<br />ᐸfunc_out_table_setofᐳ"}}:::plan
    First250 --> PgSelectSingle251
    PgClassExpression252{{"PgClassExpression[252∈23] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle251 --> PgClassExpression252
    __Item242[/"__Item[242∈24]<br />ᐸ241ᐳ"\]:::itemplan
    PgSelect241 ==> __Item242
    PgSelectSingle243{{"PgSelectSingle[243∈24]<br />ᐸfunc_out_table_setofᐳ"}}:::plan
    __Item242 --> PgSelectSingle243
    List246{{"List[246∈25]<br />ᐸ56,245ᐳ"}}:::plan
    PgClassExpression245{{"PgClassExpression[245∈25]<br />ᐸ__func_out...tof__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression245 --> List246
    PgSelectSingle243 --> PgClassExpression245
    Lambda247{{"Lambda[247∈25]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List246 --> Lambda247
    PgClassExpression266{{"PgClassExpression[266∈26] ➊<br />ᐸ__func_out....”column1”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression266
    PgClassExpression267{{"PgClassExpression[267∈26] ➊<br />ᐸ__func_out....”column3”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression267
    PgClassExpression268{{"PgClassExpression[268∈26] ➊<br />ᐸ__func_out...med__.”o2”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression268
    PgSelect282[["PgSelect[282∈27] ➊<br />ᐸfunc_returns_table_multi_colᐳ"]]:::plan
    Object11 & Constant637 & Connection281 --> PgSelect282
    PgSelect287[["PgSelect[287∈27] ➊<br />ᐸfunc_returns_table_multi_col(aggregate)ᐳ"]]:::plan
    Object11 & Constant637 & Connection281 --> PgSelect287
    First288{{"First[288∈27] ➊"}}:::plan
    PgSelect287 --> First288
    PgSelectSingle289{{"PgSelectSingle[289∈27] ➊<br />ᐸfunc_returns_table_multi_colᐳ"}}:::plan
    First288 --> PgSelectSingle289
    PgClassExpression290{{"PgClassExpression[290∈27] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle289 --> PgClassExpression290
    __Item283[/"__Item[283∈28]<br />ᐸ282ᐳ"\]:::itemplan
    PgSelect282 ==> __Item283
    PgSelectSingle284{{"PgSelectSingle[284∈28]<br />ᐸfunc_returns_table_multi_colᐳ"}}:::plan
    __Item283 --> PgSelectSingle284
    PgClassExpression285{{"PgClassExpression[285∈29]<br />ᐸ__func_ret...l__.”col1”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression285
    PgClassExpression286{{"PgClassExpression[286∈29]<br />ᐸ__func_ret...l__.”col2”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression286
    PgSelect302[["PgSelect[302∈30] ➊<br />ᐸfunc_returns_table_one_colᐳ"]]:::plan
    Object11 & Constant637 & Connection301 --> PgSelect302
    PgSelect306[["PgSelect[306∈30] ➊<br />ᐸfunc_returns_table_one_col(aggregate)ᐳ"]]:::plan
    Object11 & Constant637 & Connection301 --> PgSelect306
    First307{{"First[307∈30] ➊"}}:::plan
    PgSelect306 --> First307
    PgSelectSingle308{{"PgSelectSingle[308∈30] ➊<br />ᐸfunc_returns_table_one_colᐳ"}}:::plan
    First307 --> PgSelectSingle308
    PgClassExpression309{{"PgClassExpression[309∈30] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle308 --> PgClassExpression309
    __Item303[/"__Item[303∈31]<br />ᐸ302ᐳ"\]:::itemplan
    PgSelect302 ==> __Item303
    PgSelectSingle304{{"PgSelectSingle[304∈31]<br />ᐸfunc_returns_table_one_colᐳ"}}:::plan
    __Item303 --> PgSelectSingle304
    PgClassExpression305{{"PgClassExpression[305∈31]<br />ᐸ__func_ret...ne_col__.vᐳ"}}:::plan
    PgSelectSingle304 --> PgClassExpression305
    List319{{"List[319∈32] ➊<br />ᐸ56,318ᐳ"}}:::plan
    PgClassExpression318{{"PgClassExpression[318∈32] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression318 --> List319
    PgSelectSingle316 --> PgClassExpression318
    Lambda320{{"Lambda[320∈32] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List319 --> Lambda320
    PgClassExpression322{{"PgClassExpression[322∈32] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle316 --> PgClassExpression322
    PgSelectSingle331{{"PgSelectSingle[331∈32] ➊<br />ᐸperson_computed_complexᐳ"}}:::plan
    RemapKeys593{{"RemapKeys[593∈32] ➊<br />ᐸ316:{”0”:2,”1”:3,”2”:4,”3”:5,”4”:6,”5”:7,”6”:8,”7”:9,”8”:10}ᐳ"}}:::plan
    RemapKeys593 --> PgSelectSingle331
    PgSelectSingle384{{"PgSelectSingle[384∈32] ➊<br />ᐸperson_computed_first_arg_inoutᐳ"}}:::plan
    RemapKeys595{{"RemapKeys[595∈32] ➊<br />ᐸ316:{”0”:11,”1”:12}ᐳ"}}:::plan
    RemapKeys595 --> PgSelectSingle384
    PgSelectSingle393{{"PgSelectSingle[393∈32] ➊<br />ᐸperson_computed_first_arg_inout_outᐳ"}}:::plan
    RemapKeys599{{"RemapKeys[599∈32] ➊<br />ᐸ316:{”0”:13,”1”:14,”2”:15,”3”:16}ᐳ"}}:::plan
    RemapKeys599 --> PgSelectSingle393
    PgClassExpression406{{"PgClassExpression[406∈32] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle316 --> PgClassExpression406
    PgSelectSingle414{{"PgSelectSingle[414∈32] ➊<br />ᐸperson_computed_inout_outᐳ"}}:::plan
    RemapKeys601{{"RemapKeys[601∈32] ➊<br />ᐸ316:{”0”:17,”1”:18,”2”:19}ᐳ"}}:::plan
    RemapKeys601 --> PgSelectSingle414
    PgClassExpression418{{"PgClassExpression[418∈32] ➊<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle316 --> PgClassExpression418
    PgSelectSingle425{{"PgSelectSingle[425∈32] ➊<br />ᐸperson_computed_out_outᐳ"}}:::plan
    RemapKeys603{{"RemapKeys[603∈32] ➊<br />ᐸ316:{”0”:20,”1”:21,”2”:22}ᐳ"}}:::plan
    RemapKeys603 --> PgSelectSingle425
    PgSelectSingle316 --> RemapKeys593
    PgSelectSingle316 --> RemapKeys595
    PgSelectSingle316 --> RemapKeys599
    PgSelectSingle316 --> RemapKeys601
    PgSelectSingle316 --> RemapKeys603
    Connection369{{"Connection[369∈32] ➊<br />ᐸ365ᐳ"}}:::plan
    PgClassExpression332{{"PgClassExpression[332∈33] ➊<br />ᐸ__person_c...plex__.”x”ᐳ"}}:::plan
    PgSelectSingle331 --> PgClassExpression332
    PgSelectSingle339{{"PgSelectSingle[339∈33] ➊<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    RemapKeys588{{"RemapKeys[588∈33] ➊<br />ᐸ331:{”0”:1,”1”:2,”2”:3,”3”:4}ᐳ"}}:::plan
    RemapKeys588 --> PgSelectSingle339
    PgSelectSingle349{{"PgSelectSingle[349∈33] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys591{{"RemapKeys[591∈33] ➊<br />ᐸ331:{”0”:5,”1”:6,”2”:7}ᐳ"}}:::plan
    RemapKeys591 --> PgSelectSingle349
    PgSelectSingle331 --> RemapKeys588
    PgSelectSingle331 --> RemapKeys591
    PgClassExpression340{{"PgClassExpression[340∈34] ➊<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle339 --> PgClassExpression340
    PgClassExpression341{{"PgClassExpression[341∈34] ➊<br />ᐸ__frmcdc_c...type__.”b”ᐳ"}}:::plan
    PgSelectSingle339 --> PgClassExpression341
    PgClassExpression342{{"PgClassExpression[342∈34] ➊<br />ᐸ__frmcdc_c...type__.”c”ᐳ"}}:::plan
    PgSelectSingle339 --> PgClassExpression342
    List352{{"List[352∈35] ➊<br />ᐸ56,351ᐳ"}}:::plan
    PgClassExpression351{{"PgClassExpression[351∈35] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant56 & PgClassExpression351 --> List352
    PgSelectSingle349 --> PgClassExpression351
    Lambda353{{"Lambda[353∈35] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List352 --> Lambda353
    PgClassExpression355{{"PgClassExpression[355∈35] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle349 --> PgClassExpression355
    Access590{{"Access[590∈35] ➊<br />ᐸ591.0ᐳ"}}:::plan
    RemapKeys591 --> Access590
    __Item371[/"__Item[371∈36]<br />ᐸ590ᐳ"\]:::itemplan
    Access590 ==> __Item371
    PgSelectSingle372{{"PgSelectSingle[372∈36]<br />ᐸpostᐳ"}}:::plan
    __Item371 --> PgSelectSingle372
    List375{{"List[375∈37]<br />ᐸ79,374ᐳ"}}:::plan
    PgClassExpression374{{"PgClassExpression[374∈37]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant79 & PgClassExpression374 --> List375
    PgSelectSingle372 --> PgClassExpression374
    Lambda376{{"Lambda[376∈37]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List375 --> Lambda376
    PgClassExpression385{{"PgClassExpression[385∈38] ➊<br />ᐸ__person_c...out__.”id”ᐳ"}}:::plan
    PgSelectSingle384 --> PgClassExpression385
    PgClassExpression386{{"PgClassExpression[386∈38] ➊<br />ᐸ__person_c...full_name”ᐳ"}}:::plan
    PgSelectSingle384 --> PgClassExpression386
    PgSelectSingle400{{"PgSelectSingle[400∈39] ➊<br />ᐸpersonᐳ"}}:::plan
    PgSelectSingle393 --> PgSelectSingle400
    PgClassExpression403{{"PgClassExpression[403∈39] ➊<br />ᐸ__person_c..._out__.”o”ᐳ"}}:::plan
    PgSelectSingle393 --> PgClassExpression403
    PgClassExpression401{{"PgClassExpression[401∈40] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle400 --> PgClassExpression401
    PgClassExpression402{{"PgClassExpression[402∈40] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle400 --> PgClassExpression402
    PgClassExpression415{{"PgClassExpression[415∈41] ➊<br />ᐸ__person_c...ut__.”ino”ᐳ"}}:::plan
    PgSelectSingle414 --> PgClassExpression415
    PgClassExpression416{{"PgClassExpression[416∈41] ➊<br />ᐸ__person_c..._out__.”o”ᐳ"}}:::plan
    PgSelectSingle414 --> PgClassExpression416
    PgClassExpression426{{"PgClassExpression[426∈42] ➊<br />ᐸ__person_c...out__.”o1”ᐳ"}}:::plan
    PgSelectSingle425 --> PgClassExpression426
    PgClassExpression427{{"PgClassExpression[427∈42] ➊<br />ᐸ__person_c...out__.”o2”ᐳ"}}:::plan
    PgSelectSingle425 --> PgClassExpression427
    PgSelectSingle443{{"PgSelectSingle[443∈43] ➊<br />ᐸleft_armᐳ"}}:::plan
    PgSelectSingle436 --> PgSelectSingle443
    PgSelectSingle477{{"PgSelectSingle[477∈43] ➊<br />ᐸpostᐳ"}}:::plan
    RemapKeys615{{"RemapKeys[615∈43] ➊<br />ᐸ436:{”0”:7,”1”:8,”2”:9,”3”:10,”4”:11,”5”:12}ᐳ"}}:::plan
    RemapKeys615 --> PgSelectSingle477
    PgClassExpression497{{"PgClassExpression[497∈43] ➊<br />ᐸ__query_ou...ws__.”txt”ᐳ"}}:::plan
    PgSelectSingle436 --> PgClassExpression497
    PgSelectSingle436 --> RemapKeys615
    PgClassExpression444{{"PgClassExpression[444∈44] ➊<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    PgSelectSingle443 --> PgClassExpression444
    PgClassExpression445{{"PgClassExpression[445∈44] ➊<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle443 --> PgClassExpression445
    PgClassExpression446{{"PgClassExpression[446∈44] ➊<br />ᐸ__left_arm__.”mood”ᐳ"}}:::plan
    PgSelectSingle443 --> PgClassExpression446
    PgClassExpression447{{"PgClassExpression[447∈44] ➊<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    PgSelectSingle443 --> PgClassExpression447
    PgSelectSingle453{{"PgSelectSingle[453∈44] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys607{{"RemapKeys[607∈44] ➊<br />ᐸ443:{”0”:3,”1”:4,”2”:5}ᐳ"}}:::plan
    RemapKeys607 --> PgSelectSingle453
    PgSelectSingle443 --> RemapKeys607
    PgClassExpression454{{"PgClassExpression[454∈45] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle453 --> PgClassExpression454
    PgSelectSingle461{{"PgSelectSingle[461∈45] ➊<br />ᐸperson_secretᐳ"}}:::plan
    RemapKeys605{{"RemapKeys[605∈45] ➊<br />ᐸ453:{”0”:1,”1”:2}ᐳ"}}:::plan
    RemapKeys605 --> PgSelectSingle461
    PgSelectSingle453 --> RemapKeys605
    PgClassExpression462{{"PgClassExpression[462∈46] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle461 --> PgClassExpression462
    PgClassExpression478{{"PgClassExpression[478∈47] ➊<br />ᐸ__post__.”id”ᐳ"}}:::plan
    PgSelectSingle477 --> PgClassExpression478
    PgClassExpression479{{"PgClassExpression[479∈47] ➊<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle477 --> PgClassExpression479
    PgClassExpression480{{"PgClassExpression[480∈47] ➊<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgSelectSingle477 --> PgClassExpression480
    PgSelectSingle487{{"PgSelectSingle[487∈47] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys613{{"RemapKeys[613∈47] ➊<br />ᐸ477:{”0”:2,”1”:3,”2”:4}ᐳ"}}:::plan
    RemapKeys613 --> PgSelectSingle487
    PgSelectSingle477 --> RemapKeys613
    PgClassExpression488{{"PgClassExpression[488∈48] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle487 --> PgClassExpression488
    PgSelectSingle495{{"PgSelectSingle[495∈48] ➊<br />ᐸperson_secretᐳ"}}:::plan
    RemapKeys611{{"RemapKeys[611∈48] ➊<br />ᐸ487:{”0”:1,”1”:2}ᐳ"}}:::plan
    RemapKeys611 --> PgSelectSingle495
    PgSelectSingle487 --> RemapKeys611
    PgClassExpression496{{"PgClassExpression[496∈49] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle495 --> PgClassExpression496
    PgSelectSingle513{{"PgSelectSingle[513∈50] ➊<br />ᐸleft_armᐳ"}}:::plan
    PgSelectSingle506 --> PgSelectSingle513
    PgSelectSingle547{{"PgSelectSingle[547∈50] ➊<br />ᐸpostᐳ"}}:::plan
    RemapKeys627{{"RemapKeys[627∈50] ➊<br />ᐸ506:{”0”:7,”1”:8,”2”:9,”3”:10,”4”:11,”5”:12}ᐳ"}}:::plan
    RemapKeys627 --> PgSelectSingle547
    PgClassExpression567{{"PgClassExpression[567∈50] ➊<br />ᐸ__query_ou...ws__.”txt”ᐳ"}}:::plan
    PgSelectSingle506 --> PgClassExpression567
    PgSelectSingle506 --> RemapKeys627
    PgClassExpression514{{"PgClassExpression[514∈51] ➊<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    PgSelectSingle513 --> PgClassExpression514
    PgClassExpression515{{"PgClassExpression[515∈51] ➊<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle513 --> PgClassExpression515
    PgClassExpression516{{"PgClassExpression[516∈51] ➊<br />ᐸ__left_arm__.”mood”ᐳ"}}:::plan
    PgSelectSingle513 --> PgClassExpression516
    PgClassExpression517{{"PgClassExpression[517∈51] ➊<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    PgSelectSingle513 --> PgClassExpression517
    PgSelectSingle523{{"PgSelectSingle[523∈51] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys619{{"RemapKeys[619∈51] ➊<br />ᐸ513:{”0”:3,”1”:4,”2”:5}ᐳ"}}:::plan
    RemapKeys619 --> PgSelectSingle523
    PgSelectSingle513 --> RemapKeys619
    PgClassExpression524{{"PgClassExpression[524∈52] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle523 --> PgClassExpression524
    PgSelectSingle531{{"PgSelectSingle[531∈52] ➊<br />ᐸperson_secretᐳ"}}:::plan
    RemapKeys617{{"RemapKeys[617∈52] ➊<br />ᐸ523:{”0”:1,”1”:2}ᐳ"}}:::plan
    RemapKeys617 --> PgSelectSingle531
    PgSelectSingle523 --> RemapKeys617
    PgClassExpression532{{"PgClassExpression[532∈53] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle531 --> PgClassExpression532
    PgClassExpression548{{"PgClassExpression[548∈54] ➊<br />ᐸ__post__.”id”ᐳ"}}:::plan
    PgSelectSingle547 --> PgClassExpression548
    PgClassExpression549{{"PgClassExpression[549∈54] ➊<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle547 --> PgClassExpression549
    PgClassExpression550{{"PgClassExpression[550∈54] ➊<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgSelectSingle547 --> PgClassExpression550
    PgSelectSingle557{{"PgSelectSingle[557∈54] ➊<br />ᐸpersonᐳ"}}:::plan
    RemapKeys625{{"RemapKeys[625∈54] ➊<br />ᐸ547:{”0”:2,”1”:3,”2”:4}ᐳ"}}:::plan
    RemapKeys625 --> PgSelectSingle557
    PgSelectSingle547 --> RemapKeys625
    PgClassExpression558{{"PgClassExpression[558∈55] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle557 --> PgClassExpression558
    PgSelectSingle565{{"PgSelectSingle[565∈55] ➊<br />ᐸperson_secretᐳ"}}:::plan
    RemapKeys623{{"RemapKeys[623∈55] ➊<br />ᐸ557:{”0”:1,”1”:2}ᐳ"}}:::plan
    RemapKeys623 --> PgSelectSingle565
    PgSelectSingle557 --> RemapKeys623
    PgClassExpression566{{"PgClassExpression[566∈56] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle565 --> PgClassExpression566
    __Item574[/"__Item[574∈57]<br />ᐸ570ᐳ"\]:::itemplan
    PgSelect570 ==> __Item574
    PgSelectSingle575{{"PgSelectSingle[575∈57]<br />ᐸsearch_test_summariesᐳ"}}:::plan
    __Item574 --> PgSelectSingle575
    PgClassExpression576{{"PgClassExpression[576∈58]<br />ᐸ__search_t...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle575 --> PgClassExpression576
    PgClassExpression577{{"PgClassExpression[577∈58]<br />ᐸ__search_t..._duration”ᐳ"}}:::plan
    PgSelectSingle575 --> PgClassExpression577

    %% define steps

    subgraph "Buckets for queries/v4/function-return-types"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 9, 10, 56, 79, 95, 184, 211, 240, 281, 301, 629, 630, 632, 633, 637, 644, 646, 647, 649, 11<br />2: 8, 16, 23, 32, 149, 158, 194, 220, 253, 260, 311, 431, 501, 570<br />ᐳ: 12, 13, 14, 20, 21, 22, 27, 28, 29, 36, 37, 153, 154, 162, 163, 198, 199, 224, 225, 257, 258, 259, 264, 265, 315, 316, 435, 436, 505, 506"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect8,Access9,Access10,Object11,First12,PgSelectSingle13,PgClassExpression14,PgSelect16,First20,PgSelectSingle21,PgClassExpression22,PgSelect23,First27,PgSelectSingle28,PgClassExpression29,PgSelect32,First36,PgSelectSingle37,Constant56,Constant79,Connection95,PgSelect149,First153,PgSelectSingle154,PgSelect158,First162,PgSelectSingle163,Connection184,PgSelect194,First198,PgSelectSingle199,Connection211,PgSelect220,First224,PgSelectSingle225,Connection240,PgSelect253,First257,PgSelectSingle258,PgClassExpression259,PgSelect260,First264,PgSelectSingle265,Connection281,Connection301,PgSelect311,First315,PgSelectSingle316,PgSelect431,First435,PgSelectSingle436,PgSelect501,First505,PgSelectSingle506,PgSelect570,Constant629,Constant630,Constant632,Constant633,Constant637,Constant644,Constant646,Constant647,Constant649 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 37, 56, 79<br /><br />ROOT PgSelectSingleᐸfunc_out_complexᐳ[37]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression38,PgSelectSingle45,PgSelectSingle55,Connection75,RemapKeys580,RemapKeys583 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 45<br /><br />ROOT PgSelectSingle{1}ᐸfrmcdc_compoundTypeᐳ[45]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression46,PgClassExpression47,PgClassExpression48 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 55, 56, 583, 79, 75<br /><br />ROOT PgSelectSingle{1}ᐸpersonᐳ[55]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression57,List58,Lambda59,PgClassExpression61,Access582 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 79<br /><br />ROOT __Item{4}ᐸ582ᐳ[77]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item77,PgSelectSingle78 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 78, 79<br /><br />ROOT PgSelectSingle{4}ᐸpostᐳ[78]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression80,List81,Lambda82 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 11, 632, 633, 95, 56, 79<br /><br />ROOT Connectionᐸ91ᐳ[95]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect96,Connection136,PgSelect145,First146,PgSelectSingle147,PgClassExpression148 bucket6
    Bucket7("Bucket 7 (listItem)<br />Deps: 11, 56, 79, 136<br /><br />ROOT __Item{7}ᐸ96ᐳ[97]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,__Item97,PgSelectSingle98 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 98, 11, 56, 79, 136<br /><br />ROOT PgSelectSingle{7}ᐸfunc_out_complex_setofᐳ[98]<br />1: <br />ᐳ: 99, 100, 110<br />2: PgSelect[101], PgSelect[111]<br />ᐳ: 105, 106, 115, 116"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression99,PgClassExpression100,PgSelect101,First105,PgSelectSingle106,PgClassExpression110,PgSelect111,First115,PgSelectSingle116 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 106<br /><br />ROOT PgSelectSingle{8}ᐸfrmcdc_compoundTypeᐳ[106]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression107,PgClassExpression108,PgClassExpression109 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 116, 56, 115, 79, 136<br /><br />ROOT PgSelectSingle{8}ᐸpersonᐳ[116]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression118,List119,Lambda120,PgClassExpression122,Access585 bucket10
    Bucket11("Bucket 11 (listItem)<br />Deps: 79<br /><br />ROOT __Item{11}ᐸ585ᐳ[138]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Item138,PgSelectSingle139 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 139, 79<br /><br />ROOT PgSelectSingle{11}ᐸpostᐳ[139]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression141,List142,Lambda143 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 154<br /><br />ROOT PgSelectSingleᐸfunc_out_outᐳ[154]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression155,PgClassExpression156 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 163<br /><br />ROOT PgSelectSingleᐸfunc_out_out_compound_typeᐳ[163]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression164,PgSelectSingle171,RemapKeys586 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 171<br /><br />ROOT PgSelectSingle{14}ᐸfrmcdc_compoundTypeᐳ[171]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression172,PgClassExpression173,PgClassExpression174 bucket15
    Bucket16("Bucket 16 (nullableBoundary)<br />Deps: 11, 184<br /><br />ROOT Connectionᐸ180ᐳ[184]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect185,PgSelect190,First191,PgSelectSingle192,PgClassExpression193 bucket16
    Bucket17("Bucket 17 (listItem)<br /><br />ROOT __Item{17}ᐸ185ᐳ[186]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,__Item186,PgSelectSingle187 bucket17
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 187<br /><br />ROOT PgSelectSingle{17}ᐸfunc_out_out_setofᐳ[187]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgClassExpression188,PgClassExpression189 bucket18
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 199<br /><br />ROOT PgSelectSingleᐸfunc_out_out_unnamedᐳ[199]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgClassExpression200,PgClassExpression201 bucket19
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 11, 211<br /><br />ROOT Connectionᐸ207ᐳ[211]"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgSelect212,PgSelect216,First217,PgSelectSingle218,PgClassExpression219 bucket20
    Bucket21("Bucket 21 (listItem)<br /><br />ROOT __Item{21}ᐸ212ᐳ[213]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item213,PgSelectSingle214,PgClassExpression215 bucket21
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 225, 56<br /><br />ROOT PgSelectSingleᐸfunc_out_tableᐳ[225]"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgClassExpression227,List228,Lambda229 bucket22
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 11, 240, 56<br /><br />ROOT Connectionᐸ236ᐳ[240]"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgSelect241,PgSelect249,First250,PgSelectSingle251,PgClassExpression252 bucket23
    Bucket24("Bucket 24 (listItem)<br />Deps: 56<br /><br />ROOT __Item{24}ᐸ241ᐳ[242]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24,__Item242,PgSelectSingle243 bucket24
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 243, 56<br /><br />ROOT PgSelectSingle{24}ᐸfunc_out_table_setofᐳ[243]"):::bucket
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgClassExpression245,List246,Lambda247 bucket25
    Bucket26("Bucket 26 (nullableBoundary)<br />Deps: 265<br /><br />ROOT PgSelectSingleᐸfunc_out_unnamed_out_out_unnamedᐳ[265]"):::bucket
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgClassExpression266,PgClassExpression267,PgClassExpression268 bucket26
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 11, 637, 281<br /><br />ROOT Connectionᐸ277ᐳ[281]"):::bucket
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgSelect282,PgSelect287,First288,PgSelectSingle289,PgClassExpression290 bucket27
    Bucket28("Bucket 28 (listItem)<br /><br />ROOT __Item{28}ᐸ282ᐳ[283]"):::bucket
    classDef bucket28 stroke:#00ffff
    class Bucket28,__Item283,PgSelectSingle284 bucket28
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 284<br /><br />ROOT PgSelectSingle{28}ᐸfunc_returns_table_multi_colᐳ[284]"):::bucket
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression285,PgClassExpression286 bucket29
    Bucket30("Bucket 30 (nullableBoundary)<br />Deps: 11, 637, 301<br /><br />ROOT Connectionᐸ297ᐳ[301]"):::bucket
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgSelect302,PgSelect306,First307,PgSelectSingle308,PgClassExpression309 bucket30
    Bucket31("Bucket 31 (listItem)<br /><br />ROOT __Item{31}ᐸ302ᐳ[303]"):::bucket
    classDef bucket31 stroke:#a52a2a
    class Bucket31,__Item303,PgSelectSingle304,PgClassExpression305 bucket31
    Bucket32("Bucket 32 (nullableBoundary)<br />Deps: 316, 56, 79<br /><br />ROOT PgSelectSingleᐸpersonᐳ[316]"):::bucket
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgClassExpression318,List319,Lambda320,PgClassExpression322,PgSelectSingle331,Connection369,PgSelectSingle384,PgSelectSingle393,PgClassExpression406,PgSelectSingle414,PgClassExpression418,PgSelectSingle425,RemapKeys593,RemapKeys595,RemapKeys599,RemapKeys601,RemapKeys603 bucket32
    Bucket33("Bucket 33 (nullableBoundary)<br />Deps: 331, 56, 79, 369<br /><br />ROOT PgSelectSingle{32}ᐸperson_computed_complexᐳ[331]"):::bucket
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgClassExpression332,PgSelectSingle339,PgSelectSingle349,RemapKeys588,RemapKeys591 bucket33
    Bucket34("Bucket 34 (nullableBoundary)<br />Deps: 339<br /><br />ROOT PgSelectSingle{33}ᐸfrmcdc_compoundTypeᐳ[339]"):::bucket
    classDef bucket34 stroke:#696969
    class Bucket34,PgClassExpression340,PgClassExpression341,PgClassExpression342 bucket34
    Bucket35("Bucket 35 (nullableBoundary)<br />Deps: 349, 56, 591, 79, 369<br /><br />ROOT PgSelectSingle{33}ᐸpersonᐳ[349]"):::bucket
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgClassExpression351,List352,Lambda353,PgClassExpression355,Access590 bucket35
    Bucket36("Bucket 36 (listItem)<br />Deps: 79<br /><br />ROOT __Item{36}ᐸ590ᐳ[371]"):::bucket
    classDef bucket36 stroke:#7f007f
    class Bucket36,__Item371,PgSelectSingle372 bucket36
    Bucket37("Bucket 37 (nullableBoundary)<br />Deps: 372, 79<br /><br />ROOT PgSelectSingle{36}ᐸpostᐳ[372]"):::bucket
    classDef bucket37 stroke:#ffa500
    class Bucket37,PgClassExpression374,List375,Lambda376 bucket37
    Bucket38("Bucket 38 (nullableBoundary)<br />Deps: 384<br /><br />ROOT PgSelectSingle{32}ᐸperson_computed_first_arg_inoutᐳ[384]"):::bucket
    classDef bucket38 stroke:#0000ff
    class Bucket38,PgClassExpression385,PgClassExpression386 bucket38
    Bucket39("Bucket 39 (nullableBoundary)<br />Deps: 393<br /><br />ROOT PgSelectSingle{32}ᐸperson_computed_first_arg_inout_outᐳ[393]"):::bucket
    classDef bucket39 stroke:#7fff00
    class Bucket39,PgSelectSingle400,PgClassExpression403 bucket39
    Bucket40("Bucket 40 (nullableBoundary)<br />Deps: 400<br /><br />ROOT PgSelectSingle{39}ᐸpersonᐳ[400]"):::bucket
    classDef bucket40 stroke:#ff1493
    class Bucket40,PgClassExpression401,PgClassExpression402 bucket40
    Bucket41("Bucket 41 (nullableBoundary)<br />Deps: 414<br /><br />ROOT PgSelectSingle{32}ᐸperson_computed_inout_outᐳ[414]"):::bucket
    classDef bucket41 stroke:#808000
    class Bucket41,PgClassExpression415,PgClassExpression416 bucket41
    Bucket42("Bucket 42 (nullableBoundary)<br />Deps: 425<br /><br />ROOT PgSelectSingle{32}ᐸperson_computed_out_outᐳ[425]"):::bucket
    classDef bucket42 stroke:#dda0dd
    class Bucket42,PgClassExpression426,PgClassExpression427 bucket42
    Bucket43("Bucket 43 (nullableBoundary)<br />Deps: 436<br /><br />ROOT PgSelectSingleᐸquery_output_two_rowsᐳ[436]"):::bucket
    classDef bucket43 stroke:#ff0000
    class Bucket43,PgSelectSingle443,PgSelectSingle477,PgClassExpression497,RemapKeys615 bucket43
    Bucket44("Bucket 44 (nullableBoundary)<br />Deps: 443<br /><br />ROOT PgSelectSingle{43}ᐸleft_armᐳ[443]"):::bucket
    classDef bucket44 stroke:#ffff00
    class Bucket44,PgClassExpression444,PgClassExpression445,PgClassExpression446,PgClassExpression447,PgSelectSingle453,RemapKeys607 bucket44
    Bucket45("Bucket 45 (nullableBoundary)<br />Deps: 453<br /><br />ROOT PgSelectSingle{44}ᐸpersonᐳ[453]"):::bucket
    classDef bucket45 stroke:#00ffff
    class Bucket45,PgClassExpression454,PgSelectSingle461,RemapKeys605 bucket45
    Bucket46("Bucket 46 (nullableBoundary)<br />Deps: 461<br /><br />ROOT PgSelectSingle{45}ᐸperson_secretᐳ[461]"):::bucket
    classDef bucket46 stroke:#4169e1
    class Bucket46,PgClassExpression462 bucket46
    Bucket47("Bucket 47 (nullableBoundary)<br />Deps: 477<br /><br />ROOT PgSelectSingle{43}ᐸpostᐳ[477]"):::bucket
    classDef bucket47 stroke:#3cb371
    class Bucket47,PgClassExpression478,PgClassExpression479,PgClassExpression480,PgSelectSingle487,RemapKeys613 bucket47
    Bucket48("Bucket 48 (nullableBoundary)<br />Deps: 487<br /><br />ROOT PgSelectSingle{47}ᐸpersonᐳ[487]"):::bucket
    classDef bucket48 stroke:#a52a2a
    class Bucket48,PgClassExpression488,PgSelectSingle495,RemapKeys611 bucket48
    Bucket49("Bucket 49 (nullableBoundary)<br />Deps: 495<br /><br />ROOT PgSelectSingle{48}ᐸperson_secretᐳ[495]"):::bucket
    classDef bucket49 stroke:#ff00ff
    class Bucket49,PgClassExpression496 bucket49
    Bucket50("Bucket 50 (nullableBoundary)<br />Deps: 506<br /><br />ROOT PgSelectSingleᐸquery_output_two_rowsᐳ[506]"):::bucket
    classDef bucket50 stroke:#f5deb3
    class Bucket50,PgSelectSingle513,PgSelectSingle547,PgClassExpression567,RemapKeys627 bucket50
    Bucket51("Bucket 51 (nullableBoundary)<br />Deps: 513<br /><br />ROOT PgSelectSingle{50}ᐸleft_armᐳ[513]"):::bucket
    classDef bucket51 stroke:#696969
    class Bucket51,PgClassExpression514,PgClassExpression515,PgClassExpression516,PgClassExpression517,PgSelectSingle523,RemapKeys619 bucket51
    Bucket52("Bucket 52 (nullableBoundary)<br />Deps: 523<br /><br />ROOT PgSelectSingle{51}ᐸpersonᐳ[523]"):::bucket
    classDef bucket52 stroke:#00bfff
    class Bucket52,PgClassExpression524,PgSelectSingle531,RemapKeys617 bucket52
    Bucket53("Bucket 53 (nullableBoundary)<br />Deps: 531<br /><br />ROOT PgSelectSingle{52}ᐸperson_secretᐳ[531]"):::bucket
    classDef bucket53 stroke:#7f007f
    class Bucket53,PgClassExpression532 bucket53
    Bucket54("Bucket 54 (nullableBoundary)<br />Deps: 547<br /><br />ROOT PgSelectSingle{50}ᐸpostᐳ[547]"):::bucket
    classDef bucket54 stroke:#ffa500
    class Bucket54,PgClassExpression548,PgClassExpression549,PgClassExpression550,PgSelectSingle557,RemapKeys625 bucket54
    Bucket55("Bucket 55 (nullableBoundary)<br />Deps: 557<br /><br />ROOT PgSelectSingle{54}ᐸpersonᐳ[557]"):::bucket
    classDef bucket55 stroke:#0000ff
    class Bucket55,PgClassExpression558,PgSelectSingle565,RemapKeys623 bucket55
    Bucket56("Bucket 56 (nullableBoundary)<br />Deps: 565<br /><br />ROOT PgSelectSingle{55}ᐸperson_secretᐳ[565]"):::bucket
    classDef bucket56 stroke:#7fff00
    class Bucket56,PgClassExpression566 bucket56
    Bucket57("Bucket 57 (listItem)<br /><br />ROOT __Item{57}ᐸ570ᐳ[574]"):::bucket
    classDef bucket57 stroke:#ff1493
    class Bucket57,__Item574,PgSelectSingle575 bucket57
    Bucket58("Bucket 58 (nullableBoundary)<br />Deps: 575<br /><br />ROOT PgSelectSingle{57}ᐸsearch_test_summariesᐳ[575]"):::bucket
    classDef bucket58 stroke:#808000
    class Bucket58,PgClassExpression576,PgClassExpression577 bucket58
    Bucket59("Bucket 59 (nullableBoundary)<br />Deps: 577<br /><br />ROOT PgClassExpression{58}ᐸ__search_t..._duration”ᐳ[577]"):::bucket
    classDef bucket59 stroke:#dda0dd
    class Bucket59 bucket59
    Bucket0 --> Bucket1 & Bucket6 & Bucket13 & Bucket14 & Bucket16 & Bucket19 & Bucket20 & Bucket22 & Bucket23 & Bucket26 & Bucket27 & Bucket30 & Bucket32 & Bucket43 & Bucket50 & Bucket57
    Bucket1 --> Bucket2 & Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket6 --> Bucket7
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9 & Bucket10
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12
    Bucket14 --> Bucket15
    Bucket16 --> Bucket17
    Bucket17 --> Bucket18
    Bucket20 --> Bucket21
    Bucket23 --> Bucket24
    Bucket24 --> Bucket25
    Bucket27 --> Bucket28
    Bucket28 --> Bucket29
    Bucket30 --> Bucket31
    Bucket32 --> Bucket33 & Bucket38 & Bucket39 & Bucket41 & Bucket42
    Bucket33 --> Bucket34 & Bucket35
    Bucket35 --> Bucket36
    Bucket36 --> Bucket37
    Bucket39 --> Bucket40
    Bucket43 --> Bucket44 & Bucket47
    Bucket44 --> Bucket45
    Bucket45 --> Bucket46
    Bucket47 --> Bucket48
    Bucket48 --> Bucket49
    Bucket50 --> Bucket51 & Bucket54
    Bucket51 --> Bucket52
    Bucket52 --> Bucket53
    Bucket54 --> Bucket55
    Bucket55 --> Bucket56
    Bucket57 --> Bucket58
    Bucket58 --> Bucket59
    end
