%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% define steps
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    Access64{{"Access[64∈1]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access65{{"Access[65∈1]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Object66{{"Object[66∈1]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Connection67{{"Connection[67∈0]<br />ᐸ63ᐳ"}}:::plan
    PgSelect68[["PgSelect[68∈1]<br />ᐸgeomᐳ"]]:::plan
    __Item69[/"__Item[69∈2]<br />ᐸ68ᐳ"\]:::itemplan
    PgSelectSingle70{{"PgSelectSingle[70∈2]<br />ᐸgeomᐳ"}}:::plan
    PgClassExpression71{{"PgClassExpression[71∈3]<br />ᐸ__geom__.”id”ᐳ"}}:::plan
    PgClassExpression72{{"PgClassExpression[72∈3]<br />ᐸ__geom__.”point”ᐳ"}}:::plan
    PgClassExpression75{{"PgClassExpression[75∈3]<br />ᐸ__geom__.”line”ᐳ"}}:::plan
    PgClassExpression82{{"PgClassExpression[82∈3]<br />ᐸ__geom__.”lseg”ᐳ"}}:::plan
    PgClassExpression89{{"PgClassExpression[89∈3]<br />ᐸ__geom__.”box”ᐳ"}}:::plan
    PgClassExpression96{{"PgClassExpression[96∈3]<br />ᐸ__geom__.”open_path”ᐳ"}}:::plan
    Access98{{"Access[98∈8]<br />ᐸ96.pointsᐳ"}}:::plan
    __Item99[/"__Item[99∈9]<br />ᐸ98ᐳ"\]:::itemplan
    PgClassExpression102{{"PgClassExpression[102∈3]<br />ᐸ__geom__.”closed_path”ᐳ"}}:::plan
    Access104{{"Access[104∈10]<br />ᐸ102.pointsᐳ"}}:::plan
    __Item105[/"__Item[105∈11]<br />ᐸ104ᐳ"\]:::itemplan
    PgClassExpression108{{"PgClassExpression[108∈3]<br />ᐸ__geom__.”polygon”ᐳ"}}:::plan
    Access109{{"Access[109∈12]<br />ᐸ108.pointsᐳ"}}:::plan
    __Item110[/"__Item[110∈13]<br />ᐸ109ᐳ"\]:::itemplan
    PgClassExpression113{{"PgClassExpression[113∈3]<br />ᐸ__geom__.”circle”ᐳ"}}:::plan

    %% plan dependencies
    __Value3 --> Access64
    __Value3 --> Access65
    Access64 & Access65 --> Object66
    Object66 & Connection67 --> PgSelect68
    PgSelect68 ==> __Item69
    __Item69 --> PgSelectSingle70
    PgSelectSingle70 --> PgClassExpression71
    PgSelectSingle70 --> PgClassExpression72
    PgSelectSingle70 --> PgClassExpression75
    PgSelectSingle70 --> PgClassExpression82
    PgSelectSingle70 --> PgClassExpression89
    PgSelectSingle70 --> PgClassExpression96
    PgClassExpression96 --> Access98
    Access98 ==> __Item99
    PgSelectSingle70 --> PgClassExpression102
    PgClassExpression102 --> Access104
    Access104 ==> __Item105
    PgSelectSingle70 --> PgClassExpression108
    PgClassExpression108 --> Access109
    Access109 ==> __Item110
    PgSelectSingle70 --> PgClassExpression113

    subgraph "Buckets for queries/v4/geometry.queries"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value3,__Value5,Connection67 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 3, 67<br /><br />ROOT Connectionᐸ63ᐳ[67]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Access64,Access65,Object66,PgSelect68 bucket1
    Bucket2("Bucket 2 (listItem)<br />ROOT __Item{2}ᐸ68ᐳ[69]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item69,PgSelectSingle70 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 70<br /><br />ROOT PgSelectSingle{2}ᐸgeomᐳ[70]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression71,PgClassExpression72,PgClassExpression75,PgClassExpression82,PgClassExpression89,PgClassExpression96,PgClassExpression102,PgClassExpression108,PgClassExpression113 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 72<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”point”ᐳ[72]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 75<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”line”ᐳ[75]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 82<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”lseg”ᐳ[82]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 89<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”box”ᐳ[89]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 96<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”open_path”ᐳ[96]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,Access98 bucket8
    Bucket9("Bucket 9 (listItem)<br />ROOT __Item{9}ᐸ98ᐳ[99]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,__Item99 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 102<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”closed_path”ᐳ[102]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,Access104 bucket10
    Bucket11("Bucket 11 (listItem)<br />ROOT __Item{11}ᐸ104ᐳ[105]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Item105 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 108<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”polygon”ᐳ[108]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,Access109 bucket12
    Bucket13("Bucket 13 (listItem)<br />ROOT __Item{13}ᐸ109ᐳ[110]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item110 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 113<br /><br />ROOT PgClassExpression{3}ᐸ__geom__.”circle”ᐳ[113]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14 bucket14
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket10 & Bucket12 & Bucket14
    Bucket8 --> Bucket9
    Bucket10 --> Bucket11
    Bucket12 --> Bucket13
    end
