%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object16{{"Object[16∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access14{{"Access[14∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access15{{"Access[15∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access14 & Access15 --> Object16
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access14
    __Value2 --> Access15
    Connection17{{"Connection[17∈0] ➊<br />ᐸ13ᐳ"}}:::plan
    Constant47{{"Constant[47∈0] ➊<br />ᐸ50ᐳ"}}:::plan
    Constant47 --> Connection17
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect18[["PgSelect[18∈1] ➊<br />ᐸsome_messages+1ᐳ"]]:::plan
    Constant46{{"Constant[46∈1] ➊<br />ᐸ'0d126c0c-9710-478c-9aee-0be34b250573'ᐳ"}}:::plan
    Object16 & Constant46 & Connection17 --> PgSelect18
    Object38{{"Object[38∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant8{{"Constant[8∈1] ➊<br />ᐸundefinedᐳ"}}:::plan
    Access37{{"Access[37∈1] ➊<br />ᐸ18.hasMoreᐳ"}}:::plan
    Constant47 & Constant8 & Access37 --> Object38
    PgPageInfo34{{"PgPageInfo[34∈1] ➊"}}:::plan
    Connection17 --> PgPageInfo34
    PgSelect18 --> Access37
    Lambda39{{"Lambda[39∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object38 --> Lambda39
    Last41{{"Last[41∈1] ➊"}}:::plan
    PgSelect18 --> Last41
    PgSelectSingle42{{"PgSelectSingle[42∈1] ➊<br />ᐸsome_messagesᐳ"}}:::plan
    Last41 --> PgSelectSingle42
    PgCursor43{{"PgCursor[43∈1] ➊"}}:::plan
    List45{{"List[45∈1] ➊<br />ᐸ44ᐳ"}}:::plan
    List45 --> PgCursor43
    PgClassExpression44{{"PgClassExpression[44∈1] ➊<br />ᐸrow_number...tion by 1)ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression44
    PgClassExpression44 --> List45
    __Item19[/"__Item[19∈2]<br />ᐸ18ᐳ"\]:::itemplan
    PgSelect18 ==> __Item19
    PgSelectSingle20{{"PgSelectSingle[20∈2]<br />ᐸsome_messagesᐳ"}}:::plan
    __Item19 --> PgSelectSingle20
    PgSelect25[["PgSelect[25∈3]<br />ᐸtest_userᐳ"]]:::plan
    PgClassExpression24{{"PgClassExpression[24∈3]<br />ᐸ__some_mes...t_user_id”ᐳ"}}:::plan
    Object16 & PgClassExpression24 --> PgSelect25
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__some_messages__.”id”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__some_mes....”message”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__some_mes...reated_at”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression23
    PgSelectSingle20 --> PgClassExpression24
    First29{{"First[29∈3]"}}:::plan
    PgSelect25 --> First29
    PgSelectSingle30{{"PgSelectSingle[30∈3]<br />ᐸtest_userᐳ"}}:::plan
    First29 --> PgSelectSingle30
    PgClassExpression31{{"PgClassExpression[31∈4]<br />ᐸ__test_user__.”id”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression31
    PgClassExpression32{{"PgClassExpression[32∈4]<br />ᐸ__test_user__.”name”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression32

    %% define steps

    subgraph "Buckets for queries/v4/issue2210"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access14,Access15,Object16,Connection17,Constant47 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 16, 17, 47<br /><br />ROOT Connectionᐸ13ᐳ[17]<br />1: <br />ᐳ: 8, 34, 46<br />2: PgSelect[18]<br />ᐳ: 37, 38, 39, 41, 42, 44, 45, 43"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Constant8,PgSelect18,PgPageInfo34,Access37,Object38,Lambda39,Last41,PgSelectSingle42,PgCursor43,PgClassExpression44,List45,Constant46 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 16<br /><br />ROOT __Item{2}ᐸ18ᐳ[19]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item19,PgSelectSingle20 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 20, 16<br /><br />ROOT PgSelectSingle{2}ᐸsome_messagesᐳ[20]<br />1: <br />ᐳ: 21, 22, 23, 24<br />2: PgSelect[25]<br />ᐳ: First[29], PgSelectSingle[30]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression21,PgClassExpression22,PgClassExpression23,PgClassExpression24,PgSelect25,First29,PgSelectSingle30 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 30<br /><br />ROOT PgSelectSingle{3}ᐸtest_userᐳ[30]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression31,PgClassExpression32 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
