%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/issue2210"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 16, 18, 20, 21, 62, 8<br /><br />ROOT Connectionᐸ12ᐳ[20]<br />1: PgSelect[23]<br />ᐳ: 26, 32, 34, 35, 41<br />2: PgSelectRows[27]<br />ᐳ: 38, 40, 43"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 16<br /><br />ROOT __Item{2}ᐸ27ᐳ[28]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 29, 16<br /><br />ROOT PgSelectSingle{2}ᐸsome_messagesᐳ[29]<br />1: <br />ᐳ: 44, 45, 46, 47<br />2: PgSelect[48]<br />3: PgSelectRows[56]<br />ᐳ: First[55], PgSelectSingle[58]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 58<br /><br />ROOT PgSelectSingle{3}ᐸtest_userᐳ[58]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4

    %% plan dependencies
    Object16{{"Object[16∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access15{{"Access[15∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access13 & Access15 --> Object16
    Connection20{{"Connection[20∈0] ➊<br />ᐸ12ᐳ"}}:::plan
    Constant62{{"Constant[62∈0] ➊<br />ᐸ50ᐳ"}}:::plan
    Lambda21{{"Lambda[21∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    Constant62 & Lambda21 --> Connection20
    Access9{{"Access[9∈0] ➊<br />ᐸ0.afterᐳ"}}:::plan
    __Value0["__Value[0∈0] ➊<br />ᐸvariableValuesᐳ"]:::plan
    __Value0 --> Access9
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access13
    __Value2 --> Access15
    PgFromExpression18{{"PgFromExpression[18∈0] ➊"}}:::plan
    Constant61{{"Constant[61∈0] ➊<br />ᐸ'0d126c0c-9710-478c-9aee-0be34b250573'ᐳ"}}:::plan
    Constant61 --> PgFromExpression18
    Access9 --> Lambda21
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect23[["PgSelect[23∈1] ➊<br />ᐸsome_messages+1ᐳ"]]:::plan
    Object16 & PgFromExpression18 & Connection20 & Lambda21 & Constant62 --> PgSelect23
    Object34{{"Object[34∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Access32{{"Access[32∈1] ➊<br />ᐸ23.hasMoreᐳ"}}:::plan
    Constant62 & Access32 --> Object34
    PgCursor43{{"PgCursor[43∈1] ➊"}}:::plan
    PgSelectSingle40{{"PgSelectSingle[40∈1] ➊<br />ᐸsome_messagesᐳ"}}:::plan
    Access41{{"Access[41∈1] ➊<br />ᐸ23.cursorDetailsᐳ"}}:::plan
    PgSelectSingle40 & Access41 --> PgCursor43
    PgPageInfo26{{"PgPageInfo[26∈1] ➊"}}:::plan
    Connection20 --> PgPageInfo26
    PgSelectRows27[["PgSelectRows[27∈1] ➊"]]:::plan
    PgSelect23 --> PgSelectRows27
    PgSelect23 --> Access32
    Lambda35{{"Lambda[35∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object34 --> Lambda35
    Last38{{"Last[38∈1] ➊"}}:::plan
    PgSelectRows27 --> Last38
    Last38 --> PgSelectSingle40
    PgSelect23 --> Access41
    __Item28[/"__Item[28∈2]<br />ᐸ27ᐳ"\]:::itemplan
    PgSelectRows27 ==> __Item28
    PgSelectSingle29{{"PgSelectSingle[29∈2]<br />ᐸsome_messagesᐳ"}}:::plan
    __Item28 --> PgSelectSingle29
    PgSelect48[["PgSelect[48∈3]<br />ᐸtest_userᐳ"]]:::plan
    PgClassExpression47{{"PgClassExpression[47∈3]<br />ᐸ__some_mes...t_user_id”ᐳ"}}:::plan
    Object16 & PgClassExpression47 --> PgSelect48
    PgClassExpression44{{"PgClassExpression[44∈3]<br />ᐸ__some_messages__.”id”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression44
    PgClassExpression45{{"PgClassExpression[45∈3]<br />ᐸ__some_mes....”message”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression45
    PgClassExpression46{{"PgClassExpression[46∈3]<br />ᐸ__some_mes...reated_at”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression46
    PgSelectSingle29 --> PgClassExpression47
    First55{{"First[55∈3]"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈3]"]]:::plan
    PgSelectRows56 --> First55
    PgSelect48 --> PgSelectRows56
    PgSelectSingle58{{"PgSelectSingle[58∈3]<br />ᐸtest_userᐳ"}}:::plan
    First55 --> PgSelectSingle58
    PgClassExpression59{{"PgClassExpression[59∈4]<br />ᐸ__test_user__.”id”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈4]<br />ᐸ__test_user__.”name”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression60

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value2,__Value4,Access9,Access13,Access15,Object16,PgFromExpression18,Connection20,Lambda21,Constant61,Constant62 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect23,PgPageInfo26,PgSelectRows27,Access32,Object34,Lambda35,Last38,PgSelectSingle40,Access41,PgCursor43 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item28,PgSelectSingle29 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression44,PgClassExpression45,PgClassExpression46,PgClassExpression47,PgSelect48,First55,PgSelectRows56,PgSelectSingle58 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression59,PgClassExpression60 bucket4

