%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect17[["PgSelect[17∈0] ➊<br />ᐸconstructorᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant137{{"Constant[137∈0] ➊<br />ᐸ'Copper Wire'ᐳ"}}:::plan
    Lambda110{{"Lambda[110∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Object10 & Constant137 & Lambda110 --> PgSelect17
    PgSelect24[["PgSelect[24∈0] ➊<br />ᐸconstructorᐳ"]]:::plan
    Constant138{{"Constant[138∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Object10 & Constant138 & Lambda110 --> PgSelect24
    PgSelect31[["PgSelect[31∈0] ➊<br />ᐸconstructorᐳ"]]:::plan
    Constant139{{"Constant[139∈0] ➊<br />ᐸ'Iron Mine'ᐳ"}}:::plan
    Object10 & Constant139 & Lambda110 --> PgSelect31
    PgSelect45[["PgSelect[45∈0] ➊<br />ᐸyieldᐳ"]]:::plan
    Constant140{{"Constant[140∈0] ➊<br />ᐸ'UK'ᐳ"}}:::plan
    Object10 & Constant140 & Lambda110 --> PgSelect45
    PgSelect52[["PgSelect[52∈0] ➊<br />ᐸyieldᐳ"]]:::plan
    Object10 & Constant138 & Lambda110 --> PgSelect52
    PgSelect66[["PgSelect[66∈0] ➊<br />ᐸ__proto__ᐳ"]]:::plan
    Constant141{{"Constant[141∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Object10 & Constant141 & Lambda110 --> PgSelect66
    PgSelect73[["PgSelect[73∈0] ➊<br />ᐸ__proto__ᐳ"]]:::plan
    Constant142{{"Constant[142∈0] ➊<br />ᐸ'VCS'ᐳ"}}:::plan
    Object10 & Constant142 & Lambda110 --> PgSelect73
    PgSelect87[["PgSelect[87∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Constant143{{"Constant[143∈0] ➊<br />ᐸ'10 am'ᐳ"}}:::plan
    Object10 & Constant143 & Lambda110 --> PgSelect87
    PgSelect94[["PgSelect[94∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Constant144{{"Constant[144∈0] ➊<br />ᐸ'flat'ᐳ"}}:::plan
    Object10 & Constant144 & Lambda110 --> PgSelect94
    PgSelect101[["PgSelect[101∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Constant145{{"Constant[145∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Object10 & Constant145 & Lambda110 --> PgSelect101
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸconstructorᐳ"]]:::plan
    Object10 & Lambda110 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect37[["PgSelect[37∈0] ➊<br />ᐸyieldᐳ"]]:::plan
    Object10 & Lambda110 --> PgSelect37
    PgSelect58[["PgSelect[58∈0] ➊<br />ᐸ__proto__ᐳ"]]:::plan
    Object10 & Lambda110 --> PgSelect58
    PgSelect79[["PgSelect[79∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Object10 & Lambda110 --> PgSelect79
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First19{{"First[19∈0] ➊"}}:::plan
    PgSelect17 --> First19
    PgSelectSingle20{{"PgSelectSingle[20∈0] ➊<br />ᐸconstructorᐳ"}}:::plan
    First19 --> PgSelectSingle20
    First26{{"First[26∈0] ➊"}}:::plan
    PgSelect24 --> First26
    PgSelectSingle27{{"PgSelectSingle[27∈0] ➊<br />ᐸconstructorᐳ"}}:::plan
    First26 --> PgSelectSingle27
    First33{{"First[33∈0] ➊"}}:::plan
    PgSelect31 --> First33
    PgSelectSingle34{{"PgSelectSingle[34∈0] ➊<br />ᐸconstructorᐳ"}}:::plan
    First33 --> PgSelectSingle34
    First47{{"First[47∈0] ➊"}}:::plan
    PgSelect45 --> First47
    PgSelectSingle48{{"PgSelectSingle[48∈0] ➊<br />ᐸyieldᐳ"}}:::plan
    First47 --> PgSelectSingle48
    First54{{"First[54∈0] ➊"}}:::plan
    PgSelect52 --> First54
    PgSelectSingle55{{"PgSelectSingle[55∈0] ➊<br />ᐸyieldᐳ"}}:::plan
    First54 --> PgSelectSingle55
    First68{{"First[68∈0] ➊"}}:::plan
    PgSelect66 --> First68
    PgSelectSingle69{{"PgSelectSingle[69∈0] ➊<br />ᐸ__proto__ᐳ"}}:::plan
    First68 --> PgSelectSingle69
    First75{{"First[75∈0] ➊"}}:::plan
    PgSelect73 --> First75
    PgSelectSingle76{{"PgSelectSingle[76∈0] ➊<br />ᐸ__proto__ᐳ"}}:::plan
    First75 --> PgSelectSingle76
    First89{{"First[89∈0] ➊"}}:::plan
    PgSelect87 --> First89
    PgSelectSingle90{{"PgSelectSingle[90∈0] ➊<br />ᐸnullᐳ"}}:::plan
    First89 --> PgSelectSingle90
    First96{{"First[96∈0] ➊"}}:::plan
    PgSelect94 --> First96
    PgSelectSingle97{{"PgSelectSingle[97∈0] ➊<br />ᐸnullᐳ"}}:::plan
    First96 --> PgSelectSingle97
    First103{{"First[103∈0] ➊"}}:::plan
    PgSelect101 --> First103
    PgSelectSingle104{{"PgSelectSingle[104∈0] ➊<br />ᐸnullᐳ"}}:::plan
    First103 --> PgSelectSingle104
    Constant146{{"Constant[146∈0] ➊<br />ᐸ§{ cursorLower: null, cursorUpper: null, first: null, last: ᐳ"}}:::plan
    Constant146 --> Lambda110
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item11[/"__Item[11∈1]<br />ᐸ7ᐳ"\]:::itemplan
    PgSelect7 ==> __Item11
    PgSelectSingle12{{"PgSelectSingle[12∈1]<br />ᐸconstructorᐳ"}}:::plan
    __Item11 --> PgSelectSingle12
    PgClassExpression13{{"PgClassExpression[13∈1]<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression13
    PgClassExpression14{{"PgClassExpression[14∈1]<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression14
    PgClassExpression15{{"PgClassExpression[15∈1]<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression15
    PgClassExpression21{{"PgClassExpression[21∈2] ➊<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈2] ➊<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression22
    PgClassExpression28{{"PgClassExpression[28∈3] ➊<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈3] ➊<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression29
    PgClassExpression35{{"PgClassExpression[35∈4] ➊<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression35
    PgClassExpression36{{"PgClassExpression[36∈4] ➊<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression36
    __Item39[/"__Item[39∈5]<br />ᐸ37ᐳ"\]:::itemplan
    PgSelect37 ==> __Item39
    PgSelectSingle40{{"PgSelectSingle[40∈5]<br />ᐸyieldᐳ"}}:::plan
    __Item39 --> PgSelectSingle40
    PgClassExpression41{{"PgClassExpression[41∈5]<br />ᐸ__yield__.”crop”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression41
    PgClassExpression42{{"PgClassExpression[42∈5]<br />ᐸ__yield__.”export”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression42
    PgClassExpression43{{"PgClassExpression[43∈5]<br />ᐸ__yield__.”id”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression43
    PgClassExpression49{{"PgClassExpression[49∈6] ➊<br />ᐸ__yield__.”crop”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    PgClassExpression50{{"PgClassExpression[50∈6] ➊<br />ᐸ__yield__.”id”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression50
    PgClassExpression56{{"PgClassExpression[56∈7] ➊<br />ᐸ__yield__.”crop”ᐳ"}}:::plan
    PgSelectSingle55 --> PgClassExpression56
    PgClassExpression57{{"PgClassExpression[57∈7] ➊<br />ᐸ__yield__.”export”ᐳ"}}:::plan
    PgSelectSingle55 --> PgClassExpression57
    __Item60[/"__Item[60∈8]<br />ᐸ58ᐳ"\]:::itemplan
    PgSelect58 ==> __Item60
    PgSelectSingle61{{"PgSelectSingle[61∈8]<br />ᐸ__proto__ᐳ"}}:::plan
    __Item60 --> PgSelectSingle61
    PgClassExpression62{{"PgClassExpression[62∈8]<br />ᐸ__proto__.”id”ᐳ"}}:::plan
    PgSelectSingle61 --> PgClassExpression62
    PgClassExpression63{{"PgClassExpression[63∈8]<br />ᐸ__proto__.”name”ᐳ"}}:::plan
    PgSelectSingle61 --> PgClassExpression63
    PgClassExpression64{{"PgClassExpression[64∈8]<br />ᐸ__proto__.”brand”ᐳ"}}:::plan
    PgSelectSingle61 --> PgClassExpression64
    PgClassExpression70{{"PgClassExpression[70∈9] ➊<br />ᐸ__proto__.”brand”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression70
    PgClassExpression71{{"PgClassExpression[71∈9] ➊<br />ᐸ__proto__.”name”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression71
    PgClassExpression77{{"PgClassExpression[77∈10] ➊<br />ᐸ__proto__.”brand”ᐳ"}}:::plan
    PgSelectSingle76 --> PgClassExpression77
    PgClassExpression78{{"PgClassExpression[78∈10] ➊<br />ᐸ__proto__.”id”ᐳ"}}:::plan
    PgSelectSingle76 --> PgClassExpression78
    __Item81[/"__Item[81∈11]<br />ᐸ79ᐳ"\]:::itemplan
    PgSelect79 ==> __Item81
    PgSelectSingle82{{"PgSelectSingle[82∈11]<br />ᐸnullᐳ"}}:::plan
    __Item81 --> PgSelectSingle82
    PgClassExpression83{{"PgClassExpression[83∈11]<br />ᐸ__null__.”break”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression83
    PgClassExpression84{{"PgClassExpression[84∈11]<br />ᐸ__null__.”...nProperty”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression84
    PgClassExpression85{{"PgClassExpression[85∈11]<br />ᐸ__null__.”id”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression85
    PgClassExpression91{{"PgClassExpression[91∈12] ➊<br />ᐸ__null__.”...nProperty”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression91
    PgClassExpression92{{"PgClassExpression[92∈12] ➊<br />ᐸ__null__.”id”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression92
    PgClassExpression98{{"PgClassExpression[98∈13] ➊<br />ᐸ__null__.”break”ᐳ"}}:::plan
    PgSelectSingle97 --> PgClassExpression98
    PgClassExpression99{{"PgClassExpression[99∈13] ➊<br />ᐸ__null__.”id”ᐳ"}}:::plan
    PgSelectSingle97 --> PgClassExpression99
    PgClassExpression105{{"PgClassExpression[105∈14] ➊<br />ᐸ__null__.”break”ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression105
    PgClassExpression106{{"PgClassExpression[106∈14] ➊<br />ᐸ__null__.”...nProperty”ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression106

    %% define steps

    subgraph "Buckets for queries/v4/js-reserved-table-names"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 10, 110<br />2: 7, 17, 24, 31, 37, 45, 52, 58, 66, 73, 79, 87, 94, 101<br />ᐳ: 19, 20, 26, 27, 33, 34, 47, 48, 54, 55, 68, 69, 75, 76, 89, 90, 96, 97, 103, 104"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,PgSelect17,First19,PgSelectSingle20,PgSelect24,First26,PgSelectSingle27,PgSelect31,First33,PgSelectSingle34,PgSelect37,PgSelect45,First47,PgSelectSingle48,PgSelect52,First54,PgSelectSingle55,PgSelect58,PgSelect66,First68,PgSelectSingle69,PgSelect73,First75,PgSelectSingle76,PgSelect79,PgSelect87,First89,PgSelectSingle90,PgSelect94,First96,PgSelectSingle97,PgSelect101,First103,PgSelectSingle104,Lambda110,Constant137,Constant138,Constant139,Constant140,Constant141,Constant142,Constant143,Constant144,Constant145,Constant146 bucket0
    Bucket1("Bucket 1 (listItem)<br /><br />ROOT __Item{1}ᐸ7ᐳ[11]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item11,PgSelectSingle12,PgClassExpression13,PgClassExpression14,PgClassExpression15 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 20<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression21,PgClassExpression22 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 27<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[27]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression28,PgClassExpression29 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 34<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[34]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression35,PgClassExpression36 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ37ᐳ[39]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item39,PgSelectSingle40,PgClassExpression41,PgClassExpression42,PgClassExpression43 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 48<br /><br />ROOT PgSelectSingleᐸyieldᐳ[48]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression49,PgClassExpression50 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 55<br /><br />ROOT PgSelectSingleᐸyieldᐳ[55]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression56,PgClassExpression57 bucket7
    Bucket8("Bucket 8 (listItem)<br /><br />ROOT __Item{8}ᐸ58ᐳ[60]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item60,PgSelectSingle61,PgClassExpression62,PgClassExpression63,PgClassExpression64 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 69<br /><br />ROOT PgSelectSingleᐸ__proto__ᐳ[69]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression70,PgClassExpression71 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 76<br /><br />ROOT PgSelectSingleᐸ__proto__ᐳ[76]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression77,PgClassExpression78 bucket10
    Bucket11("Bucket 11 (listItem)<br /><br />ROOT __Item{11}ᐸ79ᐳ[81]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Item81,PgSelectSingle82,PgClassExpression83,PgClassExpression84,PgClassExpression85 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 90<br /><br />ROOT PgSelectSingleᐸnullᐳ[90]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression91,PgClassExpression92 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 97<br /><br />ROOT PgSelectSingleᐸnullᐳ[97]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression98,PgClassExpression99 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 104<br /><br />ROOT PgSelectSingleᐸnullᐳ[104]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression105,PgClassExpression106 bucket14
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket9 & Bucket10 & Bucket11 & Bucket12 & Bucket13 & Bucket14
    end
