%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% define steps
    __Value0["__Value[0∈0]"]:::plan
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    Access12{{"Access[12∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Object14{{"Object[14∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelect11[["PgSelect[11∈0]<br />ᐸyieldᐳ"]]:::plan
    __Item15[/"__Item[15∈1]<br />ᐸ11ᐳ"\]:::itemplan
    PgSelectSingle16{{"PgSelectSingle[16∈1]<br />ᐸyieldᐳ"}}:::plan
    PgClassExpression17{{"PgClassExpression[17∈1]<br />ᐸ__yield__.”crop”ᐳ"}}:::plan
    PgClassExpression18{{"PgClassExpression[18∈1]<br />ᐸ__yield__.”export”ᐳ"}}:::plan
    PgClassExpression19{{"PgClassExpression[19∈1]<br />ᐸ__yield__.”id”ᐳ"}}:::plan
    PgSelect24[["PgSelect[24∈0]<br />ᐸconstructorᐳ"]]:::plan
    __Item28[/"__Item[28∈2]<br />ᐸ24ᐳ"\]:::itemplan
    PgSelectSingle29{{"PgSelectSingle[29∈2]<br />ᐸconstructorᐳ"}}:::plan
    PgClassExpression30{{"PgClassExpression[30∈2]<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    PgClassExpression31{{"PgClassExpression[31∈2]<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgClassExpression32{{"PgClassExpression[32∈2]<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    __InputStaticLeaf33{{"__InputStaticLeaf[33∈0]"}}:::plan
    PgSelect34[["PgSelect[34∈0]<br />ᐸconstructorᐳ"]]:::plan
    First38{{"First[38∈0]"}}:::plan
    PgSelectSingle39{{"PgSelectSingle[39∈0]<br />ᐸconstructorᐳ"}}:::plan
    PgClassExpression40{{"PgClassExpression[40∈3]<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgClassExpression41{{"PgClassExpression[41∈3]<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    __InputStaticLeaf42{{"__InputStaticLeaf[42∈0]"}}:::plan
    PgSelect43[["PgSelect[43∈0]<br />ᐸconstructorᐳ"]]:::plan
    First47{{"First[47∈0]"}}:::plan
    PgSelectSingle48{{"PgSelectSingle[48∈0]<br />ᐸconstructorᐳ"}}:::plan
    PgClassExpression49{{"PgClassExpression[49∈4]<br />ᐸ__constructor__.”name”ᐳ"}}:::plan
    PgClassExpression50{{"PgClassExpression[50∈4]<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    __InputStaticLeaf51{{"__InputStaticLeaf[51∈0]"}}:::plan
    PgSelect52[["PgSelect[52∈0]<br />ᐸconstructorᐳ"]]:::plan
    First56{{"First[56∈0]"}}:::plan
    PgSelectSingle57{{"PgSelectSingle[57∈0]<br />ᐸconstructorᐳ"}}:::plan
    PgClassExpression58{{"PgClassExpression[58∈5]<br />ᐸ__construc..._.”export”ᐳ"}}:::plan
    PgClassExpression59{{"PgClassExpression[59∈5]<br />ᐸ__constructor__.”id”ᐳ"}}:::plan
    __InputStaticLeaf60{{"__InputStaticLeaf[60∈0]"}}:::plan
    PgSelect61[["PgSelect[61∈0]<br />ᐸyieldᐳ"]]:::plan
    First65{{"First[65∈0]"}}:::plan
    PgSelectSingle66{{"PgSelectSingle[66∈0]<br />ᐸyieldᐳ"}}:::plan
    PgClassExpression67{{"PgClassExpression[67∈6]<br />ᐸ__yield__.”export”ᐳ"}}:::plan
    PgClassExpression68{{"PgClassExpression[68∈6]<br />ᐸ__yield__.”id”ᐳ"}}:::plan
    __InputStaticLeaf69{{"__InputStaticLeaf[69∈0]"}}:::plan
    PgSelect70[["PgSelect[70∈0]<br />ᐸyieldᐳ"]]:::plan
    First74{{"First[74∈0]"}}:::plan
    PgSelectSingle75{{"PgSelectSingle[75∈0]<br />ᐸyieldᐳ"}}:::plan
    PgClassExpression76{{"PgClassExpression[76∈7]<br />ᐸ__yield__.”crop”ᐳ"}}:::plan
    PgClassExpression77{{"PgClassExpression[77∈7]<br />ᐸ__yield__.”export”ᐳ"}}:::plan

    %% plan dependencies
    __Value3 --> Access12
    __Value3 --> Access13
    Access12 & Access13 --> Object14
    Object14 --> PgSelect11
    PgSelect11 ==> __Item15
    __Item15 --> PgSelectSingle16
    PgSelectSingle16 --> PgClassExpression17
    PgSelectSingle16 --> PgClassExpression18
    PgSelectSingle16 --> PgClassExpression19
    Object14 --> PgSelect24
    PgSelect24 ==> __Item28
    __Item28 --> PgSelectSingle29
    PgSelectSingle29 --> PgClassExpression30
    PgSelectSingle29 --> PgClassExpression31
    PgSelectSingle29 --> PgClassExpression32
    Object14 & __InputStaticLeaf33 --> PgSelect34
    PgSelect34 --> First38
    First38 --> PgSelectSingle39
    PgSelectSingle39 --> PgClassExpression40
    PgSelectSingle39 --> PgClassExpression41
    Object14 & __InputStaticLeaf42 --> PgSelect43
    PgSelect43 --> First47
    First47 --> PgSelectSingle48
    PgSelectSingle48 --> PgClassExpression49
    PgSelectSingle48 --> PgClassExpression50
    Object14 & __InputStaticLeaf51 --> PgSelect52
    PgSelect52 --> First56
    First56 --> PgSelectSingle57
    PgSelectSingle57 --> PgClassExpression58
    PgSelectSingle57 --> PgClassExpression59
    Object14 & __InputStaticLeaf60 --> PgSelect61
    PgSelect61 --> First65
    First65 --> PgSelectSingle66
    PgSelectSingle66 --> PgClassExpression67
    PgSelectSingle66 --> PgClassExpression68
    Object14 & __InputStaticLeaf69 --> PgSelect70
    PgSelect70 --> First74
    First74 --> PgSelectSingle75
    PgSelectSingle75 --> PgClassExpression76
    PgSelectSingle75 --> PgClassExpression77

    subgraph "Buckets for queries/v4/js-reserved-table-names"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: 12, 13, 33, 42, 51, 60, 69, 14<br />2: 11, 24, 34, 43, 52, 61, 70<br />ᐳ: 38, 39, 47, 48, 56, 57, 65, 66, 74, 75"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,PgSelect11,Access12,Access13,Object14,PgSelect24,__InputStaticLeaf33,PgSelect34,First38,PgSelectSingle39,__InputStaticLeaf42,PgSelect43,First47,PgSelectSingle48,__InputStaticLeaf51,PgSelect52,First56,PgSelectSingle57,__InputStaticLeaf60,PgSelect61,First65,PgSelectSingle66,__InputStaticLeaf69,PgSelect70,First74,PgSelectSingle75 bucket0
    Bucket1("Bucket 1 (listItem)<br />ROOT __Item{1}ᐸ11ᐳ[15]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item15,PgSelectSingle16,PgClassExpression17,PgClassExpression18,PgClassExpression19 bucket1
    Bucket2("Bucket 2 (listItem)<br />ROOT __Item{2}ᐸ24ᐳ[28]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item28,PgSelectSingle29,PgClassExpression30,PgClassExpression31,PgClassExpression32 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 39<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[39]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression40,PgClassExpression41 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 48<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[48]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression49,PgClassExpression50 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 57<br /><br />ROOT PgSelectSingleᐸconstructorᐳ[57]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression58,PgClassExpression59 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 66<br /><br />ROOT PgSelectSingleᐸyieldᐳ[66]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression67,PgClassExpression68 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 75<br /><br />ROOT PgSelectSingleᐸyieldᐳ[75]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression76,PgClassExpression77 bucket7
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5 & Bucket6 & Bucket7
    end
