%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect36[["PgSelect[36∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Object13{{"Object[13∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant110{{"Constant[110∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant109{{"Constant[109∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Constant111{{"Constant[111∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Constant112{{"Constant[112∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Lambda49{{"Lambda[49∈0] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Access53{{"Access[53∈0] ➊<br />ᐸ52.0ᐳ"}}:::plan
    Lambda103{{"Lambda[103∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda108{{"Lambda[108∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object13 & Constant110 & Constant109 & Constant110 & Constant111 & Constant112 & Lambda49 & Access53 & Lambda103 & Lambda108 --> PgSelect36
    PgSelect10[["PgSelect[10∈0] ➊<br />ᐸawaitᐳ"]]:::plan
    Lambda58{{"Lambda[58∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda63{{"Lambda[63∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object13 & Constant109 & Constant110 & Constant111 & Constant112 & Lambda49 & Access53 & Lambda58 & Lambda63 --> PgSelect10
    PgSelect21[["PgSelect[21∈0] ➊<br />ᐸcaseᐳ"]]:::plan
    Constant113{{"Constant[113∈0] ➊<br />ᐸ10ᐳ"}}:::plan
    Lambda73{{"Lambda[73∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda78{{"Lambda[78∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object13 & Constant113 & Constant113 & Constant113 & Constant113 & Lambda49 & Access53 & Lambda73 & Lambda78 --> PgSelect21
    PgSelect30[["PgSelect[30∈0] ➊<br />ᐸvalueOfᐳ"]]:::plan
    Constant114{{"Constant[114∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant115{{"Constant[115∈0] ➊<br />ᐸ6ᐳ"}}:::plan
    Lambda88{{"Lambda[88∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda93{{"Lambda[93∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object13 & Constant114 & Constant111 & Constant109 & Constant115 & Lambda49 & Access53 & Lambda88 & Lambda93 --> PgSelect30
    Object57{{"Object[57∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant54{{"Constant[54∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant55{{"Constant[55∈0] ➊<br />ᐸsql.identifier(”await”)ᐳ"}}:::plan
    Constant56{{"Constant[56∈0] ➊<br />ᐸCodec(int4)ᐳ"}}:::plan
    Lambda49 & Constant54 & Constant55 & Constant56 --> Object57
    Object72{{"Object[72∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant69{{"Constant[69∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant70{{"Constant[70∈0] ➊<br />ᐸsql.identifier(”case”)ᐳ"}}:::plan
    Lambda49 & Constant69 & Constant70 & Constant56 --> Object72
    Object87{{"Object[87∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant84{{"Constant[84∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant85{{"Constant[85∈0] ➊<br />ᐸsql.identifier(”value_of”)ᐳ"}}:::plan
    Lambda49 & Constant84 & Constant85 & Constant56 --> Object87
    Object102{{"Object[102∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant99{{"Constant[99∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant100{{"Constant[100∈0] ➊<br />ᐸsql.identifier(”null”)ᐳ"}}:::plan
    Constant101{{"Constant[101∈0] ➊<br />ᐸRecordCodec(null)ᐳ"}}:::plan
    Lambda49 & Constant99 & Constant100 & Constant101 --> Object102
    Access11{{"Access[11∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access11 & Access12 --> Object13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access11
    __Value2 --> Access12
    First14{{"First[14∈0] ➊"}}:::plan
    PgSelect10 --> First14
    PgSelectSingle15{{"PgSelectSingle[15∈0] ➊<br />ᐸawaitᐳ"}}:::plan
    First14 --> PgSelectSingle15
    PgClassExpression16{{"PgClassExpression[16∈0] ➊<br />ᐸ__await__.vᐳ"}}:::plan
    PgSelectSingle15 --> PgClassExpression16
    First23{{"First[23∈0] ➊"}}:::plan
    PgSelect21 --> First23
    PgSelectSingle24{{"PgSelectSingle[24∈0] ➊<br />ᐸcaseᐳ"}}:::plan
    First23 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈0] ➊<br />ᐸ__case__.vᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    First32{{"First[32∈0] ➊"}}:::plan
    PgSelect30 --> First32
    PgSelectSingle33{{"PgSelectSingle[33∈0] ➊<br />ᐸvalueOfᐳ"}}:::plan
    First32 --> PgSelectSingle33
    PgClassExpression34{{"PgClassExpression[34∈0] ➊<br />ᐸ__value_of__.vᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression34
    First38{{"First[38∈0] ➊"}}:::plan
    PgSelect36 --> First38
    PgSelectSingle39{{"PgSelectSingle[39∈0] ➊<br />ᐸnullᐳ"}}:::plan
    First38 --> PgSelectSingle39
    Constant116{{"Constant[116∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant116 --> Lambda49
    Lambda52{{"Lambda[52∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant117{{"Constant[117∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant117 --> Lambda52
    Lambda52 --> Access53
    Object57 --> Lambda58
    Constant118{{"Constant[118∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”await”ᐳ"}}:::plan
    Constant118 --> Lambda63
    Object72 --> Lambda73
    Constant119{{"Constant[119∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”case”)ᐳ"}}:::plan
    Constant119 --> Lambda78
    Object87 --> Lambda88
    Constant120{{"Constant[120∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”value_ᐳ"}}:::plan
    Constant120 --> Lambda93
    Object102 --> Lambda103
    Constant121{{"Constant[121∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”null”)ᐳ"}}:::plan
    Constant121 --> Lambda108
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgClassExpression45{{"PgClassExpression[45∈1] ➊<br />ᐸ”js_reserv...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression45
    PgClassExpression46{{"PgClassExpression[46∈1] ➊<br />ᐸ__null__.”break”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression46

    %% define steps

    subgraph "Buckets for queries/v4/js-reserved-function-names"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 11, 12, 54, 55, 56, 69, 70, 84, 85, 99, 100, 101, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 13, 49, 52, 53, 57, 58, 63, 72, 73, 78, 87, 88, 93, 102, 103, 108<br />2: 10, 21, 30, 36<br />ᐳ: 14, 15, 16, 23, 24, 25, 32, 33, 34, 38, 39"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect10,Access11,Access12,Object13,First14,PgSelectSingle15,PgClassExpression16,PgSelect21,First23,PgSelectSingle24,PgClassExpression25,PgSelect30,First32,PgSelectSingle33,PgClassExpression34,PgSelect36,First38,PgSelectSingle39,Lambda49,Lambda52,Access53,Constant54,Constant55,Constant56,Object57,Lambda58,Lambda63,Constant69,Constant70,Object72,Lambda73,Lambda78,Constant84,Constant85,Object87,Lambda88,Lambda93,Constant99,Constant100,Constant101,Object102,Lambda103,Lambda108,Constant109,Constant110,Constant111,Constant112,Constant113,Constant114,Constant115,Constant116,Constant117,Constant118,Constant119,Constant120,Constant121 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 39<br /><br />ROOT PgSelectSingleᐸnullᐳ[39]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression45,PgClassExpression46 bucket1
    Bucket0 --> Bucket1
    end
