%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/js-reserved-function-names"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 11, 13, 81, 82, 83, 84, 85, 86, 87, 14, 16, 33, 50, 74<br />2: 10, 30, 47, 61<br />3: 22, 39, 56, 66<br />ᐳ: 21, 24, 25, 38, 41, 42, 55, 58, 59, 65, 68"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 68<br /><br />ROOT PgSelectSingleᐸnullᐳ[68]"):::bucket
    end
    Bucket0 --> Bucket1

    %% plan dependencies
    PgFromExpression16{{"PgFromExpression[16∈0] ➊"}}:::plan
    Constant81{{"Constant[81∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Constant82{{"Constant[82∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant83{{"Constant[83∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Constant84{{"Constant[84∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Constant81 & Constant82 & Constant83 & Constant84 --> PgFromExpression16
    PgFromExpression33{{"PgFromExpression[33∈0] ➊"}}:::plan
    Constant85{{"Constant[85∈0] ➊<br />ᐸ10ᐳ"}}:::plan
    Constant85 -- 4 --> PgFromExpression33
    PgFromExpression50{{"PgFromExpression[50∈0] ➊"}}:::plan
    Constant86{{"Constant[86∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant87{{"Constant[87∈0] ➊<br />ᐸ6ᐳ"}}:::plan
    Constant86 & Constant83 & Constant81 & Constant87 --> PgFromExpression50
    PgFromExpression74{{"PgFromExpression[74∈0] ➊"}}:::plan
    Constant81 & Constant82 & Constant83 & Constant84 --> PgFromExpression74
    PgSelect61[["PgSelect[61∈0] ➊<br />ᐸnullᐳ"]]:::plan
    Object14{{"Object[14∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Object14 & Constant82 & PgFromExpression74 --> PgSelect61
    PgSelect10[["PgSelect[10∈0] ➊<br />ᐸawaitᐳ"]]:::plan
    Object14 & PgFromExpression16 --> PgSelect10
    Access11{{"Access[11∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access11 & Access13 --> Object14
    PgSelect30[["PgSelect[30∈0] ➊<br />ᐸcaseᐳ"]]:::plan
    Object14 & PgFromExpression33 --> PgSelect30
    PgSelect47[["PgSelect[47∈0] ➊<br />ᐸvalueOfᐳ"]]:::plan
    Object14 & PgFromExpression50 --> PgSelect47
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access11
    __Value2 --> Access13
    First21{{"First[21∈0] ➊"}}:::plan
    PgSelectRows22[["PgSelectRows[22∈0] ➊"]]:::plan
    PgSelectRows22 --> First21
    PgSelect10 --> PgSelectRows22
    PgSelectSingle24{{"PgSelectSingle[24∈0] ➊<br />ᐸawaitᐳ"}}:::plan
    First21 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈0] ➊<br />ᐸ__await__.vᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    First38{{"First[38∈0] ➊"}}:::plan
    PgSelectRows39[["PgSelectRows[39∈0] ➊"]]:::plan
    PgSelectRows39 --> First38
    PgSelect30 --> PgSelectRows39
    PgSelectSingle41{{"PgSelectSingle[41∈0] ➊<br />ᐸcaseᐳ"}}:::plan
    First38 --> PgSelectSingle41
    PgClassExpression42{{"PgClassExpression[42∈0] ➊<br />ᐸ__case__.vᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression42
    First55{{"First[55∈0] ➊"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈0] ➊"]]:::plan
    PgSelectRows56 --> First55
    PgSelect47 --> PgSelectRows56
    PgSelectSingle58{{"PgSelectSingle[58∈0] ➊<br />ᐸvalueOfᐳ"}}:::plan
    First55 --> PgSelectSingle58
    PgClassExpression59{{"PgClassExpression[59∈0] ➊<br />ᐸ__value_of__.vᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    First65{{"First[65∈0] ➊"}}:::plan
    PgSelectRows66[["PgSelectRows[66∈0] ➊"]]:::plan
    PgSelectRows66 --> First65
    PgSelect61 --> PgSelectRows66
    PgSelectSingle68{{"PgSelectSingle[68∈0] ➊<br />ᐸnullᐳ"}}:::plan
    First65 --> PgSelectSingle68
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgClassExpression79{{"PgClassExpression[79∈1] ➊<br />ᐸ(1/0) /* E...ferred! */ᐳ"}}:::plan
    PgSelectSingle68 --> PgClassExpression79
    PgClassExpression80{{"PgClassExpression[80∈1] ➊<br />ᐸ__null__.”break”ᐳ"}}:::plan
    PgSelectSingle68 --> PgClassExpression80

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect10,Access11,Access13,Object14,PgFromExpression16,First21,PgSelectRows22,PgSelectSingle24,PgClassExpression25,PgSelect30,PgFromExpression33,First38,PgSelectRows39,PgSelectSingle41,PgClassExpression42,PgSelect47,PgFromExpression50,First55,PgSelectRows56,PgSelectSingle58,PgClassExpression59,PgSelect61,First65,PgSelectRows66,PgSelectSingle68,PgFromExpression74,Constant81,Constant82,Constant83,Constant84,Constant85,Constant86,Constant87 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression79,PgClassExpression80 bucket1

