select
  __person__."id"::text as "0",
  array(
    select array[
      __post__."headline",
      "a"."post_headline_trimmed"(
        __post__,
        $1::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $2::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $3::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $4::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $5::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $6::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $7::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $8::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $9::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $10::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $11::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $12::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $13::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $14::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $15::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $16::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $17::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $18::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $19::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $20::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $21::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $22::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $23::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $24::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $25::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $26::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $27::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $28::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $29::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $30::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $31::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $32::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $33::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $34::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $35::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $36::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $37::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $38::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $39::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $40::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $41::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $42::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $43::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $44::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $45::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $46::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $47::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $48::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $49::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $50::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $51::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $52::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $53::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $54::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $55::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $56::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $57::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $58::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $59::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $60::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $61::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $62::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $63::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $64::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $65::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $66::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $67::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $68::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $69::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $70::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $71::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $72::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $73::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $74::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $75::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $76::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $77::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $78::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $79::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $80::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $81::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $82::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $83::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $84::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $85::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $86::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $87::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $88::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $89::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $90::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $91::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $92::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $93::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $94::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $95::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $96::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $97::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $98::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $99::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $100::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $101::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $102::"int4"
      ),
      "a"."post_headline_trimmed"(
        __post__,
        $103::"int4"
      )
    ]::text[]
    from "a"."post" as __post__
    where (
      __post__."author_id" = __person__."id"
    )
    order by __post__."id" asc
    limit 1
  )::text as "1"
from "c"."person" as __person__
order by __person__."id" asc
limit 1;