%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object17{{"Object[17∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    PgSelect31[["PgSelect[31∈0] ➊<br />ᐸlarge_node_idᐳ"]]:::plan
    Access29{{"Access[29∈0] ➊<br />ᐸ28.1ᐳ"}}:::plan
    Object17 -->|rejectNull| PgSelect31
    Access29 --> PgSelect31
    PgSelect44[["PgSelect[44∈0] ➊<br />ᐸlarge_node_idᐳ"]]:::plan
    Access42{{"Access[42∈0] ➊<br />ᐸ41.1ᐳ"}}:::plan
    Object17 -->|rejectNull| PgSelect44
    Access42 --> PgSelect44
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access15
    __Value2 --> Access16
    Lambda28{{"Lambda[28∈0] ➊<br />ᐸspecifier_LargeNodeId_base64JSONᐳ"}}:::plan
    Constant53{{"Constant[53∈0] ➊<br />ᐸ'WyJsYXJnZV9ub2RlX2lkcyIsOTAwNzE5OTI1NDc0MDk5MF0='ᐳ"}}:::plan
    Constant53 --> Lambda28
    Lambda28 --> Access29
    First33{{"First[33∈0] ➊"}}:::plan
    PgSelect31 --> First33
    PgSelectSingle34{{"PgSelectSingle[34∈0] ➊<br />ᐸlarge_node_idᐳ"}}:::plan
    First33 --> PgSelectSingle34
    Lambda41{{"Lambda[41∈0] ➊<br />ᐸspecifier_LargeNodeId_base64JSONᐳ"}}:::plan
    Constant54{{"Constant[54∈0] ➊<br />ᐸ'WyJsYXJnZV9ub2RlX2lkcyIsIjIwOTgyODg2NjkyMTg1NzE3NjAiXQ=='ᐳ"}}:::plan
    Constant54 --> Lambda41
    Lambda41 --> Access42
    First46{{"First[46∈0] ➊"}}:::plan
    PgSelect44 --> First46
    PgSelectSingle47{{"PgSelectSingle[47∈0] ➊<br />ᐸlarge_node_idᐳ"}}:::plan
    First46 --> PgSelectSingle47
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection18{{"Connection[18∈0] ➊<br />ᐸ14ᐳ"}}:::plan
    Constant22{{"Constant[22∈0] ➊<br />ᐸ'large_node_ids'ᐳ"}}:::plan
    PgSelect19[["PgSelect[19∈1] ➊<br />ᐸlarge_node_idᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect19
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelect19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸlarge_node_idᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    List24{{"List[24∈3]<br />ᐸ22,23ᐳ"}}:::plan
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression23 --> List24
    PgSelectSingle21 --> PgClassExpression23
    Lambda25{{"Lambda[25∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List24 --> Lambda25
    PgClassExpression26{{"PgClassExpression[26∈3]<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression26
    List37{{"List[37∈4] ➊<br />ᐸ22,36ᐳ"}}:::plan
    PgClassExpression36{{"PgClassExpression[36∈4] ➊<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression36 --> List37
    PgSelectSingle34 --> PgClassExpression36
    Lambda38{{"Lambda[38∈4] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List37 --> Lambda38
    PgClassExpression39{{"PgClassExpression[39∈4] ➊<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression39
    List50{{"List[50∈5] ➊<br />ᐸ22,49ᐳ"}}:::plan
    PgClassExpression49{{"PgClassExpression[49∈5] ➊<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression49 --> List50
    PgSelectSingle47 --> PgClassExpression49
    Lambda51{{"Lambda[51∈5] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List50 --> Lambda51
    PgClassExpression52{{"PgClassExpression[52∈5] ➊<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle47 --> PgClassExpression52

    %% define steps

    subgraph "Buckets for queries/v4/large_bigint.issue491"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 15, 16, 18, 22, 53, 54, 17, 28, 29, 41, 42<br />2: PgSelect[31], PgSelect[44]<br />ᐳ: 33, 34, 46, 47"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access15,Access16,Object17,Connection18,Constant22,Lambda28,Access29,PgSelect31,First33,PgSelectSingle34,Lambda41,Access42,PgSelect44,First46,PgSelectSingle47,Constant53,Constant54 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 17, 18, 22<br /><br />ROOT Connectionᐸ14ᐳ[18]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect19 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 22<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21, 22<br /><br />ROOT PgSelectSingle{2}ᐸlarge_node_idᐳ[21]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression23,List24,Lambda25,PgClassExpression26 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 34, 22<br /><br />ROOT PgSelectSingleᐸlarge_node_idᐳ[34]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression36,List37,Lambda38,PgClassExpression39 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 47, 22<br /><br />ROOT PgSelectSingleᐸlarge_node_idᐳ[47]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression49,List50,Lambda51,PgClassExpression52 bucket5
    Bucket0 --> Bucket1 & Bucket4 & Bucket5
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    end
