%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object17{{"Object[17∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈0]<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈0]<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    PgSelect32[["PgSelect[32∈0]<br />ᐸlarge_node_idᐳ"]]:::plan
    Access30{{"Access[30∈0]<br />ᐸ29.1ᐳ"}}:::plan
    Object17 -->|rejectNull| PgSelect32
    Access30 --> PgSelect32
    PgSelect48[["PgSelect[48∈0]<br />ᐸlarge_node_idᐳ"]]:::plan
    Access46{{"Access[46∈0]<br />ᐸ45.1ᐳ"}}:::plan
    Object17 -->|rejectNull| PgSelect48
    Access46 --> PgSelect48
    __Value2["__Value[2∈0]<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access15
    __Value2 --> Access16
    Lambda29{{"Lambda[29∈0]<br />ᐸspecifier_LargeNodeId_base64JSONᐳ"}}:::plan
    Constant60{{"Constant[60∈0]<br />ᐸ'WyJsYXJnZV9ub2RlX2lkcyIsOTAwNzE5OTI1NDc0MDk5MF0='ᐳ"}}:::plan
    Constant60 --> Lambda29
    Lambda29 --> Access30
    First36{{"First[36∈0]"}}:::plan
    PgSelect32 --> First36
    PgSelectSingle37{{"PgSelectSingle[37∈0]<br />ᐸlarge_node_idᐳ"}}:::plan
    First36 --> PgSelectSingle37
    Lambda45{{"Lambda[45∈0]<br />ᐸspecifier_LargeNodeId_base64JSONᐳ"}}:::plan
    Constant61{{"Constant[61∈0]<br />ᐸ'WyJsYXJnZV9ub2RlX2lkcyIsIjIwOTgyODg2NjkyMTg1NzE3NjAiXQ=='ᐳ"}}:::plan
    Constant61 --> Lambda45
    Lambda45 --> Access46
    First52{{"First[52∈0]"}}:::plan
    PgSelect48 --> First52
    PgSelectSingle53{{"PgSelectSingle[53∈0]<br />ᐸlarge_node_idᐳ"}}:::plan
    First52 --> PgSelectSingle53
    __Value4["__Value[4∈0]<br />ᐸrootValueᐳ"]:::plan
    Connection18{{"Connection[18∈0]<br />ᐸ14ᐳ"}}:::plan
    Constant22{{"Constant[22∈0]<br />ᐸ'large_node_ids'ᐳ"}}:::plan
    PgSelect19[["PgSelect[19∈1]<br />ᐸlarge_node_idᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect19
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelect19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸlarge_node_idᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    List24{{"List[24∈3]<br />ᐸ22,23ᐳ"}}:::plan
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression23 --> List24
    PgSelectSingle21 --> PgClassExpression23
    Lambda25{{"Lambda[25∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List24 --> Lambda25
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression27
    List40{{"List[40∈4]<br />ᐸ22,39ᐳ"}}:::plan
    PgClassExpression39{{"PgClassExpression[39∈4]<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression39 --> List40
    PgSelectSingle37 --> PgClassExpression39
    Lambda41{{"Lambda[41∈4]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List40 --> Lambda41
    PgClassExpression43{{"PgClassExpression[43∈4]<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression43
    List56{{"List[56∈5]<br />ᐸ22,55ᐳ"}}:::plan
    PgClassExpression55{{"PgClassExpression[55∈5]<br />ᐸ__large_node_id__.”id”ᐳ"}}:::plan
    Constant22 & PgClassExpression55 --> List56
    PgSelectSingle53 --> PgClassExpression55
    Lambda57{{"Lambda[57∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List56 --> Lambda57
    PgClassExpression59{{"PgClassExpression[59∈5]<br />ᐸ__large_no...d__.”text”ᐳ"}}:::plan
    PgSelectSingle53 --> PgClassExpression59

    %% define steps

    subgraph "Buckets for queries/v4/large_bigint.issue491"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: 15, 16, 18, 22, 60, 61, 17, 29, 30, 45, 46<br />2: PgSelect[32], PgSelect[48]<br />ᐳ: 36, 37, 52, 53"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access15,Access16,Object17,Connection18,Constant22,Lambda29,Access30,PgSelect32,First36,PgSelectSingle37,Lambda45,Access46,PgSelect48,First52,PgSelectSingle53,Constant60,Constant61 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 17, 18, 22<br /><br />ROOT Connectionᐸ14ᐳ[18]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect19 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 22<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21, 22<br /><br />ROOT PgSelectSingle{2}ᐸlarge_node_idᐳ[21]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression23,List24,Lambda25,PgClassExpression27 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 37, 22<br /><br />ROOT PgSelectSingleᐸlarge_node_idᐳ[37]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression39,List40,Lambda41,PgClassExpression43 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 53, 22<br /><br />ROOT PgSelectSingleᐸlarge_node_idᐳ[53]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression55,List56,Lambda57,PgClassExpression59 bucket5
    Bucket0 --> Bucket1 & Bucket4 & Bucket5
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    classDef unary fill:#fafffa,borderWidth:8px
    class Object17,PgSelect32,PgSelect48,Access15,Access16,Lambda29,Access30,First36,PgSelectSingle37,Lambda45,Access46,First52,PgSelectSingle53,__Value2,__Value4,Connection18,Constant22,Constant60,Constant61,PgSelect19,List40,PgClassExpression39,Lambda41,PgClassExpression43,List56,PgClassExpression55,Lambda57,PgClassExpression59 unary
    end
