%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect7[["PgSelect[7∈0]<br />ᐸpersonᐳ"]]:::plan
    Object10{{"Object[10∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant52{{"Constant[52∈0]<br />ᐸ'sara.smith@email.com'ᐳ"}}:::plan
    Object10 & Constant52 --> PgSelect7
    Access8{{"Access[8∈0]<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0]<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __Value2["__Value[2∈0]<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0]"}}:::plan
    PgSelect7 --> First11
    PgSelectSingle12{{"PgSelectSingle[12∈0]<br />ᐸpersonᐳ"}}:::plan
    First11 --> PgSelectSingle12
    __Value4["__Value[4∈0]<br />ᐸrootValueᐳ"]:::plan
    List15{{"List[15∈1]<br />ᐸ13,14ᐳ"}}:::plan
    Constant13{{"Constant[13∈1]<br />ᐸ'people'ᐳ"}}:::plan
    PgClassExpression14{{"PgClassExpression[14∈1]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant13 & PgClassExpression14 --> List15
    PgSelectSingle12 --> PgClassExpression14
    Lambda16{{"Lambda[16∈1]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List15 --> Lambda16
    PgClassExpression17{{"PgClassExpression[17∈1]<br />ᐸ__person__.”email”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression17
    First31{{"First[31∈1]"}}:::plan
    Access50{{"Access[50∈1]<br />ᐸ11.2ᐳ"}}:::plan
    Access50 --> First31
    PgSelectSingle32{{"PgSelectSingle[32∈1]<br />ᐸperson_friendsᐳ"}}:::plan
    First31 --> PgSelectSingle32
    PgClassExpression33{{"PgClassExpression[33∈1]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression33
    First47{{"First[47∈1]"}}:::plan
    Access51{{"Access[51∈1]<br />ᐸ11.3ᐳ"}}:::plan
    Access51 --> First47
    PgSelectSingle48{{"PgSelectSingle[48∈1]<br />ᐸperson_friendsᐳ"}}:::plan
    First47 --> PgSelectSingle48
    PgClassExpression49{{"PgClassExpression[49∈1]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    First11 --> Access50
    First11 --> Access51
    Connection29{{"Connection[29∈1]<br />ᐸ25ᐳ"}}:::plan
    Connection45{{"Connection[45∈1]<br />ᐸ41ᐳ"}}:::plan

    %% define steps

    subgraph "Buckets for queries/v4/longAliases"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: 8, 9, 52, 10<br />2: PgSelect[7]<br />ᐳ: First[11], PgSelectSingle[12]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectSingle12,Constant52 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 11<br /><br />ROOT PgSelectSingleᐸpersonᐳ[12]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Constant13,PgClassExpression14,List15,Lambda16,PgClassExpression17,Connection29,First31,PgSelectSingle32,PgClassExpression33,Connection45,First47,PgSelectSingle48,PgClassExpression49,Access50,Access51 bucket1
    Bucket0 --> Bucket1
    classDef unary fill:#fafffa,borderWidth:8px
    class PgSelect7,Object10,Access8,Access9,First11,PgSelectSingle12,__Value2,__Value4,Constant52,List15,PgClassExpression14,Lambda16,PgClassExpression17,First31,PgSelectSingle32,PgClassExpression33,First47,PgSelectSingle48,PgClassExpression49,Access50,Access51,Constant13,Connection29,Connection45 unary
    end
