%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object21{{"Object[21∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access19{{"Access[19∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access20{{"Access[20∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access19 & Access20 --> Object21
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access19
    __Value2 --> Access20
    Lambda150{{"Lambda[150∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant192{{"Constant[192∈0] ➊<br />ᐸ[Object: null prototype] {   cursorLower: null,   cursorUppeᐳ"}}:::plan
    Constant192 --> Lambda150
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection22{{"Connection[22∈0] ➊<br />ᐸ18ᐳ"}}:::plan
    Constant37{{"Constant[37∈0] ➊<br />ᐸfalseᐳ"}}:::plan
    Connection67{{"Connection[67∈0] ➊<br />ᐸ65ᐳ"}}:::plan
    Connection112{{"Connection[112∈0] ➊<br />ᐸ110ᐳ"}}:::plan
    PgSelect23[["PgSelect[23∈1] ➊<br />ᐸnetworkᐳ"]]:::plan
    Constant191{{"Constant[191∈1] ➊<br />ᐸ'192.168.0.0'ᐳ"}}:::plan
    Object21 & Constant191 & Connection22 & Lambda150 --> PgSelect23
    PgSelect39[["PgSelect[39∈1] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Object21 & Constant191 & Connection22 & Lambda150 --> PgSelect39
    PgPageInfo24{{"PgPageInfo[24∈1] ➊"}}:::plan
    Connection22 --> PgPageInfo24
    First26{{"First[26∈1] ➊"}}:::plan
    PgSelect23 --> First26
    PgSelectSingle27{{"PgSelectSingle[27∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    First26 --> PgSelectSingle27
    PgCursor28{{"PgCursor[28∈1] ➊"}}:::plan
    List30{{"List[30∈1] ➊<br />ᐸ29ᐳ"}}:::plan
    List30 --> PgCursor28
    PgClassExpression29{{"PgClassExpression[29∈1] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression29
    PgClassExpression29 --> List30
    Last32{{"Last[32∈1] ➊"}}:::plan
    PgSelect23 --> Last32
    PgSelectSingle33{{"PgSelectSingle[33∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last32 --> PgSelectSingle33
    PgCursor34{{"PgCursor[34∈1] ➊"}}:::plan
    List36{{"List[36∈1] ➊<br />ᐸ35ᐳ"}}:::plan
    List36 --> PgCursor34
    PgClassExpression35{{"PgClassExpression[35∈1] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression35
    PgClassExpression35 --> List36
    First40{{"First[40∈1] ➊"}}:::plan
    PgSelect39 --> First40
    PgSelectSingle41{{"PgSelectSingle[41∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    First40 --> PgSelectSingle41
    PgClassExpression42{{"PgClassExpression[42∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression42
    __Item44[/"__Item[44∈2]<br />ᐸ23ᐳ"\]:::itemplan
    PgSelect23 ==> __Item44
    PgSelectSingle45{{"PgSelectSingle[45∈2]<br />ᐸnetworkᐳ"}}:::plan
    __Item44 --> PgSelectSingle45
    PgCursor46{{"PgCursor[46∈3]"}}:::plan
    List48{{"List[48∈3]<br />ᐸ47ᐳ"}}:::plan
    List48 --> PgCursor46
    PgClassExpression47{{"PgClassExpression[47∈3]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression47
    PgClassExpression47 --> List48
    PgClassExpression50{{"PgClassExpression[50∈3]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression50
    PgClassExpression51{{"PgClassExpression[51∈3]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression51
    PgClassExpression52{{"PgClassExpression[52∈3]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression52
    PgSelect68[["PgSelect[68∈4] ➊<br />ᐸnetworkᐳ"]]:::plan
    Constant193{{"Constant[193∈4] ➊<br />ᐸ'192.168.0.0/16'ᐳ"}}:::plan
    Object21 & Constant193 & Connection67 & Lambda150 --> PgSelect68
    PgSelect84[["PgSelect[84∈4] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Object21 & Constant193 & Connection67 & Lambda150 --> PgSelect84
    PgPageInfo69{{"PgPageInfo[69∈4] ➊"}}:::plan
    Connection67 --> PgPageInfo69
    First71{{"First[71∈4] ➊"}}:::plan
    PgSelect68 --> First71
    PgSelectSingle72{{"PgSelectSingle[72∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    First71 --> PgSelectSingle72
    PgCursor73{{"PgCursor[73∈4] ➊"}}:::plan
    List75{{"List[75∈4] ➊<br />ᐸ74ᐳ"}}:::plan
    List75 --> PgCursor73
    PgClassExpression74{{"PgClassExpression[74∈4] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle72 --> PgClassExpression74
    PgClassExpression74 --> List75
    Last77{{"Last[77∈4] ➊"}}:::plan
    PgSelect68 --> Last77
    PgSelectSingle78{{"PgSelectSingle[78∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last77 --> PgSelectSingle78
    PgCursor79{{"PgCursor[79∈4] ➊"}}:::plan
    List81{{"List[81∈4] ➊<br />ᐸ80ᐳ"}}:::plan
    List81 --> PgCursor79
    PgClassExpression80{{"PgClassExpression[80∈4] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle78 --> PgClassExpression80
    PgClassExpression80 --> List81
    First85{{"First[85∈4] ➊"}}:::plan
    PgSelect84 --> First85
    PgSelectSingle86{{"PgSelectSingle[86∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    First85 --> PgSelectSingle86
    PgClassExpression87{{"PgClassExpression[87∈4] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle86 --> PgClassExpression87
    __Item89[/"__Item[89∈5]<br />ᐸ68ᐳ"\]:::itemplan
    PgSelect68 ==> __Item89
    PgSelectSingle90{{"PgSelectSingle[90∈5]<br />ᐸnetworkᐳ"}}:::plan
    __Item89 --> PgSelectSingle90
    PgCursor91{{"PgCursor[91∈6]"}}:::plan
    List93{{"List[93∈6]<br />ᐸ92ᐳ"}}:::plan
    List93 --> PgCursor91
    PgClassExpression92{{"PgClassExpression[92∈6]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression92
    PgClassExpression92 --> List93
    PgClassExpression95{{"PgClassExpression[95∈6]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression95
    PgClassExpression96{{"PgClassExpression[96∈6]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression96
    PgClassExpression97{{"PgClassExpression[97∈6]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression97
    PgSelect113[["PgSelect[113∈7] ➊<br />ᐸnetworkᐳ"]]:::plan
    Constant194{{"Constant[194∈7] ➊<br />ᐸ'08:00:2b:01:02:03'ᐳ"}}:::plan
    Object21 & Constant194 & Connection112 & Lambda150 --> PgSelect113
    PgSelect129[["PgSelect[129∈7] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Object21 & Constant194 & Connection112 & Lambda150 --> PgSelect129
    PgPageInfo114{{"PgPageInfo[114∈7] ➊"}}:::plan
    Connection112 --> PgPageInfo114
    First116{{"First[116∈7] ➊"}}:::plan
    PgSelect113 --> First116
    PgSelectSingle117{{"PgSelectSingle[117∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    First116 --> PgSelectSingle117
    PgCursor118{{"PgCursor[118∈7] ➊"}}:::plan
    List120{{"List[120∈7] ➊<br />ᐸ119ᐳ"}}:::plan
    List120 --> PgCursor118
    PgClassExpression119{{"PgClassExpression[119∈7] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle117 --> PgClassExpression119
    PgClassExpression119 --> List120
    Last122{{"Last[122∈7] ➊"}}:::plan
    PgSelect113 --> Last122
    PgSelectSingle123{{"PgSelectSingle[123∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last122 --> PgSelectSingle123
    PgCursor124{{"PgCursor[124∈7] ➊"}}:::plan
    List126{{"List[126∈7] ➊<br />ᐸ125ᐳ"}}:::plan
    List126 --> PgCursor124
    PgClassExpression125{{"PgClassExpression[125∈7] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle123 --> PgClassExpression125
    PgClassExpression125 --> List126
    First130{{"First[130∈7] ➊"}}:::plan
    PgSelect129 --> First130
    PgSelectSingle131{{"PgSelectSingle[131∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    First130 --> PgSelectSingle131
    PgClassExpression132{{"PgClassExpression[132∈7] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle131 --> PgClassExpression132
    __Item134[/"__Item[134∈8]<br />ᐸ113ᐳ"\]:::itemplan
    PgSelect113 ==> __Item134
    PgSelectSingle135{{"PgSelectSingle[135∈8]<br />ᐸnetworkᐳ"}}:::plan
    __Item134 --> PgSelectSingle135
    PgCursor136{{"PgCursor[136∈9]"}}:::plan
    List138{{"List[138∈9]<br />ᐸ137ᐳ"}}:::plan
    List138 --> PgCursor136
    PgClassExpression137{{"PgClassExpression[137∈9]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle135 --> PgClassExpression137
    PgClassExpression137 --> List138
    PgClassExpression140{{"PgClassExpression[140∈9]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle135 --> PgClassExpression140
    PgClassExpression141{{"PgClassExpression[141∈9]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle135 --> PgClassExpression141
    PgClassExpression142{{"PgClassExpression[142∈9]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle135 --> PgClassExpression142

    %% define steps

    subgraph "Buckets for queries/v4/network_types"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access19,Access20,Object21,Connection22,Constant37,Connection67,Connection112,Lambda150,Constant192 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 21, 22, 150, 37<br /><br />ROOT Connectionᐸ18ᐳ[22]<br />1: <br />ᐳ: PgPageInfo[24], Constant[191]<br />2: PgSelect[23], PgSelect[39]<br />ᐳ: 26, 27, 29, 30, 32, 33, 35, 36, 40, 41, 42, 28, 34"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect23,PgPageInfo24,First26,PgSelectSingle27,PgCursor28,PgClassExpression29,List30,Last32,PgSelectSingle33,PgCursor34,PgClassExpression35,List36,PgSelect39,First40,PgSelectSingle41,PgClassExpression42,Constant191 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ23ᐳ[44]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item44,PgSelectSingle45 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 45<br /><br />ROOT PgSelectSingle{2}ᐸnetworkᐳ[45]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor46,PgClassExpression47,List48,PgClassExpression50,PgClassExpression51,PgClassExpression52 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 21, 67, 150, 37<br /><br />ROOT Connectionᐸ65ᐳ[67]<br />1: <br />ᐳ: PgPageInfo[69], Constant[193]<br />2: PgSelect[68], PgSelect[84]<br />ᐳ: 71, 72, 74, 75, 77, 78, 80, 81, 85, 86, 87, 73, 79"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect68,PgPageInfo69,First71,PgSelectSingle72,PgCursor73,PgClassExpression74,List75,Last77,PgSelectSingle78,PgCursor79,PgClassExpression80,List81,PgSelect84,First85,PgSelectSingle86,PgClassExpression87,Constant193 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ68ᐳ[89]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item89,PgSelectSingle90 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 90<br /><br />ROOT PgSelectSingle{5}ᐸnetworkᐳ[90]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor91,PgClassExpression92,List93,PgClassExpression95,PgClassExpression96,PgClassExpression97 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 21, 112, 150, 37<br /><br />ROOT Connectionᐸ110ᐳ[112]<br />1: <br />ᐳ: PgPageInfo[114], Constant[194]<br />2: PgSelect[113], PgSelect[129]<br />ᐳ: 116, 117, 119, 120, 122, 123, 125, 126, 130, 131, 132, 118, 124"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect113,PgPageInfo114,First116,PgSelectSingle117,PgCursor118,PgClassExpression119,List120,Last122,PgSelectSingle123,PgCursor124,PgClassExpression125,List126,PgSelect129,First130,PgSelectSingle131,PgClassExpression132,Constant194 bucket7
    Bucket8("Bucket 8 (listItem)<br /><br />ROOT __Item{8}ᐸ113ᐳ[134]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item134,PgSelectSingle135 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 135<br /><br />ROOT PgSelectSingle{8}ᐸnetworkᐳ[135]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgCursor136,PgClassExpression137,List138,PgClassExpression140,PgClassExpression141,PgClassExpression142 bucket9
    Bucket0 --> Bucket1 & Bucket4 & Bucket7
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9
    end
