%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% define steps
    __Value0["__Value[0∈0]"]:::plan
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    Access20{{"Access[20∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access21{{"Access[21∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Object22{{"Object[22∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Connection23{{"Connection[23∈0]<br />ᐸ19ᐳ"}}:::plan
    PgPageInfo24{{"PgPageInfo[24∈1]"}}:::plan
    Constant145{{"Constant[145∈1]<br />ᐸ'192.168.0.0'ᐳ"}}:::plan
    PgSelect25[["PgSelect[25∈1]<br />ᐸnetworkᐳ"]]:::plan
    First26{{"First[26∈1]"}}:::plan
    PgSelectSingle27{{"PgSelectSingle[27∈1]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression29{{"PgClassExpression[29∈1]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List30{{"List[30∈1]<br />ᐸ29ᐳ"}}:::plan
    PgCursor28{{"PgCursor[28∈1]"}}:::plan
    Last32{{"Last[32∈1]"}}:::plan
    PgSelectSingle33{{"PgSelectSingle[33∈1]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression35{{"PgClassExpression[35∈1]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List36{{"List[36∈1]<br />ᐸ35ᐳ"}}:::plan
    PgCursor34{{"PgCursor[34∈1]"}}:::plan
    Constant37{{"Constant[37∈0]<br />ᐸfalseᐳ"}}:::plan
    PgSelect39[["PgSelect[39∈1]<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    First40{{"First[40∈1]"}}:::plan
    PgSelectSingle41{{"PgSelectSingle[41∈1]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression42{{"PgClassExpression[42∈1]<br />ᐸcount(*)ᐳ"}}:::plan
    __Item44[/"__Item[44∈2]<br />ᐸ25ᐳ"\]:::itemplan
    PgSelectSingle45{{"PgSelectSingle[45∈2]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression47{{"PgClassExpression[47∈3]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List48{{"List[48∈3]<br />ᐸ47ᐳ"}}:::plan
    PgCursor46{{"PgCursor[46∈3]"}}:::plan
    PgClassExpression50{{"PgClassExpression[50∈3]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgClassExpression51{{"PgClassExpression[51∈3]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgClassExpression52{{"PgClassExpression[52∈3]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    Connection69{{"Connection[69∈0]<br />ᐸ65ᐳ"}}:::plan
    PgPageInfo70{{"PgPageInfo[70∈4]"}}:::plan
    Constant146{{"Constant[146∈4]<br />ᐸ'192.168.0.0/16'ᐳ"}}:::plan
    PgSelect71[["PgSelect[71∈4]<br />ᐸnetworkᐳ"]]:::plan
    First72{{"First[72∈4]"}}:::plan
    PgSelectSingle73{{"PgSelectSingle[73∈4]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression75{{"PgClassExpression[75∈4]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List76{{"List[76∈4]<br />ᐸ75ᐳ"}}:::plan
    PgCursor74{{"PgCursor[74∈4]"}}:::plan
    Last78{{"Last[78∈4]"}}:::plan
    PgSelectSingle79{{"PgSelectSingle[79∈4]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression81{{"PgClassExpression[81∈4]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List82{{"List[82∈4]<br />ᐸ81ᐳ"}}:::plan
    PgCursor80{{"PgCursor[80∈4]"}}:::plan
    PgSelect85[["PgSelect[85∈4]<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    First86{{"First[86∈4]"}}:::plan
    PgSelectSingle87{{"PgSelectSingle[87∈4]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression88{{"PgClassExpression[88∈4]<br />ᐸcount(*)ᐳ"}}:::plan
    __Item90[/"__Item[90∈5]<br />ᐸ71ᐳ"\]:::itemplan
    PgSelectSingle91{{"PgSelectSingle[91∈5]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression93{{"PgClassExpression[93∈6]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List94{{"List[94∈6]<br />ᐸ93ᐳ"}}:::plan
    PgCursor92{{"PgCursor[92∈6]"}}:::plan
    PgClassExpression96{{"PgClassExpression[96∈6]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgClassExpression97{{"PgClassExpression[97∈6]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgClassExpression98{{"PgClassExpression[98∈6]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    Connection115{{"Connection[115∈0]<br />ᐸ111ᐳ"}}:::plan
    PgPageInfo116{{"PgPageInfo[116∈7]"}}:::plan
    Constant147{{"Constant[147∈7]<br />ᐸ'08:00:2b:01:02:03'ᐳ"}}:::plan
    PgSelect117[["PgSelect[117∈7]<br />ᐸnetworkᐳ"]]:::plan
    First118{{"First[118∈7]"}}:::plan
    PgSelectSingle119{{"PgSelectSingle[119∈7]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression121{{"PgClassExpression[121∈7]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List122{{"List[122∈7]<br />ᐸ121ᐳ"}}:::plan
    PgCursor120{{"PgCursor[120∈7]"}}:::plan
    Last124{{"Last[124∈7]"}}:::plan
    PgSelectSingle125{{"PgSelectSingle[125∈7]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression127{{"PgClassExpression[127∈7]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List128{{"List[128∈7]<br />ᐸ127ᐳ"}}:::plan
    PgCursor126{{"PgCursor[126∈7]"}}:::plan
    PgSelect131[["PgSelect[131∈7]<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    First132{{"First[132∈7]"}}:::plan
    PgSelectSingle133{{"PgSelectSingle[133∈7]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression134{{"PgClassExpression[134∈7]<br />ᐸcount(*)ᐳ"}}:::plan
    __Item136[/"__Item[136∈8]<br />ᐸ117ᐳ"\]:::itemplan
    PgSelectSingle137{{"PgSelectSingle[137∈8]<br />ᐸnetworkᐳ"}}:::plan
    PgClassExpression139{{"PgClassExpression[139∈9]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    List140{{"List[140∈9]<br />ᐸ139ᐳ"}}:::plan
    PgCursor138{{"PgCursor[138∈9]"}}:::plan
    PgClassExpression142{{"PgClassExpression[142∈9]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgClassExpression143{{"PgClassExpression[143∈9]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgClassExpression144{{"PgClassExpression[144∈9]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan

    %% plan dependencies
    __Value3 --> Access20
    __Value3 --> Access21
    Access20 & Access21 --> Object22
    Connection23 --> PgPageInfo24
    Object22 & Constant145 & Connection23 --> PgSelect25
    PgSelect25 --> First26
    First26 --> PgSelectSingle27
    PgSelectSingle27 --> PgClassExpression29
    PgClassExpression29 --> List30
    List30 --> PgCursor28
    PgSelect25 --> Last32
    Last32 --> PgSelectSingle33
    PgSelectSingle33 --> PgClassExpression35
    PgClassExpression35 --> List36
    List36 --> PgCursor34
    Object22 & Constant145 & Connection23 --> PgSelect39
    PgSelect39 --> First40
    First40 --> PgSelectSingle41
    PgSelectSingle41 --> PgClassExpression42
    PgSelect25 ==> __Item44
    __Item44 --> PgSelectSingle45
    PgSelectSingle45 --> PgClassExpression47
    PgClassExpression47 --> List48
    List48 --> PgCursor46
    PgSelectSingle45 --> PgClassExpression50
    PgSelectSingle45 --> PgClassExpression51
    PgSelectSingle45 --> PgClassExpression52
    Connection69 --> PgPageInfo70
    Object22 & Constant146 & Connection69 --> PgSelect71
    PgSelect71 --> First72
    First72 --> PgSelectSingle73
    PgSelectSingle73 --> PgClassExpression75
    PgClassExpression75 --> List76
    List76 --> PgCursor74
    PgSelect71 --> Last78
    Last78 --> PgSelectSingle79
    PgSelectSingle79 --> PgClassExpression81
    PgClassExpression81 --> List82
    List82 --> PgCursor80
    Object22 & Constant146 & Connection69 --> PgSelect85
    PgSelect85 --> First86
    First86 --> PgSelectSingle87
    PgSelectSingle87 --> PgClassExpression88
    PgSelect71 ==> __Item90
    __Item90 --> PgSelectSingle91
    PgSelectSingle91 --> PgClassExpression93
    PgClassExpression93 --> List94
    List94 --> PgCursor92
    PgSelectSingle91 --> PgClassExpression96
    PgSelectSingle91 --> PgClassExpression97
    PgSelectSingle91 --> PgClassExpression98
    Connection115 --> PgPageInfo116
    Object22 & Constant147 & Connection115 --> PgSelect117
    PgSelect117 --> First118
    First118 --> PgSelectSingle119
    PgSelectSingle119 --> PgClassExpression121
    PgClassExpression121 --> List122
    List122 --> PgCursor120
    PgSelect117 --> Last124
    Last124 --> PgSelectSingle125
    PgSelectSingle125 --> PgClassExpression127
    PgClassExpression127 --> List128
    List128 --> PgCursor126
    Object22 & Constant147 & Connection115 --> PgSelect131
    PgSelect131 --> First132
    First132 --> PgSelectSingle133
    PgSelectSingle133 --> PgClassExpression134
    PgSelect117 ==> __Item136
    __Item136 --> PgSelectSingle137
    PgSelectSingle137 --> PgClassExpression139
    PgClassExpression139 --> List140
    List140 --> PgCursor138
    PgSelectSingle137 --> PgClassExpression142
    PgSelectSingle137 --> PgClassExpression143
    PgSelectSingle137 --> PgClassExpression144

    subgraph "Buckets for queries/v4/network_types"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,Access20,Access21,Object22,Connection23,Constant37,Connection69,Connection115 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 23, 22, 37<br /><br />ROOT Connectionᐸ19ᐳ[23]<br />1: <br />ᐳ: PgPageInfo[24], Constant[145]<br />2: PgSelect[25], PgSelect[39]<br />ᐳ: 26, 27, 29, 30, 32, 33, 35, 36, 40, 41, 42, 28, 34"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgPageInfo24,PgSelect25,First26,PgSelectSingle27,PgCursor28,PgClassExpression29,List30,Last32,PgSelectSingle33,PgCursor34,PgClassExpression35,List36,PgSelect39,First40,PgSelectSingle41,PgClassExpression42,Constant145 bucket1
    Bucket2("Bucket 2 (listItem)<br />ROOT __Item{2}ᐸ25ᐳ[44]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item44,PgSelectSingle45 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 45<br /><br />ROOT PgSelectSingle{2}ᐸnetworkᐳ[45]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor46,PgClassExpression47,List48,PgClassExpression50,PgClassExpression51,PgClassExpression52 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 69, 22, 37<br /><br />ROOT Connectionᐸ65ᐳ[69]<br />1: <br />ᐳ: PgPageInfo[70], Constant[146]<br />2: PgSelect[71], PgSelect[85]<br />ᐳ: 72, 73, 75, 76, 78, 79, 81, 82, 86, 87, 88, 74, 80"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgPageInfo70,PgSelect71,First72,PgSelectSingle73,PgCursor74,PgClassExpression75,List76,Last78,PgSelectSingle79,PgCursor80,PgClassExpression81,List82,PgSelect85,First86,PgSelectSingle87,PgClassExpression88,Constant146 bucket4
    Bucket5("Bucket 5 (listItem)<br />ROOT __Item{5}ᐸ71ᐳ[90]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item90,PgSelectSingle91 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 91<br /><br />ROOT PgSelectSingle{5}ᐸnetworkᐳ[91]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor92,PgClassExpression93,List94,PgClassExpression96,PgClassExpression97,PgClassExpression98 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 115, 22, 37<br /><br />ROOT Connectionᐸ111ᐳ[115]<br />1: <br />ᐳ: PgPageInfo[116], Constant[147]<br />2: PgSelect[117], PgSelect[131]<br />ᐳ: 118, 119, 121, 122, 124, 125, 127, 128, 132, 133, 134, 120, 126"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgPageInfo116,PgSelect117,First118,PgSelectSingle119,PgCursor120,PgClassExpression121,List122,Last124,PgSelectSingle125,PgCursor126,PgClassExpression127,List128,PgSelect131,First132,PgSelectSingle133,PgClassExpression134,Constant147 bucket7
    Bucket8("Bucket 8 (listItem)<br />ROOT __Item{8}ᐸ117ᐳ[136]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item136,PgSelectSingle137 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 137<br /><br />ROOT PgSelectSingle{8}ᐸnetworkᐳ[137]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgCursor138,PgClassExpression139,List140,PgClassExpression142,PgClassExpression143,PgClassExpression144 bucket9
    Bucket0 --> Bucket1 & Bucket4 & Bucket7
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9
    end
