%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object14{{"Object[14∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access12 & Access13 --> Object14
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access12
    __Value2 --> Access13
    Lambda143{{"Lambda[143∈0] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Constant231{{"Constant[231∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant231 --> Lambda143
    Lambda146{{"Lambda[146∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant232{{"Constant[232∈0] ➊<br />ᐸ§{ cursorLower: null, cursorUpper: null, first: null, last: ᐳ"}}:::plan
    Constant232 --> Lambda146
    Lambda161{{"Lambda[161∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant233{{"Constant[233∈0] ➊<br />ᐸ§{ cursorLower: null, cursorUpper: null, first: null, last: ᐳ"}}:::plan
    Constant233 --> Lambda161
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Connection15{{"Connection[15∈0] ➊<br />ᐸ11ᐳ"}}:::plan
    Connection59{{"Connection[59∈0] ➊<br />ᐸ57ᐳ"}}:::plan
    Connection103{{"Connection[103∈0] ➊<br />ᐸ101ᐳ"}}:::plan
    Constant147{{"Constant[147∈0] ➊<br />ᐸ[ { codec: { name: 'int4', sqlType: [Object], fromPg: [Functᐳ"}}:::plan
    Constant148{{"Constant[148∈0] ➊<br />ᐸ{ s: Symbol(network), n: 'network', [Symbol(pg-sql2-type-1)]ᐳ"}}:::plan
    Constant149{{"Constant[149∈0] ➊<br />ᐸ{ name: 'network', sqlType: { t: '”network_types”.”network”'ᐳ"}}:::plan
    Constant162{{"Constant[162∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant176{{"Constant[176∈0] ➊<br />ᐸ[ { codec: { name: 'int4', sqlType: [Object], fromPg: [Functᐳ"}}:::plan
    Constant177{{"Constant[177∈0] ➊<br />ᐸ{ s: Symbol(network), n: 'network', [Symbol(pg-sql2-type-1)]ᐳ"}}:::plan
    Constant190{{"Constant[190∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant204{{"Constant[204∈0] ➊<br />ᐸ[ { codec: { name: 'int4', sqlType: [Object], fromPg: [Functᐳ"}}:::plan
    Constant205{{"Constant[205∈0] ➊<br />ᐸ{ s: Symbol(network), n: 'network', [Symbol(pg-sql2-type-1)]ᐳ"}}:::plan
    Constant218{{"Constant[218∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant228{{"Constant[228∈0] ➊<br />ᐸ'192.168.0.0'ᐳ"}}:::plan
    Constant229{{"Constant[229∈0] ➊<br />ᐸ'192.168.0.0/16'ᐳ"}}:::plan
    Constant230{{"Constant[230∈0] ➊<br />ᐸ'08:00:2b:01:02:03'ᐳ"}}:::plan
    Constant234{{"Constant[234∈0] ➊<br />ᐸ§{ reverse: false, orders: [ { codec: [Object], fragment: [Oᐳ"}}:::plan
    Constant235{{"Constant[235∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: { s: Symbol(network), ᐳ"}}:::plan
    Constant236{{"Constant[236∈0] ➊<br />ᐸ§{ reverse: false, orders: [ { codec: [Object], fragment: [Oᐳ"}}:::plan
    Constant237{{"Constant[237∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: { s: Symbol(network), ᐳ"}}:::plan
    Constant238{{"Constant[238∈0] ➊<br />ᐸ§{ reverse: false, orders: [ { codec: [Object], fragment: [Oᐳ"}}:::plan
    Constant239{{"Constant[239∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: { s: Symbol(network), ᐳ"}}:::plan
    PgSelect16[["PgSelect[16∈1] ➊<br />ᐸnetwork+1ᐳ"]]:::plan
    Lambda151{{"Lambda[151∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda157{{"Lambda[157∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant228 & Connection15 & Lambda143 & Lambda146 & Lambda151 & Lambda157 --> PgSelect16
    PgSelect39[["PgSelect[39∈1] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Lambda166{{"Lambda[166∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda171{{"Lambda[171∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant228 & Connection15 & Lambda143 & Lambda161 & Lambda166 & Lambda171 --> PgSelect39
    Object37{{"Object[37∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access32{{"Access[32∈1] ➊<br />ᐸ16.hasMoreᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 & Access32 --> Object37
    Object150{{"Object[150∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant147 & Constant148 & Constant149 --> Object150
    Object165{{"Object[165∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant162 & Constant148 & Constant149 --> Object165
    Object33{{"Object[33∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant6 & Constant6 & Access32 --> Object33
    PgPageInfo17{{"PgPageInfo[17∈1] ➊"}}:::plan
    Connection15 --> PgPageInfo17
    First19{{"First[19∈1] ➊"}}:::plan
    PgSelect16 --> First19
    PgSelectSingle20{{"PgSelectSingle[20∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    First19 --> PgSelectSingle20
    PgCursor21{{"PgCursor[21∈1] ➊"}}:::plan
    List23{{"List[23∈1] ➊<br />ᐸ22ᐳ"}}:::plan
    List23 --> PgCursor21
    PgClassExpression22{{"PgClassExpression[22∈1] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression22
    PgClassExpression22 --> List23
    Last25{{"Last[25∈1] ➊"}}:::plan
    PgSelect16 --> Last25
    PgSelectSingle26{{"PgSelectSingle[26∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last25 --> PgSelectSingle26
    PgCursor27{{"PgCursor[27∈1] ➊"}}:::plan
    List29{{"List[29∈1] ➊<br />ᐸ28ᐳ"}}:::plan
    List29 --> PgCursor27
    PgClassExpression28{{"PgClassExpression[28∈1] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression28
    PgClassExpression28 --> List29
    PgSelect16 --> Access32
    Lambda34{{"Lambda[34∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object33 --> Lambda34
    Lambda38{{"Lambda[38∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object37 --> Lambda38
    First40{{"First[40∈1] ➊"}}:::plan
    PgSelect39 --> First40
    PgSelectSingle41{{"PgSelectSingle[41∈1] ➊<br />ᐸnetworkᐳ"}}:::plan
    First40 --> PgSelectSingle41
    PgClassExpression42{{"PgClassExpression[42∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression42
    Object150 --> Lambda151
    Constant234 --> Lambda157
    Object165 --> Lambda166
    Constant235 --> Lambda171
    __Item44[/"__Item[44∈2]<br />ᐸ16ᐳ"\]:::itemplan
    PgSelect16 ==> __Item44
    PgSelectSingle45{{"PgSelectSingle[45∈2]<br />ᐸnetworkᐳ"}}:::plan
    __Item44 --> PgSelectSingle45
    PgCursor46{{"PgCursor[46∈3]"}}:::plan
    List48{{"List[48∈3]<br />ᐸ47ᐳ"}}:::plan
    List48 --> PgCursor46
    PgClassExpression47{{"PgClassExpression[47∈3]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression47
    PgClassExpression47 --> List48
    PgClassExpression50{{"PgClassExpression[50∈3]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression50
    PgClassExpression51{{"PgClassExpression[51∈3]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression51
    PgClassExpression52{{"PgClassExpression[52∈3]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression52
    PgSelect60[["PgSelect[60∈4] ➊<br />ᐸnetwork+1ᐳ"]]:::plan
    Lambda180{{"Lambda[180∈4] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda185{{"Lambda[185∈4] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant229 & Connection59 & Lambda143 & Lambda146 & Lambda180 & Lambda185 --> PgSelect60
    PgSelect83[["PgSelect[83∈4] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Lambda194{{"Lambda[194∈4] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda199{{"Lambda[199∈4] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant229 & Connection59 & Lambda143 & Lambda161 & Lambda194 & Lambda199 --> PgSelect83
    Object81{{"Object[81∈4] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access76{{"Access[76∈4] ➊<br />ᐸ60.hasMoreᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 & Access76 --> Object81
    Object179{{"Object[179∈4] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant176 & Constant177 & Constant149 --> Object179
    Object193{{"Object[193∈4] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant190 & Constant177 & Constant149 --> Object193
    Object77{{"Object[77∈4] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant6 & Constant6 & Access76 --> Object77
    PgPageInfo61{{"PgPageInfo[61∈4] ➊"}}:::plan
    Connection59 --> PgPageInfo61
    First63{{"First[63∈4] ➊"}}:::plan
    PgSelect60 --> First63
    PgSelectSingle64{{"PgSelectSingle[64∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    First63 --> PgSelectSingle64
    PgCursor65{{"PgCursor[65∈4] ➊"}}:::plan
    List67{{"List[67∈4] ➊<br />ᐸ66ᐳ"}}:::plan
    List67 --> PgCursor65
    PgClassExpression66{{"PgClassExpression[66∈4] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle64 --> PgClassExpression66
    PgClassExpression66 --> List67
    Last69{{"Last[69∈4] ➊"}}:::plan
    PgSelect60 --> Last69
    PgSelectSingle70{{"PgSelectSingle[70∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last69 --> PgSelectSingle70
    PgCursor71{{"PgCursor[71∈4] ➊"}}:::plan
    List73{{"List[73∈4] ➊<br />ᐸ72ᐳ"}}:::plan
    List73 --> PgCursor71
    PgClassExpression72{{"PgClassExpression[72∈4] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle70 --> PgClassExpression72
    PgClassExpression72 --> List73
    PgSelect60 --> Access76
    Lambda78{{"Lambda[78∈4] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object77 --> Lambda78
    Lambda82{{"Lambda[82∈4] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object81 --> Lambda82
    First84{{"First[84∈4] ➊"}}:::plan
    PgSelect83 --> First84
    PgSelectSingle85{{"PgSelectSingle[85∈4] ➊<br />ᐸnetworkᐳ"}}:::plan
    First84 --> PgSelectSingle85
    PgClassExpression86{{"PgClassExpression[86∈4] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle85 --> PgClassExpression86
    Object179 --> Lambda180
    Constant236 --> Lambda185
    Object193 --> Lambda194
    Constant237 --> Lambda199
    __Item88[/"__Item[88∈5]<br />ᐸ60ᐳ"\]:::itemplan
    PgSelect60 ==> __Item88
    PgSelectSingle89{{"PgSelectSingle[89∈5]<br />ᐸnetworkᐳ"}}:::plan
    __Item88 --> PgSelectSingle89
    PgCursor90{{"PgCursor[90∈6]"}}:::plan
    List92{{"List[92∈6]<br />ᐸ91ᐳ"}}:::plan
    List92 --> PgCursor90
    PgClassExpression91{{"PgClassExpression[91∈6]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression91
    PgClassExpression91 --> List92
    PgClassExpression94{{"PgClassExpression[94∈6]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression94
    PgClassExpression95{{"PgClassExpression[95∈6]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression95
    PgClassExpression96{{"PgClassExpression[96∈6]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression96
    PgSelect104[["PgSelect[104∈7] ➊<br />ᐸnetwork+1ᐳ"]]:::plan
    Lambda208{{"Lambda[208∈7] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda213{{"Lambda[213∈7] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant230 & Connection103 & Lambda143 & Lambda146 & Lambda208 & Lambda213 --> PgSelect104
    PgSelect127[["PgSelect[127∈7] ➊<br />ᐸnetwork(aggregate)ᐳ"]]:::plan
    Lambda222{{"Lambda[222∈7] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda227{{"Lambda[227∈7] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object14 & Constant230 & Connection103 & Lambda143 & Lambda161 & Lambda222 & Lambda227 --> PgSelect127
    Object125{{"Object[125∈7] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access120{{"Access[120∈7] ➊<br />ᐸ104.hasMoreᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 & Access120 --> Object125
    Object207{{"Object[207∈7] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant204 & Constant205 & Constant149 --> Object207
    Object221{{"Object[221∈7] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda143 & Constant218 & Constant205 & Constant149 --> Object221
    Object121{{"Object[121∈7] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant6 & Constant6 & Access120 --> Object121
    PgPageInfo105{{"PgPageInfo[105∈7] ➊"}}:::plan
    Connection103 --> PgPageInfo105
    First107{{"First[107∈7] ➊"}}:::plan
    PgSelect104 --> First107
    PgSelectSingle108{{"PgSelectSingle[108∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    First107 --> PgSelectSingle108
    PgCursor109{{"PgCursor[109∈7] ➊"}}:::plan
    List111{{"List[111∈7] ➊<br />ᐸ110ᐳ"}}:::plan
    List111 --> PgCursor109
    PgClassExpression110{{"PgClassExpression[110∈7] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle108 --> PgClassExpression110
    PgClassExpression110 --> List111
    Last113{{"Last[113∈7] ➊"}}:::plan
    PgSelect104 --> Last113
    PgSelectSingle114{{"PgSelectSingle[114∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    Last113 --> PgSelectSingle114
    PgCursor115{{"PgCursor[115∈7] ➊"}}:::plan
    List117{{"List[117∈7] ➊<br />ᐸ116ᐳ"}}:::plan
    List117 --> PgCursor115
    PgClassExpression116{{"PgClassExpression[116∈7] ➊<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle114 --> PgClassExpression116
    PgClassExpression116 --> List117
    PgSelect104 --> Access120
    Lambda122{{"Lambda[122∈7] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object121 --> Lambda122
    Lambda126{{"Lambda[126∈7] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object125 --> Lambda126
    First128{{"First[128∈7] ➊"}}:::plan
    PgSelect127 --> First128
    PgSelectSingle129{{"PgSelectSingle[129∈7] ➊<br />ᐸnetworkᐳ"}}:::plan
    First128 --> PgSelectSingle129
    PgClassExpression130{{"PgClassExpression[130∈7] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression130
    Object207 --> Lambda208
    Constant238 --> Lambda213
    Object221 --> Lambda222
    Constant239 --> Lambda227
    __Item132[/"__Item[132∈8]<br />ᐸ104ᐳ"\]:::itemplan
    PgSelect104 ==> __Item132
    PgSelectSingle133{{"PgSelectSingle[133∈8]<br />ᐸnetworkᐳ"}}:::plan
    __Item132 --> PgSelectSingle133
    PgCursor134{{"PgCursor[134∈9]"}}:::plan
    List136{{"List[136∈9]<br />ᐸ135ᐳ"}}:::plan
    List136 --> PgCursor134
    PgClassExpression135{{"PgClassExpression[135∈9]<br />ᐸ__network__.”id”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression135
    PgClassExpression135 --> List136
    PgClassExpression138{{"PgClassExpression[138∈9]<br />ᐸ__network__.”inet”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression138
    PgClassExpression139{{"PgClassExpression[139∈9]<br />ᐸ__network__.”cidr”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression139
    PgClassExpression140{{"PgClassExpression[140∈9]<br />ᐸ__network__.”macaddr”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression140

    %% define steps

    subgraph "Buckets for queries/v4/network_types"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access12,Access13,Object14,Connection15,Connection59,Connection103,Lambda143,Lambda146,Constant147,Constant148,Constant149,Lambda161,Constant162,Constant176,Constant177,Constant190,Constant204,Constant205,Constant218,Constant228,Constant229,Constant230,Constant231,Constant232,Constant233,Constant234,Constant235,Constant236,Constant237,Constant238,Constant239 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 14, 228, 15, 143, 146, 6, 161, 147, 148, 149, 234, 162, 235<br /><br />ROOT Connectionᐸ11ᐳ[15]<br />1: <br />ᐳ: 17, 150, 157, 165, 171, 151, 166<br />2: PgSelect[16], PgSelect[39]<br />ᐳ: 19, 20, 22, 23, 25, 26, 28, 29, 32, 33, 34, 37, 38, 40, 41, 42, 21, 27"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect16,PgPageInfo17,First19,PgSelectSingle20,PgCursor21,PgClassExpression22,List23,Last25,PgSelectSingle26,PgCursor27,PgClassExpression28,List29,Access32,Object33,Lambda34,Object37,Lambda38,PgSelect39,First40,PgSelectSingle41,PgClassExpression42,Object150,Lambda151,Lambda157,Object165,Lambda166,Lambda171 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ16ᐳ[44]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item44,PgSelectSingle45 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 45<br /><br />ROOT PgSelectSingle{2}ᐸnetworkᐳ[45]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor46,PgClassExpression47,List48,PgClassExpression50,PgClassExpression51,PgClassExpression52 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 14, 229, 59, 143, 146, 6, 161, 176, 177, 149, 236, 190, 237<br /><br />ROOT Connectionᐸ57ᐳ[59]<br />1: <br />ᐳ: 61, 179, 185, 193, 199, 180, 194<br />2: PgSelect[60], PgSelect[83]<br />ᐳ: 63, 64, 66, 67, 69, 70, 72, 73, 76, 77, 78, 81, 82, 84, 85, 86, 65, 71"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect60,PgPageInfo61,First63,PgSelectSingle64,PgCursor65,PgClassExpression66,List67,Last69,PgSelectSingle70,PgCursor71,PgClassExpression72,List73,Access76,Object77,Lambda78,Object81,Lambda82,PgSelect83,First84,PgSelectSingle85,PgClassExpression86,Object179,Lambda180,Lambda185,Object193,Lambda194,Lambda199 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ60ᐳ[88]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item88,PgSelectSingle89 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 89<br /><br />ROOT PgSelectSingle{5}ᐸnetworkᐳ[89]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor90,PgClassExpression91,List92,PgClassExpression94,PgClassExpression95,PgClassExpression96 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 14, 230, 103, 143, 146, 6, 161, 204, 205, 149, 238, 218, 239<br /><br />ROOT Connectionᐸ101ᐳ[103]<br />1: <br />ᐳ: 105, 207, 213, 221, 227, 208, 222<br />2: PgSelect[104], PgSelect[127]<br />ᐳ: 107, 108, 110, 111, 113, 114, 116, 117, 120, 121, 122, 125, 126, 128, 129, 130, 109, 115"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect104,PgPageInfo105,First107,PgSelectSingle108,PgCursor109,PgClassExpression110,List111,Last113,PgSelectSingle114,PgCursor115,PgClassExpression116,List117,Access120,Object121,Lambda122,Object125,Lambda126,PgSelect127,First128,PgSelectSingle129,PgClassExpression130,Object207,Lambda208,Lambda213,Object221,Lambda222,Lambda227 bucket7
    Bucket8("Bucket 8 (listItem)<br /><br />ROOT __Item{8}ᐸ104ᐳ[132]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item132,PgSelectSingle133 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 133<br /><br />ROOT PgSelectSingle{8}ᐸnetworkᐳ[133]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgCursor134,PgClassExpression135,List136,PgClassExpression138,PgClassExpression139,PgClassExpression140 bucket9
    Bucket0 --> Bucket1 & Bucket4 & Bucket7
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9
    end
