%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/nodeId-earlyExit"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 11, 16, 18, 21, 44, 73, 79, 85, 86, 87, 88, 12, 19, 22, 25, 27, 38, 45, 48, 50<br />2: PgSelect[30], PgSelect[53]<br />3: PgSelectRows[35], PgSelectRows[58]<br />ᐳ: 34, 37, 57, 60"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 19, 22, 21, 73<br /><br />ROOT Connectionᐸ15ᐳ[21]<br />1: PgSelect[61]<br />2: PgSelectRows[67]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 37<br /><br />ROOT PgSelectSingleᐸpersonᐳ[37]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 45, 44, 79<br /><br />ROOT Connectionᐸ41ᐳ[44]<br />1: PgSelect[64]<br />2: PgSelectRows[70]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 60<br /><br />ROOT PgSelectSingleᐸpersonᐳ[60]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 73<br /><br />ROOT __Item{5}ᐸ67ᐳ[68]"):::bucket
    Bucket6("Bucket 6 (listItem)<br />Deps: 79<br /><br />ROOT __Item{6}ᐸ70ᐳ[71]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 69, 73<br /><br />ROOT PgSelectSingle{5}ᐸpersonᐳ[69]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 72, 79<br /><br />ROOT PgSelectSingle{6}ᐸpostᐳ[72]"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4
    Bucket1 --> Bucket5
    Bucket3 --> Bucket6
    Bucket5 --> Bucket7
    Bucket6 --> Bucket8

    %% plan dependencies
    __InputObject12{{"__InputObject[12∈0] ➊"}}:::plan
    Constant85{{"Constant[85∈0] ➊<br />ᐸ'Twenty Seventwo'ᐳ"}}:::plan
    Constant85 --> __InputObject12
    Object19{{"Object[19∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access16{{"Access[16∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access18{{"Access[18∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access16 & Access18 --> Object19
    PgSelect30[["PgSelect[30∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Access27{{"Access[27∈0] ➊<br />ᐸ25.1ᐳ"}}:::plan
    Object19 -->|rejectNull| PgSelect30
    Access27 --> PgSelect30
    __InputObject38{{"__InputObject[38∈0] ➊"}}:::plan
    Constant87{{"Constant[87∈0] ➊<br />ᐸ'Is that a cooking show?'ᐳ"}}:::plan
    Constant87 --> __InputObject38
    PgSelect53[["PgSelect[53∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Access50{{"Access[50∈0] ➊<br />ᐸ48.1ᐳ"}}:::plan
    Object19 -->|rejectNull| PgSelect53
    Access50 --> PgSelect53
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access16
    __Value2 --> Access18
    ApplyInput22{{"ApplyInput[22∈0] ➊"}}:::plan
    __InputObject12 --> ApplyInput22
    Lambda25{{"Lambda[25∈0] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant86{{"Constant[86∈0] ➊<br />ᐸ'WyJwZW9wbGUiLDZd'ᐳ"}}:::plan
    Constant86 --> Lambda25
    Lambda25 --> Access27
    First34{{"First[34∈0] ➊"}}:::plan
    PgSelectRows35[["PgSelectRows[35∈0] ➊"]]:::plan
    PgSelectRows35 --> First34
    PgSelect30 --> PgSelectRows35
    PgSelectSingle37{{"PgSelectSingle[37∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First34 --> PgSelectSingle37
    ApplyInput45{{"ApplyInput[45∈0] ➊"}}:::plan
    __InputObject38 --> ApplyInput45
    Lambda48{{"Lambda[48∈0] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant88{{"Constant[88∈0] ➊<br />ᐸ'WyJwb3N0cyIsM10='ᐳ"}}:::plan
    Constant88 --> Lambda48
    Lambda48 --> Access50
    First57{{"First[57∈0] ➊"}}:::plan
    PgSelectRows58[["PgSelectRows[58∈0] ➊"]]:::plan
    PgSelectRows58 --> First57
    PgSelect53 --> PgSelectRows58
    PgSelectSingle60{{"PgSelectSingle[60∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First57 --> PgSelectSingle60
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection21{{"Connection[21∈0] ➊<br />ᐸ15ᐳ"}}:::plan
    Connection44{{"Connection[44∈0] ➊<br />ᐸ41ᐳ"}}:::plan
    Constant73{{"Constant[73∈0] ➊<br />ᐸ'people'ᐳ"}}:::plan
    Constant79{{"Constant[79∈0] ➊<br />ᐸ'posts'ᐳ"}}:::plan
    PgSelect61[["PgSelect[61∈1] ➊<br />ᐸpersonᐳ"]]:::plan
    Object19 & ApplyInput22 & Connection21 --> PgSelect61
    PgSelectRows67[["PgSelectRows[67∈1] ➊"]]:::plan
    PgSelect61 --> PgSelectRows67
    __Item68[/"__Item[68∈5]<br />ᐸ67ᐳ"\]:::itemplan
    PgSelectRows67 ==> __Item68
    PgSelectSingle69{{"PgSelectSingle[69∈5]<br />ᐸpersonᐳ"}}:::plan
    __Item68 --> PgSelectSingle69
    List75{{"List[75∈7]<br />ᐸ73,74ᐳ"}}:::plan
    PgClassExpression74{{"PgClassExpression[74∈7]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant73 & PgClassExpression74 --> List75
    PgSelectSingle69 --> PgClassExpression74
    Lambda76{{"Lambda[76∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List75 --> Lambda76
    PgClassExpression78{{"PgClassExpression[78∈7]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression78
    PgClassExpression63{{"PgClassExpression[63∈2] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression63
    PgSelect64[["PgSelect[64∈3] ➊<br />ᐸpostᐳ"]]:::plan
    Object19 & ApplyInput45 & Connection44 --> PgSelect64
    PgSelectRows70[["PgSelectRows[70∈3] ➊"]]:::plan
    PgSelect64 --> PgSelectRows70
    __Item71[/"__Item[71∈6]<br />ᐸ70ᐳ"\]:::itemplan
    PgSelectRows70 ==> __Item71
    PgSelectSingle72{{"PgSelectSingle[72∈6]<br />ᐸpostᐳ"}}:::plan
    __Item71 --> PgSelectSingle72
    List81{{"List[81∈8]<br />ᐸ79,80ᐳ"}}:::plan
    PgClassExpression80{{"PgClassExpression[80∈8]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant79 & PgClassExpression80 --> List81
    PgSelectSingle72 --> PgClassExpression80
    Lambda82{{"Lambda[82∈8]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List81 --> Lambda82
    PgClassExpression84{{"PgClassExpression[84∈8]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle72 --> PgClassExpression84
    PgClassExpression66{{"PgClassExpression[66∈4] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle60 --> PgClassExpression66

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,__InputObject12,Access16,Access18,Object19,Connection21,ApplyInput22,Lambda25,Access27,PgSelect30,First34,PgSelectRows35,PgSelectSingle37,__InputObject38,Connection44,ApplyInput45,Lambda48,Access50,PgSelect53,First57,PgSelectRows58,PgSelectSingle60,Constant73,Constant79,Constant85,Constant86,Constant87,Constant88 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect61,PgSelectRows67 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression63 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelect64,PgSelectRows70 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression66 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item68,PgSelectSingle69 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item71,PgSelectSingle72 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression74,List75,Lambda76,PgClassExpression78 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression80,List81,Lambda82,PgClassExpression84 bucket8

