%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object35{{"Object[35∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access33{{"Access[33∈0]<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access34{{"Access[34∈0]<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access33 & Access34 --> Object35
    PgSelect49[["PgSelect[49∈0]<br />ᐸpersonᐳ"]]:::plan
    Access47{{"Access[47∈0]<br />ᐸ46.1ᐳ"}}:::plan
    Object35 -->|rejectNull| PgSelect49
    Access47 --> PgSelect49
    PgSelect88[["PgSelect[88∈0]<br />ᐸpersonᐳ"]]:::plan
    Access86{{"Access[86∈0]<br />ᐸ85.1ᐳ"}}:::plan
    Object35 -->|rejectNull| PgSelect88
    Access86 --> PgSelect88
    __Value2["__Value[2∈0]<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access33
    __Value2 --> Access34
    Lambda46{{"Lambda[46∈0]<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant96{{"Constant[96∈0]<br />ᐸ'WyJwZW9wbGUiLDZd'ᐳ"}}:::plan
    Constant96 --> Lambda46
    Lambda46 --> Access47
    First53{{"First[53∈0]"}}:::plan
    PgSelect49 --> First53
    PgSelectSingle54{{"PgSelectSingle[54∈0]<br />ᐸpersonᐳ"}}:::plan
    First53 --> PgSelectSingle54
    Lambda85{{"Lambda[85∈0]<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant98{{"Constant[98∈0]<br />ᐸ'WyJwb3N0cyIsM10='ᐳ"}}:::plan
    Constant98 --> Lambda85
    Lambda85 --> Access86
    First92{{"First[92∈0]"}}:::plan
    PgSelect88 --> First92
    PgSelectSingle93{{"PgSelectSingle[93∈0]<br />ᐸpersonᐳ"}}:::plan
    First92 --> PgSelectSingle93
    __Value4["__Value[4∈0]<br />ᐸrootValueᐳ"]:::plan
    Connection36{{"Connection[36∈0]<br />ᐸ32ᐳ"}}:::plan
    Connection75{{"Connection[75∈0]<br />ᐸ71ᐳ"}}:::plan
    PgSelect37[["PgSelect[37∈1]<br />ᐸpersonᐳ"]]:::plan
    Constant95{{"Constant[95∈1]<br />ᐸ'Twenty Seventwo'ᐳ"}}:::plan
    Object35 & Constant95 & Connection36 --> PgSelect37
    Constant40{{"Constant[40∈1]<br />ᐸ'people'ᐳ"}}:::plan
    __Item38[/"__Item[38∈2]<br />ᐸ37ᐳ"\]:::itemplan
    PgSelect37 ==> __Item38
    PgSelectSingle39{{"PgSelectSingle[39∈2]<br />ᐸpersonᐳ"}}:::plan
    __Item38 --> PgSelectSingle39
    List42{{"List[42∈3]<br />ᐸ40,41ᐳ"}}:::plan
    PgClassExpression41{{"PgClassExpression[41∈3]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant40 & PgClassExpression41 --> List42
    PgSelectSingle39 --> PgClassExpression41
    Lambda43{{"Lambda[43∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List42 --> Lambda43
    PgClassExpression44{{"PgClassExpression[44∈3]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression44
    PgClassExpression55{{"PgClassExpression[55∈4]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression55
    PgSelect76[["PgSelect[76∈5]<br />ᐸpostᐳ"]]:::plan
    Constant97{{"Constant[97∈5]<br />ᐸ'Is that a cooking show?'ᐳ"}}:::plan
    Object35 & Constant97 & Connection75 --> PgSelect76
    Constant79{{"Constant[79∈5]<br />ᐸ'posts'ᐳ"}}:::plan
    __Item77[/"__Item[77∈6]<br />ᐸ76ᐳ"\]:::itemplan
    PgSelect76 ==> __Item77
    PgSelectSingle78{{"PgSelectSingle[78∈6]<br />ᐸpostᐳ"}}:::plan
    __Item77 --> PgSelectSingle78
    List81{{"List[81∈7]<br />ᐸ79,80ᐳ"}}:::plan
    PgClassExpression80{{"PgClassExpression[80∈7]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant79 & PgClassExpression80 --> List81
    PgSelectSingle78 --> PgClassExpression80
    Lambda82{{"Lambda[82∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List81 --> Lambda82
    PgClassExpression83{{"PgClassExpression[83∈7]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle78 --> PgClassExpression83
    PgClassExpression94{{"PgClassExpression[94∈8]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression94

    %% define steps

    subgraph "Buckets for queries/v4/nodeId-earlyExit"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: 33, 34, 36, 75, 96, 98, 35, 46, 47, 85, 86<br />2: PgSelect[49], PgSelect[88]<br />ᐳ: 53, 54, 92, 93"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access33,Access34,Object35,Connection36,Lambda46,Access47,PgSelect49,First53,PgSelectSingle54,Connection75,Lambda85,Access86,PgSelect88,First92,PgSelectSingle93,Constant96,Constant98 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 35, 36<br /><br />ROOT Connectionᐸ32ᐳ[36]<br />1: <br />ᐳ: Constant[40], Constant[95]<br />2: PgSelect[37]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect37,Constant40,Constant95 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 40<br /><br />ROOT __Item{2}ᐸ37ᐳ[38]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item38,PgSelectSingle39 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 39, 40<br /><br />ROOT PgSelectSingle{2}ᐸpersonᐳ[39]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression41,List42,Lambda43,PgClassExpression44 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 54<br /><br />ROOT PgSelectSingleᐸpersonᐳ[54]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression55 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 35, 75<br /><br />ROOT Connectionᐸ71ᐳ[75]<br />1: <br />ᐳ: Constant[79], Constant[97]<br />2: PgSelect[76]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect76,Constant79,Constant97 bucket5
    Bucket6("Bucket 6 (listItem)<br />Deps: 79<br /><br />ROOT __Item{6}ᐸ76ᐳ[77]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item77,PgSelectSingle78 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 78, 79<br /><br />ROOT PgSelectSingle{6}ᐸpostᐳ[78]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression80,List81,Lambda82,PgClassExpression83 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 93<br /><br />ROOT PgSelectSingleᐸpersonᐳ[93]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression94 bucket8
    Bucket0 --> Bucket1 & Bucket4 & Bucket5 & Bucket8
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket5 --> Bucket6
    Bucket6 --> Bucket7
    classDef unary fill:#fafffa,borderWidth:8px
    class Object35,PgSelect49,PgSelect88,Access33,Access34,Lambda46,Access47,First53,PgSelectSingle54,Lambda85,Access86,First92,PgSelectSingle93,__Value2,__Value4,Connection36,Connection75,Constant96,Constant98,PgSelect37,Constant40,Constant95,PgClassExpression55,PgSelect76,Constant79,Constant97,PgClassExpression94 unary
    end
