%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection13
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant73{{"Constant[73∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant73 --> Lambda14
    ApplyInput15{{"ApplyInput[15∈0] ➊"}}:::plan
    Constant6 --> ApplyInput15
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant33{{"Constant[33∈0] ➊<br />ᐸ'left_arms'ᐳ"}}:::plan
    Constant55{{"Constant[55∈0] ➊<br />ᐸ'person_secrets'ᐳ"}}:::plan
    PgSelect16[["PgSelect[16∈1] ➊<br />ᐸpersonᐳ"]]:::plan
    Object12 & Lambda14 & ApplyInput15 & Connection13 & Constant6 & Constant6 & Constant6 --> PgSelect16
    PgSelectRows17[["PgSelectRows[17∈1] ➊"]]:::plan
    PgSelect16 --> PgSelectRows17
    Access20{{"Access[20∈1] ➊<br />ᐸ16.cursorDetailsᐳ"}}:::plan
    PgSelect16 --> Access20
    __Item18[/"__Item[18∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelectRows17 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈2]<br />ᐸpersonᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgCursor21{{"PgCursor[21∈3]"}}:::plan
    PgSelectSingle19 & Access20 --> PgCursor21
    PgSelect26[["PgSelect[26∈3]<br />ᐸleft_armᐳ"]]:::plan
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Object12 & PgClassExpression22 --> PgSelect26
    PgSelect50[["PgSelect[50∈3]<br />ᐸperson_secretᐳ"]]:::plan
    Object12 & PgClassExpression22 --> PgSelect50
    PgSelectSingle19 --> PgClassExpression22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression23
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression25
    First30{{"First[30∈3]"}}:::plan
    PgSelectRows31[["PgSelectRows[31∈3]"]]:::plan
    PgSelectRows31 --> First30
    PgSelect26 --> PgSelectRows31
    PgSelectSingle32{{"PgSelectSingle[32∈3]<br />ᐸleft_armᐳ"}}:::plan
    First30 --> PgSelectSingle32
    First52{{"First[52∈3]"}}:::plan
    PgSelectRows53[["PgSelectRows[53∈3]"]]:::plan
    PgSelectRows53 --> First52
    PgSelect50 --> PgSelectRows53
    PgSelectSingle54{{"PgSelectSingle[54∈3]<br />ᐸperson_secretᐳ"}}:::plan
    First52 --> PgSelectSingle54
    List35{{"List[35∈4]<br />ᐸ33,34ᐳ"}}:::plan
    PgClassExpression34{{"PgClassExpression[34∈4]<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    Constant33 & PgClassExpression34 --> List35
    PgSelect38[["PgSelect[38∈4]<br />ᐸpersonᐳ"]]:::plan
    PgClassExpression37{{"PgClassExpression[37∈4]<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    Object12 & PgClassExpression37 --> PgSelect38
    PgSelectSingle32 --> PgClassExpression34
    Lambda36{{"Lambda[36∈4]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List35 --> Lambda36
    PgSelectSingle32 --> PgClassExpression37
    First42{{"First[42∈4]"}}:::plan
    PgSelectRows43[["PgSelectRows[43∈4]"]]:::plan
    PgSelectRows43 --> First42
    PgSelect38 --> PgSelectRows43
    PgSelectSingle44{{"PgSelectSingle[44∈4]<br />ᐸpersonᐳ"}}:::plan
    First42 --> PgSelectSingle44
    PgClassExpression49{{"PgClassExpression[49∈4]<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression49
    PgClassExpression45{{"PgClassExpression[45∈5]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression45
    PgClassExpression46{{"PgClassExpression[46∈5]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression46
    PgClassExpression48{{"PgClassExpression[48∈5]<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression48
    List57{{"List[57∈6]<br />ᐸ55,56ᐳ"}}:::plan
    PgClassExpression56{{"PgClassExpression[56∈6]<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant55 & PgClassExpression56 --> List57
    PgSelect59[["PgSelect[59∈6]<br />ᐸpersonᐳ"]]:::plan
    Object12 & PgClassExpression56 --> PgSelect59
    PgSelectSingle54 --> PgClassExpression56
    Lambda58{{"Lambda[58∈6]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List57 --> Lambda58
    First63{{"First[63∈6]"}}:::plan
    PgSelectRows64[["PgSelectRows[64∈6]"]]:::plan
    PgSelectRows64 --> First63
    PgSelect59 --> PgSelectRows64
    PgSelectSingle65{{"PgSelectSingle[65∈6]<br />ᐸpersonᐳ"}}:::plan
    First63 --> PgSelectSingle65
    PgClassExpression70{{"PgClassExpression[70∈6]<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression70
    PgClassExpression66{{"PgClassExpression[66∈7]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    PgSelectSingle65 --> PgClassExpression66
    PgClassExpression67{{"PgClassExpression[67∈7]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle65 --> PgClassExpression67
    PgClassExpression69{{"PgClassExpression[69∈7]<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle65 --> PgClassExpression69

    %% define steps

    subgraph "Buckets for queries/v4/one-to-one-backward"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access10,Access11,Object12,Connection13,Lambda14,ApplyInput15,Constant33,Constant55,Constant73 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 15, 13, 6, 33, 55<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[16]<br />ᐳ: Access[20]<br />2: PgSelectRows[17]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect16,PgSelectRows17,Access20 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 20, 12, 33, 55<br /><br />ROOT __Item{2}ᐸ17ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgSelectSingle19 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 20, 12, 33, 55<br /><br />ROOT PgSelectSingle{2}ᐸpersonᐳ[19]<br />1: <br />ᐳ: 21, 22, 23, 25<br />2: PgSelect[26], PgSelect[50]<br />3: PgSelectRows[31], PgSelectRows[53]<br />ᐳ: 30, 32, 52, 54"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor21,PgClassExpression22,PgClassExpression23,PgClassExpression25,PgSelect26,First30,PgSelectRows31,PgSelectSingle32,PgSelect50,First52,PgSelectRows53,PgSelectSingle54 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 32, 33, 12<br /><br />ROOT PgSelectSingle{3}ᐸleft_armᐳ[32]<br />1: <br />ᐳ: 34, 37, 49, 35, 36<br />2: PgSelect[38]<br />3: PgSelectRows[43]<br />ᐳ: First[42], PgSelectSingle[44]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression34,List35,Lambda36,PgClassExpression37,PgSelect38,First42,PgSelectRows43,PgSelectSingle44,PgClassExpression49 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 44<br /><br />ROOT PgSelectSingle{4}ᐸpersonᐳ[44]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression45,PgClassExpression46,PgClassExpression48 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 54, 55, 12<br /><br />ROOT PgSelectSingle{3}ᐸperson_secretᐳ[54]<br />1: <br />ᐳ: 56, 70, 57, 58<br />2: PgSelect[59]<br />3: PgSelectRows[64]<br />ᐳ: First[63], PgSelectSingle[65]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression56,List57,Lambda58,PgSelect59,First63,PgSelectRows64,PgSelectSingle65,PgClassExpression70 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 65<br /><br />ROOT PgSelectSingle{6}ᐸpersonᐳ[65]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression66,PgClassExpression67,PgClassExpression69 bucket7
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket6
    Bucket4 --> Bucket5
    Bucket6 --> Bucket7
    end
