%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection18{{"Connection[18∈0] ➊<br />ᐸ14ᐳ"}}:::plan
    Object69{{"Object[69∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Constant6{{"Constant[6∈1] ➊<br />ᐸundefinedᐳ"}}:::plan
    Access61{{"Access[61∈1] ➊<br />ᐸ19.hasMoreᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 & Access61 --> Object69
    Object62{{"Object[62∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant6 & Constant6 & Access61 --> Object62
    Object17{{"Object[17∈1] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈1] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈1] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    PgSelect19[["PgSelect[19∈1] ➊<br />ᐸmeasurements+1ᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect19
    PgSelect38[["PgSelect[38∈1] ➊<br />ᐸmeasurements(aggregate)ᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect38
    List50{{"List[50∈1] ➊<br />ᐸ48,49ᐳ"}}:::plan
    PgClassExpression48{{"PgClassExpression[48∈1] ➊<br />ᐸ__measurem...timestamp”ᐳ"}}:::plan
    PgClassExpression49{{"PgClassExpression[49∈1] ➊<br />ᐸ__measurements__.”key”ᐳ"}}:::plan
    PgClassExpression48 & PgClassExpression49 --> List50
    List57{{"List[57∈1] ➊<br />ᐸ55,56ᐳ"}}:::plan
    PgClassExpression55{{"PgClassExpression[55∈1] ➊<br />ᐸ__measurem...timestamp”ᐳ"}}:::plan
    PgClassExpression56{{"PgClassExpression[56∈1] ➊<br />ᐸ__measurements__.”key”ᐳ"}}:::plan
    PgClassExpression55 & PgClassExpression56 --> List57
    __Value2 --> Access15
    __Value2 --> Access16
    First39{{"First[39∈1] ➊"}}:::plan
    PgSelect38 --> First39
    PgSelectSingle40{{"PgSelectSingle[40∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    First39 --> PgSelectSingle40
    PgClassExpression41{{"PgClassExpression[41∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression41
    PgPageInfo43{{"PgPageInfo[43∈1] ➊"}}:::plan
    Connection18 --> PgPageInfo43
    First45{{"First[45∈1] ➊"}}:::plan
    PgSelect19 --> First45
    PgSelectSingle46{{"PgSelectSingle[46∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    First45 --> PgSelectSingle46
    PgCursor47{{"PgCursor[47∈1] ➊"}}:::plan
    List50 --> PgCursor47
    PgSelectSingle46 --> PgClassExpression48
    PgSelectSingle46 --> PgClassExpression49
    Last52{{"Last[52∈1] ➊"}}:::plan
    PgSelect19 --> Last52
    PgSelectSingle53{{"PgSelectSingle[53∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    Last52 --> PgSelectSingle53
    PgCursor54{{"PgCursor[54∈1] ➊"}}:::plan
    List57 --> PgCursor54
    PgSelectSingle53 --> PgClassExpression55
    PgSelectSingle53 --> PgClassExpression56
    PgSelect19 --> Access61
    Lambda63{{"Lambda[63∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object62 --> Lambda63
    Lambda70{{"Lambda[70∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object69 --> Lambda70
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelect19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸmeasurementsᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    List25{{"List[25∈3]<br />ᐸ23,24ᐳ"}}:::plan
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__measurem...timestamp”ᐳ"}}:::plan
    PgClassExpression24{{"PgClassExpression[24∈3]<br />ᐸ__measurements__.”key”ᐳ"}}:::plan
    PgClassExpression23 & PgClassExpression24 --> List25
    PgCursor22{{"PgCursor[22∈3]"}}:::plan
    List25 --> PgCursor22
    PgSelectSingle21 --> PgClassExpression23
    PgSelectSingle21 --> PgClassExpression24
    PgClassExpression28{{"PgClassExpression[28∈3]<br />ᐸ__measurem...__.”value”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression28
    PgSelectSingle35{{"PgSelectSingle[35∈3]<br />ᐸusersᐳ"}}:::plan
    RemapKeys71{{"RemapKeys[71∈3]<br />ᐸ21:{”0”:3,”1”:4}ᐳ"}}:::plan
    RemapKeys71 --> PgSelectSingle35
    PgSelectSingle21 --> RemapKeys71
    PgClassExpression36{{"PgClassExpression[36∈4]<br />ᐸ__users__.”id”ᐳ"}}:::plan
    PgSelectSingle35 --> PgClassExpression36
    PgClassExpression37{{"PgClassExpression[37∈4]<br />ᐸ__users__.”name”ᐳ"}}:::plan
    PgSelectSingle35 --> PgClassExpression37

    %% define steps

    subgraph "Buckets for queries/v4/partitions"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Connection18 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 2, 18<br /><br />ROOT Connectionᐸ14ᐳ[18]<br />1: <br />ᐳ: 6, 15, 16, 43, 17<br />2: PgSelect[19], PgSelect[38]<br />ᐳ: 39, 40, 41, 45, 46, 48, 49, 50, 52, 53, 55, 56, 57, 61, 62, 63, 69, 70, 47, 54"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Constant6,Access15,Access16,Object17,PgSelect19,PgSelect38,First39,PgSelectSingle40,PgClassExpression41,PgPageInfo43,First45,PgSelectSingle46,PgCursor47,PgClassExpression48,PgClassExpression49,List50,Last52,PgSelectSingle53,PgCursor54,PgClassExpression55,PgClassExpression56,List57,Access61,Object62,Lambda63,Object69,Lambda70 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21<br /><br />ROOT PgSelectSingle{2}ᐸmeasurementsᐳ[21]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor22,PgClassExpression23,PgClassExpression24,List25,PgClassExpression28,PgSelectSingle35,RemapKeys71 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 35<br /><br />ROOT PgSelectSingle{3}ᐸusersᐳ[35]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression36,PgClassExpression37 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
