%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    PgSelectInlineApply61["PgSelectInlineApply[61∈0] ➊"]:::plan
    Object46{{"Object[46∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access41{{"Access[41∈1] ➊<br />ᐸ14.hasMoreᐳ"}}:::plan
    Access41 --> Object46
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸmeasurements+1ᐳ"]]:::plan
    Object11 & Connection12 & PgSelectInlineApply61 --> PgSelect14
    Object42{{"Object[42∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Access41 --> Object42
    PgSelect18[["PgSelect[18∈1] ➊<br />ᐸmeasurements(aggregate)ᐳ"]]:::plan
    Object11 & Connection12 --> PgSelect18
    PgCursor32{{"PgCursor[32∈1] ➊"}}:::plan
    PgSelectSingle30{{"PgSelectSingle[30∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    Access25{{"Access[25∈1] ➊<br />ᐸ14.cursorDetailsᐳ"}}:::plan
    PgSelectSingle30 & Access25 --> PgCursor32
    PgCursor38{{"PgCursor[38∈1] ➊"}}:::plan
    PgSelectSingle36{{"PgSelectSingle[36∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    PgSelectSingle36 & Access25 --> PgCursor38
    PgSelectRows15[["PgSelectRows[15∈1] ➊"]]:::plan
    PgSelect14 --> PgSelectRows15
    First19{{"First[19∈1] ➊"}}:::plan
    PgSelectRows20[["PgSelectRows[20∈1] ➊"]]:::plan
    PgSelectRows20 --> First19
    PgSelect18 --> PgSelectRows20
    PgSelectSingle21{{"PgSelectSingle[21∈1] ➊<br />ᐸmeasurementsᐳ"}}:::plan
    First19 --> PgSelectSingle21
    PgClassExpression22{{"PgClassExpression[22∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression22
    PgPageInfo24{{"PgPageInfo[24∈1] ➊"}}:::plan
    Connection12 --> PgPageInfo24
    PgSelect14 --> Access25
    First28{{"First[28∈1] ➊"}}:::plan
    PgSelectRows15 --> First28
    First28 --> PgSelectSingle30
    Last34{{"Last[34∈1] ➊"}}:::plan
    PgSelectRows15 --> Last34
    Last34 --> PgSelectSingle36
    PgSelect14 --> Access41
    Lambda43{{"Lambda[43∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object42 --> Lambda43
    Lambda47{{"Lambda[47∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object46 --> Lambda47
    Access62{{"Access[62∈1] ➊<br />ᐸ14.m.joinDetailsFor52ᐳ"}}:::plan
    PgSelect14 --> Access62
    __Item16[/"__Item[16∈2]<br />ᐸ15ᐳ"\]:::itemplan
    PgSelectRows15 ==> __Item16
    PgSelectSingle17{{"PgSelectSingle[17∈2]<br />ᐸmeasurementsᐳ"}}:::plan
    __Item16 --> PgSelectSingle17
    PgCursor26{{"PgCursor[26∈3]"}}:::plan
    PgSelectSingle17 & Access25 --> PgCursor26
    List63{{"List[63∈3]<br />ᐸ62,17ᐳ"}}:::plan
    Access62 & PgSelectSingle17 --> List63
    PgClassExpression48{{"PgClassExpression[48∈3]<br />ᐸ__measurem...timestamp”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression48
    PgClassExpression49{{"PgClassExpression[49∈3]<br />ᐸ__measurements__.”key”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression49
    PgClassExpression50{{"PgClassExpression[50∈3]<br />ᐸ__measurem...__.”value”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression50
    First56{{"First[56∈3]"}}:::plan
    PgSelectRows57[["PgSelectRows[57∈3]"]]:::plan
    PgSelectRows57 --> First56
    Lambda64{{"Lambda[64∈3]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda64 --> PgSelectRows57
    PgSelectSingle58{{"PgSelectSingle[58∈3]<br />ᐸusersᐳ"}}:::plan
    First56 --> PgSelectSingle58
    List63 --> Lambda64
    PgClassExpression59{{"PgClassExpression[59∈4]<br />ᐸ__users__.”id”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈4]<br />ᐸ__users__.”name”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression60

    %% define steps

    subgraph "Buckets for queries/v4/partitions"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access9,Access10,Object11,Connection12,PgSelectInlineApply61 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 61, 6<br /><br />ROOT Connectionᐸ8ᐳ[12]<br />1: PgSelect[14], PgSelect[18]<br />ᐳ: 24, 25, 41, 42, 43, 46, 47, 62<br />2: PgSelectRows[15], PgSelectRows[20]<br />ᐳ: 19, 21, 22, 28, 30, 32, 34, 36, 38"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect14,PgSelectRows15,PgSelect18,First19,PgSelectRows20,PgSelectSingle21,PgClassExpression22,PgPageInfo24,Access25,First28,PgSelectSingle30,PgCursor32,Last34,PgSelectSingle36,PgCursor38,Access41,Object42,Lambda43,Object46,Lambda47,Access62 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 25, 62<br /><br />ROOT __Item{2}ᐸ15ᐳ[16]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item16,PgSelectSingle17 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 17, 25, 62<br /><br />ROOT PgSelectSingle{2}ᐸmeasurementsᐳ[17]<br />1: <br />ᐳ: 26, 48, 49, 50, 63, 64<br />2: PgSelectRows[57]<br />ᐳ: First[56], PgSelectSingle[58]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor26,PgClassExpression48,PgClassExpression49,PgClassExpression50,First56,PgSelectRows57,PgSelectSingle58,List63,Lambda64 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 58<br /><br />ROOT PgSelectSingle{3}ᐸusersᐳ[58]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression59,PgClassExpression60 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
