%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    PgFromExpression37{{"PgFromExpression[37∈0] ➊"}}:::plan
    PgFromExpression71{{"PgFromExpression[71∈0] ➊"}}:::plan
    PgSelectInlineApply82["PgSelectInlineApply[82∈0] ➊"]:::plan
    PgSelectInlineApply86["PgSelectInlineApply[86∈0] ➊"]:::plan
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸtypes+1ᐳ"]]:::plan
    Object11 & Connection12 & PgFromExpression37 & PgSelectInlineApply82 & PgFromExpression71 & PgSelectInlineApply86 --> PgSelect14
    Object48{{"Object[48∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access43{{"Access[43∈1] ➊<br />ᐸ14.hasMoreᐳ"}}:::plan
    Access43 --> Object48
    Object44{{"Object[44∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Access43 --> Object44
    PgSelect20[["PgSelect[20∈1] ➊<br />ᐸtypes(aggregate)ᐳ"]]:::plan
    Object11 & Connection12 --> PgSelect20
    PgCursor55{{"PgCursor[55∈1] ➊"}}:::plan
    PgSelectSingle53{{"PgSelectSingle[53∈1] ➊<br />ᐸtypesᐳ"}}:::plan
    Access54{{"Access[54∈1] ➊<br />ᐸ14.cursorDetailsᐳ"}}:::plan
    PgSelectSingle53 & Access54 --> PgCursor55
    PgCursor61{{"PgCursor[61∈1] ➊"}}:::plan
    PgSelectSingle59{{"PgSelectSingle[59∈1] ➊<br />ᐸtypesᐳ"}}:::plan
    PgSelectSingle59 & Access54 --> PgCursor61
    PgSelectRows15[["PgSelectRows[15∈1] ➊"]]:::plan
    PgSelect14 --> PgSelectRows15
    First21{{"First[21∈1] ➊"}}:::plan
    PgSelectRows22[["PgSelectRows[22∈1] ➊"]]:::plan
    PgSelectRows22 --> First21
    PgSelect20 --> PgSelectRows22
    PgSelectSingle23{{"PgSelectSingle[23∈1] ➊<br />ᐸtypesᐳ"}}:::plan
    First21 --> PgSelectSingle23
    PgClassExpression24{{"PgClassExpression[24∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle23 --> PgClassExpression24
    PgPageInfo26{{"PgPageInfo[26∈1] ➊"}}:::plan
    Connection12 --> PgPageInfo26
    PgSelect14 --> Access43
    Lambda45{{"Lambda[45∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object44 --> Lambda45
    Lambda49{{"Lambda[49∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object48 --> Lambda49
    First51{{"First[51∈1] ➊"}}:::plan
    PgSelectRows15 --> First51
    First51 --> PgSelectSingle53
    PgSelect14 --> Access54
    Last57{{"Last[57∈1] ➊"}}:::plan
    PgSelectRows15 --> Last57
    Last57 --> PgSelectSingle59
    Access83{{"Access[83∈1] ➊<br />ᐸ14.m.joinDetailsFor33ᐳ"}}:::plan
    PgSelect14 --> Access83
    Access87{{"Access[87∈1] ➊<br />ᐸ14.m.joinDetailsFor69ᐳ"}}:::plan
    PgSelect14 --> Access87
    __Item16[/"__Item[16∈2]<br />ᐸ15ᐳ"\]:::itemplan
    PgSelectRows15 ==> __Item16
    PgSelectSingle17{{"PgSelectSingle[17∈2]<br />ᐸtypesᐳ"}}:::plan
    __Item16 --> PgSelectSingle17
    List84{{"List[84∈3]<br />ᐸ83,17ᐳ"}}:::plan
    Access83 & PgSelectSingle17 --> List84
    List88{{"List[88∈3]<br />ᐸ87,17ᐳ"}}:::plan
    Access87 & PgSelectSingle17 --> List88
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression27
    PgClassExpression28{{"PgClassExpression[28∈3]<br />ᐸ__types__.”regrole”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈3]<br />ᐸ__types__....namespace”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression29
    PgClassExpression30{{"PgClassExpression[30∈3]<br />ᐸ__types__....ay_domain”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression30
    First38{{"First[38∈3]"}}:::plan
    PgSelectRows39[["PgSelectRows[39∈3]"]]:::plan
    PgSelectRows39 --> First38
    Lambda85{{"Lambda[85∈3]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda85 --> PgSelectRows39
    PgSelectSingle40{{"PgSelectSingle[40∈3]<br />ᐸfrmcdc_domainConstrainedCompoundTypeᐳ"}}:::plan
    First38 --> PgSelectSingle40
    First72{{"First[72∈3]"}}:::plan
    PgSelectRows73[["PgSelectRows[73∈3]"]]:::plan
    PgSelectRows73 --> First72
    Lambda89{{"Lambda[89∈3]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda89 --> PgSelectRows73
    PgSelectSingle74{{"PgSelectSingle[74∈3]<br />ᐸfrmcdc_domainConstrainedCompoundTypeᐳ"}}:::plan
    First72 --> PgSelectSingle74
    List84 --> Lambda85
    List88 --> Lambda89
    __Item31[/"__Item[31∈4]<br />ᐸ30ᐳ"\]:::itemplan
    PgClassExpression30 ==> __Item31
    PgClassExpression62{{"PgClassExpression[62∈5]<br />ᐸ__frmcdc_d...type__.”a”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression62
    PgClassExpression63{{"PgClassExpression[63∈5]<br />ᐸ__frmcdc_d...type__.”b”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression63
    PgClassExpression64{{"PgClassExpression[64∈5]<br />ᐸ__frmcdc_d...type__.”c”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression64
    PgClassExpression65{{"PgClassExpression[65∈5]<br />ᐸ__frmcdc_d...type__.”d”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression65
    PgClassExpression66{{"PgClassExpression[66∈5]<br />ᐸ__frmcdc_d...type__.”e”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression66
    PgClassExpression67{{"PgClassExpression[67∈5]<br />ᐸ__frmcdc_d...type__.”f”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression67
    PgClassExpression68{{"PgClassExpression[68∈5]<br />ᐸ__frmcdc_d....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression68
    PgClassExpression75{{"PgClassExpression[75∈6]<br />ᐸ__frmcdc_d...type__.”a”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression75
    PgClassExpression76{{"PgClassExpression[76∈6]<br />ᐸ__frmcdc_d...type__.”b”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression76
    PgClassExpression77{{"PgClassExpression[77∈6]<br />ᐸ__frmcdc_d...type__.”c”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression77
    PgClassExpression78{{"PgClassExpression[78∈6]<br />ᐸ__frmcdc_d...type__.”d”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression78
    PgClassExpression79{{"PgClassExpression[79∈6]<br />ᐸ__frmcdc_d...type__.”e”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression79
    PgClassExpression80{{"PgClassExpression[80∈6]<br />ᐸ__frmcdc_d...type__.”f”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression80
    PgClassExpression81{{"PgClassExpression[81∈6]<br />ᐸ__frmcdc_d....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle74 --> PgClassExpression81

    %% define steps

    subgraph "Buckets for queries/v4/pg11.types"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access9,Access10,Object11,Connection12,PgFromExpression37,PgFromExpression71,PgSelectInlineApply82,PgSelectInlineApply86 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 37, 82, 71, 86, 6<br /><br />ROOT Connectionᐸ8ᐳ[12]<br />1: PgSelect[14], PgSelect[20]<br />ᐳ: 26, 43, 44, 45, 48, 49, 54, 83, 87<br />2: PgSelectRows[15], PgSelectRows[22]<br />ᐳ: 21, 23, 24, 51, 53, 55, 57, 59, 61"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect14,PgSelectRows15,PgSelect20,First21,PgSelectRows22,PgSelectSingle23,PgClassExpression24,PgPageInfo26,Access43,Object44,Lambda45,Object48,Lambda49,First51,PgSelectSingle53,Access54,PgCursor55,Last57,PgSelectSingle59,PgCursor61,Access83,Access87 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 83, 87<br /><br />ROOT __Item{2}ᐸ15ᐳ[16]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item16,PgSelectSingle17 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 17, 83, 87<br /><br />ROOT PgSelectSingle{2}ᐸtypesᐳ[17]<br />1: <br />ᐳ: 27, 28, 29, 30, 84, 88, 85, 89<br />2: PgSelectRows[39], PgSelectRows[73]<br />ᐳ: 38, 40, 72, 74"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression27,PgClassExpression28,PgClassExpression29,PgClassExpression30,First38,PgSelectRows39,PgSelectSingle40,First72,PgSelectRows73,PgSelectSingle74,List84,Lambda85,List88,Lambda89 bucket3
    Bucket4("Bucket 4 (listItem)<br /><br />ROOT __Item{4}ᐸ30ᐳ[31]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item31 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 40<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_domainConstrainedCompoundTypeᐳ[40]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression62,PgClassExpression63,PgClassExpression64,PgClassExpression65,PgClassExpression66,PgClassExpression67,PgClassExpression68 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 74<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_domainConstrainedCompoundTypeᐳ[74]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression75,PgClassExpression76,PgClassExpression77,PgClassExpression78,PgClassExpression79,PgClassExpression80,PgClassExpression81 bucket6
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5 & Bucket6
    end
