%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    __Value2["__Value[2∈0]<br />ᐸcontextᐳ"]:::plan
    __Value4["__Value[4∈0]<br />ᐸrootValueᐳ"]:::plan
    Connection18{{"Connection[18∈0]<br />ᐸ14ᐳ"}}:::plan
    Object17{{"Object[17∈1]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈1]<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈1]<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    PgSelect19[["PgSelect[19∈1]<br />ᐸtypesᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect19
    PgSelect62[["PgSelect[62∈1]<br />ᐸtypes(aggregate)ᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect62
    __Value2 --> Access15
    __Value2 --> Access16
    First63{{"First[63∈1]"}}:::plan
    PgSelect62 --> First63
    PgSelectSingle64{{"PgSelectSingle[64∈1]<br />ᐸtypesᐳ"}}:::plan
    First63 --> PgSelectSingle64
    PgClassExpression65{{"PgClassExpression[65∈1]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle64 --> PgClassExpression65
    PgPageInfo66{{"PgPageInfo[66∈1]"}}:::plan
    Connection18 --> PgPageInfo66
    First70{{"First[70∈1]"}}:::plan
    PgSelect19 --> First70
    PgSelectSingle71{{"PgSelectSingle[71∈1]<br />ᐸtypesᐳ"}}:::plan
    First70 --> PgSelectSingle71
    PgCursor72{{"PgCursor[72∈1]"}}:::plan
    List74{{"List[74∈1]<br />ᐸ73ᐳ"}}:::plan
    List74 --> PgCursor72
    PgClassExpression73{{"PgClassExpression[73∈1]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression73
    PgClassExpression73 --> List74
    Last76{{"Last[76∈1]"}}:::plan
    PgSelect19 --> Last76
    PgSelectSingle77{{"PgSelectSingle[77∈1]<br />ᐸtypesᐳ"}}:::plan
    Last76 --> PgSelectSingle77
    PgCursor78{{"PgCursor[78∈1]"}}:::plan
    List80{{"List[80∈1]<br />ᐸ79ᐳ"}}:::plan
    List80 --> PgCursor78
    PgClassExpression79{{"PgClassExpression[79∈1]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle77 --> PgClassExpression79
    PgClassExpression79 --> List80
    Constant67{{"Constant[67∈1]<br />ᐸfalseᐳ"}}:::plan
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelect19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸtypesᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__types__.”regrole”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression23
    PgClassExpression24{{"PgClassExpression[24∈3]<br />ᐸ__types__....namespace”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression24
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ__types__....ay_domain”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression25
    PgSelectSingle33{{"PgSelectSingle[33∈3]<br />ᐸfrmcdc_domainConstrainedCompoundTypeᐳ"}}:::plan
    RemapKeys81{{"RemapKeys[81∈3]<br />ᐸ21:{”0”:4,”1”:5,”2”:6,”3”:7,”4”:8,”5”:9,”6”:10,”7”:11}ᐳ"}}:::plan
    RemapKeys81 --> PgSelectSingle33
    PgSelectSingle21 --> RemapKeys81
    __Item26[/"__Item[26∈4]<br />ᐸ25ᐳ"\]:::itemplan
    PgClassExpression25 ==> __Item26
    PgClassExpression34{{"PgClassExpression[34∈5]<br />ᐸ__frmcdc_d...type__.”a”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression34
    PgClassExpression35{{"PgClassExpression[35∈5]<br />ᐸ__frmcdc_d...type__.”b”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression35
    PgClassExpression36{{"PgClassExpression[36∈5]<br />ᐸ__frmcdc_d...type__.”c”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression36
    PgClassExpression37{{"PgClassExpression[37∈5]<br />ᐸ__frmcdc_d...type__.”d”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression37
    PgClassExpression38{{"PgClassExpression[38∈5]<br />ᐸ__frmcdc_d...type__.”e”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression38
    PgClassExpression39{{"PgClassExpression[39∈5]<br />ᐸ__frmcdc_d...type__.”f”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression39
    PgClassExpression40{{"PgClassExpression[40∈5]<br />ᐸ__frmcdc_d....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression40
    PgClassExpression43{{"PgClassExpression[43∈6]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression43
    PgClassExpression44{{"PgClassExpression[44∈6]<br />ᐸ__types__.”regrole”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression44
    PgClassExpression45{{"PgClassExpression[45∈6]<br />ᐸ__types__....namespace”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression45
    PgClassExpression46{{"PgClassExpression[46∈6]<br />ᐸ__types__....ay_domain”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression46
    PgSelectSingle54{{"PgSelectSingle[54∈6]<br />ᐸfrmcdc_domainConstrainedCompoundTypeᐳ"}}:::plan
    RemapKeys83{{"RemapKeys[83∈6]<br />ᐸ21:{”0”:12,”1”:13,”2”:14,”3”:15,”4”:16,”5”:17,”6”:18,”7”:19}ᐳ"}}:::plan
    RemapKeys83 --> PgSelectSingle54
    PgSelectSingle21 --> RemapKeys83
    __Item47[/"__Item[47∈7]<br />ᐸ46ᐳ"\]:::itemplan
    PgClassExpression46 ==> __Item47
    PgClassExpression55{{"PgClassExpression[55∈8]<br />ᐸ__frmcdc_d...type__.”a”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression55
    PgClassExpression56{{"PgClassExpression[56∈8]<br />ᐸ__frmcdc_d...type__.”b”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression56
    PgClassExpression57{{"PgClassExpression[57∈8]<br />ᐸ__frmcdc_d...type__.”c”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression57
    PgClassExpression58{{"PgClassExpression[58∈8]<br />ᐸ__frmcdc_d...type__.”d”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression58
    PgClassExpression59{{"PgClassExpression[59∈8]<br />ᐸ__frmcdc_d...type__.”e”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈8]<br />ᐸ__frmcdc_d...type__.”f”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression60
    PgClassExpression61{{"PgClassExpression[61∈8]<br />ᐸ__frmcdc_d....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression61

    %% define steps

    subgraph "Buckets for queries/v4/pg11.types"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Connection18 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 2, 18<br /><br />ROOT Connectionᐸ14ᐳ[18]<br />1: <br />ᐳ: 15, 16, 66, 67, 17<br />2: PgSelect[19], PgSelect[62]<br />ᐳ: 63, 64, 65, 70, 71, 73, 74, 76, 77, 79, 80, 72, 78"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Access15,Access16,Object17,PgSelect19,PgSelect62,First63,PgSelectSingle64,PgClassExpression65,PgPageInfo66,Constant67,First70,PgSelectSingle71,PgCursor72,PgClassExpression73,List74,Last76,PgSelectSingle77,PgCursor78,PgClassExpression79,List80 bucket1
    Bucket2("Bucket 2 (listItem)<br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21<br /><br />ROOT PgSelectSingle{2}ᐸtypesᐳ[21]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression22,PgClassExpression23,PgClassExpression24,PgClassExpression25,PgSelectSingle33,RemapKeys81 bucket3
    Bucket4("Bucket 4 (listItem)<br />ROOT __Item{4}ᐸ25ᐳ[26]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item26 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 33<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_domainConstrainedCompoundTypeᐳ[33]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression34,PgClassExpression35,PgClassExpression36,PgClassExpression37,PgClassExpression38,PgClassExpression39,PgClassExpression40 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 21<br /><br />ROOT PgSelectSingle{2}ᐸtypesᐳ[21]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression43,PgClassExpression44,PgClassExpression45,PgClassExpression46,PgSelectSingle54,RemapKeys83 bucket6
    Bucket7("Bucket 7 (listItem)<br />ROOT __Item{7}ᐸ46ᐳ[47]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,__Item47 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 54<br /><br />ROOT PgSelectSingle{6}ᐸfrmcdc_domainConstrainedCompoundTypeᐳ[54]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression55,PgClassExpression56,PgClassExpression57,PgClassExpression58,PgClassExpression59,PgClassExpression60,PgClassExpression61 bucket8
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3 & Bucket6
    Bucket3 --> Bucket4 & Bucket5
    Bucket6 --> Bucket7 & Bucket8
    classDef unary fill:#fafffa,borderWidth:8px
    class __Value2,__Value4,Connection18,Object17,PgSelect19,PgSelect62,Access15,Access16,First63,PgSelectSingle64,PgClassExpression65,PgPageInfo66,First70,PgSelectSingle71,PgCursor72,PgClassExpression73,List74,Last76,PgSelectSingle77,PgCursor78,PgClassExpression79,List80,Constant67 unary
    end
