%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect278[["PgSelect[278∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant323{{"Constant[323∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant326{{"Constant[326∈0] ➊<br />ᐸ7ᐳ"}}:::plan
    Constant321{{"Constant[321∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant127{{"Constant[127∈0] ➊<br />ᐸnullᐳ"}}:::plan
    Object12 & Constant323 & Constant323 & Constant326 & Constant323 & Constant321 & Constant326 & Constant323 & Constant326 & Constant323 & Constant326 & Constant323 & Constant127 & Constant326 & Constant323 & Constant326 --> PgSelect278
    __InputObject134{{"__InputObject[134∈0] ➊"}}:::plan
    Constant315{{"Constant[315∈0] ➊<br />ᐸ419ᐳ"}}:::plan
    Constant316{{"Constant[316∈0] ➊<br />ᐸ'easy cheesy baked potatoes'ᐳ"}}:::plan
    Constant317{{"Constant[317∈0] ➊<br />ᐸ'red'ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant318{{"Constant[318∈0] ➊<br />ᐸ'BAR_FOO'ᐳ"}}:::plan
    Constant319{{"Constant[319∈0] ➊<br />ᐸ''ᐳ"}}:::plan
    __InputObject140{{"__InputObject[140∈0] ➊"}}:::plan
    Constant315 & Constant316 & Constant317 & Constant6 & Constant318 & Constant319 & __InputObject140 & Constant321 --> __InputObject134
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection13
    Connection100{{"Connection[100∈0] ➊<br />ᐸ98ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection100
    Connection184{{"Connection[184∈0] ➊<br />ᐸ182ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection184
    Connection215{{"Connection[215∈0] ➊<br />ᐸ213ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection215
    Connection230{{"Connection[230∈0] ➊<br />ᐸ226ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection230
    Connection245{{"Connection[245∈0] ➊<br />ᐸ241ᐳ"}}:::plan
    Constant323 & Constant6 & Constant6 --> Connection245
    Connection266{{"Connection[266∈0] ➊<br />ᐸ264ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection266
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Constant320{{"Constant[320∈0] ➊<br />ᐸ5ᐳ"}}:::plan
    Constant6 & Constant320 --> __InputObject140
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant327{{"Constant[327∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant327 --> Lambda14
    ApplyInput15{{"ApplyInput[15∈0] ➊"}}:::plan
    Constant6 --> ApplyInput15
    Lambda101{{"Lambda[101∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant327 --> Lambda101
    ApplyInput102{{"ApplyInput[102∈0] ➊"}}:::plan
    Constant6 --> ApplyInput102
    BakedInput143{{"BakedInput[143∈0] ➊"}}:::plan
    __InputObject134 --> BakedInput143
    Lambda216{{"Lambda[216∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant327 --> Lambda216
    ApplyInput217{{"ApplyInput[217∈0] ➊"}}:::plan
    Constant6 --> ApplyInput217
    Lambda231{{"Lambda[231∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant6 --> Lambda231
    Lambda267{{"Lambda[267∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant328{{"Constant[328∈0] ➊<br />ᐸ[ 'NATURAL' ]ᐳ"}}:::plan
    Constant328 --> Lambda267
    ApplyInput268{{"ApplyInput[268∈0] ➊"}}:::plan
    Constant6 --> ApplyInput268
    First280{{"First[280∈0] ➊"}}:::plan
    PgSelectRows281[["PgSelectRows[281∈0] ➊"]]:::plan
    PgSelectRows281 --> First280
    PgSelect278 --> PgSelectRows281
    PgSelectSingle282{{"PgSelectSingle[282∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First280 --> PgSelectSingle282
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant312{{"Constant[312∈0] ➊<br />ᐸ15ᐳ"}}:::plan
    Constant313{{"Constant[313∈0] ➊<br />ᐸ20ᐳ"}}:::plan
    Constant314{{"Constant[314∈0] ➊<br />ᐸ'[...]'ᐳ"}}:::plan
    PgSelect16[["PgSelect[16∈1] ➊<br />ᐸtypesᐳ"]]:::plan
    Object12 & Lambda14 & ApplyInput15 & Connection13 & Constant6 & Constant6 & Constant6 --> PgSelect16
    PgSelectRows17[["PgSelectRows[17∈1] ➊"]]:::plan
    PgSelect16 --> PgSelectRows17
    __Item18[/"__Item[18∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelectRows17 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈2]<br />ᐸtypesᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgSelect21[["PgSelect[21∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression20 --> PgSelect21
    PgSelect33[["PgSelect[33∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"]]:::plan
    PgClassExpression32{{"PgClassExpression[32∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression32 --> PgSelect33
    PgSelect39[["PgSelect[39∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression38{{"PgClassExpression[38∈3]<br />ᐸ__frmcdc_n...type__.”a”ᐳ"}}:::plan
    Object12 & PgClassExpression38 --> PgSelect39
    PgSelect49[["PgSelect[49∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression48{{"PgClassExpression[48∈3]<br />ᐸ__frmcdc_n...type__.”b”ᐳ"}}:::plan
    Object12 & PgClassExpression48 --> PgSelect49
    PgSelect59[["PgSelect[59∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression58{{"PgClassExpression[58∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression58 --> PgSelect59
    PgSelect69[["PgSelect[69∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"]]:::plan
    PgClassExpression68{{"PgClassExpression[68∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression68 --> PgSelect69
    PgSelectSingle19 --> PgClassExpression20
    First25{{"First[25∈3]"}}:::plan
    PgSelectRows26[["PgSelectRows[26∈3]"]]:::plan
    PgSelectRows26 --> First25
    PgSelect21 --> PgSelectRows26
    PgSelectSingle27{{"PgSelectSingle[27∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First25 --> PgSelectSingle27
    PgClassExpression28{{"PgClassExpression[28∈3]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈3]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression29
    PgClassExpression31{{"PgClassExpression[31∈3]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression31
    PgSelectSingle19 --> PgClassExpression32
    First35{{"First[35∈3]"}}:::plan
    PgSelectRows36[["PgSelectRows[36∈3]"]]:::plan
    PgSelectRows36 --> First35
    PgSelect33 --> PgSelectRows36
    PgSelectSingle37{{"PgSelectSingle[37∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"}}:::plan
    First35 --> PgSelectSingle37
    PgSelectSingle37 --> PgClassExpression38
    First41{{"First[41∈3]"}}:::plan
    PgSelectRows42[["PgSelectRows[42∈3]"]]:::plan
    PgSelectRows42 --> First41
    PgSelect39 --> PgSelectRows42
    PgSelectSingle43{{"PgSelectSingle[43∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First41 --> PgSelectSingle43
    PgSelectSingle37 --> PgClassExpression48
    First51{{"First[51∈3]"}}:::plan
    PgSelectRows52[["PgSelectRows[52∈3]"]]:::plan
    PgSelectRows52 --> First51
    PgSelect49 --> PgSelectRows52
    PgSelectSingle53{{"PgSelectSingle[53∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First51 --> PgSelectSingle53
    PgSelectSingle19 --> PgClassExpression58
    First61{{"First[61∈3]"}}:::plan
    PgSelectRows62[["PgSelectRows[62∈3]"]]:::plan
    PgSelectRows62 --> First61
    PgSelect59 --> PgSelectRows62
    PgSelectSingle63{{"PgSelectSingle[63∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First61 --> PgSelectSingle63
    PgSelectSingle19 --> PgClassExpression68
    First71{{"First[71∈3]"}}:::plan
    PgSelectRows72[["PgSelectRows[72∈3]"]]:::plan
    PgSelectRows72 --> First71
    PgSelect69 --> PgSelectRows72
    PgSelectSingle73{{"PgSelectSingle[73∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"}}:::plan
    First71 --> PgSelectSingle73
    PgClassExpression44{{"PgClassExpression[44∈4]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression44
    PgClassExpression45{{"PgClassExpression[45∈4]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression45
    PgClassExpression47{{"PgClassExpression[47∈4]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression47
    PgClassExpression54{{"PgClassExpression[54∈5]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle53 --> PgClassExpression54
    PgClassExpression55{{"PgClassExpression[55∈5]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle53 --> PgClassExpression55
    PgClassExpression57{{"PgClassExpression[57∈5]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle53 --> PgClassExpression57
    PgClassExpression64{{"PgClassExpression[64∈6]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle63 --> PgClassExpression64
    PgClassExpression65{{"PgClassExpression[65∈6]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle63 --> PgClassExpression65
    PgClassExpression67{{"PgClassExpression[67∈6]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle63 --> PgClassExpression67
    PgSelect75[["PgSelect[75∈7]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression74{{"PgClassExpression[74∈7]<br />ᐸ__frmcdc_n...type__.”a”ᐳ"}}:::plan
    Object12 & PgClassExpression74 --> PgSelect75
    PgSelect87[["PgSelect[87∈7]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression86{{"PgClassExpression[86∈7]<br />ᐸ__frmcdc_n...type__.”b”ᐳ"}}:::plan
    Object12 & PgClassExpression86 --> PgSelect87
    PgSelectSingle73 --> PgClassExpression74
    First79{{"First[79∈7]"}}:::plan
    PgSelectRows80[["PgSelectRows[80∈7]"]]:::plan
    PgSelectRows80 --> First79
    PgSelect75 --> PgSelectRows80
    PgSelectSingle81{{"PgSelectSingle[81∈7]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First79 --> PgSelectSingle81
    PgSelectSingle73 --> PgClassExpression86
    First89{{"First[89∈7]"}}:::plan
    PgSelectRows90[["PgSelectRows[90∈7]"]]:::plan
    PgSelectRows90 --> First89
    PgSelect87 --> PgSelectRows90
    PgSelectSingle91{{"PgSelectSingle[91∈7]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First89 --> PgSelectSingle91
    PgClassExpression82{{"PgClassExpression[82∈8]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle81 --> PgClassExpression82
    PgClassExpression83{{"PgClassExpression[83∈8]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle81 --> PgClassExpression83
    PgClassExpression85{{"PgClassExpression[85∈8]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle81 --> PgClassExpression85
    PgClassExpression92{{"PgClassExpression[92∈9]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression92
    PgClassExpression93{{"PgClassExpression[93∈9]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression93
    PgClassExpression95{{"PgClassExpression[95∈9]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression95
    PgSelect103[["PgSelect[103∈10] ➊<br />ᐸpostᐳ"]]:::plan
    Object12 & Lambda101 & ApplyInput102 & Connection100 & Constant6 & Constant6 & Constant6 & Constant312 & Constant313 & Constant314 & Constant312 & Constant313 & Constant314 & Constant312 & Constant127 & Constant313 & Constant314 --> PgSelect103
    PgSelectRows104[["PgSelectRows[104∈10] ➊"]]:::plan
    PgSelect103 --> PgSelectRows104
    __Item105[/"__Item[105∈11]<br />ᐸ104ᐳ"\]:::itemplan
    PgSelectRows104 ==> __Item105
    PgSelectSingle106{{"PgSelectSingle[106∈11]<br />ᐸpostᐳ"}}:::plan
    __Item105 --> PgSelectSingle106
    PgSelect185[["PgSelect[185∈12]<br />ᐸpost_computed_interval_setᐳ"]]:::plan
    PgClassExpression108{{"PgClassExpression[108∈12]<br />ᐸ__post__ᐳ"}}:::plan
    Object12 & PgClassExpression108 & Connection184 & Constant6 & Constant6 & Constant6 --> PgSelect185
    PgSelect153[["PgSelect[153∈12]<br />ᐸpost_computed_compound_type_arrayᐳ"]]:::plan
    PgClassExpression152{{"PgClassExpression[152∈12]<br />ᐸ__post__ᐳ"}}:::plan
    Object12 & PgClassExpression152 & BakedInput143 --> PgSelect153
    PgSelect145[["PgSelect[145∈12]<br />ᐸpostᐳ"]]:::plan
    Object12 & PgClassExpression108 --> PgSelect145
    __ListTransform197[["__ListTransform[197∈12]<br />ᐸeach:196ᐳ"]]:::plan
    PgSelectRows186[["PgSelectRows[186∈12]"]]:::plan
    PgSelectRows186 & PgSelect185 --> __ListTransform197
    PgClassExpression107{{"PgClassExpression[107∈12]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression107
    PgSelectSingle106 --> PgClassExpression108
    PgClassExpression109{{"PgClassExpression[109∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression109
    PgClassExpression112{{"PgClassExpression[112∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression112
    PgClassExpression116{{"PgClassExpression[116∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression116
    PgClassExpression118{{"PgClassExpression[118∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression118
    PgClassExpression121{{"PgClassExpression[121∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression121
    PgClassExpression125{{"PgClassExpression[125∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression125
    PgClassExpression129{{"PgClassExpression[129∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression129
    PgClassExpression133{{"PgClassExpression[133∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression133
    First149{{"First[149∈12]"}}:::plan
    PgSelectRows150[["PgSelectRows[150∈12]"]]:::plan
    PgSelectRows150 --> First149
    PgSelect145 --> PgSelectRows150
    PgSelectSingle151{{"PgSelectSingle[151∈12]<br />ᐸpostᐳ"}}:::plan
    First149 --> PgSelectSingle151
    PgSelectSingle151 --> PgClassExpression152
    PgSelectRows155[["PgSelectRows[155∈12]"]]:::plan
    PgSelect153 --> PgSelectRows155
    PgClassExpression170{{"PgClassExpression[170∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression170
    PgClassExpression173{{"PgClassExpression[173∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression173
    PgSelect185 --> PgSelectRows186
    __Item156[/"__Item[156∈13]<br />ᐸ155ᐳ"\]:::itemplan
    PgSelectRows155 ==> __Item156
    PgSelectSingle157{{"PgSelectSingle[157∈13]<br />ᐸpost_computed_compound_type_arrayᐳ"}}:::plan
    __Item156 --> PgSelectSingle157
    PgClassExpression158{{"PgClassExpression[158∈14]<br />ᐸ__post_com...rray__.”a”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression158
    PgClassExpression159{{"PgClassExpression[159∈14]<br />ᐸ__post_com...rray__.”b”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression159
    PgClassExpression160{{"PgClassExpression[160∈14]<br />ᐸ__post_com...rray__.”c”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression160
    PgClassExpression161{{"PgClassExpression[161∈14]<br />ᐸ__post_com...rray__.”d”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression161
    PgClassExpression162{{"PgClassExpression[162∈14]<br />ᐸ__post_com...rray__.”e”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression162
    PgClassExpression163{{"PgClassExpression[163∈14]<br />ᐸ__post_com...rray__.”f”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression163
    PgClassExpression164{{"PgClassExpression[164∈14]<br />ᐸ__post_com...rray__.”g”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression164
    PgClassExpression168{{"PgClassExpression[168∈14]<br />ᐸ__post_com....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression168
    __Item171[/"__Item[171∈16]<br />ᐸ170ᐳ"\]:::itemplan
    PgClassExpression170 ==> __Item171
    __Item174[/"__Item[174∈17]<br />ᐸ173ᐳ"\]:::itemplan
    PgClassExpression173 ==> __Item174
    __Item187[/"__Item[187∈19]<br />ᐸ186ᐳ"\]:::itemplan
    PgSelectRows186 ==> __Item187
    PgSelectSingle188{{"PgSelectSingle[188∈19]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    __Item187 --> PgSelectSingle188
    PgClassExpression189{{"PgClassExpression[189∈19]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgSelectSingle188 --> PgClassExpression189
    __Item199[/"__Item[199∈21]<br />ᐸ186ᐳ"\]:::itemplan
    PgSelectRows186 -.-> __Item199
    PgSelectSingle200{{"PgSelectSingle[200∈21]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    __Item199 --> PgSelectSingle200
    PgClassExpression201{{"PgClassExpression[201∈21]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgSelectSingle200 --> PgClassExpression201
    Edge205{{"Edge[205∈22]"}}:::plan
    PgClassExpression204{{"PgClassExpression[204∈22]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgCursor207{{"PgCursor[207∈22]"}}:::plan
    PgClassExpression204 & PgCursor207 & Connection184 --> Edge205
    PgSelectSingle203{{"PgSelectSingle[203∈22]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    Access206{{"Access[206∈22]<br />ᐸ185.cursorDetailsᐳ"}}:::plan
    PgSelectSingle203 & Access206 --> PgCursor207
    __Item202[/"__Item[202∈22]<br />ᐸ197ᐳ"\]:::itemplan
    __ListTransform197 ==> __Item202
    __Item202 --> PgSelectSingle203
    PgSelectSingle203 --> PgClassExpression204
    PgSelect185 --> Access206
    PgSelect218[["PgSelect[218∈25] ➊<br />ᐸpersonᐳ"]]:::plan
    Object12 & Lambda216 & ApplyInput217 & Connection215 & Constant6 & Constant6 & Constant6 --> PgSelect218
    PgSelectRows219[["PgSelectRows[219∈25] ➊"]]:::plan
    PgSelect218 --> PgSelectRows219
    __Item220[/"__Item[220∈26]<br />ᐸ219ᐳ"\]:::itemplan
    PgSelectRows219 ==> __Item220
    PgSelectSingle221{{"PgSelectSingle[221∈26]<br />ᐸpersonᐳ"}}:::plan
    __Item220 --> PgSelectSingle221
    PgSelect232[["PgSelect[232∈27]<br />ᐸperson_friendsᐳ"]]:::plan
    PgClassExpression223{{"PgClassExpression[223∈27]<br />ᐸ__person__ᐳ"}}:::plan
    Object12 & PgClassExpression223 & Lambda231 & Connection230 & Constant6 & Constant6 & Constant6 --> PgSelect232
    PgSelect255[["PgSelect[255∈27]<br />ᐸperson_first_postᐳ"]]:::plan
    Object12 & PgClassExpression223 --> PgSelect255
    PgClassExpression222{{"PgClassExpression[222∈27]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle221 --> PgClassExpression222
    PgSelectSingle221 --> PgClassExpression223
    PgClassExpression224{{"PgClassExpression[224∈27]<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle221 --> PgClassExpression224
    PgSelectRows233[["PgSelectRows[233∈27]"]]:::plan
    PgSelect232 --> PgSelectRows233
    First257{{"First[257∈27]"}}:::plan
    PgSelectRows258[["PgSelectRows[258∈27]"]]:::plan
    PgSelectRows258 --> First257
    PgSelect255 --> PgSelectRows258
    PgSelectSingle259{{"PgSelectSingle[259∈27]<br />ᐸperson_first_postᐳ"}}:::plan
    First257 --> PgSelectSingle259
    __Item234[/"__Item[234∈28]<br />ᐸ233ᐳ"\]:::itemplan
    PgSelectRows233 ==> __Item234
    PgSelectSingle235{{"PgSelectSingle[235∈28]<br />ᐸperson_friendsᐳ"}}:::plan
    __Item234 --> PgSelectSingle235
    PgSelect247[["PgSelect[247∈29]<br />ᐸperson_friendsᐳ"]]:::plan
    PgClassExpression237{{"PgClassExpression[237∈29]<br />ᐸ__person_friends__ᐳ"}}:::plan
    Object12 & PgClassExpression237 & Lambda231 & Connection245 & Constant323 & Constant6 & Constant6 --> PgSelect247
    PgClassExpression236{{"PgClassExpression[236∈29]<br />ᐸ__person_f...full_name”ᐳ"}}:::plan
    PgSelectSingle235 --> PgClassExpression236
    PgSelectSingle235 --> PgClassExpression237
    PgClassExpression238{{"PgClassExpression[238∈29]<br />ᐸ”c”.”perso...friends__)ᐳ"}}:::plan
    PgSelectSingle235 --> PgClassExpression238
    PgSelectRows248[["PgSelectRows[248∈29]"]]:::plan
    PgSelect247 --> PgSelectRows248
    __Item249[/"__Item[249∈30]<br />ᐸ248ᐳ"\]:::itemplan
    PgSelectRows248 ==> __Item249
    PgSelectSingle250{{"PgSelectSingle[250∈30]<br />ᐸperson_friendsᐳ"}}:::plan
    __Item249 --> PgSelectSingle250
    PgClassExpression251{{"PgClassExpression[251∈31]<br />ᐸ__person_f...full_name”ᐳ"}}:::plan
    PgSelectSingle250 --> PgClassExpression251
    PgClassExpression253{{"PgClassExpression[253∈31]<br />ᐸ”c”.”perso...friends__)ᐳ"}}:::plan
    PgSelectSingle250 --> PgClassExpression253
    PgClassExpression260{{"PgClassExpression[260∈32]<br />ᐸ__person_f...ost__.”id”ᐳ"}}:::plan
    PgSelectSingle259 --> PgClassExpression260
    PgClassExpression261{{"PgClassExpression[261∈32]<br />ᐸ__person_f...”headline”ᐳ"}}:::plan
    PgSelectSingle259 --> PgClassExpression261
    PgSelect269[["PgSelect[269∈33] ➊<br />ᐸedge_caseᐳ"]]:::plan
    Object12 & Lambda267 & ApplyInput268 & Connection266 & Constant6 & Constant6 & Constant6 --> PgSelect269
    PgSelectRows270[["PgSelectRows[270∈33] ➊"]]:::plan
    PgSelect269 --> PgSelectRows270
    __Item271[/"__Item[271∈34]<br />ᐸ270ᐳ"\]:::itemplan
    PgSelectRows270 ==> __Item271
    PgSelectSingle272{{"PgSelectSingle[272∈34]<br />ᐸedge_caseᐳ"}}:::plan
    __Item271 --> PgSelectSingle272
    PgClassExpression273{{"PgClassExpression[273∈35]<br />ᐸ__edge_cas...s_default”ᐳ"}}:::plan
    PgSelectSingle272 --> PgClassExpression273
    PgClassExpression274{{"PgClassExpression[274∈35]<br />ᐸ__edge_cas...cast_easy”ᐳ"}}:::plan
    PgSelectSingle272 --> PgClassExpression274
    PgClassExpression276{{"PgClassExpression[276∈35]<br />ᐸ”c”.”edge_...ge_case__)ᐳ"}}:::plan
    PgSelectSingle272 --> PgClassExpression276
    PgClassExpression286{{"PgClassExpression[286∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression286
    PgClassExpression291{{"PgClassExpression[291∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression291
    PgClassExpression295{{"PgClassExpression[295∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression295
    PgClassExpression299{{"PgClassExpression[299∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression299
    PgClassExpression304{{"PgClassExpression[304∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression304
    PgClassExpression308{{"PgClassExpression[308∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle282 --> PgClassExpression308

    %% define steps

    subgraph "Buckets for queries/v4/procedure-computed-fields"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 10, 11, 127, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 323, 326, 327, 328, 12, 13, 14, 15, 100, 101, 102, 140, 184, 215, 216, 217, 230, 231, 245, 266, 267, 268, 134, 143<br />2: PgSelect[278]<br />3: PgSelectRows[281]<br />ᐳ: First[280], PgSelectSingle[282]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access10,Access11,Object12,Connection13,Lambda14,ApplyInput15,Connection100,Lambda101,ApplyInput102,Constant127,__InputObject134,__InputObject140,BakedInput143,Connection184,Connection215,Lambda216,ApplyInput217,Connection230,Lambda231,Connection245,Connection266,Lambda267,ApplyInput268,PgSelect278,First280,PgSelectRows281,PgSelectSingle282,Constant312,Constant313,Constant314,Constant315,Constant316,Constant317,Constant318,Constant319,Constant320,Constant321,Constant323,Constant326,Constant327,Constant328 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 15, 13, 6<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[16]<br />2: PgSelectRows[17]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect16,PgSelectRows17 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 12<br /><br />ROOT __Item{2}ᐸ17ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgSelectSingle19 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 12<br /><br />ROOT PgSelectSingle{2}ᐸtypesᐳ[19]<br />1: <br />ᐳ: 20, 32, 58, 68<br />2: 21, 33, 59, 69<br />3: 26, 36, 62, 72<br />ᐳ: 25, 27, 28, 29, 31, 35, 37, 38, 48, 61, 63, 71, 73<br />4: PgSelect[39], PgSelect[49]<br />5: PgSelectRows[42], PgSelectRows[52]<br />ᐳ: 41, 43, 51, 53"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression20,PgSelect21,First25,PgSelectRows26,PgSelectSingle27,PgClassExpression28,PgClassExpression29,PgClassExpression31,PgClassExpression32,PgSelect33,First35,PgSelectRows36,PgSelectSingle37,PgClassExpression38,PgSelect39,First41,PgSelectRows42,PgSelectSingle43,PgClassExpression48,PgSelect49,First51,PgSelectRows52,PgSelectSingle53,PgClassExpression58,PgSelect59,First61,PgSelectRows62,PgSelectSingle63,PgClassExpression68,PgSelect69,First71,PgSelectRows72,PgSelectSingle73 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 43<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[43]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression44,PgClassExpression45,PgClassExpression47 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 53<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[53]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression54,PgClassExpression55,PgClassExpression57 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 63<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[63]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression64,PgClassExpression65,PgClassExpression67 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 73, 12<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_nestedCompoundTypeᐳ[73]<br />1: <br />ᐳ: 74, 86<br />2: PgSelect[75], PgSelect[87]<br />3: PgSelectRows[80], PgSelectRows[90]<br />ᐳ: 79, 81, 89, 91"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression74,PgSelect75,First79,PgSelectRows80,PgSelectSingle81,PgClassExpression86,PgSelect87,First89,PgSelectRows90,PgSelectSingle91 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 81<br /><br />ROOT PgSelectSingle{7}ᐸfrmcdc_compoundTypeᐳ[81]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression82,PgClassExpression83,PgClassExpression85 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 91<br /><br />ROOT PgSelectSingle{7}ᐸfrmcdc_compoundTypeᐳ[91]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression92,PgClassExpression93,PgClassExpression95 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 12, 101, 102, 100, 6, 312, 313, 314, 127, 143, 184<br /><br />ROOT Connectionᐸ98ᐳ[100]<br />1: PgSelect[103]<br />2: PgSelectRows[104]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgSelect103,PgSelectRows104 bucket10
    Bucket11("Bucket 11 (listItem)<br />Deps: 12, 143, 184, 6<br /><br />ROOT __Item{11}ᐸ104ᐳ[105]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Item105,PgSelectSingle106 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 106, 12, 143, 184, 6<br /><br />ROOT PgSelectSingle{11}ᐸpostᐳ[106]<br />1: <br />ᐳ: 107, 108, 109, 112, 116, 118, 121, 125, 129, 133, 170, 173<br />2: PgSelect[145], PgSelect[185]<br />3: PgSelectRows[150], PgSelectRows[186]<br />ᐳ: 149, 151, 152<br />4: PgSelect[153], __ListTransform[197]<br />5: PgSelectRows[155]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression107,PgClassExpression108,PgClassExpression109,PgClassExpression112,PgClassExpression116,PgClassExpression118,PgClassExpression121,PgClassExpression125,PgClassExpression129,PgClassExpression133,PgSelect145,First149,PgSelectRows150,PgSelectSingle151,PgClassExpression152,PgSelect153,PgSelectRows155,PgClassExpression170,PgClassExpression173,PgSelect185,PgSelectRows186,__ListTransform197 bucket12
    Bucket13("Bucket 13 (listItem)<br /><br />ROOT __Item{13}ᐸ155ᐳ[156]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item156,PgSelectSingle157 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 157<br /><br />ROOT PgSelectSingle{13}ᐸpost_computed_compound_type_arrayᐳ[157]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression158,PgClassExpression159,PgClassExpression160,PgClassExpression161,PgClassExpression162,PgClassExpression163,PgClassExpression164,PgClassExpression168 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 164<br /><br />ROOT PgClassExpression{14}ᐸ__post_com...rray__.”g”ᐳ[164]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15 bucket15
    Bucket16("Bucket 16 (listItem)<br /><br />ROOT __Item{16}ᐸ170ᐳ[171]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item171 bucket16
    Bucket17("Bucket 17 (listItem)<br /><br />ROOT __Item{17}ᐸ173ᐳ[174]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,__Item174 bucket17
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 174<br /><br />ROOT __Item{17}ᐸ173ᐳ[174]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    Bucket19("Bucket 19 (listItem)<br /><br />ROOT __Item{19}ᐸ186ᐳ[187]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item187,PgSelectSingle188,PgClassExpression189 bucket19
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 189<br /><br />ROOT PgClassExpression{19}ᐸ__post_com...al_set__.vᐳ[189]"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20 bucket20
    Bucket21("Bucket 21 (subroutine)<br /><br />ROOT PgClassExpression{21}ᐸ__post_com...al_set__.vᐳ[201]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item199,PgSelectSingle200,PgClassExpression201 bucket21
    Bucket22("Bucket 22 (listItem)<br />Deps: 184, 185<br /><br />ROOT __Item{22}ᐸ197ᐳ[202]"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,__Item202,PgSelectSingle203,PgClassExpression204,Edge205,Access206,PgCursor207 bucket22
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 205, 204, 207<br /><br />ROOT Edge{22}[205]"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23 bucket23
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 204<br /><br />ROOT PgClassExpression{22}ᐸ__post_com...al_set__.vᐳ[204]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24 bucket24
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 12, 216, 217, 215, 6, 231, 230, 245, 323<br /><br />ROOT Connectionᐸ213ᐳ[215]<br />1: PgSelect[218]<br />2: PgSelectRows[219]"):::bucket
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect218,PgSelectRows219 bucket25
    Bucket26("Bucket 26 (listItem)<br />Deps: 12, 231, 230, 6, 245, 323<br /><br />ROOT __Item{26}ᐸ219ᐳ[220]"):::bucket
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item220,PgSelectSingle221 bucket26
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 221, 12, 231, 230, 6, 245, 323<br /><br />ROOT PgSelectSingle{26}ᐸpersonᐳ[221]<br />1: <br />ᐳ: 222, 223, 224<br />2: PgSelect[232], PgSelect[255]<br />3: PgSelectRows[233], PgSelectRows[258]<br />ᐳ: First[257], PgSelectSingle[259]"):::bucket
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgClassExpression222,PgClassExpression223,PgClassExpression224,PgSelect232,PgSelectRows233,PgSelect255,First257,PgSelectRows258,PgSelectSingle259 bucket27
    Bucket28("Bucket 28 (listItem)<br />Deps: 12, 231, 245, 323, 6<br /><br />ROOT __Item{28}ᐸ233ᐳ[234]"):::bucket
    classDef bucket28 stroke:#00ffff
    class Bucket28,__Item234,PgSelectSingle235 bucket28
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 235, 12, 231, 245, 323, 6<br /><br />ROOT PgSelectSingle{28}ᐸperson_friendsᐳ[235]<br />1: <br />ᐳ: 236, 237, 238<br />2: PgSelect[247]<br />3: PgSelectRows[248]"):::bucket
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression236,PgClassExpression237,PgClassExpression238,PgSelect247,PgSelectRows248 bucket29
    Bucket30("Bucket 30 (listItem)<br /><br />ROOT __Item{30}ᐸ248ᐳ[249]"):::bucket
    classDef bucket30 stroke:#3cb371
    class Bucket30,__Item249,PgSelectSingle250 bucket30
    Bucket31("Bucket 31 (nullableBoundary)<br />Deps: 250<br /><br />ROOT PgSelectSingle{30}ᐸperson_friendsᐳ[250]"):::bucket
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgClassExpression251,PgClassExpression253 bucket31
    Bucket32("Bucket 32 (nullableBoundary)<br />Deps: 259<br /><br />ROOT PgSelectSingle{27}ᐸperson_first_postᐳ[259]"):::bucket
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgClassExpression260,PgClassExpression261 bucket32
    Bucket33("Bucket 33 (nullableBoundary)<br />Deps: 12, 267, 268, 266, 6<br /><br />ROOT Connectionᐸ264ᐳ[266]<br />1: PgSelect[269]<br />2: PgSelectRows[270]"):::bucket
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgSelect269,PgSelectRows270 bucket33
    Bucket34("Bucket 34 (listItem)<br /><br />ROOT __Item{34}ᐸ270ᐳ[271]"):::bucket
    classDef bucket34 stroke:#696969
    class Bucket34,__Item271,PgSelectSingle272 bucket34
    Bucket35("Bucket 35 (nullableBoundary)<br />Deps: 272<br /><br />ROOT PgSelectSingle{34}ᐸedge_caseᐳ[272]"):::bucket
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgClassExpression273,PgClassExpression274,PgClassExpression276 bucket35
    Bucket36("Bucket 36 (nullableBoundary)<br />Deps: 282<br /><br />ROOT PgSelectSingleᐸpersonᐳ[282]"):::bucket
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgClassExpression286,PgClassExpression291,PgClassExpression295,PgClassExpression299,PgClassExpression304,PgClassExpression308 bucket36
    Bucket0 --> Bucket1 & Bucket10 & Bucket25 & Bucket33 & Bucket36
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5 & Bucket6 & Bucket7
    Bucket7 --> Bucket8 & Bucket9
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12
    Bucket12 --> Bucket13 & Bucket16 & Bucket17 & Bucket19 & Bucket21 & Bucket22
    Bucket13 --> Bucket14
    Bucket14 --> Bucket15
    Bucket17 --> Bucket18
    Bucket19 --> Bucket20
    Bucket22 --> Bucket23
    Bucket23 --> Bucket24
    Bucket25 --> Bucket26
    Bucket26 --> Bucket27
    Bucket27 --> Bucket28 & Bucket32
    Bucket28 --> Bucket29
    Bucket29 --> Bucket30
    Bucket30 --> Bucket31
    Bucket33 --> Bucket34
    Bucket34 --> Bucket35
    end
