%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect274[["PgSelect[274∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant319{{"Constant[319∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant322{{"Constant[322∈0] ➊<br />ᐸ7ᐳ"}}:::plan
    Constant317{{"Constant[317∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant125{{"Constant[125∈0] ➊<br />ᐸnullᐳ"}}:::plan
    Object12 & Constant319 & Constant319 & Constant322 & Constant319 & Constant317 & Constant322 & Constant319 & Constant322 & Constant319 & Constant322 & Constant319 & Constant125 & Constant322 & Constant319 & Constant322 --> PgSelect274
    __InputObject132{{"__InputObject[132∈0] ➊"}}:::plan
    Constant311{{"Constant[311∈0] ➊<br />ᐸ419ᐳ"}}:::plan
    Constant312{{"Constant[312∈0] ➊<br />ᐸ'easy cheesy baked potatoes'ᐳ"}}:::plan
    Constant313{{"Constant[313∈0] ➊<br />ᐸ'red'ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant314{{"Constant[314∈0] ➊<br />ᐸ'BAR_FOO'ᐳ"}}:::plan
    Constant315{{"Constant[315∈0] ➊<br />ᐸ''ᐳ"}}:::plan
    __InputObject138{{"__InputObject[138∈0] ➊"}}:::plan
    Constant311 & Constant312 & Constant313 & Constant6 & Constant314 & Constant315 & __InputObject138 & Constant317 --> __InputObject132
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection13
    Connection99{{"Connection[99∈0] ➊<br />ᐸ97ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection99
    Connection182{{"Connection[182∈0] ➊<br />ᐸ180ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection182
    Connection213{{"Connection[213∈0] ➊<br />ᐸ211ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection213
    Connection227{{"Connection[227∈0] ➊<br />ᐸ223ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection227
    Connection242{{"Connection[242∈0] ➊<br />ᐸ238ᐳ"}}:::plan
    Constant319 & Constant6 & Constant6 --> Connection242
    Connection263{{"Connection[263∈0] ➊<br />ᐸ261ᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection263
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Constant316{{"Constant[316∈0] ➊<br />ᐸ5ᐳ"}}:::plan
    Constant6 & Constant316 --> __InputObject138
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant323{{"Constant[323∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant323 --> Lambda14
    Lambda100{{"Lambda[100∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant323 --> Lambda100
    BakedInput141{{"BakedInput[141∈0] ➊"}}:::plan
    __InputObject132 --> BakedInput141
    Lambda214{{"Lambda[214∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant323 --> Lambda214
    Lambda228{{"Lambda[228∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant6 --> Lambda228
    Lambda264{{"Lambda[264∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant324{{"Constant[324∈0] ➊<br />ᐸ[ 'NATURAL' ]ᐳ"}}:::plan
    Constant324 --> Lambda264
    First276{{"First[276∈0] ➊"}}:::plan
    PgSelectRows277[["PgSelectRows[277∈0] ➊"]]:::plan
    PgSelectRows277 --> First276
    PgSelect274 --> PgSelectRows277
    PgSelectSingle278{{"PgSelectSingle[278∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First276 --> PgSelectSingle278
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant308{{"Constant[308∈0] ➊<br />ᐸ15ᐳ"}}:::plan
    Constant309{{"Constant[309∈0] ➊<br />ᐸ20ᐳ"}}:::plan
    Constant310{{"Constant[310∈0] ➊<br />ᐸ'[...]'ᐳ"}}:::plan
    PgSelect15[["PgSelect[15∈1] ➊<br />ᐸtypesᐳ"]]:::plan
    Object12 & Lambda14 & Connection13 & Constant6 & Constant6 & Constant6 --> PgSelect15
    PgSelectRows16[["PgSelectRows[16∈1] ➊"]]:::plan
    PgSelect15 --> PgSelectRows16
    __Item17[/"__Item[17∈2]<br />ᐸ16ᐳ"\]:::itemplan
    PgSelectRows16 ==> __Item17
    PgSelectSingle18{{"PgSelectSingle[18∈2]<br />ᐸtypesᐳ"}}:::plan
    __Item17 --> PgSelectSingle18
    PgSelect20[["PgSelect[20∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression19{{"PgClassExpression[19∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression19 --> PgSelect20
    PgSelect32[["PgSelect[32∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"]]:::plan
    PgClassExpression31{{"PgClassExpression[31∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression31 --> PgSelect32
    PgSelect38[["PgSelect[38∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression37{{"PgClassExpression[37∈3]<br />ᐸ__frmcdc_n...type__.”a”ᐳ"}}:::plan
    Object12 & PgClassExpression37 --> PgSelect38
    PgSelect48[["PgSelect[48∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression47{{"PgClassExpression[47∈3]<br />ᐸ__frmcdc_n...type__.”b”ᐳ"}}:::plan
    Object12 & PgClassExpression47 --> PgSelect48
    PgSelect58[["PgSelect[58∈3]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression57{{"PgClassExpression[57∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression57 --> PgSelect58
    PgSelect68[["PgSelect[68∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"]]:::plan
    PgClassExpression67{{"PgClassExpression[67∈3]<br />ᐸ__types__....ound_type”ᐳ"}}:::plan
    Object12 & PgClassExpression67 --> PgSelect68
    PgSelectSingle18 --> PgClassExpression19
    First24{{"First[24∈3]"}}:::plan
    PgSelectRows25[["PgSelectRows[25∈3]"]]:::plan
    PgSelectRows25 --> First24
    PgSelect20 --> PgSelectRows25
    PgSelectSingle26{{"PgSelectSingle[26∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First24 --> PgSelectSingle26
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression27
    PgClassExpression28{{"PgClassExpression[28∈3]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression28
    PgClassExpression30{{"PgClassExpression[30∈3]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression30
    PgSelectSingle18 --> PgClassExpression31
    First34{{"First[34∈3]"}}:::plan
    PgSelectRows35[["PgSelectRows[35∈3]"]]:::plan
    PgSelectRows35 --> First34
    PgSelect32 --> PgSelectRows35
    PgSelectSingle36{{"PgSelectSingle[36∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"}}:::plan
    First34 --> PgSelectSingle36
    PgSelectSingle36 --> PgClassExpression37
    First40{{"First[40∈3]"}}:::plan
    PgSelectRows41[["PgSelectRows[41∈3]"]]:::plan
    PgSelectRows41 --> First40
    PgSelect38 --> PgSelectRows41
    PgSelectSingle42{{"PgSelectSingle[42∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First40 --> PgSelectSingle42
    PgSelectSingle36 --> PgClassExpression47
    First50{{"First[50∈3]"}}:::plan
    PgSelectRows51[["PgSelectRows[51∈3]"]]:::plan
    PgSelectRows51 --> First50
    PgSelect48 --> PgSelectRows51
    PgSelectSingle52{{"PgSelectSingle[52∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First50 --> PgSelectSingle52
    PgSelectSingle18 --> PgClassExpression57
    First60{{"First[60∈3]"}}:::plan
    PgSelectRows61[["PgSelectRows[61∈3]"]]:::plan
    PgSelectRows61 --> First60
    PgSelect58 --> PgSelectRows61
    PgSelectSingle62{{"PgSelectSingle[62∈3]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First60 --> PgSelectSingle62
    PgSelectSingle18 --> PgClassExpression67
    First70{{"First[70∈3]"}}:::plan
    PgSelectRows71[["PgSelectRows[71∈3]"]]:::plan
    PgSelectRows71 --> First70
    PgSelect68 --> PgSelectRows71
    PgSelectSingle72{{"PgSelectSingle[72∈3]<br />ᐸfrmcdc_nestedCompoundTypeᐳ"}}:::plan
    First70 --> PgSelectSingle72
    PgClassExpression43{{"PgClassExpression[43∈4]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression43
    PgClassExpression44{{"PgClassExpression[44∈4]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression44
    PgClassExpression46{{"PgClassExpression[46∈4]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression46
    PgClassExpression53{{"PgClassExpression[53∈5]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression53
    PgClassExpression54{{"PgClassExpression[54∈5]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression54
    PgClassExpression56{{"PgClassExpression[56∈5]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression56
    PgClassExpression63{{"PgClassExpression[63∈6]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle62 --> PgClassExpression63
    PgClassExpression64{{"PgClassExpression[64∈6]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle62 --> PgClassExpression64
    PgClassExpression66{{"PgClassExpression[66∈6]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle62 --> PgClassExpression66
    PgSelect74[["PgSelect[74∈7]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression73{{"PgClassExpression[73∈7]<br />ᐸ__frmcdc_n...type__.”a”ᐳ"}}:::plan
    Object12 & PgClassExpression73 --> PgSelect74
    PgSelect86[["PgSelect[86∈7]<br />ᐸfrmcdc_compoundTypeᐳ"]]:::plan
    PgClassExpression85{{"PgClassExpression[85∈7]<br />ᐸ__frmcdc_n...type__.”b”ᐳ"}}:::plan
    Object12 & PgClassExpression85 --> PgSelect86
    PgSelectSingle72 --> PgClassExpression73
    First78{{"First[78∈7]"}}:::plan
    PgSelectRows79[["PgSelectRows[79∈7]"]]:::plan
    PgSelectRows79 --> First78
    PgSelect74 --> PgSelectRows79
    PgSelectSingle80{{"PgSelectSingle[80∈7]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First78 --> PgSelectSingle80
    PgSelectSingle72 --> PgClassExpression85
    First88{{"First[88∈7]"}}:::plan
    PgSelectRows89[["PgSelectRows[89∈7]"]]:::plan
    PgSelectRows89 --> First88
    PgSelect86 --> PgSelectRows89
    PgSelectSingle90{{"PgSelectSingle[90∈7]<br />ᐸfrmcdc_compoundTypeᐳ"}}:::plan
    First88 --> PgSelectSingle90
    PgClassExpression81{{"PgClassExpression[81∈8]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle80 --> PgClassExpression81
    PgClassExpression82{{"PgClassExpression[82∈8]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle80 --> PgClassExpression82
    PgClassExpression84{{"PgClassExpression[84∈8]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle80 --> PgClassExpression84
    PgClassExpression91{{"PgClassExpression[91∈9]<br />ᐸ__frmcdc_c...type__.”a”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression91
    PgClassExpression92{{"PgClassExpression[92∈9]<br />ᐸ__frmcdc_c....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression92
    PgClassExpression94{{"PgClassExpression[94∈9]<br />ᐸ”c”.”compo...nd_type__)ᐳ"}}:::plan
    PgSelectSingle90 --> PgClassExpression94
    PgSelect101[["PgSelect[101∈10] ➊<br />ᐸpostᐳ"]]:::plan
    Object12 & Lambda100 & Connection99 & Constant6 & Constant6 & Constant6 & Constant308 & Constant309 & Constant310 & Constant308 & Constant309 & Constant310 & Constant308 & Constant125 & Constant309 & Constant310 --> PgSelect101
    PgSelectRows102[["PgSelectRows[102∈10] ➊"]]:::plan
    PgSelect101 --> PgSelectRows102
    __Item103[/"__Item[103∈11]<br />ᐸ102ᐳ"\]:::itemplan
    PgSelectRows102 ==> __Item103
    PgSelectSingle104{{"PgSelectSingle[104∈11]<br />ᐸpostᐳ"}}:::plan
    __Item103 --> PgSelectSingle104
    PgSelect183[["PgSelect[183∈12]<br />ᐸpost_computed_interval_setᐳ"]]:::plan
    PgClassExpression106{{"PgClassExpression[106∈12]<br />ᐸ__post__ᐳ"}}:::plan
    Object12 & PgClassExpression106 & Connection182 & Constant6 & Constant6 & Constant6 --> PgSelect183
    PgSelect151[["PgSelect[151∈12]<br />ᐸpost_computed_compound_type_arrayᐳ"]]:::plan
    PgClassExpression150{{"PgClassExpression[150∈12]<br />ᐸ__post__ᐳ"}}:::plan
    Object12 & PgClassExpression150 & BakedInput141 --> PgSelect151
    PgSelect143[["PgSelect[143∈12]<br />ᐸpostᐳ"]]:::plan
    Object12 & PgClassExpression106 --> PgSelect143
    __ListTransform195[["__ListTransform[195∈12]<br />ᐸeach:194ᐳ"]]:::plan
    PgSelectRows184[["PgSelectRows[184∈12]"]]:::plan
    PgSelectRows184 & PgSelect183 --> __ListTransform195
    PgClassExpression105{{"PgClassExpression[105∈12]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression105
    PgSelectSingle104 --> PgClassExpression106
    PgClassExpression107{{"PgClassExpression[107∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression107
    PgClassExpression110{{"PgClassExpression[110∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression110
    PgClassExpression114{{"PgClassExpression[114∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression114
    PgClassExpression116{{"PgClassExpression[116∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression116
    PgClassExpression119{{"PgClassExpression[119∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression119
    PgClassExpression123{{"PgClassExpression[123∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression123
    PgClassExpression127{{"PgClassExpression[127∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression127
    PgClassExpression131{{"PgClassExpression[131∈12]<br />ᐸ”a”.”post_...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression131
    First147{{"First[147∈12]"}}:::plan
    PgSelectRows148[["PgSelectRows[148∈12]"]]:::plan
    PgSelectRows148 --> First147
    PgSelect143 --> PgSelectRows148
    PgSelectSingle149{{"PgSelectSingle[149∈12]<br />ᐸpostᐳ"}}:::plan
    First147 --> PgSelectSingle149
    PgSelectSingle149 --> PgClassExpression150
    PgSelectRows153[["PgSelectRows[153∈12]"]]:::plan
    PgSelect151 --> PgSelectRows153
    PgClassExpression168{{"PgClassExpression[168∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression168
    PgClassExpression171{{"PgClassExpression[171∈12]<br />ᐸ”a”.”post_...(__post__)ᐳ"}}:::plan
    PgSelectSingle104 --> PgClassExpression171
    PgSelect183 --> PgSelectRows184
    __Item154[/"__Item[154∈13]<br />ᐸ153ᐳ"\]:::itemplan
    PgSelectRows153 ==> __Item154
    PgSelectSingle155{{"PgSelectSingle[155∈13]<br />ᐸpost_computed_compound_type_arrayᐳ"}}:::plan
    __Item154 --> PgSelectSingle155
    PgClassExpression156{{"PgClassExpression[156∈14]<br />ᐸ__post_com...rray__.”a”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression156
    PgClassExpression157{{"PgClassExpression[157∈14]<br />ᐸ__post_com...rray__.”b”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression157
    PgClassExpression158{{"PgClassExpression[158∈14]<br />ᐸ__post_com...rray__.”c”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression158
    PgClassExpression159{{"PgClassExpression[159∈14]<br />ᐸ__post_com...rray__.”d”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression159
    PgClassExpression160{{"PgClassExpression[160∈14]<br />ᐸ__post_com...rray__.”e”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression160
    PgClassExpression161{{"PgClassExpression[161∈14]<br />ᐸ__post_com...rray__.”f”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression161
    PgClassExpression162{{"PgClassExpression[162∈14]<br />ᐸ__post_com...rray__.”g”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression162
    PgClassExpression166{{"PgClassExpression[166∈14]<br />ᐸ__post_com....”foo_bar”ᐳ"}}:::plan
    PgSelectSingle155 --> PgClassExpression166
    __Item169[/"__Item[169∈16]<br />ᐸ168ᐳ"\]:::itemplan
    PgClassExpression168 ==> __Item169
    __Item172[/"__Item[172∈17]<br />ᐸ171ᐳ"\]:::itemplan
    PgClassExpression171 ==> __Item172
    __Item185[/"__Item[185∈19]<br />ᐸ184ᐳ"\]:::itemplan
    PgSelectRows184 ==> __Item185
    PgSelectSingle186{{"PgSelectSingle[186∈19]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    __Item185 --> PgSelectSingle186
    PgClassExpression187{{"PgClassExpression[187∈19]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgSelectSingle186 --> PgClassExpression187
    __Item197[/"__Item[197∈21]<br />ᐸ184ᐳ"\]:::itemplan
    PgSelectRows184 -.-> __Item197
    PgSelectSingle198{{"PgSelectSingle[198∈21]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    __Item197 --> PgSelectSingle198
    PgClassExpression199{{"PgClassExpression[199∈21]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgSelectSingle198 --> PgClassExpression199
    Edge203{{"Edge[203∈22]"}}:::plan
    PgClassExpression202{{"PgClassExpression[202∈22]<br />ᐸ__post_com...al_set__.vᐳ"}}:::plan
    PgCursor205{{"PgCursor[205∈22]"}}:::plan
    PgClassExpression202 & PgCursor205 & Connection182 --> Edge203
    PgSelectSingle201{{"PgSelectSingle[201∈22]<br />ᐸpost_computed_interval_setᐳ"}}:::plan
    Access204{{"Access[204∈22]<br />ᐸ183.cursorDetailsᐳ"}}:::plan
    PgSelectSingle201 & Access204 --> PgCursor205
    __Item200[/"__Item[200∈22]<br />ᐸ195ᐳ"\]:::itemplan
    __ListTransform195 ==> __Item200
    __Item200 --> PgSelectSingle201
    PgSelectSingle201 --> PgClassExpression202
    PgSelect183 --> Access204
    PgSelect215[["PgSelect[215∈25] ➊<br />ᐸpersonᐳ"]]:::plan
    Object12 & Lambda214 & Connection213 & Constant6 & Constant6 & Constant6 --> PgSelect215
    PgSelectRows216[["PgSelectRows[216∈25] ➊"]]:::plan
    PgSelect215 --> PgSelectRows216
    __Item217[/"__Item[217∈26]<br />ᐸ216ᐳ"\]:::itemplan
    PgSelectRows216 ==> __Item217
    PgSelectSingle218{{"PgSelectSingle[218∈26]<br />ᐸpersonᐳ"}}:::plan
    __Item217 --> PgSelectSingle218
    PgSelect229[["PgSelect[229∈27]<br />ᐸperson_friendsᐳ"]]:::plan
    PgClassExpression220{{"PgClassExpression[220∈27]<br />ᐸ__person__ᐳ"}}:::plan
    Object12 & PgClassExpression220 & Lambda228 & Connection227 & Constant6 & Constant6 & Constant6 --> PgSelect229
    PgSelect252[["PgSelect[252∈27]<br />ᐸperson_first_postᐳ"]]:::plan
    Object12 & PgClassExpression220 --> PgSelect252
    PgClassExpression219{{"PgClassExpression[219∈27]<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle218 --> PgClassExpression219
    PgSelectSingle218 --> PgClassExpression220
    PgClassExpression221{{"PgClassExpression[221∈27]<br />ᐸ”c”.”perso..._person__)ᐳ"}}:::plan
    PgSelectSingle218 --> PgClassExpression221
    PgSelectRows230[["PgSelectRows[230∈27]"]]:::plan
    PgSelect229 --> PgSelectRows230
    First254{{"First[254∈27]"}}:::plan
    PgSelectRows255[["PgSelectRows[255∈27]"]]:::plan
    PgSelectRows255 --> First254
    PgSelect252 --> PgSelectRows255
    PgSelectSingle256{{"PgSelectSingle[256∈27]<br />ᐸperson_first_postᐳ"}}:::plan
    First254 --> PgSelectSingle256
    __Item231[/"__Item[231∈28]<br />ᐸ230ᐳ"\]:::itemplan
    PgSelectRows230 ==> __Item231
    PgSelectSingle232{{"PgSelectSingle[232∈28]<br />ᐸperson_friendsᐳ"}}:::plan
    __Item231 --> PgSelectSingle232
    PgSelect244[["PgSelect[244∈29]<br />ᐸperson_friendsᐳ"]]:::plan
    PgClassExpression234{{"PgClassExpression[234∈29]<br />ᐸ__person_friends__ᐳ"}}:::plan
    Object12 & PgClassExpression234 & Lambda228 & Connection242 & Constant319 & Constant6 & Constant6 --> PgSelect244
    PgClassExpression233{{"PgClassExpression[233∈29]<br />ᐸ__person_f...full_name”ᐳ"}}:::plan
    PgSelectSingle232 --> PgClassExpression233
    PgSelectSingle232 --> PgClassExpression234
    PgClassExpression235{{"PgClassExpression[235∈29]<br />ᐸ”c”.”perso...friends__)ᐳ"}}:::plan
    PgSelectSingle232 --> PgClassExpression235
    PgSelectRows245[["PgSelectRows[245∈29]"]]:::plan
    PgSelect244 --> PgSelectRows245
    __Item246[/"__Item[246∈30]<br />ᐸ245ᐳ"\]:::itemplan
    PgSelectRows245 ==> __Item246
    PgSelectSingle247{{"PgSelectSingle[247∈30]<br />ᐸperson_friendsᐳ"}}:::plan
    __Item246 --> PgSelectSingle247
    PgClassExpression248{{"PgClassExpression[248∈31]<br />ᐸ__person_f...full_name”ᐳ"}}:::plan
    PgSelectSingle247 --> PgClassExpression248
    PgClassExpression250{{"PgClassExpression[250∈31]<br />ᐸ”c”.”perso...friends__)ᐳ"}}:::plan
    PgSelectSingle247 --> PgClassExpression250
    PgClassExpression257{{"PgClassExpression[257∈32]<br />ᐸ__person_f...ost__.”id”ᐳ"}}:::plan
    PgSelectSingle256 --> PgClassExpression257
    PgClassExpression258{{"PgClassExpression[258∈32]<br />ᐸ__person_f...”headline”ᐳ"}}:::plan
    PgSelectSingle256 --> PgClassExpression258
    PgSelect265[["PgSelect[265∈33] ➊<br />ᐸedge_caseᐳ"]]:::plan
    Object12 & Lambda264 & Connection263 & Constant6 & Constant6 & Constant6 --> PgSelect265
    PgSelectRows266[["PgSelectRows[266∈33] ➊"]]:::plan
    PgSelect265 --> PgSelectRows266
    __Item267[/"__Item[267∈34]<br />ᐸ266ᐳ"\]:::itemplan
    PgSelectRows266 ==> __Item267
    PgSelectSingle268{{"PgSelectSingle[268∈34]<br />ᐸedge_caseᐳ"}}:::plan
    __Item267 --> PgSelectSingle268
    PgClassExpression269{{"PgClassExpression[269∈35]<br />ᐸ__edge_cas...s_default”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression269
    PgClassExpression270{{"PgClassExpression[270∈35]<br />ᐸ__edge_cas...cast_easy”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression270
    PgClassExpression272{{"PgClassExpression[272∈35]<br />ᐸ”c”.”edge_...ge_case__)ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression272
    PgClassExpression282{{"PgClassExpression[282∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression282
    PgClassExpression287{{"PgClassExpression[287∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression287
    PgClassExpression291{{"PgClassExpression[291∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression291
    PgClassExpression295{{"PgClassExpression[295∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression295
    PgClassExpression300{{"PgClassExpression[300∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression300
    PgClassExpression304{{"PgClassExpression[304∈36] ➊<br />ᐸ”c”.”perso...lder! */<br />)ᐳ"}}:::plan
    PgSelectSingle278 --> PgClassExpression304

    %% define steps

    subgraph "Buckets for queries/v4/procedure-computed-fields"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 10, 11, 125, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 319, 322, 323, 324, 12, 13, 14, 99, 100, 138, 182, 213, 214, 227, 228, 242, 263, 264, 132, 141<br />2: PgSelect[274]<br />3: PgSelectRows[277]<br />ᐳ: First[276], PgSelectSingle[278]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access10,Access11,Object12,Connection13,Lambda14,Connection99,Lambda100,Constant125,__InputObject132,__InputObject138,BakedInput141,Connection182,Connection213,Lambda214,Connection227,Lambda228,Connection242,Connection263,Lambda264,PgSelect274,First276,PgSelectRows277,PgSelectSingle278,Constant308,Constant309,Constant310,Constant311,Constant312,Constant313,Constant314,Constant315,Constant316,Constant317,Constant319,Constant322,Constant323,Constant324 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 13, 6<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[15]<br />2: PgSelectRows[16]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect15,PgSelectRows16 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 12<br /><br />ROOT __Item{2}ᐸ16ᐳ[17]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item17,PgSelectSingle18 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 18, 12<br /><br />ROOT PgSelectSingle{2}ᐸtypesᐳ[18]<br />1: <br />ᐳ: 19, 31, 57, 67<br />2: 20, 32, 58, 68<br />3: 25, 35, 61, 71<br />ᐳ: 24, 26, 27, 28, 30, 34, 36, 37, 47, 60, 62, 70, 72<br />4: PgSelect[38], PgSelect[48]<br />5: PgSelectRows[41], PgSelectRows[51]<br />ᐳ: 40, 42, 50, 52"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression19,PgSelect20,First24,PgSelectRows25,PgSelectSingle26,PgClassExpression27,PgClassExpression28,PgClassExpression30,PgClassExpression31,PgSelect32,First34,PgSelectRows35,PgSelectSingle36,PgClassExpression37,PgSelect38,First40,PgSelectRows41,PgSelectSingle42,PgClassExpression47,PgSelect48,First50,PgSelectRows51,PgSelectSingle52,PgClassExpression57,PgSelect58,First60,PgSelectRows61,PgSelectSingle62,PgClassExpression67,PgSelect68,First70,PgSelectRows71,PgSelectSingle72 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 42<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[42]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression43,PgClassExpression44,PgClassExpression46 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 52<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[52]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression53,PgClassExpression54,PgClassExpression56 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 62<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_compoundTypeᐳ[62]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression63,PgClassExpression64,PgClassExpression66 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 72, 12<br /><br />ROOT PgSelectSingle{3}ᐸfrmcdc_nestedCompoundTypeᐳ[72]<br />1: <br />ᐳ: 73, 85<br />2: PgSelect[74], PgSelect[86]<br />3: PgSelectRows[79], PgSelectRows[89]<br />ᐳ: 78, 80, 88, 90"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression73,PgSelect74,First78,PgSelectRows79,PgSelectSingle80,PgClassExpression85,PgSelect86,First88,PgSelectRows89,PgSelectSingle90 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 80<br /><br />ROOT PgSelectSingle{7}ᐸfrmcdc_compoundTypeᐳ[80]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression81,PgClassExpression82,PgClassExpression84 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 90<br /><br />ROOT PgSelectSingle{7}ᐸfrmcdc_compoundTypeᐳ[90]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression91,PgClassExpression92,PgClassExpression94 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 12, 100, 99, 6, 308, 309, 310, 125, 141, 182<br /><br />ROOT Connectionᐸ97ᐳ[99]<br />1: PgSelect[101]<br />2: PgSelectRows[102]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgSelect101,PgSelectRows102 bucket10
    Bucket11("Bucket 11 (listItem)<br />Deps: 12, 141, 182, 6<br /><br />ROOT __Item{11}ᐸ102ᐳ[103]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Item103,PgSelectSingle104 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 104, 12, 141, 182, 6<br /><br />ROOT PgSelectSingle{11}ᐸpostᐳ[104]<br />1: <br />ᐳ: 105, 106, 107, 110, 114, 116, 119, 123, 127, 131, 168, 171<br />2: PgSelect[143], PgSelect[183]<br />3: PgSelectRows[148], PgSelectRows[184]<br />ᐳ: 147, 149, 150<br />4: PgSelect[151], __ListTransform[195]<br />5: PgSelectRows[153]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression105,PgClassExpression106,PgClassExpression107,PgClassExpression110,PgClassExpression114,PgClassExpression116,PgClassExpression119,PgClassExpression123,PgClassExpression127,PgClassExpression131,PgSelect143,First147,PgSelectRows148,PgSelectSingle149,PgClassExpression150,PgSelect151,PgSelectRows153,PgClassExpression168,PgClassExpression171,PgSelect183,PgSelectRows184,__ListTransform195 bucket12
    Bucket13("Bucket 13 (listItem)<br /><br />ROOT __Item{13}ᐸ153ᐳ[154]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item154,PgSelectSingle155 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 155<br /><br />ROOT PgSelectSingle{13}ᐸpost_computed_compound_type_arrayᐳ[155]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression156,PgClassExpression157,PgClassExpression158,PgClassExpression159,PgClassExpression160,PgClassExpression161,PgClassExpression162,PgClassExpression166 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 162<br /><br />ROOT PgClassExpression{14}ᐸ__post_com...rray__.”g”ᐳ[162]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15 bucket15
    Bucket16("Bucket 16 (listItem)<br /><br />ROOT __Item{16}ᐸ168ᐳ[169]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item169 bucket16
    Bucket17("Bucket 17 (listItem)<br /><br />ROOT __Item{17}ᐸ171ᐳ[172]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,__Item172 bucket17
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 172<br /><br />ROOT __Item{17}ᐸ171ᐳ[172]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    Bucket19("Bucket 19 (listItem)<br /><br />ROOT __Item{19}ᐸ184ᐳ[185]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item185,PgSelectSingle186,PgClassExpression187 bucket19
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 187<br /><br />ROOT PgClassExpression{19}ᐸ__post_com...al_set__.vᐳ[187]"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20 bucket20
    Bucket21("Bucket 21 (subroutine)<br /><br />ROOT PgClassExpression{21}ᐸ__post_com...al_set__.vᐳ[199]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item197,PgSelectSingle198,PgClassExpression199 bucket21
    Bucket22("Bucket 22 (listItem)<br />Deps: 182, 183<br /><br />ROOT __Item{22}ᐸ195ᐳ[200]"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,__Item200,PgSelectSingle201,PgClassExpression202,Edge203,Access204,PgCursor205 bucket22
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 203, 202, 205<br /><br />ROOT Edge{22}[203]"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23 bucket23
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 202<br /><br />ROOT PgClassExpression{22}ᐸ__post_com...al_set__.vᐳ[202]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24 bucket24
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 12, 214, 213, 6, 228, 227, 242, 319<br /><br />ROOT Connectionᐸ211ᐳ[213]<br />1: PgSelect[215]<br />2: PgSelectRows[216]"):::bucket
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect215,PgSelectRows216 bucket25
    Bucket26("Bucket 26 (listItem)<br />Deps: 12, 228, 227, 6, 242, 319<br /><br />ROOT __Item{26}ᐸ216ᐳ[217]"):::bucket
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item217,PgSelectSingle218 bucket26
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 218, 12, 228, 227, 6, 242, 319<br /><br />ROOT PgSelectSingle{26}ᐸpersonᐳ[218]<br />1: <br />ᐳ: 219, 220, 221<br />2: PgSelect[229], PgSelect[252]<br />3: PgSelectRows[230], PgSelectRows[255]<br />ᐳ: First[254], PgSelectSingle[256]"):::bucket
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgClassExpression219,PgClassExpression220,PgClassExpression221,PgSelect229,PgSelectRows230,PgSelect252,First254,PgSelectRows255,PgSelectSingle256 bucket27
    Bucket28("Bucket 28 (listItem)<br />Deps: 12, 228, 242, 319, 6<br /><br />ROOT __Item{28}ᐸ230ᐳ[231]"):::bucket
    classDef bucket28 stroke:#00ffff
    class Bucket28,__Item231,PgSelectSingle232 bucket28
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 232, 12, 228, 242, 319, 6<br /><br />ROOT PgSelectSingle{28}ᐸperson_friendsᐳ[232]<br />1: <br />ᐳ: 233, 234, 235<br />2: PgSelect[244]<br />3: PgSelectRows[245]"):::bucket
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression233,PgClassExpression234,PgClassExpression235,PgSelect244,PgSelectRows245 bucket29
    Bucket30("Bucket 30 (listItem)<br /><br />ROOT __Item{30}ᐸ245ᐳ[246]"):::bucket
    classDef bucket30 stroke:#3cb371
    class Bucket30,__Item246,PgSelectSingle247 bucket30
    Bucket31("Bucket 31 (nullableBoundary)<br />Deps: 247<br /><br />ROOT PgSelectSingle{30}ᐸperson_friendsᐳ[247]"):::bucket
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgClassExpression248,PgClassExpression250 bucket31
    Bucket32("Bucket 32 (nullableBoundary)<br />Deps: 256<br /><br />ROOT PgSelectSingle{27}ᐸperson_first_postᐳ[256]"):::bucket
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgClassExpression257,PgClassExpression258 bucket32
    Bucket33("Bucket 33 (nullableBoundary)<br />Deps: 12, 264, 263, 6<br /><br />ROOT Connectionᐸ261ᐳ[263]<br />1: PgSelect[265]<br />2: PgSelectRows[266]"):::bucket
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgSelect265,PgSelectRows266 bucket33
    Bucket34("Bucket 34 (listItem)<br /><br />ROOT __Item{34}ᐸ266ᐳ[267]"):::bucket
    classDef bucket34 stroke:#696969
    class Bucket34,__Item267,PgSelectSingle268 bucket34
    Bucket35("Bucket 35 (nullableBoundary)<br />Deps: 268<br /><br />ROOT PgSelectSingle{34}ᐸedge_caseᐳ[268]"):::bucket
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgClassExpression269,PgClassExpression270,PgClassExpression272 bucket35
    Bucket36("Bucket 36 (nullableBoundary)<br />Deps: 278<br /><br />ROOT PgSelectSingleᐸpersonᐳ[278]"):::bucket
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgClassExpression282,PgClassExpression287,PgClassExpression291,PgClassExpression295,PgClassExpression300,PgClassExpression304 bucket36
    Bucket0 --> Bucket1 & Bucket10 & Bucket25 & Bucket33 & Bucket36
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5 & Bucket6 & Bucket7
    Bucket7 --> Bucket8 & Bucket9
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12
    Bucket12 --> Bucket13 & Bucket16 & Bucket17 & Bucket19 & Bucket21 & Bucket22
    Bucket13 --> Bucket14
    Bucket14 --> Bucket15
    Bucket17 --> Bucket18
    Bucket19 --> Bucket20
    Bucket22 --> Bucket23
    Bucket23 --> Bucket24
    Bucket25 --> Bucket26
    Bucket26 --> Bucket27
    Bucket27 --> Bucket28 & Bucket32
    Bucket28 --> Bucket29
    Bucket29 --> Bucket30
    Bucket30 --> Bucket31
    Bucket33 --> Bucket34
    Bucket34 --> Bucket35
    end
