%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸperson_secretᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant227{{"Constant[227∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Object10 & Constant227 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect36[["PgSelect[36∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Constant230{{"Constant[230∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Object10 & Constant230 --> PgSelect36
    PgSelect61[["PgSelect[61∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Access59{{"Access[59∈0] ➊<br />ᐸ58.1ᐳ"}}:::plan
    Object10 -->|rejectNull| PgSelect61
    Access59 --> PgSelect61
    PgSelect86[["PgSelect[86∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Access84{{"Access[84∈0] ➊<br />ᐸ83.1ᐳ"}}:::plan
    Object10 -->|rejectNull| PgSelect86
    Access84 --> PgSelect86
    PgSelect108[["PgSelect[108∈0] ➊<br />ᐸleft_armᐳ"]]:::plan
    Constant233{{"Constant[233∈0] ➊<br />ᐸ42ᐳ"}}:::plan
    Object10 & Constant233 --> PgSelect108
    PgSelect138[["PgSelect[138∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Constant235{{"Constant[235∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Object10 & Constant235 --> PgSelect138
    PgSelect162[["PgSelect[162∈0] ➊<br />ᐸpostᐳ"]]:::plan
    Constant236{{"Constant[236∈0] ➊<br />ᐸ7ᐳ"}}:::plan
    Object10 & Constant236 --> PgSelect162
    PgSelect192[["PgSelect[192∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Object10 & Constant227 --> PgSelect192
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0] ➊"}}:::plan
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelectRows12 --> First11
    PgSelect7 --> PgSelectRows12
    PgSelectSingle13{{"PgSelectSingle[13∈0] ➊<br />ᐸperson_secretᐳ"}}:::plan
    First11 --> PgSelectSingle13
    Lambda25{{"Lambda[25∈0] ➊<br />ᐸextractList_pgSelectApplyᐳ"}}:::plan
    Constant239{{"Constant[239∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant239 --> Lambda25
    First38{{"First[38∈0] ➊"}}:::plan
    PgSelectRows39[["PgSelectRows[39∈0] ➊"]]:::plan
    PgSelectRows39 --> First38
    PgSelect36 --> PgSelectRows39
    PgSelectSingle40{{"PgSelectSingle[40∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First38 --> PgSelectSingle40
    Lambda58{{"Lambda[58∈0] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant231{{"Constant[231∈0] ➊<br />ᐸ'fa4f3e13-456c-4a9e-8c1e-37a6e3177d0b'ᐳ"}}:::plan
    Constant231 --> Lambda58
    Lambda58 --> Access59
    First63{{"First[63∈0] ➊"}}:::plan
    PgSelectRows64[["PgSelectRows[64∈0] ➊"]]:::plan
    PgSelectRows64 --> First63
    PgSelect61 --> PgSelectRows64
    PgSelectSingle65{{"PgSelectSingle[65∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First63 --> PgSelectSingle65
    Lambda83{{"Lambda[83∈0] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant232{{"Constant[232∈0] ➊<br />ᐸ'WyJwZW9wbGUiLDBd'ᐳ"}}:::plan
    Constant232 --> Lambda83
    Lambda83 --> Access84
    First88{{"First[88∈0] ➊"}}:::plan
    PgSelectRows89[["PgSelectRows[89∈0] ➊"]]:::plan
    PgSelectRows89 --> First88
    PgSelect86 --> PgSelectRows89
    PgSelectSingle90{{"PgSelectSingle[90∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First88 --> PgSelectSingle90
    First110{{"First[110∈0] ➊"}}:::plan
    PgSelectRows111[["PgSelectRows[111∈0] ➊"]]:::plan
    PgSelectRows111 --> First110
    PgSelect108 --> PgSelectRows111
    PgSelectSingle112{{"PgSelectSingle[112∈0] ➊<br />ᐸleft_armᐳ"}}:::plan
    First110 --> PgSelectSingle112
    Lambda125{{"Lambda[125∈0] ➊<br />ᐸextractList_pgSelectApplyᐳ"}}:::plan
    Constant239 --> Lambda125
    First140{{"First[140∈0] ➊"}}:::plan
    PgSelectRows141[["PgSelectRows[141∈0] ➊"]]:::plan
    PgSelectRows141 --> First140
    PgSelect138 --> PgSelectRows141
    PgSelectSingle142{{"PgSelectSingle[142∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First140 --> PgSelectSingle142
    First164{{"First[164∈0] ➊"}}:::plan
    PgSelectRows165[["PgSelectRows[165∈0] ➊"]]:::plan
    PgSelectRows165 --> First164
    PgSelect162 --> PgSelectRows165
    PgSelectSingle166{{"PgSelectSingle[166∈0] ➊<br />ᐸpostᐳ"}}:::plan
    First164 --> PgSelectSingle166
    Lambda179{{"Lambda[179∈0] ➊<br />ᐸextractList_pgSelectApplyᐳ"}}:::plan
    Constant239 --> Lambda179
    First194{{"First[194∈0] ➊"}}:::plan
    PgSelectRows195[["PgSelectRows[195∈0] ➊"]]:::plan
    PgSelectRows195 --> First194
    PgSelect192 --> PgSelectRows195
    PgSelectSingle196{{"PgSelectSingle[196∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First194 --> PgSelectSingle196
    PgSelect220[["PgSelect[220∈0] ➊<br />ᐸreturn_table_without_grantsᐳ"]]:::plan
    Object10 --> PgSelect220
    First222{{"First[222∈0] ➊"}}:::plan
    PgSelectRows223[["PgSelectRows[223∈0] ➊"]]:::plan
    PgSelectRows223 --> First222
    PgSelect220 --> PgSelectRows223
    PgSelectSingle224{{"PgSelectSingle[224∈0] ➊<br />ᐸreturn_table_without_grantsᐳ"}}:::plan
    First222 --> PgSelectSingle224
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant14{{"Constant[14∈0] ➊<br />ᐸ'person_secrets'ᐳ"}}:::plan
    Connection24{{"Connection[24∈0] ➊<br />ᐸ22ᐳ"}}:::plan
    Constant41{{"Constant[41∈0] ➊<br />ᐸ'people'ᐳ"}}:::plan
    Constant113{{"Constant[113∈0] ➊<br />ᐸ'left_arms'ᐳ"}}:::plan
    Connection124{{"Connection[124∈0] ➊<br />ᐸ122ᐳ"}}:::plan
    Constant167{{"Constant[167∈0] ➊<br />ᐸ'posts'ᐳ"}}:::plan
    Connection178{{"Connection[178∈0] ➊<br />ᐸ176ᐳ"}}:::plan
    Connection207{{"Connection[207∈0] ➊<br />ᐸ203ᐳ"}}:::plan
    List16{{"List[16∈1] ➊<br />ᐸ14,15ᐳ"}}:::plan
    PgClassExpression15{{"PgClassExpression[15∈1] ➊<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant14 & PgClassExpression15 --> List16
    PgSelectSingle13 --> PgClassExpression15
    Lambda17{{"Lambda[17∈1] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List16 --> Lambda17
    PgClassExpression18{{"PgClassExpression[18∈1] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle13 --> PgClassExpression18
    PgSelect26[["PgSelect[26∈2] ➊<br />ᐸperson_secretᐳ"]]:::plan
    Object10 & Lambda25 & Connection24 --> PgSelect26
    PgSelectRows27[["PgSelectRows[27∈2] ➊"]]:::plan
    PgSelect26 --> PgSelectRows27
    __Item28[/"__Item[28∈3]<br />ᐸ27ᐳ"\]:::itemplan
    PgSelectRows27 ==> __Item28
    PgSelectSingle29{{"PgSelectSingle[29∈3]<br />ᐸperson_secretᐳ"}}:::plan
    __Item28 --> PgSelectSingle29
    List32{{"List[32∈4]<br />ᐸ14,31ᐳ"}}:::plan
    PgClassExpression31{{"PgClassExpression[31∈4]<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant14 & PgClassExpression31 --> List32
    PgSelectSingle29 --> PgClassExpression31
    Lambda33{{"Lambda[33∈4]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List32 --> Lambda33
    PgClassExpression34{{"PgClassExpression[34∈4]<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression34
    List43{{"List[43∈5] ➊<br />ᐸ41,42ᐳ"}}:::plan
    PgClassExpression42{{"PgClassExpression[42∈5] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant41 & PgClassExpression42 --> List43
    PgSelect45[["PgSelect[45∈5] ➊<br />ᐸperson_secretᐳ"]]:::plan
    Object10 & PgClassExpression42 --> PgSelect45
    PgSelectSingle40 --> PgClassExpression42
    Lambda44{{"Lambda[44∈5] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List43 --> Lambda44
    First49{{"First[49∈5] ➊"}}:::plan
    PgSelectRows50[["PgSelectRows[50∈5] ➊"]]:::plan
    PgSelectRows50 --> First49
    PgSelect45 --> PgSelectRows50
    PgSelectSingle51{{"PgSelectSingle[51∈5] ➊<br />ᐸperson_secretᐳ"}}:::plan
    First49 --> PgSelectSingle51
    List54{{"List[54∈6] ➊<br />ᐸ14,53ᐳ"}}:::plan
    PgClassExpression53{{"PgClassExpression[53∈6] ➊<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant14 & PgClassExpression53 --> List54
    PgSelectSingle51 --> PgClassExpression53
    Lambda55{{"Lambda[55∈6] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List54 --> Lambda55
    PgClassExpression56{{"PgClassExpression[56∈6] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle51 --> PgClassExpression56
    List68{{"List[68∈7] ➊<br />ᐸ41,67ᐳ"}}:::plan
    PgClassExpression67{{"PgClassExpression[67∈7] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant41 & PgClassExpression67 --> List68
    PgSelect70[["PgSelect[70∈7] ➊<br />ᐸperson_secretᐳ"]]:::plan
    Object10 & PgClassExpression67 --> PgSelect70
    PgSelectSingle65 --> PgClassExpression67
    Lambda69{{"Lambda[69∈7] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List68 --> Lambda69
    First74{{"First[74∈7] ➊"}}:::plan
    PgSelectRows75[["PgSelectRows[75∈7] ➊"]]:::plan
    PgSelectRows75 --> First74
    PgSelect70 --> PgSelectRows75
    PgSelectSingle76{{"PgSelectSingle[76∈7] ➊<br />ᐸperson_secretᐳ"}}:::plan
    First74 --> PgSelectSingle76
    List79{{"List[79∈8] ➊<br />ᐸ14,78ᐳ"}}:::plan
    PgClassExpression78{{"PgClassExpression[78∈8] ➊<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant14 & PgClassExpression78 --> List79
    PgSelectSingle76 --> PgClassExpression78
    Lambda80{{"Lambda[80∈8] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List79 --> Lambda80
    PgClassExpression81{{"PgClassExpression[81∈8] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle76 --> PgClassExpression81
    List93{{"List[93∈9] ➊<br />ᐸ41,92ᐳ"}}:::plan
    PgClassExpression92{{"PgClassExpression[92∈9] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant41 & PgClassExpression92 --> List93
    PgSelect95[["PgSelect[95∈9] ➊<br />ᐸperson_secretᐳ"]]:::plan
    Object10 & PgClassExpression92 --> PgSelect95
    PgSelectSingle90 --> PgClassExpression92
    Lambda94{{"Lambda[94∈9] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List93 --> Lambda94
    First99{{"First[99∈9] ➊"}}:::plan
    PgSelectRows100[["PgSelectRows[100∈9] ➊"]]:::plan
    PgSelectRows100 --> First99
    PgSelect95 --> PgSelectRows100
    PgSelectSingle101{{"PgSelectSingle[101∈9] ➊<br />ᐸperson_secretᐳ"}}:::plan
    First99 --> PgSelectSingle101
    List104{{"List[104∈10] ➊<br />ᐸ14,103ᐳ"}}:::plan
    PgClassExpression103{{"PgClassExpression[103∈10] ➊<br />ᐸ__person_s...person_id”ᐳ"}}:::plan
    Constant14 & PgClassExpression103 --> List104
    PgSelectSingle101 --> PgClassExpression103
    Lambda105{{"Lambda[105∈10] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List104 --> Lambda105
    PgClassExpression106{{"PgClassExpression[106∈10] ➊<br />ᐸ__person_s..._.”sekrit”ᐳ"}}:::plan
    PgSelectSingle101 --> PgClassExpression106
    List115{{"List[115∈11] ➊<br />ᐸ113,114ᐳ"}}:::plan
    PgClassExpression114{{"PgClassExpression[114∈11] ➊<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    Constant113 & PgClassExpression114 --> List115
    PgSelectSingle112 --> PgClassExpression114
    Lambda116{{"Lambda[116∈11] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List115 --> Lambda116
    PgClassExpression117{{"PgClassExpression[117∈11] ➊<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression117
    PgClassExpression118{{"PgClassExpression[118∈11] ➊<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression118
    PgClassExpression119{{"PgClassExpression[119∈11] ➊<br />ᐸ__left_arm__.”mood”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression119
    PgSelect126[["PgSelect[126∈12] ➊<br />ᐸleft_armᐳ"]]:::plan
    Object10 & Lambda125 & Connection124 --> PgSelect126
    PgSelectRows127[["PgSelectRows[127∈12] ➊"]]:::plan
    PgSelect126 --> PgSelectRows127
    __Item128[/"__Item[128∈13]<br />ᐸ127ᐳ"\]:::itemplan
    PgSelectRows127 ==> __Item128
    PgSelectSingle129{{"PgSelectSingle[129∈13]<br />ᐸleft_armᐳ"}}:::plan
    __Item128 --> PgSelectSingle129
    List132{{"List[132∈14]<br />ᐸ113,131ᐳ"}}:::plan
    PgClassExpression131{{"PgClassExpression[131∈14]<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    Constant113 & PgClassExpression131 --> List132
    PgSelectSingle129 --> PgClassExpression131
    Lambda133{{"Lambda[133∈14]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List132 --> Lambda133
    PgClassExpression134{{"PgClassExpression[134∈14]<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression134
    PgClassExpression135{{"PgClassExpression[135∈14]<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression135
    PgClassExpression136{{"PgClassExpression[136∈14]<br />ᐸ__left_arm__.”mood”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression136
    List145{{"List[145∈15] ➊<br />ᐸ41,144ᐳ"}}:::plan
    PgClassExpression144{{"PgClassExpression[144∈15] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant41 & PgClassExpression144 --> List145
    PgSelect147[["PgSelect[147∈15] ➊<br />ᐸleft_armᐳ"]]:::plan
    Object10 & PgClassExpression144 --> PgSelect147
    PgSelectSingle142 --> PgClassExpression144
    Lambda146{{"Lambda[146∈15] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List145 --> Lambda146
    First151{{"First[151∈15] ➊"}}:::plan
    PgSelectRows152[["PgSelectRows[152∈15] ➊"]]:::plan
    PgSelectRows152 --> First151
    PgSelect147 --> PgSelectRows152
    PgSelectSingle153{{"PgSelectSingle[153∈15] ➊<br />ᐸleft_armᐳ"}}:::plan
    First151 --> PgSelectSingle153
    List156{{"List[156∈16] ➊<br />ᐸ113,155ᐳ"}}:::plan
    PgClassExpression155{{"PgClassExpression[155∈16] ➊<br />ᐸ__left_arm__.”id”ᐳ"}}:::plan
    Constant113 & PgClassExpression155 --> List156
    PgSelectSingle153 --> PgClassExpression155
    Lambda157{{"Lambda[157∈16] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List156 --> Lambda157
    PgClassExpression158{{"PgClassExpression[158∈16] ➊<br />ᐸ__left_arm...person_id”ᐳ"}}:::plan
    PgSelectSingle153 --> PgClassExpression158
    PgClassExpression159{{"PgClassExpression[159∈16] ➊<br />ᐸ__left_arm...in_metres”ᐳ"}}:::plan
    PgSelectSingle153 --> PgClassExpression159
    PgClassExpression160{{"PgClassExpression[160∈16] ➊<br />ᐸ__left_arm__.”mood”ᐳ"}}:::plan
    PgSelectSingle153 --> PgClassExpression160
    List169{{"List[169∈17] ➊<br />ᐸ167,168ᐳ"}}:::plan
    PgClassExpression168{{"PgClassExpression[168∈17] ➊<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant167 & PgClassExpression168 --> List169
    PgSelectSingle166 --> PgClassExpression168
    Lambda170{{"Lambda[170∈17] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List169 --> Lambda170
    PgClassExpression171{{"PgClassExpression[171∈17] ➊<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle166 --> PgClassExpression171
    PgClassExpression172{{"PgClassExpression[172∈17] ➊<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle166 --> PgClassExpression172
    PgClassExpression173{{"PgClassExpression[173∈17] ➊<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgSelectSingle166 --> PgClassExpression173
    PgSelect180[["PgSelect[180∈18] ➊<br />ᐸpostᐳ"]]:::plan
    Object10 & Lambda179 & Connection178 --> PgSelect180
    PgSelectRows181[["PgSelectRows[181∈18] ➊"]]:::plan
    PgSelect180 --> PgSelectRows181
    __Item182[/"__Item[182∈19]<br />ᐸ181ᐳ"\]:::itemplan
    PgSelectRows181 ==> __Item182
    PgSelectSingle183{{"PgSelectSingle[183∈19]<br />ᐸpostᐳ"}}:::plan
    __Item182 --> PgSelectSingle183
    List186{{"List[186∈20]<br />ᐸ167,185ᐳ"}}:::plan
    PgClassExpression185{{"PgClassExpression[185∈20]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant167 & PgClassExpression185 --> List186
    PgSelectSingle183 --> PgClassExpression185
    Lambda187{{"Lambda[187∈20]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List186 --> Lambda187
    PgClassExpression188{{"PgClassExpression[188∈20]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle183 --> PgClassExpression188
    PgClassExpression189{{"PgClassExpression[189∈20]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle183 --> PgClassExpression189
    PgClassExpression190{{"PgClassExpression[190∈20]<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgSelectSingle183 --> PgClassExpression190
    PgSelect209[["PgSelect[209∈21] ➊<br />ᐸpostᐳ"]]:::plan
    PgClassExpression198{{"PgClassExpression[198∈21] ➊<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Object10 & PgClassExpression198 & Lambda179 & Connection207 --> PgSelect209
    List199{{"List[199∈21] ➊<br />ᐸ41,198ᐳ"}}:::plan
    Constant41 & PgClassExpression198 --> List199
    PgSelectSingle196 --> PgClassExpression198
    Lambda200{{"Lambda[200∈21] ➊<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List199 --> Lambda200
    PgSelectRows210[["PgSelectRows[210∈21] ➊"]]:::plan
    PgSelect209 --> PgSelectRows210
    __Item211[/"__Item[211∈22]<br />ᐸ210ᐳ"\]:::itemplan
    PgSelectRows210 ==> __Item211
    PgSelectSingle212{{"PgSelectSingle[212∈22]<br />ᐸpostᐳ"}}:::plan
    __Item211 --> PgSelectSingle212
    List215{{"List[215∈23]<br />ᐸ167,214ᐳ"}}:::plan
    PgClassExpression214{{"PgClassExpression[214∈23]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    Constant167 & PgClassExpression214 --> List215
    PgSelectSingle212 --> PgClassExpression214
    Lambda216{{"Lambda[216∈23]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List215 --> Lambda216
    PgClassExpression217{{"PgClassExpression[217∈23]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle212 --> PgClassExpression217
    PgClassExpression218{{"PgClassExpression[218∈23]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle212 --> PgClassExpression218
    PgClassExpression219{{"PgClassExpression[219∈23]<br />ᐸ__post__.”author_id”ᐳ"}}:::plan
    PgSelectSingle212 --> PgClassExpression219
    PgClassExpression225{{"PgClassExpression[225∈24] ➊<br />ᐸ__return_t...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression225
    PgClassExpression226{{"PgClassExpression[226∈24] ➊<br />ᐸ__return_t...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression226

    %% define steps

    subgraph "Buckets for queries/v4/rbac.basic"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 14, 24, 41, 113, 124, 167, 178, 207, 227, 230, 231, 232, 233, 235, 236, 239, 10, 25, 58, 59, 83, 84, 125, 179<br />2: 7, 36, 61, 86, 108, 138, 162, 192, 220<br />3: 12, 39, 64, 89, 111, 141, 165, 195, 223<br />ᐳ: 11, 13, 38, 40, 63, 65, 88, 90, 110, 112, 140, 142, 164, 166, 194, 196, 222, 224"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectRows12,PgSelectSingle13,Constant14,Connection24,Lambda25,PgSelect36,First38,PgSelectRows39,PgSelectSingle40,Constant41,Lambda58,Access59,PgSelect61,First63,PgSelectRows64,PgSelectSingle65,Lambda83,Access84,PgSelect86,First88,PgSelectRows89,PgSelectSingle90,PgSelect108,First110,PgSelectRows111,PgSelectSingle112,Constant113,Connection124,Lambda125,PgSelect138,First140,PgSelectRows141,PgSelectSingle142,PgSelect162,First164,PgSelectRows165,PgSelectSingle166,Constant167,Connection178,Lambda179,PgSelect192,First194,PgSelectRows195,PgSelectSingle196,Connection207,PgSelect220,First222,PgSelectRows223,PgSelectSingle224,Constant227,Constant230,Constant231,Constant232,Constant233,Constant235,Constant236,Constant239 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 14<br /><br />ROOT PgSelectSingleᐸperson_secretᐳ[13]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression15,List16,Lambda17,PgClassExpression18 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 10, 25, 24, 14<br /><br />ROOT Connectionᐸ22ᐳ[24]<br />1: PgSelect[26]<br />2: PgSelectRows[27]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgSelect26,PgSelectRows27 bucket2
    Bucket3("Bucket 3 (listItem)<br />Deps: 14<br /><br />ROOT __Item{3}ᐸ27ᐳ[28]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item28,PgSelectSingle29 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 29, 14<br /><br />ROOT PgSelectSingle{3}ᐸperson_secretᐳ[29]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression31,List32,Lambda33,PgClassExpression34 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 40, 41, 10, 14<br /><br />ROOT PgSelectSingleᐸpersonᐳ[40]<br />1: <br />ᐳ: 42, 43, 44<br />2: PgSelect[45]<br />3: PgSelectRows[50]<br />ᐳ: First[49], PgSelectSingle[51]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression42,List43,Lambda44,PgSelect45,First49,PgSelectRows50,PgSelectSingle51 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 51, 14<br /><br />ROOT PgSelectSingle{5}ᐸperson_secretᐳ[51]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression53,List54,Lambda55,PgClassExpression56 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 65, 41, 10, 14<br /><br />ROOT PgSelectSingleᐸpersonᐳ[65]<br />1: <br />ᐳ: 67, 68, 69<br />2: PgSelect[70]<br />3: PgSelectRows[75]<br />ᐳ: First[74], PgSelectSingle[76]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression67,List68,Lambda69,PgSelect70,First74,PgSelectRows75,PgSelectSingle76 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 76, 14<br /><br />ROOT PgSelectSingle{7}ᐸperson_secretᐳ[76]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression78,List79,Lambda80,PgClassExpression81 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 90, 41, 10, 14<br /><br />ROOT PgSelectSingleᐸpersonᐳ[90]<br />1: <br />ᐳ: 92, 93, 94<br />2: PgSelect[95]<br />3: PgSelectRows[100]<br />ᐳ: First[99], PgSelectSingle[101]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression92,List93,Lambda94,PgSelect95,First99,PgSelectRows100,PgSelectSingle101 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 101, 14<br /><br />ROOT PgSelectSingle{9}ᐸperson_secretᐳ[101]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression103,List104,Lambda105,PgClassExpression106 bucket10
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 112, 113<br /><br />ROOT PgSelectSingleᐸleft_armᐳ[112]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression114,List115,Lambda116,PgClassExpression117,PgClassExpression118,PgClassExpression119 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 10, 125, 124, 113<br /><br />ROOT Connectionᐸ122ᐳ[124]<br />1: PgSelect[126]<br />2: PgSelectRows[127]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgSelect126,PgSelectRows127 bucket12
    Bucket13("Bucket 13 (listItem)<br />Deps: 113<br /><br />ROOT __Item{13}ᐸ127ᐳ[128]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item128,PgSelectSingle129 bucket13
    Bucket14("Bucket 14 (nullableBoundary)<br />Deps: 129, 113<br /><br />ROOT PgSelectSingle{13}ᐸleft_armᐳ[129]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression131,List132,Lambda133,PgClassExpression134,PgClassExpression135,PgClassExpression136 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 142, 41, 10, 113<br /><br />ROOT PgSelectSingleᐸpersonᐳ[142]<br />1: <br />ᐳ: 144, 145, 146<br />2: PgSelect[147]<br />3: PgSelectRows[152]<br />ᐳ: First[151], PgSelectSingle[153]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression144,List145,Lambda146,PgSelect147,First151,PgSelectRows152,PgSelectSingle153 bucket15
    Bucket16("Bucket 16 (nullableBoundary)<br />Deps: 153, 113<br /><br />ROOT PgSelectSingle{15}ᐸleft_armᐳ[153]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgClassExpression155,List156,Lambda157,PgClassExpression158,PgClassExpression159,PgClassExpression160 bucket16
    Bucket17("Bucket 17 (nullableBoundary)<br />Deps: 166, 167<br /><br />ROOT PgSelectSingleᐸpostᐳ[166]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,PgClassExpression168,List169,Lambda170,PgClassExpression171,PgClassExpression172,PgClassExpression173 bucket17
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 10, 179, 178, 167<br /><br />ROOT Connectionᐸ176ᐳ[178]<br />1: PgSelect[180]<br />2: PgSelectRows[181]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgSelect180,PgSelectRows181 bucket18
    Bucket19("Bucket 19 (listItem)<br />Deps: 167<br /><br />ROOT __Item{19}ᐸ181ᐳ[182]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item182,PgSelectSingle183 bucket19
    Bucket20("Bucket 20 (nullableBoundary)<br />Deps: 183, 167<br /><br />ROOT PgSelectSingle{19}ᐸpostᐳ[183]"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgClassExpression185,List186,Lambda187,PgClassExpression188,PgClassExpression189,PgClassExpression190 bucket20
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 196, 41, 10, 179, 207, 167<br /><br />ROOT PgSelectSingleᐸpersonᐳ[196]<br />1: <br />ᐳ: 198, 199, 200<br />2: PgSelect[209]<br />3: PgSelectRows[210]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgClassExpression198,List199,Lambda200,PgSelect209,PgSelectRows210 bucket21
    Bucket22("Bucket 22 (listItem)<br />Deps: 167<br /><br />ROOT __Item{22}ᐸ210ᐳ[211]"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,__Item211,PgSelectSingle212 bucket22
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 212, 167<br /><br />ROOT PgSelectSingle{22}ᐸpostᐳ[212]"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression214,List215,Lambda216,PgClassExpression217,PgClassExpression218,PgClassExpression219 bucket23
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 224<br /><br />ROOT PgSelectSingleᐸreturn_table_without_grantsᐳ[224]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24,PgClassExpression225,PgClassExpression226 bucket24
    Bucket0 --> Bucket1 & Bucket2 & Bucket5 & Bucket7 & Bucket9 & Bucket11 & Bucket12 & Bucket15 & Bucket17 & Bucket18 & Bucket21 & Bucket24
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket9 --> Bucket10
    Bucket12 --> Bucket13
    Bucket13 --> Bucket14
    Bucket15 --> Bucket16
    Bucket18 --> Bucket19
    Bucket19 --> Bucket20
    Bucket21 --> Bucket22
    Bucket22 --> Bucket23
    end
