%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/v4/streamLoads"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 15, 37, 23, 24, 7<br /><br />ROOT Connectionᐸ9ᐳ[15]<br />1: PgSelect[17]<br />2: PgSelectRows[19]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 13, 23, 24, 7<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21, 13, 23, 24, 7<br /><br />ROOT PgSelectSingle{2}ᐸpersonᐳ[21]<br />1: <br />ᐳ: PgClassExpression[22]<br />2: PgSelect[25]<br />3: PgSelectRows[32]"):::bucket
    Bucket4("Bucket 4 (listItem)<br /><br />ROOT __Item{4}ᐸ32ᐳ[33]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4

    %% plan dependencies
    Object13{{"Object[13∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access12 --> Object13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access12
    Connection15{{"Connection[15∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant37{{"Constant[37∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant37 --> Connection15
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant23{{"Constant[23∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant24{{"Constant[24∈0] ➊<br />ᐸtrueᐳ"}}:::plan
    PgSelect17[["PgSelect[17∈1] ➊<br />ᐸpersonᐳ"]]:::plan
    Object13 & Connection15 & Constant37 --> PgSelect17
    PgSelectRows19[["PgSelectRows[19∈1] ➊"]]:::plan
    PgSelect17 --> PgSelectRows19
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelectRows19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸpersonᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    PgSelect25[["PgSelect[25∈3@s]<br />ᐸpostᐳ"]]:::plan
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Object13 & PgClassExpression22 --> PgSelect25
    PgSelectSingle21 --> PgClassExpression22
    PgSelectRows32[["PgSelectRows[32∈3@s]"]]:::plan
    PgSelect25 --> PgSelectRows32
    __Item33[/"__Item[33∈4]<br />ᐸ32ᐳ"\]:::itemplan
    PgSelectRows32 ==> __Item33
    PgSelectSingle34{{"PgSelectSingle[34∈4]<br />ᐸpostᐳ"}}:::plan
    __Item33 --> PgSelectSingle34
    PgClassExpression35{{"PgClassExpression[35∈4]<br />ᐸ__post__.”id”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression35
    PgClassExpression36{{"PgClassExpression[36∈4]<br />ᐸ__post__.”headline”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression36

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access12,Object13,Connection15,Constant23,Constant24,Constant37 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect17,PgSelectRows19 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression22,PgSelect25,PgSelectRows32 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item33,PgSelectSingle34,PgClassExpression35,PgClassExpression36 bucket4

