%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Node8{{"Node[8∈0]"}}:::plan
    Lambda9{{"Lambda[9∈0]<br />ᐸdecodeNodeIdWithCodecsᐳ"}}:::plan
    Lambda9 --> Node8
    Constant178{{"Constant[178∈0]<br />ᐸ'WyJ0eXBlcyIsMTFd'ᐳ"}}:::plan
    Constant178 --> Lambda9
    __Value0["__Value[0∈0]"]:::plan
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    PgSelect70[["PgSelect[70∈1]<br />ᐸcompound_keyᐳ<br />ᐳCompoundKey"]]:::plan
    Object17{{"Object[17∈1]<br />ᐸ{pgSettings,withPgClient}ᐳ<br />ᐳInput<br />ᐳPatch<br />ᐳReserved<br />ᐳReservedPatchRecord<br />ᐳReservedInputRecord<br />ᐳDefaultValue<br />ᐳCompoundKey<br />ᐳPerson<br />ᐳPost<br />ᐳType<br />ᐳPersonSecret<br />ᐳLeftArm<br />ᐳMyTable<br />ᐳViewTable<br />ᐳSimilarTable1<br />ᐳSimilarTable2<br />ᐳNullTestRecord<br />ᐳIssue756"}}:::plan
    Access176{{"Access[176∈1]<br />ᐸ9.base64JSON.1ᐳ<br />ᐳInput<br />ᐳPatch<br />ᐳReserved<br />ᐳReservedPatchRecord<br />ᐳReservedInputRecord<br />ᐳDefaultValue<br />ᐳCompoundKey<br />ᐳPerson<br />ᐳPost<br />ᐳType<br />ᐳPersonSecret<br />ᐳLeftArm<br />ᐳMyTable<br />ᐳViewTable<br />ᐳSimilarTable1<br />ᐳSimilarTable2<br />ᐳNullTestRecord<br />ᐳIssue756"}}:::plan
    Access177{{"Access[177∈1]<br />ᐸ9.base64JSON.2ᐳ<br />ᐳCompoundKey"}}:::plan
    Object17 & Access176 & Access177 --> PgSelect70
    PgSelect14[["PgSelect[14∈1]<br />ᐸinputsᐳ<br />ᐳInput"]]:::plan
    Object17 & Access176 --> PgSelect14
    Access15{{"Access[15∈1]<br />ᐸ3.pgSettingsᐳ<br />ᐳInput<br />ᐳPatch<br />ᐳReserved<br />ᐳReservedPatchRecord<br />ᐳReservedInputRecord<br />ᐳDefaultValue<br />ᐳCompoundKey<br />ᐳPerson<br />ᐳPost<br />ᐳType<br />ᐳPersonSecret<br />ᐳLeftArm<br />ᐳMyTable<br />ᐳViewTable<br />ᐳSimilarTable1<br />ᐳSimilarTable2<br />ᐳNullTestRecord<br />ᐳIssue756"}}:::plan
    Access16{{"Access[16∈1]<br />ᐸ3.withPgClientᐳ<br />ᐳInput<br />ᐳPatch<br />ᐳReserved<br />ᐳReservedPatchRecord<br />ᐳReservedInputRecord<br />ᐳDefaultValue<br />ᐳCompoundKey<br />ᐳPerson<br />ᐳPost<br />ᐳType<br />ᐳPersonSecret<br />ᐳLeftArm<br />ᐳMyTable<br />ᐳViewTable<br />ᐳSimilarTable1<br />ᐳSimilarTable2<br />ᐳNullTestRecord<br />ᐳIssue756"}}:::plan
    Access15 & Access16 --> Object17
    PgSelect23[["PgSelect[23∈1]<br />ᐸpatchsᐳ<br />ᐳPatch"]]:::plan
    Object17 & Access176 --> PgSelect23
    PgSelect32[["PgSelect[32∈1]<br />ᐸreservedᐳ<br />ᐳReserved"]]:::plan
    Object17 & Access176 --> PgSelect32
    PgSelect41[["PgSelect[41∈1]<br />ᐸreservedPatchsᐳ<br />ᐳReservedPatchRecord"]]:::plan
    Object17 & Access176 --> PgSelect41
    PgSelect50[["PgSelect[50∈1]<br />ᐸreserved_inputᐳ<br />ᐳReservedInputRecord"]]:::plan
    Object17 & Access176 --> PgSelect50
    PgSelect59[["PgSelect[59∈1]<br />ᐸdefault_valueᐳ<br />ᐳDefaultValue"]]:::plan
    Object17 & Access176 --> PgSelect59
    PgSelect79[["PgSelect[79∈1]<br />ᐸpersonᐳ<br />ᐳPerson"]]:::plan
    Object17 & Access176 --> PgSelect79
    PgSelect88[["PgSelect[88∈1]<br />ᐸpostᐳ<br />ᐳPost"]]:::plan
    Object17 & Access176 --> PgSelect88
    PgSelect97[["PgSelect[97∈1]<br />ᐸtypesᐳ<br />ᐳType"]]:::plan
    Object17 & Access176 --> PgSelect97
    PgSelect107[["PgSelect[107∈1]<br />ᐸperson_secretᐳ<br />ᐳPersonSecret"]]:::plan
    Object17 & Access176 --> PgSelect107
    PgSelect116[["PgSelect[116∈1]<br />ᐸleft_armᐳ<br />ᐳLeftArm"]]:::plan
    Object17 & Access176 --> PgSelect116
    PgSelect125[["PgSelect[125∈1]<br />ᐸmy_tableᐳ<br />ᐳMyTable"]]:::plan
    Object17 & Access176 --> PgSelect125
    PgSelect134[["PgSelect[134∈1]<br />ᐸview_tableᐳ<br />ᐳViewTable"]]:::plan
    Object17 & Access176 --> PgSelect134
    PgSelect143[["PgSelect[143∈1]<br />ᐸsimilar_table_1ᐳ<br />ᐳSimilarTable1"]]:::plan
    Object17 & Access176 --> PgSelect143
    PgSelect152[["PgSelect[152∈1]<br />ᐸsimilar_table_2ᐳ<br />ᐳSimilarTable2"]]:::plan
    Object17 & Access176 --> PgSelect152
    PgSelect161[["PgSelect[161∈1]<br />ᐸnull_test_recordᐳ<br />ᐳNullTestRecord"]]:::plan
    Object17 & Access176 --> PgSelect161
    PgSelect170[["PgSelect[170∈1]<br />ᐸissue756ᐳ<br />ᐳIssue756"]]:::plan
    Object17 & Access176 --> PgSelect170
    __Value3 --> Access15
    __Value3 --> Access16
    First18{{"First[18∈1]"}}:::plan
    PgSelect14 --> First18
    PgSelectSingle19{{"PgSelectSingle[19∈1]<br />ᐸinputsᐳ"}}:::plan
    First18 --> PgSelectSingle19
    First27{{"First[27∈1]"}}:::plan
    PgSelect23 --> First27
    PgSelectSingle28{{"PgSelectSingle[28∈1]<br />ᐸpatchsᐳ"}}:::plan
    First27 --> PgSelectSingle28
    First36{{"First[36∈1]"}}:::plan
    PgSelect32 --> First36
    PgSelectSingle37{{"PgSelectSingle[37∈1]<br />ᐸreservedᐳ"}}:::plan
    First36 --> PgSelectSingle37
    First45{{"First[45∈1]"}}:::plan
    PgSelect41 --> First45
    PgSelectSingle46{{"PgSelectSingle[46∈1]<br />ᐸreservedPatchsᐳ"}}:::plan
    First45 --> PgSelectSingle46
    First54{{"First[54∈1]"}}:::plan
    PgSelect50 --> First54
    PgSelectSingle55{{"PgSelectSingle[55∈1]<br />ᐸreserved_inputᐳ"}}:::plan
    First54 --> PgSelectSingle55
    First63{{"First[63∈1]"}}:::plan
    PgSelect59 --> First63
    PgSelectSingle64{{"PgSelectSingle[64∈1]<br />ᐸdefault_valueᐳ"}}:::plan
    First63 --> PgSelectSingle64
    First74{{"First[74∈1]"}}:::plan
    PgSelect70 --> First74
    PgSelectSingle75{{"PgSelectSingle[75∈1]<br />ᐸcompound_keyᐳ"}}:::plan
    First74 --> PgSelectSingle75
    First83{{"First[83∈1]"}}:::plan
    PgSelect79 --> First83
    PgSelectSingle84{{"PgSelectSingle[84∈1]<br />ᐸpersonᐳ"}}:::plan
    First83 --> PgSelectSingle84
    First92{{"First[92∈1]"}}:::plan
    PgSelect88 --> First92
    PgSelectSingle93{{"PgSelectSingle[93∈1]<br />ᐸpostᐳ"}}:::plan
    First92 --> PgSelectSingle93
    First101{{"First[101∈1]"}}:::plan
    PgSelect97 --> First101
    PgSelectSingle102{{"PgSelectSingle[102∈1]<br />ᐸtypesᐳ"}}:::plan
    First101 --> PgSelectSingle102
    PgClassExpression103{{"PgClassExpression[103∈1]<br />ᐸ__types__.”id”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression103
    First111{{"First[111∈1]"}}:::plan
    PgSelect107 --> First111
    PgSelectSingle112{{"PgSelectSingle[112∈1]<br />ᐸperson_secretᐳ"}}:::plan
    First111 --> PgSelectSingle112
    First120{{"First[120∈1]"}}:::plan
    PgSelect116 --> First120
    PgSelectSingle121{{"PgSelectSingle[121∈1]<br />ᐸleft_armᐳ"}}:::plan
    First120 --> PgSelectSingle121
    First129{{"First[129∈1]"}}:::plan
    PgSelect125 --> First129
    PgSelectSingle130{{"PgSelectSingle[130∈1]<br />ᐸmy_tableᐳ"}}:::plan
    First129 --> PgSelectSingle130
    First138{{"First[138∈1]"}}:::plan
    PgSelect134 --> First138
    PgSelectSingle139{{"PgSelectSingle[139∈1]<br />ᐸview_tableᐳ"}}:::plan
    First138 --> PgSelectSingle139
    First147{{"First[147∈1]"}}:::plan
    PgSelect143 --> First147
    PgSelectSingle148{{"PgSelectSingle[148∈1]<br />ᐸsimilar_table_1ᐳ"}}:::plan
    First147 --> PgSelectSingle148
    First156{{"First[156∈1]"}}:::plan
    PgSelect152 --> First156
    PgSelectSingle157{{"PgSelectSingle[157∈1]<br />ᐸsimilar_table_2ᐳ"}}:::plan
    First156 --> PgSelectSingle157
    First165{{"First[165∈1]"}}:::plan
    PgSelect161 --> First165
    PgSelectSingle166{{"PgSelectSingle[166∈1]<br />ᐸnull_test_recordᐳ"}}:::plan
    First165 --> PgSelectSingle166
    First174{{"First[174∈1]"}}:::plan
    PgSelect170 --> First174
    PgSelectSingle175{{"PgSelectSingle[175∈1]<br />ᐸissue756ᐳ"}}:::plan
    First174 --> PgSelectSingle175
    Lambda9 --> Access176
    Lambda9 --> Access177

    %% define steps

    subgraph "Buckets for queries/v4/types-single-node"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,Node8,Lambda9,Constant178 bucket0
    Bucket1("Bucket 1 (polymorphic)<br />Query,Input,Patch,Reserved,ReservedPatchRecord,ReservedInputRecord,DefaultValue,CompoundKey,Person,Post,Type,PersonSecret,LeftArm,MyTable,ViewTable,SimilarTable1,SimilarTable2,NullTestRecord,Issue756<br />Deps: 3, 9, 8, 5<br />ᐳQuery<br />ᐳInput<br />ᐳPatch<br />ᐳReserved<br />ᐳReservedPatchRecord<br />ᐳReservedInputRecord<br />ᐳDefaultValue<br />ᐳCompoundKey<br />ᐳPerson<br />ᐳPost<br />ᐳType<br />ᐳPersonSecret<br />ᐳLeftArm<br />ᐳMyTable<br />ᐳViewTable<br />ᐳSimilarTable1<br />ᐳSimilarTable2<br />ᐳNullTestRecord<br />ᐳIssue756<br />1: <br />ᐳ: 15, 16, 176, 177, 17<br />2: 14, 23, 32, 41, 50, 59, 70, 79, 88, 97, 107, 116, 125, 134, 143, 152, 161, 170<br />ᐳ: 18, 19, 27, 28, 36, 37, 45, 46, 54, 55, 63, 64, 74, 75, 83, 84, 92, 93, 101, 102, 103, 111, 112, 120, 121, 129, 130, 138, 139, 147, 148, 156, 157, 165, 166, 174, 175"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect14,Access15,Access16,Object17,First18,PgSelectSingle19,PgSelect23,First27,PgSelectSingle28,PgSelect32,First36,PgSelectSingle37,PgSelect41,First45,PgSelectSingle46,PgSelect50,First54,PgSelectSingle55,PgSelect59,First63,PgSelectSingle64,PgSelect70,First74,PgSelectSingle75,PgSelect79,First83,PgSelectSingle84,PgSelect88,First92,PgSelectSingle93,PgSelect97,First101,PgSelectSingle102,PgClassExpression103,PgSelect107,First111,PgSelectSingle112,PgSelect116,First120,PgSelectSingle121,PgSelect125,First129,PgSelectSingle130,PgSelect134,First138,PgSelectSingle139,PgSelect143,First147,PgSelectSingle148,PgSelect152,First156,PgSelectSingle157,PgSelect161,First165,PgSelectSingle166,PgSelect170,First174,PgSelectSingle175,Access176,Access177 bucket1
    Bucket0 --> Bucket1
    classDef unary fill:#fafffa,borderWidth:8px
    class Node8,Lambda9,__Value0,__Value3,__Value5,Constant178,PgSelect70,PgSelect14,Object17,PgSelect23,PgSelect32,PgSelect41,PgSelect50,PgSelect59,PgSelect79,PgSelect88,PgSelect97,PgSelect107,PgSelect116,PgSelect125,PgSelect134,PgSelect143,PgSelect152,PgSelect161,PgSelect170,Access15,Access16,First18,PgSelectSingle19,First27,PgSelectSingle28,First36,PgSelectSingle37,First45,PgSelectSingle46,First54,PgSelectSingle55,First63,PgSelectSingle64,First74,PgSelectSingle75,First83,PgSelectSingle84,First92,PgSelectSingle93,First101,PgSelectSingle102,PgClassExpression103,First111,PgSelectSingle112,First120,PgSelectSingle121,First129,PgSelectSingle130,First138,PgSelectSingle139,First147,PgSelectSingle148,First156,PgSelectSingle157,First165,PgSelectSingle166,First174,PgSelectSingle175,Access176,Access177 unary
    end
