%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect24[["PgSelect[24∈0] ➊<br />ᐸcompound_keyᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant48{{"Constant[48∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Constant49{{"Constant[49∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Object10 & Constant48 & Constant49 --> PgSelect24
    PgSelect32[["PgSelect[32∈0] ➊<br />ᐸcompound_keyᐳ"]]:::plan
    Constant50{{"Constant[50∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Object10 & Constant50 & Constant50 --> PgSelect32
    PgSelect40[["PgSelect[40∈0] ➊<br />ᐸcompound_keyᐳ"]]:::plan
    Constant53{{"Constant[53∈0] ➊<br />ᐸ100ᐳ"}}:::plan
    Object10 & Constant48 & Constant53 --> PgSelect40
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Constant46{{"Constant[46∈0] ➊<br />ᐸ'sara.smith@email.com'ᐳ"}}:::plan
    Object10 & Constant46 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect16[["PgSelect[16∈0] ➊<br />ᐸpersonᐳ"]]:::plan
    Constant47{{"Constant[47∈0] ➊<br />ᐸ'does.not.exist@email.com'ᐳ"}}:::plan
    Object10 & Constant47 --> PgSelect16
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0] ➊"}}:::plan
    PgSelect7 --> First11
    PgSelectSingle12{{"PgSelectSingle[12∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First11 --> PgSelectSingle12
    First18{{"First[18∈0] ➊"}}:::plan
    PgSelect16 --> First18
    PgSelectSingle19{{"PgSelectSingle[19∈0] ➊<br />ᐸpersonᐳ"}}:::plan
    First18 --> PgSelectSingle19
    First26{{"First[26∈0] ➊"}}:::plan
    PgSelect24 --> First26
    PgSelectSingle27{{"PgSelectSingle[27∈0] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    First26 --> PgSelectSingle27
    First34{{"First[34∈0] ➊"}}:::plan
    PgSelect32 --> First34
    PgSelectSingle35{{"PgSelectSingle[35∈0] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    First34 --> PgSelectSingle35
    First42{{"First[42∈0] ➊"}}:::plan
    PgSelect40 --> First42
    PgSelectSingle43{{"PgSelectSingle[43∈0] ➊<br />ᐸcompound_keyᐳ"}}:::plan
    First42 --> PgSelectSingle43
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgClassExpression13{{"PgClassExpression[13∈1] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression13
    PgClassExpression14{{"PgClassExpression[14∈1] ➊<br />ᐸ__person__.”email”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression14
    PgClassExpression20{{"PgClassExpression[20∈2] ➊<br />ᐸ__person__...full_name”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgClassExpression21{{"PgClassExpression[21∈2] ➊<br />ᐸ__person__.”email”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression21
    PgClassExpression28{{"PgClassExpression[28∈3] ➊<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈3] ➊<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression29
    PgClassExpression36{{"PgClassExpression[36∈4] ➊<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle35 --> PgClassExpression36
    PgClassExpression37{{"PgClassExpression[37∈4] ➊<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle35 --> PgClassExpression37
    PgClassExpression44{{"PgClassExpression[44∈5] ➊<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression44
    PgClassExpression45{{"PgClassExpression[45∈5] ➊<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression45

    %% define steps

    subgraph "Buckets for queries/v4/unique-constraints"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 46, 47, 48, 49, 50, 53, 10<br />2: 7, 16, 24, 32, 40<br />ᐳ: 11, 12, 18, 19, 26, 27, 34, 35, 42, 43"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectSingle12,PgSelect16,First18,PgSelectSingle19,PgSelect24,First26,PgSelectSingle27,PgSelect32,First34,PgSelectSingle35,PgSelect40,First42,PgSelectSingle43,Constant46,Constant47,Constant48,Constant49,Constant50,Constant53 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12<br /><br />ROOT PgSelectSingleᐸpersonᐳ[12]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression13,PgClassExpression14 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 19<br /><br />ROOT PgSelectSingleᐸpersonᐳ[19]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression20,PgClassExpression21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 27<br /><br />ROOT PgSelectSingleᐸcompound_keyᐳ[27]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression28,PgClassExpression29 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 35<br /><br />ROOT PgSelectSingleᐸcompound_keyᐳ[35]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression36,PgClassExpression37 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 43<br /><br />ROOT PgSelectSingleᐸcompound_keyᐳ[43]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression44,PgClassExpression45 bucket5
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5
    end
