%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant49{{"Constant[49∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant50{{"Constant[50∈0] ➊<br />ᐸsql.identifier(”unique_foreign_key”)ᐳ"}}:::plan
    Constant51{{"Constant[51∈0] ➊<br />ᐸRecordCodec(uniqueForeignKey)ᐳ"}}:::plan
    Constant65{{"Constant[65∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant66{{"Constant[66∈0] ➊<br />ᐸsql.identifier(”compound_key”)ᐳ"}}:::plan
    Constant67{{"Constant[67∈0] ➊<br />ᐸRecordCodec(compoundKey)ᐳ"}}:::plan
    Constant81{{"Constant[81∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant82{{"Constant[82∈0] ➊<br />ᐸsql.identifier(”unique_foreign_key”)ᐳ"}}:::plan
    Constant97{{"Constant[97∈0] ➊<br />ᐸ[ { codec: Codec(int4), fragment: { n: [Array], f: 0, c: 116ᐳ"}}:::plan
    Constant98{{"Constant[98∈0] ➊<br />ᐸsql.identifier(”compound_key”)ᐳ"}}:::plan
    Constant107{{"Constant[107∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant108{{"Constant[108∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant109{{"Constant[109∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”uniqueᐳ"}}:::plan
    Constant110{{"Constant[110∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”compouᐳ"}}:::plan
    Constant111{{"Constant[111∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”uniqueᐳ"}}:::plan
    Constant112{{"Constant[112∈0] ➊<br />ᐸ§{ reverse: false, orders: [ { codec: Codec(int4), fragment:ᐳ"}}:::plan
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸcompound_keyᐳ"]]:::plan
    Object12{{"Object[12∈1] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda48{{"Lambda[48∈1] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Lambda53{{"Lambda[53∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda58{{"Lambda[58∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda69{{"Lambda[69∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda74{{"Lambda[74∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda85{{"Lambda[85∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda90{{"Lambda[90∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda45{{"Lambda[45∈1] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Lambda101{{"Lambda[101∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Lambda106{{"Lambda[106∈1] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object12 & Connection13 & Lambda48 & Lambda53 & Lambda58 & Lambda69 & Lambda74 & Lambda48 & Lambda85 & Lambda90 & Lambda45 & Lambda48 & Lambda101 & Lambda106 --> PgSelect14
    Object52{{"Object[52∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda45 & Constant49 & Constant50 & Constant51 --> Object52
    Object68{{"Object[68∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda45 & Constant65 & Constant66 & Constant67 --> Object68
    Object84{{"Object[84∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda45 & Constant81 & Constant82 & Constant51 --> Object84
    Object100{{"Object[100∈1] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda45 & Constant97 & Constant98 & Constant67 --> Object100
    Access10{{"Access[10∈1] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈1] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2 --> Access10
    __Value2 --> Access11
    Constant107 --> Lambda45
    Constant108 --> Lambda48
    Object52 --> Lambda53
    Constant109 --> Lambda58
    Object68 --> Lambda69
    Constant110 --> Lambda74
    Object84 --> Lambda85
    Constant111 --> Lambda90
    Object100 --> Lambda101
    Constant112 --> Lambda106
    __Item15[/"__Item[15∈2]<br />ᐸ14ᐳ"\]:::itemplan
    PgSelect14 ==> __Item15
    PgSelectSingle16{{"PgSelectSingle[16∈2]<br />ᐸcompound_keyᐳ"}}:::plan
    __Item15 --> PgSelectSingle16
    PgClassExpression17{{"PgClassExpression[17∈3]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression17
    PgClassExpression18{{"PgClassExpression[18∈3]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression18
    PgSelectSingle24{{"PgSelectSingle[24∈3]<br />ᐸunique_foreign_keyᐳ"}}:::plan
    PgSelectSingle16 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈4]<br />ᐸ__unique_f...und_key_1”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    PgClassExpression26{{"PgClassExpression[26∈4]<br />ᐸ__unique_f...und_key_2”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression26
    PgSelectSingle32{{"PgSelectSingle[32∈4]<br />ᐸcompound_keyᐳ"}}:::plan
    PgSelectSingle24 --> PgSelectSingle32
    PgClassExpression33{{"PgClassExpression[33∈5]<br />ᐸ__compound...rson_id_1”ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression33
    PgClassExpression34{{"PgClassExpression[34∈5]<br />ᐸ__compound...rson_id_2”ᐳ"}}:::plan
    PgSelectSingle32 --> PgClassExpression34
    PgSelectSingle40{{"PgSelectSingle[40∈5]<br />ᐸunique_foreign_keyᐳ"}}:::plan
    PgSelectSingle32 --> PgSelectSingle40
    PgClassExpression41{{"PgClassExpression[41∈6]<br />ᐸ__unique_f...und_key_1”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression41
    PgClassExpression42{{"PgClassExpression[42∈6]<br />ᐸ__unique_f...und_key_2”ᐳ"}}:::plan
    PgSelectSingle40 --> PgClassExpression42

    %% define steps

    subgraph "Buckets for queries/v4/unique-foreign-keys"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Connection13,Constant49,Constant50,Constant51,Constant65,Constant66,Constant67,Constant81,Constant82,Constant97,Constant98,Constant107,Constant108,Constant109,Constant110,Constant111,Constant112 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 2, 13, 107, 108, 49, 50, 51, 109, 65, 66, 67, 110, 81, 82, 111, 97, 98, 112<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: <br />ᐳ: 10, 11, 45, 48, 58, 74, 90, 106, 12, 52, 53, 68, 69, 84, 85, 100, 101<br />2: PgSelect[14]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,Access10,Access11,Object12,PgSelect14,Lambda45,Lambda48,Object52,Lambda53,Lambda58,Object68,Lambda69,Lambda74,Object84,Lambda85,Lambda90,Object100,Lambda101,Lambda106 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ14ᐳ[15]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,PgSelectSingle16 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 16<br /><br />ROOT PgSelectSingle{2}ᐸcompound_keyᐳ[16]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression17,PgClassExpression18,PgSelectSingle24 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 24<br /><br />ROOT PgSelectSingle{3}ᐸunique_foreign_keyᐳ[24]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression25,PgClassExpression26,PgSelectSingle32 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 32<br /><br />ROOT PgSelectSingle{4}ᐸcompound_keyᐳ[32]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression33,PgClassExpression34,PgSelectSingle40 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 40<br /><br />ROOT PgSelectSingle{5}ᐸunique_foreign_keyᐳ[40]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression41,PgClassExpression42 bucket6
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    end
