%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸextractList_pgSelectApplyᐳ"}}:::plan
    Constant43{{"Constant[43∈0] ➊<br />ᐸ[ 'NATURAL' ]ᐳ"}}:::plan
    Constant43 --> Lambda14
    Lambda29{{"Lambda[29∈0] ➊<br />ᐸextractList_pgSelectApplyᐳ"}}:::plan
    Constant44{{"Constant[44∈0] ➊<br />ᐸ[ 'COL1_DESC' ]ᐳ"}}:::plan
    Constant44 --> Lambda29
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Connection28{{"Connection[28∈0] ➊<br />ᐸ26ᐳ"}}:::plan
    PgSelect15[["PgSelect[15∈1] ➊<br />ᐸtestviewᐳ"]]:::plan
    Object12 & Lambda14 & Connection13 --> PgSelect15
    PgSelectRows16[["PgSelectRows[16∈1] ➊"]]:::plan
    PgSelect15 --> PgSelectRows16
    Access19{{"Access[19∈1] ➊<br />ᐸ15.cursorDetailsᐳ"}}:::plan
    PgSelect15 --> Access19
    __Item17[/"__Item[17∈2]<br />ᐸ16ᐳ"\]:::itemplan
    PgSelectRows16 ==> __Item17
    PgSelectSingle18{{"PgSelectSingle[18∈2]<br />ᐸtestviewᐳ"}}:::plan
    __Item17 --> PgSelectSingle18
    PgCursor20{{"PgCursor[20∈3]"}}:::plan
    PgSelectSingle18 & Access19 --> PgCursor20
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__testview...estviewid”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression21
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__testview__.”col1”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__testview__.”col2”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression23
    PgSelect30[["PgSelect[30∈4] ➊<br />ᐸtestviewᐳ"]]:::plan
    Object12 & Lambda29 & Connection28 --> PgSelect30
    PgSelectRows31[["PgSelectRows[31∈4] ➊"]]:::plan
    PgSelect30 --> PgSelectRows31
    Access34{{"Access[34∈4] ➊<br />ᐸ30.cursorDetailsᐳ"}}:::plan
    PgSelect30 --> Access34
    __Item32[/"__Item[32∈5]<br />ᐸ31ᐳ"\]:::itemplan
    PgSelectRows31 ==> __Item32
    PgSelectSingle33{{"PgSelectSingle[33∈5]<br />ᐸtestviewᐳ"}}:::plan
    __Item32 --> PgSelectSingle33
    PgCursor35{{"PgCursor[35∈6]"}}:::plan
    PgSelectSingle33 & Access34 --> PgCursor35
    PgClassExpression36{{"PgClassExpression[36∈6]<br />ᐸ__testview...estviewid”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression36
    PgClassExpression37{{"PgClassExpression[37∈6]<br />ᐸ__testview__.”col1”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression37
    PgClassExpression38{{"PgClassExpression[38∈6]<br />ᐸ__testview__.”col2”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression38

    %% define steps

    subgraph "Buckets for queries/v4/view"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13,Lambda14,Connection28,Lambda29,Constant43,Constant44 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 13<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[15]<br />ᐳ: Access[19]<br />2: PgSelectRows[16]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect15,PgSelectRows16,Access19 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 19<br /><br />ROOT __Item{2}ᐸ16ᐳ[17]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item17,PgSelectSingle18 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 18, 19<br /><br />ROOT PgSelectSingle{2}ᐸtestviewᐳ[18]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor20,PgClassExpression21,PgClassExpression22,PgClassExpression23 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 12, 29, 28<br /><br />ROOT Connectionᐸ26ᐳ[28]<br />1: PgSelect[30]<br />ᐳ: Access[34]<br />2: PgSelectRows[31]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect30,PgSelectRows31,Access34 bucket4
    Bucket5("Bucket 5 (listItem)<br />Deps: 34<br /><br />ROOT __Item{5}ᐸ31ᐳ[32]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item32,PgSelectSingle33 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 33, 34<br /><br />ROOT PgSelectSingle{5}ᐸtestviewᐳ[33]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor35,PgClassExpression36,PgClassExpression37,PgClassExpression38 bucket6
    Bucket0 --> Bucket1 & Bucket4
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    end
