%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object17{{"Object[17∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈0]<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈0]<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    __Value2["__Value[2∈0]<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access15
    __Value2 --> Access16
    __Value4["__Value[4∈0]<br />ᐸrootValueᐳ"]:::plan
    Connection18{{"Connection[18∈0]<br />ᐸ14ᐳ"}}:::plan
    Connection40{{"Connection[40∈0]<br />ᐸ36ᐳ"}}:::plan
    PgSelect19[["PgSelect[19∈1]<br />ᐸtestviewᐳ"]]:::plan
    Object17 & Connection18 --> PgSelect19
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgSelect19 ==> __Item20
    PgSelectSingle21{{"PgSelectSingle[21∈2]<br />ᐸtestviewᐳ"}}:::plan
    __Item20 --> PgSelectSingle21
    PgCursor22{{"PgCursor[22∈3]"}}:::plan
    List24{{"List[24∈3]<br />ᐸ23ᐳ"}}:::plan
    List24 --> PgCursor22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸrow_number...tion by 1)ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression23
    PgClassExpression23 --> List24
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ__testview...estviewid”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression25
    PgClassExpression26{{"PgClassExpression[26∈3]<br />ᐸ__testview__.”col1”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression26
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__testview__.”col2”ᐳ"}}:::plan
    PgSelectSingle21 --> PgClassExpression27
    PgSelect41[["PgSelect[41∈4]<br />ᐸtestviewᐳ"]]:::plan
    Object17 & Connection40 --> PgSelect41
    __Item42[/"__Item[42∈5]<br />ᐸ41ᐳ"\]:::itemplan
    PgSelect41 ==> __Item42
    PgSelectSingle43{{"PgSelectSingle[43∈5]<br />ᐸtestviewᐳ"}}:::plan
    __Item42 --> PgSelectSingle43
    PgCursor44{{"PgCursor[44∈6]"}}:::plan
    List46{{"List[46∈6]<br />ᐸ45ᐳ"}}:::plan
    List46 --> PgCursor44
    PgClassExpression45{{"PgClassExpression[45∈6]<br />ᐸ__testview__.”col1”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression45
    PgClassExpression45 --> List46
    PgClassExpression47{{"PgClassExpression[47∈6]<br />ᐸ__testview...estviewid”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression47
    PgClassExpression49{{"PgClassExpression[49∈6]<br />ᐸ__testview__.”col2”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression49

    %% define steps

    subgraph "Buckets for queries/v4/view"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access15,Access16,Object17,Connection18,Connection40 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 17, 18<br /><br />ROOT Connectionᐸ14ᐳ[18]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect19 bucket1
    Bucket2("Bucket 2 (listItem)<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgSelectSingle21 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 21<br /><br />ROOT PgSelectSingle{2}ᐸtestviewᐳ[21]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor22,PgClassExpression23,List24,PgClassExpression25,PgClassExpression26,PgClassExpression27 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 17, 40<br /><br />ROOT Connectionᐸ36ᐳ[40]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect41 bucket4
    Bucket5("Bucket 5 (listItem)<br /><br />ROOT __Item{5}ᐸ41ᐳ[42]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item42,PgSelectSingle43 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 43<br /><br />ROOT PgSelectSingle{5}ᐸtestviewᐳ[43]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor44,PgClassExpression45,List46,PgClassExpression47,PgClassExpression49 bucket6
    Bucket0 --> Bucket1 & Bucket4
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    classDef unary fill:#fafffa,borderWidth:8px
    class Object17,Access15,Access16,__Value2,__Value4,Connection18,Connection40,PgSelect19,PgSelect41 unary
    end
