%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-relational/commentables"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: Access[8], Access[9], Object[10]<br />2: PgSelect[7]<br />3: PgSelectRows[12]<br />4: __ListTransform[11]"):::bucket
    Bucket1("Bucket 1 (subroutine)<br /><br />ROOT PgSelectSingle{1}ᐸrelational_commentablesᐳ[14]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 10<br /><br />ROOT __Item{2}ᐸ11ᐳ[15]"):::bucket
    Bucket3("Bucket 3 (polymorphic)<br />__typename: Lambda[21]<br />Deps: 10, 17, 21<br /><br />1: 149, 153, 157<br />2: 23, 35, 47<br />ᐳ: Access[150], Access[154], Access[158]<br />3: 32, 44, 56<br />ᐳ: 31, 34, 43, 46, 55, 58, 59, 87, 88, 89, 90, 118, 119, 147, 148, 151, 152, 155, 156, 159, 160<br />4: 65, 96, 125<br />ᐳ: 64, 67, 68, 77, 86, 95, 98, 99, 108, 117, 124, 127, 128, 137, 146"):::bucket
    Bucket4("Bucket 4 (polymorphicPartition)<br />|RelationalPost<br />Deps: 59, 68, 77, 86, 87, 88, 89<br />ᐳRelationalPost"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 90, 99, 108, 117, 118<br />ᐳRelationalChecklist"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 119, 128, 137, 146, 147, 148<br />ᐳRelationalChecklistItem"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5 & Bucket6

    %% plan dependencies
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸrelational_commentablesᐳ"]]:::plan
    Object10 --> PgSelect7
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    __ListTransform11[["__ListTransform[11∈0] ➊<br />ᐸeach:7ᐳ"]]:::plan
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelectRows12 --> __ListTransform11
    PgSelect7 --> PgSelectRows12
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item13[/"__Item[13∈1]<br />ᐸ12ᐳ"\]:::itemplan
    PgSelectRows12 -.-> __Item13
    PgSelectSingle14{{"PgSelectSingle[14∈1]<br />ᐸrelational_commentablesᐳ"}}:::plan
    __Item13 --> PgSelectSingle14
    __Item15[/"__Item[15∈2]<br />ᐸ11ᐳ"\]:::itemplan
    __ListTransform11 ==> __Item15
    PgSelectSingle16{{"PgSelectSingle[16∈2]<br />ᐸrelational_commentablesᐳ"}}:::plan
    __Item15 --> PgSelectSingle16
    PgClassExpression17{{"PgClassExpression[17∈2]<br />ᐸ__relation...les__.”id”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression17
    PgClassExpression19{{"PgClassExpression[19∈2]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression19
    Lambda21{{"Lambda[21∈2]<br />ᐸrelationalItemTypeNameFromTypeᐳ"}}:::plan
    PgClassExpression19 -->|rejectNull| Lambda21
    PgSelect23[["PgSelect[23∈3]^<br />ᐸrelational_postsᐳ"]]:::plan
    PgSelectInlineApply149["PgSelectInlineApply[149∈3] ➊<br />ᐳRelationalPost"]:::plan
    PgClassExpression17 -->|rejectNull| PgSelect23
    Object10 & PgSelectInlineApply149 --> PgSelect23
    PgSelect35[["PgSelect[35∈3]^<br />ᐸrelational_checklistsᐳ"]]:::plan
    PgSelectInlineApply153["PgSelectInlineApply[153∈3] ➊<br />ᐳRelationalChecklist"]:::plan
    PgClassExpression17 -->|rejectNull| PgSelect35
    Object10 & PgSelectInlineApply153 --> PgSelect35
    PgSelect47[["PgSelect[47∈3]^<br />ᐸrelational_checklist_itemsᐳ"]]:::plan
    PgSelectInlineApply157["PgSelectInlineApply[157∈3] ➊<br />ᐳRelationalChecklistItem"]:::plan
    PgClassExpression17 -->|rejectNull| PgSelect47
    Object10 & PgSelectInlineApply157 --> PgSelect47
    List151{{"List[151∈3]^<br />ᐸ150,34ᐳ"}}:::plan
    Access150{{"Access[150∈3]^<br />ᐸ23.m.joinDetailsFor60ᐳ"}}:::plan
    PgSelectSingle34{{"PgSelectSingle[34∈3]^<br />ᐸrelational_postsᐳ"}}:::plan
    Access150 & PgSelectSingle34 --> List151
    List155{{"List[155∈3]^<br />ᐸ154,46ᐳ"}}:::plan
    Access154{{"Access[154∈3]^<br />ᐸ35.m.joinDetailsFor91ᐳ"}}:::plan
    PgSelectSingle46{{"PgSelectSingle[46∈3]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    Access154 & PgSelectSingle46 --> List155
    List159{{"List[159∈3]^<br />ᐸ158,58ᐳ"}}:::plan
    Access158{{"Access[158∈3]^<br />ᐸ47.m.joinDetailsFor120ᐳ"}}:::plan
    PgSelectSingle58{{"PgSelectSingle[58∈3]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    Access158 & PgSelectSingle58 --> List159
    First31{{"First[31∈3]^"}}:::plan
    PgSelectRows32[["PgSelectRows[32∈3]^"]]:::plan
    PgSelectRows32 --> First31
    PgSelect23 --> PgSelectRows32
    First31 --> PgSelectSingle34
    First43{{"First[43∈3]^"}}:::plan
    PgSelectRows44[["PgSelectRows[44∈3]^"]]:::plan
    PgSelectRows44 --> First43
    PgSelect35 --> PgSelectRows44
    First43 --> PgSelectSingle46
    First55{{"First[55∈3]^"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈3]^"]]:::plan
    PgSelectRows56 --> First55
    PgSelect47 --> PgSelectRows56
    First55 --> PgSelectSingle58
    PgClassExpression59{{"PgClassExpression[59∈3]^<br />ᐸ__relation...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression59
    First64{{"First[64∈3]^"}}:::plan
    PgSelectRows65[["PgSelectRows[65∈3]^"]]:::plan
    PgSelectRows65 --> First64
    Lambda152{{"Lambda[152∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda152 --> PgSelectRows65
    PgSelectSingle67{{"PgSelectSingle[67∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First64 --> PgSelectSingle67
    PgClassExpression68{{"PgClassExpression[68∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle67 --> PgClassExpression68
    PgClassExpression77{{"PgClassExpression[77∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle67 --> PgClassExpression77
    PgClassExpression86{{"PgClassExpression[86∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle67 --> PgClassExpression86
    PgClassExpression87{{"PgClassExpression[87∈3]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression87
    PgClassExpression88{{"PgClassExpression[88∈3]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression88
    PgClassExpression89{{"PgClassExpression[89∈3]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression89
    PgClassExpression90{{"PgClassExpression[90∈3]^<br />ᐸ__relation...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression90
    First95{{"First[95∈3]^"}}:::plan
    PgSelectRows96[["PgSelectRows[96∈3]^"]]:::plan
    PgSelectRows96 --> First95
    Lambda156{{"Lambda[156∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda156 --> PgSelectRows96
    PgSelectSingle98{{"PgSelectSingle[98∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First95 --> PgSelectSingle98
    PgClassExpression99{{"PgClassExpression[99∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle98 --> PgClassExpression99
    PgClassExpression108{{"PgClassExpression[108∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle98 --> PgClassExpression108
    PgClassExpression117{{"PgClassExpression[117∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle98 --> PgClassExpression117
    PgClassExpression118{{"PgClassExpression[118∈3]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression118
    PgClassExpression119{{"PgClassExpression[119∈3]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression119
    First124{{"First[124∈3]^"}}:::plan
    PgSelectRows125[["PgSelectRows[125∈3]^"]]:::plan
    PgSelectRows125 --> First124
    Lambda160{{"Lambda[160∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda160 --> PgSelectRows125
    PgSelectSingle127{{"PgSelectSingle[127∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First124 --> PgSelectSingle127
    PgClassExpression128{{"PgClassExpression[128∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle127 --> PgClassExpression128
    PgClassExpression137{{"PgClassExpression[137∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle127 --> PgClassExpression137
    PgClassExpression146{{"PgClassExpression[146∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle127 --> PgClassExpression146
    PgClassExpression147{{"PgClassExpression[147∈3]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression147
    PgClassExpression148{{"PgClassExpression[148∈3]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression148
    PgSelect23 --> Access150
    List151 --> Lambda152
    PgSelect35 --> Access154
    List155 --> Lambda156
    PgSelect47 --> Access158
    List159 --> Lambda160

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,__ListTransform11,PgSelectRows12 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item13,PgSelectSingle14 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,PgSelectSingle16,PgClassExpression17,PgClassExpression19,Lambda21 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelect23,First31,PgSelectRows32,PgSelectSingle34,PgSelect35,First43,PgSelectRows44,PgSelectSingle46,PgSelect47,First55,PgSelectRows56,PgSelectSingle58,PgClassExpression59,First64,PgSelectRows65,PgSelectSingle67,PgClassExpression68,PgClassExpression77,PgClassExpression86,PgClassExpression87,PgClassExpression88,PgClassExpression89,PgClassExpression90,First95,PgSelectRows96,PgSelectSingle98,PgClassExpression99,PgClassExpression108,PgClassExpression117,PgClassExpression118,PgClassExpression119,First124,PgSelectRows125,PgSelectSingle127,PgClassExpression128,PgClassExpression137,PgClassExpression146,PgClassExpression147,PgClassExpression148,PgSelectInlineApply149,Access150,List151,Lambda152,PgSelectInlineApply153,Access154,List155,Lambda156,PgSelectInlineApply157,Access158,List159,Lambda160 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6 bucket6

