%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-relational/commentables"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: Access[8], Access[9], Object[10]<br />2: PgSelect[7]<br />3: PgSelectRows[12]<br />4: __ListTransform[11]"):::bucket
    Bucket1("Bucket 1 (subroutine)<br /><br />ROOT PgSelectSingle{1}ᐸrelational_commentablesᐳ[14]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 10<br /><br />ROOT __Item{2}ᐸ11ᐳ[15]"):::bucket
    Bucket3("Bucket 3 (polymorphic)<br />RelationalPost,RelationalChecklist,RelationalChecklistItem<br />Deps: 10, 19, 18<br />ᐳRelationalPost<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem<br /><br />1: 100, 104, 108<br />2: 20, 27, 32<br />ᐳ: Access[101], Access[105], Access[109]<br />3: 25, 30, 35<br />ᐳ: 24, 26, 29, 31, 34, 36, 37, 56, 57, 58, 59, 78, 79, 98, 99, 102, 103, 106, 107, 110, 111<br />4: 41, 63, 83<br />ᐳ: 40, 42, 43, 49, 55, 62, 64, 65, 71, 77, 82, 84, 85, 91, 97"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2
    Bucket2 --> Bucket3

    %% plan dependencies
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __ListTransform11[["__ListTransform[11∈0] ➊<br />ᐸeach:7ᐳ"]]:::plan
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸrelational_commentablesᐳ"]]:::plan
    PgSelectRows12 & PgSelect7 --> __ListTransform11
    Object10 --> PgSelect7
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    PgSelect7 --> PgSelectRows12
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item13[/"__Item[13∈1]<br />ᐸ12ᐳ"\]:::itemplan
    PgSelectRows12 -.-> __Item13
    PgSelectSingle14{{"PgSelectSingle[14∈1]<br />ᐸrelational_commentablesᐳ"}}:::plan
    __Item13 --> PgSelectSingle14
    PgPolymorphic18{{"PgPolymorphic[18∈2]"}}:::plan
    PgSelectSingle16{{"PgSelectSingle[16∈2]<br />ᐸrelational_commentablesᐳ"}}:::plan
    PgClassExpression17{{"PgClassExpression[17∈2]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle16 & PgClassExpression17 --> PgPolymorphic18
    __Item15[/"__Item[15∈2]<br />ᐸ11ᐳ"\]:::itemplan
    __ListTransform11 ==> __Item15
    __Item15 --> PgSelectSingle16
    PgSelectSingle16 --> PgClassExpression17
    PgClassExpression19{{"PgClassExpression[19∈2]<br />ᐸ__relation...les__.”id”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression19
    PgSelect20[["PgSelect[20∈3]^<br />ᐸrelational_postsᐳ"]]:::plan
    PgSelectInlineApply100["PgSelectInlineApply[100∈3] ➊<br />ᐳRelationalPost"]:::plan
    Object10 & PgClassExpression19 & PgSelectInlineApply100 --> PgSelect20
    PgSelect27[["PgSelect[27∈3]^<br />ᐸrelational_checklistsᐳ"]]:::plan
    PgSelectInlineApply104["PgSelectInlineApply[104∈3] ➊<br />ᐳRelationalChecklist"]:::plan
    Object10 & PgClassExpression19 & PgSelectInlineApply104 --> PgSelect27
    PgSelect32[["PgSelect[32∈3]^<br />ᐸrelational_checklist_itemsᐳ"]]:::plan
    PgSelectInlineApply108["PgSelectInlineApply[108∈3] ➊<br />ᐳRelationalChecklistItem"]:::plan
    Object10 & PgClassExpression19 & PgSelectInlineApply108 --> PgSelect32
    List102{{"List[102∈3]^<br />ᐸ101,26ᐳ"}}:::plan
    Access101{{"Access[101∈3]^<br />ᐸ20.m.joinDetailsFor38ᐳ"}}:::plan
    PgSelectSingle26{{"PgSelectSingle[26∈3]^<br />ᐸrelational_postsᐳ"}}:::plan
    Access101 & PgSelectSingle26 --> List102
    List106{{"List[106∈3]^<br />ᐸ105,31ᐳ"}}:::plan
    Access105{{"Access[105∈3]^<br />ᐸ27.m.joinDetailsFor60ᐳ"}}:::plan
    PgSelectSingle31{{"PgSelectSingle[31∈3]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    Access105 & PgSelectSingle31 --> List106
    List110{{"List[110∈3]^<br />ᐸ109,36ᐳ"}}:::plan
    Access109{{"Access[109∈3]^<br />ᐸ32.m.joinDetailsFor80ᐳ"}}:::plan
    PgSelectSingle36{{"PgSelectSingle[36∈3]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    Access109 & PgSelectSingle36 --> List110
    First24{{"First[24∈3]^"}}:::plan
    PgSelectRows25[["PgSelectRows[25∈3]^"]]:::plan
    PgSelectRows25 --> First24
    PgSelect20 --> PgSelectRows25
    First24 --> PgSelectSingle26
    First29{{"First[29∈3]^"}}:::plan
    PgSelectRows30[["PgSelectRows[30∈3]^"]]:::plan
    PgSelectRows30 --> First29
    PgSelect27 --> PgSelectRows30
    First29 --> PgSelectSingle31
    First34{{"First[34∈3]^"}}:::plan
    PgSelectRows35[["PgSelectRows[35∈3]^"]]:::plan
    PgSelectRows35 --> First34
    PgSelect32 --> PgSelectRows35
    First34 --> PgSelectSingle36
    PgClassExpression37{{"PgClassExpression[37∈3]^<br />ᐸ__relation...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression37
    First40{{"First[40∈3]^"}}:::plan
    PgSelectRows41[["PgSelectRows[41∈3]^"]]:::plan
    PgSelectRows41 --> First40
    Lambda103{{"Lambda[103∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda103 --> PgSelectRows41
    PgSelectSingle42{{"PgSelectSingle[42∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First40 --> PgSelectSingle42
    PgClassExpression43{{"PgClassExpression[43∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression43
    PgClassExpression49{{"PgClassExpression[49∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression49
    PgClassExpression55{{"PgClassExpression[55∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression55
    PgClassExpression56{{"PgClassExpression[56∈3]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression56
    PgClassExpression57{{"PgClassExpression[57∈3]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression57
    PgClassExpression58{{"PgClassExpression[58∈3]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgSelectSingle26 --> PgClassExpression58
    PgClassExpression59{{"PgClassExpression[59∈3]^<br />ᐸ__relation...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression59
    First62{{"First[62∈3]^"}}:::plan
    PgSelectRows63[["PgSelectRows[63∈3]^"]]:::plan
    PgSelectRows63 --> First62
    Lambda107{{"Lambda[107∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda107 --> PgSelectRows63
    PgSelectSingle64{{"PgSelectSingle[64∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First62 --> PgSelectSingle64
    PgClassExpression65{{"PgClassExpression[65∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle64 --> PgClassExpression65
    PgClassExpression71{{"PgClassExpression[71∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle64 --> PgClassExpression71
    PgClassExpression77{{"PgClassExpression[77∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle64 --> PgClassExpression77
    PgClassExpression78{{"PgClassExpression[78∈3]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression78
    PgClassExpression79{{"PgClassExpression[79∈3]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression79
    First82{{"First[82∈3]^"}}:::plan
    PgSelectRows83[["PgSelectRows[83∈3]^"]]:::plan
    PgSelectRows83 --> First82
    Lambda111{{"Lambda[111∈3]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda111 --> PgSelectRows83
    PgSelectSingle84{{"PgSelectSingle[84∈3]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First82 --> PgSelectSingle84
    PgClassExpression85{{"PgClassExpression[85∈3]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle84 --> PgClassExpression85
    PgClassExpression91{{"PgClassExpression[91∈3]^<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle84 --> PgClassExpression91
    PgClassExpression97{{"PgClassExpression[97∈3]^<br />ᐸ__relation...”position”ᐳ"}}:::plan
    PgSelectSingle84 --> PgClassExpression97
    PgClassExpression98{{"PgClassExpression[98∈3]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression98
    PgClassExpression99{{"PgClassExpression[99∈3]^<br />ᐸ__relation...s__.”note”ᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression99
    PgSelect20 --> Access101
    List102 --> Lambda103
    PgSelect27 --> Access105
    List106 --> Lambda107
    PgSelect32 --> Access109
    List110 --> Lambda111

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,__ListTransform11,PgSelectRows12 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item13,PgSelectSingle14 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,PgSelectSingle16,PgClassExpression17,PgPolymorphic18,PgClassExpression19 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelect20,First24,PgSelectRows25,PgSelectSingle26,PgSelect27,First29,PgSelectRows30,PgSelectSingle31,PgSelect32,First34,PgSelectRows35,PgSelectSingle36,PgClassExpression37,First40,PgSelectRows41,PgSelectSingle42,PgClassExpression43,PgClassExpression49,PgClassExpression55,PgClassExpression56,PgClassExpression57,PgClassExpression58,PgClassExpression59,First62,PgSelectRows63,PgSelectSingle64,PgClassExpression65,PgClassExpression71,PgClassExpression77,PgClassExpression78,PgClassExpression79,First82,PgSelectRows83,PgSelectSingle84,PgClassExpression85,PgClassExpression91,PgClassExpression97,PgClassExpression98,PgClassExpression99,PgSelectInlineApply100,Access101,List102,Lambda103,PgSelectInlineApply104,Access105,List106,Lambda107,PgSelectInlineApply108,Access109,List110,Lambda111 bucket3

