%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-relational/nested-simplified"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[243]<br />ᐳ: 8, 9, 251, 10<br />2: PgSelectInlineApply[247]<br />3: PgSelect[7]<br />ᐳ: Access[248]<br />4: PgSelectRows[11]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 248, 10<br /><br />ROOT __Item{1}ᐸ11ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 13, 248, 12, 10<br /><br />ROOT PgSelectSingle{1}ᐸpeopleᐳ[13]<br />1: <br />ᐳ: 14, 249, 250<br />2: PgSelectRows[22]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 10, 250<br /><br />ROOT __Item{3}ᐸ22ᐳ[23]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Lambda[28]<br />Deps: 28, 10, 25, 250, 24, 27, 71"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 25, 250, 24, 27, 71<br />ᐳRelationalTopic<br /><br />1: PgSelect[30]<br />2: PgSelectRows[35]<br />ᐳ: First[34], PgSelectSingle[36]"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 25, 250, 24, 27, 71<br />ᐳRelationalPost<br /><br />1: PgSelect[38]<br />2: PgSelectRows[43]<br />ᐳ: First[42], PgSelectSingle[44]"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 25, 250, 24, 27, 71<br />ᐳRelationalDivider<br /><br />1: PgSelect[46]<br />2: PgSelectRows[51]<br />ᐳ: First[50], PgSelectSingle[52]"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 25, 250, 24, 27, 71<br />ᐳRelationalChecklist<br /><br />1: PgSelect[54]<br />2: PgSelectRows[59]<br />ᐳ: First[58], PgSelectSingle[60]"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 25, 250, 24, 27, 71<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[62]<br />2: PgSelectRows[67]<br />ᐳ: First[66], PgSelectSingle[68]"):::bucket
    Bucket10("Bucket 10 (combined)<br />Deps: 250, 24, 10<br /><br />1: <br />ᐳ: Access[244], List[245], Lambda[246]<br />2: PgSelectRows[78]<br />ᐳ: 77, 79, 124, 126, 127, 170"):::bucket
    Bucket11("Bucket 11 (polymorphic)<br />__typename: Lambda[127]<br />Deps: 127, 10, 124, 126, 170"):::bucket
    Bucket12("Bucket 12 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 124, 126, 170<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[129]<br />2: PgSelectRows[134]<br />ᐳ: First[133], PgSelectSingle[135]"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 124, 126, 170<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[137]<br />2: PgSelectRows[142]<br />ᐳ: First[141], PgSelectSingle[143]"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 124, 126, 170<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[145]<br />2: PgSelectRows[150]<br />ᐳ: First[149], PgSelectSingle[151]"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 124, 126, 170<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[153]<br />2: PgSelectRows[158]<br />ᐳ: First[157], PgSelectSingle[159]"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 124, 126, 170<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[161]<br />2: PgSelectRows[166]<br />ᐳ: First[165], PgSelectSingle[167]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6 & Bucket7 & Bucket8 & Bucket9
    Bucket5 --> Bucket10
    Bucket6 --> Bucket10
    Bucket7 --> Bucket10
    Bucket8 --> Bucket10
    Bucket9 --> Bucket10
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12 & Bucket13 & Bucket14 & Bucket15 & Bucket16

    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸpeopleᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant251{{"Constant[251∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    PgSelectInlineApply247["PgSelectInlineApply[247∈0] ➊"]:::plan
    Object10 & Constant251 & PgSelectInlineApply247 --> PgSelect7
    PgSelectInlineApply243["PgSelectInlineApply[243∈0] ➊"]:::plan
    PgSelectInlineApply243 --> PgSelectInlineApply247
    Constant251 -- 2 --> PgSelectInlineApply247
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    PgSelectRows11[["PgSelectRows[11∈0] ➊"]]:::plan
    PgSelect7 --> PgSelectRows11
    Access248{{"Access[248∈0] ➊<br />ᐸ7.m.subqueryDetailsFor18ᐳ"}}:::plan
    PgSelect7 --> Access248
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item12[/"__Item[12∈1]<br />ᐸ11ᐳ"\]:::itemplan
    PgSelectRows11 ==> __Item12
    PgSelectSingle13{{"PgSelectSingle[13∈1]<br />ᐸpeopleᐳ"}}:::plan
    __Item12 --> PgSelectSingle13
    List249{{"List[249∈2]<br />ᐸ248,12ᐳ"}}:::plan
    Access248 & __Item12 --> List249
    PgClassExpression14{{"PgClassExpression[14∈2]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle13 --> PgClassExpression14
    PgSelectRows22[["PgSelectRows[22∈2]"]]:::plan
    Lambda250{{"Lambda[250∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda250 --> PgSelectRows22
    List249 --> Lambda250
    __Item23[/"__Item[23∈3]<br />ᐸ22ᐳ"\]:::itemplan
    PgSelectRows22 ==> __Item23
    PgSelectSingle24{{"PgSelectSingle[24∈3]<br />ᐸrelational_itemsᐳ"}}:::plan
    __Item23 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression27
    Lambda28{{"Lambda[28∈3]<br />ᐸrelationalItemTypeNameFromTypeᐳ"}}:::plan
    PgClassExpression27 --> Lambda28
    PgClassExpression71{{"PgClassExpression[71∈3]<br />ᐸ__relation...__.”type2”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression71
    PgSelect30[["PgSelect[30∈5]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic"]]:::plan
    Object10 & PgClassExpression25 --> PgSelect30
    First34{{"First[34∈5]^"}}:::plan
    PgSelectRows35[["PgSelectRows[35∈5]^"]]:::plan
    PgSelectRows35 --> First34
    PgSelect30 --> PgSelectRows35
    PgSelectSingle36{{"PgSelectSingle[36∈5]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First34 --> PgSelectSingle36
    PgSelect38[["PgSelect[38∈6]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost"]]:::plan
    Object10 & PgClassExpression25 --> PgSelect38
    First42{{"First[42∈6]^"}}:::plan
    PgSelectRows43[["PgSelectRows[43∈6]^"]]:::plan
    PgSelectRows43 --> First42
    PgSelect38 --> PgSelectRows43
    PgSelectSingle44{{"PgSelectSingle[44∈6]^<br />ᐸrelational_postsᐳ"}}:::plan
    First42 --> PgSelectSingle44
    PgSelect46[["PgSelect[46∈7]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider"]]:::plan
    Object10 & PgClassExpression25 --> PgSelect46
    First50{{"First[50∈7]^"}}:::plan
    PgSelectRows51[["PgSelectRows[51∈7]^"]]:::plan
    PgSelectRows51 --> First50
    PgSelect46 --> PgSelectRows51
    PgSelectSingle52{{"PgSelectSingle[52∈7]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First50 --> PgSelectSingle52
    PgSelect54[["PgSelect[54∈8]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist"]]:::plan
    Object10 & PgClassExpression25 --> PgSelect54
    First58{{"First[58∈8]^"}}:::plan
    PgSelectRows59[["PgSelectRows[59∈8]^"]]:::plan
    PgSelectRows59 --> First58
    PgSelect54 --> PgSelectRows59
    PgSelectSingle60{{"PgSelectSingle[60∈8]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First58 --> PgSelectSingle60
    PgSelect62[["PgSelect[62∈9]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem"]]:::plan
    Object10 & PgClassExpression25 --> PgSelect62
    First66{{"First[66∈9]^"}}:::plan
    PgSelectRows67[["PgSelectRows[67∈9]^"]]:::plan
    PgSelectRows67 --> First66
    PgSelect62 --> PgSelectRows67
    PgSelectSingle68{{"PgSelectSingle[68∈9]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First66 --> PgSelectSingle68
    List245{{"List[245∈10]<br />ᐸ244,24ᐳ"}}:::plan
    Access244{{"Access[244∈10]<br />ᐸ250.m.joinDetailsFor73ᐳ"}}:::plan
    Access244 & PgSelectSingle24 --> List245
    First77{{"First[77∈10]"}}:::plan
    PgSelectRows78[["PgSelectRows[78∈10]"]]:::plan
    PgSelectRows78 --> First77
    Lambda246{{"Lambda[246∈10]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda246 --> PgSelectRows78
    PgSelectSingle79{{"PgSelectSingle[79∈10]<br />ᐸrelational_itemsᐳ"}}:::plan
    First77 --> PgSelectSingle79
    PgClassExpression124{{"PgClassExpression[124∈10]<br />ᐸ__relation...ems__.”id”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle79 --> PgClassExpression124
    PgClassExpression126{{"PgClassExpression[126∈10]<br />ᐸ__relation...s__.”type”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle79 --> PgClassExpression126
    Lambda127{{"Lambda[127∈10]^<br />ᐸrelationalItemTypeNameFromTypeᐳ"}}:::plan
    PgClassExpression126 --> Lambda127
    PgClassExpression170{{"PgClassExpression[170∈10]<br />ᐸ__relation...__.”type2”ᐳ<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}}:::plan
    PgSelectSingle79 --> PgClassExpression170
    Lambda250 --> Access244
    List245 --> Lambda246
    PgSelect129[["PgSelect[129∈12]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic"]]:::plan
    Object10 & PgClassExpression124 --> PgSelect129
    First133{{"First[133∈12]^"}}:::plan
    PgSelectRows134[["PgSelectRows[134∈12]^"]]:::plan
    PgSelectRows134 --> First133
    PgSelect129 --> PgSelectRows134
    PgSelectSingle135{{"PgSelectSingle[135∈12]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First133 --> PgSelectSingle135
    PgSelect137[["PgSelect[137∈13]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost"]]:::plan
    Object10 & PgClassExpression124 --> PgSelect137
    First141{{"First[141∈13]^"}}:::plan
    PgSelectRows142[["PgSelectRows[142∈13]^"]]:::plan
    PgSelectRows142 --> First141
    PgSelect137 --> PgSelectRows142
    PgSelectSingle143{{"PgSelectSingle[143∈13]^<br />ᐸrelational_postsᐳ"}}:::plan
    First141 --> PgSelectSingle143
    PgSelect145[["PgSelect[145∈14]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider"]]:::plan
    Object10 & PgClassExpression124 --> PgSelect145
    First149{{"First[149∈14]^"}}:::plan
    PgSelectRows150[["PgSelectRows[150∈14]^"]]:::plan
    PgSelectRows150 --> First149
    PgSelect145 --> PgSelectRows150
    PgSelectSingle151{{"PgSelectSingle[151∈14]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First149 --> PgSelectSingle151
    PgSelect153[["PgSelect[153∈15]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist"]]:::plan
    Object10 & PgClassExpression124 --> PgSelect153
    First157{{"First[157∈15]^"}}:::plan
    PgSelectRows158[["PgSelectRows[158∈15]^"]]:::plan
    PgSelectRows158 --> First157
    PgSelect153 --> PgSelectRows158
    PgSelectSingle159{{"PgSelectSingle[159∈15]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First157 --> PgSelectSingle159
    PgSelect161[["PgSelect[161∈16]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem"]]:::plan
    Object10 & PgClassExpression124 --> PgSelect161
    First165{{"First[165∈16]^"}}:::plan
    PgSelectRows166[["PgSelectRows[166∈16]^"]]:::plan
    PgSelectRows166 --> First165
    PgSelect161 --> PgSelectRows166
    PgSelectSingle167{{"PgSelectSingle[167∈16]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First165 --> PgSelectSingle167

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,PgSelectRows11,PgSelectInlineApply243,PgSelectInlineApply247,Access248,Constant251 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item12,PgSelectSingle13 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression14,PgSelectRows22,List249,Lambda250 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item23,PgSelectSingle24,PgClassExpression25,PgClassExpression27,Lambda28,PgClassExpression71 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect30,First34,PgSelectRows35,PgSelectSingle36 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect38,First42,PgSelectRows43,PgSelectSingle44 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect46,First50,PgSelectRows51,PgSelectSingle52 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect54,First58,PgSelectRows59,PgSelectSingle60 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelect62,First66,PgSelectRows67,PgSelectSingle68 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,First77,PgSelectRows78,PgSelectSingle79,PgClassExpression124,PgClassExpression126,Lambda127,PgClassExpression170,Access244,List245,Lambda246 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgSelect129,First133,PgSelectRows134,PgSelectSingle135 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect137,First141,PgSelectRows142,PgSelectSingle143 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect145,First149,PgSelectRows150,PgSelectSingle151 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect153,First157,PgSelectRows158,PgSelectSingle159 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect161,First165,PgSelectRows166,PgSelectSingle167 bucket16

