%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant58{{"Constant[58∈0] ➊<br />ᐸ'f1700000-0000-0000-0000-000000000f17'ᐳ"}}:::plan
    Lambda47{{"Lambda[47∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Object10 & Constant58 & Lambda47 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0] ➊"}}:::plan
    PgSelect7 --> First11
    PgSelectSingle12{{"PgSelectSingle[12∈0] ➊<br />ᐸforumsᐳ"}}:::plan
    First11 --> PgSelectSingle12
    Constant59{{"Constant[59∈0] ➊<br />ᐸ§{ cursorLower: null, cursorUpper: null, first: null, last: ᐳ"}}:::plan
    Constant59 --> Lambda47
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant29{{"Constant[29∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸforums_random_userᐳ"]]:::plan
    PgClassExpression13{{"PgClassExpression[13∈1] ➊<br />ᐸ__forums__ᐳ"}}:::plan
    Object10 & PgClassExpression13 & Lambda47 --> PgSelect14
    PgSelectSingle12 --> PgClassExpression13
    First18{{"First[18∈1] ➊"}}:::plan
    PgSelect14 --> First18
    PgSelectSingle19{{"PgSelectSingle[19∈1] ➊<br />ᐸusersᐳ"}}:::plan
    First18 --> PgSelectSingle19
    PgSelect23[["PgSelect[23∈2] ➊<br />ᐸusers_most_recent_forumᐳ"]]:::plan
    PgClassExpression22{{"PgClassExpression[22∈2] ➊<br />ᐸ__forums_random_user__ᐳ"}}:::plan
    Object10 & PgClassExpression22 & Constant29 & Lambda47 & Lambda47 --> PgSelect23
    PgClassExpression20{{"PgClassExpression[20∈2] ➊<br />ᐸ__forums_r...”username”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgClassExpression21{{"PgClassExpression[21∈2] ➊<br />ᐸ__forums_r...vatar_url”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression21
    PgSelectSingle19 --> PgClassExpression22
    First27{{"First[27∈2] ➊"}}:::plan
    PgSelect23 --> First27
    PgSelectSingle28{{"PgSelectSingle[28∈2] ➊<br />ᐸusers_most_recent_forumᐳ"}}:::plan
    First27 --> PgSelectSingle28
    PgSelect39[["PgSelect[39∈3] ➊<br />ᐸforums_featured_messagesᐳ"]]:::plan
    PgClassExpression30{{"PgClassExpression[30∈3] ➊<br />ᐸ__users_mo...nt_forum__ᐳ"}}:::plan
    Object10 & PgClassExpression30 & Lambda47 --> PgSelect39
    PgSelectSingle28 --> PgClassExpression30
    PgSelectSingle36{{"PgSelectSingle[36∈3] ➊<br />ᐸforums_unique_author_countᐳ"}}:::plan
    PgSelectSingle28 --> PgSelectSingle36
    PgClassExpression37{{"PgClassExpression[37∈3] ➊<br />ᐸ__forums_u..._count__.vᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression37
    __Item41[/"__Item[41∈4]<br />ᐸ39ᐳ"\]:::itemplan
    PgSelect39 ==> __Item41
    PgSelectSingle42{{"PgSelectSingle[42∈4]<br />ᐸforums_featured_messagesᐳ"}}:::plan
    __Item41 --> PgSelectSingle42
    PgClassExpression43{{"PgClassExpression[43∈5]<br />ᐸ__forums_f...s__.”body”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression43

    %% define steps

    subgraph "Buckets for queries/functions/computed-column-combined"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 29, 58, 59, 10, 47<br />2: PgSelect[7]<br />ᐳ: First[11], PgSelectSingle[12]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectSingle12,Constant29,Lambda47,Constant58,Constant59 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 10, 47, 29<br /><br />ROOT PgSelectSingleᐸforumsᐳ[12]<br />1: <br />ᐳ: PgClassExpression[13]<br />2: PgSelect[14]<br />ᐳ: First[18], PgSelectSingle[19]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression13,PgSelect14,First18,PgSelectSingle19 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 19, 10, 29, 47<br /><br />ROOT PgSelectSingle{1}ᐸusersᐳ[19]<br />1: <br />ᐳ: 20, 21, 22<br />2: PgSelect[23]<br />ᐳ: First[27], PgSelectSingle[28]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression20,PgClassExpression21,PgClassExpression22,PgSelect23,First27,PgSelectSingle28 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 28, 10, 47<br /><br />ROOT PgSelectSingle{2}ᐸusers_most_recent_forumᐳ[28]<br />1: <br />ᐳ: 30, 36, 37<br />2: PgSelect[39]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression30,PgSelectSingle36,PgClassExpression37,PgSelect39 bucket3
    Bucket4("Bucket 4 (listItem)<br /><br />ROOT __Item{4}ᐸ39ᐳ[41]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item41,PgSelectSingle42 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 42<br /><br />ROOT PgSelectSingle{4}ᐸforums_featured_messagesᐳ[42]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression43 bucket5
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    end
