%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object10{{"Object[10∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access8{{"Access[8∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect7[["PgSelect[7∈0]<br />ᐸrandom_userᐳ"]]:::plan
    Object10 --> PgSelect7
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value3 --> Access8
    __Value3 --> Access9
    First11{{"First[11∈0]"}}:::plan
    PgSelect7 --> First11
    PgSelectSingle12{{"PgSelectSingle[12∈0]<br />ᐸusersᐳ"}}:::plan
    First11 --> PgSelectSingle12
    __Value0["__Value[0∈0]"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    PgClassExpression13{{"PgClassExpression[13∈1]<br />ᐸ__random_u...”username”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression13
    PgClassExpression14{{"PgClassExpression[14∈1]<br />ᐸ__random_u...vatar_url”ᐳ"}}:::plan
    PgSelectSingle12 --> PgClassExpression14

    %% define steps

    subgraph "Buckets for queries/functions/custom-query-user"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: Access[8], Access[9], Object[10]<br />2: PgSelect[7]<br />ᐳ: First[11], PgSelectSingle[12]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,PgSelect7,Access8,Access9,Object10,First11,PgSelectSingle12 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12<br /><br />ROOT PgSelectSingleᐸusersᐳ[12]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression13,PgClassExpression14 bucket1
    Bucket0 --> Bucket1
    end
