%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/interfaces-single-table/nested"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[186]<br />ᐳ: 6, 8, 9, 10<br />2: PgSelectInlineApply[190]<br />3: PgSelect[7]<br />ᐳ: Access[191]<br />4: PgSelectRows[11]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 191<br /><br />ROOT __Item{1}ᐸ11ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 13, 191, 12<br /><br />ROOT PgSelectSingle{1}ᐸpeopleᐳ[13]<br />1: <br />ᐳ: 14, 192, 193<br />2: PgSelectRows[20]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 193<br /><br />ROOT __Item{3}ᐸ20ᐳ[21]<br />1: <br />ᐳ: 22, 187, 23, 25, 26, 27, 42, 188, 189<br />2: PgSelectRows[37]<br />ᐳ: 36, 39, 108, 109, 113"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Lambda[26]<br />Deps: 26, 109, 22, 23, 25, 42, 39, 27, 108, 113"):::bucket
    Bucket5("Bucket 5 (polymorphic)<br />__typename: Lambda[109]<br />Deps: 109, 39, 27, 108, 113"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5

    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸpeopleᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    PgSelectInlineApply190["PgSelectInlineApply[190∈0] ➊"]:::plan
    Object10 & PgSelectInlineApply190 --> PgSelect7
    PgSelectInlineApply186["PgSelectInlineApply[186∈0] ➊"]:::plan
    PgSelectInlineApply186 --> PgSelectInlineApply190
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    PgSelectRows11[["PgSelectRows[11∈0] ➊"]]:::plan
    PgSelect7 --> PgSelectRows11
    Access191{{"Access[191∈0] ➊<br />ᐸ7.m.subqueryDetailsFor16ᐳ"}}:::plan
    PgSelect7 --> Access191
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item12[/"__Item[12∈1]<br />ᐸ11ᐳ"\]:::itemplan
    PgSelectRows11 ==> __Item12
    PgSelectSingle13{{"PgSelectSingle[13∈1]<br />ᐸpeopleᐳ"}}:::plan
    __Item12 --> PgSelectSingle13
    List192{{"List[192∈2]<br />ᐸ191,12ᐳ"}}:::plan
    Access191 & __Item12 --> List192
    PgClassExpression14{{"PgClassExpression[14∈2]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle13 --> PgClassExpression14
    PgSelectRows20[["PgSelectRows[20∈2]"]]:::plan
    Lambda193{{"Lambda[193∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda193 --> PgSelectRows20
    List192 --> Lambda193
    List188{{"List[188∈3]<br />ᐸ187,22ᐳ"}}:::plan
    Access187{{"Access[187∈3]<br />ᐸ193.m.joinDetailsFor28ᐳ"}}:::plan
    PgSelectSingle22{{"PgSelectSingle[22∈3]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Access187 & PgSelectSingle22 --> List188
    __Item21[/"__Item[21∈3]<br />ᐸ20ᐳ"\]:::itemplan
    PgSelectRows20 ==> __Item21
    __Item21 --> PgSelectSingle22
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__single_t...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression23
    PgClassExpression25{{"PgClassExpression[25∈3]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression25
    Lambda26{{"Lambda[26∈3]"}}:::plan
    PgClassExpression25 --> Lambda26
    PgClassExpression27{{"PgClassExpression[27∈3]<br />ᐸ__single_t...parent_id”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression27
    First36{{"First[36∈3]"}}:::plan
    PgSelectRows37[["PgSelectRows[37∈3]"]]:::plan
    PgSelectRows37 --> First36
    Lambda189{{"Lambda[189∈3]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda189 --> PgSelectRows37
    PgSelectSingle39{{"PgSelectSingle[39∈3]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    First36 --> PgSelectSingle39
    PgClassExpression42{{"PgClassExpression[42∈3]<br />ᐸ__single_t...__.”type2”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression42
    PgClassExpression108{{"PgClassExpression[108∈3]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression108
    Lambda109{{"Lambda[109∈3]"}}:::plan
    PgClassExpression108 --> Lambda109
    PgClassExpression113{{"PgClassExpression[113∈3]<br />ᐸ__single_t...__.”type2”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression113
    Lambda193 --> Access187
    List188 --> Lambda189

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,PgSelectRows11,PgSelectInlineApply186,PgSelectInlineApply190,Access191 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item12,PgSelectSingle13 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression14,PgSelectRows20,List192,Lambda193 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item21,PgSelectSingle22,PgClassExpression23,PgClassExpression25,Lambda26,PgClassExpression27,First36,PgSelectRows37,PgSelectSingle39,PgClassExpression42,PgClassExpression108,Lambda109,PgClassExpression113,Access187,List188,Lambda189 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5

