%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸsingle_table_itemsᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant231{{"Constant[231∈0] ➊<br />ᐸ15ᐳ"}}:::plan
    Object10 & Constant231 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSingleTablePolymorphic16["PgSingleTablePolymorphic[16∈0] ➊"]:::plan
    Lambda15{{"Lambda[15∈0] ➊"}}:::plan
    PgSelectSingle13{{"PgSelectSingle[13∈0] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda15 & PgSelectSingle13 --> PgSingleTablePolymorphic16
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0] ➊"}}:::plan
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelectRows12 --> First11
    PgSelect7 --> PgSelectRows12
    First11 --> PgSelectSingle13
    PgClassExpression14{{"PgClassExpression[14∈0] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle13 --> PgClassExpression14
    PgClassExpression14 --> Lambda15
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect18[["PgSelect[18∈1] ➊<br />ᐸsingle_table_itemsᐳ<br />ᐳSingleTableTopic<br />ᐳSingleTablePost<br />ᐳSingleTableDivider<br />ᐳSingleTableChecklist<br />ᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression17{{"PgClassExpression[17∈1] ➊<br />ᐸ__single_t...parent_id”ᐳ<br />ᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression17 --> PgSelect18
    PgSingleTablePolymorphic27["PgSingleTablePolymorphic[27∈1] ➊<br />ᐳSingleTableTopic"]:::plan
    Lambda26{{"Lambda[26∈1] ➊"}}:::plan
    PgSelectSingle24{{"PgSelectSingle[24∈1] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda26 & PgSelectSingle24 --> PgSingleTablePolymorphic27
    PgSingleTablePolymorphic70["PgSingleTablePolymorphic[70∈1] ➊<br />ᐳSingleTablePost"]:::plan
    Lambda69{{"Lambda[69∈1] ➊"}}:::plan
    PgSelectSingle67{{"PgSelectSingle[67∈1] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda69 & PgSelectSingle67 --> PgSingleTablePolymorphic70
    PgSingleTablePolymorphic112["PgSingleTablePolymorphic[112∈1] ➊<br />ᐳSingleTableDivider"]:::plan
    Lambda111{{"Lambda[111∈1] ➊"}}:::plan
    PgSelectSingle109{{"PgSelectSingle[109∈1] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda111 & PgSelectSingle109 --> PgSingleTablePolymorphic112
    PgSingleTablePolymorphic154["PgSingleTablePolymorphic[154∈1] ➊<br />ᐳSingleTableChecklist"]:::plan
    Lambda153{{"Lambda[153∈1] ➊"}}:::plan
    PgSelectSingle151{{"PgSelectSingle[151∈1] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda153 & PgSelectSingle151 --> PgSingleTablePolymorphic154
    PgSingleTablePolymorphic196["PgSingleTablePolymorphic[196∈1] ➊<br />ᐳSingleTableChecklistItem"]:::plan
    Lambda195{{"Lambda[195∈1] ➊"}}:::plan
    PgSelectSingle193{{"PgSelectSingle[193∈1] ➊<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Lambda195 & PgSelectSingle193 --> PgSingleTablePolymorphic196
    PgSelectSingle13 --> PgClassExpression17
    First22{{"First[22∈1] ➊"}}:::plan
    PgSelectRows23[["PgSelectRows[23∈1] ➊<br />ᐳSingleTableTopic"]]:::plan
    PgSelectRows23 --> First22
    PgSelect18 --> PgSelectRows23
    First22 --> PgSelectSingle24
    PgClassExpression25{{"PgClassExpression[25∈1] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression25
    PgClassExpression25 --> Lambda26
    PgClassExpression62{{"PgClassExpression[62∈1] ➊<br />ᐸ__single_t...ems__.”id”ᐳ<br />ᐳSingleTableTopic"}}:::plan
    PgSelectSingle13 --> PgClassExpression62
    First65{{"First[65∈1] ➊"}}:::plan
    PgSelectRows66[["PgSelectRows[66∈1] ➊<br />ᐳSingleTablePost"]]:::plan
    PgSelectRows66 --> First65
    PgSelect18 --> PgSelectRows66
    First65 --> PgSelectSingle67
    PgClassExpression68{{"PgClassExpression[68∈1] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle67 --> PgClassExpression68
    PgClassExpression68 --> Lambda69
    First107{{"First[107∈1] ➊"}}:::plan
    PgSelectRows108[["PgSelectRows[108∈1] ➊<br />ᐳSingleTableDivider"]]:::plan
    PgSelectRows108 --> First107
    PgSelect18 --> PgSelectRows108
    First107 --> PgSelectSingle109
    PgClassExpression110{{"PgClassExpression[110∈1] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle109 --> PgClassExpression110
    PgClassExpression110 --> Lambda111
    First149{{"First[149∈1] ➊"}}:::plan
    PgSelectRows150[["PgSelectRows[150∈1] ➊<br />ᐳSingleTableChecklist"]]:::plan
    PgSelectRows150 --> First149
    PgSelect18 --> PgSelectRows150
    First149 --> PgSelectSingle151
    PgClassExpression152{{"PgClassExpression[152∈1] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle151 --> PgClassExpression152
    PgClassExpression152 --> Lambda153
    First191{{"First[191∈1] ➊"}}:::plan
    PgSelectRows192[["PgSelectRows[192∈1] ➊<br />ᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows192 --> First191
    PgSelect18 --> PgSelectRows192
    First191 --> PgSelectSingle193
    PgClassExpression194{{"PgClassExpression[194∈1] ➊<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle193 --> PgClassExpression194
    PgClassExpression194 --> Lambda195
    PgSelect30[["PgSelect[30∈2] ➊<br />ᐸpeopleᐳ<br />ᐳSingleTableTopicᐳSingleTableTopic<br />ᐳSingleTableTopicᐳSingleTablePost<br />ᐳSingleTableTopicᐳSingleTableDivider<br />ᐳSingleTableTopicᐳSingleTableChecklist<br />ᐳSingleTableTopicᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression29{{"PgClassExpression[29∈2] ➊<br />ᐸ__single_t...author_id”ᐳ<br />ᐳSingleTableTopicᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression29 --> PgSelect30
    PgSelectSingle24 --> PgClassExpression29
    First34{{"First[34∈2] ➊"}}:::plan
    PgSelectRows35[["PgSelectRows[35∈2] ➊<br />ᐳSingleTableTopicᐳSingleTableTopic"]]:::plan
    PgSelectRows35 --> First34
    PgSelect30 --> PgSelectRows35
    PgSelectSingle36{{"PgSelectSingle[36∈2] ➊<br />ᐸpeopleᐳ"}}:::plan
    First34 --> PgSelectSingle36
    First40{{"First[40∈2] ➊"}}:::plan
    PgSelectRows41[["PgSelectRows[41∈2] ➊<br />ᐳSingleTableTopicᐳSingleTablePost"]]:::plan
    PgSelectRows41 --> First40
    PgSelect30 --> PgSelectRows41
    PgSelectSingle42{{"PgSelectSingle[42∈2] ➊<br />ᐸpeopleᐳ"}}:::plan
    First40 --> PgSelectSingle42
    First46{{"First[46∈2] ➊"}}:::plan
    PgSelectRows47[["PgSelectRows[47∈2] ➊<br />ᐳSingleTableTopicᐳSingleTableDivider"]]:::plan
    PgSelectRows47 --> First46
    PgSelect30 --> PgSelectRows47
    PgSelectSingle48{{"PgSelectSingle[48∈2] ➊<br />ᐸpeopleᐳ"}}:::plan
    First46 --> PgSelectSingle48
    First52{{"First[52∈2] ➊"}}:::plan
    PgSelectRows53[["PgSelectRows[53∈2] ➊<br />ᐳSingleTableTopicᐳSingleTableChecklist"]]:::plan
    PgSelectRows53 --> First52
    PgSelect30 --> PgSelectRows53
    PgSelectSingle54{{"PgSelectSingle[54∈2] ➊<br />ᐸpeopleᐳ"}}:::plan
    First52 --> PgSelectSingle54
    First58{{"First[58∈2] ➊"}}:::plan
    PgSelectRows59[["PgSelectRows[59∈2] ➊<br />ᐳSingleTableTopicᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows59 --> First58
    PgSelect30 --> PgSelectRows59
    PgSelectSingle60{{"PgSelectSingle[60∈2] ➊<br />ᐸpeopleᐳ"}}:::plan
    First58 --> PgSelectSingle60
    PgClassExpression37{{"PgClassExpression[37∈3] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression37
    PgClassExpression43{{"PgClassExpression[43∈4] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression43
    PgClassExpression49{{"PgClassExpression[49∈5] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    PgClassExpression55{{"PgClassExpression[55∈6] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression55
    PgClassExpression61{{"PgClassExpression[61∈7] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle60 --> PgClassExpression61
    PgSelect73[["PgSelect[73∈8] ➊<br />ᐸpeopleᐳ<br />ᐳSingleTablePostᐳSingleTableTopic<br />ᐳSingleTablePostᐳSingleTablePost<br />ᐳSingleTablePostᐳSingleTableDivider<br />ᐳSingleTablePostᐳSingleTableChecklist<br />ᐳSingleTablePostᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression72{{"PgClassExpression[72∈8] ➊<br />ᐸ__single_t...author_id”ᐳ<br />ᐳSingleTablePostᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression72 --> PgSelect73
    PgSelectSingle67 --> PgClassExpression72
    First77{{"First[77∈8] ➊"}}:::plan
    PgSelectRows78[["PgSelectRows[78∈8] ➊<br />ᐳSingleTablePostᐳSingleTableTopic"]]:::plan
    PgSelectRows78 --> First77
    PgSelect73 --> PgSelectRows78
    PgSelectSingle79{{"PgSelectSingle[79∈8] ➊<br />ᐸpeopleᐳ"}}:::plan
    First77 --> PgSelectSingle79
    First83{{"First[83∈8] ➊"}}:::plan
    PgSelectRows84[["PgSelectRows[84∈8] ➊<br />ᐳSingleTablePostᐳSingleTablePost"]]:::plan
    PgSelectRows84 --> First83
    PgSelect73 --> PgSelectRows84
    PgSelectSingle85{{"PgSelectSingle[85∈8] ➊<br />ᐸpeopleᐳ"}}:::plan
    First83 --> PgSelectSingle85
    First89{{"First[89∈8] ➊"}}:::plan
    PgSelectRows90[["PgSelectRows[90∈8] ➊<br />ᐳSingleTablePostᐳSingleTableDivider"]]:::plan
    PgSelectRows90 --> First89
    PgSelect73 --> PgSelectRows90
    PgSelectSingle91{{"PgSelectSingle[91∈8] ➊<br />ᐸpeopleᐳ"}}:::plan
    First89 --> PgSelectSingle91
    First95{{"First[95∈8] ➊"}}:::plan
    PgSelectRows96[["PgSelectRows[96∈8] ➊<br />ᐳSingleTablePostᐳSingleTableChecklist"]]:::plan
    PgSelectRows96 --> First95
    PgSelect73 --> PgSelectRows96
    PgSelectSingle97{{"PgSelectSingle[97∈8] ➊<br />ᐸpeopleᐳ"}}:::plan
    First95 --> PgSelectSingle97
    First101{{"First[101∈8] ➊"}}:::plan
    PgSelectRows102[["PgSelectRows[102∈8] ➊<br />ᐳSingleTablePostᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows102 --> First101
    PgSelect73 --> PgSelectRows102
    PgSelectSingle103{{"PgSelectSingle[103∈8] ➊<br />ᐸpeopleᐳ"}}:::plan
    First101 --> PgSelectSingle103
    PgClassExpression80{{"PgClassExpression[80∈9] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle79 --> PgClassExpression80
    PgClassExpression86{{"PgClassExpression[86∈10] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle85 --> PgClassExpression86
    PgClassExpression92{{"PgClassExpression[92∈11] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression92
    PgClassExpression98{{"PgClassExpression[98∈12] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle97 --> PgClassExpression98
    PgClassExpression104{{"PgClassExpression[104∈13] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle103 --> PgClassExpression104
    PgSelect115[["PgSelect[115∈14] ➊<br />ᐸpeopleᐳ<br />ᐳSingleTableDividerᐳSingleTableTopic<br />ᐳSingleTableDividerᐳSingleTablePost<br />ᐳSingleTableDividerᐳSingleTableDivider<br />ᐳSingleTableDividerᐳSingleTableChecklist<br />ᐳSingleTableDividerᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression114{{"PgClassExpression[114∈14] ➊<br />ᐸ__single_t...author_id”ᐳ<br />ᐳSingleTableDividerᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression114 --> PgSelect115
    PgSelectSingle109 --> PgClassExpression114
    First119{{"First[119∈14] ➊"}}:::plan
    PgSelectRows120[["PgSelectRows[120∈14] ➊<br />ᐳSingleTableDividerᐳSingleTableTopic"]]:::plan
    PgSelectRows120 --> First119
    PgSelect115 --> PgSelectRows120
    PgSelectSingle121{{"PgSelectSingle[121∈14] ➊<br />ᐸpeopleᐳ"}}:::plan
    First119 --> PgSelectSingle121
    First125{{"First[125∈14] ➊"}}:::plan
    PgSelectRows126[["PgSelectRows[126∈14] ➊<br />ᐳSingleTableDividerᐳSingleTablePost"]]:::plan
    PgSelectRows126 --> First125
    PgSelect115 --> PgSelectRows126
    PgSelectSingle127{{"PgSelectSingle[127∈14] ➊<br />ᐸpeopleᐳ"}}:::plan
    First125 --> PgSelectSingle127
    First131{{"First[131∈14] ➊"}}:::plan
    PgSelectRows132[["PgSelectRows[132∈14] ➊<br />ᐳSingleTableDividerᐳSingleTableDivider"]]:::plan
    PgSelectRows132 --> First131
    PgSelect115 --> PgSelectRows132
    PgSelectSingle133{{"PgSelectSingle[133∈14] ➊<br />ᐸpeopleᐳ"}}:::plan
    First131 --> PgSelectSingle133
    First137{{"First[137∈14] ➊"}}:::plan
    PgSelectRows138[["PgSelectRows[138∈14] ➊<br />ᐳSingleTableDividerᐳSingleTableChecklist"]]:::plan
    PgSelectRows138 --> First137
    PgSelect115 --> PgSelectRows138
    PgSelectSingle139{{"PgSelectSingle[139∈14] ➊<br />ᐸpeopleᐳ"}}:::plan
    First137 --> PgSelectSingle139
    First143{{"First[143∈14] ➊"}}:::plan
    PgSelectRows144[["PgSelectRows[144∈14] ➊<br />ᐳSingleTableDividerᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows144 --> First143
    PgSelect115 --> PgSelectRows144
    PgSelectSingle145{{"PgSelectSingle[145∈14] ➊<br />ᐸpeopleᐳ"}}:::plan
    First143 --> PgSelectSingle145
    PgClassExpression122{{"PgClassExpression[122∈15] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle121 --> PgClassExpression122
    PgClassExpression128{{"PgClassExpression[128∈16] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle127 --> PgClassExpression128
    PgClassExpression134{{"PgClassExpression[134∈17] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle133 --> PgClassExpression134
    PgClassExpression140{{"PgClassExpression[140∈18] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle139 --> PgClassExpression140
    PgClassExpression146{{"PgClassExpression[146∈19] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle145 --> PgClassExpression146
    PgSelect157[["PgSelect[157∈20] ➊<br />ᐸpeopleᐳ<br />ᐳSingleTableChecklistᐳSingleTableTopic<br />ᐳSingleTableChecklistᐳSingleTablePost<br />ᐳSingleTableChecklistᐳSingleTableDivider<br />ᐳSingleTableChecklistᐳSingleTableChecklist<br />ᐳSingleTableChecklistᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression156{{"PgClassExpression[156∈20] ➊<br />ᐸ__single_t...author_id”ᐳ<br />ᐳSingleTableChecklistᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression156 --> PgSelect157
    PgSelectSingle151 --> PgClassExpression156
    First161{{"First[161∈20] ➊"}}:::plan
    PgSelectRows162[["PgSelectRows[162∈20] ➊<br />ᐳSingleTableChecklistᐳSingleTableTopic"]]:::plan
    PgSelectRows162 --> First161
    PgSelect157 --> PgSelectRows162
    PgSelectSingle163{{"PgSelectSingle[163∈20] ➊<br />ᐸpeopleᐳ"}}:::plan
    First161 --> PgSelectSingle163
    First167{{"First[167∈20] ➊"}}:::plan
    PgSelectRows168[["PgSelectRows[168∈20] ➊<br />ᐳSingleTableChecklistᐳSingleTablePost"]]:::plan
    PgSelectRows168 --> First167
    PgSelect157 --> PgSelectRows168
    PgSelectSingle169{{"PgSelectSingle[169∈20] ➊<br />ᐸpeopleᐳ"}}:::plan
    First167 --> PgSelectSingle169
    First173{{"First[173∈20] ➊"}}:::plan
    PgSelectRows174[["PgSelectRows[174∈20] ➊<br />ᐳSingleTableChecklistᐳSingleTableDivider"]]:::plan
    PgSelectRows174 --> First173
    PgSelect157 --> PgSelectRows174
    PgSelectSingle175{{"PgSelectSingle[175∈20] ➊<br />ᐸpeopleᐳ"}}:::plan
    First173 --> PgSelectSingle175
    First179{{"First[179∈20] ➊"}}:::plan
    PgSelectRows180[["PgSelectRows[180∈20] ➊<br />ᐳSingleTableChecklistᐳSingleTableChecklist"]]:::plan
    PgSelectRows180 --> First179
    PgSelect157 --> PgSelectRows180
    PgSelectSingle181{{"PgSelectSingle[181∈20] ➊<br />ᐸpeopleᐳ"}}:::plan
    First179 --> PgSelectSingle181
    First185{{"First[185∈20] ➊"}}:::plan
    PgSelectRows186[["PgSelectRows[186∈20] ➊<br />ᐳSingleTableChecklistᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows186 --> First185
    PgSelect157 --> PgSelectRows186
    PgSelectSingle187{{"PgSelectSingle[187∈20] ➊<br />ᐸpeopleᐳ"}}:::plan
    First185 --> PgSelectSingle187
    PgClassExpression164{{"PgClassExpression[164∈21] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle163 --> PgClassExpression164
    PgClassExpression170{{"PgClassExpression[170∈22] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle169 --> PgClassExpression170
    PgClassExpression176{{"PgClassExpression[176∈23] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle175 --> PgClassExpression176
    PgClassExpression182{{"PgClassExpression[182∈24] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle181 --> PgClassExpression182
    PgClassExpression188{{"PgClassExpression[188∈25] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle187 --> PgClassExpression188
    PgSelect199[["PgSelect[199∈26] ➊<br />ᐸpeopleᐳ<br />ᐳSingleTableChecklistItemᐳSingleTableTopic<br />ᐳSingleTableChecklistItemᐳSingleTablePost<br />ᐳSingleTableChecklistItemᐳSingleTableDivider<br />ᐳSingleTableChecklistItemᐳSingleTableChecklist<br />ᐳSingleTableChecklistItemᐳSingleTableChecklistItem"]]:::plan
    PgClassExpression198{{"PgClassExpression[198∈26] ➊<br />ᐸ__single_t...author_id”ᐳ<br />ᐳSingleTableChecklistItemᐳSingleTableTopic"}}:::plan
    Object10 & PgClassExpression198 --> PgSelect199
    PgSelectSingle193 --> PgClassExpression198
    First203{{"First[203∈26] ➊"}}:::plan
    PgSelectRows204[["PgSelectRows[204∈26] ➊<br />ᐳSingleTableChecklistItemᐳSingleTableTopic"]]:::plan
    PgSelectRows204 --> First203
    PgSelect199 --> PgSelectRows204
    PgSelectSingle205{{"PgSelectSingle[205∈26] ➊<br />ᐸpeopleᐳ"}}:::plan
    First203 --> PgSelectSingle205
    First209{{"First[209∈26] ➊"}}:::plan
    PgSelectRows210[["PgSelectRows[210∈26] ➊<br />ᐳSingleTableChecklistItemᐳSingleTablePost"]]:::plan
    PgSelectRows210 --> First209
    PgSelect199 --> PgSelectRows210
    PgSelectSingle211{{"PgSelectSingle[211∈26] ➊<br />ᐸpeopleᐳ"}}:::plan
    First209 --> PgSelectSingle211
    First215{{"First[215∈26] ➊"}}:::plan
    PgSelectRows216[["PgSelectRows[216∈26] ➊<br />ᐳSingleTableChecklistItemᐳSingleTableDivider"]]:::plan
    PgSelectRows216 --> First215
    PgSelect199 --> PgSelectRows216
    PgSelectSingle217{{"PgSelectSingle[217∈26] ➊<br />ᐸpeopleᐳ"}}:::plan
    First215 --> PgSelectSingle217
    First221{{"First[221∈26] ➊"}}:::plan
    PgSelectRows222[["PgSelectRows[222∈26] ➊<br />ᐳSingleTableChecklistItemᐳSingleTableChecklist"]]:::plan
    PgSelectRows222 --> First221
    PgSelect199 --> PgSelectRows222
    PgSelectSingle223{{"PgSelectSingle[223∈26] ➊<br />ᐸpeopleᐳ"}}:::plan
    First221 --> PgSelectSingle223
    First227{{"First[227∈26] ➊"}}:::plan
    PgSelectRows228[["PgSelectRows[228∈26] ➊<br />ᐳSingleTableChecklistItemᐳSingleTableChecklistItem"]]:::plan
    PgSelectRows228 --> First227
    PgSelect199 --> PgSelectRows228
    PgSelectSingle229{{"PgSelectSingle[229∈26] ➊<br />ᐸpeopleᐳ"}}:::plan
    First227 --> PgSelectSingle229
    PgClassExpression206{{"PgClassExpression[206∈27] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle205 --> PgClassExpression206
    PgClassExpression212{{"PgClassExpression[212∈28] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle211 --> PgClassExpression212
    PgClassExpression218{{"PgClassExpression[218∈29] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression218
    PgClassExpression224{{"PgClassExpression[224∈30] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle223 --> PgClassExpression224
    PgClassExpression230{{"PgClassExpression[230∈31] ➊<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle229 --> PgClassExpression230

    %% define steps

    subgraph "Buckets for queries/interfaces-single-table/relation"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 231, 10<br />2: PgSelect[7]<br />3: PgSelectRows[12]<br />ᐳ: 11, 13, 14, 15<br />4: PgSingleTablePolymorphic[16]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectRows12,PgSelectSingle13,PgClassExpression14,Lambda15,PgSingleTablePolymorphic16,Constant231 bucket0
    Bucket1("Bucket 1 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 13, 10, 16<br />ᐳSingleTableTopic<br />ᐳSingleTablePost<br />ᐳSingleTableDivider<br />ᐳSingleTableChecklist<br />ᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: 17, 62<br />2: PgSelect[18]<br />3: 23, 66, 108, 150, 192<br />ᐳ: 22, 24, 25, 26, 65, 67, 68, 69, 107, 109, 110, 111, 149, 151, 152, 153, 191, 193, 194, 195<br />4: 27, 70, 112, 154, 196"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression17,PgSelect18,First22,PgSelectRows23,PgSelectSingle24,PgClassExpression25,Lambda26,PgSingleTablePolymorphic27,PgClassExpression62,First65,PgSelectRows66,PgSelectSingle67,PgClassExpression68,Lambda69,PgSingleTablePolymorphic70,First107,PgSelectRows108,PgSelectSingle109,PgClassExpression110,Lambda111,PgSingleTablePolymorphic112,First149,PgSelectRows150,PgSelectSingle151,PgClassExpression152,Lambda153,PgSingleTablePolymorphic154,First191,PgSelectRows192,PgSelectSingle193,PgClassExpression194,Lambda195,PgSingleTablePolymorphic196 bucket1
    Bucket2("Bucket 2 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 24, 10, 27, 17<br />ᐳSingleTableTopicᐳSingleTableTopic<br />ᐳSingleTableTopicᐳSingleTablePost<br />ᐳSingleTableTopicᐳSingleTableDivider<br />ᐳSingleTableTopicᐳSingleTableChecklist<br />ᐳSingleTableTopicᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[29]<br />2: PgSelect[30]<br />3: 35, 41, 47, 53, 59<br />ᐳ: 34, 36, 40, 42, 46, 48, 52, 54, 58, 60"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression29,PgSelect30,First34,PgSelectRows35,PgSelectSingle36,First40,PgSelectRows41,PgSelectSingle42,First46,PgSelectRows47,PgSelectSingle48,First52,PgSelectRows53,PgSelectSingle54,First58,PgSelectRows59,PgSelectSingle60 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 36<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[36]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression37 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 42<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[42]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression43 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 48<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[48]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression49 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 54<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[54]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression55 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 60<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[60]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgClassExpression61 bucket7
    Bucket8("Bucket 8 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 67, 10, 70, 17<br />ᐳSingleTablePostᐳSingleTableTopic<br />ᐳSingleTablePostᐳSingleTablePost<br />ᐳSingleTablePostᐳSingleTableDivider<br />ᐳSingleTablePostᐳSingleTableChecklist<br />ᐳSingleTablePostᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[72]<br />2: PgSelect[73]<br />3: 78, 84, 90, 96, 102<br />ᐳ: 77, 79, 83, 85, 89, 91, 95, 97, 101, 103"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression72,PgSelect73,First77,PgSelectRows78,PgSelectSingle79,First83,PgSelectRows84,PgSelectSingle85,First89,PgSelectRows90,PgSelectSingle91,First95,PgSelectRows96,PgSelectSingle97,First101,PgSelectRows102,PgSelectSingle103 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 79<br /><br />ROOT PgSelectSingle{8}ᐸpeopleᐳ[79]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression80 bucket9
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 85<br /><br />ROOT PgSelectSingle{8}ᐸpeopleᐳ[85]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression86 bucket10
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 91<br /><br />ROOT PgSelectSingle{8}ᐸpeopleᐳ[91]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression92 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 97<br /><br />ROOT PgSelectSingle{8}ᐸpeopleᐳ[97]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression98 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 103<br /><br />ROOT PgSelectSingle{8}ᐸpeopleᐳ[103]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgClassExpression104 bucket13
    Bucket14("Bucket 14 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 109, 10, 112, 17<br />ᐳSingleTableDividerᐳSingleTableTopic<br />ᐳSingleTableDividerᐳSingleTablePost<br />ᐳSingleTableDividerᐳSingleTableDivider<br />ᐳSingleTableDividerᐳSingleTableChecklist<br />ᐳSingleTableDividerᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[114]<br />2: PgSelect[115]<br />3: 120, 126, 132, 138, 144<br />ᐳ: 119, 121, 125, 127, 131, 133, 137, 139, 143, 145"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgClassExpression114,PgSelect115,First119,PgSelectRows120,PgSelectSingle121,First125,PgSelectRows126,PgSelectSingle127,First131,PgSelectRows132,PgSelectSingle133,First137,PgSelectRows138,PgSelectSingle139,First143,PgSelectRows144,PgSelectSingle145 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 121<br /><br />ROOT PgSelectSingle{14}ᐸpeopleᐳ[121]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgClassExpression122 bucket15
    Bucket16("Bucket 16 (nullableBoundary)<br />Deps: 127<br /><br />ROOT PgSelectSingle{14}ᐸpeopleᐳ[127]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgClassExpression128 bucket16
    Bucket17("Bucket 17 (nullableBoundary)<br />Deps: 133<br /><br />ROOT PgSelectSingle{14}ᐸpeopleᐳ[133]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,PgClassExpression134 bucket17
    Bucket18("Bucket 18 (nullableBoundary)<br />Deps: 139<br /><br />ROOT PgSelectSingle{14}ᐸpeopleᐳ[139]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgClassExpression140 bucket18
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 145<br /><br />ROOT PgSelectSingle{14}ᐸpeopleᐳ[145]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgClassExpression146 bucket19
    Bucket20("Bucket 20 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 151, 10, 154, 17<br />ᐳSingleTableChecklistᐳSingleTableTopic<br />ᐳSingleTableChecklistᐳSingleTablePost<br />ᐳSingleTableChecklistᐳSingleTableDivider<br />ᐳSingleTableChecklistᐳSingleTableChecklist<br />ᐳSingleTableChecklistᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[156]<br />2: PgSelect[157]<br />3: 162, 168, 174, 180, 186<br />ᐳ: 161, 163, 167, 169, 173, 175, 179, 181, 185, 187"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgClassExpression156,PgSelect157,First161,PgSelectRows162,PgSelectSingle163,First167,PgSelectRows168,PgSelectSingle169,First173,PgSelectRows174,PgSelectSingle175,First179,PgSelectRows180,PgSelectSingle181,First185,PgSelectRows186,PgSelectSingle187 bucket20
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 163<br /><br />ROOT PgSelectSingle{20}ᐸpeopleᐳ[163]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgClassExpression164 bucket21
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 169<br /><br />ROOT PgSelectSingle{20}ᐸpeopleᐳ[169]"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgClassExpression170 bucket22
    Bucket23("Bucket 23 (nullableBoundary)<br />Deps: 175<br /><br />ROOT PgSelectSingle{20}ᐸpeopleᐳ[175]"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgClassExpression176 bucket23
    Bucket24("Bucket 24 (nullableBoundary)<br />Deps: 181<br /><br />ROOT PgSelectSingle{20}ᐸpeopleᐳ[181]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24,PgClassExpression182 bucket24
    Bucket25("Bucket 25 (nullableBoundary)<br />Deps: 187<br /><br />ROOT PgSelectSingle{20}ᐸpeopleᐳ[187]"):::bucket
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgClassExpression188 bucket25
    Bucket26("Bucket 26 (polymorphic)<br />SingleTableTopic,SingleTablePost,SingleTableDivider,SingleTableChecklist,SingleTableChecklistItem<br />Deps: 193, 10, 196, 17<br />ᐳSingleTableChecklistItemᐳSingleTableTopic<br />ᐳSingleTableChecklistItemᐳSingleTablePost<br />ᐳSingleTableChecklistItemᐳSingleTableDivider<br />ᐳSingleTableChecklistItemᐳSingleTableChecklist<br />ᐳSingleTableChecklistItemᐳSingleTableChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[198]<br />2: PgSelect[199]<br />3: 204, 210, 216, 222, 228<br />ᐳ: 203, 205, 209, 211, 215, 217, 221, 223, 227, 229"):::bucket
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgClassExpression198,PgSelect199,First203,PgSelectRows204,PgSelectSingle205,First209,PgSelectRows210,PgSelectSingle211,First215,PgSelectRows216,PgSelectSingle217,First221,PgSelectRows222,PgSelectSingle223,First227,PgSelectRows228,PgSelectSingle229 bucket26
    Bucket27("Bucket 27 (nullableBoundary)<br />Deps: 205<br /><br />ROOT PgSelectSingle{26}ᐸpeopleᐳ[205]"):::bucket
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgClassExpression206 bucket27
    Bucket28("Bucket 28 (nullableBoundary)<br />Deps: 211<br /><br />ROOT PgSelectSingle{26}ᐸpeopleᐳ[211]"):::bucket
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgClassExpression212 bucket28
    Bucket29("Bucket 29 (nullableBoundary)<br />Deps: 217<br /><br />ROOT PgSelectSingle{26}ᐸpeopleᐳ[217]"):::bucket
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgClassExpression218 bucket29
    Bucket30("Bucket 30 (nullableBoundary)<br />Deps: 223<br /><br />ROOT PgSelectSingle{26}ᐸpeopleᐳ[223]"):::bucket
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgClassExpression224 bucket30
    Bucket31("Bucket 31 (nullableBoundary)<br />Deps: 229<br /><br />ROOT PgSelectSingle{26}ᐸpeopleᐳ[229]"):::bucket
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgClassExpression230 bucket31
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2 & Bucket8 & Bucket14 & Bucket20 & Bucket26
    Bucket2 --> Bucket3 & Bucket4 & Bucket5 & Bucket6 & Bucket7
    Bucket8 --> Bucket9 & Bucket10 & Bucket11 & Bucket12 & Bucket13
    Bucket14 --> Bucket15 & Bucket16 & Bucket17 & Bucket18 & Bucket19
    Bucket20 --> Bucket21 & Bucket22 & Bucket23 & Bucket24 & Bucket25
    Bucket26 --> Bucket27 & Bucket28 & Bucket29 & Bucket30 & Bucket31
    end
