%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object20{{"Object[20∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access18{{"Access[18∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access19{{"Access[19∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access18 & Access19 --> Object20
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access18
    __Value2 --> Access19
    __Value0["__Value[0∈0] ➊<br />ᐸvariableValuesᐳ"]:::plan
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection21{{"Connection[21∈0] ➊<br />ᐸ17ᐳ"}}:::plan
    Constant32{{"Constant[32∈0] ➊<br />ᐸ'people'ᐳ"}}:::plan
    Connection50{{"Connection[50∈0] ➊<br />ᐸ48ᐳ"}}:::plan
    Connection84{{"Connection[84∈0] ➊<br />ᐸ82ᐳ"}}:::plan
    Connection119{{"Connection[119∈0] ➊<br />ᐸ117ᐳ"}}:::plan
    PgSelect22[["PgSelect[22∈1] ➊<br />ᐸpostᐳ"]]:::plan
    Object20 & Connection21 --> PgSelect22
    __Item23[/"__Item[23∈2]<br />ᐸ22ᐳ"\]:::itemplan
    PgSelect22 ==> __Item23
    PgSelectSingle24{{"PgSelectSingle[24∈2]<br />ᐸpostᐳ"}}:::plan
    __Item23 --> PgSelectSingle24
    PgSelectSingle31{{"PgSelectSingle[31∈3]<br />ᐸpersonᐳ"}}:::plan
    PgSelectSingle24 --> PgSelectSingle31
    PgClassExpression36{{"PgClassExpression[36∈3]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle24 --> PgClassExpression36
    List34{{"List[34∈4]<br />ᐸ32,33ᐳ"}}:::plan
    PgClassExpression33{{"PgClassExpression[33∈4]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant32 & PgClassExpression33 --> List34
    PgSelectSingle31 --> PgClassExpression33
    Lambda35{{"Lambda[35∈4]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List34 --> Lambda35
    PgSelect57[["PgSelect[57∈5] ➊<br />ᐸpostᐳ"]]:::plan
    __Flag56[["__Flag[56∈5] ➊<br />ᐸ55, if(51), rejectNull, onReject: Error: Invali…ᐳ"]]:::plan
    Object20 & __Flag56 & Connection50 --> PgSelect57
    __Flag55[["__Flag[55∈5] ➊<br />ᐸ54, trapInhibited, onReject: INHIBITᐳ"]]:::plan
    Condition51{{"Condition[51∈5] ➊<br />ᐸexistsᐳ"}}:::plan
    __Flag55 & Condition51 --> __Flag56
    Access46{{"Access[46∈5] ➊<br />ᐸ0.aliceᐳ"}}:::plan
    __Value0 --> Access46
    Access46 --> Condition51
    Lambda52{{"Lambda[52∈5] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Access46 --> Lambda52
    Access53{{"Access[53∈5] ➊<br />ᐸ52.1ᐳ"}}:::plan
    Lambda52 --> Access53
    __Flag54[["__Flag[54∈5] ➊<br />ᐸ53, rejectNull, onReject: INHIBITᐳ"]]:::plan
    Access53 --> __Flag54
    __Flag54 --> __Flag55
    __Item58[/"__Item[58∈6]<br />ᐸ57ᐳ"\]:::itemplan
    PgSelect57 ==> __Item58
    PgSelectSingle59{{"PgSelectSingle[59∈6]<br />ᐸpostᐳ"}}:::plan
    __Item58 --> PgSelectSingle59
    PgSelectSingle66{{"PgSelectSingle[66∈7]<br />ᐸpersonᐳ"}}:::plan
    PgSelectSingle59 --> PgSelectSingle66
    PgClassExpression71{{"PgClassExpression[71∈7]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle59 --> PgClassExpression71
    List69{{"List[69∈8]<br />ᐸ32,68ᐳ"}}:::plan
    PgClassExpression68{{"PgClassExpression[68∈8]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant32 & PgClassExpression68 --> List69
    PgSelectSingle66 --> PgClassExpression68
    Lambda70{{"Lambda[70∈8]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List69 --> Lambda70
    PgSelect91[["PgSelect[91∈9] ➊<br />ᐸpostᐳ"]]:::plan
    __Flag90[["__Flag[90∈9] ➊<br />ᐸ89, if(85), rejectNull, onReject: Error: Invali…ᐳ"]]:::plan
    Object20 & __Flag90 & Connection84 --> PgSelect91
    __Flag89[["__Flag[89∈9] ➊<br />ᐸ88, trapInhibited, onReject: INHIBITᐳ"]]:::plan
    Condition85{{"Condition[85∈9] ➊<br />ᐸexistsᐳ"}}:::plan
    __Flag89 & Condition85 --> __Flag90
    Constant149{{"Constant[149∈9] ➊<br />ᐸnullᐳ"}}:::plan
    Constant149 --> Condition85
    Lambda86{{"Lambda[86∈9] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Constant149 --> Lambda86
    Access87{{"Access[87∈9] ➊<br />ᐸ86.1ᐳ"}}:::plan
    Lambda86 --> Access87
    __Flag88[["__Flag[88∈9] ➊<br />ᐸ87, rejectNull, onReject: INHIBITᐳ"]]:::plan
    Access87 --> __Flag88
    __Flag88 --> __Flag89
    __Item92[/"__Item[92∈10]<br />ᐸ91ᐳ"\]:::itemplan
    PgSelect91 ==> __Item92
    PgSelectSingle93{{"PgSelectSingle[93∈10]<br />ᐸpostᐳ"}}:::plan
    __Item92 --> PgSelectSingle93
    PgSelectSingle100{{"PgSelectSingle[100∈11]<br />ᐸpersonᐳ"}}:::plan
    PgSelectSingle93 --> PgSelectSingle100
    PgClassExpression105{{"PgClassExpression[105∈11]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression105
    List103{{"List[103∈12]<br />ᐸ32,102ᐳ"}}:::plan
    PgClassExpression102{{"PgClassExpression[102∈12]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant32 & PgClassExpression102 --> List103
    PgSelectSingle100 --> PgClassExpression102
    Lambda104{{"Lambda[104∈12]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List103 --> Lambda104
    PgSelect126[["PgSelect[126∈13] ➊<br />ᐸpostᐳ"]]:::plan
    __Flag125[["__Flag[125∈13] ➊<br />ᐸ124, if(120), rejectNull, onReject: Error: Invali…ᐳ"]]:::plan
    Object20 & __Flag125 & Connection119 --> PgSelect126
    __Flag124[["__Flag[124∈13] ➊<br />ᐸ123, trapInhibited, onReject: INHIBITᐳ"]]:::plan
    Condition120{{"Condition[120∈13] ➊<br />ᐸexistsᐳ"}}:::plan
    __Flag124 & Condition120 --> __Flag125
    Access115{{"Access[115∈13] ➊<br />ᐸ0.post3ᐳ"}}:::plan
    __Value0 --> Access115
    Access115 --> Condition120
    Lambda121{{"Lambda[121∈13] ➊<br />ᐸspecifier_Person_base64JSONᐳ"}}:::plan
    Access115 --> Lambda121
    Access122{{"Access[122∈13] ➊<br />ᐸ121.1ᐳ"}}:::plan
    Lambda121 --> Access122
    __Flag123[["__Flag[123∈13] ➊<br />ᐸ122, rejectNull, onReject: INHIBITᐳ"]]:::plan
    Access122 --> __Flag123
    __Flag123 --> __Flag124
    __Item127[/"__Item[127∈14]<br />ᐸ126ᐳ"\]:::itemplan
    PgSelect126 ==> __Item127
    PgSelectSingle128{{"PgSelectSingle[128∈14]<br />ᐸpostᐳ"}}:::plan
    __Item127 --> PgSelectSingle128
    PgSelectSingle135{{"PgSelectSingle[135∈15]<br />ᐸpersonᐳ"}}:::plan
    PgSelectSingle128 --> PgSelectSingle135
    PgClassExpression140{{"PgClassExpression[140∈15]<br />ᐸ__post__.”body”ᐳ"}}:::plan
    PgSelectSingle128 --> PgClassExpression140
    List138{{"List[138∈16]<br />ᐸ32,137ᐳ"}}:::plan
    PgClassExpression137{{"PgClassExpression[137∈16]<br />ᐸ__person__.”id”ᐳ"}}:::plan
    Constant32 & PgClassExpression137 --> List138
    PgSelectSingle135 --> PgClassExpression137
    Lambda139{{"Lambda[139∈16]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List138 --> Lambda139

    %% define steps

    subgraph "Buckets for queries/relay/conditionNodeId"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value2,__Value4,Access18,Access19,Object20,Connection21,Constant32,Connection50,Connection84,Connection119 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 20, 21, 32<br /><br />ROOT Connectionᐸ17ᐳ[21]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect22 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 32<br /><br />ROOT __Item{2}ᐸ22ᐳ[23]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item23,PgSelectSingle24 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 24, 32<br /><br />ROOT PgSelectSingle{2}ᐸpostᐳ[24]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelectSingle31,PgClassExpression36 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 31, 32<br /><br />ROOT PgSelectSingle{3}ᐸpersonᐳ[31]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression33,List34,Lambda35 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 0, 20, 50, 32<br /><br />ROOT Connectionᐸ48ᐳ[50]<br />1: <br />ᐳ: 46, 51, 52, 53<br />2: __Flag[54]<br />3: __Flag[55]<br />4: __Flag[56]<br />5: PgSelect[57]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,Access46,Condition51,Lambda52,Access53,__Flag54,__Flag55,__Flag56,PgSelect57 bucket5
    Bucket6("Bucket 6 (listItem)<br />Deps: 32<br /><br />ROOT __Item{6}ᐸ57ᐳ[58]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item58,PgSelectSingle59 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 59, 32<br /><br />ROOT PgSelectSingle{6}ᐸpostᐳ[59]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelectSingle66,PgClassExpression71 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 66, 32<br /><br />ROOT PgSelectSingle{7}ᐸpersonᐳ[66]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression68,List69,Lambda70 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 20, 84, 32<br /><br />ROOT Connectionᐸ82ᐳ[84]<br />1: <br />ᐳ: 149, 85, 86, 87<br />2: __Flag[88]<br />3: __Flag[89]<br />4: __Flag[90]<br />5: PgSelect[91]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,Condition85,Lambda86,Access87,__Flag88,__Flag89,__Flag90,PgSelect91,Constant149 bucket9
    Bucket10("Bucket 10 (listItem)<br />Deps: 32<br /><br />ROOT __Item{10}ᐸ91ᐳ[92]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Item92,PgSelectSingle93 bucket10
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 93, 32<br /><br />ROOT PgSelectSingle{10}ᐸpostᐳ[93]"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgSelectSingle100,PgClassExpression105 bucket11
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 100, 32<br /><br />ROOT PgSelectSingle{11}ᐸpersonᐳ[100]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression102,List103,Lambda104 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 0, 20, 119, 32<br /><br />ROOT Connectionᐸ117ᐳ[119]<br />1: <br />ᐳ: 115, 120, 121, 122<br />2: __Flag[123]<br />3: __Flag[124]<br />4: __Flag[125]<br />5: PgSelect[126]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,Access115,Condition120,Lambda121,Access122,__Flag123,__Flag124,__Flag125,PgSelect126 bucket13
    Bucket14("Bucket 14 (listItem)<br />Deps: 32<br /><br />ROOT __Item{14}ᐸ126ᐳ[127]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,__Item127,PgSelectSingle128 bucket14
    Bucket15("Bucket 15 (nullableBoundary)<br />Deps: 128, 32<br /><br />ROOT PgSelectSingle{14}ᐸpostᐳ[128]"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelectSingle135,PgClassExpression140 bucket15
    Bucket16("Bucket 16 (nullableBoundary)<br />Deps: 135, 32<br /><br />ROOT PgSelectSingle{15}ᐸpersonᐳ[135]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgClassExpression137,List138,Lambda139 bucket16
    Bucket0 --> Bucket1 & Bucket5 & Bucket9 & Bucket13
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket5 --> Bucket6
    Bucket6 --> Bucket7
    Bucket7 --> Bucket8
    Bucket9 --> Bucket10
    Bucket10 --> Bucket11
    Bucket11 --> Bucket12
    Bucket13 --> Bucket14
    Bucket14 --> Bucket15
    Bucket15 --> Bucket16
    end
