extends: existence
message: "Use first person (such as '%s') sparingly."
link: https://docs.microsoft.com/en-us/style-guide/grammar/person
ignorecase: true
level: warning
nonword: true
tokens:
  - (?:^|\s)I(?=\s)
  - (?:^|\s)I(?=,\s)
  - \bI'd\b
  - \bI'll\b
  - \bI'm\b
  - \bI've\b
  - \bme\b
  - \bmy\b
  - \bmine\b
