%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸunion_itemsᐳ"]]:::plan
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant117{{"Constant[117∈0] ➊<br />ᐸ987654321ᐳ"}}:::plan
    Object10 & Constant117 --> PgSelect7
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgPolymorphic15{{"PgPolymorphic[15∈0] ➊"}}:::plan
    PgSelectSingle13{{"PgSelectSingle[13∈0] ➊<br />ᐸunion_itemsᐳ"}}:::plan
    PgClassExpression14{{"PgClassExpression[14∈0] ➊<br />ᐸ__union_items__.”type”ᐳ"}}:::plan
    PgSelectSingle13 & PgClassExpression14 --> PgPolymorphic15
    PgUnionAll59[["PgUnionAll[59∈0] ➊"]]:::plan
    Object10 & Constant117 --> PgUnionAll59
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    First11{{"First[11∈0] ➊"}}:::plan
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelectRows12 --> First11
    PgSelect7 --> PgSelectRows12
    First11 --> PgSelectSingle13
    PgSelectSingle13 --> PgClassExpression14
    First61{{"First[61∈0] ➊"}}:::plan
    Access116{{"Access[116∈0] ➊<br />ᐸ59.itemsᐳ"}}:::plan
    Access116 --> First61
    PgUnionAllSingle63["PgUnionAllSingle[63∈0] ➊"]:::plan
    First61 --> PgUnionAllSingle63
    PgUnionAll59 --> Access116
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect17[["PgSelect[17∈1] ➊<br />ᐸunion_topicsᐳ<br />ᐳUnionTopic"]]:::plan
    PgClassExpression16{{"PgClassExpression[16∈1] ➊<br />ᐸ__union_items__.”id”ᐳ<br />ᐳUnionTopic"}}:::plan
    Object10 & PgClassExpression16 --> PgSelect17
    PgSelect26[["PgSelect[26∈1] ➊<br />ᐸunion_postsᐳ<br />ᐳUnionPost"]]:::plan
    Object10 & PgClassExpression16 --> PgSelect26
    PgSelect35[["PgSelect[35∈1] ➊<br />ᐸunion_dividersᐳ<br />ᐳUnionDivider"]]:::plan
    Object10 & PgClassExpression16 --> PgSelect35
    PgSelect43[["PgSelect[43∈1] ➊<br />ᐸunion_checklistsᐳ<br />ᐳUnionChecklist"]]:::plan
    Object10 & PgClassExpression16 --> PgSelect43
    PgSelect50[["PgSelect[50∈1] ➊<br />ᐸunion_checklist_itemsᐳ<br />ᐳUnionChecklistItem"]]:::plan
    Object10 & PgClassExpression16 --> PgSelect50
    PgSelectSingle13 --> PgClassExpression16
    First21{{"First[21∈1] ➊"}}:::plan
    PgSelectRows22[["PgSelectRows[22∈1] ➊"]]:::plan
    PgSelectRows22 --> First21
    PgSelect17 --> PgSelectRows22
    PgSelectSingle23{{"PgSelectSingle[23∈1] ➊<br />ᐸunion_topicsᐳ"}}:::plan
    First21 --> PgSelectSingle23
    PgClassExpression24{{"PgClassExpression[24∈1] ➊<br />ᐸ__union_topics__.”id”ᐳ"}}:::plan
    PgSelectSingle23 --> PgClassExpression24
    PgClassExpression25{{"PgClassExpression[25∈1] ➊<br />ᐸ__union_to...__.”title”ᐳ"}}:::plan
    PgSelectSingle23 --> PgClassExpression25
    First28{{"First[28∈1] ➊"}}:::plan
    PgSelectRows29[["PgSelectRows[29∈1] ➊"]]:::plan
    PgSelectRows29 --> First28
    PgSelect26 --> PgSelectRows29
    PgSelectSingle30{{"PgSelectSingle[30∈1] ➊<br />ᐸunion_postsᐳ"}}:::plan
    First28 --> PgSelectSingle30
    PgClassExpression31{{"PgClassExpression[31∈1] ➊<br />ᐸ__union_posts__.”id”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression31
    PgClassExpression32{{"PgClassExpression[32∈1] ➊<br />ᐸ__union_posts__.”title”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression32
    PgClassExpression33{{"PgClassExpression[33∈1] ➊<br />ᐸ__union_po...scription”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression33
    PgClassExpression34{{"PgClassExpression[34∈1] ➊<br />ᐸ__union_posts__.”note”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression34
    First37{{"First[37∈1] ➊"}}:::plan
    PgSelectRows38[["PgSelectRows[38∈1] ➊"]]:::plan
    PgSelectRows38 --> First37
    PgSelect35 --> PgSelectRows38
    PgSelectSingle39{{"PgSelectSingle[39∈1] ➊<br />ᐸunion_dividersᐳ"}}:::plan
    First37 --> PgSelectSingle39
    PgClassExpression40{{"PgClassExpression[40∈1] ➊<br />ᐸ__union_dividers__.”id”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression40
    PgClassExpression41{{"PgClassExpression[41∈1] ➊<br />ᐸ__union_di...__.”title”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression41
    PgClassExpression42{{"PgClassExpression[42∈1] ➊<br />ᐸ__union_di...__.”color”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression42
    First45{{"First[45∈1] ➊"}}:::plan
    PgSelectRows46[["PgSelectRows[46∈1] ➊"]]:::plan
    PgSelectRows46 --> First45
    PgSelect43 --> PgSelectRows46
    PgSelectSingle47{{"PgSelectSingle[47∈1] ➊<br />ᐸunion_checklistsᐳ"}}:::plan
    First45 --> PgSelectSingle47
    PgClassExpression48{{"PgClassExpression[48∈1] ➊<br />ᐸ__union_ch...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle47 --> PgClassExpression48
    PgClassExpression49{{"PgClassExpression[49∈1] ➊<br />ᐸ__union_ch...__.”title”ᐳ"}}:::plan
    PgSelectSingle47 --> PgClassExpression49
    First52{{"First[52∈1] ➊"}}:::plan
    PgSelectRows53[["PgSelectRows[53∈1] ➊"]]:::plan
    PgSelectRows53 --> First52
    PgSelect50 --> PgSelectRows53
    PgSelectSingle54{{"PgSelectSingle[54∈1] ➊<br />ᐸunion_checklist_itemsᐳ"}}:::plan
    First52 --> PgSelectSingle54
    PgClassExpression55{{"PgClassExpression[55∈1] ➊<br />ᐸ__union_ch...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression55
    PgClassExpression56{{"PgClassExpression[56∈1] ➊<br />ᐸ__union_ch...scription”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression56
    PgClassExpression57{{"PgClassExpression[57∈1] ➊<br />ᐸ__union_ch...s__.”note”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression57
    PgSelect67[["PgSelect[67∈2] ➊<br />ᐸunion_topicsᐳ<br />ᐳUnionTopic"]]:::plan
    Access66{{"Access[66∈2] ➊<br />ᐸ65.0ᐳ"}}:::plan
    Object10 & Access66 --> PgSelect67
    PgSelect78[["PgSelect[78∈2] ➊<br />ᐸunion_postsᐳ<br />ᐳUnionPost"]]:::plan
    Access77{{"Access[77∈2] ➊<br />ᐸ76.0ᐳ"}}:::plan
    Object10 & Access77 --> PgSelect78
    PgSelect89[["PgSelect[89∈2] ➊<br />ᐸunion_dividersᐳ<br />ᐳUnionDivider"]]:::plan
    Access88{{"Access[88∈2] ➊<br />ᐸ87.0ᐳ"}}:::plan
    Object10 & Access88 --> PgSelect89
    PgSelect99[["PgSelect[99∈2] ➊<br />ᐸunion_checklistsᐳ<br />ᐳUnionChecklist"]]:::plan
    Access98{{"Access[98∈2] ➊<br />ᐸ97.0ᐳ"}}:::plan
    Object10 & Access98 --> PgSelect99
    PgSelect108[["PgSelect[108∈2] ➊<br />ᐸunion_checklist_itemsᐳ<br />ᐳUnionChecklistItem"]]:::plan
    Access107{{"Access[107∈2] ➊<br />ᐸ106.0ᐳ"}}:::plan
    Object10 & Access107 --> PgSelect108
    Access64{{"Access[64∈2] ➊<br />ᐸ63.1ᐳ<br />ᐳUnionTopic"}}:::plan
    PgUnionAllSingle63 --> Access64
    JSONParse65[["JSONParse[65∈2] ➊<br />ᐸ64ᐳ"]]:::plan
    Access64 --> JSONParse65
    JSONParse65 --> Access66
    First71{{"First[71∈2] ➊"}}:::plan
    PgSelectRows72[["PgSelectRows[72∈2] ➊"]]:::plan
    PgSelectRows72 --> First71
    PgSelect67 --> PgSelectRows72
    PgSelectSingle73{{"PgSelectSingle[73∈2] ➊<br />ᐸunion_topicsᐳ"}}:::plan
    First71 --> PgSelectSingle73
    PgClassExpression74{{"PgClassExpression[74∈2] ➊<br />ᐸ__union_topics__.”id”ᐳ"}}:::plan
    PgSelectSingle73 --> PgClassExpression74
    PgClassExpression75{{"PgClassExpression[75∈2] ➊<br />ᐸ__union_to...__.”title”ᐳ"}}:::plan
    PgSelectSingle73 --> PgClassExpression75
    JSONParse76[["JSONParse[76∈2] ➊<br />ᐸ64ᐳ<br />ᐳUnionPost"]]:::plan
    Access64 --> JSONParse76
    JSONParse76 --> Access77
    First80{{"First[80∈2] ➊"}}:::plan
    PgSelectRows81[["PgSelectRows[81∈2] ➊"]]:::plan
    PgSelectRows81 --> First80
    PgSelect78 --> PgSelectRows81
    PgSelectSingle82{{"PgSelectSingle[82∈2] ➊<br />ᐸunion_postsᐳ"}}:::plan
    First80 --> PgSelectSingle82
    PgClassExpression83{{"PgClassExpression[83∈2] ➊<br />ᐸ__union_posts__.”id”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression83
    PgClassExpression84{{"PgClassExpression[84∈2] ➊<br />ᐸ__union_posts__.”title”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression84
    PgClassExpression85{{"PgClassExpression[85∈2] ➊<br />ᐸ__union_po...scription”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression85
    PgClassExpression86{{"PgClassExpression[86∈2] ➊<br />ᐸ__union_posts__.”note”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression86
    JSONParse87[["JSONParse[87∈2] ➊<br />ᐸ64ᐳ<br />ᐳUnionDivider"]]:::plan
    Access64 --> JSONParse87
    JSONParse87 --> Access88
    First91{{"First[91∈2] ➊"}}:::plan
    PgSelectRows92[["PgSelectRows[92∈2] ➊"]]:::plan
    PgSelectRows92 --> First91
    PgSelect89 --> PgSelectRows92
    PgSelectSingle93{{"PgSelectSingle[93∈2] ➊<br />ᐸunion_dividersᐳ"}}:::plan
    First91 --> PgSelectSingle93
    PgClassExpression94{{"PgClassExpression[94∈2] ➊<br />ᐸ__union_dividers__.”id”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression94
    PgClassExpression95{{"PgClassExpression[95∈2] ➊<br />ᐸ__union_di...__.”title”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression95
    PgClassExpression96{{"PgClassExpression[96∈2] ➊<br />ᐸ__union_di...__.”color”ᐳ"}}:::plan
    PgSelectSingle93 --> PgClassExpression96
    JSONParse97[["JSONParse[97∈2] ➊<br />ᐸ64ᐳ<br />ᐳUnionChecklist"]]:::plan
    Access64 --> JSONParse97
    JSONParse97 --> Access98
    First101{{"First[101∈2] ➊"}}:::plan
    PgSelectRows102[["PgSelectRows[102∈2] ➊"]]:::plan
    PgSelectRows102 --> First101
    PgSelect99 --> PgSelectRows102
    PgSelectSingle103{{"PgSelectSingle[103∈2] ➊<br />ᐸunion_checklistsᐳ"}}:::plan
    First101 --> PgSelectSingle103
    PgClassExpression104{{"PgClassExpression[104∈2] ➊<br />ᐸ__union_ch...sts__.”id”ᐳ"}}:::plan
    PgSelectSingle103 --> PgClassExpression104
    PgClassExpression105{{"PgClassExpression[105∈2] ➊<br />ᐸ__union_ch...__.”title”ᐳ"}}:::plan
    PgSelectSingle103 --> PgClassExpression105
    JSONParse106[["JSONParse[106∈2] ➊<br />ᐸ64ᐳ<br />ᐳUnionChecklistItem"]]:::plan
    Access64 --> JSONParse106
    JSONParse106 --> Access107
    First110{{"First[110∈2] ➊"}}:::plan
    PgSelectRows111[["PgSelectRows[111∈2] ➊"]]:::plan
    PgSelectRows111 --> First110
    PgSelect108 --> PgSelectRows111
    PgSelectSingle112{{"PgSelectSingle[112∈2] ➊<br />ᐸunion_checklist_itemsᐳ"}}:::plan
    First110 --> PgSelectSingle112
    PgClassExpression113{{"PgClassExpression[113∈2] ➊<br />ᐸ__union_ch...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression113
    PgClassExpression114{{"PgClassExpression[114∈2] ➊<br />ᐸ__union_ch...scription”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression114
    PgClassExpression115{{"PgClassExpression[115∈2] ➊<br />ᐸ__union_ch...s__.”note”ᐳ"}}:::plan
    PgSelectSingle112 --> PgClassExpression115

    %% define steps

    subgraph "Buckets for queries/unions-table/by-id-987654321"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 8, 9, 117, 10<br />2: PgSelect[7], PgUnionAll[59]<br />ᐳ: Access[116], First[61]<br />3: PgSelectRows[12], PgUnionAllSingle[63]<br />ᐳ: 11, 13, 14, 15"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect7,Access8,Access9,Object10,First11,PgSelectRows12,PgSelectSingle13,PgClassExpression14,PgPolymorphic15,PgUnionAll59,First61,PgUnionAllSingle63,Access116,Constant117 bucket0
    Bucket1("Bucket 1 (polymorphic)<br />UnionTopic,UnionPost,UnionDivider,UnionChecklist,UnionChecklistItem<br />Deps: 13, 10, 15<br />ᐳUnionTopic<br />ᐳUnionPost<br />ᐳUnionDivider<br />ᐳUnionChecklist<br />ᐳUnionChecklistItem<br /><br />1: <br />ᐳ: PgClassExpression[16]<br />2: 17, 26, 35, 43, 50<br />3: 22, 29, 38, 46, 53<br />ᐳ: 21, 23, 24, 25, 28, 30, 31, 32, 33, 34, 37, 39, 40, 41, 42, 45, 47, 48, 49, 52, 54, 55, 56, 57"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgClassExpression16,PgSelect17,First21,PgSelectRows22,PgSelectSingle23,PgClassExpression24,PgClassExpression25,PgSelect26,First28,PgSelectRows29,PgSelectSingle30,PgClassExpression31,PgClassExpression32,PgClassExpression33,PgClassExpression34,PgSelect35,First37,PgSelectRows38,PgSelectSingle39,PgClassExpression40,PgClassExpression41,PgClassExpression42,PgSelect43,First45,PgSelectRows46,PgSelectSingle47,PgClassExpression48,PgClassExpression49,PgSelect50,First52,PgSelectRows53,PgSelectSingle54,PgClassExpression55,PgClassExpression56,PgClassExpression57 bucket1
    Bucket2("Bucket 2 (polymorphic)<br />UnionTopic,UnionPost,UnionDivider,UnionChecklist,UnionChecklistItem<br />Deps: 63, 10<br />ᐳUnionTopic<br />ᐳUnionPost<br />ᐳUnionDivider<br />ᐳUnionChecklist<br />ᐳUnionChecklistItem<br /><br />1: <br />ᐳ: Access[64]<br />2: 65, 76, 87, 97, 106<br />ᐳ: 66, 77, 88, 98, 107<br />3: 67, 78, 89, 99, 108<br />4: 72, 81, 92, 102, 111<br />ᐳ: 71, 73, 74, 75, 80, 82, 83, 84, 85, 86, 91, 93, 94, 95, 96, 101, 103, 104, 105, 110, 112, 113, 114, 115"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,Access64,JSONParse65,Access66,PgSelect67,First71,PgSelectRows72,PgSelectSingle73,PgClassExpression74,PgClassExpression75,JSONParse76,Access77,PgSelect78,First80,PgSelectRows81,PgSelectSingle82,PgClassExpression83,PgClassExpression84,PgClassExpression85,PgClassExpression86,JSONParse87,Access88,PgSelect89,First91,PgSelectRows92,PgSelectSingle93,PgClassExpression94,PgClassExpression95,PgClassExpression96,JSONParse97,Access98,PgSelect99,First101,PgSelectRows102,PgSelectSingle103,PgClassExpression104,PgClassExpression105,JSONParse106,Access107,PgSelect108,First110,PgSelectRows111,PgSelectSingle112,PgClassExpression113,PgClassExpression114,PgClassExpression115 bucket2
    Bucket0 --> Bucket1 & Bucket2
    end
