select
  __collections__."recommendations"::text as "0",
  (not (__collections__."id" is null))::text as "1"
from "polymorphic"."collections" as __collections__
where (
  __collections__."id" = $1::"text"
);

select
  case when (__collections__) is not distinct from null then null::text else to_json(array[
    ((__collections__)."id"),
    ((__collections__)."name"),
    ((__collections__)."type"),
    (((__collections__)."episodes"))::text,
    (((__collections__)."recommendations"))::text,
    ((__collections__)."col_001"),
    ((__collections__)."col_002"),
    ((__collections__)."col_003"),
    ((__collections__)."col_004"),
    ((__collections__)."col_005"),
    ((__collections__)."col_006"),
    ((__collections__)."col_007"),
    ((__collections__)."col_008"),
    ((__collections__)."col_009"),
    ((__collections__)."col_010"),
    ((__collections__)."col_011"),
    ((__collections__)."col_012"),
    ((__collections__)."col_013"),
    ((__collections__)."col_014"),
    ((__collections__)."col_015"),
    ((__collections__)."col_016"),
    ((__collections__)."col_017"),
    ((__collections__)."col_018"),
    ((__collections__)."col_019"),
    ((__collections__)."col_020"),
    ((__collections__)."col_021"),
    ((__collections__)."col_022"),
    ((__collections__)."col_023"),
    ((__collections__)."col_024"),
    ((__collections__)."col_025"),
    ((__collections__)."col_026"),
    ((__collections__)."col_027"),
    ((__collections__)."col_028"),
    ((__collections__)."col_029"),
    ((__collections__)."col_030"),
    ((__collections__)."col_031"),
    ((__collections__)."col_032"),
    ((__collections__)."col_033"),
    ((__collections__)."col_034"),
    ((__collections__)."col_035"),
    ((__collections__)."col_036"),
    ((__collections__)."col_037"),
    ((__collections__)."col_038"),
    ((__collections__)."col_039"),
    ((__collections__)."col_040"),
    ((__collections__)."col_041"),
    ((__collections__)."col_042"),
    ((__collections__)."col_043"),
    ((__collections__)."col_044"),
    ((__collections__)."col_045"),
    ((__collections__)."col_046"),
    ((__collections__)."col_047"),
    ((__collections__)."col_048"),
    ((__collections__)."col_049"),
    ((__collections__)."col_050"),
    ((__collections__)."col_051"),
    ((__collections__)."col_052"),
    ((__collections__)."col_053"),
    ((__collections__)."col_054"),
    ((__collections__)."col_055"),
    ((__collections__)."col_056"),
    ((__collections__)."col_057"),
    ((__collections__)."col_058"),
    ((__collections__)."col_059"),
    ((__collections__)."col_060"),
    ((__collections__)."col_061"),
    ((__collections__)."col_062"),
    ((__collections__)."col_063"),
    ((__collections__)."col_064"),
    ((__collections__)."col_065"),
    ((__collections__)."col_066"),
    ((__collections__)."col_067"),
    ((__collections__)."col_068"),
    ((__collections__)."col_069"),
    ((__collections__)."col_070"),
    ((__collections__)."col_071"),
    ((__collections__)."col_072"),
    ((__collections__)."col_073"),
    ((__collections__)."col_074"),
    ((__collections__)."col_075"),
    ((__collections__)."col_076"),
    ((__collections__)."col_077"),
    ((__collections__)."col_078"),
    ((__collections__)."col_079"),
    ((__collections__)."col_080"),
    ((__collections__)."col_081"),
    ((__collections__)."col_082"),
    ((__collections__)."col_083"),
    ((__collections__)."col_084"),
    ((__collections__)."col_085"),
    ((__collections__)."col_086"),
    ((__collections__)."col_087"),
    ((__collections__)."col_088"),
    ((__collections__)."col_089"),
    ((__collections__)."col_090"),
    ((__collections__)."col_091"),
    ((__collections__)."col_092"),
    ((__collections__)."col_093"),
    ((__collections__)."col_094"),
    ((__collections__)."col_095"),
    ((__collections__)."col_096"),
    ((__collections__)."col_097"),
    ((__collections__)."col_098"),
    ((__collections__)."col_099"),
    ((__collections__)."col_100"),
    to_char(((__collections__)."created_at"), 'YYYY-MM-DD"T"HH24:MI:SS.USTZH:TZM'::text)
  ])::text end as "0",
  (not (__collections__."id" is null))::text as "1"
from "polymorphic"."collections" as __collections__
where (
  __collections__.id = ANY($1::"text"[])
)
order by __collections__."id" asc
limit 10;