%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/person-app-vulns.app-condition"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 13, 77, 31, 29, 30, 78, 40<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[15]<br />2: PgSelectRows[16]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 12, 31, 29, 30, 78, 40<br /><br />ROOT __Item{2}ᐸ16ᐳ[17]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 18, 12, 31, 29, 30, 78, 40<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[18]<br />1: <br />ᐳ: 19, 20<br />2: PgUnionAll[32]<br />ᐳ: Access[76]"):::bucket
    Bucket4("Bucket 4 (listItem)<br />Deps: 32, 40, 12<br /><br />ROOT __Item{4}ᐸ76ᐳ[34]"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 34, 36, 40, 12<br /><br />ROOT __Item{4}ᐸ76ᐳ[34]"):::bucket
    Bucket6("Bucket 6 (polymorphic)<br />Deps: 12, 44, 43<br /><br />1: PgSelect[46], PgSelect[60]<br />2: PgSelectRows[55], PgSelectRows[69]<br />ᐳ: 54, 57, 68, 71, 72, 73, 74, 75"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />AwsApplication<br />Deps: 72, 73<br />ᐳAwsApplication"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />GcpApplication<br />Deps: 74, 75<br />ᐳGcpApplication"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket6 --> Bucket7 & Bucket8

    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __InputObject23{{"__InputObject[23∈0] ➊"}}:::plan
    Constant80{{"Constant[80∈0] ➊<br />ᐸ'AWfulS'ᐳ"}}:::plan
    Constant80 --> __InputObject23
    Connection29{{"Connection[29∈0] ➊<br />ᐸ25ᐳ"}}:::plan
    Constant78{{"Constant[78∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Lambda30{{"Lambda[30∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    Constant78 & Lambda30 --> Connection29
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant77{{"Constant[77∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Constant77 --> Connection13
    Constant79{{"Constant[79∈0] ➊<br />ᐸ'WyI0OTgwM2MxZTJiIiwiQXdzQXBwbGljYXRpb24iLCJbXCI0XCJdIl0='ᐳ"}}:::plan
    Constant79 --> Lambda30
    ApplyInput31{{"ApplyInput[31∈0] ➊"}}:::plan
    __InputObject23 --> ApplyInput31
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant40{{"Constant[40∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    PgSelect15[["PgSelect[15∈1] ➊<br />ᐸpeopleᐳ"]]:::plan
    Object12 & Connection13 & Constant77 --> PgSelect15
    PgSelectRows16[["PgSelectRows[16∈1] ➊"]]:::plan
    PgSelect15 --> PgSelectRows16
    __Item17[/"__Item[17∈2]<br />ᐸ16ᐳ"\]:::itemplan
    PgSelectRows16 ==> __Item17
    PgSelectSingle18{{"PgSelectSingle[18∈2]<br />ᐸpeopleᐳ"}}:::plan
    __Item17 --> PgSelectSingle18
    PgUnionAll32[["PgUnionAll[32∈3]<br />ᐸAwsApplication,GcpApplicationᐳ"]]:::plan
    PgClassExpression19{{"PgClassExpression[19∈3]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Object12 & PgClassExpression19 & ApplyInput31 & Connection29 & Lambda30 & Constant78 --> PgUnionAll32
    PgSelectSingle18 --> PgClassExpression19
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression20
    Access76{{"Access[76∈3]<br />ᐸ32.itemsᐳ"}}:::plan
    PgUnionAll32 --> Access76
    __Item34[/"__Item[34∈4]<br />ᐸ76ᐳ"\]:::itemplan
    Access76 ==> __Item34
    Access36{{"Access[36∈4]<br />ᐸ32.cursorDetailsᐳ"}}:::plan
    PgUnionAll32 --> Access36
    List41{{"List[41∈5]<br />ᐸ38,39,40ᐳ"}}:::plan
    Access38{{"Access[38∈5]<br />ᐸ34.0ᐳ"}}:::plan
    Access39{{"Access[39∈5]<br />ᐸ34.1ᐳ"}}:::plan
    Access38 & Access39 & Constant40 --> List41
    PgCursor37{{"PgCursor[37∈5]"}}:::plan
    __Item34 & Access36 --> PgCursor37
    __Item34 --> Access38
    __Item34 --> Access39
    Lambda42{{"Lambda[42∈5]<br />ᐸtoSpecifierᐳ"}}:::plan
    List41 --> Lambda42
    Access43{{"Access[43∈5]<br />ᐸ42.__typenameᐳ"}}:::plan
    Lambda42 --> Access43
    Access44{{"Access[44∈5]<br />ᐸ42.idᐳ"}}:::plan
    Lambda42 --> Access44
    PgSelect46[["PgSelect[46∈6]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Object12 & Access44 --> PgSelect46
    PgSelect60[["PgSelect[60∈6]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & Access44 --> PgSelect60
    First54{{"First[54∈6]^"}}:::plan
    PgSelectRows55[["PgSelectRows[55∈6]^"]]:::plan
    PgSelectRows55 --> First54
    PgSelect46 --> PgSelectRows55
    PgSelectSingle57{{"PgSelectSingle[57∈6]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First54 --> PgSelectSingle57
    First68{{"First[68∈6]^"}}:::plan
    PgSelectRows69[["PgSelectRows[69∈6]^"]]:::plan
    PgSelectRows69 --> First68
    PgSelect60 --> PgSelectRows69
    PgSelectSingle71{{"PgSelectSingle[71∈6]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First68 --> PgSelectSingle71
    PgClassExpression72{{"PgClassExpression[72∈6]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle57 --> PgClassExpression72
    PgClassExpression73{{"PgClassExpression[73∈6]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle57 --> PgClassExpression73
    PgClassExpression74{{"PgClassExpression[74∈6]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression74
    PgClassExpression75{{"PgClassExpression[75∈6]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression75

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13,__InputObject23,Connection29,Lambda30,ApplyInput31,Constant40,Constant77,Constant78,Constant79,Constant80 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect15,PgSelectRows16 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item17,PgSelectSingle18 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression19,PgClassExpression20,PgUnionAll32,Access76 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item34,Access36 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgCursor37,Access38,Access39,List41,Lambda42,Access43,Access44 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect46,First54,PgSelectRows55,PgSelectSingle57,PgSelect60,First68,PgSelectRows69,PgSelectSingle71,PgClassExpression72,PgClassExpression73,PgClassExpression74,PgClassExpression75 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8 bucket8

