%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object18{{"Object[18∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access16{{"Access[16∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access17{{"Access[17∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Access16 & Access17 --> Object18
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value3 --> Access16
    __Value3 --> Access17
    Connection19{{"Connection[19∈0]<br />ᐸ15ᐳ"}}:::plan
    Constant74{{"Constant[74∈0]<br />ᐸ4ᐳ"}}:::plan
    Constant74 --> Connection19
    __Value0["__Value[0∈0]"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    PgSelect20[["PgSelect[20∈1]<br />ᐸpeopleᐳ"]]:::plan
    Object18 & Connection19 --> PgSelect20
    Connection40{{"Connection[40∈1]<br />ᐸ36ᐳ"}}:::plan
    __Item21[/"__Item[21∈2]<br />ᐸ20ᐳ"\]:::itemplan
    PgSelect20 ==> __Item21
    PgSelectSingle22{{"PgSelectSingle[22∈2]<br />ᐸpeopleᐳ"}}:::plan
    __Item21 --> PgSelectSingle22
    PgUnionAll41[["PgUnionAll[41∈3]"]]:::plan
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Object18 & PgClassExpression23 & PgClassExpression23 --> PgUnionAll41
    PgSelectSingle22 --> PgClassExpression23
    PgClassExpression24{{"PgClassExpression[24∈3]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression24
    __Item42[/"__Item[42∈4]<br />ᐸ41ᐳ"\]:::itemplan
    PgUnionAll41 ==> __Item42
    PgUnionAllSingle43["PgUnionAllSingle[43∈4]"]:::plan
    __Item42 --> PgUnionAllSingle43
    List49{{"List[49∈5]<br />ᐸ45,46,47,48ᐳ"}}:::plan
    Access45{{"Access[45∈5]<br />ᐸ43.0ᐳ"}}:::plan
    Access46{{"Access[46∈5]<br />ᐸ43.1ᐳ"}}:::plan
    Access47{{"Access[47∈5]<br />ᐸ43.2ᐳ"}}:::plan
    Access48{{"Access[48∈5]<br />ᐸ43.3ᐳ"}}:::plan
    Access45 & Access46 & Access47 & Access48 --> List49
    PgUnionAllSingle43 --> Access45
    PgUnionAllSingle43 --> Access46
    PgUnionAllSingle43 --> Access47
    PgUnionAllSingle43 --> Access48
    PgCursor44{{"PgCursor[44∈5]"}}:::plan
    List49 --> PgCursor44
    PgSelect53[["PgSelect[53∈6]<br />ᐸawsApplicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Access52{{"Access[52∈6]<br />ᐸ51.0ᐳ"}}:::plan
    Object18 & Access52 --> PgSelect53
    PgSelect65[["PgSelect[65∈6]<br />ᐸgcpApplicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Access64{{"Access[64∈6]<br />ᐸ63.0ᐳ"}}:::plan
    Object18 & Access64 --> PgSelect65
    JSONParse51[["JSONParse[51∈6]<br />ᐸ48ᐳ<br />ᐳAwsApplication"]]:::plan
    Access48 --> JSONParse51
    JSONParse51 --> Access52
    First57{{"First[57∈6]"}}:::plan
    PgSelect53 --> First57
    PgSelectSingle58{{"PgSelectSingle[58∈6]<br />ᐸawsApplicationsᐳ"}}:::plan
    First57 --> PgSelectSingle58
    PgClassExpression59{{"PgClassExpression[59∈6]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈6]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression60
    PgClassExpression61{{"PgClassExpression[61∈6]<br />ᐸ__aws_appl..._deployed”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression61
    JSONParse63[["JSONParse[63∈6]<br />ᐸ48ᐳ<br />ᐳGcpApplication"]]:::plan
    Access48 --> JSONParse63
    JSONParse63 --> Access64
    First69{{"First[69∈6]"}}:::plan
    PgSelect65 --> First69
    PgSelectSingle70{{"PgSelectSingle[70∈6]<br />ᐸgcpApplicationsᐳ"}}:::plan
    First69 --> PgSelectSingle70
    PgClassExpression71{{"PgClassExpression[71∈6]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle70 --> PgClassExpression71
    PgClassExpression72{{"PgClassExpression[72∈6]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle70 --> PgClassExpression72
    PgClassExpression73{{"PgClassExpression[73∈6]<br />ᐸ__gcp_appl..._deployed”ᐳ"}}:::plan
    PgSelectSingle70 --> PgClassExpression73

    %% define steps

    subgraph "Buckets for queries/polymorphic/person-app-vulns.app-order"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,Access16,Access17,Object18,Connection19,Constant74 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 18, 19<br /><br />ROOT Connectionᐸ15ᐳ[19]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect20,Connection40 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 18, 40<br /><br />ROOT __Item{2}ᐸ20ᐳ[21]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item21,PgSelectSingle22 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 22, 18, 40<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[22]<br />1: <br />ᐳ: 23, 24<br />2: PgUnionAll[41]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression23,PgClassExpression24,PgUnionAll41 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 18<br /><br />ROOT __Item{4}ᐸ41ᐳ[42]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item42,PgUnionAllSingle43 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 43, 18<br /><br />ROOT PgUnionAllSingle{4}[43]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgCursor44,Access45,Access46,Access47,Access48,List49 bucket5
    Bucket6("Bucket 6 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 48, 18, 43<br />ᐳAwsApplication<br />ᐳGcpApplication<br />1: JSONParse[51], JSONParse[63]<br />ᐳ: Access[52], Access[64]<br />2: PgSelect[53], PgSelect[65]<br />ᐳ: 57, 58, 59, 60, 61, 69, 70, 71, 72, 73"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,JSONParse51,Access52,PgSelect53,First57,PgSelectSingle58,PgClassExpression59,PgClassExpression60,PgClassExpression61,JSONParse63,Access64,PgSelect65,First69,PgSelectSingle70,PgClassExpression71,PgClassExpression72,PgClassExpression73 bucket6
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    end
