%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object13{{"Object[13∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access11 & Access12 --> Object13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access11
    __Value2 --> Access12
    Connection14{{"Connection[14∈0] ➊<br />ᐸ10ᐳ"}}:::plan
    Constant290{{"Constant[290∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Constant290 --> Connection14
    Lambda15{{"Lambda[15∈0] ➊<br />ᐸextractList_grafast_pgSelectApplyᐳ"}}:::plan
    Constant293{{"Constant[293∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant293 --> Lambda15
    Lambda27{{"Lambda[27∈0] ➊<br />ᐸextractList_grafast_pgSelectApplyᐳ"}}:::plan
    Constant7{{"Constant[7∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant7 --> Lambda27
    Lambda105{{"Lambda[105∈0] ➊<br />ᐸextractList_grafast_pgSelectApplyᐳ"}}:::plan
    Constant7 --> Lambda105
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection26{{"Connection[26∈0] ➊<br />ᐸ22ᐳ"}}:::plan
    PgSelect16[["PgSelect[16∈1] ➊<br />ᐸpeopleᐳ"]]:::plan
    Object13 & Lambda15 & Connection14 & Constant290 --> PgSelect16
    PgSelectRows17[["PgSelectRows[17∈1] ➊"]]:::plan
    PgSelect16 --> PgSelectRows17
    __Item18[/"__Item[18∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelectRows17 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈2]<br />ᐸpeopleᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgUnionAll28[["PgUnionAll[28∈3]"]]:::plan
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Object13 & PgClassExpression20 & Lambda27 & Connection26 --> PgUnionAll28
    PgUnionAll33[["PgUnionAll[33∈3]"]]:::plan
    Object13 & PgClassExpression20 & Lambda27 & Connection26 --> PgUnionAll33
    PgUnionAll58[["PgUnionAll[58∈3]"]]:::plan
    Object13 & PgClassExpression20 & Lambda27 & Connection26 --> PgUnionAll58
    PgSelectSingle19 --> PgClassExpression20
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression21
    First29{{"First[29∈3]"}}:::plan
    Access279{{"Access[279∈3]<br />ᐸ28.itemsᐳ"}}:::plan
    Access279 --> First29
    PgUnionAllSingle31["PgUnionAllSingle[31∈3]"]:::plan
    First29 --> PgUnionAllSingle31
    PgClassExpression32{{"PgClassExpression[32∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle31 --> PgClassExpression32
    PgUnionAll28 --> Access279
    Access280{{"Access[280∈3]<br />ᐸ33.itemsᐳ"}}:::plan
    PgUnionAll33 --> Access280
    Access289{{"Access[289∈3]<br />ᐸ58.itemsᐳ"}}:::plan
    PgUnionAll58 --> Access289
    __Item35[/"__Item[35∈4]<br />ᐸ280ᐳ"\]:::itemplan
    Access280 ==> __Item35
    PgUnionAllSingle36["PgUnionAllSingle[36∈4]"]:::plan
    __Item35 --> PgUnionAllSingle36
    Access37{{"Access[37∈4]<br />ᐸ33.cursorDetailsᐳ"}}:::plan
    PgUnionAll33 --> Access37
    PgCursor38{{"PgCursor[38∈5]"}}:::plan
    PgUnionAllSingle36 & Access37 --> PgCursor38
    Access39{{"Access[39∈5]<br />ᐸ36.1ᐳ"}}:::plan
    PgUnionAllSingle36 --> Access39
    PgSelect42[["PgSelect[42∈6]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Access41{{"Access[41∈6]<br />ᐸ40.0ᐳ"}}:::plan
    Object13 & Access41 --> PgSelect42
    PgSelect52[["PgSelect[52∈6]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Access51{{"Access[51∈6]<br />ᐸ50.0ᐳ"}}:::plan
    Object13 & Access51 --> PgSelect52
    JSONParse40[["JSONParse[40∈6]<br />ᐸ39ᐳ<br />ᐳAwsApplication"]]:::plan
    Access39 --> JSONParse40
    JSONParse40 --> Access41
    First46{{"First[46∈6]"}}:::plan
    PgSelectRows47[["PgSelectRows[47∈6]"]]:::plan
    PgSelectRows47 --> First46
    PgSelect42 --> PgSelectRows47
    PgSelectSingle48{{"PgSelectSingle[48∈6]<br />ᐸaws_applicationsᐳ"}}:::plan
    First46 --> PgSelectSingle48
    PgClassExpression49{{"PgClassExpression[49∈6]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    JSONParse50[["JSONParse[50∈6]<br />ᐸ39ᐳ<br />ᐳGcpApplication"]]:::plan
    Access39 --> JSONParse50
    JSONParse50 --> Access51
    First54{{"First[54∈6]"}}:::plan
    PgSelectRows55[["PgSelectRows[55∈6]"]]:::plan
    PgSelectRows55 --> First54
    PgSelect52 --> PgSelectRows55
    PgSelectSingle56{{"PgSelectSingle[56∈6]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First54 --> PgSelectSingle56
    PgClassExpression57{{"PgClassExpression[57∈6]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression57
    __Item60[/"__Item[60∈7]<br />ᐸ289ᐳ"\]:::itemplan
    Access289 ==> __Item60
    PgUnionAllSingle61["PgUnionAllSingle[61∈7]"]:::plan
    __Item60 --> PgUnionAllSingle61
    Access62{{"Access[62∈7]<br />ᐸ61.1ᐳ"}}:::plan
    PgUnionAllSingle61 --> Access62
    PgUnionAll138[["PgUnionAll[138∈8]<br />ᐳAwsApplication"]]:::plan
    PgClassExpression73{{"PgClassExpression[73∈8]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Connection136{{"Connection[136∈8] ➊<br />ᐸ134ᐳ<br />ᐳAwsApplication"}}:::plan
    Object13 & PgClassExpression73 & Lambda105 & Connection136 --> PgUnionAll138
    PgUnionAll143[["PgUnionAll[143∈8]<br />ᐳAwsApplication"]]:::plan
    Object13 & PgClassExpression73 & Lambda105 & Connection136 --> PgUnionAll143
    PgUnionAll245[["PgUnionAll[245∈8]<br />ᐳGcpApplication"]]:::plan
    PgClassExpression180{{"PgClassExpression[180∈8]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Connection243{{"Connection[243∈8] ➊<br />ᐸ241ᐳ<br />ᐳGcpApplication"}}:::plan
    Object13 & PgClassExpression180 & Lambda105 & Connection243 --> PgUnionAll245
    PgUnionAll250[["PgUnionAll[250∈8]<br />ᐳGcpApplication"]]:::plan
    Object13 & PgClassExpression180 & Lambda105 & Connection243 --> PgUnionAll250
    PgUnionAll77[["PgUnionAll[77∈8]<br />ᐳAwsApplication"]]:::plan
    PgClassExpression75{{"PgClassExpression[75∈8]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression76{{"PgClassExpression[76∈8]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object13 & PgClassExpression75 & PgClassExpression76 --> PgUnionAll77
    PgUnionAll103[["PgUnionAll[103∈8]<br />ᐳAwsApplication"]]:::plan
    Object13 & PgClassExpression73 & Lambda105 --> PgUnionAll103
    PgUnionAll184[["PgUnionAll[184∈8]<br />ᐳGcpApplication"]]:::plan
    PgClassExpression182{{"PgClassExpression[182∈8]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression183{{"PgClassExpression[183∈8]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object13 & PgClassExpression182 & PgClassExpression183 --> PgUnionAll184
    PgUnionAll210[["PgUnionAll[210∈8]<br />ᐳGcpApplication"]]:::plan
    Object13 & PgClassExpression180 & Lambda105 --> PgUnionAll210
    PgSelect65[["PgSelect[65∈8]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Access64{{"Access[64∈8]<br />ᐸ63.0ᐳ"}}:::plan
    Object13 & Access64 --> PgSelect65
    PgSelect174[["PgSelect[174∈8]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Access173{{"Access[173∈8]<br />ᐸ172.0ᐳ"}}:::plan
    Object13 & Access173 --> PgSelect174
    JSONParse63[["JSONParse[63∈8]<br />ᐸ62ᐳ<br />ᐳAwsApplication"]]:::plan
    Access62 --> JSONParse63
    JSONParse63 --> Access64
    First69{{"First[69∈8]"}}:::plan
    PgSelectRows70[["PgSelectRows[70∈8]"]]:::plan
    PgSelectRows70 --> First69
    PgSelect65 --> PgSelectRows70
    PgSelectSingle71{{"PgSelectSingle[71∈8]<br />ᐸaws_applicationsᐳ"}}:::plan
    First69 --> PgSelectSingle71
    PgClassExpression72{{"PgClassExpression[72∈8]<br />ᐸ__aws_appl..._.”aws_id”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression72
    PgSelectSingle71 --> PgClassExpression73
    PgClassExpression74{{"PgClassExpression[74∈8]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression74
    PgSelectSingle71 --> PgClassExpression75
    PgSelectSingle71 --> PgClassExpression76
    First79{{"First[79∈8]"}}:::plan
    Access284{{"Access[284∈8]<br />ᐸ77.itemsᐳ"}}:::plan
    Access284 --> First79
    PgUnionAllSingle81["PgUnionAllSingle[81∈8]"]:::plan
    First79 --> PgUnionAllSingle81
    Access82{{"Access[82∈8]<br />ᐸ81.1ᐳ"}}:::plan
    PgUnionAllSingle81 --> Access82
    First139{{"First[139∈8]"}}:::plan
    Access282{{"Access[282∈8]<br />ᐸ138.itemsᐳ"}}:::plan
    Access282 --> First139
    PgUnionAllSingle141["PgUnionAllSingle[141∈8]"]:::plan
    First139 --> PgUnionAllSingle141
    PgClassExpression142{{"PgClassExpression[142∈8]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle141 --> PgClassExpression142
    JSONParse172[["JSONParse[172∈8]<br />ᐸ62ᐳ<br />ᐳGcpApplication"]]:::plan
    Access62 --> JSONParse172
    JSONParse172 --> Access173
    First176{{"First[176∈8]"}}:::plan
    PgSelectRows177[["PgSelectRows[177∈8]"]]:::plan
    PgSelectRows177 --> First176
    PgSelect174 --> PgSelectRows177
    PgSelectSingle178{{"PgSelectSingle[178∈8]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First176 --> PgSelectSingle178
    PgClassExpression179{{"PgClassExpression[179∈8]<br />ᐸ__gcp_appl..._.”gcp_id”ᐳ"}}:::plan
    PgSelectSingle178 --> PgClassExpression179
    PgSelectSingle178 --> PgClassExpression180
    PgClassExpression181{{"PgClassExpression[181∈8]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle178 --> PgClassExpression181
    PgSelectSingle178 --> PgClassExpression182
    PgSelectSingle178 --> PgClassExpression183
    First186{{"First[186∈8]"}}:::plan
    Access288{{"Access[288∈8]<br />ᐸ184.itemsᐳ"}}:::plan
    Access288 --> First186
    PgUnionAllSingle188["PgUnionAllSingle[188∈8]"]:::plan
    First186 --> PgUnionAllSingle188
    Access189{{"Access[189∈8]<br />ᐸ188.1ᐳ"}}:::plan
    PgUnionAllSingle188 --> Access189
    First246{{"First[246∈8]"}}:::plan
    Access286{{"Access[286∈8]<br />ᐸ245.itemsᐳ"}}:::plan
    Access286 --> First246
    PgUnionAllSingle248["PgUnionAllSingle[248∈8]"]:::plan
    First246 --> PgUnionAllSingle248
    PgClassExpression249{{"PgClassExpression[249∈8]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle248 --> PgClassExpression249
    Access281{{"Access[281∈8]<br />ᐸ103.itemsᐳ"}}:::plan
    PgUnionAll103 --> Access281
    PgUnionAll138 --> Access282
    Access283{{"Access[283∈8]<br />ᐸ143.itemsᐳ"}}:::plan
    PgUnionAll143 --> Access283
    PgUnionAll77 --> Access284
    Access285{{"Access[285∈8]<br />ᐸ210.itemsᐳ"}}:::plan
    PgUnionAll210 --> Access285
    PgUnionAll245 --> Access286
    Access287{{"Access[287∈8]<br />ᐸ250.itemsᐳ"}}:::plan
    PgUnionAll250 --> Access287
    PgUnionAll184 --> Access288
    PgSelect85[["PgSelect[85∈9]<br />ᐸorganizationsᐳ<br />ᐳAwsApplicationᐳOrganization"]]:::plan
    Access84{{"Access[84∈9]<br />ᐸ83.0ᐳ"}}:::plan
    Object13 & Access84 --> PgSelect85
    PgSelect96[["PgSelect[96∈9]<br />ᐸpeopleᐳ<br />ᐳAwsApplicationᐳPerson"]]:::plan
    Access95{{"Access[95∈9]<br />ᐸ94.0ᐳ"}}:::plan
    Object13 & Access95 --> PgSelect96
    JSONParse83[["JSONParse[83∈9]<br />ᐸ82ᐳ<br />ᐳAwsApplicationᐳOrganization"]]:::plan
    Access82 --> JSONParse83
    JSONParse83 --> Access84
    First89{{"First[89∈9]"}}:::plan
    PgSelectRows90[["PgSelectRows[90∈9]"]]:::plan
    PgSelectRows90 --> First89
    PgSelect85 --> PgSelectRows90
    PgSelectSingle91{{"PgSelectSingle[91∈9]<br />ᐸorganizationsᐳ"}}:::plan
    First89 --> PgSelectSingle91
    PgClassExpression92{{"PgClassExpression[92∈9]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression92
    PgClassExpression93{{"PgClassExpression[93∈9]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle91 --> PgClassExpression93
    JSONParse94[["JSONParse[94∈9]<br />ᐸ82ᐳ<br />ᐳAwsApplicationᐳPerson"]]:::plan
    Access82 --> JSONParse94
    JSONParse94 --> Access95
    First98{{"First[98∈9]"}}:::plan
    PgSelectRows99[["PgSelectRows[99∈9]"]]:::plan
    PgSelectRows99 --> First98
    PgSelect96 --> PgSelectRows99
    PgSelectSingle100{{"PgSelectSingle[100∈9]<br />ᐸpeopleᐳ"}}:::plan
    First98 --> PgSelectSingle100
    PgClassExpression101{{"PgClassExpression[101∈9]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle100 --> PgClassExpression101
    PgClassExpression102{{"PgClassExpression[102∈9]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle100 --> PgClassExpression102
    __Item107[/"__Item[107∈10]<br />ᐸ281ᐳ"\]:::itemplan
    Access281 ==> __Item107
    PgUnionAllSingle108["PgUnionAllSingle[108∈10]"]:::plan
    __Item107 --> PgUnionAllSingle108
    Access109{{"Access[109∈10]<br />ᐸ108.1ᐳ"}}:::plan
    PgUnionAllSingle108 --> Access109
    PgSelect112[["PgSelect[112∈11]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access111{{"Access[111∈11]<br />ᐸ110.0ᐳ"}}:::plan
    Object13 & Access111 --> PgSelect112
    PgSelect125[["PgSelect[125∈11]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access124{{"Access[124∈11]<br />ᐸ123.0ᐳ"}}:::plan
    Object13 & Access124 --> PgSelect125
    JSONParse110[["JSONParse[110∈11]<br />ᐸ109ᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access109 --> JSONParse110
    JSONParse110 --> Access111
    First116{{"First[116∈11]"}}:::plan
    PgSelectRows117[["PgSelectRows[117∈11]"]]:::plan
    PgSelectRows117 --> First116
    PgSelect112 --> PgSelectRows117
    PgSelectSingle118{{"PgSelectSingle[118∈11]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First116 --> PgSelectSingle118
    PgClassExpression119{{"PgClassExpression[119∈11]<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression119
    PgClassExpression120{{"PgClassExpression[120∈11]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression120
    PgClassExpression121{{"PgClassExpression[121∈11]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression121
    PgClassExpression122{{"PgClassExpression[122∈11]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression122
    JSONParse123[["JSONParse[123∈11]<br />ᐸ109ᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access109 --> JSONParse123
    JSONParse123 --> Access124
    First127{{"First[127∈11]"}}:::plan
    PgSelectRows128[["PgSelectRows[128∈11]"]]:::plan
    PgSelectRows128 --> First127
    PgSelect125 --> PgSelectRows128
    PgSelectSingle129{{"PgSelectSingle[129∈11]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First127 --> PgSelectSingle129
    PgClassExpression130{{"PgClassExpression[130∈11]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression130
    PgClassExpression131{{"PgClassExpression[131∈11]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression131
    PgClassExpression132{{"PgClassExpression[132∈11]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression132
    PgClassExpression133{{"PgClassExpression[133∈11]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle129 --> PgClassExpression133
    __Item145[/"__Item[145∈12]<br />ᐸ283ᐳ"\]:::itemplan
    Access283 ==> __Item145
    PgUnionAllSingle146["PgUnionAllSingle[146∈12]"]:::plan
    __Item145 --> PgUnionAllSingle146
    Access147{{"Access[147∈12]<br />ᐸ143.cursorDetailsᐳ"}}:::plan
    PgUnionAll143 --> Access147
    PgCursor148{{"PgCursor[148∈13]<br />ᐳAwsApplication"}}:::plan
    PgUnionAllSingle146 & Access147 --> PgCursor148
    Access149{{"Access[149∈13]<br />ᐸ146.1ᐳ"}}:::plan
    PgUnionAllSingle146 --> Access149
    PgSelect152[["PgSelect[152∈14]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access151{{"Access[151∈14]<br />ᐸ150.0ᐳ"}}:::plan
    Object13 & Access151 --> PgSelect152
    PgSelect164[["PgSelect[164∈14]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access163{{"Access[163∈14]<br />ᐸ162.0ᐳ"}}:::plan
    Object13 & Access163 --> PgSelect164
    JSONParse150[["JSONParse[150∈14]<br />ᐸ149ᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access149 --> JSONParse150
    JSONParse150 --> Access151
    First156{{"First[156∈14]"}}:::plan
    PgSelectRows157[["PgSelectRows[157∈14]"]]:::plan
    PgSelectRows157 --> First156
    PgSelect152 --> PgSelectRows157
    PgSelectSingle158{{"PgSelectSingle[158∈14]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First156 --> PgSelectSingle158
    PgClassExpression159{{"PgClassExpression[159∈14]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle158 --> PgClassExpression159
    PgClassExpression160{{"PgClassExpression[160∈14]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle158 --> PgClassExpression160
    PgClassExpression161{{"PgClassExpression[161∈14]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle158 --> PgClassExpression161
    JSONParse162[["JSONParse[162∈14]<br />ᐸ149ᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access149 --> JSONParse162
    JSONParse162 --> Access163
    First166{{"First[166∈14]"}}:::plan
    PgSelectRows167[["PgSelectRows[167∈14]"]]:::plan
    PgSelectRows167 --> First166
    PgSelect164 --> PgSelectRows167
    PgSelectSingle168{{"PgSelectSingle[168∈14]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First166 --> PgSelectSingle168
    PgClassExpression169{{"PgClassExpression[169∈14]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle168 --> PgClassExpression169
    PgClassExpression170{{"PgClassExpression[170∈14]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle168 --> PgClassExpression170
    PgClassExpression171{{"PgClassExpression[171∈14]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle168 --> PgClassExpression171
    PgSelect192[["PgSelect[192∈15]<br />ᐸorganizationsᐳ<br />ᐳGcpApplicationᐳOrganization"]]:::plan
    Access191{{"Access[191∈15]<br />ᐸ190.0ᐳ"}}:::plan
    Object13 & Access191 --> PgSelect192
    PgSelect203[["PgSelect[203∈15]<br />ᐸpeopleᐳ<br />ᐳGcpApplicationᐳPerson"]]:::plan
    Access202{{"Access[202∈15]<br />ᐸ201.0ᐳ"}}:::plan
    Object13 & Access202 --> PgSelect203
    JSONParse190[["JSONParse[190∈15]<br />ᐸ189ᐳ<br />ᐳGcpApplicationᐳOrganization"]]:::plan
    Access189 --> JSONParse190
    JSONParse190 --> Access191
    First196{{"First[196∈15]"}}:::plan
    PgSelectRows197[["PgSelectRows[197∈15]"]]:::plan
    PgSelectRows197 --> First196
    PgSelect192 --> PgSelectRows197
    PgSelectSingle198{{"PgSelectSingle[198∈15]<br />ᐸorganizationsᐳ"}}:::plan
    First196 --> PgSelectSingle198
    PgClassExpression199{{"PgClassExpression[199∈15]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle198 --> PgClassExpression199
    PgClassExpression200{{"PgClassExpression[200∈15]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle198 --> PgClassExpression200
    JSONParse201[["JSONParse[201∈15]<br />ᐸ189ᐳ<br />ᐳGcpApplicationᐳPerson"]]:::plan
    Access189 --> JSONParse201
    JSONParse201 --> Access202
    First205{{"First[205∈15]"}}:::plan
    PgSelectRows206[["PgSelectRows[206∈15]"]]:::plan
    PgSelectRows206 --> First205
    PgSelect203 --> PgSelectRows206
    PgSelectSingle207{{"PgSelectSingle[207∈15]<br />ᐸpeopleᐳ"}}:::plan
    First205 --> PgSelectSingle207
    PgClassExpression208{{"PgClassExpression[208∈15]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle207 --> PgClassExpression208
    PgClassExpression209{{"PgClassExpression[209∈15]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle207 --> PgClassExpression209
    __Item214[/"__Item[214∈16]<br />ᐸ285ᐳ"\]:::itemplan
    Access285 ==> __Item214
    PgUnionAllSingle215["PgUnionAllSingle[215∈16]"]:::plan
    __Item214 --> PgUnionAllSingle215
    Access216{{"Access[216∈16]<br />ᐸ215.1ᐳ"}}:::plan
    PgUnionAllSingle215 --> Access216
    PgSelect219[["PgSelect[219∈17]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access218{{"Access[218∈17]<br />ᐸ217.0ᐳ"}}:::plan
    Object13 & Access218 --> PgSelect219
    PgSelect232[["PgSelect[232∈17]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access231{{"Access[231∈17]<br />ᐸ230.0ᐳ"}}:::plan
    Object13 & Access231 --> PgSelect232
    JSONParse217[["JSONParse[217∈17]<br />ᐸ216ᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access216 --> JSONParse217
    JSONParse217 --> Access218
    First223{{"First[223∈17]"}}:::plan
    PgSelectRows224[["PgSelectRows[224∈17]"]]:::plan
    PgSelectRows224 --> First223
    PgSelect219 --> PgSelectRows224
    PgSelectSingle225{{"PgSelectSingle[225∈17]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First223 --> PgSelectSingle225
    PgClassExpression226{{"PgClassExpression[226∈17]<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression226
    PgClassExpression227{{"PgClassExpression[227∈17]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression227
    PgClassExpression228{{"PgClassExpression[228∈17]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression228
    PgClassExpression229{{"PgClassExpression[229∈17]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression229
    JSONParse230[["JSONParse[230∈17]<br />ᐸ216ᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access216 --> JSONParse230
    JSONParse230 --> Access231
    First234{{"First[234∈17]"}}:::plan
    PgSelectRows235[["PgSelectRows[235∈17]"]]:::plan
    PgSelectRows235 --> First234
    PgSelect232 --> PgSelectRows235
    PgSelectSingle236{{"PgSelectSingle[236∈17]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First234 --> PgSelectSingle236
    PgClassExpression237{{"PgClassExpression[237∈17]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle236 --> PgClassExpression237
    PgClassExpression238{{"PgClassExpression[238∈17]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle236 --> PgClassExpression238
    PgClassExpression239{{"PgClassExpression[239∈17]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle236 --> PgClassExpression239
    PgClassExpression240{{"PgClassExpression[240∈17]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle236 --> PgClassExpression240
    __Item252[/"__Item[252∈18]<br />ᐸ287ᐳ"\]:::itemplan
    Access287 ==> __Item252
    PgUnionAllSingle253["PgUnionAllSingle[253∈18]"]:::plan
    __Item252 --> PgUnionAllSingle253
    Access254{{"Access[254∈18]<br />ᐸ250.cursorDetailsᐳ"}}:::plan
    PgUnionAll250 --> Access254
    PgCursor255{{"PgCursor[255∈19]<br />ᐳGcpApplication"}}:::plan
    PgUnionAllSingle253 & Access254 --> PgCursor255
    Access256{{"Access[256∈19]<br />ᐸ253.1ᐳ"}}:::plan
    PgUnionAllSingle253 --> Access256
    PgSelect259[["PgSelect[259∈20]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access258{{"Access[258∈20]<br />ᐸ257.0ᐳ"}}:::plan
    Object13 & Access258 --> PgSelect259
    PgSelect271[["PgSelect[271∈20]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access270{{"Access[270∈20]<br />ᐸ269.0ᐳ"}}:::plan
    Object13 & Access270 --> PgSelect271
    JSONParse257[["JSONParse[257∈20]<br />ᐸ256ᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access256 --> JSONParse257
    JSONParse257 --> Access258
    First263{{"First[263∈20]"}}:::plan
    PgSelectRows264[["PgSelectRows[264∈20]"]]:::plan
    PgSelectRows264 --> First263
    PgSelect259 --> PgSelectRows264
    PgSelectSingle265{{"PgSelectSingle[265∈20]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First263 --> PgSelectSingle265
    PgClassExpression266{{"PgClassExpression[266∈20]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression266
    PgClassExpression267{{"PgClassExpression[267∈20]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression267
    PgClassExpression268{{"PgClassExpression[268∈20]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle265 --> PgClassExpression268
    JSONParse269[["JSONParse[269∈20]<br />ᐸ256ᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access256 --> JSONParse269
    JSONParse269 --> Access270
    First273{{"First[273∈20]"}}:::plan
    PgSelectRows274[["PgSelectRows[274∈20]"]]:::plan
    PgSelectRows274 --> First273
    PgSelect271 --> PgSelectRows274
    PgSelectSingle275{{"PgSelectSingle[275∈20]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First273 --> PgSelectSingle275
    PgClassExpression276{{"PgClassExpression[276∈20]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle275 --> PgClassExpression276
    PgClassExpression277{{"PgClassExpression[277∈20]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle275 --> PgClassExpression277
    PgClassExpression278{{"PgClassExpression[278∈20]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle275 --> PgClassExpression278

    %% define steps

    subgraph "Buckets for queries/polymorphic/person-app-vulns"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant7,Access11,Access12,Object13,Connection14,Lambda15,Connection26,Lambda27,Lambda105,Constant290,Constant293 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 15, 14, 290, 27, 26, 105<br /><br />ROOT Connectionᐸ10ᐳ[14]<br />1: PgSelect[16]<br />2: PgSelectRows[17]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect16,PgSelectRows17 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 13, 27, 26, 105<br /><br />ROOT __Item{2}ᐸ17ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgSelectSingle19 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 13, 27, 26, 105<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[19]<br />1: <br />ᐳ: 20, 21<br />2: 28, 33, 58<br />ᐳ: 279, 280, 289, 29<br />3: PgUnionAllSingle[31]<br />ᐳ: PgClassExpression[32]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression20,PgClassExpression21,PgUnionAll28,First29,PgUnionAllSingle31,PgClassExpression32,PgUnionAll33,PgUnionAll58,Access279,Access280,Access289 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 33, 13<br /><br />ROOT __Item{4}ᐸ280ᐳ[35]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item35,PgUnionAllSingle36,Access37 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 36, 37, 13<br /><br />ROOT PgUnionAllSingle{4}[36]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgCursor38,Access39 bucket5
    Bucket6("Bucket 6 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 39, 13, 36<br />ᐳAwsApplication<br />ᐳGcpApplication<br /><br />1: JSONParse[40], JSONParse[50]<br />ᐳ: Access[41], Access[51]<br />2: PgSelect[42], PgSelect[52]<br />3: PgSelectRows[47], PgSelectRows[55]<br />ᐳ: 46, 48, 49, 54, 56, 57"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,JSONParse40,Access41,PgSelect42,First46,PgSelectRows47,PgSelectSingle48,PgClassExpression49,JSONParse50,Access51,PgSelect52,First54,PgSelectRows55,PgSelectSingle56,PgClassExpression57 bucket6
    Bucket7("Bucket 7 (listItem)<br />Deps: 13, 105<br /><br />ROOT __Item{7}ᐸ289ᐳ[60]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,__Item60,PgUnionAllSingle61,Access62 bucket7
    Bucket8("Bucket 8 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 62, 13, 105, 61<br />ᐳAwsApplication<br />ᐳGcpApplication<br /><br />1: JSONParse[63], JSONParse[172]<br />ᐳ: 136, 243, 64, 173<br />2: PgSelect[65], PgSelect[174]<br />3: PgSelectRows[70], PgSelectRows[177]<br />ᐳ: 69, 71, 72, 73, 74, 75, 76, 176, 178, 179, 180, 181, 182, 183<br />4: 77, 103, 138, 143, 184, 210, 245, 250<br />ᐳ: 281, 282, 283, 284, 285, 286, 287, 288, 79, 139, 186, 246<br />5: 81, 141, 188, 248<br />ᐳ: 82, 142, 189, 249"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,JSONParse63,Access64,PgSelect65,First69,PgSelectRows70,PgSelectSingle71,PgClassExpression72,PgClassExpression73,PgClassExpression74,PgClassExpression75,PgClassExpression76,PgUnionAll77,First79,PgUnionAllSingle81,Access82,PgUnionAll103,Connection136,PgUnionAll138,First139,PgUnionAllSingle141,PgClassExpression142,PgUnionAll143,JSONParse172,Access173,PgSelect174,First176,PgSelectRows177,PgSelectSingle178,PgClassExpression179,PgClassExpression180,PgClassExpression181,PgClassExpression182,PgClassExpression183,PgUnionAll184,First186,PgUnionAllSingle188,Access189,PgUnionAll210,Connection243,PgUnionAll245,First246,PgUnionAllSingle248,PgClassExpression249,PgUnionAll250,Access281,Access282,Access283,Access284,Access285,Access286,Access287,Access288 bucket8
    Bucket9("Bucket 9 (polymorphic)<br />Organization,Person<br />Deps: 82, 13, 81<br />ᐳAwsApplicationᐳOrganization<br />ᐳAwsApplicationᐳPerson<br /><br />1: JSONParse[83], JSONParse[94]<br />ᐳ: Access[84], Access[95]<br />2: PgSelect[85], PgSelect[96]<br />3: PgSelectRows[90], PgSelectRows[99]<br />ᐳ: 89, 91, 92, 93, 98, 100, 101, 102"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,JSONParse83,Access84,PgSelect85,First89,PgSelectRows90,PgSelectSingle91,PgClassExpression92,PgClassExpression93,JSONParse94,Access95,PgSelect96,First98,PgSelectRows99,PgSelectSingle100,PgClassExpression101,PgClassExpression102 bucket9
    Bucket10("Bucket 10 (listItem)<br />Deps: 13<br /><br />ROOT __Item{10}ᐸ281ᐳ[107]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Item107,PgUnionAllSingle108,Access109 bucket10
    Bucket11("Bucket 11 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 109, 13, 108<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br /><br />1: JSONParse[110], JSONParse[123]<br />ᐳ: Access[111], Access[124]<br />2: PgSelect[112], PgSelect[125]<br />3: PgSelectRows[117], PgSelectRows[128]<br />ᐳ: 116, 118, 119, 120, 121, 122, 127, 129, 130, 131, 132, 133"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,JSONParse110,Access111,PgSelect112,First116,PgSelectRows117,PgSelectSingle118,PgClassExpression119,PgClassExpression120,PgClassExpression121,PgClassExpression122,JSONParse123,Access124,PgSelect125,First127,PgSelectRows128,PgSelectSingle129,PgClassExpression130,PgClassExpression131,PgClassExpression132,PgClassExpression133 bucket11
    Bucket12("Bucket 12 (listItem)<br />Deps: 143, 13<br /><br />ROOT __Item{12}ᐸ283ᐳ[145]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,__Item145,PgUnionAllSingle146,Access147 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 146, 147, 13<br /><br />ROOT PgUnionAllSingle{12}[146]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgCursor148,Access149 bucket13
    Bucket14("Bucket 14 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 149, 13, 146<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br /><br />1: JSONParse[150], JSONParse[162]<br />ᐳ: Access[151], Access[163]<br />2: PgSelect[152], PgSelect[164]<br />3: PgSelectRows[157], PgSelectRows[167]<br />ᐳ: 156, 158, 159, 160, 161, 166, 168, 169, 170, 171"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,JSONParse150,Access151,PgSelect152,First156,PgSelectRows157,PgSelectSingle158,PgClassExpression159,PgClassExpression160,PgClassExpression161,JSONParse162,Access163,PgSelect164,First166,PgSelectRows167,PgSelectSingle168,PgClassExpression169,PgClassExpression170,PgClassExpression171 bucket14
    Bucket15("Bucket 15 (polymorphic)<br />Organization,Person<br />Deps: 189, 13, 188<br />ᐳGcpApplicationᐳOrganization<br />ᐳGcpApplicationᐳPerson<br /><br />1: JSONParse[190], JSONParse[201]<br />ᐳ: Access[191], Access[202]<br />2: PgSelect[192], PgSelect[203]<br />3: PgSelectRows[197], PgSelectRows[206]<br />ᐳ: 196, 198, 199, 200, 205, 207, 208, 209"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,JSONParse190,Access191,PgSelect192,First196,PgSelectRows197,PgSelectSingle198,PgClassExpression199,PgClassExpression200,JSONParse201,Access202,PgSelect203,First205,PgSelectRows206,PgSelectSingle207,PgClassExpression208,PgClassExpression209 bucket15
    Bucket16("Bucket 16 (listItem)<br />Deps: 13<br /><br />ROOT __Item{16}ᐸ285ᐳ[214]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item214,PgUnionAllSingle215,Access216 bucket16
    Bucket17("Bucket 17 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 216, 13, 215<br />ᐳGcpApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability<br /><br />1: JSONParse[217], JSONParse[230]<br />ᐳ: Access[218], Access[231]<br />2: PgSelect[219], PgSelect[232]<br />3: PgSelectRows[224], PgSelectRows[235]<br />ᐳ: 223, 225, 226, 227, 228, 229, 234, 236, 237, 238, 239, 240"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,JSONParse217,Access218,PgSelect219,First223,PgSelectRows224,PgSelectSingle225,PgClassExpression226,PgClassExpression227,PgClassExpression228,PgClassExpression229,JSONParse230,Access231,PgSelect232,First234,PgSelectRows235,PgSelectSingle236,PgClassExpression237,PgClassExpression238,PgClassExpression239,PgClassExpression240 bucket17
    Bucket18("Bucket 18 (listItem)<br />Deps: 250, 13<br /><br />ROOT __Item{18}ᐸ287ᐳ[252]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item252,PgUnionAllSingle253,Access254 bucket18
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 253, 254, 13<br /><br />ROOT PgUnionAllSingle{18}[253]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgCursor255,Access256 bucket19
    Bucket20("Bucket 20 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 256, 13, 253<br />ᐳGcpApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability<br /><br />1: JSONParse[257], JSONParse[269]<br />ᐳ: Access[258], Access[270]<br />2: PgSelect[259], PgSelect[271]<br />3: PgSelectRows[264], PgSelectRows[274]<br />ᐳ: 263, 265, 266, 267, 268, 273, 275, 276, 277, 278"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,JSONParse257,Access258,PgSelect259,First263,PgSelectRows264,PgSelectSingle265,PgClassExpression266,PgClassExpression267,PgClassExpression268,JSONParse269,Access270,PgSelect271,First273,PgSelectRows274,PgSelectSingle275,PgClassExpression276,PgClassExpression277,PgClassExpression278 bucket20
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket7
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9 & Bucket10 & Bucket12 & Bucket15 & Bucket16 & Bucket18
    Bucket10 --> Bucket11
    Bucket12 --> Bucket13
    Bucket13 --> Bucket14
    Bucket16 --> Bucket17
    Bucket18 --> Bucket19
    Bucket19 --> Bucket20
    end
