%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/person-app-vulns"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 13, 381, 25, 41, 165, 173, 242, 250, 315, 323<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[15]<br />2: PgSelectRows[16]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 12, 25, 41, 165, 173, 242, 250, 315, 323<br /><br />ROOT __Item{2}ᐸ16ᐳ[17]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 18, 12, 25, 41, 165, 173, 242, 250, 315, 323<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[18]<br />1: <br />ᐳ: 19, 20<br />2: 26, 31, 32<br />ᐳ: 370, 371, 380, 27, 30"):::bucket
    Bucket4("Bucket 4 (listItem)<br />Deps: 31, 41, 12<br /><br />ROOT __Item{4}ᐸ371ᐳ[35]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 41, 12, 165, 173, 242, 250, 315, 323<br /><br />ROOT __Item{5}ᐸ380ᐳ[37]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 35, 73, 41, 12<br /><br />ROOT __Item{4}ᐸ371ᐳ[35]"):::bucket
    Bucket7("Bucket 7 (polymorphic)<br />Deps: 12, 45, 44, 165, 173, 242, 250, 315, 323<br /><br />1: 47, 61, 99, 124<br />2: PgSelectRows[56], PgSelectRows[70]<br />ᐳ: 55, 58, 69, 72, 75, 76, 77, 78, 79, 100, 101, 102, 103, 104<br />3: 80, 92, 105<br />ᐳ: 376, 379, 85, 110<br />4: PgUnionAll[89], PgUnionAll[114]"):::bucket
    Bucket8("Bucket 8 (polymorphic)<br />Deps: 12, 131, 130<br /><br />1: PgSelect[133], PgSelect[147]<br />2: PgSelectRows[142], PgSelectRows[156]<br />ᐳ: 141, 144, 155, 158, 208, 209"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />AwsApplication<br />Deps: 85, 165, 12, 76, 99, 89, 242, 315, 77<br />ᐳAwsApplication"):::bucket
    Bucket10("Bucket 10 (polymorphicPartition)<br />GcpApplication<br />Deps: 110, 173, 12, 101, 124, 114, 250, 323, 102<br />ᐳGcpApplication"):::bucket
    Bucket11("Bucket 11 (combined)<br />Deps: 12"):::bucket
    Bucket12("Bucket 12 (polymorphic)<br />Deps: 177, 12, 178<br /><br />1: <br />ᐳ: Access[180], Access[194]<br />2: PgSelect[182], PgSelect[196]<br />3: PgSelectRows[191], PgSelectRows[205]<br />ᐳ: 190, 193, 204, 207, 228, 229, 230, 231"):::bucket
    Bucket13("Bucket 13 (listItem)<br />Deps: 242, 12<br /><br />ROOT __Item{13}ᐸ372ᐳ[210]"):::bucket
    Bucket14("Bucket 14 (listItem)<br />Deps: 250, 12<br /><br />ROOT __Item{14}ᐸ373ᐳ[219]"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />AwsApplication<br />Deps: 208<br />ᐳAwsApplication"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />GcpApplication<br />Deps: 209<br />ᐳGcpApplication"):::bucket
    Bucket17("Bucket 17 (combined)<br />Deps: 12"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />Deps: 12, 257, 255<br /><br />1: PgSelect[259], PgSelect[273]<br />2: PgSelectRows[268], PgSelectRows[282]<br />ᐳ: 267, 270, 281, 284, 289, 290, 291, 292, 293, 294, 295, 296"):::bucket
    Bucket19("Bucket 19 (listItem)<br />Deps: 218, 315, 12<br /><br />ROOT __Item{19}ᐸ375ᐳ[285]"):::bucket
    Bucket20("Bucket 20 (listItem)<br />Deps: 227, 323, 12<br /><br />ROOT __Item{20}ᐸ378ᐳ[287]"):::bucket
    Bucket21("Bucket 21 (nullableBoundary)<br />Deps: 285, 305, 315, 12<br /><br />ROOT __Item{19}ᐸ375ᐳ[285]"):::bucket
    Bucket22("Bucket 22 (nullableBoundary)<br />Deps: 287, 308, 323, 12<br /><br />ROOT __Item{20}ᐸ378ᐳ[287]"):::bucket
    Bucket23("Bucket 23 (polymorphicPartition)<br />FirstPartyVulnerability<br />Deps: 290, 291, 292<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳFirstPartyVulnerability"):::bucket
    Bucket24("Bucket 24 (polymorphicPartition)<br />ThirdPartyVulnerability<br />Deps: 294, 295, 296<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability"):::bucket
    Bucket25("Bucket 25 (combined)<br />Deps: 12"):::bucket
    Bucket26("Bucket 26 (polymorphic)<br />Deps: 12, 330, 328<br /><br />1: PgSelect[332], PgSelect[346]<br />2: PgSelectRows[341], PgSelectRows[355]<br />ᐳ: 340, 343, 354, 357, 358, 359, 360, 361, 362, 363"):::bucket
    Bucket27("Bucket 27 (polymorphicPartition)<br />FirstPartyVulnerability<br />Deps: 358, 359, 360<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳFirstPartyVulnerability"):::bucket
    Bucket28("Bucket 28 (polymorphicPartition)<br />ThirdPartyVulnerability<br />Deps: 361, 362, 363<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5
    Bucket4 --> Bucket6
    Bucket5 --> Bucket7
    Bucket6 --> Bucket8
    Bucket7 --> Bucket9 & Bucket10
    Bucket8 --> Bucket15 & Bucket16
    Bucket9 --> Bucket11 & Bucket13 & Bucket19
    Bucket10 --> Bucket11 & Bucket14 & Bucket20
    Bucket11 --> Bucket12
    Bucket13 --> Bucket17
    Bucket14 --> Bucket17
    Bucket17 --> Bucket18
    Bucket18 --> Bucket23 & Bucket24
    Bucket19 --> Bucket21
    Bucket20 --> Bucket22
    Bucket21 --> Bucket25
    Bucket22 --> Bucket25
    Bucket25 --> Bucket26
    Bucket26 --> Bucket27 & Bucket28

    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant381{{"Constant[381∈0] ➊<br />ᐸ4ᐳ"}}:::plan
    Constant381 --> Connection13
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection25{{"Connection[25∈0] ➊<br />ᐸ21ᐳ"}}:::plan
    Constant41{{"Constant[41∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant165{{"Constant[165∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant173{{"Constant[173∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant242{{"Constant[242∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant250{{"Constant[250∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant315{{"Constant[315∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant323{{"Constant[323∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    PgSelect15[["PgSelect[15∈1] ➊<br />ᐸpeopleᐳ"]]:::plan
    Object12 & Connection13 & Constant381 --> PgSelect15
    PgSelectRows16[["PgSelectRows[16∈1] ➊"]]:::plan
    PgSelect15 --> PgSelectRows16
    __Item17[/"__Item[17∈2]<br />ᐸ16ᐳ"\]:::itemplan
    PgSelectRows16 ==> __Item17
    PgSelectSingle18{{"PgSelectSingle[18∈2]<br />ᐸpeopleᐳ"}}:::plan
    __Item17 --> PgSelectSingle18
    PgUnionAll26[["PgUnionAll[26∈3]<br />ᐸAwsApplication,GcpApplicationᐳ"]]:::plan
    PgClassExpression19{{"PgClassExpression[19∈3]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Object12 & PgClassExpression19 & Connection25 --> PgUnionAll26
    PgUnionAll31[["PgUnionAll[31∈3]<br />ᐸAwsApplication,GcpApplicationᐳ"]]:::plan
    Object12 & PgClassExpression19 & Connection25 --> PgUnionAll31
    PgUnionAll32[["PgUnionAll[32∈3]<br />ᐸAwsApplication,GcpApplicationᐳ"]]:::plan
    Object12 & PgClassExpression19 & Connection25 --> PgUnionAll32
    PgSelectSingle18 --> PgClassExpression19
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression20
    First27{{"First[27∈3]"}}:::plan
    Access370{{"Access[370∈3]<br />ᐸ26.itemsᐳ"}}:::plan
    Access370 --> First27
    PgClassExpression30{{"PgClassExpression[30∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    First27 --> PgClassExpression30
    PgUnionAll26 --> Access370
    Access371{{"Access[371∈3]<br />ᐸ31.itemsᐳ"}}:::plan
    PgUnionAll31 --> Access371
    Access380{{"Access[380∈3]<br />ᐸ32.itemsᐳ"}}:::plan
    PgUnionAll32 --> Access380
    __Item35[/"__Item[35∈4]<br />ᐸ371ᐳ"\]:::itemplan
    Access371 ==> __Item35
    Access73{{"Access[73∈4]<br />ᐸ31.cursorDetailsᐳ"}}:::plan
    PgUnionAll31 --> Access73
    List128{{"List[128∈6]<br />ᐸ125,126,41ᐳ"}}:::plan
    Access125{{"Access[125∈6]<br />ᐸ35.0ᐳ"}}:::plan
    Access126{{"Access[126∈6]<br />ᐸ35.1ᐳ"}}:::plan
    Access125 & Access126 & Constant41 --> List128
    PgCursor74{{"PgCursor[74∈6]"}}:::plan
    __Item35 & Access73 --> PgCursor74
    __Item35 --> Access125
    __Item35 --> Access126
    Lambda129{{"Lambda[129∈6]<br />ᐸtoSpecifierᐳ"}}:::plan
    List128 --> Lambda129
    Access130{{"Access[130∈6]<br />ᐸ129.__typenameᐳ"}}:::plan
    Lambda129 --> Access130
    Access131{{"Access[131∈6]<br />ᐸ129.idᐳ"}}:::plan
    Lambda129 --> Access131
    PgSelect133[["PgSelect[133∈8]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Object12 & Access131 --> PgSelect133
    PgSelect147[["PgSelect[147∈8]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & Access131 --> PgSelect147
    First141{{"First[141∈8]^"}}:::plan
    PgSelectRows142[["PgSelectRows[142∈8]^"]]:::plan
    PgSelectRows142 --> First141
    PgSelect133 --> PgSelectRows142
    PgSelectSingle144{{"PgSelectSingle[144∈8]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First141 --> PgSelectSingle144
    First155{{"First[155∈8]^"}}:::plan
    PgSelectRows156[["PgSelectRows[156∈8]^"]]:::plan
    PgSelectRows156 --> First155
    PgSelect147 --> PgSelectRows156
    PgSelectSingle158{{"PgSelectSingle[158∈8]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First155 --> PgSelectSingle158
    PgClassExpression208{{"PgClassExpression[208∈8]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle144 --> PgClassExpression208
    PgClassExpression209{{"PgClassExpression[209∈8]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle158 --> PgClassExpression209
    List42{{"List[42∈5]<br />ᐸ39,40,41ᐳ"}}:::plan
    Access39{{"Access[39∈5]<br />ᐸ37.0ᐳ"}}:::plan
    Access40{{"Access[40∈5]<br />ᐸ37.1ᐳ"}}:::plan
    Access39 & Access40 & Constant41 --> List42
    __Item37[/"__Item[37∈5]<br />ᐸ380ᐳ"\]:::itemplan
    Access380 ==> __Item37
    __Item37 --> Access39
    __Item37 --> Access40
    Lambda43{{"Lambda[43∈5]<br />ᐸtoSpecifierᐳ"}}:::plan
    List42 --> Lambda43
    Access44{{"Access[44∈5]<br />ᐸ43.__typenameᐳ"}}:::plan
    Lambda43 --> Access44
    Access45{{"Access[45∈5]<br />ᐸ43.idᐳ"}}:::plan
    Lambda43 --> Access45
    PgUnionAll80[["PgUnionAll[80∈7]^<br />ᐸPerson,Organizationᐳ"]]:::plan
    PgClassExpression78{{"PgClassExpression[78∈7]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression79{{"PgClassExpression[79∈7]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object12 & PgClassExpression78 & PgClassExpression79 --> PgUnionAll80
    PgUnionAll105[["PgUnionAll[105∈7]^<br />ᐸPerson,Organizationᐳ"]]:::plan
    PgClassExpression103{{"PgClassExpression[103∈7]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression104{{"PgClassExpression[104∈7]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object12 & PgClassExpression103 & PgClassExpression104 --> PgUnionAll105
    PgSelect47[["PgSelect[47∈7]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Object12 & Access45 --> PgSelect47
    PgSelect61[["PgSelect[61∈7]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & Access45 --> PgSelect61
    PgUnionAll89[["PgUnionAll[89∈7]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳAwsApplication"]]:::plan
    __DataOnly92["__DataOnly[92∈7]<br />ᐸ76,101ᐳ<br />ᐳAwsApplication<br />ᐳGcpApplication"]:::plan
    Object12 & __DataOnly92 --> PgUnionAll89
    PgClassExpression76{{"PgClassExpression[76∈7]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression101{{"PgClassExpression[101∈7]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression76 -->|"trapError;trapInhibited"| __DataOnly92
    PgClassExpression101 --> __DataOnly92
    PgUnionAll114[["PgUnionAll[114∈7]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & __DataOnly92 --> PgUnionAll114
    First55{{"First[55∈7]^"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈7]^"]]:::plan
    PgSelectRows56 --> First55
    PgSelect47 --> PgSelectRows56
    PgSelectSingle58{{"PgSelectSingle[58∈7]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First55 --> PgSelectSingle58
    First69{{"First[69∈7]^"}}:::plan
    PgSelectRows70[["PgSelectRows[70∈7]^"]]:::plan
    PgSelectRows70 --> First69
    PgSelect61 --> PgSelectRows70
    PgSelectSingle72{{"PgSelectSingle[72∈7]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First69 --> PgSelectSingle72
    PgClassExpression75{{"PgClassExpression[75∈7]^<br />ᐸ__aws_appl..._.”aws_id”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression75
    PgSelectSingle58 --> PgClassExpression76
    PgClassExpression77{{"PgClassExpression[77∈7]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression77
    PgSelectSingle58 --> PgClassExpression78
    PgSelectSingle58 --> PgClassExpression79
    First85{{"First[85∈7]^"}}:::plan
    Access376{{"Access[376∈7]^<br />ᐸ80.itemsᐳ"}}:::plan
    Access376 --> First85
    PgClassExpression100{{"PgClassExpression[100∈7]^<br />ᐸ__gcp_appl..._.”gcp_id”ᐳ"}}:::plan
    PgSelectSingle72 --> PgClassExpression100
    PgSelectSingle72 --> PgClassExpression101
    PgClassExpression102{{"PgClassExpression[102∈7]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle72 --> PgClassExpression102
    PgSelectSingle72 --> PgClassExpression103
    PgSelectSingle72 --> PgClassExpression104
    First110{{"First[110∈7]^"}}:::plan
    Access379{{"Access[379∈7]^<br />ᐸ105.itemsᐳ"}}:::plan
    Access379 --> First110
    PgUnionAll80 --> Access376
    PgUnionAll105 --> Access379
    Connection99{{"Connection[99∈7] ➊<br />ᐸ94ᐳ<br />ᐳAwsApplication"}}:::plan
    Connection124{{"Connection[124∈7] ➊<br />ᐸ119ᐳ<br />ᐳGcpApplication"}}:::plan
    List166{{"List[166∈9]^<br />ᐸ161,163,165ᐳ"}}:::plan
    Access161{{"Access[161∈9]<br />ᐸ85.0ᐳ<br />ᐳAwsApplication"}}:::plan
    Access163{{"Access[163∈9]<br />ᐸ85.1ᐳ<br />ᐳAwsApplication"}}:::plan
    Access161 & Access163 & Constant165 --> List166
    PgUnionAll212[["PgUnionAll[212∈9]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳAwsApplication"]]:::plan
    Object12 & PgClassExpression76 & Connection99 --> PgUnionAll212
    PgUnionAll218[["PgUnionAll[218∈9]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳAwsApplication"]]:::plan
    Object12 & PgClassExpression76 & Connection99 --> PgUnionAll218
    First85 --> Access161
    First85 --> Access163
    Lambda167{{"Lambda[167∈9]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List166 --> Lambda167
    First213{{"First[213∈9]^"}}:::plan
    Access374{{"Access[374∈9]^<br />ᐸ212.itemsᐳ"}}:::plan
    Access374 --> First213
    PgClassExpression217{{"PgClassExpression[217∈9]^<br />ᐸcount(*)ᐳ"}}:::plan
    First213 --> PgClassExpression217
    Access372{{"Access[372∈9]<br />ᐸ89.itemsᐳ<br />ᐳAwsApplication"}}:::plan
    PgUnionAll89 --> Access372
    PgUnionAll212 --> Access374
    Access375{{"Access[375∈9]^<br />ᐸ218.itemsᐳ"}}:::plan
    PgUnionAll218 --> Access375
    Access178{{"Access[178∈11]^<br />ᐸ177.__typenameᐳ"}}:::plan
    __Value177:::plan@{shape: docs, label: "__Combined[177∈11]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value177 --> Access178
    PgSelect182[["PgSelect[182∈12]^<br />ᐸorganizationsᐳ"]]:::plan
    Access180{{"Access[180∈12]<br />ᐸ177.organization_idᐳ<br />ᐳAwsApplicationᐳOrganization<br />ᐳGcpApplicationᐳOrganization"}}:::plan
    Object12 & Access180 --> PgSelect182
    PgSelect196[["PgSelect[196∈12]^<br />ᐸpeopleᐳ"]]:::plan
    Access194{{"Access[194∈12]<br />ᐸ177.person_idᐳ<br />ᐳAwsApplicationᐳPerson<br />ᐳGcpApplicationᐳPerson"}}:::plan
    Object12 & Access194 --> PgSelect196
    __Value177 --> Access180
    First190{{"First[190∈12]^"}}:::plan
    PgSelectRows191[["PgSelectRows[191∈12]^"]]:::plan
    PgSelectRows191 --> First190
    PgSelect182 --> PgSelectRows191
    PgSelectSingle193{{"PgSelectSingle[193∈12]^<br />ᐸorganizationsᐳ"}}:::plan
    First190 --> PgSelectSingle193
    __Value177 --> Access194
    First204{{"First[204∈12]^"}}:::plan
    PgSelectRows205[["PgSelectRows[205∈12]^"]]:::plan
    PgSelectRows205 --> First204
    PgSelect196 --> PgSelectRows205
    PgSelectSingle207{{"PgSelectSingle[207∈12]^<br />ᐸpeopleᐳ"}}:::plan
    First204 --> PgSelectSingle207
    PgClassExpression228{{"PgClassExpression[228∈12]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle193 --> PgClassExpression228
    PgClassExpression229{{"PgClassExpression[229∈12]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle193 --> PgClassExpression229
    PgClassExpression230{{"PgClassExpression[230∈12]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle207 --> PgClassExpression230
    PgClassExpression231{{"PgClassExpression[231∈12]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle207 --> PgClassExpression231
    List243{{"List[243∈13]^<br />ᐸ238,240,242ᐳ"}}:::plan
    Access238{{"Access[238∈13]^<br />ᐸ210.0ᐳ"}}:::plan
    Access240{{"Access[240∈13]^<br />ᐸ210.1ᐳ"}}:::plan
    Access238 & Access240 & Constant242 --> List243
    __Item210[/"__Item[210∈13]<br />ᐸ372ᐳ<br />ᐳAwsApplication"\]:::itemplan
    Access372 ==> __Item210
    __Item210 --> Access238
    __Item210 --> Access240
    Lambda244{{"Lambda[244∈13]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List243 --> Lambda244
    Access255{{"Access[255∈17]^<br />ᐸ254.__typenameᐳ"}}:::plan
    __Value254:::plan@{shape: docs, label: "__Combined[254∈17]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value254 --> Access255
    Access257{{"Access[257∈17]^<br />ᐸ254.idᐳ"}}:::plan
    __Value254 --> Access257
    PgSelect259[["PgSelect[259∈18]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Object12 & Access257 --> PgSelect259
    PgSelect273[["PgSelect[273∈18]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Object12 & Access257 --> PgSelect273
    First267{{"First[267∈18]^"}}:::plan
    PgSelectRows268[["PgSelectRows[268∈18]^"]]:::plan
    PgSelectRows268 --> First267
    PgSelect259 --> PgSelectRows268
    PgSelectSingle270{{"PgSelectSingle[270∈18]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First267 --> PgSelectSingle270
    First281{{"First[281∈18]^"}}:::plan
    PgSelectRows282[["PgSelectRows[282∈18]^"]]:::plan
    PgSelectRows282 --> First281
    PgSelect273 --> PgSelectRows282
    PgSelectSingle284{{"PgSelectSingle[284∈18]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First281 --> PgSelectSingle284
    PgClassExpression289{{"PgClassExpression[289∈18]^<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle270 --> PgClassExpression289
    PgClassExpression290{{"PgClassExpression[290∈18]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle270 --> PgClassExpression290
    PgClassExpression291{{"PgClassExpression[291∈18]^<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle270 --> PgClassExpression291
    PgClassExpression292{{"PgClassExpression[292∈18]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle270 --> PgClassExpression292
    PgClassExpression293{{"PgClassExpression[293∈18]^<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression293
    PgClassExpression294{{"PgClassExpression[294∈18]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression294
    PgClassExpression295{{"PgClassExpression[295∈18]^<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression295
    PgClassExpression296{{"PgClassExpression[296∈18]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle284 --> PgClassExpression296
    __Item285[/"__Item[285∈19]<br />ᐸ375ᐳ<br />ᐳAwsApplication"\]:::itemplan
    Access375 ==> __Item285
    Access305{{"Access[305∈19]<br />ᐸ218.cursorDetailsᐳ<br />ᐳAwsApplication"}}:::plan
    PgUnionAll218 --> Access305
    List316{{"List[316∈21]^<br />ᐸ311,313,315ᐳ"}}:::plan
    Access311{{"Access[311∈21]<br />ᐸ285.0ᐳ<br />ᐳAwsApplication"}}:::plan
    Access313{{"Access[313∈21]<br />ᐸ285.1ᐳ<br />ᐳAwsApplication"}}:::plan
    Access311 & Access313 & Constant315 --> List316
    PgCursor307{{"PgCursor[307∈21]<br />ᐳAwsApplication"}}:::plan
    __Item285 & Access305 --> PgCursor307
    __Item285 --> Access311
    __Item285 --> Access313
    Lambda317{{"Lambda[317∈21]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List316 --> Lambda317
    Access328{{"Access[328∈25]^<br />ᐸ327.__typenameᐳ"}}:::plan
    __Value327:::plan@{shape: docs, label: "__Combined[327∈25]<br />ᐳAwsApplication<br />ᐳGcpApplication"}
    __Value327 --> Access328
    Access330{{"Access[330∈25]^<br />ᐸ327.idᐳ"}}:::plan
    __Value327 --> Access330
    PgSelect332[["PgSelect[332∈26]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Object12 & Access330 --> PgSelect332
    PgSelect346[["PgSelect[346∈26]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Object12 & Access330 --> PgSelect346
    First340{{"First[340∈26]^"}}:::plan
    PgSelectRows341[["PgSelectRows[341∈26]^"]]:::plan
    PgSelectRows341 --> First340
    PgSelect332 --> PgSelectRows341
    PgSelectSingle343{{"PgSelectSingle[343∈26]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First340 --> PgSelectSingle343
    First354{{"First[354∈26]^"}}:::plan
    PgSelectRows355[["PgSelectRows[355∈26]^"]]:::plan
    PgSelectRows355 --> First354
    PgSelect346 --> PgSelectRows355
    PgSelectSingle357{{"PgSelectSingle[357∈26]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First354 --> PgSelectSingle357
    PgClassExpression358{{"PgClassExpression[358∈26]^<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle343 --> PgClassExpression358
    PgClassExpression359{{"PgClassExpression[359∈26]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle343 --> PgClassExpression359
    PgClassExpression360{{"PgClassExpression[360∈26]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle343 --> PgClassExpression360
    PgClassExpression361{{"PgClassExpression[361∈26]^<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle357 --> PgClassExpression361
    PgClassExpression362{{"PgClassExpression[362∈26]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle357 --> PgClassExpression362
    PgClassExpression363{{"PgClassExpression[363∈26]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle357 --> PgClassExpression363
    List174{{"List[174∈10]^<br />ᐸ169,171,173ᐳ"}}:::plan
    Access169{{"Access[169∈10]<br />ᐸ110.0ᐳ<br />ᐳGcpApplication"}}:::plan
    Access171{{"Access[171∈10]<br />ᐸ110.1ᐳ<br />ᐳGcpApplication"}}:::plan
    Access169 & Access171 & Constant173 --> List174
    PgUnionAll221[["PgUnionAll[221∈10]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & PgClassExpression101 & Connection124 --> PgUnionAll221
    PgUnionAll227[["PgUnionAll[227∈10]<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />ᐳGcpApplication"]]:::plan
    Object12 & PgClassExpression101 & Connection124 --> PgUnionAll227
    First110 --> Access169
    First110 --> Access171
    Lambda175{{"Lambda[175∈10]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List174 --> Lambda175
    First222{{"First[222∈10]^"}}:::plan
    Access377{{"Access[377∈10]^<br />ᐸ221.itemsᐳ"}}:::plan
    Access377 --> First222
    PgClassExpression226{{"PgClassExpression[226∈10]^<br />ᐸcount(*)ᐳ"}}:::plan
    First222 --> PgClassExpression226
    Access373{{"Access[373∈10]<br />ᐸ114.itemsᐳ<br />ᐳGcpApplication"}}:::plan
    PgUnionAll114 --> Access373
    PgUnionAll221 --> Access377
    Access378{{"Access[378∈10]^<br />ᐸ227.itemsᐳ"}}:::plan
    PgUnionAll227 --> Access378
    List251{{"List[251∈14]^<br />ᐸ246,248,250ᐳ"}}:::plan
    Access246{{"Access[246∈14]^<br />ᐸ219.0ᐳ"}}:::plan
    Access248{{"Access[248∈14]^<br />ᐸ219.1ᐳ"}}:::plan
    Access246 & Access248 & Constant250 --> List251
    __Item219[/"__Item[219∈14]<br />ᐸ373ᐳ<br />ᐳGcpApplication"\]:::itemplan
    Access373 ==> __Item219
    __Item219 --> Access246
    __Item219 --> Access248
    Lambda252{{"Lambda[252∈14]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List251 --> Lambda252
    __Item287[/"__Item[287∈20]<br />ᐸ378ᐳ<br />ᐳGcpApplication"\]:::itemplan
    Access378 ==> __Item287
    Access308{{"Access[308∈20]<br />ᐸ227.cursorDetailsᐳ<br />ᐳGcpApplication"}}:::plan
    PgUnionAll227 --> Access308
    List324{{"List[324∈22]^<br />ᐸ319,321,323ᐳ"}}:::plan
    Access319{{"Access[319∈22]<br />ᐸ287.0ᐳ<br />ᐳGcpApplication"}}:::plan
    Access321{{"Access[321∈22]<br />ᐸ287.1ᐳ<br />ᐳGcpApplication"}}:::plan
    Access319 & Access321 & Constant323 --> List324
    PgCursor310{{"PgCursor[310∈22]<br />ᐳGcpApplication"}}:::plan
    __Item287 & Access308 --> PgCursor310
    __Item287 --> Access319
    __Item287 --> Access321
    Lambda325{{"Lambda[325∈22]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List324 --> Lambda325

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13,Connection25,Constant41,Constant165,Constant173,Constant242,Constant250,Constant315,Constant323,Constant381 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect15,PgSelectRows16 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item17,PgSelectSingle18 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression19,PgClassExpression20,PgUnionAll26,First27,PgClassExpression30,PgUnionAll31,PgUnionAll32,Access370,Access371,Access380 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item35,Access73 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item37,Access39,Access40,List42,Lambda43,Access44,Access45 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgCursor74,Access125,Access126,List128,Lambda129,Access130,Access131 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect47,First55,PgSelectRows56,PgSelectSingle58,PgSelect61,First69,PgSelectRows70,PgSelectSingle72,PgClassExpression75,PgClassExpression76,PgClassExpression77,PgClassExpression78,PgClassExpression79,PgUnionAll80,First85,PgUnionAll89,__DataOnly92,Connection99,PgClassExpression100,PgClassExpression101,PgClassExpression102,PgClassExpression103,PgClassExpression104,PgUnionAll105,First110,PgUnionAll114,Connection124,Access376,Access379 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect133,First141,PgSelectRows142,PgSelectSingle144,PgSelect147,First155,PgSelectRows156,PgSelectSingle158,PgClassExpression208,PgClassExpression209 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,Access161,Access163,List166,Lambda167,PgUnionAll212,First213,PgClassExpression217,PgUnionAll218,Access372,Access374,Access375 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,Access169,Access171,List174,Lambda175,PgUnionAll221,First222,PgClassExpression226,PgUnionAll227,Access373,Access377,Access378 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,__Value177,Access178 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,Access180,PgSelect182,First190,PgSelectRows191,PgSelectSingle193,Access194,PgSelect196,First204,PgSelectRows205,PgSelectSingle207,PgClassExpression228,PgClassExpression229,PgClassExpression230,PgClassExpression231 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,__Item210,Access238,Access240,List243,Lambda244 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,__Item219,Access246,Access248,List251,Lambda252 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Value254,Access255,Access257 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,PgSelect259,First267,PgSelectRows268,PgSelectSingle270,PgSelect273,First281,PgSelectRows282,PgSelectSingle284,PgClassExpression289,PgClassExpression290,PgClassExpression291,PgClassExpression292,PgClassExpression293,PgClassExpression294,PgClassExpression295,PgClassExpression296 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item285,Access305 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,__Item287,Access308 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,PgCursor307,Access311,Access313,List316,Lambda317 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgCursor310,Access319,Access321,List324,Lambda325 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,__Value327,Access328,Access330 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect332,First340,PgSelectRows341,PgSelectSingle343,PgSelect346,First354,PgSelectRows355,PgSelectSingle357,PgClassExpression358,PgClassExpression359,PgClassExpression360,PgClassExpression361,PgClassExpression362,PgClassExpression363 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28 bucket28

    Lambda167 -.-x __Value177
    Lambda175 -.-x __Value177
    Lambda244 -.-x __Value254
    Lambda252 -.-x __Value254
    Lambda317 -.-x __Value327
    Lambda325 -.-x __Value327
