%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object18{{"Object[18∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access16{{"Access[16∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access17{{"Access[17∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Access16 & Access17 --> Object18
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value3 --> Access16
    __Value3 --> Access17
    Connection19{{"Connection[19∈0]<br />ᐸ15ᐳ"}}:::plan
    Constant336{{"Constant[336∈0]<br />ᐸ4ᐳ"}}:::plan
    Constant336 --> Connection19
    __Value0["__Value[0∈0]"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    PgSelect20[["PgSelect[20∈1]<br />ᐸpeopleᐳ"]]:::plan
    Object18 & Connection19 --> PgSelect20
    Connection39{{"Connection[39∈1]<br />ᐸ35ᐳ"}}:::plan
    __Item21[/"__Item[21∈2]<br />ᐸ20ᐳ"\]:::itemplan
    PgSelect20 ==> __Item21
    PgSelectSingle22{{"PgSelectSingle[22∈2]<br />ᐸpeopleᐳ"}}:::plan
    __Item21 --> PgSelectSingle22
    PgUnionAll40[["PgUnionAll[40∈3]"]]:::plan
    PgClassExpression23{{"PgClassExpression[23∈3]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Object18 & PgClassExpression23 & PgClassExpression23 & Connection39 --> PgUnionAll40
    PgUnionAll44[["PgUnionAll[44∈3]"]]:::plan
    Object18 & PgClassExpression23 & PgClassExpression23 & Connection39 --> PgUnionAll44
    PgUnionAll71[["PgUnionAll[71∈3]"]]:::plan
    Object18 & PgClassExpression23 & PgClassExpression23 & Connection39 --> PgUnionAll71
    PgSelectSingle22 --> PgClassExpression23
    PgClassExpression24{{"PgClassExpression[24∈3]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle22 --> PgClassExpression24
    First41{{"First[41∈3]"}}:::plan
    PgUnionAll40 --> First41
    PgUnionAllSingle42["PgUnionAllSingle[42∈3]"]:::plan
    First41 --> PgUnionAllSingle42
    PgClassExpression43{{"PgClassExpression[43∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle42 --> PgClassExpression43
    __Item45[/"__Item[45∈4]<br />ᐸ44ᐳ"\]:::itemplan
    PgUnionAll44 ==> __Item45
    PgUnionAllSingle46["PgUnionAllSingle[46∈4]"]:::plan
    __Item45 --> PgUnionAllSingle46
    List50{{"List[50∈5]<br />ᐸ48,49ᐳ"}}:::plan
    Access48{{"Access[48∈5]<br />ᐸ46.0ᐳ"}}:::plan
    Access49{{"Access[49∈5]<br />ᐸ46.1ᐳ"}}:::plan
    Access48 & Access49 --> List50
    PgCursor47{{"PgCursor[47∈5]"}}:::plan
    List50 --> PgCursor47
    PgUnionAllSingle46 --> Access48
    PgUnionAllSingle46 --> Access49
    PgSelect54[["PgSelect[54∈6]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Access53{{"Access[53∈6]<br />ᐸ52.0ᐳ"}}:::plan
    Object18 & Access53 --> PgSelect54
    PgSelect64[["PgSelect[64∈6]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Access63{{"Access[63∈6]<br />ᐸ62.0ᐳ"}}:::plan
    Object18 & Access63 --> PgSelect64
    JSONParse52[["JSONParse[52∈6]<br />ᐸ49ᐳ<br />ᐳAwsApplication"]]:::plan
    Access49 --> JSONParse52
    JSONParse52 --> Access53
    First58{{"First[58∈6]"}}:::plan
    PgSelect54 --> First58
    PgSelectSingle59{{"PgSelectSingle[59∈6]<br />ᐸaws_applicationsᐳ"}}:::plan
    First58 --> PgSelectSingle59
    PgClassExpression60{{"PgClassExpression[60∈6]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle59 --> PgClassExpression60
    JSONParse62[["JSONParse[62∈6]<br />ᐸ49ᐳ<br />ᐳGcpApplication"]]:::plan
    Access49 --> JSONParse62
    JSONParse62 --> Access63
    First68{{"First[68∈6]"}}:::plan
    PgSelect64 --> First68
    PgSelectSingle69{{"PgSelectSingle[69∈6]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First68 --> PgSelectSingle69
    PgClassExpression70{{"PgClassExpression[70∈6]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgSelectSingle69 --> PgClassExpression70
    __Item72[/"__Item[72∈7]<br />ᐸ71ᐳ"\]:::itemplan
    PgUnionAll71 ==> __Item72
    PgUnionAllSingle73["PgUnionAllSingle[73∈7]"]:::plan
    __Item72 --> PgUnionAllSingle73
    Access74{{"Access[74∈7]<br />ᐸ73.1ᐳ"}}:::plan
    PgUnionAllSingle73 --> Access74
    PgUnionAll170[["PgUnionAll[170∈8]<br />ᐳAwsApplication"]]:::plan
    PgClassExpression84{{"PgClassExpression[84∈8]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Connection169{{"Connection[169∈8]<br />ᐸ165ᐳ<br />ᐳAwsApplication"}}:::plan
    Object18 & PgClassExpression84 & PgClassExpression84 & Connection169 --> PgUnionAll170
    PgUnionAll174[["PgUnionAll[174∈8]<br />ᐳAwsApplication"]]:::plan
    Object18 & PgClassExpression84 & PgClassExpression84 & Connection169 --> PgUnionAll174
    PgUnionAll301[["PgUnionAll[301∈8]<br />ᐳGcpApplication"]]:::plan
    PgClassExpression215{{"PgClassExpression[215∈8]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Connection300{{"Connection[300∈8]<br />ᐸ296ᐳ<br />ᐳGcpApplication"}}:::plan
    Object18 & PgClassExpression215 & PgClassExpression215 & Connection300 --> PgUnionAll301
    PgUnionAll305[["PgUnionAll[305∈8]<br />ᐳGcpApplication"]]:::plan
    Object18 & PgClassExpression215 & PgClassExpression215 & Connection300 --> PgUnionAll305
    PgUnionAll88[["PgUnionAll[88∈8]<br />ᐳAwsApplication"]]:::plan
    PgClassExpression86{{"PgClassExpression[86∈8]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression87{{"PgClassExpression[87∈8]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object18 & PgClassExpression86 & PgClassExpression87 --> PgUnionAll88
    PgUnionAll123[["PgUnionAll[123∈8]<br />ᐳAwsApplication"]]:::plan
    Object18 & PgClassExpression84 & PgClassExpression84 --> PgUnionAll123
    PgUnionAll219[["PgUnionAll[219∈8]<br />ᐳGcpApplication"]]:::plan
    PgClassExpression217{{"PgClassExpression[217∈8]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression218{{"PgClassExpression[218∈8]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object18 & PgClassExpression217 & PgClassExpression218 --> PgUnionAll219
    PgUnionAll254[["PgUnionAll[254∈8]<br />ᐳGcpApplication"]]:::plan
    Object18 & PgClassExpression215 & PgClassExpression215 --> PgUnionAll254
    PgSelect77[["PgSelect[77∈8]<br />ᐸaws_applicationsᐳ<br />ᐳAwsApplication"]]:::plan
    Access76{{"Access[76∈8]<br />ᐸ75.0ᐳ"}}:::plan
    Object18 & Access76 --> PgSelect77
    PgSelect208[["PgSelect[208∈8]<br />ᐸgcp_applicationsᐳ<br />ᐳGcpApplication"]]:::plan
    Access207{{"Access[207∈8]<br />ᐸ206.0ᐳ"}}:::plan
    Object18 & Access207 --> PgSelect208
    JSONParse75[["JSONParse[75∈8]<br />ᐸ74ᐳ<br />ᐳAwsApplication"]]:::plan
    Access74 --> JSONParse75
    JSONParse75 --> Access76
    First81{{"First[81∈8]"}}:::plan
    PgSelect77 --> First81
    PgSelectSingle82{{"PgSelectSingle[82∈8]<br />ᐸaws_applicationsᐳ"}}:::plan
    First81 --> PgSelectSingle82
    PgClassExpression83{{"PgClassExpression[83∈8]<br />ᐸ__aws_appl..._.”aws_id”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression83
    PgSelectSingle82 --> PgClassExpression84
    PgClassExpression85{{"PgClassExpression[85∈8]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle82 --> PgClassExpression85
    PgSelectSingle82 --> PgClassExpression86
    PgSelectSingle82 --> PgClassExpression87
    First92{{"First[92∈8]"}}:::plan
    PgUnionAll88 --> First92
    PgUnionAllSingle93["PgUnionAllSingle[93∈8]"]:::plan
    First92 --> PgUnionAllSingle93
    Access94{{"Access[94∈8]<br />ᐸ93.1ᐳ"}}:::plan
    PgUnionAllSingle93 --> Access94
    First171{{"First[171∈8]"}}:::plan
    PgUnionAll170 --> First171
    PgUnionAllSingle172["PgUnionAllSingle[172∈8]"]:::plan
    First171 --> PgUnionAllSingle172
    PgClassExpression173{{"PgClassExpression[173∈8]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle172 --> PgClassExpression173
    JSONParse206[["JSONParse[206∈8]<br />ᐸ74ᐳ<br />ᐳGcpApplication"]]:::plan
    Access74 --> JSONParse206
    JSONParse206 --> Access207
    First212{{"First[212∈8]"}}:::plan
    PgSelect208 --> First212
    PgSelectSingle213{{"PgSelectSingle[213∈8]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First212 --> PgSelectSingle213
    PgClassExpression214{{"PgClassExpression[214∈8]<br />ᐸ__gcp_appl..._.”gcp_id”ᐳ"}}:::plan
    PgSelectSingle213 --> PgClassExpression214
    PgSelectSingle213 --> PgClassExpression215
    PgClassExpression216{{"PgClassExpression[216∈8]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle213 --> PgClassExpression216
    PgSelectSingle213 --> PgClassExpression217
    PgSelectSingle213 --> PgClassExpression218
    First223{{"First[223∈8]"}}:::plan
    PgUnionAll219 --> First223
    PgUnionAllSingle224["PgUnionAllSingle[224∈8]"]:::plan
    First223 --> PgUnionAllSingle224
    Access225{{"Access[225∈8]<br />ᐸ224.1ᐳ"}}:::plan
    PgUnionAllSingle224 --> Access225
    First302{{"First[302∈8]"}}:::plan
    PgUnionAll301 --> First302
    PgUnionAllSingle303["PgUnionAllSingle[303∈8]"]:::plan
    First302 --> PgUnionAllSingle303
    PgClassExpression304{{"PgClassExpression[304∈8]<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle303 --> PgClassExpression304
    PgSelect97[["PgSelect[97∈9]<br />ᐸorganizationsᐳ<br />ᐳAwsApplicationᐳOrganization"]]:::plan
    Access96{{"Access[96∈9]<br />ᐸ95.0ᐳ"}}:::plan
    Object18 & Access96 --> PgSelect97
    PgSelect108[["PgSelect[108∈9]<br />ᐸpeopleᐳ<br />ᐳAwsApplicationᐳPerson"]]:::plan
    Access107{{"Access[107∈9]<br />ᐸ106.0ᐳ"}}:::plan
    Object18 & Access107 --> PgSelect108
    JSONParse95[["JSONParse[95∈9]<br />ᐸ94ᐳ<br />ᐳAwsApplicationᐳOrganization"]]:::plan
    Access94 --> JSONParse95
    JSONParse95 --> Access96
    First101{{"First[101∈9]"}}:::plan
    PgSelect97 --> First101
    PgSelectSingle102{{"PgSelectSingle[102∈9]<br />ᐸorganizationsᐳ"}}:::plan
    First101 --> PgSelectSingle102
    PgClassExpression103{{"PgClassExpression[103∈9]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression103
    PgClassExpression104{{"PgClassExpression[104∈9]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression104
    JSONParse106[["JSONParse[106∈9]<br />ᐸ94ᐳ<br />ᐳAwsApplicationᐳPerson"]]:::plan
    Access94 --> JSONParse106
    JSONParse106 --> Access107
    First112{{"First[112∈9]"}}:::plan
    PgSelect108 --> First112
    PgSelectSingle113{{"PgSelectSingle[113∈9]<br />ᐸpeopleᐳ"}}:::plan
    First112 --> PgSelectSingle113
    PgClassExpression114{{"PgClassExpression[114∈9]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle113 --> PgClassExpression114
    PgClassExpression115{{"PgClassExpression[115∈9]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle113 --> PgClassExpression115
    __Item127[/"__Item[127∈10]<br />ᐸ123ᐳ"\]:::itemplan
    PgUnionAll123 ==> __Item127
    PgUnionAllSingle128["PgUnionAllSingle[128∈10]"]:::plan
    __Item127 --> PgUnionAllSingle128
    Access129{{"Access[129∈10]<br />ᐸ128.1ᐳ"}}:::plan
    PgUnionAllSingle128 --> Access129
    PgSelect132[["PgSelect[132∈11]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access131{{"Access[131∈11]<br />ᐸ130.0ᐳ"}}:::plan
    Object18 & Access131 --> PgSelect132
    PgSelect145[["PgSelect[145∈11]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access144{{"Access[144∈11]<br />ᐸ143.0ᐳ"}}:::plan
    Object18 & Access144 --> PgSelect145
    JSONParse130[["JSONParse[130∈11]<br />ᐸ129ᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access129 --> JSONParse130
    JSONParse130 --> Access131
    First136{{"First[136∈11]"}}:::plan
    PgSelect132 --> First136
    PgSelectSingle137{{"PgSelectSingle[137∈11]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First136 --> PgSelectSingle137
    PgClassExpression138{{"PgClassExpression[138∈11]<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle137 --> PgClassExpression138
    PgClassExpression139{{"PgClassExpression[139∈11]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle137 --> PgClassExpression139
    PgClassExpression140{{"PgClassExpression[140∈11]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle137 --> PgClassExpression140
    PgClassExpression141{{"PgClassExpression[141∈11]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle137 --> PgClassExpression141
    JSONParse143[["JSONParse[143∈11]<br />ᐸ129ᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access129 --> JSONParse143
    JSONParse143 --> Access144
    First149{{"First[149∈11]"}}:::plan
    PgSelect145 --> First149
    PgSelectSingle150{{"PgSelectSingle[150∈11]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First149 --> PgSelectSingle150
    PgClassExpression151{{"PgClassExpression[151∈11]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle150 --> PgClassExpression151
    PgClassExpression152{{"PgClassExpression[152∈11]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle150 --> PgClassExpression152
    PgClassExpression153{{"PgClassExpression[153∈11]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle150 --> PgClassExpression153
    PgClassExpression154{{"PgClassExpression[154∈11]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle150 --> PgClassExpression154
    __Item175[/"__Item[175∈12]<br />ᐸ174ᐳ"\]:::itemplan
    PgUnionAll174 ==> __Item175
    PgUnionAllSingle176["PgUnionAllSingle[176∈12]"]:::plan
    __Item175 --> PgUnionAllSingle176
    List180{{"List[180∈13]<br />ᐸ178,179ᐳ<br />ᐳAwsApplication"}}:::plan
    Access178{{"Access[178∈13]<br />ᐸ176.0ᐳ"}}:::plan
    Access179{{"Access[179∈13]<br />ᐸ176.1ᐳ"}}:::plan
    Access178 & Access179 --> List180
    PgCursor177{{"PgCursor[177∈13]"}}:::plan
    List180 --> PgCursor177
    PgUnionAllSingle176 --> Access178
    PgUnionAllSingle176 --> Access179
    PgSelect184[["PgSelect[184∈14]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access183{{"Access[183∈14]<br />ᐸ182.0ᐳ"}}:::plan
    Object18 & Access183 --> PgSelect184
    PgSelect196[["PgSelect[196∈14]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access195{{"Access[195∈14]<br />ᐸ194.0ᐳ"}}:::plan
    Object18 & Access195 --> PgSelect196
    JSONParse182[["JSONParse[182∈14]<br />ᐸ179ᐳ<br />ᐳAwsApplicationᐳFirstPartyVulnerability"]]:::plan
    Access179 --> JSONParse182
    JSONParse182 --> Access183
    First188{{"First[188∈14]"}}:::plan
    PgSelect184 --> First188
    PgSelectSingle189{{"PgSelectSingle[189∈14]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First188 --> PgSelectSingle189
    PgClassExpression190{{"PgClassExpression[190∈14]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle189 --> PgClassExpression190
    PgClassExpression191{{"PgClassExpression[191∈14]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle189 --> PgClassExpression191
    PgClassExpression192{{"PgClassExpression[192∈14]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle189 --> PgClassExpression192
    JSONParse194[["JSONParse[194∈14]<br />ᐸ179ᐳ<br />ᐳAwsApplicationᐳThirdPartyVulnerability"]]:::plan
    Access179 --> JSONParse194
    JSONParse194 --> Access195
    First200{{"First[200∈14]"}}:::plan
    PgSelect196 --> First200
    PgSelectSingle201{{"PgSelectSingle[201∈14]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First200 --> PgSelectSingle201
    PgClassExpression202{{"PgClassExpression[202∈14]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle201 --> PgClassExpression202
    PgClassExpression203{{"PgClassExpression[203∈14]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle201 --> PgClassExpression203
    PgClassExpression204{{"PgClassExpression[204∈14]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle201 --> PgClassExpression204
    PgSelect228[["PgSelect[228∈15]<br />ᐸorganizationsᐳ<br />ᐳGcpApplicationᐳOrganization"]]:::plan
    Access227{{"Access[227∈15]<br />ᐸ226.0ᐳ"}}:::plan
    Object18 & Access227 --> PgSelect228
    PgSelect239[["PgSelect[239∈15]<br />ᐸpeopleᐳ<br />ᐳGcpApplicationᐳPerson"]]:::plan
    Access238{{"Access[238∈15]<br />ᐸ237.0ᐳ"}}:::plan
    Object18 & Access238 --> PgSelect239
    JSONParse226[["JSONParse[226∈15]<br />ᐸ225ᐳ<br />ᐳGcpApplicationᐳOrganization"]]:::plan
    Access225 --> JSONParse226
    JSONParse226 --> Access227
    First232{{"First[232∈15]"}}:::plan
    PgSelect228 --> First232
    PgSelectSingle233{{"PgSelectSingle[233∈15]<br />ᐸorganizationsᐳ"}}:::plan
    First232 --> PgSelectSingle233
    PgClassExpression234{{"PgClassExpression[234∈15]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgSelectSingle233 --> PgClassExpression234
    PgClassExpression235{{"PgClassExpression[235∈15]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle233 --> PgClassExpression235
    JSONParse237[["JSONParse[237∈15]<br />ᐸ225ᐳ<br />ᐳGcpApplicationᐳPerson"]]:::plan
    Access225 --> JSONParse237
    JSONParse237 --> Access238
    First243{{"First[243∈15]"}}:::plan
    PgSelect239 --> First243
    PgSelectSingle244{{"PgSelectSingle[244∈15]<br />ᐸpeopleᐳ"}}:::plan
    First243 --> PgSelectSingle244
    PgClassExpression245{{"PgClassExpression[245∈15]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgSelectSingle244 --> PgClassExpression245
    PgClassExpression246{{"PgClassExpression[246∈15]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle244 --> PgClassExpression246
    __Item258[/"__Item[258∈16]<br />ᐸ254ᐳ"\]:::itemplan
    PgUnionAll254 ==> __Item258
    PgUnionAllSingle259["PgUnionAllSingle[259∈16]"]:::plan
    __Item258 --> PgUnionAllSingle259
    Access260{{"Access[260∈16]<br />ᐸ259.1ᐳ"}}:::plan
    PgUnionAllSingle259 --> Access260
    PgSelect263[["PgSelect[263∈17]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access262{{"Access[262∈17]<br />ᐸ261.0ᐳ"}}:::plan
    Object18 & Access262 --> PgSelect263
    PgSelect276[["PgSelect[276∈17]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access275{{"Access[275∈17]<br />ᐸ274.0ᐳ"}}:::plan
    Object18 & Access275 --> PgSelect276
    JSONParse261[["JSONParse[261∈17]<br />ᐸ260ᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access260 --> JSONParse261
    JSONParse261 --> Access262
    First267{{"First[267∈17]"}}:::plan
    PgSelect263 --> First267
    PgSelectSingle268{{"PgSelectSingle[268∈17]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First267 --> PgSelectSingle268
    PgClassExpression269{{"PgClassExpression[269∈17]<br />ᐸ__first_pa...team_name”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression269
    PgClassExpression270{{"PgClassExpression[270∈17]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression270
    PgClassExpression271{{"PgClassExpression[271∈17]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression271
    PgClassExpression272{{"PgClassExpression[272∈17]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle268 --> PgClassExpression272
    JSONParse274[["JSONParse[274∈17]<br />ᐸ260ᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access260 --> JSONParse274
    JSONParse274 --> Access275
    First280{{"First[280∈17]"}}:::plan
    PgSelect276 --> First280
    PgSelectSingle281{{"PgSelectSingle[281∈17]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First280 --> PgSelectSingle281
    PgClassExpression282{{"PgClassExpression[282∈17]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression282
    PgClassExpression283{{"PgClassExpression[283∈17]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression283
    PgClassExpression284{{"PgClassExpression[284∈17]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression284
    PgClassExpression285{{"PgClassExpression[285∈17]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression285
    __Item306[/"__Item[306∈18]<br />ᐸ305ᐳ"\]:::itemplan
    PgUnionAll305 ==> __Item306
    PgUnionAllSingle307["PgUnionAllSingle[307∈18]"]:::plan
    __Item306 --> PgUnionAllSingle307
    List311{{"List[311∈19]<br />ᐸ309,310ᐳ<br />ᐳGcpApplication"}}:::plan
    Access309{{"Access[309∈19]<br />ᐸ307.0ᐳ"}}:::plan
    Access310{{"Access[310∈19]<br />ᐸ307.1ᐳ"}}:::plan
    Access309 & Access310 --> List311
    PgCursor308{{"PgCursor[308∈19]"}}:::plan
    List311 --> PgCursor308
    PgUnionAllSingle307 --> Access309
    PgUnionAllSingle307 --> Access310
    PgSelect315[["PgSelect[315∈20]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access314{{"Access[314∈20]<br />ᐸ313.0ᐳ"}}:::plan
    Object18 & Access314 --> PgSelect315
    PgSelect327[["PgSelect[327∈20]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access326{{"Access[326∈20]<br />ᐸ325.0ᐳ"}}:::plan
    Object18 & Access326 --> PgSelect327
    JSONParse313[["JSONParse[313∈20]<br />ᐸ310ᐳ<br />ᐳGcpApplicationᐳFirstPartyVulnerability"]]:::plan
    Access310 --> JSONParse313
    JSONParse313 --> Access314
    First319{{"First[319∈20]"}}:::plan
    PgSelect315 --> First319
    PgSelectSingle320{{"PgSelectSingle[320∈20]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First319 --> PgSelectSingle320
    PgClassExpression321{{"PgClassExpression[321∈20]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle320 --> PgClassExpression321
    PgClassExpression322{{"PgClassExpression[322∈20]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle320 --> PgClassExpression322
    PgClassExpression323{{"PgClassExpression[323∈20]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle320 --> PgClassExpression323
    JSONParse325[["JSONParse[325∈20]<br />ᐸ310ᐳ<br />ᐳGcpApplicationᐳThirdPartyVulnerability"]]:::plan
    Access310 --> JSONParse325
    JSONParse325 --> Access326
    First331{{"First[331∈20]"}}:::plan
    PgSelect327 --> First331
    PgSelectSingle332{{"PgSelectSingle[332∈20]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First331 --> PgSelectSingle332
    PgClassExpression333{{"PgClassExpression[333∈20]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle332 --> PgClassExpression333
    PgClassExpression334{{"PgClassExpression[334∈20]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle332 --> PgClassExpression334
    PgClassExpression335{{"PgClassExpression[335∈20]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle332 --> PgClassExpression335

    %% define steps

    subgraph "Buckets for queries/polymorphic/person-app-vulns"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,Access16,Access17,Object18,Connection19,Constant336 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 18, 19<br /><br />ROOT Connectionᐸ15ᐳ[19]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect20,Connection39 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 18, 39<br /><br />ROOT __Item{2}ᐸ20ᐳ[21]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item21,PgSelectSingle22 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 18, 39, 22<br /><br />ROOT PgSelectSingle{2}ᐸpeopleᐳ[22]<br />1: <br />ᐳ: 23, 24<br />2: 40, 44, 71<br />ᐳ: First[41]<br />3: PgUnionAllSingle[42]<br />ᐳ: PgClassExpression[43]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression23,PgClassExpression24,PgUnionAll40,First41,PgUnionAllSingle42,PgClassExpression43,PgUnionAll44,PgUnionAll71 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 18<br /><br />ROOT __Item{4}ᐸ44ᐳ[45]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item45,PgUnionAllSingle46 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 18, 46<br /><br />ROOT PgUnionAllSingle{4}[46]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgCursor47,Access48,Access49,List50 bucket5
    Bucket6("Bucket 6 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 18, 49, 46<br />ᐳAwsApplication<br />ᐳGcpApplication<br />1: JSONParse[52], JSONParse[62]<br />ᐳ: Access[53], Access[63]<br />2: PgSelect[54], PgSelect[64]<br />ᐳ: 58, 59, 60, 68, 69, 70"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,JSONParse52,Access53,PgSelect54,First58,PgSelectSingle59,PgClassExpression60,JSONParse62,Access63,PgSelect64,First68,PgSelectSingle69,PgClassExpression70 bucket6
    Bucket7("Bucket 7 (listItem)<br />Deps: 18<br /><br />ROOT __Item{7}ᐸ71ᐳ[72]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,__Item72,PgUnionAllSingle73,Access74 bucket7
    Bucket8("Bucket 8 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 18, 74, 73<br />ᐳAwsApplication<br />ᐳGcpApplication<br />1: JSONParse[75], JSONParse[206]<br />ᐳ: 169, 300, 76, 207<br />2: PgSelect[77], PgSelect[208]<br />ᐳ: 81, 82, 83, 84, 85, 86, 87, 212, 213, 214, 215, 216, 217, 218<br />3: 88, 123, 170, 174, 219, 254, 301, 305<br />ᐳ: 92, 171, 223, 302<br />4: 93, 172, 224, 303<br />ᐳ: 94, 173, 225, 304"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,JSONParse75,Access76,PgSelect77,First81,PgSelectSingle82,PgClassExpression83,PgClassExpression84,PgClassExpression85,PgClassExpression86,PgClassExpression87,PgUnionAll88,First92,PgUnionAllSingle93,Access94,PgUnionAll123,Connection169,PgUnionAll170,First171,PgUnionAllSingle172,PgClassExpression173,PgUnionAll174,JSONParse206,Access207,PgSelect208,First212,PgSelectSingle213,PgClassExpression214,PgClassExpression215,PgClassExpression216,PgClassExpression217,PgClassExpression218,PgUnionAll219,First223,PgUnionAllSingle224,Access225,PgUnionAll254,Connection300,PgUnionAll301,First302,PgUnionAllSingle303,PgClassExpression304,PgUnionAll305 bucket8
    Bucket9("Bucket 9 (polymorphic)<br />Organization,Person<br />Deps: 18, 94, 93<br />ᐳAwsApplicationᐳOrganization<br />ᐳAwsApplicationᐳPerson<br />1: JSONParse[95], JSONParse[106]<br />ᐳ: Access[96], Access[107]<br />2: PgSelect[97], PgSelect[108]<br />ᐳ: 101, 102, 103, 104, 112, 113, 114, 115"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,JSONParse95,Access96,PgSelect97,First101,PgSelectSingle102,PgClassExpression103,PgClassExpression104,JSONParse106,Access107,PgSelect108,First112,PgSelectSingle113,PgClassExpression114,PgClassExpression115 bucket9
    Bucket10("Bucket 10 (listItem)<br />Deps: 18<br /><br />ROOT __Item{10}ᐸ123ᐳ[127]"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Item127,PgUnionAllSingle128,Access129 bucket10
    Bucket11("Bucket 11 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 18, 129, 128<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />1: JSONParse[130], JSONParse[143]<br />ᐳ: Access[131], Access[144]<br />2: PgSelect[132], PgSelect[145]<br />ᐳ: 136, 137, 138, 139, 140, 141, 149, 150, 151, 152, 153, 154"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,JSONParse130,Access131,PgSelect132,First136,PgSelectSingle137,PgClassExpression138,PgClassExpression139,PgClassExpression140,PgClassExpression141,JSONParse143,Access144,PgSelect145,First149,PgSelectSingle150,PgClassExpression151,PgClassExpression152,PgClassExpression153,PgClassExpression154 bucket11
    Bucket12("Bucket 12 (listItem)<br />Deps: 18<br /><br />ROOT __Item{12}ᐸ174ᐳ[175]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,__Item175,PgUnionAllSingle176 bucket12
    Bucket13("Bucket 13 (nullableBoundary)<br />Deps: 18, 176<br /><br />ROOT PgUnionAllSingle{12}[176]"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgCursor177,Access178,Access179,List180 bucket13
    Bucket14("Bucket 14 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 18, 179, 176<br />ᐳAwsApplicationᐳFirstPartyVulnerability<br />ᐳAwsApplicationᐳThirdPartyVulnerability<br />1: JSONParse[182], JSONParse[194]<br />ᐳ: Access[183], Access[195]<br />2: PgSelect[184], PgSelect[196]<br />ᐳ: 188, 189, 190, 191, 192, 200, 201, 202, 203, 204"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,JSONParse182,Access183,PgSelect184,First188,PgSelectSingle189,PgClassExpression190,PgClassExpression191,PgClassExpression192,JSONParse194,Access195,PgSelect196,First200,PgSelectSingle201,PgClassExpression202,PgClassExpression203,PgClassExpression204 bucket14
    Bucket15("Bucket 15 (polymorphic)<br />Organization,Person<br />Deps: 18, 225, 224<br />ᐳGcpApplicationᐳOrganization<br />ᐳGcpApplicationᐳPerson<br />1: JSONParse[226], JSONParse[237]<br />ᐳ: Access[227], Access[238]<br />2: PgSelect[228], PgSelect[239]<br />ᐳ: 232, 233, 234, 235, 243, 244, 245, 246"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,JSONParse226,Access227,PgSelect228,First232,PgSelectSingle233,PgClassExpression234,PgClassExpression235,JSONParse237,Access238,PgSelect239,First243,PgSelectSingle244,PgClassExpression245,PgClassExpression246 bucket15
    Bucket16("Bucket 16 (listItem)<br />Deps: 18<br /><br />ROOT __Item{16}ᐸ254ᐳ[258]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item258,PgUnionAllSingle259,Access260 bucket16
    Bucket17("Bucket 17 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 18, 260, 259<br />ᐳGcpApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability<br />1: JSONParse[261], JSONParse[274]<br />ᐳ: Access[262], Access[275]<br />2: PgSelect[263], PgSelect[276]<br />ᐳ: 267, 268, 269, 270, 271, 272, 280, 281, 282, 283, 284, 285"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,JSONParse261,Access262,PgSelect263,First267,PgSelectSingle268,PgClassExpression269,PgClassExpression270,PgClassExpression271,PgClassExpression272,JSONParse274,Access275,PgSelect276,First280,PgSelectSingle281,PgClassExpression282,PgClassExpression283,PgClassExpression284,PgClassExpression285 bucket17
    Bucket18("Bucket 18 (listItem)<br />Deps: 18<br /><br />ROOT __Item{18}ᐸ305ᐳ[306]"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item306,PgUnionAllSingle307 bucket18
    Bucket19("Bucket 19 (nullableBoundary)<br />Deps: 18, 307<br /><br />ROOT PgUnionAllSingle{18}[307]"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgCursor308,Access309,Access310,List311 bucket19
    Bucket20("Bucket 20 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 18, 310, 307<br />ᐳGcpApplicationᐳFirstPartyVulnerability<br />ᐳGcpApplicationᐳThirdPartyVulnerability<br />1: JSONParse[313], JSONParse[325]<br />ᐳ: Access[314], Access[326]<br />2: PgSelect[315], PgSelect[327]<br />ᐳ: 319, 320, 321, 322, 323, 331, 332, 333, 334, 335"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,JSONParse313,Access314,PgSelect315,First319,PgSelectSingle320,PgClassExpression321,PgClassExpression322,PgClassExpression323,JSONParse325,Access326,PgSelect327,First331,PgSelectSingle332,PgClassExpression333,PgClassExpression334,PgClassExpression335 bucket20
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket7
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9 & Bucket10 & Bucket12 & Bucket15 & Bucket16 & Bucket18
    Bucket10 --> Bucket11
    Bucket12 --> Bucket13
    Bucket13 --> Bucket14
    Bucket16 --> Bucket17
    Bucket18 --> Bucket19
    Bucket19 --> Bucket20
    classDef unary fill:#fafffa,borderWidth:8px
    class Object18,Access16,Access17,Connection19,__Value0,__Value3,__Value5,Constant336,PgSelect20,Connection39,Connection169,Connection300 unary
    end
