%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/relay.polyroot_with_related_poly"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 541, 135, 139, 143, 147, 151<br /><br />ROOT Connectionᐸ8ᐳ[12]<br />1: PgSelect[35]<br />ᐳ: Access[542]<br />2: PgSelectRows[39]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 11, 17, 155, 159, 163, 167, 171<br /><br />ROOT Connectionᐸ15ᐳ[17]<br />1: PgSelect[36]<br />2: PgSelectRows[40]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 11, 25, 24, 545, 549, 99, 135, 139, 143, 147, 151<br /><br />ROOT Connectionᐸ22ᐳ[24]<br />1: PgSelect[37]<br />ᐳ: Access[546], Access[550]<br />2: PgSelectRows[41]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 11, 33, 32, 553, 557, 103, 155, 159, 163, 167, 171<br /><br />ROOT Connectionᐸ30ᐳ[32]<br />1: PgSelect[38]<br />ᐳ: Access[554], Access[558]<br />2: PgSelectRows[42]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 542, 135, 139, 143, 147, 151<br /><br />ROOT __Item{5}ᐸ39ᐳ[43]<br />1: <br />ᐳ: 44, 51, 53, 54, 543, 544<br />2: PgSelectRows[191]<br />ᐳ: 190, 192, 356, 358, 359"):::bucket
    Bucket6("Bucket 6 (listItem)<br />Deps: 11, 155, 159, 163, 167, 171<br /><br />ROOT __Item{6}ᐸ40ᐳ[45]"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 99, 546, 550, 135, 139, 143, 147, 151<br /><br />ROOT __Item{7}ᐸ41ᐳ[47]"):::bucket
    Bucket8("Bucket 8 (listItem)<br />Deps: 103, 554, 558, 11, 155, 159, 163, 167, 171<br /><br />ROOT __Item{8}ᐸ42ᐳ[49]"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 48, 99, 546, 550, 135, 139, 143, 147, 151<br /><br />ROOT PgSelectSingle{7}ᐸsingle_table_item_relationsᐳ[48]<br />1: <br />ᐳ: 100, 547, 551, 101, 102, 548, 552<br />2: PgSelectRows[113], PgSelectRows[127]<br />ᐳ: 112, 114, 126, 128, 260, 262, 263, 308, 310, 311"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 50, 103, 554, 558, 11, 155, 159, 163, 167, 171<br /><br />ROOT PgSelectSingle{8}ᐸrelational_item_relationsᐳ[50]<br />1: <br />ᐳ: 104, 555, 559, 105, 106, 556, 560<br />2: PgSelectRows[121], PgSelectRows[133]<br />ᐳ: 120, 122, 132, 134, 264, 266, 267, 312, 314, 315"):::bucket
    Bucket11("Bucket 11 (polymorphic)<br />__typename: Lambda[54]<br />Deps: 135, 51, 139, 143, 147, 151, 54, 356, 359, 44, 53, 192, 358"):::bucket
    Bucket12("Bucket 12 (polymorphic)<br />__typename: Lambda[58]<br />Deps: 58, 11, 55, 155, 159, 163, 167, 171, 57"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 55, 155, 159, 163, 167, 171, 57<br />ᐳRelationalTopic<br /><br />1: PgSelect[60]<br />2: PgSelectRows[65]<br />ᐳ: 64, 66, 156, 157, 158<br />3: PgSelect[225]<br />4: PgSelectRows[230]<br />ᐳ: 229, 231, 360, 361"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 55, 159, 155, 163, 167, 171, 57<br />ᐳRelationalPost<br /><br />1: PgSelect[68]<br />2: PgSelectRows[73]<br />ᐳ: 72, 74, 160, 161, 162<br />3: PgSelect[232]<br />4: PgSelectRows[237]<br />ᐳ: 236, 238, 362, 363"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 55, 163, 155, 159, 167, 171, 57<br />ᐳRelationalDivider<br /><br />1: PgSelect[76]<br />2: PgSelectRows[81]<br />ᐳ: 80, 82, 164, 165, 166<br />3: PgSelect[239]<br />4: PgSelectRows[244]<br />ᐳ: 243, 245, 364, 365"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 55, 167, 155, 159, 163, 171, 57<br />ᐳRelationalChecklist<br /><br />1: PgSelect[84]<br />2: PgSelectRows[89]<br />ᐳ: 88, 90, 168, 169, 170<br />3: PgSelect[246]<br />4: PgSelectRows[251]<br />ᐳ: 250, 252, 366, 367"):::bucket
    Bucket17("Bucket 17 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 55, 171, 155, 159, 163, 167, 57<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[92]<br />2: PgSelectRows[97]<br />ᐳ: 96, 98, 172, 173, 174<br />3: PgSelect[253]<br />4: PgSelectRows[258]<br />ᐳ: 257, 259, 368, 369"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />__typename: Lambda[263]<br />Deps: 135, 260, 139, 143, 147, 151, 263, 114, 262"):::bucket
    Bucket19("Bucket 19 (polymorphic)<br />__typename: Lambda[267]<br />Deps: 267, 11, 264, 155, 159, 163, 167, 171, 266"):::bucket
    Bucket20("Bucket 20 (polymorphic)<br />__typename: Lambda[311]<br />Deps: 135, 308, 139, 143, 147, 151, 311, 128, 310"):::bucket
    Bucket21("Bucket 21 (polymorphic)<br />__typename: Lambda[315]<br />Deps: 315, 11, 312, 155, 159, 163, 167, 171, 314"):::bucket
    Bucket22("Bucket 22 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 264, 155, 266<br />ᐳRelationalTopic<br /><br />1: PgSelect[269]<br />2: PgSelectRows[274]<br />ᐳ: 273, 275, 436, 437, 438"):::bucket
    Bucket23("Bucket 23 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 264, 159, 266<br />ᐳRelationalPost<br /><br />1: PgSelect[277]<br />2: PgSelectRows[282]<br />ᐳ: 281, 283, 439, 440, 441"):::bucket
    Bucket24("Bucket 24 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 264, 163, 266<br />ᐳRelationalDivider<br /><br />1: PgSelect[285]<br />2: PgSelectRows[290]<br />ᐳ: 289, 291, 442, 443, 444"):::bucket
    Bucket25("Bucket 25 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 264, 167, 266<br />ᐳRelationalChecklist<br /><br />1: PgSelect[293]<br />2: PgSelectRows[298]<br />ᐳ: 297, 299, 445, 446, 447"):::bucket
    Bucket26("Bucket 26 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 264, 171, 266<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[301]<br />2: PgSelectRows[306]<br />ᐳ: 305, 307, 448, 449, 450"):::bucket
    Bucket27("Bucket 27 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 312, 155, 314<br />ᐳRelationalTopic<br /><br />1: PgSelect[317]<br />2: PgSelectRows[322]<br />ᐳ: 321, 323, 466, 467, 468"):::bucket
    Bucket28("Bucket 28 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 312, 159, 314<br />ᐳRelationalPost<br /><br />1: PgSelect[325]<br />2: PgSelectRows[330]<br />ᐳ: 329, 331, 469, 470, 471"):::bucket
    Bucket29("Bucket 29 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 312, 163, 314<br />ᐳRelationalDivider<br /><br />1: PgSelect[333]<br />2: PgSelectRows[338]<br />ᐳ: 337, 339, 472, 473, 474"):::bucket
    Bucket30("Bucket 30 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 312, 167, 314<br />ᐳRelationalChecklist<br /><br />1: PgSelect[341]<br />2: PgSelectRows[346]<br />ᐳ: 345, 347, 475, 476, 477"):::bucket
    Bucket31("Bucket 31 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 312, 171, 314<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[349]<br />2: PgSelectRows[354]<br />ᐳ: 353, 355, 478, 479, 480"):::bucket
    Bucket32("Bucket 32 (polymorphic)<br />__typename: Lambda[359]<br />Deps: 135, 356, 139, 143, 147, 151, 359, 192, 358"):::bucket
    Bucket33("Bucket 33 (combined)<br />Deps: 11, 155, 159, 163, 167, 171<br /><br />1: <br />ᐳ: Access[371]<br />2: PgSelect[372]<br />3: PgSelectRows[377]<br />ᐳ: 376, 378, 379, 380, 381"):::bucket
    Bucket34("Bucket 34 (polymorphic)<br />__typename: Lambda[380]<br />Deps: 380, 11, 381, 155, 159, 163, 167, 171, 379"):::bucket
    Bucket35("Bucket 35 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 11, 381, 155, 379<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[382]<br />2: PgSelectRows[387]<br />ᐳ: 386, 388, 516, 517, 518"):::bucket
    Bucket36("Bucket 36 (polymorphicPartition)<br />|RelationalPost<br />Deps: 11, 381, 159, 379<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[390]<br />2: PgSelectRows[395]<br />ᐳ: 394, 396, 519, 520, 521"):::bucket
    Bucket37("Bucket 37 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 11, 381, 163, 379<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[398]<br />2: PgSelectRows[403]<br />ᐳ: 402, 404, 522, 523, 524"):::bucket
    Bucket38("Bucket 38 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 11, 381, 167, 379<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[406]<br />2: PgSelectRows[411]<br />ᐳ: 410, 412, 525, 526, 527"):::bucket
    Bucket39("Bucket 39 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 11, 381, 171, 379<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[414]<br />2: PgSelectRows[419]<br />ᐳ: 418, 420, 528, 529, 530"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4
    Bucket1 --> Bucket5
    Bucket2 --> Bucket6
    Bucket3 --> Bucket7
    Bucket4 --> Bucket8
    Bucket5 --> Bucket11
    Bucket6 --> Bucket12
    Bucket7 --> Bucket9
    Bucket8 --> Bucket10
    Bucket9 --> Bucket18 & Bucket20
    Bucket10 --> Bucket19 & Bucket21
    Bucket11 --> Bucket32
    Bucket12 --> Bucket13 & Bucket14 & Bucket15 & Bucket16 & Bucket17
    Bucket13 --> Bucket33
    Bucket14 --> Bucket33
    Bucket15 --> Bucket33
    Bucket16 --> Bucket33
    Bucket17 --> Bucket33
    Bucket19 --> Bucket22 & Bucket23 & Bucket24 & Bucket25 & Bucket26
    Bucket21 --> Bucket27 & Bucket28 & Bucket29 & Bucket30 & Bucket31
    Bucket33 --> Bucket34
    Bucket34 --> Bucket35 & Bucket36 & Bucket37 & Bucket38 & Bucket39

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 30"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __InputObject19{{"__InputObject[19∈0] ➊<br />More deps:<br />- Constantᐸ'WyJTaW5nbGVUYWJsZURpdmlkZXIiLDNd'ᐳ[561]<br />- Constantᐸundefinedᐳ[6]"}}:::plan
    __InputObject27{{"__InputObject[27∈0] ➊<br />More deps:<br />- Constantᐸ'WyJyZWxhdGlvbmFsX2NoZWNrbGlzdF9pdGVtcyIsMjFd'ᐳ[562]<br />- Constantᐸundefinedᐳ[6]"}}:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    ApplyInput25{{"ApplyInput[25∈0] ➊"}}:::plan
    __InputObject19 --> ApplyInput25
    ApplyInput33{{"ApplyInput[33∈0] ➊"}}:::plan
    __InputObject27 --> ApplyInput33
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Connection17{{"Connection[17∈0] ➊<br />ᐸ15ᐳ"}}:::plan
    Connection24{{"Connection[24∈0] ➊<br />ᐸ22ᐳ"}}:::plan
    Connection32{{"Connection[32∈0] ➊<br />ᐸ30ᐳ"}}:::plan
    PgSelectInlineApply541["PgSelectInlineApply[541∈0] ➊"]:::plan
    PgSelectInlineApply545["PgSelectInlineApply[545∈0] ➊"]:::plan
    PgSelectInlineApply549["PgSelectInlineApply[549∈0] ➊"]:::plan
    PgSelectInlineApply553["PgSelectInlineApply[553∈0] ➊"]:::plan
    PgSelectInlineApply557["PgSelectInlineApply[557∈0] ➊"]:::plan
    PgSelect35[["PgSelect[35∈1] ➊<br />ᐸsingle_table_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Connection12 & PgSelectInlineApply541 --> PgSelect35
    PgSelectRows39[["PgSelectRows[39∈1] ➊"]]:::plan
    PgSelect35 --> PgSelectRows39
    Access542{{"Access[542∈1] ➊<br />ᐸ35.m.joinDetailsFor186ᐳ"}}:::plan
    PgSelect35 --> Access542
    PgSelect36[["PgSelect[36∈2] ➊<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Connection17 --> PgSelect36
    PgSelectRows40[["PgSelectRows[40∈2] ➊"]]:::plan
    PgSelect36 --> PgSelectRows40
    PgSelect37[["PgSelect[37∈3] ➊<br />ᐸsingle_table_item_relationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    ApplyInput25 & Connection24 & PgSelectInlineApply545 & PgSelectInlineApply549 --> PgSelect37
    PgSelectRows41[["PgSelectRows[41∈3] ➊"]]:::plan
    PgSelect37 --> PgSelectRows41
    Access546{{"Access[546∈3] ➊<br />ᐸ37.m.joinDetailsFor108ᐳ"}}:::plan
    PgSelect37 --> Access546
    Access550{{"Access[550∈3] ➊<br />ᐸ37.m.joinDetailsFor124ᐳ"}}:::plan
    PgSelect37 --> Access550
    PgSelect38[["PgSelect[38∈4] ➊<br />ᐸrelational_item_relationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    ApplyInput33 & Connection32 & PgSelectInlineApply553 & PgSelectInlineApply557 --> PgSelect38
    PgSelectRows42[["PgSelectRows[42∈4] ➊"]]:::plan
    PgSelect38 --> PgSelectRows42
    Access554{{"Access[554∈4] ➊<br />ᐸ38.m.joinDetailsFor116ᐳ"}}:::plan
    PgSelect38 --> Access554
    Access558{{"Access[558∈4] ➊<br />ᐸ38.m.joinDetailsFor130ᐳ"}}:::plan
    PgSelect38 --> Access558
    List543{{"List[543∈5]<br />ᐸ542,44ᐳ"}}:::plan
    PgSelectSingle44{{"PgSelectSingle[44∈5]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    Access542 & PgSelectSingle44 --> List543
    __Item43[/"__Item[43∈5]<br />ᐸ39ᐳ"\]:::itemplan
    PgSelectRows39 ==> __Item43
    __Item43 --> PgSelectSingle44
    PgClassExpression51{{"PgClassExpression[51∈5]<br />ᐸ__single_t...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression51
    PgClassExpression53{{"PgClassExpression[53∈5]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression53
    Lambda54{{"Lambda[54∈5]<br />ᐸSingleTableItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression53 --> Lambda54
    First190{{"First[190∈5]"}}:::plan
    PgSelectRows191[["PgSelectRows[191∈5]"]]:::plan
    PgSelectRows191 --> First190
    Lambda544{{"Lambda[544∈5]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda544 --> PgSelectRows191
    PgSelectSingle192{{"PgSelectSingle[192∈5]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    First190 --> PgSelectSingle192
    PgClassExpression356{{"PgClassExpression[356∈5]<br />ᐸ__single_t...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle192 --> PgClassExpression356
    PgClassExpression358{{"PgClassExpression[358∈5]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle192 --> PgClassExpression358
    Lambda359{{"Lambda[359∈5]<br />ᐸSingleTableItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression358 --> Lambda359
    List543 --> Lambda544
    __Item45[/"__Item[45∈6]<br />ᐸ40ᐳ"\]:::itemplan
    PgSelectRows40 ==> __Item45
    PgSelectSingle46{{"PgSelectSingle[46∈6]<br />ᐸrelational_itemsᐳ"}}:::plan
    __Item45 --> PgSelectSingle46
    PgClassExpression55{{"PgClassExpression[55∈6]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression55
    PgClassExpression57{{"PgClassExpression[57∈6]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle46 --> PgClassExpression57
    Lambda58{{"Lambda[58∈6]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression57 --> Lambda58
    __Item47[/"__Item[47∈7]<br />ᐸ41ᐳ"\]:::itemplan
    PgSelectRows41 ==> __Item47
    PgSelectSingle48{{"PgSelectSingle[48∈7]<br />ᐸsingle_table_item_relationsᐳ"}}:::plan
    __Item47 --> PgSelectSingle48
    __Item49[/"__Item[49∈8]<br />ᐸ42ᐳ"\]:::itemplan
    PgSelectRows42 ==> __Item49
    PgSelectSingle50{{"PgSelectSingle[50∈8]<br />ᐸrelational_item_relationsᐳ"}}:::plan
    __Item49 --> PgSelectSingle50
    List101{{"List[101∈9]<br />ᐸ99,100ᐳ<br />More deps:<br />- Constantᐸ'single_table_item_relations'ᐳ[99]"}}:::plan
    PgClassExpression100{{"PgClassExpression[100∈9]<br />ᐸ__single_t...ons__.”id”ᐳ"}}:::plan
    PgClassExpression100 --> List101
    List547{{"List[547∈9]<br />ᐸ546,48ᐳ"}}:::plan
    Access546 & PgSelectSingle48 --> List547
    List551{{"List[551∈9]<br />ᐸ550,48ᐳ"}}:::plan
    Access550 & PgSelectSingle48 --> List551
    PgSelectSingle48 --> PgClassExpression100
    Lambda102{{"Lambda[102∈9]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List101 --> Lambda102
    First112{{"First[112∈9]"}}:::plan
    PgSelectRows113[["PgSelectRows[113∈9]"]]:::plan
    PgSelectRows113 --> First112
    Lambda548{{"Lambda[548∈9]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda548 --> PgSelectRows113
    PgSelectSingle114{{"PgSelectSingle[114∈9]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    First112 --> PgSelectSingle114
    First126{{"First[126∈9]"}}:::plan
    PgSelectRows127[["PgSelectRows[127∈9]"]]:::plan
    PgSelectRows127 --> First126
    Lambda552{{"Lambda[552∈9]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda552 --> PgSelectRows127
    PgSelectSingle128{{"PgSelectSingle[128∈9]<br />ᐸsingle_table_itemsᐳ"}}:::plan
    First126 --> PgSelectSingle128
    PgClassExpression260{{"PgClassExpression[260∈9]<br />ᐸ__single_t...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle114 --> PgClassExpression260
    PgClassExpression262{{"PgClassExpression[262∈9]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle114 --> PgClassExpression262
    Lambda263{{"Lambda[263∈9]<br />ᐸSingleTableItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression262 --> Lambda263
    PgClassExpression308{{"PgClassExpression[308∈9]<br />ᐸ__single_t...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle128 --> PgClassExpression308
    PgClassExpression310{{"PgClassExpression[310∈9]<br />ᐸ__single_t...s__.”type”ᐳ"}}:::plan
    PgSelectSingle128 --> PgClassExpression310
    Lambda311{{"Lambda[311∈9]<br />ᐸSingleTableItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression310 --> Lambda311
    List547 --> Lambda548
    List551 --> Lambda552
    List105{{"List[105∈10]<br />ᐸ103,104ᐳ<br />More deps:<br />- Constantᐸ'relational_item_relations'ᐳ[103]"}}:::plan
    PgClassExpression104{{"PgClassExpression[104∈10]<br />ᐸ__relation...ons__.”id”ᐳ"}}:::plan
    PgClassExpression104 --> List105
    List555{{"List[555∈10]<br />ᐸ554,50ᐳ"}}:::plan
    Access554 & PgSelectSingle50 --> List555
    List559{{"List[559∈10]<br />ᐸ558,50ᐳ"}}:::plan
    Access558 & PgSelectSingle50 --> List559
    PgSelectSingle50 --> PgClassExpression104
    Lambda106{{"Lambda[106∈10]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List105 --> Lambda106
    First120{{"First[120∈10]"}}:::plan
    PgSelectRows121[["PgSelectRows[121∈10]"]]:::plan
    PgSelectRows121 --> First120
    Lambda556{{"Lambda[556∈10]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda556 --> PgSelectRows121
    PgSelectSingle122{{"PgSelectSingle[122∈10]<br />ᐸrelational_itemsᐳ"}}:::plan
    First120 --> PgSelectSingle122
    First132{{"First[132∈10]"}}:::plan
    PgSelectRows133[["PgSelectRows[133∈10]"]]:::plan
    PgSelectRows133 --> First132
    Lambda560{{"Lambda[560∈10]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda560 --> PgSelectRows133
    PgSelectSingle134{{"PgSelectSingle[134∈10]<br />ᐸrelational_itemsᐳ"}}:::plan
    First132 --> PgSelectSingle134
    PgClassExpression264{{"PgClassExpression[264∈10]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle122 --> PgClassExpression264
    PgClassExpression266{{"PgClassExpression[266∈10]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle122 --> PgClassExpression266
    Lambda267{{"Lambda[267∈10]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression266 --> Lambda267
    PgClassExpression312{{"PgClassExpression[312∈10]<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle134 --> PgClassExpression312
    PgClassExpression314{{"PgClassExpression[314∈10]<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle134 --> PgClassExpression314
    Lambda315{{"Lambda[315∈10]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression314 --> Lambda315
    List555 --> Lambda556
    List559 --> Lambda560
    List137{{"List[137∈11]<br />ᐸ135,51ᐳ<br />ᐳSingleTableTopic<br />More deps:<br />- Constantᐸ'SingleTableTopic'ᐳ[135]"}}:::plan
    PgClassExpression51 --> List137
    List141{{"List[141∈11]<br />ᐸ139,51ᐳ<br />ᐳSingleTablePost<br />More deps:<br />- Constantᐸ'SingleTablePost'ᐳ[139]"}}:::plan
    PgClassExpression51 --> List141
    List145{{"List[145∈11]<br />ᐸ143,51ᐳ<br />ᐳSingleTableDivider<br />More deps:<br />- Constantᐸ'SingleTableDivider'ᐳ[143]"}}:::plan
    PgClassExpression51 --> List145
    List149{{"List[149∈11]<br />ᐸ147,51ᐳ<br />ᐳSingleTableChecklist<br />More deps:<br />- Constantᐸ'SingleTableChecklist'ᐳ[147]"}}:::plan
    PgClassExpression51 --> List149
    List153{{"List[153∈11]<br />ᐸ151,51ᐳ<br />ᐳSingleTableChecklistItem<br />More deps:<br />- Constantᐸ'SingleTableChecklistItem'ᐳ[151]"}}:::plan
    PgClassExpression51 --> List153
    Lambda138{{"Lambda[138∈11]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List137 --> Lambda138
    Lambda142{{"Lambda[142∈11]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List141 --> Lambda142
    Lambda146{{"Lambda[146∈11]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List145 --> Lambda146
    Lambda150{{"Lambda[150∈11]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List149 --> Lambda150
    Lambda154{{"Lambda[154∈11]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List153 --> Lambda154
    PgSelect60[["PgSelect[60∈13]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression55 --> PgSelect60
    List157{{"List[157∈13]^<br />ᐸ155,156ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[155]"}}:::plan
    PgClassExpression156{{"PgClassExpression[156∈13]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression156 --> List157
    PgSelect225[["PgSelect[225∈13]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression156 --> PgSelect225
    First64{{"First[64∈13]^"}}:::plan
    PgSelectRows65[["PgSelectRows[65∈13]^"]]:::plan
    PgSelectRows65 --> First64
    PgSelect60 --> PgSelectRows65
    PgSelectSingle66{{"PgSelectSingle[66∈13]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First64 --> PgSelectSingle66
    PgSelectSingle66 --> PgClassExpression156
    Lambda158{{"Lambda[158∈13]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List157 --> Lambda158
    First229{{"First[229∈13]^"}}:::plan
    PgSelectRows230[["PgSelectRows[230∈13]^"]]:::plan
    PgSelectRows230 --> First229
    PgSelect225 --> PgSelectRows230
    PgSelectSingle231{{"PgSelectSingle[231∈13]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First229 --> PgSelectSingle231
    PgClassExpression360{{"PgClassExpression[360∈13]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle231 --> PgClassExpression360
    Object361{{"Object[361∈13]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression360 --> Object361
    PgSelect68[["PgSelect[68∈14]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression55 --> PgSelect68
    List161{{"List[161∈14]^<br />ᐸ159,160ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[159]"}}:::plan
    PgClassExpression160{{"PgClassExpression[160∈14]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression160 --> List161
    PgSelect232[["PgSelect[232∈14]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression160 --> PgSelect232
    First72{{"First[72∈14]^"}}:::plan
    PgSelectRows73[["PgSelectRows[73∈14]^"]]:::plan
    PgSelectRows73 --> First72
    PgSelect68 --> PgSelectRows73
    PgSelectSingle74{{"PgSelectSingle[74∈14]^<br />ᐸrelational_postsᐳ"}}:::plan
    First72 --> PgSelectSingle74
    PgSelectSingle74 --> PgClassExpression160
    Lambda162{{"Lambda[162∈14]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List161 --> Lambda162
    First236{{"First[236∈14]^"}}:::plan
    PgSelectRows237[["PgSelectRows[237∈14]^"]]:::plan
    PgSelectRows237 --> First236
    PgSelect232 --> PgSelectRows237
    PgSelectSingle238{{"PgSelectSingle[238∈14]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First236 --> PgSelectSingle238
    PgClassExpression362{{"PgClassExpression[362∈14]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle238 --> PgClassExpression362
    Object363{{"Object[363∈14]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression362 --> Object363
    PgSelect76[["PgSelect[76∈15]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression55 --> PgSelect76
    List165{{"List[165∈15]^<br />ᐸ163,164ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[163]"}}:::plan
    PgClassExpression164{{"PgClassExpression[164∈15]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression164 --> List165
    PgSelect239[["PgSelect[239∈15]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression164 --> PgSelect239
    First80{{"First[80∈15]^"}}:::plan
    PgSelectRows81[["PgSelectRows[81∈15]^"]]:::plan
    PgSelectRows81 --> First80
    PgSelect76 --> PgSelectRows81
    PgSelectSingle82{{"PgSelectSingle[82∈15]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First80 --> PgSelectSingle82
    PgSelectSingle82 --> PgClassExpression164
    Lambda166{{"Lambda[166∈15]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List165 --> Lambda166
    First243{{"First[243∈15]^"}}:::plan
    PgSelectRows244[["PgSelectRows[244∈15]^"]]:::plan
    PgSelectRows244 --> First243
    PgSelect239 --> PgSelectRows244
    PgSelectSingle245{{"PgSelectSingle[245∈15]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First243 --> PgSelectSingle245
    PgClassExpression364{{"PgClassExpression[364∈15]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle245 --> PgClassExpression364
    Object365{{"Object[365∈15]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression364 --> Object365
    PgSelect84[["PgSelect[84∈16]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression55 --> PgSelect84
    List169{{"List[169∈16]^<br />ᐸ167,168ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[167]"}}:::plan
    PgClassExpression168{{"PgClassExpression[168∈16]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression168 --> List169
    PgSelect246[["PgSelect[246∈16]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression168 --> PgSelect246
    First88{{"First[88∈16]^"}}:::plan
    PgSelectRows89[["PgSelectRows[89∈16]^"]]:::plan
    PgSelectRows89 --> First88
    PgSelect84 --> PgSelectRows89
    PgSelectSingle90{{"PgSelectSingle[90∈16]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First88 --> PgSelectSingle90
    PgSelectSingle90 --> PgClassExpression168
    Lambda170{{"Lambda[170∈16]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List169 --> Lambda170
    First250{{"First[250∈16]^"}}:::plan
    PgSelectRows251[["PgSelectRows[251∈16]^"]]:::plan
    PgSelectRows251 --> First250
    PgSelect246 --> PgSelectRows251
    PgSelectSingle252{{"PgSelectSingle[252∈16]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First250 --> PgSelectSingle252
    PgClassExpression366{{"PgClassExpression[366∈16]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle252 --> PgClassExpression366
    Object367{{"Object[367∈16]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression366 --> Object367
    PgSelect92[["PgSelect[92∈17]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression55 --> PgSelect92
    List173{{"List[173∈17]^<br />ᐸ171,172ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[171]"}}:::plan
    PgClassExpression172{{"PgClassExpression[172∈17]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression172 --> List173
    PgSelect253[["PgSelect[253∈17]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression172 --> PgSelect253
    First96{{"First[96∈17]^"}}:::plan
    PgSelectRows97[["PgSelectRows[97∈17]^"]]:::plan
    PgSelectRows97 --> First96
    PgSelect92 --> PgSelectRows97
    PgSelectSingle98{{"PgSelectSingle[98∈17]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First96 --> PgSelectSingle98
    PgSelectSingle98 --> PgClassExpression172
    Lambda174{{"Lambda[174∈17]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List173 --> Lambda174
    First257{{"First[257∈17]^"}}:::plan
    PgSelectRows258[["PgSelectRows[258∈17]^"]]:::plan
    PgSelectRows258 --> First257
    PgSelect253 --> PgSelectRows258
    PgSelectSingle259{{"PgSelectSingle[259∈17]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First257 --> PgSelectSingle259
    PgClassExpression368{{"PgClassExpression[368∈17]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle259 --> PgClassExpression368
    Object369{{"Object[369∈17]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression368 --> Object369
    List422{{"List[422∈18]<br />ᐸ135,260ᐳ<br />ᐳSingleTableTopic<br />More deps:<br />- Constantᐸ'SingleTableTopic'ᐳ[135]"}}:::plan
    PgClassExpression260 --> List422
    List425{{"List[425∈18]<br />ᐸ139,260ᐳ<br />ᐳSingleTablePost<br />More deps:<br />- Constantᐸ'SingleTablePost'ᐳ[139]"}}:::plan
    PgClassExpression260 --> List425
    List428{{"List[428∈18]<br />ᐸ143,260ᐳ<br />ᐳSingleTableDivider<br />More deps:<br />- Constantᐸ'SingleTableDivider'ᐳ[143]"}}:::plan
    PgClassExpression260 --> List428
    List431{{"List[431∈18]<br />ᐸ147,260ᐳ<br />ᐳSingleTableChecklist<br />More deps:<br />- Constantᐸ'SingleTableChecklist'ᐳ[147]"}}:::plan
    PgClassExpression260 --> List431
    List434{{"List[434∈18]<br />ᐸ151,260ᐳ<br />ᐳSingleTableChecklistItem<br />More deps:<br />- Constantᐸ'SingleTableChecklistItem'ᐳ[151]"}}:::plan
    PgClassExpression260 --> List434
    Lambda423{{"Lambda[423∈18]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List422 --> Lambda423
    Lambda426{{"Lambda[426∈18]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List425 --> Lambda426
    Lambda429{{"Lambda[429∈18]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List428 --> Lambda429
    Lambda432{{"Lambda[432∈18]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List431 --> Lambda432
    Lambda435{{"Lambda[435∈18]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List434 --> Lambda435
    List452{{"List[452∈20]<br />ᐸ135,308ᐳ<br />ᐳSingleTableTopic<br />More deps:<br />- Constantᐸ'SingleTableTopic'ᐳ[135]"}}:::plan
    PgClassExpression308 --> List452
    List455{{"List[455∈20]<br />ᐸ139,308ᐳ<br />ᐳSingleTablePost<br />More deps:<br />- Constantᐸ'SingleTablePost'ᐳ[139]"}}:::plan
    PgClassExpression308 --> List455
    List458{{"List[458∈20]<br />ᐸ143,308ᐳ<br />ᐳSingleTableDivider<br />More deps:<br />- Constantᐸ'SingleTableDivider'ᐳ[143]"}}:::plan
    PgClassExpression308 --> List458
    List461{{"List[461∈20]<br />ᐸ147,308ᐳ<br />ᐳSingleTableChecklist<br />More deps:<br />- Constantᐸ'SingleTableChecklist'ᐳ[147]"}}:::plan
    PgClassExpression308 --> List461
    List464{{"List[464∈20]<br />ᐸ151,308ᐳ<br />ᐳSingleTableChecklistItem<br />More deps:<br />- Constantᐸ'SingleTableChecklistItem'ᐳ[151]"}}:::plan
    PgClassExpression308 --> List464
    Lambda453{{"Lambda[453∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List452 --> Lambda453
    Lambda456{{"Lambda[456∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List455 --> Lambda456
    Lambda459{{"Lambda[459∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List458 --> Lambda459
    Lambda462{{"Lambda[462∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List461 --> Lambda462
    Lambda465{{"Lambda[465∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List464 --> Lambda465
    PgSelect269[["PgSelect[269∈22]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression264 --> PgSelect269
    List437{{"List[437∈22]^<br />ᐸ155,436ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[155]"}}:::plan
    PgClassExpression436{{"PgClassExpression[436∈22]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression436 --> List437
    First273{{"First[273∈22]^"}}:::plan
    PgSelectRows274[["PgSelectRows[274∈22]^"]]:::plan
    PgSelectRows274 --> First273
    PgSelect269 --> PgSelectRows274
    PgSelectSingle275{{"PgSelectSingle[275∈22]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First273 --> PgSelectSingle275
    PgSelectSingle275 --> PgClassExpression436
    Lambda438{{"Lambda[438∈22]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List437 --> Lambda438
    PgSelect277[["PgSelect[277∈23]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression264 --> PgSelect277
    List440{{"List[440∈23]^<br />ᐸ159,439ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[159]"}}:::plan
    PgClassExpression439{{"PgClassExpression[439∈23]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression439 --> List440
    First281{{"First[281∈23]^"}}:::plan
    PgSelectRows282[["PgSelectRows[282∈23]^"]]:::plan
    PgSelectRows282 --> First281
    PgSelect277 --> PgSelectRows282
    PgSelectSingle283{{"PgSelectSingle[283∈23]^<br />ᐸrelational_postsᐳ"}}:::plan
    First281 --> PgSelectSingle283
    PgSelectSingle283 --> PgClassExpression439
    Lambda441{{"Lambda[441∈23]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List440 --> Lambda441
    PgSelect285[["PgSelect[285∈24]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression264 --> PgSelect285
    List443{{"List[443∈24]^<br />ᐸ163,442ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[163]"}}:::plan
    PgClassExpression442{{"PgClassExpression[442∈24]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression442 --> List443
    First289{{"First[289∈24]^"}}:::plan
    PgSelectRows290[["PgSelectRows[290∈24]^"]]:::plan
    PgSelectRows290 --> First289
    PgSelect285 --> PgSelectRows290
    PgSelectSingle291{{"PgSelectSingle[291∈24]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First289 --> PgSelectSingle291
    PgSelectSingle291 --> PgClassExpression442
    Lambda444{{"Lambda[444∈24]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List443 --> Lambda444
    PgSelect293[["PgSelect[293∈25]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression264 --> PgSelect293
    List446{{"List[446∈25]^<br />ᐸ167,445ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[167]"}}:::plan
    PgClassExpression445{{"PgClassExpression[445∈25]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression445 --> List446
    First297{{"First[297∈25]^"}}:::plan
    PgSelectRows298[["PgSelectRows[298∈25]^"]]:::plan
    PgSelectRows298 --> First297
    PgSelect293 --> PgSelectRows298
    PgSelectSingle299{{"PgSelectSingle[299∈25]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First297 --> PgSelectSingle299
    PgSelectSingle299 --> PgClassExpression445
    Lambda447{{"Lambda[447∈25]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List446 --> Lambda447
    PgSelect301[["PgSelect[301∈26]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression264 --> PgSelect301
    List449{{"List[449∈26]^<br />ᐸ171,448ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[171]"}}:::plan
    PgClassExpression448{{"PgClassExpression[448∈26]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression448 --> List449
    First305{{"First[305∈26]^"}}:::plan
    PgSelectRows306[["PgSelectRows[306∈26]^"]]:::plan
    PgSelectRows306 --> First305
    PgSelect301 --> PgSelectRows306
    PgSelectSingle307{{"PgSelectSingle[307∈26]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First305 --> PgSelectSingle307
    PgSelectSingle307 --> PgClassExpression448
    Lambda450{{"Lambda[450∈26]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List449 --> Lambda450
    PgSelect317[["PgSelect[317∈27]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression312 --> PgSelect317
    List467{{"List[467∈27]^<br />ᐸ155,466ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[155]"}}:::plan
    PgClassExpression466{{"PgClassExpression[466∈27]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression466 --> List467
    First321{{"First[321∈27]^"}}:::plan
    PgSelectRows322[["PgSelectRows[322∈27]^"]]:::plan
    PgSelectRows322 --> First321
    PgSelect317 --> PgSelectRows322
    PgSelectSingle323{{"PgSelectSingle[323∈27]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First321 --> PgSelectSingle323
    PgSelectSingle323 --> PgClassExpression466
    Lambda468{{"Lambda[468∈27]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List467 --> Lambda468
    PgSelect325[["PgSelect[325∈28]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression312 --> PgSelect325
    List470{{"List[470∈28]^<br />ᐸ159,469ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[159]"}}:::plan
    PgClassExpression469{{"PgClassExpression[469∈28]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression469 --> List470
    First329{{"First[329∈28]^"}}:::plan
    PgSelectRows330[["PgSelectRows[330∈28]^"]]:::plan
    PgSelectRows330 --> First329
    PgSelect325 --> PgSelectRows330
    PgSelectSingle331{{"PgSelectSingle[331∈28]^<br />ᐸrelational_postsᐳ"}}:::plan
    First329 --> PgSelectSingle331
    PgSelectSingle331 --> PgClassExpression469
    Lambda471{{"Lambda[471∈28]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List470 --> Lambda471
    PgSelect333[["PgSelect[333∈29]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression312 --> PgSelect333
    List473{{"List[473∈29]^<br />ᐸ163,472ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[163]"}}:::plan
    PgClassExpression472{{"PgClassExpression[472∈29]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression472 --> List473
    First337{{"First[337∈29]^"}}:::plan
    PgSelectRows338[["PgSelectRows[338∈29]^"]]:::plan
    PgSelectRows338 --> First337
    PgSelect333 --> PgSelectRows338
    PgSelectSingle339{{"PgSelectSingle[339∈29]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First337 --> PgSelectSingle339
    PgSelectSingle339 --> PgClassExpression472
    Lambda474{{"Lambda[474∈29]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List473 --> Lambda474
    PgSelect341[["PgSelect[341∈30]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression312 --> PgSelect341
    List476{{"List[476∈30]^<br />ᐸ167,475ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[167]"}}:::plan
    PgClassExpression475{{"PgClassExpression[475∈30]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression475 --> List476
    First345{{"First[345∈30]^"}}:::plan
    PgSelectRows346[["PgSelectRows[346∈30]^"]]:::plan
    PgSelectRows346 --> First345
    PgSelect341 --> PgSelectRows346
    PgSelectSingle347{{"PgSelectSingle[347∈30]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First345 --> PgSelectSingle347
    PgSelectSingle347 --> PgClassExpression475
    Lambda477{{"Lambda[477∈30]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List476 --> Lambda477
    PgSelect349[["PgSelect[349∈31]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression312 --> PgSelect349
    List479{{"List[479∈31]^<br />ᐸ171,478ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[171]"}}:::plan
    PgClassExpression478{{"PgClassExpression[478∈31]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression478 --> List479
    First353{{"First[353∈31]^"}}:::plan
    PgSelectRows354[["PgSelectRows[354∈31]^"]]:::plan
    PgSelectRows354 --> First353
    PgSelect349 --> PgSelectRows354
    PgSelectSingle355{{"PgSelectSingle[355∈31]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First353 --> PgSelectSingle355
    PgSelectSingle355 --> PgClassExpression478
    Lambda480{{"Lambda[480∈31]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List479 --> Lambda480
    List502{{"List[502∈32]<br />ᐸ135,356ᐳ<br />(5) ...ᐳSingleTableTopic<br />More deps:<br />- Constantᐸ'SingleTableTopic'ᐳ[135]"}}:::plan
    PgClassExpression356 --> List502
    List505{{"List[505∈32]<br />ᐸ139,356ᐳ<br />(5) ...ᐳSingleTablePost<br />More deps:<br />- Constantᐸ'SingleTablePost'ᐳ[139]"}}:::plan
    PgClassExpression356 --> List505
    List508{{"List[508∈32]<br />ᐸ143,356ᐳ<br />(5) ...ᐳSingleTableDivider<br />More deps:<br />- Constantᐸ'SingleTableDivider'ᐳ[143]"}}:::plan
    PgClassExpression356 --> List508
    List511{{"List[511∈32]<br />ᐸ147,356ᐳ<br />(5) ...ᐳSingleTableChecklist<br />More deps:<br />- Constantᐸ'SingleTableChecklist'ᐳ[147]"}}:::plan
    PgClassExpression356 --> List511
    List514{{"List[514∈32]<br />ᐸ151,356ᐳ<br />(5) ...ᐳSingleTableChecklistItem<br />More deps:<br />- Constantᐸ'SingleTableChecklistItem'ᐳ[151]"}}:::plan
    PgClassExpression356 --> List514
    Lambda503{{"Lambda[503∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List502 --> Lambda503
    Lambda506{{"Lambda[506∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List505 --> Lambda506
    Lambda509{{"Lambda[509∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List508 --> Lambda509
    Lambda512{{"Lambda[512∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List511 --> Lambda512
    Lambda515{{"Lambda[515∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List514 --> Lambda515
    PgSelect372[["PgSelect[372∈33]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access371{{"Access[371∈33]^<br />ᐸ370.idᐳ"}}:::plan
    Access371 --> PgSelect372
    __Value370:::plan@{shape: docs, label: "__Combined[370∈33]<br />ᐳRelationalTopic<br />ᐳRelationalPost<br />ᐳRelationalDivider<br />ᐳRelationalChecklist<br />ᐳRelationalChecklistItem"}
    __Value370 --> Access371
    First376{{"First[376∈33]^"}}:::plan
    PgSelectRows377[["PgSelectRows[377∈33]^"]]:::plan
    PgSelectRows377 --> First376
    PgSelect372 --> PgSelectRows377
    PgSelectSingle378{{"PgSelectSingle[378∈33]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First376 --> PgSelectSingle378
    PgClassExpression379{{"PgClassExpression[379∈33]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle378 --> PgClassExpression379
    Lambda380{{"Lambda[380∈33]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression379 --> Lambda380
    PgClassExpression381{{"PgClassExpression[381∈33]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle378 --> PgClassExpression381
    PgSelect382[["PgSelect[382∈35]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression381 --> PgSelect382
    List517{{"List[517∈35]^<br />ᐸ155,516ᐳ<br />More deps:<br />- Constantᐸ'relational_topics'ᐳ[155]"}}:::plan
    PgClassExpression516{{"PgClassExpression[516∈35]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression516 --> List517
    First386{{"First[386∈35]^"}}:::plan
    PgSelectRows387[["PgSelectRows[387∈35]^"]]:::plan
    PgSelectRows387 --> First386
    PgSelect382 --> PgSelectRows387
    PgSelectSingle388{{"PgSelectSingle[388∈35]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First386 --> PgSelectSingle388
    PgSelectSingle388 --> PgClassExpression516
    Lambda518{{"Lambda[518∈35]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List517 --> Lambda518
    PgSelect390[["PgSelect[390∈36]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression381 --> PgSelect390
    List520{{"List[520∈36]^<br />ᐸ159,519ᐳ<br />More deps:<br />- Constantᐸ'relational_posts'ᐳ[159]"}}:::plan
    PgClassExpression519{{"PgClassExpression[519∈36]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression519 --> List520
    First394{{"First[394∈36]^"}}:::plan
    PgSelectRows395[["PgSelectRows[395∈36]^"]]:::plan
    PgSelectRows395 --> First394
    PgSelect390 --> PgSelectRows395
    PgSelectSingle396{{"PgSelectSingle[396∈36]^<br />ᐸrelational_postsᐳ"}}:::plan
    First394 --> PgSelectSingle396
    PgSelectSingle396 --> PgClassExpression519
    Lambda521{{"Lambda[521∈36]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List520 --> Lambda521
    PgSelect398[["PgSelect[398∈37]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression381 --> PgSelect398
    List523{{"List[523∈37]^<br />ᐸ163,522ᐳ<br />More deps:<br />- Constantᐸ'relational_dividers'ᐳ[163]"}}:::plan
    PgClassExpression522{{"PgClassExpression[522∈37]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression522 --> List523
    First402{{"First[402∈37]^"}}:::plan
    PgSelectRows403[["PgSelectRows[403∈37]^"]]:::plan
    PgSelectRows403 --> First402
    PgSelect398 --> PgSelectRows403
    PgSelectSingle404{{"PgSelectSingle[404∈37]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First402 --> PgSelectSingle404
    PgSelectSingle404 --> PgClassExpression522
    Lambda524{{"Lambda[524∈37]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List523 --> Lambda524
    PgSelect406[["PgSelect[406∈38]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression381 --> PgSelect406
    List526{{"List[526∈38]^<br />ᐸ167,525ᐳ<br />More deps:<br />- Constantᐸ'relational_checklists'ᐳ[167]"}}:::plan
    PgClassExpression525{{"PgClassExpression[525∈38]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression525 --> List526
    First410{{"First[410∈38]^"}}:::plan
    PgSelectRows411[["PgSelectRows[411∈38]^"]]:::plan
    PgSelectRows411 --> First410
    PgSelect406 --> PgSelectRows411
    PgSelectSingle412{{"PgSelectSingle[412∈38]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First410 --> PgSelectSingle412
    PgSelectSingle412 --> PgClassExpression525
    Lambda527{{"Lambda[527∈38]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List526 --> Lambda527
    PgSelect414[["PgSelect[414∈39]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression381 --> PgSelect414
    List529{{"List[529∈39]^<br />ᐸ171,528ᐳ<br />More deps:<br />- Constantᐸ'relational_checklist_items'ᐳ[171]"}}:::plan
    PgClassExpression528{{"PgClassExpression[528∈39]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression528 --> List529
    First418{{"First[418∈39]^"}}:::plan
    PgSelectRows419[["PgSelectRows[419∈39]^"]]:::plan
    PgSelectRows419 --> First418
    PgSelect414 --> PgSelectRows419
    PgSelectSingle420{{"PgSelectSingle[420∈39]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First418 --> PgSelectSingle420
    PgSelectSingle420 --> PgClassExpression528
    Lambda530{{"Lambda[530∈39]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List529 --> Lambda530

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,Access9,Access10,Object11,Connection12,Connection17,__InputObject19,Connection24,ApplyInput25,__InputObject27,Connection32,ApplyInput33,PgSelectInlineApply541,PgSelectInlineApply545,PgSelectInlineApply549,PgSelectInlineApply553,PgSelectInlineApply557 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect35,PgSelectRows39,Access542 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgSelect36,PgSelectRows40 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelect37,PgSelectRows41,Access546,Access550 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect38,PgSelectRows42,Access554,Access558 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item43,PgSelectSingle44,PgClassExpression51,PgClassExpression53,Lambda54,First190,PgSelectRows191,PgSelectSingle192,PgClassExpression356,PgClassExpression358,Lambda359,List543,Lambda544 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item45,PgSelectSingle46,PgClassExpression55,PgClassExpression57,Lambda58 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,__Item47,PgSelectSingle48 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item49,PgSelectSingle50 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression100,List101,Lambda102,First112,PgSelectRows113,PgSelectSingle114,First126,PgSelectRows127,PgSelectSingle128,PgClassExpression260,PgClassExpression262,Lambda263,PgClassExpression308,PgClassExpression310,Lambda311,List547,Lambda548,List551,Lambda552 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression104,List105,Lambda106,First120,PgSelectRows121,PgSelectSingle122,First132,PgSelectRows133,PgSelectSingle134,PgClassExpression264,PgClassExpression266,Lambda267,PgClassExpression312,PgClassExpression314,Lambda315,List555,Lambda556,List559,Lambda560 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,List137,Lambda138,List141,Lambda142,List145,Lambda146,List149,Lambda150,List153,Lambda154 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect60,First64,PgSelectRows65,PgSelectSingle66,PgClassExpression156,List157,Lambda158,PgSelect225,First229,PgSelectRows230,PgSelectSingle231,PgClassExpression360,Object361 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect68,First72,PgSelectRows73,PgSelectSingle74,PgClassExpression160,List161,Lambda162,PgSelect232,First236,PgSelectRows237,PgSelectSingle238,PgClassExpression362,Object363 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect76,First80,PgSelectRows81,PgSelectSingle82,PgClassExpression164,List165,Lambda166,PgSelect239,First243,PgSelectRows244,PgSelectSingle245,PgClassExpression364,Object365 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect84,First88,PgSelectRows89,PgSelectSingle90,PgClassExpression168,List169,Lambda170,PgSelect246,First250,PgSelectRows251,PgSelectSingle252,PgClassExpression366,Object367 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,PgSelect92,First96,PgSelectRows97,PgSelectSingle98,PgClassExpression172,List173,Lambda174,PgSelect253,First257,PgSelectRows258,PgSelectSingle259,PgClassExpression368,Object369 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,List422,Lambda423,List425,Lambda426,List428,Lambda429,List431,Lambda432,List434,Lambda435 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,List452,Lambda453,List455,Lambda456,List458,Lambda459,List461,Lambda462,List464,Lambda465 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgSelect269,First273,PgSelectRows274,PgSelectSingle275,PgClassExpression436,List437,Lambda438 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgSelect277,First281,PgSelectRows282,PgSelectSingle283,PgClassExpression439,List440,Lambda441 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgSelect285,First289,PgSelectRows290,PgSelectSingle291,PgClassExpression442,List443,Lambda444 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect293,First297,PgSelectRows298,PgSelectSingle299,PgClassExpression445,List446,Lambda447 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect301,First305,PgSelectRows306,PgSelectSingle307,PgClassExpression448,List449,Lambda450 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgSelect317,First321,PgSelectRows322,PgSelectSingle323,PgClassExpression466,List467,Lambda468 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgSelect325,First329,PgSelectRows330,PgSelectSingle331,PgClassExpression469,List470,Lambda471 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgSelect333,First337,PgSelectRows338,PgSelectSingle339,PgClassExpression472,List473,Lambda474 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgSelect341,First345,PgSelectRows346,PgSelectSingle347,PgClassExpression475,List476,Lambda477 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgSelect349,First353,PgSelectRows354,PgSelectSingle355,PgClassExpression478,List479,Lambda480 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,List502,Lambda503,List505,Lambda506,List508,Lambda509,List511,Lambda512,List514,Lambda515 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,__Value370,Access371,PgSelect372,First376,PgSelectRows377,PgSelectSingle378,PgClassExpression379,Lambda380,PgClassExpression381 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgSelect382,First386,PgSelectRows387,PgSelectSingle388,PgClassExpression516,List517,Lambda518 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgSelect390,First394,PgSelectRows395,PgSelectSingle396,PgClassExpression519,List520,Lambda521 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37,PgSelect398,First402,PgSelectRows403,PgSelectSingle404,PgClassExpression522,List523,Lambda524 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38,PgSelect406,First410,PgSelectRows411,PgSelectSingle412,PgClassExpression525,List526,Lambda527 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39,PgSelect414,First418,PgSelectRows419,PgSelectSingle420,PgClassExpression528,List529,Lambda530 bucket39

    Object361 -.-x __Value370
    Object363 -.-x __Value370
    Object365 -.-x __Value370
    Object367 -.-x __Value370
    Object369 -.-x __Value370
