%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/relational-functions"
    Bucket0("Bucket 0 (root)<br /><br />1: 921, 926, 930, 935, 939, 944<br />ᐳ: 8, 9, 925, 934, 943, 952, 953, 954, 10, 15, 22, 28, 34, 41<br />2: 7, 13, 20, 26, 32, 39<br />ᐳ: 922, 927, 931, 936, 940, 945<br />3: 11, 17, 24, 30, 36, 43<br />ᐳ: 16, 18, 23, 25, 29, 31, 35, 37, 42, 44, 45, 48, 49, 90, 93, 94, 245, 250<br />4: ConnectionItems[135]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 135, 10<br /><br />ROOT Connectionᐸ7ᐳ[11]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 31, 922, 927, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[31]<br />1: <br />ᐳ: 201, 923, 928, 924, 929<br />2: PgSelectRows[144], PgSelectRows[209]<br />ᐳ: 143, 145, 146, 170, 188, 208, 210, 283, 286, 287"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 37, 931, 936, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[37]<br />1: <br />ᐳ: 202, 932, 937, 933, 938<br />2: PgSelectRows[153], PgSelectRows[216]<br />ᐳ: 152, 154, 155, 176, 194, 215, 217, 328, 331, 332"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 44, 940, 945, 10<br /><br />ROOT PgSelectSingleᐸrelational_topic_by_id_fnᐳ[44]<br />1: <br />ᐳ: 203, 941, 946, 942, 947<br />2: PgSelectRows[162], PgSelectRows[223]<br />ᐳ: 161, 163, 164, 182, 200, 222, 224, 373, 376, 377"):::bucket
    Bucket5("Bucket 5 (polymorphic)<br />__typename: Lambda[49]<br />Deps: 49, 10, 45, 48, 245"):::bucket
    Bucket6("Bucket 6 (polymorphic)<br />__typename: Lambda[94]<br />Deps: 94, 10, 90, 93, 250"):::bucket
    Bucket7("Bucket 7 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 45, 48, 245<br />ᐳRelationalTopic<br /><br />1: 911, 912<br />2: PgSelect[51]<br />ᐳ: Access[913]<br />3: PgSelectRows[56]<br />ᐳ: 55, 57, 255, 914, 915<br />4: PgSelectRows[270]<br />ᐳ: 269, 271, 420, 423, 424"):::bucket
    Bucket8("Bucket 8 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 45, 48, 245<br />ᐳRelationalPost<br /><br />1: PgSelect[59]<br />2: PgSelectRows[64]<br />ᐳ: 63, 65, 256, 272"):::bucket
    Bucket9("Bucket 9 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 45, 48, 245<br />ᐳRelationalDivider<br /><br />1: PgSelect[67]<br />2: PgSelectRows[72]<br />ᐳ: 71, 73, 257"):::bucket
    Bucket10("Bucket 10 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 45, 48, 245<br />ᐳRelationalChecklist<br /><br />1: PgSelect[75]<br />2: PgSelectRows[80]<br />ᐳ: First[79], PgSelectSingle[81]"):::bucket
    Bucket11("Bucket 11 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 45, 48, 245<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[83]<br />2: PgSelectRows[88]<br />ᐳ: 87, 89, 258"):::bucket
    Bucket12("Bucket 12 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 90, 93, 250<br />ᐳRelationalTopic<br /><br />1: 916, 917<br />2: PgSelect[96]<br />ᐳ: Access[918]<br />3: PgSelectRows[101]<br />ᐳ: 100, 102, 259, 919, 920<br />4: PgSelectRows[280]<br />ᐳ: 279, 281, 465, 468, 469"):::bucket
    Bucket13("Bucket 13 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 90, 93, 250<br />ᐳRelationalPost<br /><br />1: PgSelect[104]<br />2: PgSelectRows[109]<br />ᐳ: 108, 110, 260, 282"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 90, 93, 250<br />ᐳRelationalDivider<br /><br />1: PgSelect[112]<br />2: PgSelectRows[117]<br />ᐳ: 116, 118, 261"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 90, 93, 250<br />ᐳRelationalChecklist<br /><br />1: PgSelect[120]<br />2: PgSelectRows[125]<br />ᐳ: First[124], PgSelectSingle[126]"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 90, 93, 250<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[128]<br />2: PgSelectRows[133]<br />ᐳ: 132, 134, 262"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />__typename: Lambda[287]<br />Deps: 287, 10, 283, 286"):::bucket
    Bucket19("Bucket 19 (polymorphic)<br />__typename: Lambda[332]<br />Deps: 332, 10, 328, 331"):::bucket
    Bucket20("Bucket 20 (polymorphic)<br />__typename: Lambda[377]<br />Deps: 377, 10, 373, 376"):::bucket
    Bucket21("Bucket 21 (listItem)<br />Deps: 10<br /><br />ROOT __Item{21}ᐸ135ᐳ[418]"):::bucket
    Bucket22("Bucket 22 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 283, 286<br />ᐳRelationalTopic<br /><br />1: PgSelect[289]<br />2: PgSelectRows[294]<br />ᐳ: 293, 295, 585"):::bucket
    Bucket23("Bucket 23 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 283, 286<br />ᐳRelationalPost<br /><br />1: PgSelect[297]<br />2: PgSelectRows[302]<br />ᐳ: 301, 303, 586, 597"):::bucket
    Bucket24("Bucket 24 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 283, 286<br />ᐳRelationalDivider<br /><br />1: PgSelect[305]<br />2: PgSelectRows[310]<br />ᐳ: 309, 311, 587"):::bucket
    Bucket25("Bucket 25 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 283, 286<br />ᐳRelationalChecklist<br /><br />1: PgSelect[313]<br />2: PgSelectRows[318]<br />ᐳ: First[317], PgSelectSingle[319]"):::bucket
    Bucket26("Bucket 26 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 283, 286<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[321]<br />2: PgSelectRows[326]<br />ᐳ: 325, 327, 588"):::bucket
    Bucket27("Bucket 27 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 328, 331<br />ᐳRelationalTopic<br /><br />1: PgSelect[334]<br />2: PgSelectRows[339]<br />ᐳ: 338, 340, 589"):::bucket
    Bucket28("Bucket 28 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 328, 331<br />ᐳRelationalPost<br /><br />1: PgSelect[342]<br />2: PgSelectRows[347]<br />ᐳ: 346, 348, 590, 598"):::bucket
    Bucket29("Bucket 29 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 328, 331<br />ᐳRelationalDivider<br /><br />1: PgSelect[350]<br />2: PgSelectRows[355]<br />ᐳ: 354, 356, 591"):::bucket
    Bucket30("Bucket 30 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 328, 331<br />ᐳRelationalChecklist<br /><br />1: PgSelect[358]<br />2: PgSelectRows[363]<br />ᐳ: First[362], PgSelectSingle[364]"):::bucket
    Bucket31("Bucket 31 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 328, 331<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[366]<br />2: PgSelectRows[371]<br />ᐳ: 370, 372, 592"):::bucket
    Bucket32("Bucket 32 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 373, 376<br />ᐳRelationalTopic<br /><br />1: PgSelect[379]<br />2: PgSelectRows[384]<br />ᐳ: 383, 385, 593"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 373, 376<br />ᐳRelationalPost<br /><br />1: PgSelect[387]<br />2: PgSelectRows[392]<br />ᐳ: 391, 393, 594, 599"):::bucket
    Bucket34("Bucket 34 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 373, 376<br />ᐳRelationalDivider<br /><br />1: PgSelect[395]<br />2: PgSelectRows[400]<br />ᐳ: 399, 401, 595"):::bucket
    Bucket35("Bucket 35 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 373, 376<br />ᐳRelationalChecklist<br /><br />1: PgSelect[403]<br />2: PgSelectRows[408]<br />ᐳ: First[407], PgSelectSingle[409]"):::bucket
    Bucket36("Bucket 36 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 373, 376<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[411]<br />2: PgSelectRows[416]<br />ᐳ: 415, 417, 596"):::bucket
    Bucket37("Bucket 37 (polymorphic)<br />__typename: Lambda[424]<br />Deps: 424, 10, 420, 423"):::bucket
    Bucket38("Bucket 38 (polymorphic)<br />__typename: Lambda[469]<br />Deps: 469, 10, 465, 468"):::bucket
    Bucket39("Bucket 39 (polymorphic)<br />__typename: Lambda[514]<br />Deps: 514, 10, 510, 513, 640"):::bucket
    Bucket40("Bucket 40 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 420, 423<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[426]<br />2: PgSelectRows[431]<br />ᐳ: 430, 432, 620"):::bucket
    Bucket41("Bucket 41 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 420, 423<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[434]<br />2: PgSelectRows[439]<br />ᐳ: 438, 440, 621, 628"):::bucket
    Bucket42("Bucket 42 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 420, 423<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[442]<br />2: PgSelectRows[447]<br />ᐳ: 446, 448, 622"):::bucket
    Bucket43("Bucket 43 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 420, 423<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[450]<br />2: PgSelectRows[455]<br />ᐳ: First[454], PgSelectSingle[456]"):::bucket
    Bucket44("Bucket 44 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 420, 423<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[458]<br />2: PgSelectRows[463]<br />ᐳ: 462, 464, 623"):::bucket
    Bucket45("Bucket 45 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 465, 468<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[471]<br />2: PgSelectRows[476]<br />ᐳ: 475, 477, 624"):::bucket
    Bucket46("Bucket 46 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 465, 468<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[479]<br />2: PgSelectRows[484]<br />ᐳ: 483, 485, 625, 629"):::bucket
    Bucket47("Bucket 47 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 465, 468<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[487]<br />2: PgSelectRows[492]<br />ᐳ: 491, 493, 626"):::bucket
    Bucket48("Bucket 48 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 465, 468<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[495]<br />2: PgSelectRows[500]<br />ᐳ: First[499], PgSelectSingle[501]"):::bucket
    Bucket49("Bucket 49 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 465, 468<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[503]<br />2: PgSelectRows[508]<br />ᐳ: 507, 509, 627"):::bucket
    Bucket50("Bucket 50 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 510, 513, 640<br />ᐳRelationalTopic<br /><br />1: 662, 907<br />2: PgSelect[516]<br />ᐳ: Access[908]<br />3: PgSelectRows[521]<br />ᐳ: 520, 522, 645, 685, 909, 910<br />4: PgSelectRows[664], PgSelect[683]<br />ᐳ: 663, 665, 758, 761, 762<br />5: PgSelectRows[687]<br />ᐳ: 686, 688, 703, 704"):::bucket
    Bucket51("Bucket 51 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 510, 513, 640<br />ᐳRelationalPost<br /><br />1: PgSelect[524]<br />2: PgSelectRows[529]<br />ᐳ: 528, 530, 646, 666, 693<br />3: PgSelect[689]<br />4: PgSelectRows[695]<br />ᐳ: 694, 696, 705, 706"):::bucket
    Bucket52("Bucket 52 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 510, 513, 640<br />ᐳRelationalDivider<br /><br />1: PgSelect[532]<br />2: PgSelectRows[537]<br />ᐳ: 536, 538, 647, 671<br />3: PgSelect[667]<br />4: PgSelectRows[673]<br />ᐳ: 672, 674, 699, 700"):::bucket
    Bucket53("Bucket 53 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 510, 513, 640<br />ᐳRelationalChecklist<br /><br />1: PgSelect[540]<br />2: PgSelectRows[545]<br />ᐳ: 544, 546, 652<br />3: PgSelect[648]<br />4: PgSelectRows[654]<br />ᐳ: 653, 655, 697, 698"):::bucket
    Bucket54("Bucket 54 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 510, 513, 640<br />ᐳRelationalChecklistItem<br /><br />1: PgSelect[548]<br />2: PgSelectRows[553]<br />ᐳ: 552, 554, 656, 679<br />3: PgSelect[675]<br />4: PgSelectRows[681]<br />ᐳ: 680, 682, 701, 702"):::bucket
    Bucket55("Bucket 55 (combined)<br />Deps: 10<br /><br />1: <br />ᐳ: Access[708]<br />2: PgSelect[709]<br />3: PgSelectRows[714]<br />ᐳ: 713, 715, 716, 717, 718, 823"):::bucket
    Bucket56("Bucket 56 (polymorphic)<br />__typename: Lambda[717]<br />Deps: 717, 10, 718, 716, 823"):::bucket
    Bucket57("Bucket 57 (polymorphic)<br />__typename: Lambda[762]<br />Deps: 762, 10, 758, 761"):::bucket
    Bucket58("Bucket 58 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 718, 716, 823<br />(5) ...ᐳRelationalTopic<br /><br />1: 842, 948<br />2: PgSelect[719]<br />ᐳ: Access[949]<br />3: PgSelectRows[724]<br />ᐳ: 723, 725, 832, 950, 951<br />4: PgSelectRows[844]<br />ᐳ: 843, 845, 847, 850, 851"):::bucket
    Bucket59("Bucket 59 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 718, 716, 823<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[727]<br />2: PgSelectRows[732]<br />ᐳ: 731, 733, 833, 846"):::bucket
    Bucket60("Bucket 60 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 718, 716, 823<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[735]<br />2: PgSelectRows[740]<br />ᐳ: 739, 741, 834"):::bucket
    Bucket61("Bucket 61 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 718, 716, 823<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[743]<br />2: PgSelectRows[748]<br />ᐳ: First[747], PgSelectSingle[749]"):::bucket
    Bucket62("Bucket 62 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 718, 716, 823<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[751]<br />2: PgSelectRows[756]<br />ᐳ: 755, 757, 835"):::bucket
    Bucket63("Bucket 63 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 758, 761<br />ᐳRelationalTopicᐳRelationalTopic<br /><br />1: PgSelect[764]<br />2: PgSelectRows[769]<br />ᐳ: 768, 770, 828"):::bucket
    Bucket64("Bucket 64 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 758, 761<br />ᐳRelationalTopicᐳRelationalPost<br /><br />1: PgSelect[772]<br />2: PgSelectRows[777]<br />ᐳ: 776, 778, 829, 836"):::bucket
    Bucket65("Bucket 65 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 758, 761<br />ᐳRelationalTopicᐳRelationalDivider<br /><br />1: PgSelect[780]<br />2: PgSelectRows[785]<br />ᐳ: 784, 786, 830"):::bucket
    Bucket66("Bucket 66 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 758, 761<br />ᐳRelationalTopicᐳRelationalChecklist<br /><br />1: PgSelect[788]<br />2: PgSelectRows[793]<br />ᐳ: First[792], PgSelectSingle[794]"):::bucket
    Bucket67("Bucket 67 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 758, 761<br />ᐳRelationalTopicᐳRelationalChecklistItem<br /><br />1: PgSelect[796]<br />2: PgSelectRows[801]<br />ᐳ: 800, 802, 831"):::bucket
    Bucket68("Bucket 68 (polymorphic)<br />__typename: Lambda[851]<br />Deps: 851, 10, 847, 850"):::bucket
    Bucket69("Bucket 69 (polymorphicPartition)<br />|RelationalTopic<br />Deps: 10, 847, 850<br />(5) ...ᐳRelationalTopic<br /><br />1: PgSelect[853]<br />2: PgSelectRows[858]<br />ᐳ: 857, 859, 902"):::bucket
    Bucket70("Bucket 70 (polymorphicPartition)<br />|RelationalPost<br />Deps: 10, 847, 850<br />(5) ...ᐳRelationalPost<br /><br />1: PgSelect[861]<br />2: PgSelectRows[866]<br />ᐳ: 865, 867, 903, 906"):::bucket
    Bucket71("Bucket 71 (polymorphicPartition)<br />|RelationalDivider<br />Deps: 10, 847, 850<br />(5) ...ᐳRelationalDivider<br /><br />1: PgSelect[869]<br />2: PgSelectRows[874]<br />ᐳ: 873, 875, 904"):::bucket
    Bucket72("Bucket 72 (polymorphicPartition)<br />|RelationalChecklist<br />Deps: 10, 847, 850<br />(5) ...ᐳRelationalChecklist<br /><br />1: PgSelect[877]<br />2: PgSelectRows[882]<br />ᐳ: First[881], PgSelectSingle[883]"):::bucket
    Bucket73("Bucket 73 (polymorphicPartition)<br />|RelationalChecklistItem<br />Deps: 10, 847, 850<br />(5) ...ᐳRelationalChecklistItem<br /><br />1: PgSelect[885]<br />2: PgSelectRows[890]<br />ᐳ: 889, 891, 905"):::bucket
    end
    Bucket0 --> Bucket1 & Bucket2 & Bucket3 & Bucket4 & Bucket5 & Bucket6
    Bucket1 --> Bucket21
    Bucket2 --> Bucket18
    Bucket3 --> Bucket19
    Bucket4 --> Bucket20
    Bucket5 --> Bucket7 & Bucket8 & Bucket9 & Bucket10 & Bucket11
    Bucket6 --> Bucket12 & Bucket13 & Bucket14 & Bucket15 & Bucket16
    Bucket7 --> Bucket37
    Bucket12 --> Bucket38
    Bucket18 --> Bucket22 & Bucket23 & Bucket24 & Bucket25 & Bucket26
    Bucket19 --> Bucket27 & Bucket28 & Bucket29 & Bucket30 & Bucket31
    Bucket20 --> Bucket32 & Bucket33 & Bucket34 & Bucket35 & Bucket36
    Bucket21 --> Bucket39
    Bucket37 --> Bucket40 & Bucket41 & Bucket42 & Bucket43 & Bucket44
    Bucket38 --> Bucket45 & Bucket46 & Bucket47 & Bucket48 & Bucket49
    Bucket39 --> Bucket50 & Bucket51 & Bucket52 & Bucket53 & Bucket54
    Bucket50 --> Bucket55 & Bucket57
    Bucket51 --> Bucket55
    Bucket52 --> Bucket55
    Bucket53 --> Bucket55
    Bucket54 --> Bucket55
    Bucket55 --> Bucket56
    Bucket56 --> Bucket58 & Bucket59 & Bucket60 & Bucket61 & Bucket62
    Bucket57 --> Bucket63 & Bucket64 & Bucket65 & Bucket66 & Bucket67
    Bucket58 --> Bucket68
    Bucket68 --> Bucket69 & Bucket70 & Bucket71 & Bucket72 & Bucket73

    %% plan dependencies
    PgSelect26[["PgSelect[26∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression28{{"PgFromExpression[28∈0] ➊<br />More deps:<br />- Constantᐸ-1ᐳ[953]"}}:::plan
    PgSelectInlineApply921["PgSelectInlineApply[921∈0] ➊"]:::plan
    PgFromExpression925{{"PgFromExpression[925∈0] ➊"}}:::plan
    PgSelectInlineApply926["PgSelectInlineApply[926∈0] ➊"]:::plan
    PgFromExpression28 & PgSelectInlineApply921 & PgFromExpression925 & PgSelectInlineApply926 --> PgSelect26
    PgSelect32[["PgSelect[32∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression34{{"PgFromExpression[34∈0] ➊<br />More deps:<br />- Constantᐸ16ᐳ[952]"}}:::plan
    PgSelectInlineApply930["PgSelectInlineApply[930∈0] ➊"]:::plan
    PgFromExpression934{{"PgFromExpression[934∈0] ➊"}}:::plan
    PgSelectInlineApply935["PgSelectInlineApply[935∈0] ➊"]:::plan
    PgFromExpression34 & PgSelectInlineApply930 & PgFromExpression934 & PgSelectInlineApply935 --> PgSelect32
    PgSelect39[["PgSelect[39∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression41{{"PgFromExpression[41∈0] ➊<br />More deps:<br />- Constantᐸ11ᐳ[954]"}}:::plan
    PgSelectInlineApply939["PgSelectInlineApply[939∈0] ➊"]:::plan
    PgFromExpression943{{"PgFromExpression[943∈0] ➊"}}:::plan
    PgSelectInlineApply944["PgSelectInlineApply[944∈0] ➊"]:::plan
    PgFromExpression41 & PgSelectInlineApply939 & PgFromExpression943 & PgSelectInlineApply944 --> PgSelect39
    Object10{{"Object[10∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 67"}}:::plan
    Access8{{"Access[8∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access8 & Access9 --> Object10
    PgSelect13[["PgSelect[13∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression15{{"PgFromExpression[15∈0] ➊<br />More deps:<br />- Constantᐸ16ᐳ[952]"}}:::plan
    PgFromExpression15 --> PgSelect13
    PgSelect20[["PgSelect[20∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression22{{"PgFromExpression[22∈0] ➊<br />More deps:<br />- Constantᐸ-1ᐳ[953]"}}:::plan
    PgFromExpression22 --> PgSelect20
    PgSelect7[["PgSelect[7∈0] ➊<br />ᐸall_relational_items_fnᐳ<br />More deps:<br />- Object[10]"]]:::plan
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access8
    __Value2 --> Access9
    Connection11[["Connection[11∈0] ➊<br />ᐸ7ᐳ"]]:::plan
    PgSelect7 --> Connection11
    First16{{"First[16∈0] ➊"}}:::plan
    PgSelectRows17[["PgSelectRows[17∈0] ➊"]]:::plan
    PgSelectRows17 --> First16
    PgSelect13 --> PgSelectRows17
    PgSelectSingle18{{"PgSelectSingle[18∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ"}}:::plan
    First16 --> PgSelectSingle18
    First23{{"First[23∈0] ➊"}}:::plan
    PgSelectRows24[["PgSelectRows[24∈0] ➊"]]:::plan
    PgSelectRows24 --> First23
    PgSelect20 --> PgSelectRows24
    PgSelectSingle25{{"PgSelectSingle[25∈0] ➊<br />ᐸrelational_item_by_id_fnᐳ"}}:::plan
    First23 --> PgSelectSingle25
    First29{{"First[29∈0] ➊"}}:::plan
    PgSelectRows30[["PgSelectRows[30∈0] ➊"]]:::plan
    PgSelectRows30 --> First29
    PgSelect26 --> PgSelectRows30
    PgSelectSingle31{{"PgSelectSingle[31∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First29 --> PgSelectSingle31
    First35{{"First[35∈0] ➊"}}:::plan
    PgSelectRows36[["PgSelectRows[36∈0] ➊"]]:::plan
    PgSelectRows36 --> First35
    PgSelect32 --> PgSelectRows36
    PgSelectSingle37{{"PgSelectSingle[37∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First35 --> PgSelectSingle37
    First42{{"First[42∈0] ➊"}}:::plan
    PgSelectRows43[["PgSelectRows[43∈0] ➊"]]:::plan
    PgSelectRows43 --> First42
    PgSelect39 --> PgSelectRows43
    PgSelectSingle44{{"PgSelectSingle[44∈0] ➊<br />ᐸrelational_topic_by_id_fnᐳ"}}:::plan
    First42 --> PgSelectSingle44
    PgClassExpression45{{"PgClassExpression[45∈0] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression45
    PgClassExpression48{{"PgClassExpression[48∈0] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle18 --> PgClassExpression48
    PgClassExpression90{{"PgClassExpression[90∈0] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle25 --> PgClassExpression90
    PgClassExpression93{{"PgClassExpression[93∈0] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle25 --> PgClassExpression93
    ConnectionItems135[["ConnectionItems[135∈0] ➊"]]:::plan
    Connection11 --> ConnectionItems135
    Access922{{"Access[922∈0] ➊<br />ᐸ26.m.joinDetailsFor139ᐳ"}}:::plan
    PgSelect26 --> Access922
    Access927{{"Access[927∈0] ➊<br />ᐸ26.m.joinDetailsFor205ᐳ"}}:::plan
    PgSelect26 --> Access927
    Access931{{"Access[931∈0] ➊<br />ᐸ32.m.joinDetailsFor148ᐳ"}}:::plan
    PgSelect32 --> Access931
    Access936{{"Access[936∈0] ➊<br />ᐸ32.m.joinDetailsFor212ᐳ"}}:::plan
    PgSelect32 --> Access936
    Access940{{"Access[940∈0] ➊<br />ᐸ39.m.joinDetailsFor157ᐳ"}}:::plan
    PgSelect39 --> Access940
    Access945{{"Access[945∈0] ➊<br />ᐸ39.m.joinDetailsFor219ᐳ"}}:::plan
    PgSelect39 --> Access945
    List923{{"List[923∈2] ➊<br />ᐸ922,31ᐳ"}}:::plan
    Access922 & PgSelectSingle31 --> List923
    List928{{"List[928∈2] ➊<br />ᐸ927,31ᐳ"}}:::plan
    Access927 & PgSelectSingle31 --> List928
    First143{{"First[143∈2] ➊"}}:::plan
    PgSelectRows144[["PgSelectRows[144∈2] ➊"]]:::plan
    PgSelectRows144 --> First143
    Lambda924{{"Lambda[924∈2] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda924 --> PgSelectRows144
    PgSelectSingle145{{"PgSelectSingle[145∈2] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First143 --> PgSelectSingle145
    PgClassExpression146{{"PgClassExpression[146∈2] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle145 --> PgClassExpression146
    PgClassExpression170{{"PgClassExpression[170∈2] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression146 o--o PgClassExpression170
    PgClassExpression188{{"PgClassExpression[188∈2] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression170 o--o PgClassExpression188
    PgClassExpression201{{"PgClassExpression[201∈2] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression201
    First208{{"First[208∈2] ➊"}}:::plan
    PgSelectRows209[["PgSelectRows[209∈2] ➊"]]:::plan
    PgSelectRows209 --> First208
    Lambda929{{"Lambda[929∈2] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda929 --> PgSelectRows209
    PgSelectSingle210{{"PgSelectSingle[210∈2] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First208 --> PgSelectSingle210
    PgClassExpression283{{"PgClassExpression[283∈2] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle210 --> PgClassExpression283
    PgClassExpression286{{"PgClassExpression[286∈2] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle210 --> PgClassExpression286
    Lambda287{{"Lambda[287∈2] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression286 --> Lambda287
    List923 --> Lambda924
    List928 --> Lambda929
    List932{{"List[932∈3] ➊<br />ᐸ931,37ᐳ"}}:::plan
    Access931 & PgSelectSingle37 --> List932
    List937{{"List[937∈3] ➊<br />ᐸ936,37ᐳ"}}:::plan
    Access936 & PgSelectSingle37 --> List937
    First152{{"First[152∈3] ➊"}}:::plan
    PgSelectRows153[["PgSelectRows[153∈3] ➊"]]:::plan
    PgSelectRows153 --> First152
    Lambda933{{"Lambda[933∈3] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda933 --> PgSelectRows153
    PgSelectSingle154{{"PgSelectSingle[154∈3] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First152 --> PgSelectSingle154
    PgClassExpression155{{"PgClassExpression[155∈3] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle154 --> PgClassExpression155
    PgClassExpression176{{"PgClassExpression[176∈3] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression155 o--o PgClassExpression176
    PgClassExpression194{{"PgClassExpression[194∈3] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression176 o--o PgClassExpression194
    PgClassExpression202{{"PgClassExpression[202∈3] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression202
    First215{{"First[215∈3] ➊"}}:::plan
    PgSelectRows216[["PgSelectRows[216∈3] ➊"]]:::plan
    PgSelectRows216 --> First215
    Lambda938{{"Lambda[938∈3] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda938 --> PgSelectRows216
    PgSelectSingle217{{"PgSelectSingle[217∈3] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First215 --> PgSelectSingle217
    PgClassExpression328{{"PgClassExpression[328∈3] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression328
    PgClassExpression331{{"PgClassExpression[331∈3] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle217 --> PgClassExpression331
    Lambda332{{"Lambda[332∈3] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression331 --> Lambda332
    List932 --> Lambda933
    List937 --> Lambda938
    List941{{"List[941∈4] ➊<br />ᐸ940,44ᐳ"}}:::plan
    Access940 & PgSelectSingle44 --> List941
    List946{{"List[946∈4] ➊<br />ᐸ945,44ᐳ"}}:::plan
    Access945 & PgSelectSingle44 --> List946
    First161{{"First[161∈4] ➊"}}:::plan
    PgSelectRows162[["PgSelectRows[162∈4] ➊"]]:::plan
    PgSelectRows162 --> First161
    Lambda942{{"Lambda[942∈4] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda942 --> PgSelectRows162
    PgSelectSingle163{{"PgSelectSingle[163∈4] ➊<br />ᐸrelational_itemsᐳ"}}:::plan
    First161 --> PgSelectSingle163
    PgClassExpression164{{"PgClassExpression[164∈4] ➊<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle163 --> PgClassExpression164
    PgClassExpression182{{"PgClassExpression[182∈4] ➊<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgClassExpression164 o--o PgClassExpression182
    PgClassExpression200{{"PgClassExpression[200∈4] ➊<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgClassExpression182 o--o PgClassExpression200
    PgClassExpression203{{"PgClassExpression[203∈4] ➊<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression203
    First222{{"First[222∈4] ➊"}}:::plan
    PgSelectRows223[["PgSelectRows[223∈4] ➊"]]:::plan
    PgSelectRows223 --> First222
    Lambda947{{"Lambda[947∈4] ➊<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda947 --> PgSelectRows223
    PgSelectSingle224{{"PgSelectSingle[224∈4] ➊<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First222 --> PgSelectSingle224
    PgClassExpression373{{"PgClassExpression[373∈4] ➊<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression373
    PgClassExpression376{{"PgClassExpression[376∈4] ➊<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle224 --> PgClassExpression376
    Lambda377{{"Lambda[377∈4] ➊<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression376 --> Lambda377
    List941 --> Lambda942
    List946 --> Lambda947
    PgSelect51[["PgSelect[51∈7] ➊^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression911{{"PgFromExpression[911∈7] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply912["PgSelectInlineApply[912∈7] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression45 & PgFromExpression911 & PgSelectInlineApply912 --> PgSelect51
    List914{{"List[914∈7] ➊^<br />ᐸ913,57ᐳ"}}:::plan
    Access913{{"Access[913∈7] ➊^<br />ᐸ51.m.joinDetailsFor264ᐳ"}}:::plan
    PgSelectSingle57{{"PgSelectSingle[57∈7] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access913 & PgSelectSingle57 --> List914
    First55{{"First[55∈7] ➊^"}}:::plan
    PgSelectRows56[["PgSelectRows[56∈7] ➊^"]]:::plan
    PgSelectRows56 --> First55
    PgSelect51 --> PgSelectRows56
    First55 --> PgSelectSingle57
    PgClassExpression255{{"PgClassExpression[255∈7] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle57 --> PgClassExpression255
    First269{{"First[269∈7] ➊^"}}:::plan
    PgSelectRows270[["PgSelectRows[270∈7] ➊^"]]:::plan
    PgSelectRows270 --> First269
    Lambda915{{"Lambda[915∈7] ➊^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda915 --> PgSelectRows270
    PgSelectSingle271{{"PgSelectSingle[271∈7] ➊^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First269 --> PgSelectSingle271
    PgClassExpression420{{"PgClassExpression[420∈7] ➊^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle271 --> PgClassExpression420
    PgClassExpression423{{"PgClassExpression[423∈7] ➊^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle271 --> PgClassExpression423
    Lambda424{{"Lambda[424∈7] ➊^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression423 --> Lambda424
    PgSelect51 --> Access913
    List914 --> Lambda915
    PgSelect59[["PgSelect[59∈8] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect59
    First63{{"First[63∈8] ➊^"}}:::plan
    PgSelectRows64[["PgSelectRows[64∈8] ➊^"]]:::plan
    PgSelectRows64 --> First63
    PgSelect59 --> PgSelectRows64
    PgSelectSingle65{{"PgSelectSingle[65∈8] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First63 --> PgSelectSingle65
    PgClassExpression256{{"PgClassExpression[256∈8] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle65 --> PgClassExpression256
    PgClassExpression272{{"PgClassExpression[272∈8] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression256 o--o PgClassExpression272
    PgSelect67[["PgSelect[67∈9] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect67
    First71{{"First[71∈9] ➊^"}}:::plan
    PgSelectRows72[["PgSelectRows[72∈9] ➊^"]]:::plan
    PgSelectRows72 --> First71
    PgSelect67 --> PgSelectRows72
    PgSelectSingle73{{"PgSelectSingle[73∈9] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First71 --> PgSelectSingle73
    PgClassExpression257{{"PgClassExpression[257∈9] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle73 --> PgClassExpression257
    PgSelect75[["PgSelect[75∈10] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect75
    First79{{"First[79∈10] ➊^"}}:::plan
    PgSelectRows80[["PgSelectRows[80∈10] ➊^"]]:::plan
    PgSelectRows80 --> First79
    PgSelect75 --> PgSelectRows80
    PgSelectSingle81{{"PgSelectSingle[81∈10] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First79 --> PgSelectSingle81
    PgSelect83[["PgSelect[83∈11] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression45 --> PgSelect83
    First87{{"First[87∈11] ➊^"}}:::plan
    PgSelectRows88[["PgSelectRows[88∈11] ➊^"]]:::plan
    PgSelectRows88 --> First87
    PgSelect83 --> PgSelectRows88
    PgSelectSingle89{{"PgSelectSingle[89∈11] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First87 --> PgSelectSingle89
    PgClassExpression258{{"PgClassExpression[258∈11] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle89 --> PgClassExpression258
    PgSelect96[["PgSelect[96∈12] ➊^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression916{{"PgFromExpression[916∈12] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply917["PgSelectInlineApply[917∈12] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression90 & PgFromExpression916 & PgSelectInlineApply917 --> PgSelect96
    List919{{"List[919∈12] ➊^<br />ᐸ918,102ᐳ"}}:::plan
    Access918{{"Access[918∈12] ➊^<br />ᐸ96.m.joinDetailsFor274ᐳ"}}:::plan
    PgSelectSingle102{{"PgSelectSingle[102∈12] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access918 & PgSelectSingle102 --> List919
    First100{{"First[100∈12] ➊^"}}:::plan
    PgSelectRows101[["PgSelectRows[101∈12] ➊^"]]:::plan
    PgSelectRows101 --> First100
    PgSelect96 --> PgSelectRows101
    First100 --> PgSelectSingle102
    PgClassExpression259{{"PgClassExpression[259∈12] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression259
    First279{{"First[279∈12] ➊^"}}:::plan
    PgSelectRows280[["PgSelectRows[280∈12] ➊^"]]:::plan
    PgSelectRows280 --> First279
    Lambda920{{"Lambda[920∈12] ➊^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda920 --> PgSelectRows280
    PgSelectSingle281{{"PgSelectSingle[281∈12] ➊^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First279 --> PgSelectSingle281
    PgClassExpression465{{"PgClassExpression[465∈12] ➊^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression465
    PgClassExpression468{{"PgClassExpression[468∈12] ➊^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle281 --> PgClassExpression468
    Lambda469{{"Lambda[469∈12] ➊^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression468 --> Lambda469
    PgSelect96 --> Access918
    List919 --> Lambda920
    PgSelect104[["PgSelect[104∈13] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect104
    First108{{"First[108∈13] ➊^"}}:::plan
    PgSelectRows109[["PgSelectRows[109∈13] ➊^"]]:::plan
    PgSelectRows109 --> First108
    PgSelect104 --> PgSelectRows109
    PgSelectSingle110{{"PgSelectSingle[110∈13] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First108 --> PgSelectSingle110
    PgClassExpression260{{"PgClassExpression[260∈13] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle110 --> PgClassExpression260
    PgClassExpression282{{"PgClassExpression[282∈13] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression260 o--o PgClassExpression282
    PgSelect112[["PgSelect[112∈14] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect112
    First116{{"First[116∈14] ➊^"}}:::plan
    PgSelectRows117[["PgSelectRows[117∈14] ➊^"]]:::plan
    PgSelectRows117 --> First116
    PgSelect112 --> PgSelectRows117
    PgSelectSingle118{{"PgSelectSingle[118∈14] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First116 --> PgSelectSingle118
    PgClassExpression261{{"PgClassExpression[261∈14] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle118 --> PgClassExpression261
    PgSelect120[["PgSelect[120∈15] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect120
    First124{{"First[124∈15] ➊^"}}:::plan
    PgSelectRows125[["PgSelectRows[125∈15] ➊^"]]:::plan
    PgSelectRows125 --> First124
    PgSelect120 --> PgSelectRows125
    PgSelectSingle126{{"PgSelectSingle[126∈15] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First124 --> PgSelectSingle126
    PgSelect128[["PgSelect[128∈16] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression90 --> PgSelect128
    First132{{"First[132∈16] ➊^"}}:::plan
    PgSelectRows133[["PgSelectRows[133∈16] ➊^"]]:::plan
    PgSelectRows133 --> First132
    PgSelect128 --> PgSelectRows133
    PgSelectSingle134{{"PgSelectSingle[134∈16] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First132 --> PgSelectSingle134
    PgClassExpression262{{"PgClassExpression[262∈16] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle134 --> PgClassExpression262
    __Item418[/"__Item[418∈21]<br />ᐸ135ᐳ"\]:::itemplan
    ConnectionItems135 ==> __Item418
    PgSelectSingle419{{"PgSelectSingle[419∈21]<br />ᐸall_relational_items_fnᐳ"}}:::plan
    __Item418 --> PgSelectSingle419
    PgClassExpression510{{"PgClassExpression[510∈21]<br />ᐸ__all_rela..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle419 --> PgClassExpression510
    PgClassExpression513{{"PgClassExpression[513∈21]<br />ᐸ__all_rela...n__.”type”ᐳ"}}:::plan
    PgSelectSingle419 --> PgClassExpression513
    Lambda514{{"Lambda[514∈21]<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression513 --> Lambda514
    PgClassExpression640{{"PgClassExpression[640∈21]<br />ᐸ__all_rela...parent_id”ᐳ"}}:::plan
    PgSelectSingle419 --> PgClassExpression640
    PgSelect289[["PgSelect[289∈22] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression283 --> PgSelect289
    First293{{"First[293∈22] ➊^"}}:::plan
    PgSelectRows294[["PgSelectRows[294∈22] ➊^"]]:::plan
    PgSelectRows294 --> First293
    PgSelect289 --> PgSelectRows294
    PgSelectSingle295{{"PgSelectSingle[295∈22] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First293 --> PgSelectSingle295
    PgClassExpression585{{"PgClassExpression[585∈22] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle295 --> PgClassExpression585
    PgSelect297[["PgSelect[297∈23] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression283 --> PgSelect297
    First301{{"First[301∈23] ➊^"}}:::plan
    PgSelectRows302[["PgSelectRows[302∈23] ➊^"]]:::plan
    PgSelectRows302 --> First301
    PgSelect297 --> PgSelectRows302
    PgSelectSingle303{{"PgSelectSingle[303∈23] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First301 --> PgSelectSingle303
    PgClassExpression586{{"PgClassExpression[586∈23] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle303 --> PgClassExpression586
    PgClassExpression597{{"PgClassExpression[597∈23] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression586 o--o PgClassExpression597
    PgSelect305[["PgSelect[305∈24] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression283 --> PgSelect305
    First309{{"First[309∈24] ➊^"}}:::plan
    PgSelectRows310[["PgSelectRows[310∈24] ➊^"]]:::plan
    PgSelectRows310 --> First309
    PgSelect305 --> PgSelectRows310
    PgSelectSingle311{{"PgSelectSingle[311∈24] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First309 --> PgSelectSingle311
    PgClassExpression587{{"PgClassExpression[587∈24] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle311 --> PgClassExpression587
    PgSelect313[["PgSelect[313∈25] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression283 --> PgSelect313
    First317{{"First[317∈25] ➊^"}}:::plan
    PgSelectRows318[["PgSelectRows[318∈25] ➊^"]]:::plan
    PgSelectRows318 --> First317
    PgSelect313 --> PgSelectRows318
    PgSelectSingle319{{"PgSelectSingle[319∈25] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First317 --> PgSelectSingle319
    PgSelect321[["PgSelect[321∈26] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression283 --> PgSelect321
    First325{{"First[325∈26] ➊^"}}:::plan
    PgSelectRows326[["PgSelectRows[326∈26] ➊^"]]:::plan
    PgSelectRows326 --> First325
    PgSelect321 --> PgSelectRows326
    PgSelectSingle327{{"PgSelectSingle[327∈26] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First325 --> PgSelectSingle327
    PgClassExpression588{{"PgClassExpression[588∈26] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle327 --> PgClassExpression588
    PgSelect334[["PgSelect[334∈27] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression328 --> PgSelect334
    First338{{"First[338∈27] ➊^"}}:::plan
    PgSelectRows339[["PgSelectRows[339∈27] ➊^"]]:::plan
    PgSelectRows339 --> First338
    PgSelect334 --> PgSelectRows339
    PgSelectSingle340{{"PgSelectSingle[340∈27] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First338 --> PgSelectSingle340
    PgClassExpression589{{"PgClassExpression[589∈27] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle340 --> PgClassExpression589
    PgSelect342[["PgSelect[342∈28] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression328 --> PgSelect342
    First346{{"First[346∈28] ➊^"}}:::plan
    PgSelectRows347[["PgSelectRows[347∈28] ➊^"]]:::plan
    PgSelectRows347 --> First346
    PgSelect342 --> PgSelectRows347
    PgSelectSingle348{{"PgSelectSingle[348∈28] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First346 --> PgSelectSingle348
    PgClassExpression590{{"PgClassExpression[590∈28] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle348 --> PgClassExpression590
    PgClassExpression598{{"PgClassExpression[598∈28] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression590 o--o PgClassExpression598
    PgSelect350[["PgSelect[350∈29] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression328 --> PgSelect350
    First354{{"First[354∈29] ➊^"}}:::plan
    PgSelectRows355[["PgSelectRows[355∈29] ➊^"]]:::plan
    PgSelectRows355 --> First354
    PgSelect350 --> PgSelectRows355
    PgSelectSingle356{{"PgSelectSingle[356∈29] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First354 --> PgSelectSingle356
    PgClassExpression591{{"PgClassExpression[591∈29] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle356 --> PgClassExpression591
    PgSelect358[["PgSelect[358∈30] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression328 --> PgSelect358
    First362{{"First[362∈30] ➊^"}}:::plan
    PgSelectRows363[["PgSelectRows[363∈30] ➊^"]]:::plan
    PgSelectRows363 --> First362
    PgSelect358 --> PgSelectRows363
    PgSelectSingle364{{"PgSelectSingle[364∈30] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First362 --> PgSelectSingle364
    PgSelect366[["PgSelect[366∈31] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression328 --> PgSelect366
    First370{{"First[370∈31] ➊^"}}:::plan
    PgSelectRows371[["PgSelectRows[371∈31] ➊^"]]:::plan
    PgSelectRows371 --> First370
    PgSelect366 --> PgSelectRows371
    PgSelectSingle372{{"PgSelectSingle[372∈31] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First370 --> PgSelectSingle372
    PgClassExpression592{{"PgClassExpression[592∈31] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle372 --> PgClassExpression592
    PgSelect379[["PgSelect[379∈32] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression373 --> PgSelect379
    First383{{"First[383∈32] ➊^"}}:::plan
    PgSelectRows384[["PgSelectRows[384∈32] ➊^"]]:::plan
    PgSelectRows384 --> First383
    PgSelect379 --> PgSelectRows384
    PgSelectSingle385{{"PgSelectSingle[385∈32] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First383 --> PgSelectSingle385
    PgClassExpression593{{"PgClassExpression[593∈32] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle385 --> PgClassExpression593
    PgSelect387[["PgSelect[387∈33] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression373 --> PgSelect387
    First391{{"First[391∈33] ➊^"}}:::plan
    PgSelectRows392[["PgSelectRows[392∈33] ➊^"]]:::plan
    PgSelectRows392 --> First391
    PgSelect387 --> PgSelectRows392
    PgSelectSingle393{{"PgSelectSingle[393∈33] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First391 --> PgSelectSingle393
    PgClassExpression594{{"PgClassExpression[594∈33] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle393 --> PgClassExpression594
    PgClassExpression599{{"PgClassExpression[599∈33] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression594 o--o PgClassExpression599
    PgSelect395[["PgSelect[395∈34] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression373 --> PgSelect395
    First399{{"First[399∈34] ➊^"}}:::plan
    PgSelectRows400[["PgSelectRows[400∈34] ➊^"]]:::plan
    PgSelectRows400 --> First399
    PgSelect395 --> PgSelectRows400
    PgSelectSingle401{{"PgSelectSingle[401∈34] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First399 --> PgSelectSingle401
    PgClassExpression595{{"PgClassExpression[595∈34] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle401 --> PgClassExpression595
    PgSelect403[["PgSelect[403∈35] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression373 --> PgSelect403
    First407{{"First[407∈35] ➊^"}}:::plan
    PgSelectRows408[["PgSelectRows[408∈35] ➊^"]]:::plan
    PgSelectRows408 --> First407
    PgSelect403 --> PgSelectRows408
    PgSelectSingle409{{"PgSelectSingle[409∈35] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First407 --> PgSelectSingle409
    PgSelect411[["PgSelect[411∈36] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression373 --> PgSelect411
    First415{{"First[415∈36] ➊^"}}:::plan
    PgSelectRows416[["PgSelectRows[416∈36] ➊^"]]:::plan
    PgSelectRows416 --> First415
    PgSelect411 --> PgSelectRows416
    PgSelectSingle417{{"PgSelectSingle[417∈36] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First415 --> PgSelectSingle417
    PgClassExpression596{{"PgClassExpression[596∈36] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle417 --> PgClassExpression596
    PgSelect426[["PgSelect[426∈40] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression420 --> PgSelect426
    First430{{"First[430∈40] ➊^"}}:::plan
    PgSelectRows431[["PgSelectRows[431∈40] ➊^"]]:::plan
    PgSelectRows431 --> First430
    PgSelect426 --> PgSelectRows431
    PgSelectSingle432{{"PgSelectSingle[432∈40] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First430 --> PgSelectSingle432
    PgClassExpression620{{"PgClassExpression[620∈40] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle432 --> PgClassExpression620
    PgSelect434[["PgSelect[434∈41] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression420 --> PgSelect434
    First438{{"First[438∈41] ➊^"}}:::plan
    PgSelectRows439[["PgSelectRows[439∈41] ➊^"]]:::plan
    PgSelectRows439 --> First438
    PgSelect434 --> PgSelectRows439
    PgSelectSingle440{{"PgSelectSingle[440∈41] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First438 --> PgSelectSingle440
    PgClassExpression621{{"PgClassExpression[621∈41] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle440 --> PgClassExpression621
    PgClassExpression628{{"PgClassExpression[628∈41] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression621 o--o PgClassExpression628
    PgSelect442[["PgSelect[442∈42] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression420 --> PgSelect442
    First446{{"First[446∈42] ➊^"}}:::plan
    PgSelectRows447[["PgSelectRows[447∈42] ➊^"]]:::plan
    PgSelectRows447 --> First446
    PgSelect442 --> PgSelectRows447
    PgSelectSingle448{{"PgSelectSingle[448∈42] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First446 --> PgSelectSingle448
    PgClassExpression622{{"PgClassExpression[622∈42] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle448 --> PgClassExpression622
    PgSelect450[["PgSelect[450∈43] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression420 --> PgSelect450
    First454{{"First[454∈43] ➊^"}}:::plan
    PgSelectRows455[["PgSelectRows[455∈43] ➊^"]]:::plan
    PgSelectRows455 --> First454
    PgSelect450 --> PgSelectRows455
    PgSelectSingle456{{"PgSelectSingle[456∈43] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First454 --> PgSelectSingle456
    PgSelect458[["PgSelect[458∈44] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression420 --> PgSelect458
    First462{{"First[462∈44] ➊^"}}:::plan
    PgSelectRows463[["PgSelectRows[463∈44] ➊^"]]:::plan
    PgSelectRows463 --> First462
    PgSelect458 --> PgSelectRows463
    PgSelectSingle464{{"PgSelectSingle[464∈44] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First462 --> PgSelectSingle464
    PgClassExpression623{{"PgClassExpression[623∈44] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle464 --> PgClassExpression623
    PgSelect471[["PgSelect[471∈45] ➊<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression465 --> PgSelect471
    First475{{"First[475∈45] ➊^"}}:::plan
    PgSelectRows476[["PgSelectRows[476∈45] ➊^"]]:::plan
    PgSelectRows476 --> First475
    PgSelect471 --> PgSelectRows476
    PgSelectSingle477{{"PgSelectSingle[477∈45] ➊^<br />ᐸrelational_topicsᐳ"}}:::plan
    First475 --> PgSelectSingle477
    PgClassExpression624{{"PgClassExpression[624∈45] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle477 --> PgClassExpression624
    PgSelect479[["PgSelect[479∈46] ➊<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression465 --> PgSelect479
    First483{{"First[483∈46] ➊^"}}:::plan
    PgSelectRows484[["PgSelectRows[484∈46] ➊^"]]:::plan
    PgSelectRows484 --> First483
    PgSelect479 --> PgSelectRows484
    PgSelectSingle485{{"PgSelectSingle[485∈46] ➊^<br />ᐸrelational_postsᐳ"}}:::plan
    First483 --> PgSelectSingle485
    PgClassExpression625{{"PgClassExpression[625∈46] ➊^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle485 --> PgClassExpression625
    PgClassExpression629{{"PgClassExpression[629∈46] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression625 o--o PgClassExpression629
    PgSelect487[["PgSelect[487∈47] ➊<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression465 --> PgSelect487
    First491{{"First[491∈47] ➊^"}}:::plan
    PgSelectRows492[["PgSelectRows[492∈47] ➊^"]]:::plan
    PgSelectRows492 --> First491
    PgSelect487 --> PgSelectRows492
    PgSelectSingle493{{"PgSelectSingle[493∈47] ➊^<br />ᐸrelational_dividersᐳ"}}:::plan
    First491 --> PgSelectSingle493
    PgClassExpression626{{"PgClassExpression[626∈47] ➊^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle493 --> PgClassExpression626
    PgSelect495[["PgSelect[495∈48] ➊<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression465 --> PgSelect495
    First499{{"First[499∈48] ➊^"}}:::plan
    PgSelectRows500[["PgSelectRows[500∈48] ➊^"]]:::plan
    PgSelectRows500 --> First499
    PgSelect495 --> PgSelectRows500
    PgSelectSingle501{{"PgSelectSingle[501∈48] ➊^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First499 --> PgSelectSingle501
    PgSelect503[["PgSelect[503∈49] ➊<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression465 --> PgSelect503
    First507{{"First[507∈49] ➊^"}}:::plan
    PgSelectRows508[["PgSelectRows[508∈49] ➊^"]]:::plan
    PgSelectRows508 --> First507
    PgSelect503 --> PgSelectRows508
    PgSelectSingle509{{"PgSelectSingle[509∈49] ➊^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First507 --> PgSelectSingle509
    PgClassExpression627{{"PgClassExpression[627∈49] ➊^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle509 --> PgClassExpression627
    PgSelect516[["PgSelect[516∈50]^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression662{{"PgFromExpression[662∈50] ➊<br />ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply907["PgSelectInlineApply[907∈50] ➊<br />ᐳRelationalTopic"]:::plan
    PgClassExpression510 & PgFromExpression662 & PgSelectInlineApply907 --> PgSelect516
    PgSelect683[["PgSelect[683∈50]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression685{{"PgClassExpression[685∈50]^<br />ᐸ__relation...c_item_id”ᐳ"}}:::plan
    PgClassExpression685 --> PgSelect683
    List909{{"List[909∈50]^<br />ᐸ908,522ᐳ"}}:::plan
    Access908{{"Access[908∈50]^<br />ᐸ516.m.joinDetailsFor658ᐳ"}}:::plan
    PgSelectSingle522{{"PgSelectSingle[522∈50]^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access908 & PgSelectSingle522 --> List909
    First520{{"First[520∈50]^"}}:::plan
    PgSelectRows521[["PgSelectRows[521∈50]^"]]:::plan
    PgSelectRows521 --> First520
    PgSelect516 --> PgSelectRows521
    First520 --> PgSelectSingle522
    PgClassExpression645{{"PgClassExpression[645∈50]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle522 --> PgClassExpression645
    First663{{"First[663∈50]^"}}:::plan
    PgSelectRows664[["PgSelectRows[664∈50]^"]]:::plan
    PgSelectRows664 --> First663
    Lambda910{{"Lambda[910∈50]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda910 --> PgSelectRows664
    PgSelectSingle665{{"PgSelectSingle[665∈50]^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First663 --> PgSelectSingle665
    PgSelectSingle522 --> PgClassExpression685
    First686{{"First[686∈50]^"}}:::plan
    PgSelectRows687[["PgSelectRows[687∈50]^"]]:::plan
    PgSelectRows687 --> First686
    PgSelect683 --> PgSelectRows687
    PgSelectSingle688{{"PgSelectSingle[688∈50]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First686 --> PgSelectSingle688
    PgClassExpression703{{"PgClassExpression[703∈50]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle688 --> PgClassExpression703
    Object704{{"Object[704∈50]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression703 --> Object704
    PgClassExpression758{{"PgClassExpression[758∈50]^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle665 --> PgClassExpression758
    PgClassExpression761{{"PgClassExpression[761∈50]^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle665 --> PgClassExpression761
    Lambda762{{"Lambda[762∈50]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression761 --> Lambda762
    PgSelect516 --> Access908
    List909 --> Lambda910
    PgSelect524[["PgSelect[524∈51]<br />ᐸrelational_postsᐳ<br />ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression510 --> PgSelect524
    PgSelect689[["PgSelect[689∈51]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression693{{"PgClassExpression[693∈51]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression693 --> PgSelect689
    First528{{"First[528∈51]^"}}:::plan
    PgSelectRows529[["PgSelectRows[529∈51]^"]]:::plan
    PgSelectRows529 --> First528
    PgSelect524 --> PgSelectRows529
    PgSelectSingle530{{"PgSelectSingle[530∈51]^<br />ᐸrelational_postsᐳ"}}:::plan
    First528 --> PgSelectSingle530
    PgClassExpression646{{"PgClassExpression[646∈51]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle530 --> PgClassExpression646
    PgClassExpression666{{"PgClassExpression[666∈51]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression646 o--o PgClassExpression666
    PgSelectSingle530 --> PgClassExpression693
    First694{{"First[694∈51]^"}}:::plan
    PgSelectRows695[["PgSelectRows[695∈51]^"]]:::plan
    PgSelectRows695 --> First694
    PgSelect689 --> PgSelectRows695
    PgSelectSingle696{{"PgSelectSingle[696∈51]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First694 --> PgSelectSingle696
    PgClassExpression705{{"PgClassExpression[705∈51]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle696 --> PgClassExpression705
    Object706{{"Object[706∈51]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression705 --> Object706
    PgSelect532[["PgSelect[532∈52]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression510 --> PgSelect532
    PgSelect667[["PgSelect[667∈52]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression671{{"PgClassExpression[671∈52]^<br />ᐸ__relation...r_item_id”ᐳ"}}:::plan
    PgClassExpression671 --> PgSelect667
    First536{{"First[536∈52]^"}}:::plan
    PgSelectRows537[["PgSelectRows[537∈52]^"]]:::plan
    PgSelectRows537 --> First536
    PgSelect532 --> PgSelectRows537
    PgSelectSingle538{{"PgSelectSingle[538∈52]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First536 --> PgSelectSingle538
    PgClassExpression647{{"PgClassExpression[647∈52]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle538 --> PgClassExpression647
    PgSelectSingle538 --> PgClassExpression671
    First672{{"First[672∈52]^"}}:::plan
    PgSelectRows673[["PgSelectRows[673∈52]^"]]:::plan
    PgSelectRows673 --> First672
    PgSelect667 --> PgSelectRows673
    PgSelectSingle674{{"PgSelectSingle[674∈52]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First672 --> PgSelectSingle674
    PgClassExpression699{{"PgClassExpression[699∈52]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle674 --> PgClassExpression699
    Object700{{"Object[700∈52]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression699 --> Object700
    PgSelect540[["PgSelect[540∈53]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression510 --> PgSelect540
    PgSelect648[["PgSelect[648∈53]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression652{{"PgClassExpression[652∈53]^<br />ᐸ__relation...t_item_id”ᐳ"}}:::plan
    PgClassExpression652 --> PgSelect648
    First544{{"First[544∈53]^"}}:::plan
    PgSelectRows545[["PgSelectRows[545∈53]^"]]:::plan
    PgSelectRows545 --> First544
    PgSelect540 --> PgSelectRows545
    PgSelectSingle546{{"PgSelectSingle[546∈53]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First544 --> PgSelectSingle546
    PgSelectSingle546 --> PgClassExpression652
    First653{{"First[653∈53]^"}}:::plan
    PgSelectRows654[["PgSelectRows[654∈53]^"]]:::plan
    PgSelectRows654 --> First653
    PgSelect648 --> PgSelectRows654
    PgSelectSingle655{{"PgSelectSingle[655∈53]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First653 --> PgSelectSingle655
    PgClassExpression697{{"PgClassExpression[697∈53]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle655 --> PgClassExpression697
    Object698{{"Object[698∈53]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression697 --> Object698
    PgSelect548[["PgSelect[548∈54]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression510 --> PgSelect548
    PgSelect675[["PgSelect[675∈54]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression679{{"PgClassExpression[679∈54]^<br />ᐸ__relation...m_item_id”ᐳ"}}:::plan
    PgClassExpression679 --> PgSelect675
    First552{{"First[552∈54]^"}}:::plan
    PgSelectRows553[["PgSelectRows[553∈54]^"]]:::plan
    PgSelectRows553 --> First552
    PgSelect548 --> PgSelectRows553
    PgSelectSingle554{{"PgSelectSingle[554∈54]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First552 --> PgSelectSingle554
    PgClassExpression656{{"PgClassExpression[656∈54]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle554 --> PgClassExpression656
    PgSelectSingle554 --> PgClassExpression679
    First680{{"First[680∈54]^"}}:::plan
    PgSelectRows681[["PgSelectRows[681∈54]^"]]:::plan
    PgSelectRows681 --> First680
    PgSelect675 --> PgSelectRows681
    PgSelectSingle682{{"PgSelectSingle[682∈54]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First680 --> PgSelectSingle682
    PgClassExpression701{{"PgClassExpression[701∈54]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle682 --> PgClassExpression701
    Object702{{"Object[702∈54]^<br />ᐸ{id}ᐳ"}}:::plan
    PgClassExpression701 --> Object702
    PgSelect709[["PgSelect[709∈55]^<br />ᐸrelational_itemsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    Access708{{"Access[708∈55]^<br />ᐸ707.idᐳ"}}:::plan
    Access708 --> PgSelect709
    __Value707:::plan@{shape: docs, label: "__Combined[707∈55]<br />ᐳRelationalChecklist<br />ᐳRelationalDivider<br />ᐳRelationalChecklistItem<br />ᐳRelationalTopic<br />ᐳRelationalPost"}
    __Value707 --> Access708
    First713{{"First[713∈55]^"}}:::plan
    PgSelectRows714[["PgSelectRows[714∈55]^"]]:::plan
    PgSelectRows714 --> First713
    PgSelect709 --> PgSelectRows714
    PgSelectSingle715{{"PgSelectSingle[715∈55]^<br />ᐸrelational_itemsᐳ"}}:::plan
    First713 --> PgSelectSingle715
    PgClassExpression716{{"PgClassExpression[716∈55]^<br />ᐸ__relation...s__.”type”ᐳ"}}:::plan
    PgSelectSingle715 --> PgClassExpression716
    Lambda717{{"Lambda[717∈55]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression716 --> Lambda717
    PgClassExpression718{{"PgClassExpression[718∈55]^<br />ᐸ__relation...ems__.”id”ᐳ"}}:::plan
    PgSelectSingle715 --> PgClassExpression718
    PgClassExpression823{{"PgClassExpression[823∈55]^<br />ᐸ__relation...parent_id”ᐳ"}}:::plan
    PgSelectSingle715 --> PgClassExpression823
    PgSelect719[["PgSelect[719∈58]^<br />ᐸrelational_topicsᐳ<br />More deps:<br />- Object[10]"]]:::plan
    PgFromExpression842{{"PgFromExpression[842∈58] ➊<br />(5) ...ᐳRelationalTopic"}}:::plan
    PgSelectInlineApply948["PgSelectInlineApply[948∈58] ➊<br />(5) ...ᐳRelationalTopic"]:::plan
    PgClassExpression718 & PgFromExpression842 & PgSelectInlineApply948 --> PgSelect719
    List950{{"List[950∈58]^<br />ᐸ949,725ᐳ"}}:::plan
    Access949{{"Access[949∈58]^<br />ᐸ719.m.joinDetailsFor838ᐳ"}}:::plan
    PgSelectSingle725{{"PgSelectSingle[725∈58]^<br />ᐸrelational_topicsᐳ"}}:::plan
    Access949 & PgSelectSingle725 --> List950
    First723{{"First[723∈58]^"}}:::plan
    PgSelectRows724[["PgSelectRows[724∈58]^"]]:::plan
    PgSelectRows724 --> First723
    PgSelect719 --> PgSelectRows724
    First723 --> PgSelectSingle725
    PgClassExpression832{{"PgClassExpression[832∈58]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle725 --> PgClassExpression832
    First843{{"First[843∈58]^"}}:::plan
    PgSelectRows844[["PgSelectRows[844∈58]^"]]:::plan
    PgSelectRows844 --> First843
    Lambda951{{"Lambda[951∈58]^<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda951 --> PgSelectRows844
    PgSelectSingle845{{"PgSelectSingle[845∈58]^<br />ᐸrelational_topics_parent_fnᐳ"}}:::plan
    First843 --> PgSelectSingle845
    PgClassExpression847{{"PgClassExpression[847∈58]^<br />ᐸ__relation..._fn__.”id”ᐳ"}}:::plan
    PgSelectSingle845 --> PgClassExpression847
    PgClassExpression850{{"PgClassExpression[850∈58]^<br />ᐸ__relation...n__.”type”ᐳ"}}:::plan
    PgSelectSingle845 --> PgClassExpression850
    Lambda851{{"Lambda[851∈58]^<br />ᐸRelationalItem_typeNameFromTypeᐳ"}}:::plan
    PgClassExpression850 --> Lambda851
    PgSelect719 --> Access949
    List950 --> Lambda951
    PgSelect727[["PgSelect[727∈59]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression718 --> PgSelect727
    First731{{"First[731∈59]^"}}:::plan
    PgSelectRows732[["PgSelectRows[732∈59]^"]]:::plan
    PgSelectRows732 --> First731
    PgSelect727 --> PgSelectRows732
    PgSelectSingle733{{"PgSelectSingle[733∈59]^<br />ᐸrelational_postsᐳ"}}:::plan
    First731 --> PgSelectSingle733
    PgClassExpression833{{"PgClassExpression[833∈59]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle733 --> PgClassExpression833
    PgClassExpression846{{"PgClassExpression[846∈59]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression833 o--o PgClassExpression846
    PgSelect735[["PgSelect[735∈60]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression718 --> PgSelect735
    First739{{"First[739∈60]^"}}:::plan
    PgSelectRows740[["PgSelectRows[740∈60]^"]]:::plan
    PgSelectRows740 --> First739
    PgSelect735 --> PgSelectRows740
    PgSelectSingle741{{"PgSelectSingle[741∈60]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First739 --> PgSelectSingle741
    PgClassExpression834{{"PgClassExpression[834∈60]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle741 --> PgClassExpression834
    PgSelect743[["PgSelect[743∈61]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression718 --> PgSelect743
    First747{{"First[747∈61]^"}}:::plan
    PgSelectRows748[["PgSelectRows[748∈61]^"]]:::plan
    PgSelectRows748 --> First747
    PgSelect743 --> PgSelectRows748
    PgSelectSingle749{{"PgSelectSingle[749∈61]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First747 --> PgSelectSingle749
    PgSelect751[["PgSelect[751∈62]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression718 --> PgSelect751
    First755{{"First[755∈62]^"}}:::plan
    PgSelectRows756[["PgSelectRows[756∈62]^"]]:::plan
    PgSelectRows756 --> First755
    PgSelect751 --> PgSelectRows756
    PgSelectSingle757{{"PgSelectSingle[757∈62]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First755 --> PgSelectSingle757
    PgClassExpression835{{"PgClassExpression[835∈62]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle757 --> PgClassExpression835
    PgSelect764[["PgSelect[764∈63]<br />ᐸrelational_topicsᐳ<br />ᐳRelationalTopicᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression758 --> PgSelect764
    First768{{"First[768∈63]^"}}:::plan
    PgSelectRows769[["PgSelectRows[769∈63]^"]]:::plan
    PgSelectRows769 --> First768
    PgSelect764 --> PgSelectRows769
    PgSelectSingle770{{"PgSelectSingle[770∈63]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First768 --> PgSelectSingle770
    PgClassExpression828{{"PgClassExpression[828∈63]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle770 --> PgClassExpression828
    PgSelect772[["PgSelect[772∈64]<br />ᐸrelational_postsᐳ<br />ᐳRelationalTopicᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression758 --> PgSelect772
    First776{{"First[776∈64]^"}}:::plan
    PgSelectRows777[["PgSelectRows[777∈64]^"]]:::plan
    PgSelectRows777 --> First776
    PgSelect772 --> PgSelectRows777
    PgSelectSingle778{{"PgSelectSingle[778∈64]^<br />ᐸrelational_postsᐳ"}}:::plan
    First776 --> PgSelectSingle778
    PgClassExpression829{{"PgClassExpression[829∈64]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle778 --> PgClassExpression829
    PgClassExpression836{{"PgClassExpression[836∈64]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression829 o--o PgClassExpression836
    PgSelect780[["PgSelect[780∈65]<br />ᐸrelational_dividersᐳ<br />ᐳRelationalTopicᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression758 --> PgSelect780
    First784{{"First[784∈65]^"}}:::plan
    PgSelectRows785[["PgSelectRows[785∈65]^"]]:::plan
    PgSelectRows785 --> First784
    PgSelect780 --> PgSelectRows785
    PgSelectSingle786{{"PgSelectSingle[786∈65]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First784 --> PgSelectSingle786
    PgClassExpression830{{"PgClassExpression[830∈65]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle786 --> PgClassExpression830
    PgSelect788[["PgSelect[788∈66]<br />ᐸrelational_checklistsᐳ<br />ᐳRelationalTopicᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression758 --> PgSelect788
    First792{{"First[792∈66]^"}}:::plan
    PgSelectRows793[["PgSelectRows[793∈66]^"]]:::plan
    PgSelectRows793 --> First792
    PgSelect788 --> PgSelectRows793
    PgSelectSingle794{{"PgSelectSingle[794∈66]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First792 --> PgSelectSingle794
    PgSelect796[["PgSelect[796∈67]<br />ᐸrelational_checklist_itemsᐳ<br />ᐳRelationalTopicᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression758 --> PgSelect796
    First800{{"First[800∈67]^"}}:::plan
    PgSelectRows801[["PgSelectRows[801∈67]^"]]:::plan
    PgSelectRows801 --> First800
    PgSelect796 --> PgSelectRows801
    PgSelectSingle802{{"PgSelectSingle[802∈67]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First800 --> PgSelectSingle802
    PgClassExpression831{{"PgClassExpression[831∈67]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle802 --> PgClassExpression831
    PgSelect853[["PgSelect[853∈69]<br />ᐸrelational_topicsᐳ<br />(5) ...ᐳRelationalTopic<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression847 --> PgSelect853
    First857{{"First[857∈69]^"}}:::plan
    PgSelectRows858[["PgSelectRows[858∈69]^"]]:::plan
    PgSelectRows858 --> First857
    PgSelect853 --> PgSelectRows858
    PgSelectSingle859{{"PgSelectSingle[859∈69]^<br />ᐸrelational_topicsᐳ"}}:::plan
    First857 --> PgSelectSingle859
    PgClassExpression902{{"PgClassExpression[902∈69]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle859 --> PgClassExpression902
    PgSelect861[["PgSelect[861∈70]<br />ᐸrelational_postsᐳ<br />(5) ...ᐳRelationalPost<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression847 --> PgSelect861
    First865{{"First[865∈70]^"}}:::plan
    PgSelectRows866[["PgSelectRows[866∈70]^"]]:::plan
    PgSelectRows866 --> First865
    PgSelect861 --> PgSelectRows866
    PgSelectSingle867{{"PgSelectSingle[867∈70]^<br />ᐸrelational_postsᐳ"}}:::plan
    First865 --> PgSelectSingle867
    PgClassExpression903{{"PgClassExpression[903∈70]^<br />ᐸ__relation...__.”title”ᐳ"}}:::plan
    PgSelectSingle867 --> PgClassExpression903
    PgClassExpression906{{"PgClassExpression[906∈70]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgClassExpression903 o--o PgClassExpression906
    PgSelect869[["PgSelect[869∈71]<br />ᐸrelational_dividersᐳ<br />(5) ...ᐳRelationalDivider<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression847 --> PgSelect869
    First873{{"First[873∈71]^"}}:::plan
    PgSelectRows874[["PgSelectRows[874∈71]^"]]:::plan
    PgSelectRows874 --> First873
    PgSelect869 --> PgSelectRows874
    PgSelectSingle875{{"PgSelectSingle[875∈71]^<br />ᐸrelational_dividersᐳ"}}:::plan
    First873 --> PgSelectSingle875
    PgClassExpression904{{"PgClassExpression[904∈71]^<br />ᐸ__relation...__.”color”ᐳ"}}:::plan
    PgSelectSingle875 --> PgClassExpression904
    PgSelect877[["PgSelect[877∈72]<br />ᐸrelational_checklistsᐳ<br />(5) ...ᐳRelationalChecklist<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression847 --> PgSelect877
    First881{{"First[881∈72]^"}}:::plan
    PgSelectRows882[["PgSelectRows[882∈72]^"]]:::plan
    PgSelectRows882 --> First881
    PgSelect877 --> PgSelectRows882
    PgSelectSingle883{{"PgSelectSingle[883∈72]^<br />ᐸrelational_checklistsᐳ"}}:::plan
    First881 --> PgSelectSingle883
    PgSelect885[["PgSelect[885∈73]<br />ᐸrelational_checklist_itemsᐳ<br />(5) ...ᐳRelationalChecklistItem<br />More deps:<br />- Object[10]"]]:::plan
    PgClassExpression847 --> PgSelect885
    First889{{"First[889∈73]^"}}:::plan
    PgSelectRows890[["PgSelectRows[890∈73]^"]]:::plan
    PgSelectRows890 --> First889
    PgSelect885 --> PgSelectRows890
    PgSelectSingle891{{"PgSelectSingle[891∈73]^<br />ᐸrelational_checklist_itemsᐳ"}}:::plan
    First889 --> PgSelectSingle891
    PgClassExpression905{{"PgClassExpression[905∈73]^<br />ᐸ__relation...scription”ᐳ"}}:::plan
    PgSelectSingle891 --> PgClassExpression905

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect7,Access8,Access9,Object10,Connection11,PgSelect13,PgFromExpression15,First16,PgSelectRows17,PgSelectSingle18,PgSelect20,PgFromExpression22,First23,PgSelectRows24,PgSelectSingle25,PgSelect26,PgFromExpression28,First29,PgSelectRows30,PgSelectSingle31,PgSelect32,PgFromExpression34,First35,PgSelectRows36,PgSelectSingle37,PgSelect39,PgFromExpression41,First42,PgSelectRows43,PgSelectSingle44,PgClassExpression45,PgClassExpression48,PgClassExpression90,PgClassExpression93,ConnectionItems135,PgSelectInlineApply921,Access922,PgFromExpression925,PgSelectInlineApply926,Access927,PgSelectInlineApply930,Access931,PgFromExpression934,PgSelectInlineApply935,Access936,PgSelectInlineApply939,Access940,PgFromExpression943,PgSelectInlineApply944,Access945 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,First143,PgSelectRows144,PgSelectSingle145,PgClassExpression146,PgClassExpression170,PgClassExpression188,PgClassExpression201,First208,PgSelectRows209,PgSelectSingle210,PgClassExpression283,PgClassExpression286,Lambda287,List923,Lambda924,List928,Lambda929 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,First152,PgSelectRows153,PgSelectSingle154,PgClassExpression155,PgClassExpression176,PgClassExpression194,PgClassExpression202,First215,PgSelectRows216,PgSelectSingle217,PgClassExpression328,PgClassExpression331,Lambda332,List932,Lambda933,List937,Lambda938 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,First161,PgSelectRows162,PgSelectSingle163,PgClassExpression164,PgClassExpression182,PgClassExpression200,PgClassExpression203,First222,PgSelectRows223,PgSelectSingle224,PgClassExpression373,PgClassExpression376,Lambda377,List941,Lambda942,List946,Lambda947 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgSelect51,First55,PgSelectRows56,PgSelectSingle57,PgClassExpression255,First269,PgSelectRows270,PgSelectSingle271,PgClassExpression420,PgClassExpression423,Lambda424,PgFromExpression911,PgSelectInlineApply912,Access913,List914,Lambda915 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgSelect59,First63,PgSelectRows64,PgSelectSingle65,PgClassExpression256,PgClassExpression272 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelect67,First71,PgSelectRows72,PgSelectSingle73,PgClassExpression257 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgSelect75,First79,PgSelectRows80,PgSelectSingle81 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgSelect83,First87,PgSelectRows88,PgSelectSingle89,PgClassExpression258 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgSelect96,First100,PgSelectRows101,PgSelectSingle102,PgClassExpression259,First279,PgSelectRows280,PgSelectSingle281,PgClassExpression465,PgClassExpression468,Lambda469,PgFromExpression916,PgSelectInlineApply917,Access918,List919,Lambda920 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13,PgSelect104,First108,PgSelectRows109,PgSelectSingle110,PgClassExpression260,PgClassExpression282 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect112,First116,PgSelectRows117,PgSelectSingle118,PgClassExpression261 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect120,First124,PgSelectRows125,PgSelectSingle126 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,PgSelect128,First132,PgSelectRows133,PgSelectSingle134,PgClassExpression262 bucket16
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item418,PgSelectSingle419,PgClassExpression510,PgClassExpression513,Lambda514,PgClassExpression640 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,PgSelect289,First293,PgSelectRows294,PgSelectSingle295,PgClassExpression585 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,PgSelect297,First301,PgSelectRows302,PgSelectSingle303,PgClassExpression586,PgClassExpression597 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,PgSelect305,First309,PgSelectRows310,PgSelectSingle311,PgClassExpression587 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,PgSelect313,First317,PgSelectRows318,PgSelectSingle319 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect321,First325,PgSelectRows326,PgSelectSingle327,PgClassExpression588 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgSelect334,First338,PgSelectRows339,PgSelectSingle340,PgClassExpression589 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,PgSelect342,First346,PgSelectRows347,PgSelectSingle348,PgClassExpression590,PgClassExpression598 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,PgSelect350,First354,PgSelectRows355,PgSelectSingle356,PgClassExpression591 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,PgSelect358,First362,PgSelectRows363,PgSelectSingle364 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgSelect366,First370,PgSelectRows371,PgSelectSingle372,PgClassExpression592 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgSelect379,First383,PgSelectRows384,PgSelectSingle385,PgClassExpression593 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,PgSelect387,First391,PgSelectRows392,PgSelectSingle393,PgClassExpression594,PgClassExpression599 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,PgSelect395,First399,PgSelectRows400,PgSelectSingle401,PgClassExpression595 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,PgSelect403,First407,PgSelectRows408,PgSelectSingle409 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36,PgSelect411,First415,PgSelectRows416,PgSelectSingle417,PgClassExpression596 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39 bucket39
    classDef bucket40 stroke:#ff1493
    class Bucket40,PgSelect426,First430,PgSelectRows431,PgSelectSingle432,PgClassExpression620 bucket40
    classDef bucket41 stroke:#808000
    class Bucket41,PgSelect434,First438,PgSelectRows439,PgSelectSingle440,PgClassExpression621,PgClassExpression628 bucket41
    classDef bucket42 stroke:#dda0dd
    class Bucket42,PgSelect442,First446,PgSelectRows447,PgSelectSingle448,PgClassExpression622 bucket42
    classDef bucket43 stroke:#ff0000
    class Bucket43,PgSelect450,First454,PgSelectRows455,PgSelectSingle456 bucket43
    classDef bucket44 stroke:#ffff00
    class Bucket44,PgSelect458,First462,PgSelectRows463,PgSelectSingle464,PgClassExpression623 bucket44
    classDef bucket45 stroke:#00ffff
    class Bucket45,PgSelect471,First475,PgSelectRows476,PgSelectSingle477,PgClassExpression624 bucket45
    classDef bucket46 stroke:#4169e1
    class Bucket46,PgSelect479,First483,PgSelectRows484,PgSelectSingle485,PgClassExpression625,PgClassExpression629 bucket46
    classDef bucket47 stroke:#3cb371
    class Bucket47,PgSelect487,First491,PgSelectRows492,PgSelectSingle493,PgClassExpression626 bucket47
    classDef bucket48 stroke:#a52a2a
    class Bucket48,PgSelect495,First499,PgSelectRows500,PgSelectSingle501 bucket48
    classDef bucket49 stroke:#ff00ff
    class Bucket49,PgSelect503,First507,PgSelectRows508,PgSelectSingle509,PgClassExpression627 bucket49
    classDef bucket50 stroke:#f5deb3
    class Bucket50,PgSelect516,First520,PgSelectRows521,PgSelectSingle522,PgClassExpression645,PgFromExpression662,First663,PgSelectRows664,PgSelectSingle665,PgSelect683,PgClassExpression685,First686,PgSelectRows687,PgSelectSingle688,PgClassExpression703,Object704,PgClassExpression758,PgClassExpression761,Lambda762,PgSelectInlineApply907,Access908,List909,Lambda910 bucket50
    classDef bucket51 stroke:#696969
    class Bucket51,PgSelect524,First528,PgSelectRows529,PgSelectSingle530,PgClassExpression646,PgClassExpression666,PgSelect689,PgClassExpression693,First694,PgSelectRows695,PgSelectSingle696,PgClassExpression705,Object706 bucket51
    classDef bucket52 stroke:#00bfff
    class Bucket52,PgSelect532,First536,PgSelectRows537,PgSelectSingle538,PgClassExpression647,PgSelect667,PgClassExpression671,First672,PgSelectRows673,PgSelectSingle674,PgClassExpression699,Object700 bucket52
    classDef bucket53 stroke:#7f007f
    class Bucket53,PgSelect540,First544,PgSelectRows545,PgSelectSingle546,PgSelect648,PgClassExpression652,First653,PgSelectRows654,PgSelectSingle655,PgClassExpression697,Object698 bucket53
    classDef bucket54 stroke:#ffa500
    class Bucket54,PgSelect548,First552,PgSelectRows553,PgSelectSingle554,PgClassExpression656,PgSelect675,PgClassExpression679,First680,PgSelectRows681,PgSelectSingle682,PgClassExpression701,Object702 bucket54
    classDef bucket55 stroke:#0000ff
    class Bucket55,__Value707,Access708,PgSelect709,First713,PgSelectRows714,PgSelectSingle715,PgClassExpression716,Lambda717,PgClassExpression718,PgClassExpression823 bucket55
    classDef bucket56 stroke:#7fff00
    class Bucket56 bucket56
    classDef bucket57 stroke:#ff1493
    class Bucket57 bucket57
    classDef bucket58 stroke:#808000
    class Bucket58,PgSelect719,First723,PgSelectRows724,PgSelectSingle725,PgClassExpression832,PgFromExpression842,First843,PgSelectRows844,PgSelectSingle845,PgClassExpression847,PgClassExpression850,Lambda851,PgSelectInlineApply948,Access949,List950,Lambda951 bucket58
    classDef bucket59 stroke:#dda0dd
    class Bucket59,PgSelect727,First731,PgSelectRows732,PgSelectSingle733,PgClassExpression833,PgClassExpression846 bucket59
    classDef bucket60 stroke:#ff0000
    class Bucket60,PgSelect735,First739,PgSelectRows740,PgSelectSingle741,PgClassExpression834 bucket60
    classDef bucket61 stroke:#ffff00
    class Bucket61,PgSelect743,First747,PgSelectRows748,PgSelectSingle749 bucket61
    classDef bucket62 stroke:#00ffff
    class Bucket62,PgSelect751,First755,PgSelectRows756,PgSelectSingle757,PgClassExpression835 bucket62
    classDef bucket63 stroke:#4169e1
    class Bucket63,PgSelect764,First768,PgSelectRows769,PgSelectSingle770,PgClassExpression828 bucket63
    classDef bucket64 stroke:#3cb371
    class Bucket64,PgSelect772,First776,PgSelectRows777,PgSelectSingle778,PgClassExpression829,PgClassExpression836 bucket64
    classDef bucket65 stroke:#a52a2a
    class Bucket65,PgSelect780,First784,PgSelectRows785,PgSelectSingle786,PgClassExpression830 bucket65
    classDef bucket66 stroke:#ff00ff
    class Bucket66,PgSelect788,First792,PgSelectRows793,PgSelectSingle794 bucket66
    classDef bucket67 stroke:#f5deb3
    class Bucket67,PgSelect796,First800,PgSelectRows801,PgSelectSingle802,PgClassExpression831 bucket67
    classDef bucket68 stroke:#696969
    class Bucket68 bucket68
    classDef bucket69 stroke:#00bfff
    class Bucket69,PgSelect853,First857,PgSelectRows858,PgSelectSingle859,PgClassExpression902 bucket69
    classDef bucket70 stroke:#7f007f
    class Bucket70,PgSelect861,First865,PgSelectRows866,PgSelectSingle867,PgClassExpression903,PgClassExpression906 bucket70
    classDef bucket71 stroke:#ffa500
    class Bucket71,PgSelect869,First873,PgSelectRows874,PgSelectSingle875,PgClassExpression904 bucket71
    classDef bucket72 stroke:#0000ff
    class Bucket72,PgSelect877,First881,PgSelectRows882,PgSelectSingle883 bucket72
    classDef bucket73 stroke:#7fff00
    class Bucket73,PgSelect885,First889,PgSelectRows890,PgSelectSingle891,PgClassExpression905 bucket73

    Object698 -.-x __Value707
    Object700 -.-x __Value707
    Object702 -.-x __Value707
    Object704 -.-x __Value707
    Object706 -.-x __Value707
