%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸlog_entriesᐳ"]]:::plan
    Object12 & Connection13 --> PgSelect14
    __Item15[/"__Item[15∈2]<br />ᐸ14ᐳ"\]:::itemplan
    PgSelect14 ==> __Item15
    PgSelectSingle16{{"PgSelectSingle[16∈2]<br />ᐸlog_entriesᐳ"}}:::plan
    __Item15 --> PgSelectSingle16
    PgUnionAll20[["PgUnionAll[20∈3]"]]:::plan
    PgClassExpression18{{"PgClassExpression[18∈3]<br />ᐸ__log_entr...person_id”ᐳ"}}:::plan
    PgClassExpression19{{"PgClassExpression[19∈3]<br />ᐸ__log_entr...zation_id”ᐳ"}}:::plan
    Object12 & PgClassExpression18 & PgClassExpression19 --> PgUnionAll20
    PgClassExpression17{{"PgClassExpression[17∈3]<br />ᐸ__log_entries__.”id”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression17
    PgSelectSingle16 --> PgClassExpression18
    PgSelectSingle16 --> PgClassExpression19
    First24{{"First[24∈3]"}}:::plan
    PgUnionAll20 --> First24
    PgUnionAllSingle25["PgUnionAllSingle[25∈3]"]:::plan
    First24 --> PgUnionAllSingle25
    PgSelect29[["PgSelect[29∈4]<br />ᐸorganizationsᐳ<br />ᐳOrganization"]]:::plan
    Access28{{"Access[28∈4]<br />ᐸ27.0ᐳ"}}:::plan
    Object12 & Access28 --> PgSelect29
    PgSelect38[["PgSelect[38∈4]<br />ᐸpeopleᐳ<br />ᐳPerson"]]:::plan
    Access37{{"Access[37∈4]<br />ᐸ36.0ᐳ"}}:::plan
    Object12 & Access37 --> PgSelect38
    Access26{{"Access[26∈4]<br />ᐸ25.1ᐳ<br />ᐳOrganization"}}:::plan
    PgUnionAllSingle25 --> Access26
    JSONParse27[["JSONParse[27∈4]<br />ᐸ26ᐳ"]]:::plan
    Access26 --> JSONParse27
    JSONParse27 --> Access28
    First33{{"First[33∈4]"}}:::plan
    PgSelect29 --> First33
    PgSelectSingle34{{"PgSelectSingle[34∈4]<br />ᐸorganizationsᐳ"}}:::plan
    First33 --> PgSelectSingle34
    PgClassExpression35{{"PgClassExpression[35∈4]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression35
    JSONParse36[["JSONParse[36∈4]<br />ᐸ26ᐳ<br />ᐳPerson"]]:::plan
    Access26 --> JSONParse36
    JSONParse36 --> Access37
    First40{{"First[40∈4]"}}:::plan
    PgSelect38 --> First40
    PgSelectSingle41{{"PgSelectSingle[41∈4]<br />ᐸpeopleᐳ"}}:::plan
    First40 --> PgSelectSingle41
    PgClassExpression42{{"PgClassExpression[42∈4]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle41 --> PgClassExpression42

    %% define steps

    subgraph "Buckets for queries/polymorphic/simple-log-entries"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 13<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect14 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 12<br /><br />ROOT __Item{2}ᐸ14ᐳ[15]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,PgSelectSingle16 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 16, 12<br /><br />ROOT PgSelectSingle{2}ᐸlog_entriesᐳ[16]<br />1: <br />ᐳ: 17, 18, 19<br />2: PgUnionAll[20]<br />ᐳ: First[24]<br />3: PgUnionAllSingle[25]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression17,PgClassExpression18,PgClassExpression19,PgUnionAll20,First24,PgUnionAllSingle25 bucket3
    Bucket4("Bucket 4 (polymorphic)<br />Organization,Person<br />Deps: 25, 12<br />ᐳOrganization<br />ᐳPerson<br /><br />1: <br />ᐳ: Access[26]<br />2: JSONParse[27], JSONParse[36]<br />ᐳ: Access[28], Access[37]<br />3: PgSelect[29], PgSelect[38]<br />ᐳ: 33, 34, 35, 40, 41, 42"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,Access26,JSONParse27,Access28,PgSelect29,First33,PgSelectSingle34,PgClassExpression35,JSONParse36,Access37,PgSelect38,First40,PgSelectSingle41,PgClassExpression42 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
