%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 --> Connection13
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant52{{"Constant[52∈0] ➊<br />ᐸ[ 'PRIMARY_KEY_ASC' ]ᐳ"}}:::plan
    Constant52 --> Lambda14
    ApplyInput15{{"ApplyInput[15∈0] ➊"}}:::plan
    Constant6 --> ApplyInput15
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect16[["PgSelect[16∈1] ➊<br />ᐸlog_entriesᐳ"]]:::plan
    Object12 & Lambda14 & ApplyInput15 & Connection13 & Constant6 & Constant6 & Constant6 --> PgSelect16
    PgSelectRows17[["PgSelectRows[17∈1] ➊"]]:::plan
    PgSelect16 --> PgSelectRows17
    __Item18[/"__Item[18∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelectRows17 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈2]<br />ᐸlog_entriesᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    PgUnionAll23[["PgUnionAll[23∈3]"]]:::plan
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__log_entr...person_id”ᐳ"}}:::plan
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__log_entr...zation_id”ᐳ"}}:::plan
    Object12 & PgClassExpression21 & PgClassExpression22 --> PgUnionAll23
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__log_entries__.”id”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    PgSelectSingle19 --> PgClassExpression21
    PgSelectSingle19 --> PgClassExpression22
    First27{{"First[27∈3]"}}:::plan
    Access49{{"Access[49∈3]<br />ᐸ23.itemsᐳ"}}:::plan
    Access49 --> First27
    PgUnionAllSingle29["PgUnionAllSingle[29∈3]"]:::plan
    First27 --> PgUnionAllSingle29
    Access30{{"Access[30∈3]<br />ᐸ29.1ᐳ"}}:::plan
    PgUnionAllSingle29 --> Access30
    PgUnionAll23 --> Access49
    PgSelect33[["PgSelect[33∈4]<br />ᐸorganizationsᐳ<br />ᐳOrganization"]]:::plan
    Access32{{"Access[32∈4]<br />ᐸ31.0ᐳ"}}:::plan
    Object12 & Access32 --> PgSelect33
    PgSelect43[["PgSelect[43∈4]<br />ᐸpeopleᐳ<br />ᐳPerson"]]:::plan
    Access42{{"Access[42∈4]<br />ᐸ41.0ᐳ"}}:::plan
    Object12 & Access42 --> PgSelect43
    JSONParse31[["JSONParse[31∈4]<br />ᐸ30ᐳ<br />ᐳOrganization"]]:::plan
    Access30 --> JSONParse31
    JSONParse31 --> Access32
    First37{{"First[37∈4]"}}:::plan
    PgSelectRows38[["PgSelectRows[38∈4]"]]:::plan
    PgSelectRows38 --> First37
    PgSelect33 --> PgSelectRows38
    PgSelectSingle39{{"PgSelectSingle[39∈4]<br />ᐸorganizationsᐳ"}}:::plan
    First37 --> PgSelectSingle39
    PgClassExpression40{{"PgClassExpression[40∈4]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression40
    JSONParse41[["JSONParse[41∈4]<br />ᐸ30ᐳ<br />ᐳPerson"]]:::plan
    Access30 --> JSONParse41
    JSONParse41 --> Access42
    First45{{"First[45∈4]"}}:::plan
    PgSelectRows46[["PgSelectRows[46∈4]"]]:::plan
    PgSelectRows46 --> First45
    PgSelect43 --> PgSelectRows46
    PgSelectSingle47{{"PgSelectSingle[47∈4]<br />ᐸpeopleᐳ"}}:::plan
    First45 --> PgSelectSingle47
    PgClassExpression48{{"PgClassExpression[48∈4]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle47 --> PgClassExpression48

    %% define steps

    subgraph "Buckets for queries/polymorphic/simple-log-entries"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access10,Access11,Object12,Connection13,Lambda14,ApplyInput15,Constant52 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 14, 15, 13, 6<br /><br />ROOT Connectionᐸ9ᐳ[13]<br />1: PgSelect[16]<br />2: PgSelectRows[17]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect16,PgSelectRows17 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 12<br /><br />ROOT __Item{2}ᐸ17ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgSelectSingle19 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 12<br /><br />ROOT PgSelectSingle{2}ᐸlog_entriesᐳ[19]<br />1: <br />ᐳ: 20, 21, 22<br />2: PgUnionAll[23]<br />ᐳ: Access[49], First[27]<br />3: PgUnionAllSingle[29]<br />ᐳ: Access[30]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression20,PgClassExpression21,PgClassExpression22,PgUnionAll23,First27,PgUnionAllSingle29,Access30,Access49 bucket3
    Bucket4("Bucket 4 (polymorphic)<br />Organization,Person<br />Deps: 30, 12, 29<br />ᐳOrganization<br />ᐳPerson<br /><br />1: JSONParse[31], JSONParse[41]<br />ᐳ: Access[32], Access[42]<br />2: PgSelect[33], PgSelect[43]<br />3: PgSelectRows[38], PgSelectRows[46]<br />ᐳ: 37, 39, 40, 45, 47, 48"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,JSONParse31,Access32,PgSelect33,First37,PgSelectRows38,PgSelectSingle39,PgClassExpression40,JSONParse41,Access42,PgSelect43,First45,PgSelectRows46,PgSelectSingle47,PgClassExpression48 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
