%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection15{{"Connection[15∈0] ➊<br />ᐸ11ᐳ"}}:::plan
    Constant234{{"Constant[234∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Lambda16{{"Lambda[16∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    PgValidateParsedCursor21["PgValidateParsedCursor[21∈0] ➊"]:::plan
    Constant234 & Lambda16 & PgValidateParsedCursor21 & PgValidateParsedCursor21 & PgValidateParsedCursor21 & PgValidateParsedCursor21 & PgValidateParsedCursor21 --> Connection15
    PgUnionAll94[["PgUnionAll[94∈0] ➊"]]:::plan
    Object14{{"Object[14∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant236{{"Constant[236∈0] ➊<br />ᐸ1ᐳ"}}:::plan
    Lambda153{{"Lambda[153∈0] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Access232{{"Access[232∈0] ➊<br />ᐸ231.0ᐳ"}}:::plan
    Access233{{"Access[233∈0] ➊<br />ᐸ231.1ᐳ"}}:::plan
    Object14 & Constant234 & Constant236 & Lambda153 & Access232 & Access233 --> PgUnionAll94
    Object130{{"Object[130∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda122{{"Lambda[122∈0] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Constant127{{"Constant[127∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant128{{"Constant[128∈0] ➊<br />ᐸsql.identifier(”first_party_vulnerabilities”)ᐳ"}}:::plan
    Constant129{{"Constant[129∈0] ➊<br />ᐸRecordCodec(firstPartyVulnerabilities)ᐳ"}}:::plan
    Lambda122 & Constant127 & Constant128 & Constant129 --> Object130
    Object145{{"Object[145∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant142{{"Constant[142∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant143{{"Constant[143∈0] ➊<br />ᐸsql.identifier(”third_party_vulnerabilities”)ᐳ"}}:::plan
    Constant144{{"Constant[144∈0] ➊<br />ᐸRecordCodec(thirdPartyVulnerabilities)ᐳ"}}:::plan
    Lambda122 & Constant142 & Constant143 & Constant144 --> Object145
    Object206{{"Object[206∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant203{{"Constant[203∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant204{{"Constant[204∈0] ➊<br />ᐸsql.identifier(”first_party_vulnerabilities”)ᐳ"}}:::plan
    Lambda122 & Constant203 & Constant204 & Constant129 --> Object206
    Object221{{"Object[221∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant218{{"Constant[218∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant219{{"Constant[219∈0] ➊<br />ᐸsql.identifier(”third_party_vulnerabilities”)ᐳ"}}:::plan
    Lambda122 & Constant218 & Constant219 & Constant144 --> Object221
    Access12{{"Access[12∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access12 & Access13 --> Object14
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access12
    __Value2 --> Access13
    Constant235{{"Constant[235∈0] ➊<br />ᐸ'WyIzMDY3N2Q5ZTIyIiwiMTAiLCJUaGlyZFBhcnR5VnVsbmVyYWJpbGl0eSIᐳ"}}:::plan
    Constant235 --> Lambda16
    Lambda16 --> PgValidateParsedCursor21
    Access22{{"Access[22∈0] ➊<br />ᐸ16.1ᐳ"}}:::plan
    Lambda16 --> Access22
    ToPg23{{"ToPg[23∈0] ➊"}}:::plan
    Access22 --> ToPg23
    Access24{{"Access[24∈0] ➊<br />ᐸ16.2ᐳ"}}:::plan
    Lambda16 --> Access24
    ToPg25{{"ToPg[25∈0] ➊"}}:::plan
    Access24 --> ToPg25
    Access26{{"Access[26∈0] ➊<br />ᐸ16.3ᐳ"}}:::plan
    Lambda16 --> Access26
    Constant237{{"Constant[237∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant237 --> Lambda122
    Lambda125{{"Lambda[125∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant238{{"Constant[238∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant238 --> Lambda125
    Access126{{"Access[126∈0] ➊<br />ᐸ125.0ᐳ"}}:::plan
    Lambda125 --> Access126
    Lambda131{{"Lambda[131∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object130 --> Lambda131
    Lambda136{{"Lambda[136∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant239{{"Constant[239∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”first_ᐳ"}}:::plan
    Constant239 --> Lambda136
    Lambda146{{"Lambda[146∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object145 --> Lambda146
    Lambda151{{"Lambda[151∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant240{{"Constant[240∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”third_ᐳ"}}:::plan
    Constant240 --> Lambda151
    Constant243{{"Constant[243∈0] ➊<br />ᐸ§{ first: 3, last: null, cursorLower: null, cursorUpper: nulᐳ"}}:::plan
    Constant243 --> Lambda153
    Lambda155{{"Lambda[155∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant244{{"Constant[244∈0] ➊<br />ᐸ§{ first: 3, last: null, cursorLower: null, cursorUpper: nulᐳ"}}:::plan
    Constant244 --> Lambda155
    Access156{{"Access[156∈0] ➊<br />ᐸ155.0ᐳ"}}:::plan
    Lambda155 --> Access156
    Access157{{"Access[157∈0] ➊<br />ᐸ155.1ᐳ"}}:::plan
    Lambda155 --> Access157
    Access163{{"Access[163∈0] ➊<br />ᐸ125.1ᐳ"}}:::plan
    Lambda125 --> Access163
    Lambda186{{"Lambda[186∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant245{{"Constant[245∈0] ➊<br />ᐸ§{ first: 3, last: null, cursorLower: null, cursorUpper: nulᐳ"}}:::plan
    Constant245 --> Lambda186
    Access187{{"Access[187∈0] ➊<br />ᐸ186.0ᐳ"}}:::plan
    Lambda186 --> Access187
    Access188{{"Access[188∈0] ➊<br />ᐸ186.1ᐳ"}}:::plan
    Lambda186 --> Access188
    Lambda207{{"Lambda[207∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object206 --> Lambda207
    Lambda212{{"Lambda[212∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant241{{"Constant[241∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”first_ᐳ"}}:::plan
    Constant241 --> Lambda212
    Lambda222{{"Lambda[222∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object221 --> Lambda222
    Lambda227{{"Lambda[227∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant242{{"Constant[242∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”third_ᐳ"}}:::plan
    Constant242 --> Lambda227
    Lambda231{{"Lambda[231∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant246{{"Constant[246∈0] ➊<br />ᐸ§{ first: 3, last: null, cursorLower: null, cursorUpper: nulᐳ"}}:::plan
    Constant246 --> Lambda231
    Lambda231 --> Access232
    Lambda231 --> Access233
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant7{{"Constant[7∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    PgUnionAll17[["PgUnionAll[17∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda16 & Constant234 & ToPg23 & ToPg25 & Access26 & Lambda153 & Access156 & Access157 --> PgUnionAll17
    PgUnionAll59[["PgUnionAll[59∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda16 & Constant234 & ToPg23 & ToPg25 & Access26 & Lambda153 & Access156 & Access157 --> PgUnionAll59
    PgUnionAll70[["PgUnionAll[70∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda16 & Constant234 & ToPg23 & ToPg25 & Access26 & Lambda153 & Access156 & Access157 --> PgUnionAll70
    PgUnionAll82[["PgUnionAll[82∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda16 & Constant234 & ToPg23 & ToPg25 & Access26 & Lambda153 & Access187 & Access188 --> PgUnionAll82
    PgUnionAll86[["PgUnionAll[86∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda16 & Constant234 & ToPg23 & ToPg25 & Access26 & Lambda153 & Access187 & Access188 --> PgUnionAll86
    PgUnionAll53[["PgUnionAll[53∈1] ➊"]]:::plan
    Object14 & Connection15 & Lambda122 & Access126 & Access163 --> PgUnionAll53
    Object88{{"Object[88∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access87{{"Access[87∈1] ➊<br />ᐸ86.hasMoreᐳ"}}:::plan
    Constant234 & Constant7 & Constant7 & Access87 --> Object88
    List69{{"List[69∈1] ➊<br />ᐸ66,67,68ᐳ"}}:::plan
    Access66{{"Access[66∈1] ➊<br />ᐸ61.0ᐳ"}}:::plan
    Access67{{"Access[67∈1] ➊<br />ᐸ61.1ᐳ"}}:::plan
    Access68{{"Access[68∈1] ➊<br />ᐸ61.2ᐳ"}}:::plan
    Access66 & Access67 & Access68 --> List69
    List80{{"List[80∈1] ➊<br />ᐸ77,78,79ᐳ"}}:::plan
    Access77{{"Access[77∈1] ➊<br />ᐸ72.0ᐳ"}}:::plan
    Access78{{"Access[78∈1] ➊<br />ᐸ72.1ᐳ"}}:::plan
    Access79{{"Access[79∈1] ➊<br />ᐸ72.2ᐳ"}}:::plan
    Access77 & Access78 & Access79 --> List80
    Object84{{"Object[84∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Access83{{"Access[83∈1] ➊<br />ᐸ82.hasMoreᐳ"}}:::plan
    Constant234 & Constant7 & Access83 --> Object84
    First54{{"First[54∈1] ➊"}}:::plan
    PgUnionAll53 --> First54
    PgUnionAllSingle55["PgUnionAllSingle[55∈1] ➊"]:::plan
    First54 --> PgUnionAllSingle55
    PgClassExpression56{{"PgClassExpression[56∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgUnionAllSingle55 --> PgClassExpression56
    PgPageInfo58{{"PgPageInfo[58∈1] ➊"}}:::plan
    Connection15 --> PgPageInfo58
    First60{{"First[60∈1] ➊"}}:::plan
    PgUnionAll59 --> First60
    PgUnionAllSingle61["PgUnionAllSingle[61∈1] ➊"]:::plan
    First60 --> PgUnionAllSingle61
    PgCursor62{{"PgCursor[62∈1] ➊"}}:::plan
    List69 --> PgCursor62
    PgUnionAllSingle61 --> Access66
    PgUnionAllSingle61 --> Access67
    PgUnionAllSingle61 --> Access68
    Last71{{"Last[71∈1] ➊"}}:::plan
    PgUnionAll70 --> Last71
    PgUnionAllSingle72["PgUnionAllSingle[72∈1] ➊"]:::plan
    Last71 --> PgUnionAllSingle72
    PgCursor73{{"PgCursor[73∈1] ➊"}}:::plan
    List80 --> PgCursor73
    PgUnionAllSingle72 --> Access77
    PgUnionAllSingle72 --> Access78
    PgUnionAllSingle72 --> Access79
    PgUnionAll82 --> Access83
    Lambda85{{"Lambda[85∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object84 --> Lambda85
    PgUnionAll86 --> Access87
    Lambda89{{"Lambda[89∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object88 --> Lambda89
    __Item18[/"__Item[18∈2]<br />ᐸ17ᐳ"\]:::itemplan
    PgUnionAll17 ==> __Item18
    PgUnionAllSingle19["PgUnionAllSingle[19∈2]"]:::plan
    __Item18 --> PgUnionAllSingle19
    List30{{"List[30∈3]<br />ᐸ27,28,29ᐳ"}}:::plan
    Access27{{"Access[27∈3]<br />ᐸ19.0ᐳ"}}:::plan
    Access28{{"Access[28∈3]<br />ᐸ19.1ᐳ"}}:::plan
    Access29{{"Access[29∈3]<br />ᐸ19.2ᐳ"}}:::plan
    Access27 & Access28 & Access29 --> List30
    PgCursor20{{"PgCursor[20∈3]"}}:::plan
    List30 --> PgCursor20
    PgUnionAllSingle19 --> Access27
    PgUnionAllSingle19 --> Access28
    PgUnionAllSingle19 --> Access29
    PgSelect34[["PgSelect[34∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access33{{"Access[33∈4]<br />ᐸ32.0ᐳ"}}:::plan
    Object14 & Access33 & Lambda122 & Access126 & Lambda131 & Lambda136 --> PgSelect34
    PgSelect45[["PgSelect[45∈4]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access44{{"Access[44∈4]<br />ᐸ43.0ᐳ"}}:::plan
    Object14 & Access44 & Lambda122 & Access126 & Lambda146 & Lambda151 --> PgSelect45
    JSONParse32[["JSONParse[32∈4]<br />ᐸ29ᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access29 --> JSONParse32
    JSONParse32 --> Access33
    First38{{"First[38∈4]"}}:::plan
    PgSelect34 --> First38
    PgSelectSingle39{{"PgSelectSingle[39∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First38 --> PgSelectSingle39
    PgClassExpression40{{"PgClassExpression[40∈4]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression40
    PgClassExpression41{{"PgClassExpression[41∈4]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression41
    PgClassExpression42{{"PgClassExpression[42∈4]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression42
    JSONParse43[["JSONParse[43∈4]<br />ᐸ29ᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access29 --> JSONParse43
    JSONParse43 --> Access44
    First47{{"First[47∈4]"}}:::plan
    PgSelect45 --> First47
    PgSelectSingle48{{"PgSelectSingle[48∈4]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First47 --> PgSelectSingle48
    PgClassExpression49{{"PgClassExpression[49∈4]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    PgClassExpression50{{"PgClassExpression[50∈4]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression50
    PgClassExpression51{{"PgClassExpression[51∈4]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression51
    PgClassExpression52{{"PgClassExpression[52∈4]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression52
    __Item96[/"__Item[96∈5]<br />ᐸ94ᐳ"\]:::itemplan
    PgUnionAll94 ==> __Item96
    PgUnionAllSingle97["PgUnionAllSingle[97∈5]"]:::plan
    __Item96 --> PgUnionAllSingle97
    PgSelect101[["PgSelect[101∈6]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access100{{"Access[100∈6]<br />ᐸ99.0ᐳ"}}:::plan
    Object14 & Access100 & Lambda122 & Access126 & Lambda207 & Lambda212 --> PgSelect101
    PgSelect112[["PgSelect[112∈6]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access111{{"Access[111∈6]<br />ᐸ110.0ᐳ"}}:::plan
    Object14 & Access111 & Lambda122 & Access126 & Lambda222 & Lambda227 --> PgSelect112
    Access98{{"Access[98∈6]<br />ᐸ97.2ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    PgUnionAllSingle97 --> Access98
    JSONParse99[["JSONParse[99∈6]<br />ᐸ98ᐳ"]]:::plan
    Access98 --> JSONParse99
    JSONParse99 --> Access100
    First105{{"First[105∈6]"}}:::plan
    PgSelect101 --> First105
    PgSelectSingle106{{"PgSelectSingle[106∈6]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First105 --> PgSelectSingle106
    PgClassExpression107{{"PgClassExpression[107∈6]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression107
    PgClassExpression108{{"PgClassExpression[108∈6]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression108
    PgClassExpression109{{"PgClassExpression[109∈6]<br />ᐸ__first_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle106 --> PgClassExpression109
    JSONParse110[["JSONParse[110∈6]<br />ᐸ98ᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access98 --> JSONParse110
    JSONParse110 --> Access111
    First114{{"First[114∈6]"}}:::plan
    PgSelect112 --> First114
    PgSelectSingle115{{"PgSelectSingle[115∈6]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First114 --> PgSelectSingle115
    PgClassExpression116{{"PgClassExpression[116∈6]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgSelectSingle115 --> PgClassExpression116
    PgClassExpression117{{"PgClassExpression[117∈6]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle115 --> PgClassExpression117
    PgClassExpression118{{"PgClassExpression[118∈6]<br />ᐸ__third_pa...vss_score”ᐳ"}}:::plan
    PgSelectSingle115 --> PgClassExpression118
    PgClassExpression119{{"PgClassExpression[119∈6]<br />ᐸ__third_pa...ndor_name”ᐳ"}}:::plan
    PgSelectSingle115 --> PgClassExpression119

    %% define steps

    subgraph "Buckets for queries/polymorphic/vulns"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 7, 12, 13, 127, 128, 129, 142, 143, 144, 203, 204, 218, 219, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 14, 16, 22, 23, 24, 25, 26, 122, 125, 126, 130, 131, 136, 145, 146, 151, 153, 155, 156, 157, 163, 186, 187, 188, 206, 207, 212, 221, 222, 227, 231, 232, 233<br />2: 21, 94<br />ᐳ: Connection[15]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant7,Access12,Access13,Object14,Connection15,Lambda16,PgValidateParsedCursor21,Access22,ToPg23,Access24,ToPg25,Access26,PgUnionAll94,Lambda122,Lambda125,Access126,Constant127,Constant128,Constant129,Object130,Lambda131,Lambda136,Constant142,Constant143,Constant144,Object145,Lambda146,Lambda151,Lambda153,Lambda155,Access156,Access157,Access163,Lambda186,Access187,Access188,Constant203,Constant204,Object206,Lambda207,Lambda212,Constant218,Constant219,Object221,Lambda222,Lambda227,Lambda231,Access232,Access233,Constant234,Constant235,Constant236,Constant237,Constant238,Constant239,Constant240,Constant241,Constant242,Constant243,Constant244,Constant245,Constant246 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 14, 15, 16, 234, 23, 25, 26, 153, 156, 157, 122, 126, 163, 187, 188, 7, 131, 136, 146, 151<br /><br />ROOT Connectionᐸ11ᐳ[15]<br />1: 17, 53, 59, 70, 82, 86<br />ᐳ: 58, 54, 60, 71, 83, 84, 85, 87, 88, 89<br />2: 55, 61, 72<br />ᐳ: 56, 66, 67, 68, 69, 77, 78, 79, 80, 62, 73"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll17,PgUnionAll53,First54,PgUnionAllSingle55,PgClassExpression56,PgPageInfo58,PgUnionAll59,First60,PgUnionAllSingle61,PgCursor62,Access66,Access67,Access68,List69,PgUnionAll70,Last71,PgUnionAllSingle72,PgCursor73,Access77,Access78,Access79,List80,PgUnionAll82,Access83,Object84,Lambda85,PgUnionAll86,Access87,Object88,Lambda89 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 14, 122, 126, 131, 136, 146, 151<br /><br />ROOT __Item{2}ᐸ17ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgUnionAllSingle19 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 14, 122, 126, 131, 136, 146, 151<br /><br />ROOT PgUnionAllSingle{2}[19]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor20,Access27,Access28,Access29,List30 bucket3
    Bucket4("Bucket 4 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 29, 14, 122, 126, 131, 136, 146, 151, 19<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: JSONParse[32], JSONParse[43]<br />ᐳ: Access[33], Access[44]<br />2: PgSelect[34], PgSelect[45]<br />ᐳ: 38, 39, 40, 41, 42, 47, 48, 49, 50, 51, 52"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,JSONParse32,Access33,PgSelect34,First38,PgSelectSingle39,PgClassExpression40,PgClassExpression41,PgClassExpression42,JSONParse43,Access44,PgSelect45,First47,PgSelectSingle48,PgClassExpression49,PgClassExpression50,PgClassExpression51,PgClassExpression52 bucket4
    Bucket5("Bucket 5 (listItem)<br />Deps: 14, 122, 126, 207, 212, 222, 227<br /><br />ROOT __Item{5}ᐸ94ᐳ[96]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item96,PgUnionAllSingle97 bucket5
    Bucket6("Bucket 6 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 97, 14, 122, 126, 207, 212, 222, 227<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: <br />ᐳ: Access[98]<br />2: JSONParse[99], JSONParse[110]<br />ᐳ: Access[100], Access[111]<br />3: PgSelect[101], PgSelect[112]<br />ᐳ: 105, 106, 107, 108, 109, 114, 115, 116, 117, 118, 119"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,Access98,JSONParse99,Access100,PgSelect101,First105,PgSelectSingle106,PgClassExpression107,PgClassExpression108,PgClassExpression109,JSONParse110,Access111,PgSelect112,First114,PgSelectSingle115,PgClassExpression116,PgClassExpression117,PgClassExpression118,PgClassExpression119 bucket6
    Bucket0 --> Bucket1 & Bucket5
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket5 --> Bucket6
    end
