%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/vulns.union_owners"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 390, 19, 39, 43, 91, 96, 119, 124, 157, 253, 161, 258, 165, 169, 197, 202, 225, 230<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 19, 11, 39, 43, 91, 96, 119, 124, 157, 253, 161, 258, 165, 169, 197, 202, 225, 230<br /><br />ROOT __Item{2}ᐸ385ᐳ[15]"):::bucket
    Bucket3("Bucket 3 (polymorphic)<br />__typename: Access[22]<br />Deps: 22, 11, 23, 39, 43, 91, 96, 119, 124, 157, 253, 161, 258, 165, 169, 197, 202, 225, 230"):::bucket
    Bucket4("Bucket 4 (polymorphicPartition)<br />|FirstPartyVulnerability<br />Deps: 11, 23, 39, 91, 119, 157, 253, 161, 258, 165, 169, 197, 225<br />ᐳFirstPartyVulnerability<br /><br />1: 24, 53, 65<br />2: PgSelectRows[29]<br />ᐳ: 28, 30, 40, 41, 42, 47<br />3: 59, 69, 85, 87<br />ᐳ: 377, 378, 379, 380"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|ThirdPartyVulnerability<br />Deps: 11, 23, 43, 96, 124, 157, 253, 161, 258, 165, 169, 202, 230<br />ᐳThirdPartyVulnerability<br /><br />1: 32, 58, 68<br />2: PgSelectRows[37]<br />ᐳ: 36, 38, 44, 45, 46, 48<br />3: 61, 71, 86, 88<br />ᐳ: 381, 382, 383, 384"):::bucket
    Bucket6("Bucket 6 (listItem)<br />Deps: 91, 11, 157, 253, 161, 258, 165, 169<br /><br />ROOT __Item{6}ᐸ377ᐳ[77]"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 96, 11, 157, 253, 161, 258, 165, 169<br /><br />ROOT __Item{7}ᐸ381ᐳ[79]"):::bucket
    Bucket8("Bucket 8 (listItem)<br />Deps: 119, 11, 165, 169<br /><br />ROOT __Item{8}ᐸ378ᐳ[81]"):::bucket
    Bucket9("Bucket 9 (listItem)<br />Deps: 124, 11, 165, 169<br /><br />ROOT __Item{9}ᐸ382ᐳ[83]"):::bucket
    Bucket10("Bucket 10 (combined)<br />Deps: 11, 157, 253, 161, 258, 165, 169"):::bucket
    Bucket11("Bucket 11 (polymorphic)<br />__typename: Access[100]<br />Deps: 100, 11, 101, 157, 253, 161, 258, 165, 169"):::bucket
    Bucket12("Bucket 12 (combined)<br />Deps: 11, 165, 169"):::bucket
    Bucket13("Bucket 13 (polymorphic)<br />__typename: Access[128]<br />Deps: 128, 127, 11, 165, 169"):::bucket
    Bucket14("Bucket 14 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 101, 157, 253, 165, 169<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[102]<br />2: PgSelectRows[107]<br />ᐳ: 106, 108, 158, 159, 160, 173, 177, 178<br />3: PgUnionAll[179]<br />ᐳ: 386, 183, 251, 252, 254, 255"):::bucket
    Bucket15("Bucket 15 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 101, 161, 258, 165, 169<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[110]<br />2: PgSelectRows[115]<br />ᐳ: 114, 116, 162, 163, 164, 174, 186, 187<br />3: PgUnionAll[188]<br />ᐳ: 387, 192, 256, 257, 259, 260"):::bucket
    Bucket16("Bucket 16 (polymorphicPartition)<br />|Organization<br />Deps: 127, 11, 165<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[129]<br />2: PgSelect[130]<br />3: PgSelectRows[135]<br />ᐳ: 134, 136, 166, 167, 168, 175"):::bucket
    Bucket17("Bucket 17 (polymorphicPartition)<br />|Person<br />Deps: 127, 11, 169<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[137]<br />2: PgSelect[138]<br />3: PgSelectRows[143]<br />ᐳ: 142, 144, 170, 171, 172, 176"):::bucket
    Bucket18("Bucket 18 (listItem)<br />Deps: 197, 11, 157, 253, 161, 258, 165, 169<br /><br />ROOT __Item{18}ᐸ379ᐳ[149]"):::bucket
    Bucket19("Bucket 19 (listItem)<br />Deps: 202, 11, 157, 253, 161, 258, 165, 169<br /><br />ROOT __Item{19}ᐸ383ᐳ[151]"):::bucket
    Bucket20("Bucket 20 (listItem)<br />Deps: 225, 11, 165, 169<br /><br />ROOT __Item{20}ᐸ380ᐳ[153]"):::bucket
    Bucket21("Bucket 21 (listItem)<br />Deps: 230, 11, 165, 169<br /><br />ROOT __Item{21}ᐸ384ᐳ[155]"):::bucket
    Bucket22("Bucket 22 (combined)<br />Deps: 11, 157, 253, 161, 258, 165, 169"):::bucket
    Bucket23("Bucket 23 (polymorphic)<br />__typename: Access[206]<br />Deps: 206, 11, 207, 157, 253, 161, 258, 165, 169"):::bucket
    Bucket24("Bucket 24 (combined)<br />Deps: 11, 165, 169"):::bucket
    Bucket25("Bucket 25 (polymorphic)<br />__typename: Access[234]<br />Deps: 234, 233, 11, 165, 169"):::bucket
    Bucket26("Bucket 26 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 207, 157, 253, 165, 169<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[208]<br />2: PgSelectRows[213]<br />ᐳ: 212, 214, 289, 290, 291, 301, 305, 306<br />3: PgUnionAll[307]<br />ᐳ: 388, 311, 331, 332, 334, 335"):::bucket
    Bucket27("Bucket 27 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 207, 161, 258, 165, 169<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[216]<br />2: PgSelectRows[221]<br />ᐳ: 220, 222, 292, 293, 294, 302, 314, 315<br />3: PgUnionAll[316]<br />ᐳ: 389, 320, 336, 337, 339, 340"):::bucket
    Bucket28("Bucket 28 (polymorphicPartition)<br />|Organization<br />Deps: 233, 11, 165<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[235]<br />2: PgSelect[236]<br />3: PgSelectRows[241]<br />ᐳ: 240, 242, 295, 296, 297, 303"):::bucket
    Bucket29("Bucket 29 (polymorphicPartition)<br />|Person<br />Deps: 233, 11, 169<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[243]<br />2: PgSelect[244]<br />3: PgSelectRows[249]<br />ᐳ: 248, 250, 298, 299, 300, 304"):::bucket
    Bucket30("Bucket 30 (combined)<br />Deps: 11, 165, 169"):::bucket
    Bucket31("Bucket 31 (polymorphic)<br />__typename: Access[272]<br />Deps: 272, 271, 11, 165, 169"):::bucket
    Bucket32("Bucket 32 (polymorphicPartition)<br />|Organization<br />Deps: 271, 11, 165<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[273]<br />2: PgSelect[274]<br />3: PgSelectRows[279]<br />ᐳ: 278, 280, 323, 324, 325, 329"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|Person<br />Deps: 271, 11, 169<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[281]<br />2: PgSelect[282]<br />3: PgSelectRows[287]<br />ᐳ: 286, 288, 326, 327, 328, 330"):::bucket
    Bucket34("Bucket 34 (combined)<br />Deps: 11, 165, 169"):::bucket
    Bucket35("Bucket 35 (polymorphic)<br />__typename: Access[352]<br />Deps: 352, 351, 11, 165, 169"):::bucket
    Bucket36("Bucket 36 (polymorphicPartition)<br />|Organization<br />Deps: 351, 11, 165<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[353]<br />2: PgSelect[354]<br />3: PgSelectRows[359]<br />ᐳ: 358, 360, 369, 370, 371, 375"):::bucket
    Bucket37("Bucket 37 (polymorphicPartition)<br />|Person<br />Deps: 351, 11, 169<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[361]<br />2: PgSelect[362]<br />3: PgSelectRows[367]<br />ᐳ: 366, 368, 372, 373, 374, 376"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5
    Bucket4 --> Bucket6 & Bucket8 & Bucket18 & Bucket20
    Bucket5 --> Bucket7 & Bucket9 & Bucket19 & Bucket21
    Bucket6 --> Bucket10
    Bucket7 --> Bucket10
    Bucket8 --> Bucket12
    Bucket9 --> Bucket12
    Bucket10 --> Bucket11
    Bucket11 --> Bucket14 & Bucket15
    Bucket12 --> Bucket13
    Bucket13 --> Bucket16 & Bucket17
    Bucket14 --> Bucket30
    Bucket15 --> Bucket30
    Bucket18 --> Bucket22
    Bucket19 --> Bucket22
    Bucket20 --> Bucket24
    Bucket21 --> Bucket24
    Bucket22 --> Bucket23
    Bucket23 --> Bucket26 & Bucket27
    Bucket24 --> Bucket25
    Bucket25 --> Bucket28 & Bucket29
    Bucket26 --> Bucket34
    Bucket27 --> Bucket34
    Bucket30 --> Bucket31
    Bucket31 --> Bucket32 & Bucket33
    Bucket34 --> Bucket35
    Bucket35 --> Bucket36 & Bucket37

    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 27"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ<br />More deps:<br />- Constantᐸ2ᐳ[390]"}}:::plan
    PgUnionAll13[["PgUnionAll[13∈1] ➊<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[11]<br />- Constantᐸ2ᐳ[390]"]]:::plan
    Connection12 --> PgUnionAll13
    Access385{{"Access[385∈1] ➊<br />ᐸ13.itemsᐳ"}}:::plan
    PgUnionAll13 --> Access385
    List20{{"List[20∈2]<br />ᐸ17,18,19ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[19]"}}:::plan
    Access17{{"Access[17∈2]<br />ᐸ15.0ᐳ"}}:::plan
    Access18{{"Access[18∈2]<br />ᐸ15.1ᐳ"}}:::plan
    Access17 & Access18 --> List20
    __Item15[/"__Item[15∈2]<br />ᐸ385ᐳ"\]:::itemplan
    Access385 ==> __Item15
    __Item15 --> Access17
    __Item15 --> Access18
    Lambda21{{"Lambda[21∈2]<br />ᐸtoSpecifierᐳ"}}:::plan
    List20 --> Lambda21
    Access22{{"Access[22∈2]<br />ᐸ21.__typenameᐳ"}}:::plan
    Lambda21 --> Access22
    Access23{{"Access[23∈2]<br />ᐸ21.idᐳ"}}:::plan
    Lambda21 --> Access23
    PgUnionAll85[["PgUnionAll[85∈4]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression40{{"PgClassExpression[40∈4]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    Connection53{{"Connection[53∈4] ➊<br />ᐸ49ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    PgClassExpression40 & Connection53 --> PgUnionAll85
    PgUnionAll87[["PgUnionAll[87∈4]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Connection65{{"Connection[65∈4] ➊<br />ᐸ63ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    PgClassExpression40 & Connection65 --> PgUnionAll87
    PgSelect24[["PgSelect[24∈4]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access23 --> PgSelect24
    List41{{"List[41∈4]^<br />ᐸ39,40ᐳ<br />More deps:<br />- Constantᐸ'first_party_vulnerabilities'ᐳ[39]"}}:::plan
    PgClassExpression40 --> List41
    PgUnionAll59[["PgUnionAll[59∈4]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression40 --> PgUnionAll59
    PgUnionAll69[["PgUnionAll[69∈4]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression40 --> PgUnionAll69
    First28{{"First[28∈4]^"}}:::plan
    PgSelectRows29[["PgSelectRows[29∈4]^"]]:::plan
    PgSelectRows29 --> First28
    PgSelect24 --> PgSelectRows29
    PgSelectSingle30{{"PgSelectSingle[30∈4]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First28 --> PgSelectSingle30
    PgSelectSingle30 --> PgClassExpression40
    Lambda42{{"Lambda[42∈4]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List41 --> Lambda42
    PgClassExpression47{{"PgClassExpression[47∈4]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression47
    Access377{{"Access[377∈4]^<br />ᐸ59.itemsᐳ"}}:::plan
    PgUnionAll59 --> Access377
    Access378{{"Access[378∈4]^<br />ᐸ69.itemsᐳ"}}:::plan
    PgUnionAll69 --> Access378
    Access379{{"Access[379∈4]^<br />ᐸ85.itemsᐳ"}}:::plan
    PgUnionAll85 --> Access379
    Access380{{"Access[380∈4]^<br />ᐸ87.itemsᐳ"}}:::plan
    PgUnionAll87 --> Access380
    PgUnionAll86[["PgUnionAll[86∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression44{{"PgClassExpression[44∈5]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    Connection58{{"Connection[58∈5] ➊<br />ᐸ54ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    PgClassExpression44 & Connection58 --> PgUnionAll86
    PgUnionAll88[["PgUnionAll[88∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Connection68{{"Connection[68∈5] ➊<br />ᐸ66ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    PgClassExpression44 & Connection68 --> PgUnionAll88
    PgSelect32[["PgSelect[32∈5]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access23 --> PgSelect32
    List45{{"List[45∈5]^<br />ᐸ43,44ᐳ<br />More deps:<br />- Constantᐸ'third_party_vulnerabilities'ᐳ[43]"}}:::plan
    PgClassExpression44 --> List45
    PgUnionAll61[["PgUnionAll[61∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression44 --> PgUnionAll61
    PgUnionAll71[["PgUnionAll[71∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression44 --> PgUnionAll71
    First36{{"First[36∈5]^"}}:::plan
    PgSelectRows37[["PgSelectRows[37∈5]^"]]:::plan
    PgSelectRows37 --> First36
    PgSelect32 --> PgSelectRows37
    PgSelectSingle38{{"PgSelectSingle[38∈5]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First36 --> PgSelectSingle38
    PgSelectSingle38 --> PgClassExpression44
    Lambda46{{"Lambda[46∈5]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List45 --> Lambda46
    PgClassExpression48{{"PgClassExpression[48∈5]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle38 --> PgClassExpression48
    Access381{{"Access[381∈5]^<br />ᐸ61.itemsᐳ"}}:::plan
    PgUnionAll61 --> Access381
    Access382{{"Access[382∈5]^<br />ᐸ71.itemsᐳ"}}:::plan
    PgUnionAll71 --> Access382
    Access383{{"Access[383∈5]^<br />ᐸ86.itemsᐳ"}}:::plan
    PgUnionAll86 --> Access383
    Access384{{"Access[384∈5]^<br />ᐸ88.itemsᐳ"}}:::plan
    PgUnionAll88 --> Access384
    List92{{"List[92∈6]^<br />ᐸ89,90,91ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[91]"}}:::plan
    Access89{{"Access[89∈6]^<br />ᐸ77.0ᐳ"}}:::plan
    Access90{{"Access[90∈6]^<br />ᐸ77.1ᐳ"}}:::plan
    Access89 & Access90 --> List92
    __Item77[/"__Item[77∈6]<br />ᐸ377ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access377 ==> __Item77
    __Item77 --> Access89
    __Item77 --> Access90
    Lambda93{{"Lambda[93∈6]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List92 --> Lambda93
    List97{{"List[97∈7]^<br />ᐸ94,95,96ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[96]"}}:::plan
    Access94{{"Access[94∈7]^<br />ᐸ79.0ᐳ"}}:::plan
    Access95{{"Access[95∈7]^<br />ᐸ79.1ᐳ"}}:::plan
    Access94 & Access95 --> List97
    __Item79[/"__Item[79∈7]<br />ᐸ381ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access381 ==> __Item79
    __Item79 --> Access94
    __Item79 --> Access95
    Lambda98{{"Lambda[98∈7]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List97 --> Lambda98
    List120{{"List[120∈8]^<br />ᐸ117,118,119ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[119]"}}:::plan
    Access117{{"Access[117∈8]^<br />ᐸ81.0ᐳ"}}:::plan
    Access118{{"Access[118∈8]^<br />ᐸ81.1ᐳ"}}:::plan
    Access117 & Access118 --> List120
    __Item81[/"__Item[81∈8]<br />ᐸ378ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access378 ==> __Item81
    __Item81 --> Access117
    __Item81 --> Access118
    Lambda121{{"Lambda[121∈8]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List120 --> Lambda121
    List125{{"List[125∈9]^<br />ᐸ122,123,124ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[124]"}}:::plan
    Access122{{"Access[122∈9]^<br />ᐸ83.0ᐳ"}}:::plan
    Access123{{"Access[123∈9]^<br />ᐸ83.1ᐳ"}}:::plan
    Access122 & Access123 --> List125
    __Item83[/"__Item[83∈9]<br />ᐸ382ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access382 ==> __Item83
    __Item83 --> Access122
    __Item83 --> Access123
    Lambda126{{"Lambda[126∈9]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List125 --> Lambda126
    Access100{{"Access[100∈10]^<br />ᐸ99.__typenameᐳ"}}:::plan
    __Value99:::plan@{shape: docs, label: "__Combined[99∈10]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value99 --> Access100
    Access101{{"Access[101∈10]^<br />ᐸ99.idᐳ"}}:::plan
    __Value99 --> Access101
    Access128{{"Access[128∈12]^<br />ᐸ127.__typenameᐳ"}}:::plan
    __Value127:::plan@{shape: docs, label: "__Combined[127∈12]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value127 --> Access128
    PgUnionAll179[["PgUnionAll[179∈14]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression177{{"PgClassExpression[177∈14]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression178{{"PgClassExpression[178∈14]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression177 & PgClassExpression178 --> PgUnionAll179
    List254{{"List[254∈14]^<br />ᐸ251,252,253ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[253]"}}:::plan
    Access251{{"Access[251∈14]^<br />ᐸ183.0ᐳ"}}:::plan
    Access252{{"Access[252∈14]^<br />ᐸ183.1ᐳ"}}:::plan
    Access251 & Access252 --> List254
    PgSelect102[["PgSelect[102∈14]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access101 --> PgSelect102
    List159{{"List[159∈14]^<br />ᐸ157,158ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[157]"}}:::plan
    PgClassExpression158{{"PgClassExpression[158∈14]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression158 --> List159
    First106{{"First[106∈14]^"}}:::plan
    PgSelectRows107[["PgSelectRows[107∈14]^"]]:::plan
    PgSelectRows107 --> First106
    PgSelect102 --> PgSelectRows107
    PgSelectSingle108{{"PgSelectSingle[108∈14]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First106 --> PgSelectSingle108
    PgSelectSingle108 --> PgClassExpression158
    Lambda160{{"Lambda[160∈14]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List159 --> Lambda160
    PgClassExpression173{{"PgClassExpression[173∈14]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle108 --> PgClassExpression173
    PgSelectSingle108 --> PgClassExpression177
    PgSelectSingle108 --> PgClassExpression178
    First183{{"First[183∈14]^"}}:::plan
    Access386{{"Access[386∈14]^<br />ᐸ179.itemsᐳ"}}:::plan
    Access386 --> First183
    First183 --> Access251
    First183 --> Access252
    Lambda255{{"Lambda[255∈14]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List254 --> Lambda255
    PgUnionAll179 --> Access386
    PgUnionAll188[["PgUnionAll[188∈15]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression186{{"PgClassExpression[186∈15]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression187{{"PgClassExpression[187∈15]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression186 & PgClassExpression187 --> PgUnionAll188
    List259{{"List[259∈15]^<br />ᐸ256,257,258ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[258]"}}:::plan
    Access256{{"Access[256∈15]^<br />ᐸ192.0ᐳ"}}:::plan
    Access257{{"Access[257∈15]^<br />ᐸ192.1ᐳ"}}:::plan
    Access256 & Access257 --> List259
    PgSelect110[["PgSelect[110∈15]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access101 --> PgSelect110
    List163{{"List[163∈15]^<br />ᐸ161,162ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[161]"}}:::plan
    PgClassExpression162{{"PgClassExpression[162∈15]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression162 --> List163
    First114{{"First[114∈15]^"}}:::plan
    PgSelectRows115[["PgSelectRows[115∈15]^"]]:::plan
    PgSelectRows115 --> First114
    PgSelect110 --> PgSelectRows115
    PgSelectSingle116{{"PgSelectSingle[116∈15]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First114 --> PgSelectSingle116
    PgSelectSingle116 --> PgClassExpression162
    Lambda164{{"Lambda[164∈15]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List163 --> Lambda164
    PgClassExpression174{{"PgClassExpression[174∈15]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle116 --> PgClassExpression174
    PgSelectSingle116 --> PgClassExpression186
    PgSelectSingle116 --> PgClassExpression187
    First192{{"First[192∈15]^"}}:::plan
    Access387{{"Access[387∈15]^<br />ᐸ188.itemsᐳ"}}:::plan
    Access387 --> First192
    First192 --> Access256
    First192 --> Access257
    Lambda260{{"Lambda[260∈15]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List259 --> Lambda260
    PgUnionAll188 --> Access387
    PgSelect130[["PgSelect[130∈16]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access129{{"Access[129∈16]<br />ᐸ127.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access129 --> PgSelect130
    List167{{"List[167∈16]^<br />ᐸ165,166ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[165]"}}:::plan
    PgClassExpression166{{"PgClassExpression[166∈16]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression166 --> List167
    __Value127 --> Access129
    First134{{"First[134∈16]^"}}:::plan
    PgSelectRows135[["PgSelectRows[135∈16]^"]]:::plan
    PgSelectRows135 --> First134
    PgSelect130 --> PgSelectRows135
    PgSelectSingle136{{"PgSelectSingle[136∈16]^<br />ᐸorganizationsᐳ"}}:::plan
    First134 --> PgSelectSingle136
    PgSelectSingle136 --> PgClassExpression166
    Lambda168{{"Lambda[168∈16]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List167 --> Lambda168
    PgClassExpression175{{"PgClassExpression[175∈16]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle136 --> PgClassExpression175
    PgSelect138[["PgSelect[138∈17]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access137{{"Access[137∈17]<br />ᐸ127.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access137 --> PgSelect138
    List171{{"List[171∈17]^<br />ᐸ169,170ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[169]"}}:::plan
    PgClassExpression170{{"PgClassExpression[170∈17]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression170 --> List171
    __Value127 --> Access137
    First142{{"First[142∈17]^"}}:::plan
    PgSelectRows143[["PgSelectRows[143∈17]^"]]:::plan
    PgSelectRows143 --> First142
    PgSelect138 --> PgSelectRows143
    PgSelectSingle144{{"PgSelectSingle[144∈17]^<br />ᐸpeopleᐳ"}}:::plan
    First142 --> PgSelectSingle144
    PgSelectSingle144 --> PgClassExpression170
    Lambda172{{"Lambda[172∈17]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List171 --> Lambda172
    PgClassExpression176{{"PgClassExpression[176∈17]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle144 --> PgClassExpression176
    List198{{"List[198∈18]^<br />ᐸ195,196,197ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[197]"}}:::plan
    Access195{{"Access[195∈18]^<br />ᐸ149.0ᐳ"}}:::plan
    Access196{{"Access[196∈18]^<br />ᐸ149.1ᐳ"}}:::plan
    Access195 & Access196 --> List198
    __Item149[/"__Item[149∈18]<br />ᐸ379ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access379 ==> __Item149
    __Item149 --> Access195
    __Item149 --> Access196
    Lambda199{{"Lambda[199∈18]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List198 --> Lambda199
    List203{{"List[203∈19]^<br />ᐸ200,201,202ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[202]"}}:::plan
    Access200{{"Access[200∈19]^<br />ᐸ151.0ᐳ"}}:::plan
    Access201{{"Access[201∈19]^<br />ᐸ151.1ᐳ"}}:::plan
    Access200 & Access201 --> List203
    __Item151[/"__Item[151∈19]<br />ᐸ383ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access383 ==> __Item151
    __Item151 --> Access200
    __Item151 --> Access201
    Lambda204{{"Lambda[204∈19]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List203 --> Lambda204
    List226{{"List[226∈20]^<br />ᐸ223,224,225ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[225]"}}:::plan
    Access223{{"Access[223∈20]^<br />ᐸ153.0ᐳ"}}:::plan
    Access224{{"Access[224∈20]^<br />ᐸ153.1ᐳ"}}:::plan
    Access223 & Access224 --> List226
    __Item153[/"__Item[153∈20]<br />ᐸ380ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access380 ==> __Item153
    __Item153 --> Access223
    __Item153 --> Access224
    Lambda227{{"Lambda[227∈20]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List226 --> Lambda227
    List231{{"List[231∈21]^<br />ᐸ228,229,230ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[230]"}}:::plan
    Access228{{"Access[228∈21]^<br />ᐸ155.0ᐳ"}}:::plan
    Access229{{"Access[229∈21]^<br />ᐸ155.1ᐳ"}}:::plan
    Access228 & Access229 --> List231
    __Item155[/"__Item[155∈21]<br />ᐸ384ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access384 ==> __Item155
    __Item155 --> Access228
    __Item155 --> Access229
    Lambda232{{"Lambda[232∈21]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List231 --> Lambda232
    Access206{{"Access[206∈22]^<br />ᐸ205.__typenameᐳ"}}:::plan
    __Value205:::plan@{shape: docs, label: "__Combined[205∈22]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value205 --> Access206
    Access207{{"Access[207∈22]^<br />ᐸ205.idᐳ"}}:::plan
    __Value205 --> Access207
    Access234{{"Access[234∈24]^<br />ᐸ233.__typenameᐳ"}}:::plan
    __Value233:::plan@{shape: docs, label: "__Combined[233∈24]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value233 --> Access234
    PgUnionAll307[["PgUnionAll[307∈26]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression305{{"PgClassExpression[305∈26]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression306{{"PgClassExpression[306∈26]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression305 & PgClassExpression306 --> PgUnionAll307
    List334{{"List[334∈26]^<br />ᐸ331,332,253ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[253]"}}:::plan
    Access331{{"Access[331∈26]^<br />ᐸ311.0ᐳ"}}:::plan
    Access332{{"Access[332∈26]^<br />ᐸ311.1ᐳ"}}:::plan
    Access331 & Access332 --> List334
    PgSelect208[["PgSelect[208∈26]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access207 --> PgSelect208
    List290{{"List[290∈26]^<br />ᐸ157,289ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[157]"}}:::plan
    PgClassExpression289{{"PgClassExpression[289∈26]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression289 --> List290
    First212{{"First[212∈26]^"}}:::plan
    PgSelectRows213[["PgSelectRows[213∈26]^"]]:::plan
    PgSelectRows213 --> First212
    PgSelect208 --> PgSelectRows213
    PgSelectSingle214{{"PgSelectSingle[214∈26]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First212 --> PgSelectSingle214
    PgSelectSingle214 --> PgClassExpression289
    Lambda291{{"Lambda[291∈26]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List290 --> Lambda291
    PgClassExpression301{{"PgClassExpression[301∈26]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle214 --> PgClassExpression301
    PgSelectSingle214 --> PgClassExpression305
    PgSelectSingle214 --> PgClassExpression306
    First311{{"First[311∈26]^"}}:::plan
    Access388{{"Access[388∈26]^<br />ᐸ307.itemsᐳ"}}:::plan
    Access388 --> First311
    First311 --> Access331
    First311 --> Access332
    Lambda335{{"Lambda[335∈26]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List334 --> Lambda335
    PgUnionAll307 --> Access388
    PgUnionAll316[["PgUnionAll[316∈27]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression314{{"PgClassExpression[314∈27]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression315{{"PgClassExpression[315∈27]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression314 & PgClassExpression315 --> PgUnionAll316
    List339{{"List[339∈27]^<br />ᐸ336,337,258ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[258]"}}:::plan
    Access336{{"Access[336∈27]^<br />ᐸ320.0ᐳ"}}:::plan
    Access337{{"Access[337∈27]^<br />ᐸ320.1ᐳ"}}:::plan
    Access336 & Access337 --> List339
    PgSelect216[["PgSelect[216∈27]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access207 --> PgSelect216
    List293{{"List[293∈27]^<br />ᐸ161,292ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[161]"}}:::plan
    PgClassExpression292{{"PgClassExpression[292∈27]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression292 --> List293
    First220{{"First[220∈27]^"}}:::plan
    PgSelectRows221[["PgSelectRows[221∈27]^"]]:::plan
    PgSelectRows221 --> First220
    PgSelect216 --> PgSelectRows221
    PgSelectSingle222{{"PgSelectSingle[222∈27]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First220 --> PgSelectSingle222
    PgSelectSingle222 --> PgClassExpression292
    Lambda294{{"Lambda[294∈27]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List293 --> Lambda294
    PgClassExpression302{{"PgClassExpression[302∈27]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle222 --> PgClassExpression302
    PgSelectSingle222 --> PgClassExpression314
    PgSelectSingle222 --> PgClassExpression315
    First320{{"First[320∈27]^"}}:::plan
    Access389{{"Access[389∈27]^<br />ᐸ316.itemsᐳ"}}:::plan
    Access389 --> First320
    First320 --> Access336
    First320 --> Access337
    Lambda340{{"Lambda[340∈27]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List339 --> Lambda340
    PgUnionAll316 --> Access389
    PgSelect236[["PgSelect[236∈28]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access235{{"Access[235∈28]<br />ᐸ233.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access235 --> PgSelect236
    List296{{"List[296∈28]^<br />ᐸ165,295ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[165]"}}:::plan
    PgClassExpression295{{"PgClassExpression[295∈28]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression295 --> List296
    __Value233 --> Access235
    First240{{"First[240∈28]^"}}:::plan
    PgSelectRows241[["PgSelectRows[241∈28]^"]]:::plan
    PgSelectRows241 --> First240
    PgSelect236 --> PgSelectRows241
    PgSelectSingle242{{"PgSelectSingle[242∈28]^<br />ᐸorganizationsᐳ"}}:::plan
    First240 --> PgSelectSingle242
    PgSelectSingle242 --> PgClassExpression295
    Lambda297{{"Lambda[297∈28]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List296 --> Lambda297
    PgClassExpression303{{"PgClassExpression[303∈28]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle242 --> PgClassExpression303
    PgSelect244[["PgSelect[244∈29]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access243{{"Access[243∈29]<br />ᐸ233.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access243 --> PgSelect244
    List299{{"List[299∈29]^<br />ᐸ169,298ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[169]"}}:::plan
    PgClassExpression298{{"PgClassExpression[298∈29]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression298 --> List299
    __Value233 --> Access243
    First248{{"First[248∈29]^"}}:::plan
    PgSelectRows249[["PgSelectRows[249∈29]^"]]:::plan
    PgSelectRows249 --> First248
    PgSelect244 --> PgSelectRows249
    PgSelectSingle250{{"PgSelectSingle[250∈29]^<br />ᐸpeopleᐳ"}}:::plan
    First248 --> PgSelectSingle250
    PgSelectSingle250 --> PgClassExpression298
    Lambda300{{"Lambda[300∈29]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List299 --> Lambda300
    PgClassExpression304{{"PgClassExpression[304∈29]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle250 --> PgClassExpression304
    Access272{{"Access[272∈30]^<br />ᐸ271.__typenameᐳ"}}:::plan
    __Value271:::plan@{shape: docs, label: "__Combined[271∈30]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value271 --> Access272
    PgSelect274[["PgSelect[274∈32]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access273{{"Access[273∈32]<br />ᐸ271.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access273 --> PgSelect274
    List324{{"List[324∈32]^<br />ᐸ165,323ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[165]"}}:::plan
    PgClassExpression323{{"PgClassExpression[323∈32]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression323 --> List324
    __Value271 --> Access273
    First278{{"First[278∈32]^"}}:::plan
    PgSelectRows279[["PgSelectRows[279∈32]^"]]:::plan
    PgSelectRows279 --> First278
    PgSelect274 --> PgSelectRows279
    PgSelectSingle280{{"PgSelectSingle[280∈32]^<br />ᐸorganizationsᐳ"}}:::plan
    First278 --> PgSelectSingle280
    PgSelectSingle280 --> PgClassExpression323
    Lambda325{{"Lambda[325∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List324 --> Lambda325
    PgClassExpression329{{"PgClassExpression[329∈32]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle280 --> PgClassExpression329
    PgSelect282[["PgSelect[282∈33]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access281{{"Access[281∈33]<br />ᐸ271.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access281 --> PgSelect282
    List327{{"List[327∈33]^<br />ᐸ169,326ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[169]"}}:::plan
    PgClassExpression326{{"PgClassExpression[326∈33]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression326 --> List327
    __Value271 --> Access281
    First286{{"First[286∈33]^"}}:::plan
    PgSelectRows287[["PgSelectRows[287∈33]^"]]:::plan
    PgSelectRows287 --> First286
    PgSelect282 --> PgSelectRows287
    PgSelectSingle288{{"PgSelectSingle[288∈33]^<br />ᐸpeopleᐳ"}}:::plan
    First286 --> PgSelectSingle288
    PgSelectSingle288 --> PgClassExpression326
    Lambda328{{"Lambda[328∈33]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List327 --> Lambda328
    PgClassExpression330{{"PgClassExpression[330∈33]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle288 --> PgClassExpression330
    Access352{{"Access[352∈34]^<br />ᐸ351.__typenameᐳ"}}:::plan
    __Value351:::plan@{shape: docs, label: "__Combined[351∈34]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value351 --> Access352
    PgSelect354[["PgSelect[354∈36]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access353{{"Access[353∈36]<br />ᐸ351.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access353 --> PgSelect354
    List370{{"List[370∈36]^<br />ᐸ165,369ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[165]"}}:::plan
    PgClassExpression369{{"PgClassExpression[369∈36]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression369 --> List370
    __Value351 --> Access353
    First358{{"First[358∈36]^"}}:::plan
    PgSelectRows359[["PgSelectRows[359∈36]^"]]:::plan
    PgSelectRows359 --> First358
    PgSelect354 --> PgSelectRows359
    PgSelectSingle360{{"PgSelectSingle[360∈36]^<br />ᐸorganizationsᐳ"}}:::plan
    First358 --> PgSelectSingle360
    PgSelectSingle360 --> PgClassExpression369
    Lambda371{{"Lambda[371∈36]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List370 --> Lambda371
    PgClassExpression375{{"PgClassExpression[375∈36]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle360 --> PgClassExpression375
    PgSelect362[["PgSelect[362∈37]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access361{{"Access[361∈37]<br />ᐸ351.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access361 --> PgSelect362
    List373{{"List[373∈37]^<br />ᐸ169,372ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[169]"}}:::plan
    PgClassExpression372{{"PgClassExpression[372∈37]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression372 --> List373
    __Value351 --> Access361
    First366{{"First[366∈37]^"}}:::plan
    PgSelectRows367[["PgSelectRows[367∈37]^"]]:::plan
    PgSelectRows367 --> First366
    PgSelect362 --> PgSelectRows367
    PgSelectSingle368{{"PgSelectSingle[368∈37]^<br />ᐸpeopleᐳ"}}:::plan
    First366 --> PgSelectSingle368
    PgSelectSingle368 --> PgClassExpression372
    Lambda374{{"Lambda[374∈37]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List373 --> Lambda374
    PgClassExpression376{{"PgClassExpression[376∈37]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle368 --> PgClassExpression376

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,Access9,Access10,Object11,Connection12 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll13,Access385 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,Access17,Access18,List20,Lambda21,Access22,Access23 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelect24,First28,PgSelectRows29,PgSelectSingle30,PgClassExpression40,List41,Lambda42,PgClassExpression47,Connection53,PgUnionAll59,Connection65,PgUnionAll69,PgUnionAll85,PgUnionAll87,Access377,Access378,Access379,Access380 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect32,First36,PgSelectRows37,PgSelectSingle38,PgClassExpression44,List45,Lambda46,PgClassExpression48,Connection58,PgUnionAll61,Connection68,PgUnionAll71,PgUnionAll86,PgUnionAll88,Access381,Access382,Access383,Access384 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item77,Access89,Access90,List92,Lambda93 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,__Item79,Access94,Access95,List97,Lambda98 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item81,Access117,Access118,List120,Lambda121 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,__Item83,Access122,Access123,List125,Lambda126 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Value99,Access100,Access101 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,__Value127,Access128 bucket12
    classDef bucket13 stroke:#3cb371
    class Bucket13 bucket13
    classDef bucket14 stroke:#a52a2a
    class Bucket14,PgSelect102,First106,PgSelectRows107,PgSelectSingle108,PgClassExpression158,List159,Lambda160,PgClassExpression173,PgClassExpression177,PgClassExpression178,PgUnionAll179,First183,Access251,Access252,List254,Lambda255,Access386 bucket14
    classDef bucket15 stroke:#ff00ff
    class Bucket15,PgSelect110,First114,PgSelectRows115,PgSelectSingle116,PgClassExpression162,List163,Lambda164,PgClassExpression174,PgClassExpression186,PgClassExpression187,PgUnionAll188,First192,Access256,Access257,List259,Lambda260,Access387 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16,Access129,PgSelect130,First134,PgSelectRows135,PgSelectSingle136,PgClassExpression166,List167,Lambda168,PgClassExpression175 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,Access137,PgSelect138,First142,PgSelectRows143,PgSelectSingle144,PgClassExpression170,List171,Lambda172,PgClassExpression176 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18,__Item149,Access195,Access196,List198,Lambda199 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,__Item151,Access200,Access201,List203,Lambda204 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,__Item153,Access223,Access224,List226,Lambda227 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,__Item155,Access228,Access229,List231,Lambda232 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,__Value205,Access206,Access207 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,__Value233,Access234 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,PgSelect208,First212,PgSelectRows213,PgSelectSingle214,PgClassExpression289,List290,Lambda291,PgClassExpression301,PgClassExpression305,PgClassExpression306,PgUnionAll307,First311,Access331,Access332,List334,Lambda335,Access388 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,PgSelect216,First220,PgSelectRows221,PgSelectSingle222,PgClassExpression292,List293,Lambda294,PgClassExpression302,PgClassExpression314,PgClassExpression315,PgUnionAll316,First320,Access336,Access337,List339,Lambda340,Access389 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28,Access235,PgSelect236,First240,PgSelectRows241,PgSelectSingle242,PgClassExpression295,List296,Lambda297,PgClassExpression303 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,Access243,PgSelect244,First248,PgSelectRows249,PgSelectSingle250,PgClassExpression298,List299,Lambda300,PgClassExpression304 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30,__Value271,Access272 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,Access273,PgSelect274,First278,PgSelectRows279,PgSelectSingle280,PgClassExpression323,List324,Lambda325,PgClassExpression329 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,Access281,PgSelect282,First286,PgSelectRows287,PgSelectSingle288,PgClassExpression326,List327,Lambda328,PgClassExpression330 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,__Value351,Access352 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36,Access353,PgSelect354,First358,PgSelectRows359,PgSelectSingle360,PgClassExpression369,List370,Lambda371,PgClassExpression375 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37,Access361,PgSelect362,First366,PgSelectRows367,PgSelectSingle368,PgClassExpression372,List373,Lambda374,PgClassExpression376 bucket37

    Lambda93 -.-x __Value99
    Lambda98 -.-x __Value99
    Lambda121 -.-x __Value127
    Lambda126 -.-x __Value127
    Lambda199 -.-x __Value205
    Lambda204 -.-x __Value205
    Lambda227 -.-x __Value233
    Lambda232 -.-x __Value233
    Lambda255 -.-x __Value271
    Lambda260 -.-x __Value271
    Lambda335 -.-x __Value351
    Lambda340 -.-x __Value351
