%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object17{{"Object[17∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access15{{"Access[15∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access16{{"Access[16∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access15 & Access16 --> Object17
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access15
    __Value2 --> Access16
    Connection18{{"Connection[18∈0] ➊<br />ᐸ14ᐳ"}}:::plan
    Constant122{{"Constant[122∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Constant122 --> Connection18
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgUnionAll19[["PgUnionAll[19∈1] ➊"]]:::plan
    Object17 & Connection18 --> PgUnionAll19
    __Item20[/"__Item[20∈2]<br />ᐸ19ᐳ"\]:::itemplan
    PgUnionAll19 ==> __Item20
    PgUnionAllSingle21["PgUnionAllSingle[21∈2]"]:::plan
    __Item20 --> PgUnionAllSingle21
    Access22{{"Access[22∈2]<br />ᐸ21.1ᐳ"}}:::plan
    PgUnionAllSingle21 --> Access22
    PgUnionAll41[["PgUnionAll[41∈3]<br />ᐳFirstPartyVulnerability"]]:::plan
    PgClassExpression32{{"PgClassExpression[32∈3]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    Connection40{{"Connection[40∈3] ➊<br />ᐸ36ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Object17 & PgClassExpression32 & Connection40 --> PgUnionAll41
    PgUnionAll91[["PgUnionAll[91∈3]<br />ᐳThirdPartyVulnerability"]]:::plan
    PgClassExpression82{{"PgClassExpression[82∈3]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    Connection90{{"Connection[90∈3] ➊<br />ᐸ86ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Object17 & PgClassExpression82 & Connection90 --> PgUnionAll91
    PgSelect25[["PgSelect[25∈3]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access24{{"Access[24∈3]<br />ᐸ23.0ᐳ"}}:::plan
    Object17 & Access24 --> PgSelect25
    List33{{"List[33∈3]<br />ᐸ31,32ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Constant31{{"Constant[31∈3] ➊<br />ᐸ'first_party_vulnerabilities'ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Constant31 & PgClassExpression32 --> List33
    PgSelect75[["PgSelect[75∈3]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access74{{"Access[74∈3]<br />ᐸ73.0ᐳ"}}:::plan
    Object17 & Access74 --> PgSelect75
    List83{{"List[83∈3]<br />ᐸ81,82ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Constant81{{"Constant[81∈3] ➊<br />ᐸ'third_party_vulnerabilities'ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Constant81 & PgClassExpression82 --> List83
    JSONParse23[["JSONParse[23∈3]<br />ᐸ22ᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access22 --> JSONParse23
    JSONParse23 --> Access24
    First29{{"First[29∈3]"}}:::plan
    PgSelect25 --> First29
    PgSelectSingle30{{"PgSelectSingle[30∈3]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First29 --> PgSelectSingle30
    PgSelectSingle30 --> PgClassExpression32
    Lambda34{{"Lambda[34∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List33 --> Lambda34
    PgClassExpression35{{"PgClassExpression[35∈3]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression35
    JSONParse73[["JSONParse[73∈3]<br />ᐸ22ᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access22 --> JSONParse73
    JSONParse73 --> Access74
    First79{{"First[79∈3]"}}:::plan
    PgSelect75 --> First79
    PgSelectSingle80{{"PgSelectSingle[80∈3]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First79 --> PgSelectSingle80
    PgSelectSingle80 --> PgClassExpression82
    Lambda84{{"Lambda[84∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List83 --> Lambda84
    PgClassExpression85{{"PgClassExpression[85∈3]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle80 --> PgClassExpression85
    __Item42[/"__Item[42∈4]<br />ᐸ41ᐳ"\]:::itemplan
    PgUnionAll41 ==> __Item42
    PgUnionAllSingle43["PgUnionAllSingle[43∈4]"]:::plan
    __Item42 --> PgUnionAllSingle43
    Access44{{"Access[44∈4]<br />ᐸ43.1ᐳ"}}:::plan
    PgUnionAllSingle43 --> Access44
    PgSelect47[["PgSelect[47∈5]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access46{{"Access[46∈5]<br />ᐸ45.0ᐳ"}}:::plan
    Object17 & Access46 --> PgSelect47
    List55{{"List[55∈5]<br />ᐸ53,54ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"}}:::plan
    Constant53{{"Constant[53∈5] ➊<br />ᐸ'organizations'ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression54{{"PgClassExpression[54∈5]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant53 & PgClassExpression54 --> List55
    PgSelect61[["PgSelect[61∈5]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access60{{"Access[60∈5]<br />ᐸ59.0ᐳ"}}:::plan
    Object17 & Access60 --> PgSelect61
    List69{{"List[69∈5]<br />ᐸ67,68ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"}}:::plan
    Constant67{{"Constant[67∈5] ➊<br />ᐸ'people'ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression68{{"PgClassExpression[68∈5]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant67 & PgClassExpression68 --> List69
    JSONParse45[["JSONParse[45∈5]<br />ᐸ44ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access44 --> JSONParse45
    JSONParse45 --> Access46
    First51{{"First[51∈5]"}}:::plan
    PgSelect47 --> First51
    PgSelectSingle52{{"PgSelectSingle[52∈5]<br />ᐸorganizationsᐳ"}}:::plan
    First51 --> PgSelectSingle52
    PgSelectSingle52 --> PgClassExpression54
    Lambda56{{"Lambda[56∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List55 --> Lambda56
    PgClassExpression57{{"PgClassExpression[57∈5]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression57
    JSONParse59[["JSONParse[59∈5]<br />ᐸ44ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access44 --> JSONParse59
    JSONParse59 --> Access60
    First65{{"First[65∈5]"}}:::plan
    PgSelect61 --> First65
    PgSelectSingle66{{"PgSelectSingle[66∈5]<br />ᐸpeopleᐳ"}}:::plan
    First65 --> PgSelectSingle66
    PgSelectSingle66 --> PgClassExpression68
    Lambda70{{"Lambda[70∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List69 --> Lambda70
    PgClassExpression71{{"PgClassExpression[71∈5]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle66 --> PgClassExpression71
    __Item92[/"__Item[92∈6]<br />ᐸ91ᐳ"\]:::itemplan
    PgUnionAll91 ==> __Item92
    PgUnionAllSingle93["PgUnionAllSingle[93∈6]"]:::plan
    __Item92 --> PgUnionAllSingle93
    Access94{{"Access[94∈6]<br />ᐸ93.1ᐳ"}}:::plan
    PgUnionAllSingle93 --> Access94
    PgSelect97[["PgSelect[97∈7]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access96{{"Access[96∈7]<br />ᐸ95.0ᐳ"}}:::plan
    Object17 & Access96 --> PgSelect97
    List105{{"List[105∈7]<br />ᐸ103,104ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"}}:::plan
    Constant103{{"Constant[103∈7] ➊<br />ᐸ'organizations'ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression104{{"PgClassExpression[104∈7]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant103 & PgClassExpression104 --> List105
    PgSelect111[["PgSelect[111∈7]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access110{{"Access[110∈7]<br />ᐸ109.0ᐳ"}}:::plan
    Object17 & Access110 --> PgSelect111
    List119{{"List[119∈7]<br />ᐸ117,118ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"}}:::plan
    Constant117{{"Constant[117∈7] ➊<br />ᐸ'people'ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression118{{"PgClassExpression[118∈7]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant117 & PgClassExpression118 --> List119
    JSONParse95[["JSONParse[95∈7]<br />ᐸ94ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access94 --> JSONParse95
    JSONParse95 --> Access96
    First101{{"First[101∈7]"}}:::plan
    PgSelect97 --> First101
    PgSelectSingle102{{"PgSelectSingle[102∈7]<br />ᐸorganizationsᐳ"}}:::plan
    First101 --> PgSelectSingle102
    PgSelectSingle102 --> PgClassExpression104
    Lambda106{{"Lambda[106∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List105 --> Lambda106
    PgClassExpression107{{"PgClassExpression[107∈7]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle102 --> PgClassExpression107
    JSONParse109[["JSONParse[109∈7]<br />ᐸ94ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access94 --> JSONParse109
    JSONParse109 --> Access110
    First115{{"First[115∈7]"}}:::plan
    PgSelect111 --> First115
    PgSelectSingle116{{"PgSelectSingle[116∈7]<br />ᐸpeopleᐳ"}}:::plan
    First115 --> PgSelectSingle116
    PgSelectSingle116 --> PgClassExpression118
    Lambda120{{"Lambda[120∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List119 --> Lambda120
    PgClassExpression121{{"PgClassExpression[121∈7]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle116 --> PgClassExpression121

    %% define steps

    subgraph "Buckets for queries/polymorphic/vulns.union_owners.simple"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access15,Access16,Object17,Connection18,Constant122 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 17, 18<br /><br />ROOT Connectionᐸ14ᐳ[18]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll19 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 17<br /><br />ROOT __Item{2}ᐸ19ᐳ[20]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item20,PgUnionAllSingle21,Access22 bucket2
    Bucket3("Bucket 3 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 22, 17, 21<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: JSONParse[23], JSONParse[73]<br />ᐳ: 31, 40, 81, 90, 24, 74<br />2: PgSelect[25], PgSelect[75]<br />ᐳ: 29, 30, 32, 33, 34, 35, 79, 80, 82, 83, 84, 85<br />3: PgUnionAll[41], PgUnionAll[91]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,JSONParse23,Access24,PgSelect25,First29,PgSelectSingle30,Constant31,PgClassExpression32,List33,Lambda34,PgClassExpression35,Connection40,PgUnionAll41,JSONParse73,Access74,PgSelect75,First79,PgSelectSingle80,Constant81,PgClassExpression82,List83,Lambda84,PgClassExpression85,Connection90,PgUnionAll91 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 17<br /><br />ROOT __Item{4}ᐸ41ᐳ[42]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item42,PgUnionAllSingle43,Access44 bucket4
    Bucket5("Bucket 5 (polymorphic)<br />Organization,Person<br />Deps: 44, 17, 43<br />ᐳFirstPartyVulnerabilityᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[45], JSONParse[59]<br />ᐳ: 53, 67, 46, 60<br />2: PgSelect[47], PgSelect[61]<br />ᐳ: 51, 52, 54, 55, 56, 57, 65, 66, 68, 69, 70, 71"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,JSONParse45,Access46,PgSelect47,First51,PgSelectSingle52,Constant53,PgClassExpression54,List55,Lambda56,PgClassExpression57,JSONParse59,Access60,PgSelect61,First65,PgSelectSingle66,Constant67,PgClassExpression68,List69,Lambda70,PgClassExpression71 bucket5
    Bucket6("Bucket 6 (listItem)<br />Deps: 17<br /><br />ROOT __Item{6}ᐸ91ᐳ[92]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item92,PgUnionAllSingle93,Access94 bucket6
    Bucket7("Bucket 7 (polymorphic)<br />Organization,Person<br />Deps: 94, 17, 93<br />ᐳThirdPartyVulnerabilityᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[95], JSONParse[109]<br />ᐳ: 103, 117, 96, 110<br />2: PgSelect[97], PgSelect[111]<br />ᐳ: 101, 102, 104, 105, 106, 107, 115, 116, 118, 119, 120, 121"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,JSONParse95,Access96,PgSelect97,First101,PgSelectSingle102,Constant103,PgClassExpression104,List105,Lambda106,PgClassExpression107,JSONParse109,Access110,PgSelect111,First115,PgSelectSingle116,Constant117,PgClassExpression118,List119,Lambda120,PgClassExpression121 bucket7
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket6
    Bucket4 --> Bucket5
    Bucket6 --> Bucket7
    end
