%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant612{{"Constant[612∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Constant7{{"Constant[7∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant612 & Constant7 & Constant7 --> Connection12
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Lambda13{{"Lambda[13∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant7 --> Lambda13
    ApplyInput14{{"ApplyInput[14∈0] ➊"}}:::plan
    Constant7 --> ApplyInput14
    Lambda15[["Lambda[15∈0] ➊<br />ᐸlimitToTypesᐳ"]]:::unbatchedplan
    Constant7 --> Lambda15
    Lambda38{{"Lambda[38∈0] ➊<br />ᐸextractList_grafast_applyᐳ"}}:::plan
    Constant7 --> Lambda38
    ApplyInput39{{"ApplyInput[39∈0] ➊"}}:::plan
    Constant7 --> ApplyInput39
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant30{{"Constant[30∈0] ➊<br />ᐸ'first_party_vulnerabilities'ᐳ"}}:::plan
    Constant55{{"Constant[55∈0] ➊<br />ᐸ'aws_applications'ᐳ"}}:::plan
    Constant77{{"Constant[77∈0] ➊<br />ᐸ'organizations'ᐳ"}}:::plan
    Constant89{{"Constant[89∈0] ➊<br />ᐸ'people'ᐳ"}}:::plan
    Constant101{{"Constant[101∈0] ➊<br />ᐸ'gcp_applications'ᐳ"}}:::plan
    Constant316{{"Constant[316∈0] ➊<br />ᐸ'third_party_vulnerabilities'ᐳ"}}:::plan
    PgUnionAll16[["PgUnionAll[16∈1] ➊"]]:::plan
    Object11 & Lambda13 & ApplyInput14 & Lambda15 & Connection12 & Constant612 & Constant7 & Constant7 --> PgUnionAll16
    Access611{{"Access[611∈1] ➊<br />ᐸ16.itemsᐳ"}}:::plan
    PgUnionAll16 --> Access611
    __Item18[/"__Item[18∈2]<br />ᐸ611ᐳ"\]:::itemplan
    Access611 ==> __Item18
    PgUnionAllSingle19["PgUnionAllSingle[19∈2]"]:::plan
    __Item18 --> PgUnionAllSingle19
    Access20{{"Access[20∈2]<br />ᐸ19.1ᐳ"}}:::plan
    PgUnionAllSingle19 --> Access20
    PgUnionAll41[["PgUnionAll[41∈3]<br />ᐳFirstPartyVulnerability"]]:::plan
    PgClassExpression31{{"PgClassExpression[31∈3]<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    Connection37{{"Connection[37∈3] ➊<br />ᐸ35ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Object11 & PgClassExpression31 & Lambda38 & ApplyInput39 & Lambda15 & Connection37 & Constant7 & Constant7 & Constant7 --> PgUnionAll41
    PgUnionAll327[["PgUnionAll[327∈3]<br />ᐳThirdPartyVulnerability"]]:::plan
    PgClassExpression317{{"PgClassExpression[317∈3]<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    Connection323{{"Connection[323∈3] ➊<br />ᐸ321ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Object11 & PgClassExpression317 & Lambda38 & ApplyInput39 & Lambda15 & Connection323 & Constant7 & Constant7 & Constant7 --> PgUnionAll327
    PgUnionAll140[["PgUnionAll[140∈3]<br />ᐳFirstPartyVulnerability"]]:::plan
    Object11 & PgClassExpression31 & Lambda38 & Constant7 & Constant7 & ApplyInput39 & Lambda15 --> PgUnionAll140
    PgUnionAll426[["PgUnionAll[426∈3]<br />ᐳThirdPartyVulnerability"]]:::plan
    Object11 & PgClassExpression317 & Lambda38 & Constant7 & Constant7 & ApplyInput39 & Lambda15 --> PgUnionAll426
    Constant7 & Constant7 & Constant7 --> Connection37
    PgUnionAll246[["PgUnionAll[246∈3]<br />ᐳFirstPartyVulnerability"]]:::plan
    Connection245{{"Connection[245∈3] ➊<br />ᐸ243ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Object11 & PgClassExpression31 & Connection245 --> PgUnionAll246
    Constant7 & Constant7 & Constant7 --> Connection323
    PgUnionAll532[["PgUnionAll[532∈3]<br />ᐳThirdPartyVulnerability"]]:::plan
    Connection531{{"Connection[531∈3] ➊<br />ᐸ529ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Object11 & PgClassExpression317 & Connection531 --> PgUnionAll532
    PgSelect23[["PgSelect[23∈3]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access22{{"Access[22∈3]<br />ᐸ21.0ᐳ"}}:::plan
    Object11 & Access22 --> PgSelect23
    List32{{"List[32∈3]<br />ᐸ30,31ᐳ<br />ᐳFirstPartyVulnerability"}}:::plan
    Constant30 & PgClassExpression31 --> List32
    PgUnionAll277[["PgUnionAll[277∈3]<br />ᐳFirstPartyVulnerability"]]:::plan
    Object11 & PgClassExpression31 --> PgUnionAll277
    PgSelect311[["PgSelect[311∈3]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access310{{"Access[310∈3]<br />ᐸ309.0ᐳ"}}:::plan
    Object11 & Access310 --> PgSelect311
    List318{{"List[318∈3]<br />ᐸ316,317ᐳ<br />ᐳThirdPartyVulnerability"}}:::plan
    Constant316 & PgClassExpression317 --> List318
    PgUnionAll563[["PgUnionAll[563∈3]<br />ᐳThirdPartyVulnerability"]]:::plan
    Object11 & PgClassExpression317 --> PgUnionAll563
    JSONParse21[["JSONParse[21∈3]<br />ᐸ20ᐳ<br />ᐳFirstPartyVulnerability"]]:::plan
    Access20 --> JSONParse21
    JSONParse21 --> Access22
    First27{{"First[27∈3]"}}:::plan
    PgSelectRows28[["PgSelectRows[28∈3]"]]:::plan
    PgSelectRows28 --> First27
    PgSelect23 --> PgSelectRows28
    PgSelectSingle29{{"PgSelectSingle[29∈3]<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First27 --> PgSelectSingle29
    PgSelectSingle29 --> PgClassExpression31
    Lambda33{{"Lambda[33∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List32 --> Lambda33
    PgClassExpression34{{"PgClassExpression[34∈3]<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression34
    JSONParse309[["JSONParse[309∈3]<br />ᐸ20ᐳ<br />ᐳThirdPartyVulnerability"]]:::plan
    Access20 --> JSONParse309
    JSONParse309 --> Access310
    First313{{"First[313∈3]"}}:::plan
    PgSelectRows314[["PgSelectRows[314∈3]"]]:::plan
    PgSelectRows314 --> First313
    PgSelect311 --> PgSelectRows314
    PgSelectSingle315{{"PgSelectSingle[315∈3]<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First313 --> PgSelectSingle315
    PgSelectSingle315 --> PgClassExpression317
    Lambda319{{"Lambda[319∈3]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List318 --> Lambda319
    PgClassExpression320{{"PgClassExpression[320∈3]<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle315 --> PgClassExpression320
    Access597{{"Access[597∈3]<br />ᐸ41.itemsᐳ"}}:::plan
    PgUnionAll41 --> Access597
    Access600{{"Access[600∈3]<br />ᐸ140.itemsᐳ"}}:::plan
    PgUnionAll140 --> Access600
    Access601{{"Access[601∈3]<br />ᐸ246.itemsᐳ"}}:::plan
    PgUnionAll246 --> Access601
    Access602{{"Access[602∈3]<br />ᐸ277.itemsᐳ"}}:::plan
    PgUnionAll277 --> Access602
    Access605{{"Access[605∈3]<br />ᐸ327.itemsᐳ"}}:::plan
    PgUnionAll327 --> Access605
    Access608{{"Access[608∈3]<br />ᐸ426.itemsᐳ"}}:::plan
    PgUnionAll426 --> Access608
    Access609{{"Access[609∈3]<br />ᐸ532.itemsᐳ"}}:::plan
    PgUnionAll532 --> Access609
    Access610{{"Access[610∈3]<br />ᐸ563.itemsᐳ"}}:::plan
    PgUnionAll563 --> Access610
    __Item43[/"__Item[43∈4]<br />ᐸ597ᐳ"\]:::itemplan
    Access597 ==> __Item43
    PgUnionAllSingle44["PgUnionAllSingle[44∈4]"]:::plan
    __Item43 --> PgUnionAllSingle44
    Access45{{"Access[45∈4]<br />ᐸ44.1ᐳ"}}:::plan
    PgUnionAllSingle44 --> Access45
    PgUnionAll62[["PgUnionAll[62∈5]<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    PgClassExpression60{{"PgClassExpression[60∈5]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression61{{"PgClassExpression[61∈5]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression60 & PgClassExpression61 --> PgUnionAll62
    PgUnionAll108[["PgUnionAll[108∈5]<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    PgClassExpression106{{"PgClassExpression[106∈5]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression107{{"PgClassExpression[107∈5]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression106 & PgClassExpression107 --> PgUnionAll108
    PgSelect48[["PgSelect[48∈5]<br />ᐸaws_applicationsᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access47{{"Access[47∈5]<br />ᐸ46.0ᐳ"}}:::plan
    Object11 & Access47 --> PgSelect48
    List57{{"List[57∈5]<br />ᐸ55,56ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"}}:::plan
    PgClassExpression56{{"PgClassExpression[56∈5]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Constant55 & PgClassExpression56 --> List57
    PgSelect96[["PgSelect[96∈5]<br />ᐸgcp_applicationsᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access95{{"Access[95∈5]<br />ᐸ94.0ᐳ"}}:::plan
    Object11 & Access95 --> PgSelect96
    List103{{"List[103∈5]<br />ᐸ101,102ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"}}:::plan
    PgClassExpression102{{"PgClassExpression[102∈5]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Constant101 & PgClassExpression102 --> List103
    JSONParse46[["JSONParse[46∈5]<br />ᐸ45ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access45 --> JSONParse46
    JSONParse46 --> Access47
    First52{{"First[52∈5]"}}:::plan
    PgSelectRows53[["PgSelectRows[53∈5]"]]:::plan
    PgSelectRows53 --> First52
    PgSelect48 --> PgSelectRows53
    PgSelectSingle54{{"PgSelectSingle[54∈5]<br />ᐸaws_applicationsᐳ"}}:::plan
    First52 --> PgSelectSingle54
    PgSelectSingle54 --> PgClassExpression56
    Lambda58{{"Lambda[58∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List57 --> Lambda58
    PgClassExpression59{{"PgClassExpression[59∈5]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression59
    PgSelectSingle54 --> PgClassExpression60
    PgSelectSingle54 --> PgClassExpression61
    First64{{"First[64∈5]"}}:::plan
    Access595{{"Access[595∈5]<br />ᐸ62.itemsᐳ"}}:::plan
    Access595 --> First64
    PgUnionAllSingle66["PgUnionAllSingle[66∈5]"]:::plan
    First64 --> PgUnionAllSingle66
    Access67{{"Access[67∈5]<br />ᐸ66.1ᐳ"}}:::plan
    PgUnionAllSingle66 --> Access67
    JSONParse94[["JSONParse[94∈5]<br />ᐸ45ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access45 --> JSONParse94
    JSONParse94 --> Access95
    First98{{"First[98∈5]"}}:::plan
    PgSelectRows99[["PgSelectRows[99∈5]"]]:::plan
    PgSelectRows99 --> First98
    PgSelect96 --> PgSelectRows99
    PgSelectSingle100{{"PgSelectSingle[100∈5]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First98 --> PgSelectSingle100
    PgSelectSingle100 --> PgClassExpression102
    Lambda104{{"Lambda[104∈5]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List103 --> Lambda104
    PgClassExpression105{{"PgClassExpression[105∈5]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle100 --> PgClassExpression105
    PgSelectSingle100 --> PgClassExpression106
    PgSelectSingle100 --> PgClassExpression107
    First110{{"First[110∈5]"}}:::plan
    Access596{{"Access[596∈5]<br />ᐸ108.itemsᐳ"}}:::plan
    Access596 --> First110
    PgUnionAllSingle112["PgUnionAllSingle[112∈5]"]:::plan
    First110 --> PgUnionAllSingle112
    Access113{{"Access[113∈5]<br />ᐸ112.1ᐳ"}}:::plan
    PgUnionAllSingle112 --> Access113
    PgUnionAll62 --> Access595
    PgUnionAll108 --> Access596
    PgSelect70[["PgSelect[70∈6]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access69{{"Access[69∈6]<br />ᐸ68.0ᐳ"}}:::plan
    Object11 & Access69 --> PgSelect70
    List79{{"List[79∈6]<br />ᐸ77,78ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"}}:::plan
    PgClassExpression78{{"PgClassExpression[78∈6]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression78 --> List79
    PgSelect84[["PgSelect[84∈6]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access83{{"Access[83∈6]<br />ᐸ82.0ᐳ"}}:::plan
    Object11 & Access83 --> PgSelect84
    List91{{"List[91∈6]<br />ᐸ89,90ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"}}:::plan
    PgClassExpression90{{"PgClassExpression[90∈6]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression90 --> List91
    JSONParse68[["JSONParse[68∈6]<br />ᐸ67ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access67 --> JSONParse68
    JSONParse68 --> Access69
    First74{{"First[74∈6]"}}:::plan
    PgSelectRows75[["PgSelectRows[75∈6]"]]:::plan
    PgSelectRows75 --> First74
    PgSelect70 --> PgSelectRows75
    PgSelectSingle76{{"PgSelectSingle[76∈6]<br />ᐸorganizationsᐳ"}}:::plan
    First74 --> PgSelectSingle76
    PgSelectSingle76 --> PgClassExpression78
    Lambda80{{"Lambda[80∈6]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List79 --> Lambda80
    PgClassExpression81{{"PgClassExpression[81∈6]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle76 --> PgClassExpression81
    JSONParse82[["JSONParse[82∈6]<br />ᐸ67ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access67 --> JSONParse82
    JSONParse82 --> Access83
    First86{{"First[86∈6]"}}:::plan
    PgSelectRows87[["PgSelectRows[87∈6]"]]:::plan
    PgSelectRows87 --> First86
    PgSelect84 --> PgSelectRows87
    PgSelectSingle88{{"PgSelectSingle[88∈6]<br />ᐸpeopleᐳ"}}:::plan
    First86 --> PgSelectSingle88
    PgSelectSingle88 --> PgClassExpression90
    Lambda92{{"Lambda[92∈6]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List91 --> Lambda92
    PgClassExpression93{{"PgClassExpression[93∈6]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle88 --> PgClassExpression93
    PgSelect116[["PgSelect[116∈7]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access115{{"Access[115∈7]<br />ᐸ114.0ᐳ"}}:::plan
    Object11 & Access115 --> PgSelect116
    List125{{"List[125∈7]<br />ᐸ77,124ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"}}:::plan
    PgClassExpression124{{"PgClassExpression[124∈7]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression124 --> List125
    PgSelect130[["PgSelect[130∈7]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access129{{"Access[129∈7]<br />ᐸ128.0ᐳ"}}:::plan
    Object11 & Access129 --> PgSelect130
    List137{{"List[137∈7]<br />ᐸ89,136ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"}}:::plan
    PgClassExpression136{{"PgClassExpression[136∈7]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression136 --> List137
    JSONParse114[["JSONParse[114∈7]<br />ᐸ113ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access113 --> JSONParse114
    JSONParse114 --> Access115
    First120{{"First[120∈7]"}}:::plan
    PgSelectRows121[["PgSelectRows[121∈7]"]]:::plan
    PgSelectRows121 --> First120
    PgSelect116 --> PgSelectRows121
    PgSelectSingle122{{"PgSelectSingle[122∈7]<br />ᐸorganizationsᐳ"}}:::plan
    First120 --> PgSelectSingle122
    PgSelectSingle122 --> PgClassExpression124
    Lambda126{{"Lambda[126∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List125 --> Lambda126
    PgClassExpression127{{"PgClassExpression[127∈7]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle122 --> PgClassExpression127
    JSONParse128[["JSONParse[128∈7]<br />ᐸ113ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access113 --> JSONParse128
    JSONParse128 --> Access129
    First132{{"First[132∈7]"}}:::plan
    PgSelectRows133[["PgSelectRows[133∈7]"]]:::plan
    PgSelectRows133 --> First132
    PgSelect130 --> PgSelectRows133
    PgSelectSingle134{{"PgSelectSingle[134∈7]<br />ᐸpeopleᐳ"}}:::plan
    First132 --> PgSelectSingle134
    PgSelectSingle134 --> PgClassExpression136
    Lambda138{{"Lambda[138∈7]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List137 --> Lambda138
    PgClassExpression139{{"PgClassExpression[139∈7]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle134 --> PgClassExpression139
    __Item146[/"__Item[146∈8]<br />ᐸ600ᐳ"\]:::itemplan
    Access600 ==> __Item146
    PgUnionAllSingle147["PgUnionAllSingle[147∈8]"]:::plan
    __Item146 --> PgUnionAllSingle147
    Access148{{"Access[148∈8]<br />ᐸ147.1ᐳ"}}:::plan
    PgUnionAllSingle147 --> Access148
    PgUnionAll165[["PgUnionAll[165∈9]<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    PgClassExpression163{{"PgClassExpression[163∈9]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression164{{"PgClassExpression[164∈9]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression163 & PgClassExpression164 --> PgUnionAll165
    PgUnionAll211[["PgUnionAll[211∈9]<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    PgClassExpression209{{"PgClassExpression[209∈9]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression210{{"PgClassExpression[210∈9]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression209 & PgClassExpression210 --> PgUnionAll211
    PgSelect151[["PgSelect[151∈9]<br />ᐸaws_applicationsᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access150{{"Access[150∈9]<br />ᐸ149.0ᐳ"}}:::plan
    Object11 & Access150 --> PgSelect151
    List160{{"List[160∈9]<br />ᐸ55,159ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"}}:::plan
    PgClassExpression159{{"PgClassExpression[159∈9]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Constant55 & PgClassExpression159 --> List160
    PgSelect199[["PgSelect[199∈9]<br />ᐸgcp_applicationsᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access198{{"Access[198∈9]<br />ᐸ197.0ᐳ"}}:::plan
    Object11 & Access198 --> PgSelect199
    List206{{"List[206∈9]<br />ᐸ101,205ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"}}:::plan
    PgClassExpression205{{"PgClassExpression[205∈9]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Constant101 & PgClassExpression205 --> List206
    JSONParse149[["JSONParse[149∈9]<br />ᐸ148ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access148 --> JSONParse149
    JSONParse149 --> Access150
    First155{{"First[155∈9]"}}:::plan
    PgSelectRows156[["PgSelectRows[156∈9]"]]:::plan
    PgSelectRows156 --> First155
    PgSelect151 --> PgSelectRows156
    PgSelectSingle157{{"PgSelectSingle[157∈9]<br />ᐸaws_applicationsᐳ"}}:::plan
    First155 --> PgSelectSingle157
    PgSelectSingle157 --> PgClassExpression159
    Lambda161{{"Lambda[161∈9]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List160 --> Lambda161
    PgClassExpression162{{"PgClassExpression[162∈9]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle157 --> PgClassExpression162
    PgSelectSingle157 --> PgClassExpression163
    PgSelectSingle157 --> PgClassExpression164
    First167{{"First[167∈9]"}}:::plan
    Access598{{"Access[598∈9]<br />ᐸ165.itemsᐳ"}}:::plan
    Access598 --> First167
    PgUnionAllSingle169["PgUnionAllSingle[169∈9]"]:::plan
    First167 --> PgUnionAllSingle169
    Access170{{"Access[170∈9]<br />ᐸ169.1ᐳ"}}:::plan
    PgUnionAllSingle169 --> Access170
    JSONParse197[["JSONParse[197∈9]<br />ᐸ148ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access148 --> JSONParse197
    JSONParse197 --> Access198
    First201{{"First[201∈9]"}}:::plan
    PgSelectRows202[["PgSelectRows[202∈9]"]]:::plan
    PgSelectRows202 --> First201
    PgSelect199 --> PgSelectRows202
    PgSelectSingle203{{"PgSelectSingle[203∈9]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First201 --> PgSelectSingle203
    PgSelectSingle203 --> PgClassExpression205
    Lambda207{{"Lambda[207∈9]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List206 --> Lambda207
    PgClassExpression208{{"PgClassExpression[208∈9]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle203 --> PgClassExpression208
    PgSelectSingle203 --> PgClassExpression209
    PgSelectSingle203 --> PgClassExpression210
    First213{{"First[213∈9]"}}:::plan
    Access599{{"Access[599∈9]<br />ᐸ211.itemsᐳ"}}:::plan
    Access599 --> First213
    PgUnionAllSingle215["PgUnionAllSingle[215∈9]"]:::plan
    First213 --> PgUnionAllSingle215
    Access216{{"Access[216∈9]<br />ᐸ215.1ᐳ"}}:::plan
    PgUnionAllSingle215 --> Access216
    PgUnionAll165 --> Access598
    PgUnionAll211 --> Access599
    PgSelect173[["PgSelect[173∈10]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access172{{"Access[172∈10]<br />ᐸ171.0ᐳ"}}:::plan
    Object11 & Access172 --> PgSelect173
    List182{{"List[182∈10]<br />ᐸ77,181ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"}}:::plan
    PgClassExpression181{{"PgClassExpression[181∈10]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression181 --> List182
    PgSelect187[["PgSelect[187∈10]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access186{{"Access[186∈10]<br />ᐸ185.0ᐳ"}}:::plan
    Object11 & Access186 --> PgSelect187
    List194{{"List[194∈10]<br />ᐸ89,193ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"}}:::plan
    PgClassExpression193{{"PgClassExpression[193∈10]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression193 --> List194
    JSONParse171[["JSONParse[171∈10]<br />ᐸ170ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access170 --> JSONParse171
    JSONParse171 --> Access172
    First177{{"First[177∈10]"}}:::plan
    PgSelectRows178[["PgSelectRows[178∈10]"]]:::plan
    PgSelectRows178 --> First177
    PgSelect173 --> PgSelectRows178
    PgSelectSingle179{{"PgSelectSingle[179∈10]<br />ᐸorganizationsᐳ"}}:::plan
    First177 --> PgSelectSingle179
    PgSelectSingle179 --> PgClassExpression181
    Lambda183{{"Lambda[183∈10]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List182 --> Lambda183
    PgClassExpression184{{"PgClassExpression[184∈10]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle179 --> PgClassExpression184
    JSONParse185[["JSONParse[185∈10]<br />ᐸ170ᐳ<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access170 --> JSONParse185
    JSONParse185 --> Access186
    First189{{"First[189∈10]"}}:::plan
    PgSelectRows190[["PgSelectRows[190∈10]"]]:::plan
    PgSelectRows190 --> First189
    PgSelect187 --> PgSelectRows190
    PgSelectSingle191{{"PgSelectSingle[191∈10]<br />ᐸpeopleᐳ"}}:::plan
    First189 --> PgSelectSingle191
    PgSelectSingle191 --> PgClassExpression193
    Lambda195{{"Lambda[195∈10]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List194 --> Lambda195
    PgClassExpression196{{"PgClassExpression[196∈10]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle191 --> PgClassExpression196
    PgSelect219[["PgSelect[219∈11]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access218{{"Access[218∈11]<br />ᐸ217.0ᐳ"}}:::plan
    Object11 & Access218 --> PgSelect219
    List228{{"List[228∈11]<br />ᐸ77,227ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"}}:::plan
    PgClassExpression227{{"PgClassExpression[227∈11]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression227 --> List228
    PgSelect233[["PgSelect[233∈11]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access232{{"Access[232∈11]<br />ᐸ231.0ᐳ"}}:::plan
    Object11 & Access232 --> PgSelect233
    List240{{"List[240∈11]<br />ᐸ89,239ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"}}:::plan
    PgClassExpression239{{"PgClassExpression[239∈11]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression239 --> List240
    JSONParse217[["JSONParse[217∈11]<br />ᐸ216ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access216 --> JSONParse217
    JSONParse217 --> Access218
    First223{{"First[223∈11]"}}:::plan
    PgSelectRows224[["PgSelectRows[224∈11]"]]:::plan
    PgSelectRows224 --> First223
    PgSelect219 --> PgSelectRows224
    PgSelectSingle225{{"PgSelectSingle[225∈11]<br />ᐸorganizationsᐳ"}}:::plan
    First223 --> PgSelectSingle225
    PgSelectSingle225 --> PgClassExpression227
    Lambda229{{"Lambda[229∈11]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List228 --> Lambda229
    PgClassExpression230{{"PgClassExpression[230∈11]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle225 --> PgClassExpression230
    JSONParse231[["JSONParse[231∈11]<br />ᐸ216ᐳ<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access216 --> JSONParse231
    JSONParse231 --> Access232
    First235{{"First[235∈11]"}}:::plan
    PgSelectRows236[["PgSelectRows[236∈11]"]]:::plan
    PgSelectRows236 --> First235
    PgSelect233 --> PgSelectRows236
    PgSelectSingle237{{"PgSelectSingle[237∈11]<br />ᐸpeopleᐳ"}}:::plan
    First235 --> PgSelectSingle237
    PgSelectSingle237 --> PgClassExpression239
    Lambda241{{"Lambda[241∈11]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List240 --> Lambda241
    PgClassExpression242{{"PgClassExpression[242∈11]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle237 --> PgClassExpression242
    __Item248[/"__Item[248∈12]<br />ᐸ601ᐳ"\]:::itemplan
    Access601 ==> __Item248
    PgUnionAllSingle249["PgUnionAllSingle[249∈12]"]:::plan
    __Item248 --> PgUnionAllSingle249
    Access250{{"Access[250∈12]<br />ᐸ249.1ᐳ"}}:::plan
    PgUnionAllSingle249 --> Access250
    PgSelect253[["PgSelect[253∈13]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access252{{"Access[252∈13]<br />ᐸ251.0ᐳ"}}:::plan
    Object11 & Access252 --> PgSelect253
    List262{{"List[262∈13]<br />ᐸ77,261ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression261{{"PgClassExpression[261∈13]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression261 --> List262
    PgSelect267[["PgSelect[267∈13]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access266{{"Access[266∈13]<br />ᐸ265.0ᐳ"}}:::plan
    Object11 & Access266 --> PgSelect267
    List274{{"List[274∈13]<br />ᐸ89,273ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression273{{"PgClassExpression[273∈13]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression273 --> List274
    JSONParse251[["JSONParse[251∈13]<br />ᐸ250ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access250 --> JSONParse251
    JSONParse251 --> Access252
    First257{{"First[257∈13]"}}:::plan
    PgSelectRows258[["PgSelectRows[258∈13]"]]:::plan
    PgSelectRows258 --> First257
    PgSelect253 --> PgSelectRows258
    PgSelectSingle259{{"PgSelectSingle[259∈13]<br />ᐸorganizationsᐳ"}}:::plan
    First257 --> PgSelectSingle259
    PgSelectSingle259 --> PgClassExpression261
    Lambda263{{"Lambda[263∈13]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List262 --> Lambda263
    PgClassExpression264{{"PgClassExpression[264∈13]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle259 --> PgClassExpression264
    JSONParse265[["JSONParse[265∈13]<br />ᐸ250ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access250 --> JSONParse265
    JSONParse265 --> Access266
    First269{{"First[269∈13]"}}:::plan
    PgSelectRows270[["PgSelectRows[270∈13]"]]:::plan
    PgSelectRows270 --> First269
    PgSelect267 --> PgSelectRows270
    PgSelectSingle271{{"PgSelectSingle[271∈13]<br />ᐸpeopleᐳ"}}:::plan
    First269 --> PgSelectSingle271
    PgSelectSingle271 --> PgClassExpression273
    Lambda275{{"Lambda[275∈13]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List274 --> Lambda275
    PgClassExpression276{{"PgClassExpression[276∈13]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle271 --> PgClassExpression276
    __Item280[/"__Item[280∈14]<br />ᐸ602ᐳ"\]:::itemplan
    Access602 ==> __Item280
    PgUnionAllSingle281["PgUnionAllSingle[281∈14]"]:::plan
    __Item280 --> PgUnionAllSingle281
    Access282{{"Access[282∈14]<br />ᐸ281.1ᐳ"}}:::plan
    PgUnionAllSingle281 --> Access282
    PgSelect285[["PgSelect[285∈15]<br />ᐸorganizationsᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access284{{"Access[284∈15]<br />ᐸ283.0ᐳ"}}:::plan
    Object11 & Access284 --> PgSelect285
    List294{{"List[294∈15]<br />ᐸ77,293ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression293{{"PgClassExpression[293∈15]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression293 --> List294
    PgSelect299[["PgSelect[299∈15]<br />ᐸpeopleᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access298{{"Access[298∈15]<br />ᐸ297.0ᐳ"}}:::plan
    Object11 & Access298 --> PgSelect299
    List306{{"List[306∈15]<br />ᐸ89,305ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression305{{"PgClassExpression[305∈15]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression305 --> List306
    JSONParse283[["JSONParse[283∈15]<br />ᐸ282ᐳ<br />ᐳFirstPartyVulnerabilityᐳOrganization"]]:::plan
    Access282 --> JSONParse283
    JSONParse283 --> Access284
    First289{{"First[289∈15]"}}:::plan
    PgSelectRows290[["PgSelectRows[290∈15]"]]:::plan
    PgSelectRows290 --> First289
    PgSelect285 --> PgSelectRows290
    PgSelectSingle291{{"PgSelectSingle[291∈15]<br />ᐸorganizationsᐳ"}}:::plan
    First289 --> PgSelectSingle291
    PgSelectSingle291 --> PgClassExpression293
    Lambda295{{"Lambda[295∈15]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List294 --> Lambda295
    PgClassExpression296{{"PgClassExpression[296∈15]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle291 --> PgClassExpression296
    JSONParse297[["JSONParse[297∈15]<br />ᐸ282ᐳ<br />ᐳFirstPartyVulnerabilityᐳPerson"]]:::plan
    Access282 --> JSONParse297
    JSONParse297 --> Access298
    First301{{"First[301∈15]"}}:::plan
    PgSelectRows302[["PgSelectRows[302∈15]"]]:::plan
    PgSelectRows302 --> First301
    PgSelect299 --> PgSelectRows302
    PgSelectSingle303{{"PgSelectSingle[303∈15]<br />ᐸpeopleᐳ"}}:::plan
    First301 --> PgSelectSingle303
    PgSelectSingle303 --> PgClassExpression305
    Lambda307{{"Lambda[307∈15]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List306 --> Lambda307
    PgClassExpression308{{"PgClassExpression[308∈15]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle303 --> PgClassExpression308
    __Item329[/"__Item[329∈16]<br />ᐸ605ᐳ"\]:::itemplan
    Access605 ==> __Item329
    PgUnionAllSingle330["PgUnionAllSingle[330∈16]"]:::plan
    __Item329 --> PgUnionAllSingle330
    Access331{{"Access[331∈16]<br />ᐸ330.1ᐳ"}}:::plan
    PgUnionAllSingle330 --> Access331
    PgUnionAll348[["PgUnionAll[348∈17]<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    PgClassExpression346{{"PgClassExpression[346∈17]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression347{{"PgClassExpression[347∈17]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression346 & PgClassExpression347 --> PgUnionAll348
    PgUnionAll394[["PgUnionAll[394∈17]<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    PgClassExpression392{{"PgClassExpression[392∈17]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression393{{"PgClassExpression[393∈17]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression392 & PgClassExpression393 --> PgUnionAll394
    PgSelect334[["PgSelect[334∈17]<br />ᐸaws_applicationsᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access333{{"Access[333∈17]<br />ᐸ332.0ᐳ"}}:::plan
    Object11 & Access333 --> PgSelect334
    List343{{"List[343∈17]<br />ᐸ55,342ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"}}:::plan
    PgClassExpression342{{"PgClassExpression[342∈17]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Constant55 & PgClassExpression342 --> List343
    PgSelect382[["PgSelect[382∈17]<br />ᐸgcp_applicationsᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access381{{"Access[381∈17]<br />ᐸ380.0ᐳ"}}:::plan
    Object11 & Access381 --> PgSelect382
    List389{{"List[389∈17]<br />ᐸ101,388ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"}}:::plan
    PgClassExpression388{{"PgClassExpression[388∈17]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Constant101 & PgClassExpression388 --> List389
    JSONParse332[["JSONParse[332∈17]<br />ᐸ331ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access331 --> JSONParse332
    JSONParse332 --> Access333
    First338{{"First[338∈17]"}}:::plan
    PgSelectRows339[["PgSelectRows[339∈17]"]]:::plan
    PgSelectRows339 --> First338
    PgSelect334 --> PgSelectRows339
    PgSelectSingle340{{"PgSelectSingle[340∈17]<br />ᐸaws_applicationsᐳ"}}:::plan
    First338 --> PgSelectSingle340
    PgSelectSingle340 --> PgClassExpression342
    Lambda344{{"Lambda[344∈17]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List343 --> Lambda344
    PgClassExpression345{{"PgClassExpression[345∈17]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle340 --> PgClassExpression345
    PgSelectSingle340 --> PgClassExpression346
    PgSelectSingle340 --> PgClassExpression347
    First350{{"First[350∈17]"}}:::plan
    Access603{{"Access[603∈17]<br />ᐸ348.itemsᐳ"}}:::plan
    Access603 --> First350
    PgUnionAllSingle352["PgUnionAllSingle[352∈17]"]:::plan
    First350 --> PgUnionAllSingle352
    Access353{{"Access[353∈17]<br />ᐸ352.1ᐳ"}}:::plan
    PgUnionAllSingle352 --> Access353
    JSONParse380[["JSONParse[380∈17]<br />ᐸ331ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access331 --> JSONParse380
    JSONParse380 --> Access381
    First384{{"First[384∈17]"}}:::plan
    PgSelectRows385[["PgSelectRows[385∈17]"]]:::plan
    PgSelectRows385 --> First384
    PgSelect382 --> PgSelectRows385
    PgSelectSingle386{{"PgSelectSingle[386∈17]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First384 --> PgSelectSingle386
    PgSelectSingle386 --> PgClassExpression388
    Lambda390{{"Lambda[390∈17]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List389 --> Lambda390
    PgClassExpression391{{"PgClassExpression[391∈17]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle386 --> PgClassExpression391
    PgSelectSingle386 --> PgClassExpression392
    PgSelectSingle386 --> PgClassExpression393
    First396{{"First[396∈17]"}}:::plan
    Access604{{"Access[604∈17]<br />ᐸ394.itemsᐳ"}}:::plan
    Access604 --> First396
    PgUnionAllSingle398["PgUnionAllSingle[398∈17]"]:::plan
    First396 --> PgUnionAllSingle398
    Access399{{"Access[399∈17]<br />ᐸ398.1ᐳ"}}:::plan
    PgUnionAllSingle398 --> Access399
    PgUnionAll348 --> Access603
    PgUnionAll394 --> Access604
    PgSelect356[["PgSelect[356∈18]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access355{{"Access[355∈18]<br />ᐸ354.0ᐳ"}}:::plan
    Object11 & Access355 --> PgSelect356
    List365{{"List[365∈18]<br />ᐸ77,364ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"}}:::plan
    PgClassExpression364{{"PgClassExpression[364∈18]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression364 --> List365
    PgSelect370[["PgSelect[370∈18]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access369{{"Access[369∈18]<br />ᐸ368.0ᐳ"}}:::plan
    Object11 & Access369 --> PgSelect370
    List377{{"List[377∈18]<br />ᐸ89,376ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"}}:::plan
    PgClassExpression376{{"PgClassExpression[376∈18]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression376 --> List377
    JSONParse354[["JSONParse[354∈18]<br />ᐸ353ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access353 --> JSONParse354
    JSONParse354 --> Access355
    First360{{"First[360∈18]"}}:::plan
    PgSelectRows361[["PgSelectRows[361∈18]"]]:::plan
    PgSelectRows361 --> First360
    PgSelect356 --> PgSelectRows361
    PgSelectSingle362{{"PgSelectSingle[362∈18]<br />ᐸorganizationsᐳ"}}:::plan
    First360 --> PgSelectSingle362
    PgSelectSingle362 --> PgClassExpression364
    Lambda366{{"Lambda[366∈18]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List365 --> Lambda366
    PgClassExpression367{{"PgClassExpression[367∈18]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle362 --> PgClassExpression367
    JSONParse368[["JSONParse[368∈18]<br />ᐸ353ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access353 --> JSONParse368
    JSONParse368 --> Access369
    First372{{"First[372∈18]"}}:::plan
    PgSelectRows373[["PgSelectRows[373∈18]"]]:::plan
    PgSelectRows373 --> First372
    PgSelect370 --> PgSelectRows373
    PgSelectSingle374{{"PgSelectSingle[374∈18]<br />ᐸpeopleᐳ"}}:::plan
    First372 --> PgSelectSingle374
    PgSelectSingle374 --> PgClassExpression376
    Lambda378{{"Lambda[378∈18]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List377 --> Lambda378
    PgClassExpression379{{"PgClassExpression[379∈18]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle374 --> PgClassExpression379
    PgSelect402[["PgSelect[402∈19]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access401{{"Access[401∈19]<br />ᐸ400.0ᐳ"}}:::plan
    Object11 & Access401 --> PgSelect402
    List411{{"List[411∈19]<br />ᐸ77,410ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"}}:::plan
    PgClassExpression410{{"PgClassExpression[410∈19]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression410 --> List411
    PgSelect416[["PgSelect[416∈19]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access415{{"Access[415∈19]<br />ᐸ414.0ᐳ"}}:::plan
    Object11 & Access415 --> PgSelect416
    List423{{"List[423∈19]<br />ᐸ89,422ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"}}:::plan
    PgClassExpression422{{"PgClassExpression[422∈19]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression422 --> List423
    JSONParse400[["JSONParse[400∈19]<br />ᐸ399ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access399 --> JSONParse400
    JSONParse400 --> Access401
    First406{{"First[406∈19]"}}:::plan
    PgSelectRows407[["PgSelectRows[407∈19]"]]:::plan
    PgSelectRows407 --> First406
    PgSelect402 --> PgSelectRows407
    PgSelectSingle408{{"PgSelectSingle[408∈19]<br />ᐸorganizationsᐳ"}}:::plan
    First406 --> PgSelectSingle408
    PgSelectSingle408 --> PgClassExpression410
    Lambda412{{"Lambda[412∈19]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List411 --> Lambda412
    PgClassExpression413{{"PgClassExpression[413∈19]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle408 --> PgClassExpression413
    JSONParse414[["JSONParse[414∈19]<br />ᐸ399ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access399 --> JSONParse414
    JSONParse414 --> Access415
    First418{{"First[418∈19]"}}:::plan
    PgSelectRows419[["PgSelectRows[419∈19]"]]:::plan
    PgSelectRows419 --> First418
    PgSelect416 --> PgSelectRows419
    PgSelectSingle420{{"PgSelectSingle[420∈19]<br />ᐸpeopleᐳ"}}:::plan
    First418 --> PgSelectSingle420
    PgSelectSingle420 --> PgClassExpression422
    Lambda424{{"Lambda[424∈19]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List423 --> Lambda424
    PgClassExpression425{{"PgClassExpression[425∈19]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle420 --> PgClassExpression425
    __Item432[/"__Item[432∈20]<br />ᐸ608ᐳ"\]:::itemplan
    Access608 ==> __Item432
    PgUnionAllSingle433["PgUnionAllSingle[433∈20]"]:::plan
    __Item432 --> PgUnionAllSingle433
    Access434{{"Access[434∈20]<br />ᐸ433.1ᐳ"}}:::plan
    PgUnionAllSingle433 --> Access434
    PgUnionAll451[["PgUnionAll[451∈21]<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    PgClassExpression449{{"PgClassExpression[449∈21]<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression450{{"PgClassExpression[450∈21]<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression449 & PgClassExpression450 --> PgUnionAll451
    PgUnionAll497[["PgUnionAll[497∈21]<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    PgClassExpression495{{"PgClassExpression[495∈21]<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression496{{"PgClassExpression[496∈21]<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    Object11 & PgClassExpression495 & PgClassExpression496 --> PgUnionAll497
    PgSelect437[["PgSelect[437∈21]<br />ᐸaws_applicationsᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access436{{"Access[436∈21]<br />ᐸ435.0ᐳ"}}:::plan
    Object11 & Access436 --> PgSelect437
    List446{{"List[446∈21]<br />ᐸ55,445ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"}}:::plan
    PgClassExpression445{{"PgClassExpression[445∈21]<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    Constant55 & PgClassExpression445 --> List446
    PgSelect485[["PgSelect[485∈21]<br />ᐸgcp_applicationsᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access484{{"Access[484∈21]<br />ᐸ483.0ᐳ"}}:::plan
    Object11 & Access484 --> PgSelect485
    List492{{"List[492∈21]<br />ᐸ101,491ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"}}:::plan
    PgClassExpression491{{"PgClassExpression[491∈21]<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    Constant101 & PgClassExpression491 --> List492
    JSONParse435[["JSONParse[435∈21]<br />ᐸ434ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplication"]]:::plan
    Access434 --> JSONParse435
    JSONParse435 --> Access436
    First441{{"First[441∈21]"}}:::plan
    PgSelectRows442[["PgSelectRows[442∈21]"]]:::plan
    PgSelectRows442 --> First441
    PgSelect437 --> PgSelectRows442
    PgSelectSingle443{{"PgSelectSingle[443∈21]<br />ᐸaws_applicationsᐳ"}}:::plan
    First441 --> PgSelectSingle443
    PgSelectSingle443 --> PgClassExpression445
    Lambda447{{"Lambda[447∈21]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List446 --> Lambda447
    PgClassExpression448{{"PgClassExpression[448∈21]<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle443 --> PgClassExpression448
    PgSelectSingle443 --> PgClassExpression449
    PgSelectSingle443 --> PgClassExpression450
    First453{{"First[453∈21]"}}:::plan
    Access606{{"Access[606∈21]<br />ᐸ451.itemsᐳ"}}:::plan
    Access606 --> First453
    PgUnionAllSingle455["PgUnionAllSingle[455∈21]"]:::plan
    First453 --> PgUnionAllSingle455
    Access456{{"Access[456∈21]<br />ᐸ455.1ᐳ"}}:::plan
    PgUnionAllSingle455 --> Access456
    JSONParse483[["JSONParse[483∈21]<br />ᐸ434ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplication"]]:::plan
    Access434 --> JSONParse483
    JSONParse483 --> Access484
    First487{{"First[487∈21]"}}:::plan
    PgSelectRows488[["PgSelectRows[488∈21]"]]:::plan
    PgSelectRows488 --> First487
    PgSelect485 --> PgSelectRows488
    PgSelectSingle489{{"PgSelectSingle[489∈21]<br />ᐸgcp_applicationsᐳ"}}:::plan
    First487 --> PgSelectSingle489
    PgSelectSingle489 --> PgClassExpression491
    Lambda493{{"Lambda[493∈21]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List492 --> Lambda493
    PgClassExpression494{{"PgClassExpression[494∈21]<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle489 --> PgClassExpression494
    PgSelectSingle489 --> PgClassExpression495
    PgSelectSingle489 --> PgClassExpression496
    First499{{"First[499∈21]"}}:::plan
    Access607{{"Access[607∈21]<br />ᐸ497.itemsᐳ"}}:::plan
    Access607 --> First499
    PgUnionAllSingle501["PgUnionAllSingle[501∈21]"]:::plan
    First499 --> PgUnionAllSingle501
    Access502{{"Access[502∈21]<br />ᐸ501.1ᐳ"}}:::plan
    PgUnionAllSingle501 --> Access502
    PgUnionAll451 --> Access606
    PgUnionAll497 --> Access607
    PgSelect459[["PgSelect[459∈22]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access458{{"Access[458∈22]<br />ᐸ457.0ᐳ"}}:::plan
    Object11 & Access458 --> PgSelect459
    List468{{"List[468∈22]<br />ᐸ77,467ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"}}:::plan
    PgClassExpression467{{"PgClassExpression[467∈22]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression467 --> List468
    PgSelect473[["PgSelect[473∈22]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access472{{"Access[472∈22]<br />ᐸ471.0ᐳ"}}:::plan
    Object11 & Access472 --> PgSelect473
    List480{{"List[480∈22]<br />ᐸ89,479ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"}}:::plan
    PgClassExpression479{{"PgClassExpression[479∈22]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression479 --> List480
    JSONParse457[["JSONParse[457∈22]<br />ᐸ456ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization"]]:::plan
    Access456 --> JSONParse457
    JSONParse457 --> Access458
    First463{{"First[463∈22]"}}:::plan
    PgSelectRows464[["PgSelectRows[464∈22]"]]:::plan
    PgSelectRows464 --> First463
    PgSelect459 --> PgSelectRows464
    PgSelectSingle465{{"PgSelectSingle[465∈22]<br />ᐸorganizationsᐳ"}}:::plan
    First463 --> PgSelectSingle465
    PgSelectSingle465 --> PgClassExpression467
    Lambda469{{"Lambda[469∈22]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List468 --> Lambda469
    PgClassExpression470{{"PgClassExpression[470∈22]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle465 --> PgClassExpression470
    JSONParse471[["JSONParse[471∈22]<br />ᐸ456ᐳ<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson"]]:::plan
    Access456 --> JSONParse471
    JSONParse471 --> Access472
    First475{{"First[475∈22]"}}:::plan
    PgSelectRows476[["PgSelectRows[476∈22]"]]:::plan
    PgSelectRows476 --> First475
    PgSelect473 --> PgSelectRows476
    PgSelectSingle477{{"PgSelectSingle[477∈22]<br />ᐸpeopleᐳ"}}:::plan
    First475 --> PgSelectSingle477
    PgSelectSingle477 --> PgClassExpression479
    Lambda481{{"Lambda[481∈22]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List480 --> Lambda481
    PgClassExpression482{{"PgClassExpression[482∈22]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle477 --> PgClassExpression482
    PgSelect505[["PgSelect[505∈23]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access504{{"Access[504∈23]<br />ᐸ503.0ᐳ"}}:::plan
    Object11 & Access504 --> PgSelect505
    List514{{"List[514∈23]<br />ᐸ77,513ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"}}:::plan
    PgClassExpression513{{"PgClassExpression[513∈23]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression513 --> List514
    PgSelect519[["PgSelect[519∈23]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access518{{"Access[518∈23]<br />ᐸ517.0ᐳ"}}:::plan
    Object11 & Access518 --> PgSelect519
    List526{{"List[526∈23]<br />ᐸ89,525ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"}}:::plan
    PgClassExpression525{{"PgClassExpression[525∈23]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression525 --> List526
    JSONParse503[["JSONParse[503∈23]<br />ᐸ502ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization"]]:::plan
    Access502 --> JSONParse503
    JSONParse503 --> Access504
    First509{{"First[509∈23]"}}:::plan
    PgSelectRows510[["PgSelectRows[510∈23]"]]:::plan
    PgSelectRows510 --> First509
    PgSelect505 --> PgSelectRows510
    PgSelectSingle511{{"PgSelectSingle[511∈23]<br />ᐸorganizationsᐳ"}}:::plan
    First509 --> PgSelectSingle511
    PgSelectSingle511 --> PgClassExpression513
    Lambda515{{"Lambda[515∈23]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List514 --> Lambda515
    PgClassExpression516{{"PgClassExpression[516∈23]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle511 --> PgClassExpression516
    JSONParse517[["JSONParse[517∈23]<br />ᐸ502ᐳ<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson"]]:::plan
    Access502 --> JSONParse517
    JSONParse517 --> Access518
    First521{{"First[521∈23]"}}:::plan
    PgSelectRows522[["PgSelectRows[522∈23]"]]:::plan
    PgSelectRows522 --> First521
    PgSelect519 --> PgSelectRows522
    PgSelectSingle523{{"PgSelectSingle[523∈23]<br />ᐸpeopleᐳ"}}:::plan
    First521 --> PgSelectSingle523
    PgSelectSingle523 --> PgClassExpression525
    Lambda527{{"Lambda[527∈23]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List526 --> Lambda527
    PgClassExpression528{{"PgClassExpression[528∈23]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle523 --> PgClassExpression528
    __Item534[/"__Item[534∈24]<br />ᐸ609ᐳ"\]:::itemplan
    Access609 ==> __Item534
    PgUnionAllSingle535["PgUnionAllSingle[535∈24]"]:::plan
    __Item534 --> PgUnionAllSingle535
    Access536{{"Access[536∈24]<br />ᐸ535.1ᐳ"}}:::plan
    PgUnionAllSingle535 --> Access536
    PgSelect539[["PgSelect[539∈25]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access538{{"Access[538∈25]<br />ᐸ537.0ᐳ"}}:::plan
    Object11 & Access538 --> PgSelect539
    List548{{"List[548∈25]<br />ᐸ77,547ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression547{{"PgClassExpression[547∈25]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression547 --> List548
    PgSelect553[["PgSelect[553∈25]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access552{{"Access[552∈25]<br />ᐸ551.0ᐳ"}}:::plan
    Object11 & Access552 --> PgSelect553
    List560{{"List[560∈25]<br />ᐸ89,559ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression559{{"PgClassExpression[559∈25]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression559 --> List560
    JSONParse537[["JSONParse[537∈25]<br />ᐸ536ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access536 --> JSONParse537
    JSONParse537 --> Access538
    First543{{"First[543∈25]"}}:::plan
    PgSelectRows544[["PgSelectRows[544∈25]"]]:::plan
    PgSelectRows544 --> First543
    PgSelect539 --> PgSelectRows544
    PgSelectSingle545{{"PgSelectSingle[545∈25]<br />ᐸorganizationsᐳ"}}:::plan
    First543 --> PgSelectSingle545
    PgSelectSingle545 --> PgClassExpression547
    Lambda549{{"Lambda[549∈25]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List548 --> Lambda549
    PgClassExpression550{{"PgClassExpression[550∈25]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle545 --> PgClassExpression550
    JSONParse551[["JSONParse[551∈25]<br />ᐸ536ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access536 --> JSONParse551
    JSONParse551 --> Access552
    First555{{"First[555∈25]"}}:::plan
    PgSelectRows556[["PgSelectRows[556∈25]"]]:::plan
    PgSelectRows556 --> First555
    PgSelect553 --> PgSelectRows556
    PgSelectSingle557{{"PgSelectSingle[557∈25]<br />ᐸpeopleᐳ"}}:::plan
    First555 --> PgSelectSingle557
    PgSelectSingle557 --> PgClassExpression559
    Lambda561{{"Lambda[561∈25]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List560 --> Lambda561
    PgClassExpression562{{"PgClassExpression[562∈25]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle557 --> PgClassExpression562
    __Item566[/"__Item[566∈26]<br />ᐸ610ᐳ"\]:::itemplan
    Access610 ==> __Item566
    PgUnionAllSingle567["PgUnionAllSingle[567∈26]"]:::plan
    __Item566 --> PgUnionAllSingle567
    Access568{{"Access[568∈26]<br />ᐸ567.1ᐳ"}}:::plan
    PgUnionAllSingle567 --> Access568
    PgSelect571[["PgSelect[571∈27]<br />ᐸorganizationsᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access570{{"Access[570∈27]<br />ᐸ569.0ᐳ"}}:::plan
    Object11 & Access570 --> PgSelect571
    List580{{"List[580∈27]<br />ᐸ77,579ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"}}:::plan
    PgClassExpression579{{"PgClassExpression[579∈27]<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    Constant77 & PgClassExpression579 --> List580
    PgSelect585[["PgSelect[585∈27]<br />ᐸpeopleᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access584{{"Access[584∈27]<br />ᐸ583.0ᐳ"}}:::plan
    Object11 & Access584 --> PgSelect585
    List592{{"List[592∈27]<br />ᐸ89,591ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"}}:::plan
    PgClassExpression591{{"PgClassExpression[591∈27]<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    Constant89 & PgClassExpression591 --> List592
    JSONParse569[["JSONParse[569∈27]<br />ᐸ568ᐳ<br />ᐳThirdPartyVulnerabilityᐳOrganization"]]:::plan
    Access568 --> JSONParse569
    JSONParse569 --> Access570
    First575{{"First[575∈27]"}}:::plan
    PgSelectRows576[["PgSelectRows[576∈27]"]]:::plan
    PgSelectRows576 --> First575
    PgSelect571 --> PgSelectRows576
    PgSelectSingle577{{"PgSelectSingle[577∈27]<br />ᐸorganizationsᐳ"}}:::plan
    First575 --> PgSelectSingle577
    PgSelectSingle577 --> PgClassExpression579
    Lambda581{{"Lambda[581∈27]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List580 --> Lambda581
    PgClassExpression582{{"PgClassExpression[582∈27]<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle577 --> PgClassExpression582
    JSONParse583[["JSONParse[583∈27]<br />ᐸ568ᐳ<br />ᐳThirdPartyVulnerabilityᐳPerson"]]:::plan
    Access568 --> JSONParse583
    JSONParse583 --> Access584
    First587{{"First[587∈27]"}}:::plan
    PgSelectRows588[["PgSelectRows[588∈27]"]]:::plan
    PgSelectRows588 --> First587
    PgSelect585 --> PgSelectRows588
    PgSelectSingle589{{"PgSelectSingle[589∈27]<br />ᐸpeopleᐳ"}}:::plan
    First587 --> PgSelectSingle589
    PgSelectSingle589 --> PgClassExpression591
    Lambda593{{"Lambda[593∈27]<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List592 --> Lambda593
    PgClassExpression594{{"PgClassExpression[594∈27]<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle589 --> PgClassExpression594

    %% define steps

    subgraph "Buckets for queries/polymorphic/vulns.union_owners"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 7, 9, 10, 30, 55, 77, 89, 101, 316, 612, 11, 12, 13, 14, 38, 39<br />2: Lambda[15]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant7,Access9,Access10,Object11,Connection12,Lambda13,ApplyInput14,Lambda15,Constant30,Lambda38,ApplyInput39,Constant55,Constant77,Constant89,Constant101,Constant316,Constant612 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 13, 14, 15, 12, 612, 7, 30, 38, 39, 316, 55, 101, 77, 89<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgUnionAll16,Access611 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 11, 30, 7, 38, 39, 15, 316, 55, 101, 77, 89<br /><br />ROOT __Item{2}ᐸ611ᐳ[18]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item18,PgUnionAllSingle19,Access20 bucket2
    Bucket3("Bucket 3 (polymorphic)<br />FirstPartyVulnerability,ThirdPartyVulnerability<br />Deps: 20, 11, 30, 7, 38, 39, 15, 316, 19, 55, 101, 77, 89<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability<br /><br />1: JSONParse[21], JSONParse[309]<br />ᐳ: 37, 245, 323, 531, 22, 310<br />2: PgSelect[23], PgSelect[311]<br />3: PgSelectRows[28], PgSelectRows[314]<br />ᐳ: 27, 29, 31, 32, 33, 34, 313, 315, 317, 318, 319, 320<br />4: 41, 140, 246, 277, 327, 426, 532, 563<br />ᐳ: 597, 600, 601, 602, 605, 608, 609, 610"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,JSONParse21,Access22,PgSelect23,First27,PgSelectRows28,PgSelectSingle29,PgClassExpression31,List32,Lambda33,PgClassExpression34,Connection37,PgUnionAll41,PgUnionAll140,Connection245,PgUnionAll246,PgUnionAll277,JSONParse309,Access310,PgSelect311,First313,PgSelectRows314,PgSelectSingle315,PgClassExpression317,List318,Lambda319,PgClassExpression320,Connection323,PgUnionAll327,PgUnionAll426,Connection531,PgUnionAll532,PgUnionAll563,Access597,Access600,Access601,Access602,Access605,Access608,Access609,Access610 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 11, 55, 101, 77, 89<br /><br />ROOT __Item{4}ᐸ597ᐳ[43]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item43,PgUnionAllSingle44,Access45 bucket4
    Bucket5("Bucket 5 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 45, 11, 55, 101, 44, 77, 89<br />ᐳFirstPartyVulnerabilityᐳAwsApplication<br />ᐳFirstPartyVulnerabilityᐳGcpApplication<br /><br />1: JSONParse[46], JSONParse[94]<br />ᐳ: Access[47], Access[95]<br />2: PgSelect[48], PgSelect[96]<br />3: PgSelectRows[53], PgSelectRows[99]<br />ᐳ: 52, 54, 56, 57, 58, 59, 60, 61, 98, 100, 102, 103, 104, 105, 106, 107<br />4: PgUnionAll[62], PgUnionAll[108]<br />ᐳ: 595, 596, 64, 110<br />5: 66, 112<br />ᐳ: Access[67], Access[113]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,JSONParse46,Access47,PgSelect48,First52,PgSelectRows53,PgSelectSingle54,PgClassExpression56,List57,Lambda58,PgClassExpression59,PgClassExpression60,PgClassExpression61,PgUnionAll62,First64,PgUnionAllSingle66,Access67,JSONParse94,Access95,PgSelect96,First98,PgSelectRows99,PgSelectSingle100,PgClassExpression102,List103,Lambda104,PgClassExpression105,PgClassExpression106,PgClassExpression107,PgUnionAll108,First110,PgUnionAllSingle112,Access113,Access595,Access596 bucket5
    Bucket6("Bucket 6 (polymorphic)<br />Organization,Person<br />Deps: 67, 11, 77, 89, 66<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson<br /><br />1: JSONParse[68], JSONParse[82]<br />ᐳ: Access[69], Access[83]<br />2: PgSelect[70], PgSelect[84]<br />3: PgSelectRows[75], PgSelectRows[87]<br />ᐳ: 74, 76, 78, 79, 80, 81, 86, 88, 90, 91, 92, 93"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,JSONParse68,Access69,PgSelect70,First74,PgSelectRows75,PgSelectSingle76,PgClassExpression78,List79,Lambda80,PgClassExpression81,JSONParse82,Access83,PgSelect84,First86,PgSelectRows87,PgSelectSingle88,PgClassExpression90,List91,Lambda92,PgClassExpression93 bucket6
    Bucket7("Bucket 7 (polymorphic)<br />Organization,Person<br />Deps: 113, 11, 77, 89, 112<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson<br /><br />1: JSONParse[114], JSONParse[128]<br />ᐳ: Access[115], Access[129]<br />2: PgSelect[116], PgSelect[130]<br />3: PgSelectRows[121], PgSelectRows[133]<br />ᐳ: 120, 122, 124, 125, 126, 127, 132, 134, 136, 137, 138, 139"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,JSONParse114,Access115,PgSelect116,First120,PgSelectRows121,PgSelectSingle122,PgClassExpression124,List125,Lambda126,PgClassExpression127,JSONParse128,Access129,PgSelect130,First132,PgSelectRows133,PgSelectSingle134,PgClassExpression136,List137,Lambda138,PgClassExpression139 bucket7
    Bucket8("Bucket 8 (listItem)<br />Deps: 11, 55, 101, 77, 89<br /><br />ROOT __Item{8}ᐸ600ᐳ[146]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item146,PgUnionAllSingle147,Access148 bucket8
    Bucket9("Bucket 9 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 148, 11, 55, 101, 147, 77, 89<br />ᐳFirstPartyVulnerabilityᐳAwsApplication<br />ᐳFirstPartyVulnerabilityᐳGcpApplication<br /><br />1: JSONParse[149], JSONParse[197]<br />ᐳ: Access[150], Access[198]<br />2: PgSelect[151], PgSelect[199]<br />3: PgSelectRows[156], PgSelectRows[202]<br />ᐳ: 155, 157, 159, 160, 161, 162, 163, 164, 201, 203, 205, 206, 207, 208, 209, 210<br />4: PgUnionAll[165], PgUnionAll[211]<br />ᐳ: 598, 599, 167, 213<br />5: 169, 215<br />ᐳ: Access[170], Access[216]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,JSONParse149,Access150,PgSelect151,First155,PgSelectRows156,PgSelectSingle157,PgClassExpression159,List160,Lambda161,PgClassExpression162,PgClassExpression163,PgClassExpression164,PgUnionAll165,First167,PgUnionAllSingle169,Access170,JSONParse197,Access198,PgSelect199,First201,PgSelectRows202,PgSelectSingle203,PgClassExpression205,List206,Lambda207,PgClassExpression208,PgClassExpression209,PgClassExpression210,PgUnionAll211,First213,PgUnionAllSingle215,Access216,Access598,Access599 bucket9
    Bucket10("Bucket 10 (polymorphic)<br />Organization,Person<br />Deps: 170, 11, 77, 89, 169<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳAwsApplicationᐳPerson<br /><br />1: JSONParse[171], JSONParse[185]<br />ᐳ: Access[172], Access[186]<br />2: PgSelect[173], PgSelect[187]<br />3: PgSelectRows[178], PgSelectRows[190]<br />ᐳ: 177, 179, 181, 182, 183, 184, 189, 191, 193, 194, 195, 196"):::bucket
    classDef bucket10 stroke:#ffff00
    class Bucket10,JSONParse171,Access172,PgSelect173,First177,PgSelectRows178,PgSelectSingle179,PgClassExpression181,List182,Lambda183,PgClassExpression184,JSONParse185,Access186,PgSelect187,First189,PgSelectRows190,PgSelectSingle191,PgClassExpression193,List194,Lambda195,PgClassExpression196 bucket10
    Bucket11("Bucket 11 (polymorphic)<br />Organization,Person<br />Deps: 216, 11, 77, 89, 215<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳGcpApplicationᐳPerson<br /><br />1: JSONParse[217], JSONParse[231]<br />ᐳ: Access[218], Access[232]<br />2: PgSelect[219], PgSelect[233]<br />3: PgSelectRows[224], PgSelectRows[236]<br />ᐳ: 223, 225, 227, 228, 229, 230, 235, 237, 239, 240, 241, 242"):::bucket
    classDef bucket11 stroke:#00ffff
    class Bucket11,JSONParse217,Access218,PgSelect219,First223,PgSelectRows224,PgSelectSingle225,PgClassExpression227,List228,Lambda229,PgClassExpression230,JSONParse231,Access232,PgSelect233,First235,PgSelectRows236,PgSelectSingle237,PgClassExpression239,List240,Lambda241,PgClassExpression242 bucket11
    Bucket12("Bucket 12 (listItem)<br />Deps: 11, 77, 89<br /><br />ROOT __Item{12}ᐸ601ᐳ[248]"):::bucket
    classDef bucket12 stroke:#4169e1
    class Bucket12,__Item248,PgUnionAllSingle249,Access250 bucket12
    Bucket13("Bucket 13 (polymorphic)<br />Organization,Person<br />Deps: 250, 11, 77, 89, 249<br />ᐳFirstPartyVulnerabilityᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[251], JSONParse[265]<br />ᐳ: Access[252], Access[266]<br />2: PgSelect[253], PgSelect[267]<br />3: PgSelectRows[258], PgSelectRows[270]<br />ᐳ: 257, 259, 261, 262, 263, 264, 269, 271, 273, 274, 275, 276"):::bucket
    classDef bucket13 stroke:#3cb371
    class Bucket13,JSONParse251,Access252,PgSelect253,First257,PgSelectRows258,PgSelectSingle259,PgClassExpression261,List262,Lambda263,PgClassExpression264,JSONParse265,Access266,PgSelect267,First269,PgSelectRows270,PgSelectSingle271,PgClassExpression273,List274,Lambda275,PgClassExpression276 bucket13
    Bucket14("Bucket 14 (listItem)<br />Deps: 11, 77, 89<br /><br />ROOT __Item{14}ᐸ602ᐳ[280]"):::bucket
    classDef bucket14 stroke:#a52a2a
    class Bucket14,__Item280,PgUnionAllSingle281,Access282 bucket14
    Bucket15("Bucket 15 (polymorphic)<br />Organization,Person<br />Deps: 282, 11, 77, 89, 281<br />ᐳFirstPartyVulnerabilityᐳOrganization<br />ᐳFirstPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[283], JSONParse[297]<br />ᐳ: Access[284], Access[298]<br />2: PgSelect[285], PgSelect[299]<br />3: PgSelectRows[290], PgSelectRows[302]<br />ᐳ: 289, 291, 293, 294, 295, 296, 301, 303, 305, 306, 307, 308"):::bucket
    classDef bucket15 stroke:#ff00ff
    class Bucket15,JSONParse283,Access284,PgSelect285,First289,PgSelectRows290,PgSelectSingle291,PgClassExpression293,List294,Lambda295,PgClassExpression296,JSONParse297,Access298,PgSelect299,First301,PgSelectRows302,PgSelectSingle303,PgClassExpression305,List306,Lambda307,PgClassExpression308 bucket15
    Bucket16("Bucket 16 (listItem)<br />Deps: 11, 55, 101, 77, 89<br /><br />ROOT __Item{16}ᐸ605ᐳ[329]"):::bucket
    classDef bucket16 stroke:#f5deb3
    class Bucket16,__Item329,PgUnionAllSingle330,Access331 bucket16
    Bucket17("Bucket 17 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 331, 11, 55, 101, 330, 77, 89<br />ᐳThirdPartyVulnerabilityᐳAwsApplication<br />ᐳThirdPartyVulnerabilityᐳGcpApplication<br /><br />1: JSONParse[332], JSONParse[380]<br />ᐳ: Access[333], Access[381]<br />2: PgSelect[334], PgSelect[382]<br />3: PgSelectRows[339], PgSelectRows[385]<br />ᐳ: 338, 340, 342, 343, 344, 345, 346, 347, 384, 386, 388, 389, 390, 391, 392, 393<br />4: PgUnionAll[348], PgUnionAll[394]<br />ᐳ: 603, 604, 350, 396<br />5: 352, 398<br />ᐳ: Access[353], Access[399]"):::bucket
    classDef bucket17 stroke:#696969
    class Bucket17,JSONParse332,Access333,PgSelect334,First338,PgSelectRows339,PgSelectSingle340,PgClassExpression342,List343,Lambda344,PgClassExpression345,PgClassExpression346,PgClassExpression347,PgUnionAll348,First350,PgUnionAllSingle352,Access353,JSONParse380,Access381,PgSelect382,First384,PgSelectRows385,PgSelectSingle386,PgClassExpression388,List389,Lambda390,PgClassExpression391,PgClassExpression392,PgClassExpression393,PgUnionAll394,First396,PgUnionAllSingle398,Access399,Access603,Access604 bucket17
    Bucket18("Bucket 18 (polymorphic)<br />Organization,Person<br />Deps: 353, 11, 77, 89, 352<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson<br /><br />1: JSONParse[354], JSONParse[368]<br />ᐳ: Access[355], Access[369]<br />2: PgSelect[356], PgSelect[370]<br />3: PgSelectRows[361], PgSelectRows[373]<br />ᐳ: 360, 362, 364, 365, 366, 367, 372, 374, 376, 377, 378, 379"):::bucket
    classDef bucket18 stroke:#00bfff
    class Bucket18,JSONParse354,Access355,PgSelect356,First360,PgSelectRows361,PgSelectSingle362,PgClassExpression364,List365,Lambda366,PgClassExpression367,JSONParse368,Access369,PgSelect370,First372,PgSelectRows373,PgSelectSingle374,PgClassExpression376,List377,Lambda378,PgClassExpression379 bucket18
    Bucket19("Bucket 19 (polymorphic)<br />Organization,Person<br />Deps: 399, 11, 77, 89, 398<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson<br /><br />1: JSONParse[400], JSONParse[414]<br />ᐳ: Access[401], Access[415]<br />2: PgSelect[402], PgSelect[416]<br />3: PgSelectRows[407], PgSelectRows[419]<br />ᐳ: 406, 408, 410, 411, 412, 413, 418, 420, 422, 423, 424, 425"):::bucket
    classDef bucket19 stroke:#7f007f
    class Bucket19,JSONParse400,Access401,PgSelect402,First406,PgSelectRows407,PgSelectSingle408,PgClassExpression410,List411,Lambda412,PgClassExpression413,JSONParse414,Access415,PgSelect416,First418,PgSelectRows419,PgSelectSingle420,PgClassExpression422,List423,Lambda424,PgClassExpression425 bucket19
    Bucket20("Bucket 20 (listItem)<br />Deps: 11, 55, 101, 77, 89<br /><br />ROOT __Item{20}ᐸ608ᐳ[432]"):::bucket
    classDef bucket20 stroke:#ffa500
    class Bucket20,__Item432,PgUnionAllSingle433,Access434 bucket20
    Bucket21("Bucket 21 (polymorphic)<br />AwsApplication,GcpApplication<br />Deps: 434, 11, 55, 101, 433, 77, 89<br />ᐳThirdPartyVulnerabilityᐳAwsApplication<br />ᐳThirdPartyVulnerabilityᐳGcpApplication<br /><br />1: JSONParse[435], JSONParse[483]<br />ᐳ: Access[436], Access[484]<br />2: PgSelect[437], PgSelect[485]<br />3: PgSelectRows[442], PgSelectRows[488]<br />ᐳ: 441, 443, 445, 446, 447, 448, 449, 450, 487, 489, 491, 492, 493, 494, 495, 496<br />4: PgUnionAll[451], PgUnionAll[497]<br />ᐳ: 606, 607, 453, 499<br />5: 455, 501<br />ᐳ: Access[456], Access[502]"):::bucket
    classDef bucket21 stroke:#0000ff
    class Bucket21,JSONParse435,Access436,PgSelect437,First441,PgSelectRows442,PgSelectSingle443,PgClassExpression445,List446,Lambda447,PgClassExpression448,PgClassExpression449,PgClassExpression450,PgUnionAll451,First453,PgUnionAllSingle455,Access456,JSONParse483,Access484,PgSelect485,First487,PgSelectRows488,PgSelectSingle489,PgClassExpression491,List492,Lambda493,PgClassExpression494,PgClassExpression495,PgClassExpression496,PgUnionAll497,First499,PgUnionAllSingle501,Access502,Access606,Access607 bucket21
    Bucket22("Bucket 22 (polymorphic)<br />Organization,Person<br />Deps: 456, 11, 77, 89, 455<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳAwsApplicationᐳPerson<br /><br />1: JSONParse[457], JSONParse[471]<br />ᐳ: Access[458], Access[472]<br />2: PgSelect[459], PgSelect[473]<br />3: PgSelectRows[464], PgSelectRows[476]<br />ᐳ: 463, 465, 467, 468, 469, 470, 475, 477, 479, 480, 481, 482"):::bucket
    classDef bucket22 stroke:#7fff00
    class Bucket22,JSONParse457,Access458,PgSelect459,First463,PgSelectRows464,PgSelectSingle465,PgClassExpression467,List468,Lambda469,PgClassExpression470,JSONParse471,Access472,PgSelect473,First475,PgSelectRows476,PgSelectSingle477,PgClassExpression479,List480,Lambda481,PgClassExpression482 bucket22
    Bucket23("Bucket 23 (polymorphic)<br />Organization,Person<br />Deps: 502, 11, 77, 89, 501<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳGcpApplicationᐳPerson<br /><br />1: JSONParse[503], JSONParse[517]<br />ᐳ: Access[504], Access[518]<br />2: PgSelect[505], PgSelect[519]<br />3: PgSelectRows[510], PgSelectRows[522]<br />ᐳ: 509, 511, 513, 514, 515, 516, 521, 523, 525, 526, 527, 528"):::bucket
    classDef bucket23 stroke:#ff1493
    class Bucket23,JSONParse503,Access504,PgSelect505,First509,PgSelectRows510,PgSelectSingle511,PgClassExpression513,List514,Lambda515,PgClassExpression516,JSONParse517,Access518,PgSelect519,First521,PgSelectRows522,PgSelectSingle523,PgClassExpression525,List526,Lambda527,PgClassExpression528 bucket23
    Bucket24("Bucket 24 (listItem)<br />Deps: 11, 77, 89<br /><br />ROOT __Item{24}ᐸ609ᐳ[534]"):::bucket
    classDef bucket24 stroke:#808000
    class Bucket24,__Item534,PgUnionAllSingle535,Access536 bucket24
    Bucket25("Bucket 25 (polymorphic)<br />Organization,Person<br />Deps: 536, 11, 77, 89, 535<br />ᐳThirdPartyVulnerabilityᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[537], JSONParse[551]<br />ᐳ: Access[538], Access[552]<br />2: PgSelect[539], PgSelect[553]<br />3: PgSelectRows[544], PgSelectRows[556]<br />ᐳ: 543, 545, 547, 548, 549, 550, 555, 557, 559, 560, 561, 562"):::bucket
    classDef bucket25 stroke:#dda0dd
    class Bucket25,JSONParse537,Access538,PgSelect539,First543,PgSelectRows544,PgSelectSingle545,PgClassExpression547,List548,Lambda549,PgClassExpression550,JSONParse551,Access552,PgSelect553,First555,PgSelectRows556,PgSelectSingle557,PgClassExpression559,List560,Lambda561,PgClassExpression562 bucket25
    Bucket26("Bucket 26 (listItem)<br />Deps: 11, 77, 89<br /><br />ROOT __Item{26}ᐸ610ᐳ[566]"):::bucket
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item566,PgUnionAllSingle567,Access568 bucket26
    Bucket27("Bucket 27 (polymorphic)<br />Organization,Person<br />Deps: 568, 11, 77, 89, 567<br />ᐳThirdPartyVulnerabilityᐳOrganization<br />ᐳThirdPartyVulnerabilityᐳPerson<br /><br />1: JSONParse[569], JSONParse[583]<br />ᐳ: Access[570], Access[584]<br />2: PgSelect[571], PgSelect[585]<br />3: PgSelectRows[576], PgSelectRows[588]<br />ᐳ: 575, 577, 579, 580, 581, 582, 587, 589, 591, 592, 593, 594"):::bucket
    classDef bucket27 stroke:#ffff00
    class Bucket27,JSONParse569,Access570,PgSelect571,First575,PgSelectRows576,PgSelectSingle577,PgClassExpression579,List580,Lambda581,PgClassExpression582,JSONParse583,Access584,PgSelect585,First587,PgSelectRows588,PgSelectSingle589,PgClassExpression591,List592,Lambda593,PgClassExpression594 bucket27
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket8 & Bucket12 & Bucket14 & Bucket16 & Bucket20 & Bucket24 & Bucket26
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6 & Bucket7
    Bucket8 --> Bucket9
    Bucket9 --> Bucket10 & Bucket11
    Bucket12 --> Bucket13
    Bucket14 --> Bucket15
    Bucket16 --> Bucket17
    Bucket17 --> Bucket18 & Bucket19
    Bucket20 --> Bucket21
    Bucket21 --> Bucket22 & Bucket23
    Bucket24 --> Bucket25
    Bucket26 --> Bucket27
    end
