%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/polymorphic/vulns.union_owners"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 9, 10, 20, 40, 44, 100, 105, 128, 133, 162, 166, 170, 174, 202, 207, 230, 235, 258, 263, 390, 11<br />2: PgUnionAll[8]<br />3: Connection[12]<br />4: ConnectionItems[13]"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 20, 13, 11, 40, 44, 100, 105, 128, 133, 162, 258, 166, 263, 170, 174, 202, 207, 230, 235<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 20, 11, 40, 44, 100, 105, 128, 133, 162, 258, 166, 263, 170, 174, 202, 207, 230, 235<br /><br />ROOT __Item{3}ᐸ13ᐳ[16]"):::bucket
    Bucket4("Bucket 4 (polymorphic)<br />__typename: Access[23]<br />Deps: 23, 11, 24, 40, 44, 100, 105, 128, 133, 162, 258, 166, 263, 170, 174, 202, 207, 230, 235"):::bucket
    Bucket5("Bucket 5 (polymorphicPartition)<br />|FirstPartyVulnerability<br />Deps: 11, 24, 40, 100, 128, 162, 258, 166, 263, 170, 174, 202, 230<br />ᐳFirstPartyVulnerability<br /><br />1: PgSelect[25]<br />ᐳ: Access[29]<br />2: First[30]<br />ᐳ: 31, 41, 42, 43, 48<br />3: 50, 60, 64, 70<br />ᐳ: Access[382], Access[383]<br />4: Connection[54], Connection[66]<br />5: 86, 92"):::bucket
    Bucket6("Bucket 6 (polymorphicPartition)<br />|ThirdPartyVulnerability<br />Deps: 11, 24, 44, 105, 133, 162, 258, 166, 263, 170, 174, 207, 235<br />ᐳThirdPartyVulnerability<br /><br />1: PgSelect[33]<br />ᐳ: Access[37]<br />2: First[38]<br />ᐳ: 39, 45, 46, 47, 49<br />3: 55, 62, 67, 72<br />ᐳ: Access[384], Access[385]<br />4: Connection[59], Connection[69]<br />5: 89, 95"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 100, 11, 162, 258, 166, 263, 170, 174<br /><br />ROOT __Item{7}ᐸ382ᐳ[78]"):::bucket
    Bucket8("Bucket 8 (listItem)<br />Deps: 105, 11, 162, 258, 166, 263, 170, 174<br /><br />ROOT __Item{8}ᐸ384ᐳ[80]"):::bucket
    Bucket9("Bucket 9 (listItem)<br />Deps: 128, 11, 170, 174<br /><br />ROOT __Item{9}ᐸ383ᐳ[82]"):::bucket
    Bucket10("Bucket 10 (listItem)<br />Deps: 133, 11, 170, 174<br /><br />ROOT __Item{10}ᐸ385ᐳ[84]"):::bucket
    Bucket15("Bucket 15 (combined)<br />Deps: 11, 162, 258, 166, 263, 170, 174"):::bucket
    Bucket16("Bucket 16 (polymorphic)<br />__typename: Access[109]<br />Deps: 109, 11, 110, 162, 258, 166, 263, 170, 174"):::bucket
    Bucket17("Bucket 17 (combined)<br />Deps: 11, 170, 174"):::bucket
    Bucket18("Bucket 18 (polymorphic)<br />__typename: Access[137]<br />Deps: 137, 136, 11, 170, 174"):::bucket
    Bucket19("Bucket 19 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 110, 162, 258, 170, 174<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[111]<br />ᐳ: Access[115]<br />2: First[116]<br />ᐳ: 117, 163, 164, 165, 178, 182, 183<br />3: PgUnionAll[184]<br />ᐳ: Access[386]<br />4: First[188]<br />ᐳ: 256, 257, 259, 260"):::bucket
    Bucket20("Bucket 20 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 110, 166, 263, 170, 174<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[119]<br />ᐳ: Access[123]<br />2: First[124]<br />ᐳ: 125, 167, 168, 169, 179, 191, 192<br />3: PgUnionAll[193]<br />ᐳ: Access[387]<br />4: First[197]<br />ᐳ: 261, 262, 264, 265"):::bucket
    Bucket21("Bucket 21 (polymorphicPartition)<br />|Organization<br />Deps: 136, 11, 170<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[138]<br />2: PgSelect[139]<br />ᐳ: Access[143]<br />3: First[144]<br />ᐳ: 145, 171, 172, 173, 180"):::bucket
    Bucket22("Bucket 22 (polymorphicPartition)<br />|Person<br />Deps: 136, 11, 174<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[146]<br />2: PgSelect[147]<br />ᐳ: Access[151]<br />3: First[152]<br />ᐳ: 153, 175, 176, 177, 181"):::bucket
    Bucket23("Bucket 23 (listItem)<br />Deps: 202, 11, 162, 258, 166, 263, 170, 174<br /><br />ROOT __Item{23}ᐸ86ᐳ[154]"):::bucket
    Bucket24("Bucket 24 (listItem)<br />Deps: 207, 11, 162, 258, 166, 263, 170, 174<br /><br />ROOT __Item{24}ᐸ89ᐳ[156]"):::bucket
    Bucket25("Bucket 25 (listItem)<br />Deps: 230, 11, 170, 174<br /><br />ROOT __Item{25}ᐸ92ᐳ[158]"):::bucket
    Bucket26("Bucket 26 (listItem)<br />Deps: 235, 11, 170, 174<br /><br />ROOT __Item{26}ᐸ95ᐳ[160]"):::bucket
    Bucket27("Bucket 27 (combined)<br />Deps: 11, 162, 258, 166, 263, 170, 174"):::bucket
    Bucket28("Bucket 28 (polymorphic)<br />__typename: Access[211]<br />Deps: 211, 11, 212, 162, 258, 166, 263, 170, 174"):::bucket
    Bucket29("Bucket 29 (combined)<br />Deps: 11, 170, 174"):::bucket
    Bucket30("Bucket 30 (polymorphic)<br />__typename: Access[239]<br />Deps: 239, 238, 11, 170, 174"):::bucket
    Bucket31("Bucket 31 (polymorphicPartition)<br />|AwsApplication<br />Deps: 11, 212, 162, 258, 170, 174<br />(2) ...ᐳAwsApplication<br /><br />1: PgSelect[213]<br />ᐳ: Access[217]<br />2: First[218]<br />ᐳ: 219, 294, 295, 296, 306, 310, 311<br />3: PgUnionAll[312]<br />ᐳ: Access[388]<br />4: First[316]<br />ᐳ: 336, 337, 339, 340"):::bucket
    Bucket32("Bucket 32 (polymorphicPartition)<br />|GcpApplication<br />Deps: 11, 212, 166, 263, 170, 174<br />(2) ...ᐳGcpApplication<br /><br />1: PgSelect[221]<br />ᐳ: Access[225]<br />2: First[226]<br />ᐳ: 227, 297, 298, 299, 307, 319, 320<br />3: PgUnionAll[321]<br />ᐳ: Access[389]<br />4: First[325]<br />ᐳ: 341, 342, 344, 345"):::bucket
    Bucket33("Bucket 33 (polymorphicPartition)<br />|Organization<br />Deps: 238, 11, 170<br />(2) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[240]<br />2: PgSelect[241]<br />ᐳ: Access[245]<br />3: First[246]<br />ᐳ: 247, 300, 301, 302, 308"):::bucket
    Bucket34("Bucket 34 (polymorphicPartition)<br />|Person<br />Deps: 238, 11, 174<br />(2) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[248]<br />2: PgSelect[249]<br />ᐳ: Access[253]<br />3: First[254]<br />ᐳ: 255, 303, 304, 305, 309"):::bucket
    Bucket35("Bucket 35 (combined)<br />Deps: 11, 170, 174"):::bucket
    Bucket36("Bucket 36 (polymorphic)<br />__typename: Access[277]<br />Deps: 277, 276, 11, 170, 174"):::bucket
    Bucket37("Bucket 37 (polymorphicPartition)<br />|Organization<br />Deps: 276, 11, 170<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[278]<br />2: PgSelect[279]<br />ᐳ: Access[283]<br />3: First[284]<br />ᐳ: 285, 328, 329, 330, 334"):::bucket
    Bucket38("Bucket 38 (polymorphicPartition)<br />|Person<br />Deps: 276, 11, 174<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[286]<br />2: PgSelect[287]<br />ᐳ: Access[291]<br />3: First[292]<br />ᐳ: 293, 331, 332, 333, 335"):::bucket
    Bucket39("Bucket 39 (combined)<br />Deps: 11, 170, 174"):::bucket
    Bucket40("Bucket 40 (polymorphic)<br />__typename: Access[357]<br />Deps: 357, 356, 11, 170, 174"):::bucket
    Bucket41("Bucket 41 (polymorphicPartition)<br />|Organization<br />Deps: 356, 11, 170<br />(4) ...ᐳOrganization<br /><br />1: <br />ᐳ: Access[358]<br />2: PgSelect[359]<br />ᐳ: Access[363]<br />3: First[364]<br />ᐳ: 365, 374, 375, 376, 380"):::bucket
    Bucket42("Bucket 42 (polymorphicPartition)<br />|Person<br />Deps: 356, 11, 174<br />(4) ...ᐳPerson<br /><br />1: <br />ᐳ: Access[366]<br />2: PgSelect[367]<br />ᐳ: Access[371]<br />3: First[372]<br />ᐳ: 373, 377, 378, 379, 381"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket6
    Bucket5 --> Bucket7 & Bucket9 & Bucket23 & Bucket25
    Bucket6 --> Bucket8 & Bucket10 & Bucket24 & Bucket26
    Bucket7 --> Bucket15
    Bucket8 --> Bucket15
    Bucket9 --> Bucket17
    Bucket10 --> Bucket17
    Bucket15 --> Bucket16
    Bucket16 --> Bucket19 & Bucket20
    Bucket17 --> Bucket18
    Bucket18 --> Bucket21 & Bucket22
    Bucket19 --> Bucket35
    Bucket20 --> Bucket35
    Bucket23 --> Bucket27
    Bucket24 --> Bucket27
    Bucket25 --> Bucket29
    Bucket26 --> Bucket29
    Bucket27 --> Bucket28
    Bucket28 --> Bucket31 & Bucket32
    Bucket29 --> Bucket30
    Bucket30 --> Bucket33 & Bucket34
    Bucket31 --> Bucket39
    Bucket32 --> Bucket39
    Bucket35 --> Bucket36
    Bucket36 --> Bucket37 & Bucket38
    Bucket39 --> Bucket40
    Bucket40 --> Bucket41 & Bucket42

    %% plan dependencies
    PgUnionAll8[["PgUnionAll[8∈0] ➊<br />ᐸFirstPartyVulnerability,ThirdPartyVulnerabilityᐳ<br />More deps:<br />- Object[11]<br />- Constantᐸ2ᐳ[390]"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ<br />Dependents: 27"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    Connection12[["Connection[12∈0] ➊<br />ᐸ8ᐳ<br />More deps:<br />- Constantᐸ2ᐳ[390]"]]:::plan
    PgUnionAll8 --> Connection12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    ConnectionItems13[["ConnectionItems[13∈0] ➊"]]:::plan
    Connection12 --> ConnectionItems13
    List21{{"List[21∈3]<br />ᐸ18,19,20ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[20]"}}:::plan
    Access18{{"Access[18∈3]<br />ᐸ16.0ᐳ"}}:::plan
    Access19{{"Access[19∈3]<br />ᐸ16.1ᐳ"}}:::plan
    Access18 & Access19 --> List21
    __Item16[/"__Item[16∈3]<br />ᐸ13ᐳ"\]:::itemplan
    ConnectionItems13 ==> __Item16
    __Item16 --> Access18
    __Item16 --> Access19
    Lambda22{{"Lambda[22∈3]<br />ᐸtoSpecifierᐳ"}}:::plan
    List21 --> Lambda22
    Access23{{"Access[23∈3]<br />ᐸ22.__typenameᐳ"}}:::plan
    Lambda22 --> Access23
    Access24{{"Access[24∈3]<br />ᐸ22.idᐳ"}}:::plan
    Lambda22 --> Access24
    PgSelect25[["PgSelect[25∈5]<br />ᐸfirst_party_vulnerabilitiesᐳ<br />ᐳFirstPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access24 --> PgSelect25
    List42{{"List[42∈5]^<br />ᐸ40,41ᐳ<br />More deps:<br />- Constantᐸ'first_party_vulnerabilities'ᐳ[40]"}}:::plan
    PgClassExpression41{{"PgClassExpression[41∈5]^<br />ᐸ__first_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression41 --> List42
    PgUnionAll50[["PgUnionAll[50∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression41 --> PgUnionAll50
    PgUnionAll60[["PgUnionAll[60∈5]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression41 --> PgUnionAll60
    PgUnionAll64[["PgUnionAll[64∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression41 --> PgUnionAll64
    PgUnionAll70[["PgUnionAll[70∈5]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression41 --> PgUnionAll70
    Access29{{"Access[29∈5]^<br />ᐸ25.itemsᐳ"}}:::plan
    PgSelect25 --> Access29
    First30[["First[30∈5]^"]]:::plan
    Access29 --> First30
    PgSelectSingle31{{"PgSelectSingle[31∈5]^<br />ᐸfirst_party_vulnerabilitiesᐳ"}}:::plan
    First30 --> PgSelectSingle31
    PgSelectSingle31 --> PgClassExpression41
    Lambda43{{"Lambda[43∈5]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List42 --> Lambda43
    PgClassExpression48{{"PgClassExpression[48∈5]^<br />ᐸ__first_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle31 --> PgClassExpression48
    Connection54[["Connection[54∈5]^<br />ᐸ50ᐳ"]]:::plan
    PgUnionAll50 --> Connection54
    Connection66[["Connection[66∈5]^<br />ᐸ64ᐳ"]]:::plan
    PgUnionAll64 --> Connection66
    ConnectionItems86[["ConnectionItems[86∈5]^"]]:::plan
    Connection54 --> ConnectionItems86
    ConnectionItems92[["ConnectionItems[92∈5]^"]]:::plan
    Connection66 --> ConnectionItems92
    Access382{{"Access[382∈5]^<br />ᐸ60.itemsᐳ"}}:::plan
    PgUnionAll60 --> Access382
    Access383{{"Access[383∈5]^<br />ᐸ70.itemsᐳ"}}:::plan
    PgUnionAll70 --> Access383
    PgSelect33[["PgSelect[33∈6]<br />ᐸthird_party_vulnerabilitiesᐳ<br />ᐳThirdPartyVulnerability<br />More deps:<br />- Object[11]"]]:::plan
    Access24 --> PgSelect33
    List46{{"List[46∈6]^<br />ᐸ44,45ᐳ<br />More deps:<br />- Constantᐸ'third_party_vulnerabilities'ᐳ[44]"}}:::plan
    PgClassExpression45{{"PgClassExpression[45∈6]^<br />ᐸ__third_pa...ies__.”id”ᐳ"}}:::plan
    PgClassExpression45 --> List46
    PgUnionAll55[["PgUnionAll[55∈6]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression45 --> PgUnionAll55
    PgUnionAll62[["PgUnionAll[62∈6]^<br />ᐸAwsApplication,GcpApplicationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression45 --> PgUnionAll62
    PgUnionAll67[["PgUnionAll[67∈6]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression45 --> PgUnionAll67
    PgUnionAll72[["PgUnionAll[72∈6]^<br />ᐸPerson,Organization,Person,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression45 --> PgUnionAll72
    Access37{{"Access[37∈6]^<br />ᐸ33.itemsᐳ"}}:::plan
    PgSelect33 --> Access37
    First38[["First[38∈6]^"]]:::plan
    Access37 --> First38
    PgSelectSingle39{{"PgSelectSingle[39∈6]^<br />ᐸthird_party_vulnerabilitiesᐳ"}}:::plan
    First38 --> PgSelectSingle39
    PgSelectSingle39 --> PgClassExpression45
    Lambda47{{"Lambda[47∈6]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List46 --> Lambda47
    PgClassExpression49{{"PgClassExpression[49∈6]^<br />ᐸ__third_pa...s__.”name”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression49
    Connection59[["Connection[59∈6]^<br />ᐸ55ᐳ"]]:::plan
    PgUnionAll55 --> Connection59
    Connection69[["Connection[69∈6]^<br />ᐸ67ᐳ"]]:::plan
    PgUnionAll67 --> Connection69
    ConnectionItems89[["ConnectionItems[89∈6]^"]]:::plan
    Connection59 --> ConnectionItems89
    ConnectionItems95[["ConnectionItems[95∈6]^"]]:::plan
    Connection69 --> ConnectionItems95
    Access384{{"Access[384∈6]^<br />ᐸ62.itemsᐳ"}}:::plan
    PgUnionAll62 --> Access384
    Access385{{"Access[385∈6]^<br />ᐸ72.itemsᐳ"}}:::plan
    PgUnionAll72 --> Access385
    List101{{"List[101∈7]^<br />ᐸ98,99,100ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[100]"}}:::plan
    Access98{{"Access[98∈7]^<br />ᐸ78.0ᐳ"}}:::plan
    Access99{{"Access[99∈7]^<br />ᐸ78.1ᐳ"}}:::plan
    Access98 & Access99 --> List101
    __Item78[/"__Item[78∈7]<br />ᐸ382ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access382 ==> __Item78
    __Item78 --> Access98
    __Item78 --> Access99
    Lambda102{{"Lambda[102∈7]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List101 --> Lambda102
    List106{{"List[106∈8]^<br />ᐸ103,104,105ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[105]"}}:::plan
    Access103{{"Access[103∈8]^<br />ᐸ80.0ᐳ"}}:::plan
    Access104{{"Access[104∈8]^<br />ᐸ80.1ᐳ"}}:::plan
    Access103 & Access104 --> List106
    __Item80[/"__Item[80∈8]<br />ᐸ384ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access384 ==> __Item80
    __Item80 --> Access103
    __Item80 --> Access104
    Lambda107{{"Lambda[107∈8]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List106 --> Lambda107
    List129{{"List[129∈9]^<br />ᐸ126,127,128ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[128]"}}:::plan
    Access126{{"Access[126∈9]^<br />ᐸ82.0ᐳ"}}:::plan
    Access127{{"Access[127∈9]^<br />ᐸ82.1ᐳ"}}:::plan
    Access126 & Access127 --> List129
    __Item82[/"__Item[82∈9]<br />ᐸ383ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    Access383 ==> __Item82
    __Item82 --> Access126
    __Item82 --> Access127
    Lambda130{{"Lambda[130∈9]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List129 --> Lambda130
    List134{{"List[134∈10]^<br />ᐸ131,132,133ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[133]"}}:::plan
    Access131{{"Access[131∈10]^<br />ᐸ84.0ᐳ"}}:::plan
    Access132{{"Access[132∈10]^<br />ᐸ84.1ᐳ"}}:::plan
    Access131 & Access132 --> List134
    __Item84[/"__Item[84∈10]<br />ᐸ385ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    Access385 ==> __Item84
    __Item84 --> Access131
    __Item84 --> Access132
    Lambda135{{"Lambda[135∈10]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List134 --> Lambda135
    Access109{{"Access[109∈15]^<br />ᐸ108.__typenameᐳ"}}:::plan
    __Value108:::plan@{shape: docs, label: "__Combined[108∈15]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value108 --> Access109
    Access110{{"Access[110∈15]^<br />ᐸ108.idᐳ"}}:::plan
    __Value108 --> Access110
    Access137{{"Access[137∈17]^<br />ᐸ136.__typenameᐳ"}}:::plan
    __Value136:::plan@{shape: docs, label: "__Combined[136∈17]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value136 --> Access137
    PgUnionAll184[["PgUnionAll[184∈19]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression182{{"PgClassExpression[182∈19]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression183{{"PgClassExpression[183∈19]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression182 & PgClassExpression183 --> PgUnionAll184
    List259{{"List[259∈19]^<br />ᐸ256,257,258ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[258]"}}:::plan
    Access256{{"Access[256∈19]^<br />ᐸ188.0ᐳ"}}:::plan
    Access257{{"Access[257∈19]^<br />ᐸ188.1ᐳ"}}:::plan
    Access256 & Access257 --> List259
    PgSelect111[["PgSelect[111∈19]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access110 --> PgSelect111
    List164{{"List[164∈19]^<br />ᐸ162,163ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[162]"}}:::plan
    PgClassExpression163{{"PgClassExpression[163∈19]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression163 --> List164
    Access115{{"Access[115∈19]^<br />ᐸ111.itemsᐳ"}}:::plan
    PgSelect111 --> Access115
    First116[["First[116∈19]^"]]:::plan
    Access115 --> First116
    PgSelectSingle117{{"PgSelectSingle[117∈19]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First116 --> PgSelectSingle117
    PgSelectSingle117 --> PgClassExpression163
    Lambda165{{"Lambda[165∈19]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List164 --> Lambda165
    PgClassExpression178{{"PgClassExpression[178∈19]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle117 --> PgClassExpression178
    PgSelectSingle117 --> PgClassExpression182
    PgSelectSingle117 --> PgClassExpression183
    First188[["First[188∈19]^"]]:::plan
    Access386{{"Access[386∈19]^<br />ᐸ184.itemsᐳ"}}:::plan
    Access386 --> First188
    First188 --> Access256
    First188 --> Access257
    Lambda260{{"Lambda[260∈19]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List259 --> Lambda260
    PgUnionAll184 --> Access386
    PgUnionAll193[["PgUnionAll[193∈20]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression191{{"PgClassExpression[191∈20]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression192{{"PgClassExpression[192∈20]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression191 & PgClassExpression192 --> PgUnionAll193
    List264{{"List[264∈20]^<br />ᐸ261,262,263ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[263]"}}:::plan
    Access261{{"Access[261∈20]^<br />ᐸ197.0ᐳ"}}:::plan
    Access262{{"Access[262∈20]^<br />ᐸ197.1ᐳ"}}:::plan
    Access261 & Access262 --> List264
    PgSelect119[["PgSelect[119∈20]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access110 --> PgSelect119
    List168{{"List[168∈20]^<br />ᐸ166,167ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[166]"}}:::plan
    PgClassExpression167{{"PgClassExpression[167∈20]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression167 --> List168
    Access123{{"Access[123∈20]^<br />ᐸ119.itemsᐳ"}}:::plan
    PgSelect119 --> Access123
    First124[["First[124∈20]^"]]:::plan
    Access123 --> First124
    PgSelectSingle125{{"PgSelectSingle[125∈20]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First124 --> PgSelectSingle125
    PgSelectSingle125 --> PgClassExpression167
    Lambda169{{"Lambda[169∈20]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List168 --> Lambda169
    PgClassExpression179{{"PgClassExpression[179∈20]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle125 --> PgClassExpression179
    PgSelectSingle125 --> PgClassExpression191
    PgSelectSingle125 --> PgClassExpression192
    First197[["First[197∈20]^"]]:::plan
    Access387{{"Access[387∈20]^<br />ᐸ193.itemsᐳ"}}:::plan
    Access387 --> First197
    First197 --> Access261
    First197 --> Access262
    Lambda265{{"Lambda[265∈20]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List264 --> Lambda265
    PgUnionAll193 --> Access387
    PgSelect139[["PgSelect[139∈21]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access138{{"Access[138∈21]<br />ᐸ136.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access138 --> PgSelect139
    List172{{"List[172∈21]^<br />ᐸ170,171ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[170]"}}:::plan
    PgClassExpression171{{"PgClassExpression[171∈21]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression171 --> List172
    __Value136 --> Access138
    Access143{{"Access[143∈21]^<br />ᐸ139.itemsᐳ"}}:::plan
    PgSelect139 --> Access143
    First144[["First[144∈21]^"]]:::plan
    Access143 --> First144
    PgSelectSingle145{{"PgSelectSingle[145∈21]^<br />ᐸorganizationsᐳ"}}:::plan
    First144 --> PgSelectSingle145
    PgSelectSingle145 --> PgClassExpression171
    Lambda173{{"Lambda[173∈21]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List172 --> Lambda173
    PgClassExpression180{{"PgClassExpression[180∈21]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle145 --> PgClassExpression180
    PgSelect147[["PgSelect[147∈22]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access146{{"Access[146∈22]<br />ᐸ136.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access146 --> PgSelect147
    List176{{"List[176∈22]^<br />ᐸ174,175ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[174]"}}:::plan
    PgClassExpression175{{"PgClassExpression[175∈22]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression175 --> List176
    __Value136 --> Access146
    Access151{{"Access[151∈22]^<br />ᐸ147.itemsᐳ"}}:::plan
    PgSelect147 --> Access151
    First152[["First[152∈22]^"]]:::plan
    Access151 --> First152
    PgSelectSingle153{{"PgSelectSingle[153∈22]^<br />ᐸpeopleᐳ"}}:::plan
    First152 --> PgSelectSingle153
    PgSelectSingle153 --> PgClassExpression175
    Lambda177{{"Lambda[177∈22]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List176 --> Lambda177
    PgClassExpression181{{"PgClassExpression[181∈22]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle153 --> PgClassExpression181
    List203{{"List[203∈23]^<br />ᐸ200,201,202ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[202]"}}:::plan
    Access200{{"Access[200∈23]^<br />ᐸ154.0ᐳ"}}:::plan
    Access201{{"Access[201∈23]^<br />ᐸ154.1ᐳ"}}:::plan
    Access200 & Access201 --> List203
    __Item154[/"__Item[154∈23]<br />ᐸ86ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    ConnectionItems86 ==> __Item154
    __Item154 --> Access200
    __Item154 --> Access201
    Lambda204{{"Lambda[204∈23]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List203 --> Lambda204
    List208{{"List[208∈24]^<br />ᐸ205,206,207ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[207]"}}:::plan
    Access205{{"Access[205∈24]^<br />ᐸ156.0ᐳ"}}:::plan
    Access206{{"Access[206∈24]^<br />ᐸ156.1ᐳ"}}:::plan
    Access205 & Access206 --> List208
    __Item156[/"__Item[156∈24]<br />ᐸ89ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    ConnectionItems89 ==> __Item156
    __Item156 --> Access205
    __Item156 --> Access206
    Lambda209{{"Lambda[209∈24]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List208 --> Lambda209
    List231{{"List[231∈25]^<br />ᐸ228,229,230ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[230]"}}:::plan
    Access228{{"Access[228∈25]^<br />ᐸ158.0ᐳ"}}:::plan
    Access229{{"Access[229∈25]^<br />ᐸ158.1ᐳ"}}:::plan
    Access228 & Access229 --> List231
    __Item158[/"__Item[158∈25]<br />ᐸ92ᐳ<br />ᐳFirstPartyVulnerability"\]:::itemplan
    ConnectionItems92 ==> __Item158
    __Item158 --> Access228
    __Item158 --> Access229
    Lambda232{{"Lambda[232∈25]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List231 --> Lambda232
    List236{{"List[236∈26]^<br />ᐸ233,234,235ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[235]"}}:::plan
    Access233{{"Access[233∈26]^<br />ᐸ160.0ᐳ"}}:::plan
    Access234{{"Access[234∈26]^<br />ᐸ160.1ᐳ"}}:::plan
    Access233 & Access234 --> List236
    __Item160[/"__Item[160∈26]<br />ᐸ95ᐳ<br />ᐳThirdPartyVulnerability"\]:::itemplan
    ConnectionItems95 ==> __Item160
    __Item160 --> Access233
    __Item160 --> Access234
    Lambda237{{"Lambda[237∈26]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List236 --> Lambda237
    Access211{{"Access[211∈27]^<br />ᐸ210.__typenameᐳ"}}:::plan
    __Value210:::plan@{shape: docs, label: "__Combined[210∈27]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value210 --> Access211
    Access212{{"Access[212∈27]^<br />ᐸ210.idᐳ"}}:::plan
    __Value210 --> Access212
    Access239{{"Access[239∈29]^<br />ᐸ238.__typenameᐳ"}}:::plan
    __Value238:::plan@{shape: docs, label: "__Combined[238∈29]<br />ᐳFirstPartyVulnerability<br />ᐳThirdPartyVulnerability"}
    __Value238 --> Access239
    PgUnionAll312[["PgUnionAll[312∈31]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression310{{"PgClassExpression[310∈31]^<br />ᐸ__aws_appl...person_id”ᐳ"}}:::plan
    PgClassExpression311{{"PgClassExpression[311∈31]^<br />ᐸ__aws_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression310 & PgClassExpression311 --> PgUnionAll312
    List339{{"List[339∈31]^<br />ᐸ336,337,258ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[258]"}}:::plan
    Access336{{"Access[336∈31]^<br />ᐸ316.0ᐳ"}}:::plan
    Access337{{"Access[337∈31]^<br />ᐸ316.1ᐳ"}}:::plan
    Access336 & Access337 --> List339
    PgSelect213[["PgSelect[213∈31]<br />ᐸaws_applicationsᐳ<br />(2) ...ᐳAwsApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access212 --> PgSelect213
    List295{{"List[295∈31]^<br />ᐸ162,294ᐳ<br />More deps:<br />- Constantᐸ'aws_applications'ᐳ[162]"}}:::plan
    PgClassExpression294{{"PgClassExpression[294∈31]^<br />ᐸ__aws_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression294 --> List295
    Access217{{"Access[217∈31]^<br />ᐸ213.itemsᐳ"}}:::plan
    PgSelect213 --> Access217
    First218[["First[218∈31]^"]]:::plan
    Access217 --> First218
    PgSelectSingle219{{"PgSelectSingle[219∈31]^<br />ᐸaws_applicationsᐳ"}}:::plan
    First218 --> PgSelectSingle219
    PgSelectSingle219 --> PgClassExpression294
    Lambda296{{"Lambda[296∈31]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List295 --> Lambda296
    PgClassExpression306{{"PgClassExpression[306∈31]^<br />ᐸ__aws_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle219 --> PgClassExpression306
    PgSelectSingle219 --> PgClassExpression310
    PgSelectSingle219 --> PgClassExpression311
    First316[["First[316∈31]^"]]:::plan
    Access388{{"Access[388∈31]^<br />ᐸ312.itemsᐳ"}}:::plan
    Access388 --> First316
    First316 --> Access336
    First316 --> Access337
    Lambda340{{"Lambda[340∈31]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List339 --> Lambda340
    PgUnionAll312 --> Access388
    PgUnionAll321[["PgUnionAll[321∈32]^<br />ᐸPerson,Organizationᐳ<br />More deps:<br />- Object[11]"]]:::plan
    PgClassExpression319{{"PgClassExpression[319∈32]^<br />ᐸ__gcp_appl...person_id”ᐳ"}}:::plan
    PgClassExpression320{{"PgClassExpression[320∈32]^<br />ᐸ__gcp_appl...zation_id”ᐳ"}}:::plan
    PgClassExpression319 & PgClassExpression320 --> PgUnionAll321
    List344{{"List[344∈32]^<br />ᐸ341,342,263ᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[263]"}}:::plan
    Access341{{"Access[341∈32]^<br />ᐸ325.0ᐳ"}}:::plan
    Access342{{"Access[342∈32]^<br />ᐸ325.1ᐳ"}}:::plan
    Access341 & Access342 --> List344
    PgSelect221[["PgSelect[221∈32]<br />ᐸgcp_applicationsᐳ<br />(2) ...ᐳGcpApplication<br />More deps:<br />- Object[11]"]]:::plan
    Access212 --> PgSelect221
    List298{{"List[298∈32]^<br />ᐸ166,297ᐳ<br />More deps:<br />- Constantᐸ'gcp_applications'ᐳ[166]"}}:::plan
    PgClassExpression297{{"PgClassExpression[297∈32]^<br />ᐸ__gcp_appl...ons__.”id”ᐳ"}}:::plan
    PgClassExpression297 --> List298
    Access225{{"Access[225∈32]^<br />ᐸ221.itemsᐳ"}}:::plan
    PgSelect221 --> Access225
    First226[["First[226∈32]^"]]:::plan
    Access225 --> First226
    PgSelectSingle227{{"PgSelectSingle[227∈32]^<br />ᐸgcp_applicationsᐳ"}}:::plan
    First226 --> PgSelectSingle227
    PgSelectSingle227 --> PgClassExpression297
    Lambda299{{"Lambda[299∈32]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List298 --> Lambda299
    PgClassExpression307{{"PgClassExpression[307∈32]^<br />ᐸ__gcp_appl...s__.”name”ᐳ"}}:::plan
    PgSelectSingle227 --> PgClassExpression307
    PgSelectSingle227 --> PgClassExpression319
    PgSelectSingle227 --> PgClassExpression320
    First325[["First[325∈32]^"]]:::plan
    Access389{{"Access[389∈32]^<br />ᐸ321.itemsᐳ"}}:::plan
    Access389 --> First325
    First325 --> Access341
    First325 --> Access342
    Lambda345{{"Lambda[345∈32]^<br />ᐸtoSpecifierᐳ"}}:::plan
    List344 --> Lambda345
    PgUnionAll321 --> Access389
    PgSelect241[["PgSelect[241∈33]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access240{{"Access[240∈33]<br />ᐸ238.organization_idᐳ<br />(2) ...ᐳOrganization"}}:::plan
    Access240 --> PgSelect241
    List301{{"List[301∈33]^<br />ᐸ170,300ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[170]"}}:::plan
    PgClassExpression300{{"PgClassExpression[300∈33]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression300 --> List301
    __Value238 --> Access240
    Access245{{"Access[245∈33]^<br />ᐸ241.itemsᐳ"}}:::plan
    PgSelect241 --> Access245
    First246[["First[246∈33]^"]]:::plan
    Access245 --> First246
    PgSelectSingle247{{"PgSelectSingle[247∈33]^<br />ᐸorganizationsᐳ"}}:::plan
    First246 --> PgSelectSingle247
    PgSelectSingle247 --> PgClassExpression300
    Lambda302{{"Lambda[302∈33]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List301 --> Lambda302
    PgClassExpression308{{"PgClassExpression[308∈33]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle247 --> PgClassExpression308
    PgSelect249[["PgSelect[249∈34]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access248{{"Access[248∈34]<br />ᐸ238.person_idᐳ<br />(2) ...ᐳPerson"}}:::plan
    Access248 --> PgSelect249
    List304{{"List[304∈34]^<br />ᐸ174,303ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[174]"}}:::plan
    PgClassExpression303{{"PgClassExpression[303∈34]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression303 --> List304
    __Value238 --> Access248
    Access253{{"Access[253∈34]^<br />ᐸ249.itemsᐳ"}}:::plan
    PgSelect249 --> Access253
    First254[["First[254∈34]^"]]:::plan
    Access253 --> First254
    PgSelectSingle255{{"PgSelectSingle[255∈34]^<br />ᐸpeopleᐳ"}}:::plan
    First254 --> PgSelectSingle255
    PgSelectSingle255 --> PgClassExpression303
    Lambda305{{"Lambda[305∈34]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List304 --> Lambda305
    PgClassExpression309{{"PgClassExpression[309∈34]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle255 --> PgClassExpression309
    Access277{{"Access[277∈35]^<br />ᐸ276.__typenameᐳ"}}:::plan
    __Value276:::plan@{shape: docs, label: "__Combined[276∈35]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value276 --> Access277
    PgSelect279[["PgSelect[279∈37]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access278{{"Access[278∈37]<br />ᐸ276.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access278 --> PgSelect279
    List329{{"List[329∈37]^<br />ᐸ170,328ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[170]"}}:::plan
    PgClassExpression328{{"PgClassExpression[328∈37]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression328 --> List329
    __Value276 --> Access278
    Access283{{"Access[283∈37]^<br />ᐸ279.itemsᐳ"}}:::plan
    PgSelect279 --> Access283
    First284[["First[284∈37]^"]]:::plan
    Access283 --> First284
    PgSelectSingle285{{"PgSelectSingle[285∈37]^<br />ᐸorganizationsᐳ"}}:::plan
    First284 --> PgSelectSingle285
    PgSelectSingle285 --> PgClassExpression328
    Lambda330{{"Lambda[330∈37]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List329 --> Lambda330
    PgClassExpression334{{"PgClassExpression[334∈37]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle285 --> PgClassExpression334
    PgSelect287[["PgSelect[287∈38]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access286{{"Access[286∈38]<br />ᐸ276.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access286 --> PgSelect287
    List332{{"List[332∈38]^<br />ᐸ174,331ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[174]"}}:::plan
    PgClassExpression331{{"PgClassExpression[331∈38]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression331 --> List332
    __Value276 --> Access286
    Access291{{"Access[291∈38]^<br />ᐸ287.itemsᐳ"}}:::plan
    PgSelect287 --> Access291
    First292[["First[292∈38]^"]]:::plan
    Access291 --> First292
    PgSelectSingle293{{"PgSelectSingle[293∈38]^<br />ᐸpeopleᐳ"}}:::plan
    First292 --> PgSelectSingle293
    PgSelectSingle293 --> PgClassExpression331
    Lambda333{{"Lambda[333∈38]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List332 --> Lambda333
    PgClassExpression335{{"PgClassExpression[335∈38]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle293 --> PgClassExpression335
    Access357{{"Access[357∈39]^<br />ᐸ356.__typenameᐳ"}}:::plan
    __Value356:::plan@{shape: docs, label: "__Combined[356∈39]<br />(2) ...ᐳAwsApplication<br />(2) ...ᐳGcpApplication"}
    __Value356 --> Access357
    PgSelect359[["PgSelect[359∈41]^<br />ᐸorganizationsᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access358{{"Access[358∈41]<br />ᐸ356.organization_idᐳ<br />(4) ...ᐳOrganization"}}:::plan
    Access358 --> PgSelect359
    List375{{"List[375∈41]^<br />ᐸ170,374ᐳ<br />More deps:<br />- Constantᐸ'organizations'ᐳ[170]"}}:::plan
    PgClassExpression374{{"PgClassExpression[374∈41]^<br />ᐸ__organiza...zation_id”ᐳ"}}:::plan
    PgClassExpression374 --> List375
    __Value356 --> Access358
    Access363{{"Access[363∈41]^<br />ᐸ359.itemsᐳ"}}:::plan
    PgSelect359 --> Access363
    First364[["First[364∈41]^"]]:::plan
    Access363 --> First364
    PgSelectSingle365{{"PgSelectSingle[365∈41]^<br />ᐸorganizationsᐳ"}}:::plan
    First364 --> PgSelectSingle365
    PgSelectSingle365 --> PgClassExpression374
    Lambda376{{"Lambda[376∈41]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List375 --> Lambda376
    PgClassExpression380{{"PgClassExpression[380∈41]^<br />ᐸ__organiza...s__.”name”ᐳ"}}:::plan
    PgSelectSingle365 --> PgClassExpression380
    PgSelect367[["PgSelect[367∈42]^<br />ᐸpeopleᐳ<br />More deps:<br />- Object[11]"]]:::plan
    Access366{{"Access[366∈42]<br />ᐸ356.person_idᐳ<br />(4) ...ᐳPerson"}}:::plan
    Access366 --> PgSelect367
    List378{{"List[378∈42]^<br />ᐸ174,377ᐳ<br />More deps:<br />- Constantᐸ'people'ᐳ[174]"}}:::plan
    PgClassExpression377{{"PgClassExpression[377∈42]^<br />ᐸ__people__.”person_id”ᐳ"}}:::plan
    PgClassExpression377 --> List378
    __Value356 --> Access366
    Access371{{"Access[371∈42]^<br />ᐸ367.itemsᐳ"}}:::plan
    PgSelect367 --> Access371
    First372[["First[372∈42]^"]]:::plan
    Access371 --> First372
    PgSelectSingle373{{"PgSelectSingle[373∈42]^<br />ᐸpeopleᐳ"}}:::plan
    First372 --> PgSelectSingle373
    PgSelectSingle373 --> PgClassExpression377
    Lambda379{{"Lambda[379∈42]^<br />ᐸbase64JSONEncodeᐳ"}}:::plan
    List378 --> Lambda379
    PgClassExpression381{{"PgClassExpression[381∈42]^<br />ᐸ__people__.”username”ᐳ"}}:::plan
    PgSelectSingle373 --> PgClassExpression381

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgUnionAll8,Access9,Access10,Object11,Connection12,ConnectionItems13 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item16,Access18,Access19,List21,Lambda22,Access23,Access24 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgSelect25,Access29,First30,PgSelectSingle31,PgClassExpression41,List42,Lambda43,PgClassExpression48,PgUnionAll50,Connection54,PgUnionAll60,PgUnionAll64,Connection66,PgUnionAll70,ConnectionItems86,ConnectionItems92,Access382,Access383 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgSelect33,Access37,First38,PgSelectSingle39,PgClassExpression45,List46,Lambda47,PgClassExpression49,PgUnionAll55,Connection59,PgUnionAll62,PgUnionAll67,Connection69,PgUnionAll72,ConnectionItems89,ConnectionItems95,Access384,Access385 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,__Item78,Access98,Access99,List101,Lambda102 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,__Item80,Access103,Access104,List106,Lambda107 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,__Item82,Access126,Access127,List129,Lambda130 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,__Item84,Access131,Access132,List134,Lambda135 bucket10
    classDef bucket15 stroke:#ff00ff
    class Bucket15,__Value108,Access109,Access110 bucket15
    classDef bucket16 stroke:#f5deb3
    class Bucket16 bucket16
    classDef bucket17 stroke:#696969
    class Bucket17,__Value136,Access137 bucket17
    classDef bucket18 stroke:#00bfff
    class Bucket18 bucket18
    classDef bucket19 stroke:#7f007f
    class Bucket19,PgSelect111,Access115,First116,PgSelectSingle117,PgClassExpression163,List164,Lambda165,PgClassExpression178,PgClassExpression182,PgClassExpression183,PgUnionAll184,First188,Access256,Access257,List259,Lambda260,Access386 bucket19
    classDef bucket20 stroke:#ffa500
    class Bucket20,PgSelect119,Access123,First124,PgSelectSingle125,PgClassExpression167,List168,Lambda169,PgClassExpression179,PgClassExpression191,PgClassExpression192,PgUnionAll193,First197,Access261,Access262,List264,Lambda265,Access387 bucket20
    classDef bucket21 stroke:#0000ff
    class Bucket21,Access138,PgSelect139,Access143,First144,PgSelectSingle145,PgClassExpression171,List172,Lambda173,PgClassExpression180 bucket21
    classDef bucket22 stroke:#7fff00
    class Bucket22,Access146,PgSelect147,Access151,First152,PgSelectSingle153,PgClassExpression175,List176,Lambda177,PgClassExpression181 bucket22
    classDef bucket23 stroke:#ff1493
    class Bucket23,__Item154,Access200,Access201,List203,Lambda204 bucket23
    classDef bucket24 stroke:#808000
    class Bucket24,__Item156,Access205,Access206,List208,Lambda209 bucket24
    classDef bucket25 stroke:#dda0dd
    class Bucket25,__Item158,Access228,Access229,List231,Lambda232 bucket25
    classDef bucket26 stroke:#ff0000
    class Bucket26,__Item160,Access233,Access234,List236,Lambda237 bucket26
    classDef bucket27 stroke:#ffff00
    class Bucket27,__Value210,Access211,Access212 bucket27
    classDef bucket28 stroke:#00ffff
    class Bucket28 bucket28
    classDef bucket29 stroke:#4169e1
    class Bucket29,__Value238,Access239 bucket29
    classDef bucket30 stroke:#3cb371
    class Bucket30 bucket30
    classDef bucket31 stroke:#a52a2a
    class Bucket31,PgSelect213,Access217,First218,PgSelectSingle219,PgClassExpression294,List295,Lambda296,PgClassExpression306,PgClassExpression310,PgClassExpression311,PgUnionAll312,First316,Access336,Access337,List339,Lambda340,Access388 bucket31
    classDef bucket32 stroke:#ff00ff
    class Bucket32,PgSelect221,Access225,First226,PgSelectSingle227,PgClassExpression297,List298,Lambda299,PgClassExpression307,PgClassExpression319,PgClassExpression320,PgUnionAll321,First325,Access341,Access342,List344,Lambda345,Access389 bucket32
    classDef bucket33 stroke:#f5deb3
    class Bucket33,Access240,PgSelect241,Access245,First246,PgSelectSingle247,PgClassExpression300,List301,Lambda302,PgClassExpression308 bucket33
    classDef bucket34 stroke:#696969
    class Bucket34,Access248,PgSelect249,Access253,First254,PgSelectSingle255,PgClassExpression303,List304,Lambda305,PgClassExpression309 bucket34
    classDef bucket35 stroke:#00bfff
    class Bucket35,__Value276,Access277 bucket35
    classDef bucket36 stroke:#7f007f
    class Bucket36 bucket36
    classDef bucket37 stroke:#ffa500
    class Bucket37,Access278,PgSelect279,Access283,First284,PgSelectSingle285,PgClassExpression328,List329,Lambda330,PgClassExpression334 bucket37
    classDef bucket38 stroke:#0000ff
    class Bucket38,Access286,PgSelect287,Access291,First292,PgSelectSingle293,PgClassExpression331,List332,Lambda333,PgClassExpression335 bucket38
    classDef bucket39 stroke:#7fff00
    class Bucket39,__Value356,Access357 bucket39
    classDef bucket40 stroke:#ff1493
    class Bucket40 bucket40
    classDef bucket41 stroke:#808000
    class Bucket41,Access358,PgSelect359,Access363,First364,PgSelectSingle365,PgClassExpression374,List375,Lambda376,PgClassExpression380 bucket41
    classDef bucket42 stroke:#dda0dd
    class Bucket42,Access366,PgSelect367,Access371,First372,PgSelectSingle373,PgClassExpression377,List378,Lambda379,PgClassExpression381 bucket42

    Lambda102 -.-x __Value108
    Lambda107 -.-x __Value108
    Lambda130 -.-x __Value136
    Lambda135 -.-x __Value136
    Lambda204 -.-x __Value210
    Lambda209 -.-x __Value210
    Lambda232 -.-x __Value238
    Lambda237 -.-x __Value238
    Lambda260 -.-x __Value276
    Lambda265 -.-x __Value276
    Lambda340 -.-x __Value356
    Lambda345 -.-x __Value356
