drop schema if exists pg11 cascade;
create schema pg11;

create table pg11.always_as_identity (
  id int primary key generated always as identity,
  t text
);

create table pg11.by_default_as_identity (
  id int primary key generated by default as identity,
  t text
);

create table pg11.network (
  id serial primary key,
  inet inet,
  cidr cidr,
  macaddr macaddr,
  macaddr8 macaddr8
);

create domain c.bigint_domain as int8;
-- PG9.6 doesn't support array of domain scalars
create domain c.bigint_domain_array_domain as c.bigint_domain[];

create table pg11.types (
  id serial primary key,
  "regrole" regrole, 
  "regnamespace" regnamespace,
  "bigint_domain_array_domain" c.bigint_domain_array_domain
)
