%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object71{{"Object[71∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Lambda63{{"Lambda[63∈0] ➊<br />ᐸcalculateShouldReverseOrderᐳ"}}:::plan
    Constant68{{"Constant[68∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Constant69{{"Constant[69∈0] ➊<br />ᐸsql.identifier(”users”)ᐳ"}}:::plan
    Constant70{{"Constant[70∈0] ➊<br />ᐸRecordCodec(users)ᐳ"}}:::plan
    Lambda63 & Constant68 & Constant69 & Constant70 --> Object71
    Object87{{"Object[87∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant84{{"Constant[84∈0] ➊<br />ᐸ[ { fragment: { n: [Array], f: 0, c: 266, [Symbol(pg-sql2-tyᐳ"}}:::plan
    Constant85{{"Constant[85∈0] ➊<br />ᐸsql.identifier(”messages”)ᐳ"}}:::plan
    Constant86{{"Constant[86∈0] ➊<br />ᐸRecordCodec(messages)ᐳ"}}:::plan
    Lambda63 & Constant84 & Constant85 & Constant86 --> Object87
    Object102{{"Object[102∈0] ➊<br />ᐸ{reverse,orders,alias,codec}ᐳ"}}:::plan
    Constant99{{"Constant[99∈0] ➊<br />ᐸ[]ᐳ"}}:::plan
    Lambda63 & Constant99 & Constant85 & Constant86 --> Object102
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Constant109{{"Constant[109∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant109 --> Lambda63
    Lambda66{{"Lambda[66∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant110{{"Constant[110∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant110 --> Lambda66
    Access67{{"Access[67∈0] ➊<br />ᐸ66.0ᐳ"}}:::plan
    Lambda66 --> Access67
    Lambda72{{"Lambda[72∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object71 --> Lambda72
    Lambda77{{"Lambda[77∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant112{{"Constant[112∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”users”ᐳ"}}:::plan
    Constant112 --> Lambda77
    Lambda82{{"Lambda[82∈0] ➊<br />ᐸcalculateLimitAndOffsetSQLᐳ"}}:::plan
    Constant111{{"Constant[111∈0] ➊<br />ᐸ§{ first: null, last: null, cursorLower: null, cursorUpper: ᐳ"}}:::plan
    Constant111 --> Lambda82
    Access83{{"Access[83∈0] ➊<br />ᐸ82.0ᐳ"}}:::plan
    Lambda82 --> Access83
    Lambda88{{"Lambda[88∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object87 --> Lambda88
    Lambda93{{"Lambda[93∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant113{{"Constant[113∈0] ➊<br />ᐸ§{ reverse: false, orders: [ { fragment: [Object], codec: Coᐳ"}}:::plan
    Constant113 --> Lambda93
    Lambda103{{"Lambda[103∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Object102 --> Lambda103
    Lambda108{{"Lambda[108∈0] ➊<br />ᐸcalculateOrderBySQLᐳ"}}:::plan
    Constant114{{"Constant[114∈0] ➊<br />ᐸ§{ reverse: false, orders: [], alias: sql.identifier(”messagᐳ"}}:::plan
    Constant114 --> Lambda108
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Connection12{{"Connection[12∈0] ➊<br />ᐸ8ᐳ"}}:::plan
    Constant19{{"Constant[19∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    PgSelect13[["PgSelect[13∈1] ➊<br />ᐸmessages+1ᐳ"]]:::plan
    Object11 & Connection12 & Lambda63 & Access83 & Lambda88 & Lambda93 --> PgSelect13
    PgSelect57[["PgSelect[57∈1] ➊<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object11 & Connection12 & Lambda63 & Access67 & Lambda103 & Lambda108 --> PgSelect57
    Object40{{"Object[40∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access35{{"Access[35∈1] ➊<br />ᐸ13.hasMoreᐳ"}}:::plan
    Constant6 & Constant6 & Constant6 & Access35 --> Object40
    Object36{{"Object[36∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant6 & Constant6 & Access35 --> Object36
    List49{{"List[49∈1] ➊<br />ᐸ19,47ᐳ"}}:::plan
    List47{{"List[47∈1] ➊<br />ᐸ46ᐳ"}}:::plan
    Constant19 & List47 --> List49
    List56{{"List[56∈1] ➊<br />ᐸ19,55ᐳ"}}:::plan
    List55{{"List[55∈1] ➊<br />ᐸ54ᐳ"}}:::plan
    Constant19 & List55 --> List56
    PgPageInfo32{{"PgPageInfo[32∈1] ➊"}}:::plan
    Connection12 --> PgPageInfo32
    PgSelect13 --> Access35
    Lambda37{{"Lambda[37∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object36 --> Lambda37
    Lambda41{{"Lambda[41∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object40 --> Lambda41
    First43{{"First[43∈1] ➊"}}:::plan
    PgSelect13 --> First43
    PgSelectSingle44{{"PgSelectSingle[44∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First43 --> PgSelectSingle44
    PgCursor45{{"PgCursor[45∈1] ➊"}}:::plan
    List49 --> PgCursor45
    PgClassExpression46{{"PgClassExpression[46∈1] ➊<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle44 --> PgClassExpression46
    PgClassExpression46 --> List47
    Last51{{"Last[51∈1] ➊"}}:::plan
    PgSelect13 --> Last51
    PgSelectSingle52{{"PgSelectSingle[52∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    Last51 --> PgSelectSingle52
    PgCursor53{{"PgCursor[53∈1] ➊"}}:::plan
    List56 --> PgCursor53
    PgClassExpression54{{"PgClassExpression[54∈1] ➊<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression54
    PgClassExpression54 --> List55
    First58{{"First[58∈1] ➊"}}:::plan
    PgSelect57 --> First58
    PgSelectSingle59{{"PgSelectSingle[59∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First58 --> PgSelectSingle59
    PgClassExpression60{{"PgClassExpression[60∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle59 --> PgClassExpression60
    __Item14[/"__Item[14∈2]<br />ᐸ13ᐳ"\]:::itemplan
    PgSelect13 ==> __Item14
    PgSelectSingle15{{"PgSelectSingle[15∈2]<br />ᐸmessagesᐳ"}}:::plan
    __Item14 --> PgSelectSingle15
    PgSelect23[["PgSelect[23∈3]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object11 & PgClassExpression22 & Lambda63 & Access67 & Lambda72 & Lambda77 --> PgSelect23
    List20{{"List[20∈3]<br />ᐸ19,18ᐳ"}}:::plan
    List18{{"List[18∈3]<br />ᐸ17ᐳ"}}:::plan
    Constant19 & List18 --> List20
    PgCursor16{{"PgCursor[16∈3]"}}:::plan
    List20 --> PgCursor16
    PgClassExpression17{{"PgClassExpression[17∈3]<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle15 --> PgClassExpression17
    PgClassExpression17 --> List18
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle15 --> PgClassExpression21
    PgSelectSingle15 --> PgClassExpression22
    First27{{"First[27∈3]"}}:::plan
    PgSelect23 --> First27
    PgSelectSingle28{{"PgSelectSingle[28∈3]<br />ᐸusersᐳ"}}:::plan
    First27 --> PgSelectSingle28
    PgClassExpression29{{"PgClassExpression[29∈4]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle28 --> PgClassExpression29
    PgClassExpression30{{"PgClassExpression[30∈4]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle28 --> PgClassExpression30

    %% define steps

    subgraph "Buckets for queries/connections/basics"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,Access9,Access10,Object11,Connection12,Constant19,Lambda63,Lambda66,Access67,Constant68,Constant69,Constant70,Object71,Lambda72,Lambda77,Lambda82,Access83,Constant84,Constant85,Constant86,Object87,Lambda88,Lambda93,Constant99,Object102,Lambda103,Lambda108,Constant109,Constant110,Constant111,Constant112,Constant113,Constant114 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 11, 12, 63, 83, 88, 93, 6, 19, 67, 103, 108, 72, 77<br /><br />ROOT Connectionᐸ8ᐳ[12]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect13,PgPageInfo32,Access35,Object36,Lambda37,Object40,Lambda41,First43,PgSelectSingle44,PgCursor45,PgClassExpression46,List47,List49,Last51,PgSelectSingle52,PgCursor53,PgClassExpression54,List55,List56,PgSelect57,First58,PgSelectSingle59,PgClassExpression60 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 19, 11, 63, 67, 72, 77<br /><br />ROOT __Item{2}ᐸ13ᐳ[14]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item14,PgSelectSingle15 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 15, 19, 11, 63, 67, 72, 77<br /><br />ROOT PgSelectSingle{2}ᐸmessagesᐳ[15]<br />1: <br />ᐳ: 17, 21, 22, 18, 20, 16<br />2: PgSelect[23]<br />ᐳ: First[27], PgSelectSingle[28]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor16,PgClassExpression17,List18,List20,PgClassExpression21,PgClassExpression22,PgSelect23,First27,PgSelectSingle28 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 28<br /><br />ROOT PgSelectSingle{3}ᐸusersᐳ[28]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression29,PgClassExpression30 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
