%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/connections/basics-limit3"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[51]<br />ᐳ: 10, 11, 55, 56, 12, 15<br />2: PgSelect[9], PgSelect[20]<br />ᐳ: Access[21], Access[31], Access[52]<br />3: Connection[13], First[22]<br />ᐳ: 23, 24<br />4: ConnectionItems[16]<br />5: First[29], Last[33]<br />ᐳ: 30, 32, 34, 35"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 16, 31, 52, 24, 32, 35<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    Bucket3("Bucket 3 (listItem)<br />Deps: 31, 52<br /><br />ROOT __Item{3}ᐸ16ᐳ[25]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 25, 31, 26, 52<br /><br />ROOT Edge{3}[26]"):::bucket
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 36, 52<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[36]<br />1: <br />ᐳ: 40, 53, 54, 46<br />2: First[47]<br />ᐳ: PgSelectSingle[48]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 48<br /><br />ROOT PgSelectSingle{5}ᐸusersᐳ[48]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6

    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸmessages+1ᐳ<br />More deps:<br />- Constantᐸ3ᐳ[56]"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda15{{"Lambda[15∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[ undefined, 'INHERIT' ]ᐳ[55]"}}:::plan
    PgSelectInlineApply51["PgSelectInlineApply[51∈0] ➊"]:::plan
    Object12 & Lambda15 & PgSelectInlineApply51 --> PgSelect9
    PgSelect20[["PgSelect[20∈0] ➊<br />ᐸmessages(aggregate)ᐳ<br />More deps:<br />- Constantᐸ3ᐳ[56]"]]:::plan
    Object12 & Lambda15 --> PgSelect20
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    Connection13[["Connection[13∈0] ➊<br />ᐸ9ᐳ<br />Dependents: 2<br />More deps:<br />- Constantᐸ3ᐳ[56]"]]:::plan
    PgSelect9 --> Connection13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    ConnectionItems16[["ConnectionItems[16∈0] ➊<br />Dependents: 3<br />More deps:<br />- Connection[13]"]]:::plan
    Access21{{"Access[21∈0] ➊<br />ᐸ20.itemsᐳ"}}:::plan
    PgSelect20 --> Access21
    First22[["First[22∈0] ➊"]]:::plan
    Access21 --> First22
    PgSelectSingle23{{"PgSelectSingle[23∈0] ➊<br />ᐸmessagesᐳ"}}:::plan
    First22 --> PgSelectSingle23
    First29[["First[29∈0] ➊<br />More deps:<br />- ConnectionItems[16]"]]:::plan
    PgSelectSingle30{{"PgSelectSingle[30∈0] ➊<br />ᐸmessagesᐳ"}}:::plan
    First29 --> PgSelectSingle30
    Access31{{"Access[31∈0] ➊<br />ᐸ9.cursorDetailsᐳ<br />Dependents: 3"}}:::plan
    PgSelect9 --> Access31
    Last33[["Last[33∈0] ➊<br />More deps:<br />- ConnectionItems[16]"]]:::plan
    PgSelectSingle34{{"PgSelectSingle[34∈0] ➊<br />ᐸmessagesᐳ"}}:::plan
    Last33 --> PgSelectSingle34
    Access52{{"Access[52∈0] ➊<br />ᐸ9.m.joinDetailsFor42ᐳ"}}:::plan
    PgSelect9 --> Access52
    PageInfo19{{"PageInfo[19∈1] ➊<br />More deps:<br />- Connection[13]"}}:::plan
    __Item25[/"__Item[25∈3]<br />ᐸ16ᐳ<br />More deps:<br />- ConnectionItems[16]"\]:::itemplan
    Edge26{{"Edge[26∈3]"}}:::plan
    __Item25 --> Edge26
    PgCursor38{{"PgCursor[38∈4]<br />More deps:<br />- Access[31]"}}:::plan
    PgSelectSingle36{{"PgSelectSingle[36∈4]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle36 --> PgCursor38
    __Item25 --> PgSelectSingle36
    List53{{"List[53∈5]<br />ᐸ52,36ᐳ"}}:::plan
    Access52 & PgSelectSingle36 --> List53
    PgClassExpression40{{"PgClassExpression[40∈5]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle36 --> PgClassExpression40
    Access46{{"Access[46∈5]<br />ᐸ54.itemsᐳ"}}:::plan
    Lambda54{{"Lambda[54∈5]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda54 --> Access46
    First47[["First[47∈5]"]]:::plan
    Access46 --> First47
    PgSelectSingle48{{"PgSelectSingle[48∈5]<br />ᐸusersᐳ"}}:::plan
    First47 --> PgSelectSingle48
    List53 --> Lambda54
    PgClassExpression49{{"PgClassExpression[49∈6]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression49
    PgClassExpression50{{"PgClassExpression[50∈6]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression50

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect9,Access10,Access11,Object12,Connection13,Lambda15,ConnectionItems16,PgSelect20,Access21,First22,PgSelectSingle23,First29,PgSelectSingle30,Access31,Last33,PgSelectSingle34,PgSelectInlineApply51,Access52 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PageInfo19 bucket1
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item25,Edge26 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgSelectSingle36,PgCursor38 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression40,Access46,First47,PgSelectSingle48,List53,Lambda54 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression49,PgClassExpression50 bucket6

