%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Connection13{{"Connection[13∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant51{{"Constant[51∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Constant51 --> Connection13
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant34{{"Constant[34∈0] ➊<br />ᐸfalseᐳ"}}:::plan
    PgSelect14[["PgSelect[14∈1] ➊<br />ᐸmessages+1ᐳ"]]:::plan
    Object12 & Connection13 --> PgSelect14
    PgSelect47[["PgSelect[47∈1] ➊<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object12 & Connection13 --> PgSelect47
    PgPageInfo31{{"PgPageInfo[31∈1] ➊"}}:::plan
    Connection13 --> PgPageInfo31
    Access33{{"Access[33∈1] ➊<br />ᐸ14.hasMoreᐳ"}}:::plan
    PgSelect14 --> Access33
    First36{{"First[36∈1] ➊"}}:::plan
    PgSelect14 --> First36
    PgSelectSingle37{{"PgSelectSingle[37∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First36 --> PgSelectSingle37
    PgCursor38{{"PgCursor[38∈1] ➊"}}:::plan
    List40{{"List[40∈1] ➊<br />ᐸ39ᐳ"}}:::plan
    List40 --> PgCursor38
    PgClassExpression39{{"PgClassExpression[39∈1] ➊<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression39
    PgClassExpression39 --> List40
    Last42{{"Last[42∈1] ➊"}}:::plan
    PgSelect14 --> Last42
    PgSelectSingle43{{"PgSelectSingle[43∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    Last42 --> PgSelectSingle43
    PgCursor44{{"PgCursor[44∈1] ➊"}}:::plan
    List46{{"List[46∈1] ➊<br />ᐸ45ᐳ"}}:::plan
    List46 --> PgCursor44
    PgClassExpression45{{"PgClassExpression[45∈1] ➊<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression45
    PgClassExpression45 --> List46
    First48{{"First[48∈1] ➊"}}:::plan
    PgSelect47 --> First48
    PgSelectSingle49{{"PgSelectSingle[49∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First48 --> PgSelectSingle49
    PgClassExpression50{{"PgClassExpression[50∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle49 --> PgClassExpression50
    __Item15[/"__Item[15∈2]<br />ᐸ14ᐳ"\]:::itemplan
    PgSelect14 ==> __Item15
    PgSelectSingle16{{"PgSelectSingle[16∈2]<br />ᐸmessagesᐳ"}}:::plan
    __Item15 --> PgSelectSingle16
    PgSelect22[["PgSelect[22∈3]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object12 & PgClassExpression21 --> PgSelect22
    PgCursor17{{"PgCursor[17∈3]"}}:::plan
    List19{{"List[19∈3]<br />ᐸ18ᐳ"}}:::plan
    List19 --> PgCursor17
    PgClassExpression18{{"PgClassExpression[18∈3]<br />ᐸ__messages__.”id”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression18
    PgClassExpression18 --> List19
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression20
    PgSelectSingle16 --> PgClassExpression21
    First26{{"First[26∈3]"}}:::plan
    PgSelect22 --> First26
    PgSelectSingle27{{"PgSelectSingle[27∈3]<br />ᐸusersᐳ"}}:::plan
    First26 --> PgSelectSingle27
    PgClassExpression28{{"PgClassExpression[28∈4]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression28
    PgClassExpression29{{"PgClassExpression[29∈4]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle27 --> PgClassExpression29

    %% define steps

    subgraph "Buckets for queries/connections/basics-limit3"
    Bucket0("Bucket 0 (root)"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access11,Object12,Connection13,Constant34,Constant51 bucket0
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 12, 13, 34<br /><br />ROOT Connectionᐸ9ᐳ[13]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect14,PgPageInfo31,Access33,First36,PgSelectSingle37,PgCursor38,PgClassExpression39,List40,Last42,PgSelectSingle43,PgCursor44,PgClassExpression45,List46,PgSelect47,First48,PgSelectSingle49,PgClassExpression50 bucket1
    Bucket2("Bucket 2 (listItem)<br />Deps: 12<br /><br />ROOT __Item{2}ᐸ14ᐳ[15]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item15,PgSelectSingle16 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 16, 12<br /><br />ROOT PgSelectSingle{2}ᐸmessagesᐳ[16]<br />1: <br />ᐳ: 18, 20, 21, 19, 17<br />2: PgSelect[22]<br />ᐳ: First[26], PgSelectSingle[27]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor17,PgClassExpression18,List19,PgClassExpression20,PgClassExpression21,PgSelect22,First26,PgSelectSingle27 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 27<br /><br />ROOT PgSelectSingle{3}ᐸusersᐳ[27]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression28,PgClassExpression29 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
