%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/connections/basics-limit3"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 13, 17, 15, 89, 84, 6<br /><br />ROOT Connectionᐸ9ᐳ[15]<br />1: PgSelect[19], PgSelect[24]<br />ᐳ: 23, 37, 39, 40, 46, 47, 55, 85<br />2: PgSelectRows[27], PgSelectRows[31]<br />ᐳ: 26, 29, 30, 51, 54, 57, 60, 62, 65"):::bucket
    Bucket2("Bucket 2 (listItem)<br />Deps: 55, 85<br /><br />ROOT __Item{2}ᐸ31ᐳ[32]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 33, 55, 85<br /><br />ROOT PgSelectSingle{2}ᐸmessagesᐳ[33]<br />1: <br />ᐳ: 68, 69, 86, 87<br />2: PgSelectRows[79]<br />ᐳ: First[78], PgSelectSingle[81]"):::bucket
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 81<br /><br />ROOT PgSelectSingle{3}ᐸusersᐳ[81]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4

    %% plan dependencies
    Object13{{"Object[13∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access12{{"Access[12∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access12 --> Object13
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access12
    Connection15{{"Connection[15∈0] ➊<br />ᐸ9ᐳ"}}:::plan
    Constant89{{"Constant[89∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Constant89 --> Connection15
    Lambda17{{"Lambda[17∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    Constant88{{"Constant[88∈0] ➊<br />ᐸ[ undefined, 'INHERIT' ]ᐳ"}}:::plan
    Constant88 --> Lambda17
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelectInlineApply84["PgSelectInlineApply[84∈0] ➊"]:::plan
    PgSelect19[["PgSelect[19∈1] ➊<br />ᐸmessages+1ᐳ"]]:::plan
    Object13 & Lambda17 & Connection15 & Constant89 & PgSelectInlineApply84 --> PgSelect19
    Object46{{"Object[46∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access37{{"Access[37∈1] ➊<br />ᐸ19.hasMoreᐳ"}}:::plan
    Constant89 & Access37 --> Object46
    PgSelect24[["PgSelect[24∈1] ➊<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object13 & Lambda17 & Connection15 --> PgSelect24
    Object39{{"Object[39∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant89 & Access37 --> Object39
    PgCursor57{{"PgCursor[57∈1] ➊"}}:::plan
    PgSelectSingle54{{"PgSelectSingle[54∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    Access55{{"Access[55∈1] ➊<br />ᐸ19.cursorDetailsᐳ"}}:::plan
    PgSelectSingle54 & Access55 --> PgCursor57
    PgCursor65{{"PgCursor[65∈1] ➊"}}:::plan
    PgSelectSingle62{{"PgSelectSingle[62∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle62 & Access55 --> PgCursor65
    PgPageInfo23{{"PgPageInfo[23∈1] ➊"}}:::plan
    Connection15 --> PgPageInfo23
    First26{{"First[26∈1] ➊"}}:::plan
    PgSelectRows27[["PgSelectRows[27∈1] ➊"]]:::plan
    PgSelectRows27 --> First26
    PgSelect24 --> PgSelectRows27
    PgSelectSingle29{{"PgSelectSingle[29∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First26 --> PgSelectSingle29
    PgClassExpression30{{"PgClassExpression[30∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression30
    PgSelectRows31[["PgSelectRows[31∈1] ➊"]]:::plan
    PgSelect19 --> PgSelectRows31
    PgSelect19 --> Access37
    Lambda40{{"Lambda[40∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object39 --> Lambda40
    Lambda47{{"Lambda[47∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object46 --> Lambda47
    First51{{"First[51∈1] ➊"}}:::plan
    PgSelectRows31 --> First51
    First51 --> PgSelectSingle54
    PgSelect19 --> Access55
    Last60{{"Last[60∈1] ➊"}}:::plan
    PgSelectRows31 --> Last60
    Last60 --> PgSelectSingle62
    Access85{{"Access[85∈1] ➊<br />ᐸ19.m.joinDetailsFor71ᐳ"}}:::plan
    PgSelect19 --> Access85
    __Item32[/"__Item[32∈2]<br />ᐸ31ᐳ"\]:::itemplan
    PgSelectRows31 ==> __Item32
    PgSelectSingle33{{"PgSelectSingle[33∈2]<br />ᐸmessagesᐳ"}}:::plan
    __Item32 --> PgSelectSingle33
    PgCursor68{{"PgCursor[68∈3]"}}:::plan
    PgSelectSingle33 & Access55 --> PgCursor68
    List86{{"List[86∈3]<br />ᐸ85,33ᐳ"}}:::plan
    Access85 & PgSelectSingle33 --> List86
    PgClassExpression69{{"PgClassExpression[69∈3]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle33 --> PgClassExpression69
    First78{{"First[78∈3]"}}:::plan
    PgSelectRows79[["PgSelectRows[79∈3]"]]:::plan
    PgSelectRows79 --> First78
    Lambda87{{"Lambda[87∈3]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda87 --> PgSelectRows79
    PgSelectSingle81{{"PgSelectSingle[81∈3]<br />ᐸusersᐳ"}}:::plan
    First78 --> PgSelectSingle81
    List86 --> Lambda87
    PgClassExpression82{{"PgClassExpression[82∈4]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle81 --> PgClassExpression82
    PgClassExpression83{{"PgClassExpression[83∈4]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle81 --> PgClassExpression83

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access10,Access12,Object13,Connection15,Lambda17,PgSelectInlineApply84,Constant88,Constant89 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect19,PgPageInfo23,PgSelect24,First26,PgSelectRows27,PgSelectSingle29,PgClassExpression30,PgSelectRows31,Access37,Object39,Lambda40,Object46,Lambda47,First51,PgSelectSingle54,Access55,PgCursor57,Last60,PgSelectSingle62,PgCursor65,Access85 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,__Item32,PgSelectSingle33 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgCursor68,PgClassExpression69,First78,PgSelectRows79,PgSelectSingle81,List86,Lambda87 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression82,PgClassExpression83 bucket4

