%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect9[["PgSelect[9∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant95{{"Constant[95∈0] ➊<br />ᐸ2ᐳ"}}:::plan
    Lambda14{{"Lambda[14∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    PgSelectInlineApply87["PgSelectInlineApply[87∈0] ➊"]:::plan
    PgSelectInlineApply91["PgSelectInlineApply[91∈0] ➊"]:::plan
    Object12 & Constant95 & Lambda14 & PgSelectInlineApply87 & PgSelectInlineApply91 --> PgSelect9
    Lambda30{{"Lambda[30∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    PgSelectInlineApply83["PgSelectInlineApply[83∈0] ➊"]:::plan
    Constant95 & Lambda30 & PgSelectInlineApply83 --> PgSelectInlineApply87
    Access10{{"Access[10∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access10 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access10
    __Value2 --> Access11
    Constant98{{"Constant[98∈0] ➊<br />ᐸ[ undefined, 'YES' ]ᐳ"}}:::plan
    Constant98 --> Lambda14
    PgSelectRows15[["PgSelectRows[15∈0] ➊"]]:::plan
    PgSelect9 --> PgSelectRows15
    Connection26{{"Connection[26∈0] ➊<br />ᐸ22ᐳ"}}:::plan
    Constant95 --> Connection26
    Constant99{{"Constant[99∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant99 --> Lambda30
    Access88{{"Access[88∈0] ➊<br />ᐸ9.m.subqueryDetailsFor31ᐳ"}}:::plan
    PgSelect9 --> Access88
    Lambda30 --> PgSelectInlineApply91
    Access92{{"Access[92∈0] ➊<br />ᐸ9.m.subqueryDetailsFor39ᐳ"}}:::plan
    PgSelect9 --> Access92
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    List89{{"List[89∈1]<br />ᐸ88,16ᐳ"}}:::plan
    __Item16[/"__Item[16∈1]<br />ᐸ15ᐳ"\]:::itemplan
    Access88 & __Item16 --> List89
    PgSelectRows15 ==> __Item16
    PgSelectSingle17{{"PgSelectSingle[17∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item16 --> PgSelectSingle17
    Lambda90{{"Lambda[90∈1]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List89 --> Lambda90
    List93{{"List[93∈2]<br />ᐸ92,16ᐳ"}}:::plan
    Access92 & __Item16 --> List93
    PgClassExpression18{{"PgClassExpression[18∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression18
    Lambda94{{"Lambda[94∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List93 --> Lambda94
    Object62{{"Object[62∈3]<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access57{{"Access[57∈3]<br />ᐸ90.hasMoreᐳ"}}:::plan
    Constant95 & Access57 --> Object62
    Object58{{"Object[58∈3]<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant95 & Access57 --> Object58
    PgCursor69{{"PgCursor[69∈3]"}}:::plan
    PgSelectSingle67{{"PgSelectSingle[67∈3]<br />ᐸmessagesᐳ"}}:::plan
    Access53{{"Access[53∈3]<br />ᐸ90.cursorDetailsᐳ"}}:::plan
    PgSelectSingle67 & Access53 --> PgCursor69
    PgCursor75{{"PgCursor[75∈3]"}}:::plan
    PgSelectSingle73{{"PgSelectSingle[73∈3]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle73 & Access53 --> PgCursor75
    PgSelectRows32[["PgSelectRows[32∈3]"]]:::plan
    Lambda90 --> PgSelectRows32
    PgPageInfo38{{"PgPageInfo[38∈3] ➊"}}:::plan
    Connection26 --> PgPageInfo38
    First40{{"First[40∈3]"}}:::plan
    PgSelectRows41[["PgSelectRows[41∈3]"]]:::plan
    PgSelectRows41 --> First40
    Lambda94 --> PgSelectRows41
    PgSelectSingle42{{"PgSelectSingle[42∈3]<br />ᐸmessagesᐳ"}}:::plan
    First40 --> PgSelectSingle42
    PgClassExpression43{{"PgClassExpression[43∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle42 --> PgClassExpression43
    Lambda90 --> Access53
    Lambda90 --> Access57
    Lambda59{{"Lambda[59∈3]<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object58 --> Lambda59
    Lambda63{{"Lambda[63∈3]<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object62 --> Lambda63
    First65{{"First[65∈3]"}}:::plan
    PgSelectRows32 --> First65
    First65 --> PgSelectSingle67
    Last71{{"Last[71∈3]"}}:::plan
    PgSelectRows32 --> Last71
    Last71 --> PgSelectSingle73
    __Item33[/"__Item[33∈4]<br />ᐸ32ᐳ"\]:::itemplan
    PgSelectRows32 ==> __Item33
    PgSelectSingle34{{"PgSelectSingle[34∈4]<br />ᐸmessagesᐳ"}}:::plan
    __Item33 --> PgSelectSingle34
    Access84{{"Access[84∈4]<br />ᐸ90.m.joinDetailsFor46ᐳ"}}:::plan
    Lambda90 --> Access84
    PgCursor54{{"PgCursor[54∈5]"}}:::plan
    PgSelectSingle34 & Access53 --> PgCursor54
    List85{{"List[85∈5]<br />ᐸ84,34ᐳ"}}:::plan
    Access84 & PgSelectSingle34 --> List85
    PgClassExpression44{{"PgClassExpression[44∈5]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression44
    First50{{"First[50∈5]"}}:::plan
    PgSelectRows51[["PgSelectRows[51∈5]"]]:::plan
    PgSelectRows51 --> First50
    Lambda86{{"Lambda[86∈5]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda86 --> PgSelectRows51
    PgSelectSingle52{{"PgSelectSingle[52∈5]<br />ᐸusersᐳ"}}:::plan
    First50 --> PgSelectSingle52
    List85 --> Lambda86
    PgClassExpression76{{"PgClassExpression[76∈6]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression76
    PgClassExpression77{{"PgClassExpression[77∈6]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle52 --> PgClassExpression77

    %% define steps

    subgraph "Buckets for queries/connections/pagination-when-inlined-backwards"
    Bucket0("Bucket 0 (root)<br /><br />1: PgSelectInlineApply[83]<br />ᐳ: 8, 10, 11, 95, 98, 99, 12, 14, 26, 30<br />2: 87, 91<br />3: PgSelect[9]<br />ᐳ: Access[88], Access[92]<br />4: PgSelectRows[15]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect9,Access10,Access11,Object12,Lambda14,PgSelectRows15,Connection26,Lambda30,PgSelectInlineApply83,PgSelectInlineApply87,Access88,PgSelectInlineApply91,Access92,Constant95,Constant98,Constant99 bucket0
    Bucket1("Bucket 1 (listItem)<br />Deps: 88, 92, 26, 8, 95<br /><br />ROOT __Item{1}ᐸ15ᐳ[16]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item16,PgSelectSingle17,List89,Lambda90 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 17, 92, 16, 90, 26, 8, 95<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[17]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression18,List93,Lambda94 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 90, 26, 94, 8, 95<br /><br />ROOT Connectionᐸ22ᐳ[26]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgSelectRows32,PgPageInfo38,First40,PgSelectRows41,PgSelectSingle42,PgClassExpression43,Access53,Access57,Object58,Lambda59,Object62,Lambda63,First65,PgSelectSingle67,PgCursor69,Last71,PgSelectSingle73,PgCursor75 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 90, 53<br /><br />ROOT __Item{4}ᐸ32ᐳ[33]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item33,PgSelectSingle34,Access84 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 34, 53, 84<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[34]<br />1: <br />ᐳ: 44, 54, 85, 86<br />2: PgSelectRows[51]<br />ᐳ: First[50], PgSelectSingle[52]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression44,First50,PgSelectRows51,PgSelectSingle52,PgCursor54,List85,Lambda86 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 52<br /><br />ROOT PgSelectSingle{5}ᐸusersᐳ[52]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression76,PgClassExpression77 bucket6
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    end
