%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/connections/pagination-before-last-pagination-only"
    Bucket0("Bucket 0 (root)"):::bucket
    Bucket1("Bucket 1 (nullableBoundary)<br />Deps: 14, 18, 16, 20, 48, 6<br /><br />ROOT Connectionᐸ10ᐳ[16]<br />1: PgSelect[22], PgSelect[25]<br />ᐳ: 24, 35, 37, 38, 44, 45<br />2: PgSelectRows[28]<br />ᐳ: 27, 30, 31"):::bucket
    end
    Bucket0 --> Bucket1

    %% plan dependencies
    Object14{{"Object[14∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access11 & Access13 --> Object14
    Connection16{{"Connection[16∈0] ➊<br />ᐸ10ᐳ"}}:::plan
    Constant48{{"Constant[48∈0] ➊<br />ᐸ3ᐳ"}}:::plan
    Lambda20{{"Lambda[20∈0] ➊<br />ᐸparseCursorᐳ"}}:::plan
    Constant48 & Lambda20 --> Connection16
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access11
    __Value2 --> Access13
    Lambda18{{"Lambda[18∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    Constant47{{"Constant[47∈0] ➊<br />ᐸ[ undefined, 'INHERIT' ]ᐳ"}}:::plan
    Constant47 --> Lambda18
    Constant49{{"Constant[49∈0] ➊<br />ᐸ'WyJmMGIyOGM5NGMxIiwiZjE3MGYxNzAtMDAwMC0wMDAwLTAwMDAtYjBiMDAᐳ"}}:::plan
    Constant49 --> Lambda20
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    PgSelect22[["PgSelect[22∈1] ➊<br />ᐸmessages+1ᐳ"]]:::plan
    Object14 & Lambda18 & Connection16 & Lambda20 & Constant48 --> PgSelect22
    Object44{{"Object[44∈1] ➊<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access35{{"Access[35∈1] ➊<br />ᐸ22.hasMoreᐳ"}}:::plan
    Constant48 & Access35 --> Object44
    PgSelect25[["PgSelect[25∈1] ➊<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object14 & Lambda18 & Connection16 --> PgSelect25
    Object37{{"Object[37∈1] ➊<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant48 & Access35 --> Object37
    PgPageInfo24{{"PgPageInfo[24∈1] ➊"}}:::plan
    Connection16 --> PgPageInfo24
    First27{{"First[27∈1] ➊"}}:::plan
    PgSelectRows28[["PgSelectRows[28∈1] ➊"]]:::plan
    PgSelectRows28 --> First27
    PgSelect25 --> PgSelectRows28
    PgSelectSingle30{{"PgSelectSingle[30∈1] ➊<br />ᐸmessagesᐳ"}}:::plan
    First27 --> PgSelectSingle30
    PgClassExpression31{{"PgClassExpression[31∈1] ➊<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression31
    PgSelect22 --> Access35
    Lambda38{{"Lambda[38∈1] ➊<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object37 --> Lambda38
    Lambda45{{"Lambda[45∈1] ➊<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object44 --> Lambda45

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Access11,Access13,Object14,Connection16,Lambda18,Lambda20,Constant47,Constant48,Constant49 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,PgSelect22,PgPageInfo24,PgSelect25,First27,PgSelectRows28,PgSelectSingle30,PgClassExpression31,Access35,Object37,Lambda38,Object44,Lambda45 bucket1

