#!/bin/bash

set -e
cd $(dirname $0)/..

npm_bin=$(npm bin)

echo "Cleaning build"
rm -rf build
mkdir build

echo "Preparing assets"
scripts/make-assets

echo "Compiling with TypeScript"
"$npm_bin"/tsc
find build -wholename '*/__tests__/*' -delete
find build -name '__tests__' -delete

echo "Removing tests/mocks"
find build -wholename '*/__tests__/*' -delete
find build -name '__tests__' -delete

echo "[hack] Hacking react-scripts webpack config to not mangle names"
echo "[hack]   due to https://github.com/graphql/graphql-js/issues/1182"
sed -i'' -e 's/mangle: [{]/mangle: false, mangle_DISABLED: {/g' node_modules/react-scripts/config/webpack.config.prod.js

echo "Building GraphiQL"
(cd src/postgraphile/graphiql && "$npm_bin"/react-scripts build)

echo "Moving GraphiQL build output"
mkdir -p build/postgraphile/graphiql/public
mv src/postgraphile/graphiql/build/* build/postgraphile/graphiql/public
