#!/bin/bash

export PATH="$PATH:`pwd`/node_modules/.bin"

set -e
echo "[1/4]: Building Code"
yarn prepack:all

echo "[2/4]: Checking Code Format"
yarn prettier:check

echo "[3/4]: Linting Code"
yarn eslint

echo "[4/4]: Testing Project"
for I in packages/*/; do
  if [[ "$PGVERSION" != "9.6" || ( "$I" != "packages/lds/" && "$I" != "packages/subscriptions-lds/" ) ]]; then
    cd $I
    yarn test
    cd -
  fi;
done

echo ""
echo "CI completed succesfully 🎉"
echo ""
