#!/bin/bash

set -e

ls .
ls ./src
ls ./src/graphql
ls ./src/graphql/schema

echo "[1/3]: Building Code"
scripts/build

echo "[2/3]: Linting Code"
scripts/lint

echo "[3/3]: Testing Project"
scripts/test

echo ""
echo "CI completed succesfully 🎉"
echo ""
