#!/bin/bash
set -e
cd packages;
# Do not run this in parallel; build order matters due to TypeScript.
for PACKAGE in jest-serializer-graphql-schema graphile lru pg-sql2 graphql-parse-resolve-info graphile-build graphile-build-pg graphile-utils postgraphile-core lds subscriptions-lds pg-pubsub; do
  cd $PACKAGE;
  npm run prepack;
  cd -;
done;
