#!/bin/bash
set -e

# Make sure any generated assets are built
yarn workspaces foreach --parallel --topological run preprepack

# Build everything in the relevant order according to TypeScript project references
tsc -b

# Now run `prepack` on each package (slightly parallelised)
yarn workspaces foreach --parallel --topological run prepack
