%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/conditions/archived-forum-inherited-messages.stream-2"
    Bucket0("Bucket 0 (root)<br /><br />1: 104, 108<br />ᐳ: 6, 9, 11, 30, 37, 38, 122, 123, 12, 15, 35<br />2: 112, 116<br />3: PgSelect[8]<br />ᐳ: Access[113], Access[117]<br />4: PgSelectRows[17]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 113, 117, 12, 35, 30, 104, 108, 6, 37, 38<br /><br />ROOT __Item{1}ᐸ17ᐳ[18]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 19, 113, 18, 117, 12, 35, 30, 104, 108, 6, 37, 38<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[19]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 19, 12, 35, 30, 104, 108, 119, 115, 6, 37, 38<br /><br />ROOT Connectionᐸ23ᐳ[30]<br />1: PgSelectRows[48]<br />ᐳ: 22, 31, 45, 60, 47, 50, 51, 62, 63, 68, 69<br />2: PgSelect[39], PgSelect[43]<br />3: PgSelectRows[52], PgSelectRows[55]"):::bucket
    Bucket4("Bucket 4 (listItem)<br />Deps: 39<br /><br />ROOT __Item{4}ᐸ52ᐳ[53]"):::bucket
    Bucket5("Bucket 5 (listItem)<br />Deps: 43<br /><br />ROOT __Item{5}ᐸ55ᐳ[56]"):::bucket
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 54, 105<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[54]<br />1: <br />ᐳ: 71, 106, 107<br />2: PgSelectRows[81]<br />ᐳ: First[80], PgSelectSingle[83]"):::bucket
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 57, 84, 109<br /><br />ROOT PgSelectSingle{5}ᐸmessagesᐳ[57]<br />1: <br />ᐳ: 86, 89, 110, 111<br />2: PgSelectRows[99]<br />ᐳ: First[98], PgSelectSingle[101]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 83<br /><br />ROOT PgSelectSingle{6}ᐸusersᐳ[83]"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 101<br /><br />ROOT PgSelectSingle{7}ᐸusersᐳ[101]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket5
    Bucket4 --> Bucket6
    Bucket5 --> Bucket7
    Bucket6 --> Bucket8
    Bucket7 --> Bucket9

    %% plan dependencies
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object12{{"Object[12∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda15{{"Lambda[15∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    PgSelectInlineApply112["PgSelectInlineApply[112∈0] ➊"]:::plan
    PgSelectInlineApply116["PgSelectInlineApply[116∈0] ➊"]:::plan
    Object12 & Lambda15 & PgSelectInlineApply112 & PgSelectInlineApply116 --> PgSelect8
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access11{{"Access[11∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access11 --> Object12
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access11
    Constant122{{"Constant[122∈0] ➊<br />ᐸ[ undefined, 'EXCLUSIVELY' ]ᐳ"}}:::plan
    Constant122 --> Lambda15
    PgSelectRows17[["PgSelectRows[17∈0] ➊"]]:::plan
    PgSelect8 --> PgSelectRows17
    Lambda35{{"Lambda[35∈0] ➊<br />ᐸincludeArchivedConditionᐳ"}}:::plan
    Constant123{{"Constant[123∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant123 --> Lambda35
    Lambda35 --> PgSelectInlineApply112
    Access113{{"Access[113∈0] ➊<br />ᐸ8.m.subqueryDetailsFor44ᐳ"}}:::plan
    PgSelect8 --> Access113
    Lambda35 --> PgSelectInlineApply116
    Access117{{"Access[117∈0] ➊<br />ᐸ8.m.subqueryDetailsFor46ᐳ"}}:::plan
    PgSelect8 --> Access117
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Connection30{{"Connection[30∈0] ➊<br />ᐸ23ᐳ"}}:::plan
    Constant37{{"Constant[37∈0] ➊<br />ᐸ[HIDDEN]ᐳ"}}:::plan
    Constant38{{"Constant[38∈0] ➊<br />ᐸtrueᐳ"}}:::plan
    PgSelectInlineApply104["PgSelectInlineApply[104∈0] ➊"]:::plan
    PgSelectInlineApply108["PgSelectInlineApply[108∈0] ➊"]:::plan
    __Item18[/"__Item[18∈1]<br />ᐸ17ᐳ"\]:::itemplan
    PgSelectRows17 ==> __Item18
    PgSelectSingle19{{"PgSelectSingle[19∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item18 --> PgSelectSingle19
    List114{{"List[114∈2]<br />ᐸ113,18ᐳ"}}:::plan
    Access113 & __Item18 --> List114
    List118{{"List[118∈2]<br />ᐸ117,18ᐳ"}}:::plan
    Access117 & __Item18 --> List118
    PgClassExpression20{{"PgClassExpression[20∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle19 --> PgClassExpression20
    Lambda115{{"Lambda[115∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List114 --> Lambda115
    Lambda119{{"Lambda[119∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List118 --> Lambda119
    PgSelect39[["PgSelect[39∈3@s]<br />ᐸmessagesᐳ"]]:::plan
    PgClassExpression22{{"PgClassExpression[22∈3]<br />ᐸ__forums__.”id”ᐳ"}}:::plan
    PgClassExpression31{{"PgClassExpression[31∈3]<br />ᐸ__forums__...chived_at”ᐳ"}}:::plan
    Object12 & PgClassExpression22 & PgClassExpression31 & Lambda35 & Connection30 & PgSelectInlineApply104 --> PgSelect39
    PgSelect43[["PgSelect[43∈3@s]<br />ᐸmessagesᐳ"]]:::plan
    Object12 & PgClassExpression22 & PgClassExpression31 & Lambda35 & Connection30 & PgSelectInlineApply108 --> PgSelect43
    Object68{{"Object[68∈3]<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access60{{"Access[60∈3]<br />ᐸ115.hasMoreᐳ"}}:::plan
    Access60 --> Object68
    Object62{{"Object[62∈3]<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Access60 --> Object62
    PgSelectSingle19 --> PgClassExpression22
    PgSelectSingle19 --> PgClassExpression31
    PgPageInfo45{{"PgPageInfo[45∈3] ➊"}}:::plan
    Connection30 --> PgPageInfo45
    First47{{"First[47∈3]"}}:::plan
    PgSelectRows48[["PgSelectRows[48∈3]"]]:::plan
    PgSelectRows48 --> First47
    Lambda119 --> PgSelectRows48
    PgSelectSingle50{{"PgSelectSingle[50∈3]<br />ᐸmessagesᐳ"}}:::plan
    First47 --> PgSelectSingle50
    PgClassExpression51{{"PgClassExpression[51∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle50 --> PgClassExpression51
    PgSelectRows52[["PgSelectRows[52∈3@s]"]]:::plan
    PgSelect39 --> PgSelectRows52
    PgSelectRows55[["PgSelectRows[55∈3@s]"]]:::plan
    PgSelect43 --> PgSelectRows55
    Lambda115 --> Access60
    Lambda63{{"Lambda[63∈3]<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object62 --> Lambda63
    Lambda69{{"Lambda[69∈3]<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object68 --> Lambda69
    __Item53[/"__Item[53∈4]<br />ᐸ52ᐳ"\]:::itemplan
    PgSelectRows52 ==> __Item53
    PgSelectSingle54{{"PgSelectSingle[54∈4]<br />ᐸmessagesᐳ"}}:::plan
    __Item53 --> PgSelectSingle54
    Access105{{"Access[105∈4]<br />ᐸ39.m.joinDetailsFor73ᐳ"}}:::plan
    PgSelect39 --> Access105
    List106{{"List[106∈6]<br />ᐸ105,54ᐳ"}}:::plan
    Access105 & PgSelectSingle54 --> List106
    PgClassExpression71{{"PgClassExpression[71∈6]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle54 --> PgClassExpression71
    First80{{"First[80∈6]"}}:::plan
    PgSelectRows81[["PgSelectRows[81∈6]"]]:::plan
    PgSelectRows81 --> First80
    Lambda107{{"Lambda[107∈6]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda107 --> PgSelectRows81
    PgSelectSingle83{{"PgSelectSingle[83∈6]<br />ᐸusersᐳ"}}:::plan
    First80 --> PgSelectSingle83
    List106 --> Lambda107
    PgClassExpression87{{"PgClassExpression[87∈8]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle83 --> PgClassExpression87
    PgClassExpression88{{"PgClassExpression[88∈8]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle83 --> PgClassExpression88
    __Item56[/"__Item[56∈5]<br />ᐸ55ᐳ"\]:::itemplan
    PgSelectRows55 ==> __Item56
    PgSelectSingle57{{"PgSelectSingle[57∈5]<br />ᐸmessagesᐳ"}}:::plan
    __Item56 --> PgSelectSingle57
    Access84{{"Access[84∈5]<br />ᐸ43.cursorDetailsᐳ"}}:::plan
    PgSelect43 --> Access84
    Access109{{"Access[109∈5]<br />ᐸ43.m.joinDetailsFor91ᐳ"}}:::plan
    PgSelect43 --> Access109
    PgCursor86{{"PgCursor[86∈7]"}}:::plan
    PgSelectSingle57 & Access84 --> PgCursor86
    List110{{"List[110∈7]<br />ᐸ109,57ᐳ"}}:::plan
    Access109 & PgSelectSingle57 --> List110
    PgClassExpression89{{"PgClassExpression[89∈7]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle57 --> PgClassExpression89
    First98{{"First[98∈7]"}}:::plan
    PgSelectRows99[["PgSelectRows[99∈7]"]]:::plan
    PgSelectRows99 --> First98
    Lambda111{{"Lambda[111∈7]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda111 --> PgSelectRows99
    PgSelectSingle101{{"PgSelectSingle[101∈7]<br />ᐸusersᐳ"}}:::plan
    First98 --> PgSelectSingle101
    List110 --> Lambda111
    PgClassExpression102{{"PgClassExpression[102∈9]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle101 --> PgClassExpression102
    PgClassExpression103{{"PgClassExpression[103∈9]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle101 --> PgClassExpression103

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,PgSelect8,Access9,Access11,Object12,Lambda15,PgSelectRows17,Connection30,Lambda35,Constant37,Constant38,PgSelectInlineApply104,PgSelectInlineApply108,PgSelectInlineApply112,Access113,PgSelectInlineApply116,Access117,Constant122,Constant123 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item18,PgSelectSingle19 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression20,List114,Lambda115,List118,Lambda119 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression22,PgClassExpression31,PgSelect39,PgSelect43,PgPageInfo45,First47,PgSelectRows48,PgSelectSingle50,PgClassExpression51,PgSelectRows52,PgSelectRows55,Access60,Object62,Lambda63,Object68,Lambda69 bucket3
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item53,PgSelectSingle54,Access105 bucket4
    classDef bucket5 stroke:#7fff00
    class Bucket5,__Item56,PgSelectSingle57,Access84,Access109 bucket5
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression71,First80,PgSelectRows81,PgSelectSingle83,List106,Lambda107 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,PgCursor86,PgClassExpression89,First98,PgSelectRows99,PgSelectSingle101,List110,Lambda111 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression87,PgClassExpression88 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression102,PgClassExpression103 bucket9

