%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object14{{"Object[14∈0]<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access12{{"Access[12∈0]<br />ᐸ3.pgSettingsᐳ"}}:::plan
    Access13{{"Access[13∈0]<br />ᐸ3.withPgClientᐳ"}}:::plan
    Access12 & Access13 --> Object14
    PgSelect11[["PgSelect[11∈0]<br />ᐸforumsᐳ"]]:::plan
    Object14 --> PgSelect11
    __Value3["__Value[3∈0]<br />ᐸcontextᐳ"]:::plan
    __Value3 --> Access12
    __Value3 --> Access13
    __Value0["__Value[0∈0]"]:::plan
    __Value5["__Value[5∈0]<br />ᐸrootValueᐳ"]:::plan
    __Item15[/"__Item[15∈1]<br />ᐸ11ᐳ"\]:::itemplan
    PgSelect11 ==> __Item15
    PgSelectSingle16{{"PgSelectSingle[16∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item15 --> PgSelectSingle16
    PgClassExpression17{{"PgClassExpression[17∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle16 --> PgClassExpression17
    Access42{{"Access[42∈2]<br />ᐸ15.1ᐳ"}}:::plan
    __Item15 --> Access42
    __Item28[/"__Item[28∈3]<br />ᐸ42ᐳ"\]:::itemplan
    Access42 ==> __Item28
    PgSelectSingle29{{"PgSelectSingle[29∈3]<br />ᐸmessagesᐳ"}}:::plan
    __Item28 --> PgSelectSingle29
    PgClassExpression30{{"PgClassExpression[30∈4]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle29 --> PgClassExpression30
    PgSelectSingle37{{"PgSelectSingle[37∈4]<br />ᐸusersᐳ"}}:::plan
    RemapKeys40{{"RemapKeys[40∈4]<br />ᐸ29:{”0”:1,”1”:2}ᐳ"}}:::plan
    RemapKeys40 --> PgSelectSingle37
    PgSelectSingle29 --> RemapKeys40
    PgClassExpression38{{"PgClassExpression[38∈5]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression38
    PgClassExpression39{{"PgClassExpression[39∈5]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle37 --> PgClassExpression39

    %% define steps

    subgraph "Buckets for queries/conditions/basics-with-author"
    Bucket0("Bucket 0 (root)<br />1: <br />ᐳ: Access[12], Access[13], Object[14]<br />2: PgSelect[11]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value3,__Value5,PgSelect11,Access12,Access13,Object14 bucket0
    Bucket1("Bucket 1 (listItem)<br />ROOT __Item{1}ᐸ11ᐳ[15]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item15,PgSelectSingle16 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 16, 15<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[16]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression17,Access42 bucket2
    Bucket3("Bucket 3 (listItem)<br />ROOT __Item{3}ᐸ42ᐳ[28]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item28,PgSelectSingle29 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 29<br /><br />ROOT PgSelectSingle{3}ᐸmessagesᐳ[29]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression30,PgSelectSingle37,RemapKeys40 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 37<br /><br />ROOT PgSelectSingle{4}ᐸusersᐳ[37]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression38,PgClassExpression39 bucket5
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5
    end
