%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect12[["PgSelect[12∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object15{{"Object[15∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Lambda16[["Lambda[16∈0] ➊<br />ᐸincludeArchivedConditionᐳ"]]:::unbatchedplan
    ApplyInput17{{"ApplyInput[17∈0] ➊"}}:::plan
    Object15 & Constant6 & Lambda16 & ApplyInput17 --> PgSelect12
    Access13{{"Access[13∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access14{{"Access[14∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access13 & Access14 --> Object15
    __InputObject22{{"__InputObject[22∈0] ➊"}}:::plan
    Access23{{"Access[23∈0] ➊<br />ᐸ0.featuredᐳ"}}:::plan
    Access25{{"Access[25∈0] ➊<br />ᐸ0.isArchivedᐳ"}}:::plan
    Access23 & Access25 --> __InputObject22
    __InputObject8{{"__InputObject[8∈0] ➊"}}:::plan
    __InputObject9{{"__InputObject[9∈0] ➊"}}:::plan
    __InputObject9 --> __InputObject8
    Access10{{"Access[10∈0] ➊<br />ᐸ0.someᐳ"}}:::plan
    Access10 --> __InputObject9
    __Value0["__Value[0∈0] ➊<br />ᐸvariableValuesᐳ"]:::plan
    __Value0 --> Access10
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access13
    __Value2 --> Access14
    Constant41{{"Constant[41∈0] ➊<br />ᐸ'INHERIT'ᐳ"}}:::plan
    Constant41 --> Lambda16
    __InputObject8 --> ApplyInput17
    PgSelectRows18[["PgSelectRows[18∈0] ➊"]]:::plan
    PgSelect12 --> PgSelectRows18
    __Value0 --> Access23
    __Value0 --> Access25
    ApplyInput33{{"ApplyInput[33∈0] ➊"}}:::plan
    __InputObject22 --> ApplyInput33
    Lambda35[["Lambda[35∈0] ➊<br />ᐸincludeArchivedConditionᐳ"]]:::unbatchedplan
    Constant41 --> Lambda35
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item19[/"__Item[19∈1]<br />ᐸ18ᐳ"\]:::itemplan
    PgSelectRows18 ==> __Item19
    PgSelectSingle20{{"PgSelectSingle[20∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item19 --> PgSelectSingle20
    PgSelect29[["PgSelect[29∈2]<br />ᐸmessagesᐳ"]]:::plan
    PgClassExpression28{{"PgClassExpression[28∈2]<br />ᐸ__forums__.”id”ᐳ"}}:::plan
    PgClassExpression34{{"PgClassExpression[34∈2]<br />ᐸ__forums__...chived_at”ᐳ"}}:::plan
    Object15 & PgClassExpression28 & Constant6 & ApplyInput33 & PgClassExpression34 & Lambda35 --> PgSelect29
    PgClassExpression21{{"PgClassExpression[21∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle20 --> PgClassExpression21
    PgSelectSingle20 --> PgClassExpression28
    PgSelectSingle20 --> PgClassExpression34
    PgSelectRows36[["PgSelectRows[36∈2]"]]:::plan
    PgSelect29 --> PgSelectRows36
    __Item37[/"__Item[37∈3]<br />ᐸ36ᐳ"\]:::itemplan
    PgSelectRows36 ==> __Item37
    PgSelectSingle38{{"PgSelectSingle[38∈3]<br />ᐸmessagesᐳ"}}:::plan
    __Item37 --> PgSelectSingle38
    PgClassExpression39{{"PgClassExpression[39∈4]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle38 --> PgClassExpression39
    PgClassExpression40{{"PgClassExpression[40∈4]<br />ᐸ__messages__.”featured”ᐳ"}}:::plan
    PgSelectSingle38 --> PgClassExpression40

    %% define steps

    subgraph "Buckets for queries/conditions/complex-filter-via-partial-variables"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 10, 13, 14, 23, 25, 41, 9, 15, 22, 33, 8, 17<br />2: Lambda[16], Lambda[35]<br />3: PgSelect[12]<br />4: PgSelectRows[18]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value0,__Value2,__Value4,Constant6,__InputObject8,__InputObject9,Access10,PgSelect12,Access13,Access14,Object15,Lambda16,ApplyInput17,PgSelectRows18,__InputObject22,Access23,Access25,ApplyInput33,Lambda35,Constant41 bucket0
    Bucket1("Bucket 1 (listItem)<br />Deps: 15, 6, 33, 35<br /><br />ROOT __Item{1}ᐸ18ᐳ[19]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item19,PgSelectSingle20 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 20, 15, 6, 33, 35<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[20]<br />1: <br />ᐳ: 21, 28, 34<br />2: PgSelect[29]<br />3: PgSelectRows[36]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression21,PgClassExpression28,PgSelect29,PgClassExpression34,PgSelectRows36 bucket2
    Bucket3("Bucket 3 (listItem)<br /><br />ROOT __Item{3}ᐸ36ᐳ[37]"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,__Item37,PgSelectSingle38 bucket3
    Bucket4("Bucket 4 (nullableBoundary)<br />Deps: 38<br /><br />ROOT PgSelectSingle{3}ᐸmessagesᐳ[38]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,PgClassExpression39,PgClassExpression40 bucket4
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    end
