%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left

    subgraph "Buckets for queries/conditions/condition-featured-messages"
    Bucket0("Bucket 0 (root)<br /><br />1: 86, 90<br />ᐳ: 9, 10, 102, 103, 104, 106, 11, 13, 20, 29, 33<br />2: 94, 98<br />3: PgSelect[8]<br />ᐳ: Access[95], Access[99]<br />4: PgSelectRows[14]"):::bucket
    Bucket1("Bucket 1 (listItem)<br />Deps: 103, 95, 99<br /><br />ROOT __Item{1}ᐸ14ᐳ[16]"):::bucket
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 17, 103, 95, 16, 99<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[17]<br />1: <br />ᐳ: 18, 96, 100, 97, 101<br />2: Connection[28]"):::bucket
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 28, 101, 97<br /><br />ROOT Connection{2}ᐸ97ᐳ[28]<br />1: ConnectionItems[34]<br />ᐳ: 39, 41, 55, 87, 91<br />2: 42, 45, 46, 53, 57<br />ᐳ: 43, 44, 54, 56, 58, 59"):::bucket
    Bucket6("Bucket 6 (listItem)<br />Deps: 87<br /><br />ROOT __Item{6}ᐸ45ᐳ[47]"):::bucket
    Bucket7("Bucket 7 (listItem)<br />Deps: 55, 91<br /><br />ROOT __Item{7}ᐸ46ᐳ[49]"):::bucket
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 48, 87<br /><br />ROOT PgSelectSingle{6}ᐸmessagesᐳ[48]<br />1: <br />ᐳ: 60, 88, 89, 69<br />2: First[70]<br />ᐳ: PgSelectSingle[71]"):::bucket
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 49, 55, 50, 91<br /><br />ROOT Edge{7}[50]"):::bucket
    Bucket10("Bucket 10 (nullableBoundary)<br />Deps: 71<br /><br />ROOT PgSelectSingle{8}ᐸusersᐳ[71]"):::bucket
    Bucket11("Bucket 11 (nullableBoundary)<br />Deps: 61, 91<br /><br />ROOT PgSelectSingle{9}ᐸmessagesᐳ[61]<br />1: <br />ᐳ: 74, 92, 93, 81<br />2: First[82]<br />ᐳ: PgSelectSingle[83]"):::bucket
    Bucket12("Bucket 12 (nullableBoundary)<br />Deps: 83<br /><br />ROOT PgSelectSingle{11}ᐸusersᐳ[83]"):::bucket
    end
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket6 & Bucket7
    Bucket6 --> Bucket8
    Bucket7 --> Bucket9
    Bucket8 --> Bucket10
    Bucket9 --> Bucket11
    Bucket11 --> Bucket12

    %% plan dependencies
    PgSelectInlineApply94["PgSelectInlineApply[94∈0] ➊<br />More deps:<br />- Constantᐸ5ᐳ[103]"]:::plan
    ApplyInput29{{"ApplyInput[29∈0] ➊"}}:::plan
    Lambda33{{"Lambda[33∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[HIDDEN]ᐳ[106]"}}:::plan
    PgSelectInlineApply86["PgSelectInlineApply[86∈0] ➊"]:::plan
    PgSelectInlineApply90["PgSelectInlineApply[90∈0] ➊"]:::plan
    ApplyInput29 & Lambda33 & PgSelectInlineApply86 & PgSelectInlineApply90 --> PgSelectInlineApply94
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Lambda13{{"Lambda[13∈0] ➊<br />ᐸincludeArchivedConditionᐳ<br />More deps:<br />- Constantᐸ[ undefined, 'INHERIT' ]ᐳ[102]"}}:::plan
    PgSelectInlineApply98["PgSelectInlineApply[98∈0] ➊"]:::plan
    Object11 & Lambda13 & PgSelectInlineApply94 & PgSelectInlineApply98 --> PgSelect8
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    ApplyInput29 & Lambda33 --> PgSelectInlineApply98
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    PgSelectRows14[["PgSelectRows[14∈0] ➊"]]:::plan
    PgSelect8 --> PgSelectRows14
    __InputObject20{{"__InputObject[20∈0] ➊<br />More deps:<br />- Constantᐸtrueᐳ[104]"}}:::plan
    __InputObject20 --> ApplyInput29
    Access95{{"Access[95∈0] ➊<br />ᐸ8.m.subqueryDetailsFor24ᐳ"}}:::plan
    PgSelect8 --> Access95
    Access99{{"Access[99∈0] ➊<br />ᐸ8.m.subqueryDetailsFor40ᐳ"}}:::plan
    PgSelect8 --> Access99
    __Item16[/"__Item[16∈1]<br />ᐸ14ᐳ"\]:::itemplan
    PgSelectRows14 ==> __Item16
    PgSelectSingle17{{"PgSelectSingle[17∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item16 --> PgSelectSingle17
    Connection28[["Connection[28∈2]<br />ᐸ97ᐳ<br />More deps:<br />- Constantᐸ5ᐳ[103]"]]:::plan
    Lambda97{{"Lambda[97∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    Lambda97 --> Connection28
    List96{{"List[96∈2]<br />ᐸ95,16ᐳ"}}:::plan
    Access95 & __Item16 --> List96
    List100{{"List[100∈2]<br />ᐸ99,16ᐳ"}}:::plan
    Access99 & __Item16 --> List100
    PgClassExpression18{{"PgClassExpression[18∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression18
    List96 --> Lambda97
    Lambda101{{"Lambda[101∈2]<br />ᐸpgInlineViaSubqueryTransformᐳ"}}:::plan
    List100 --> Lambda101
    PgCursor56{{"PgCursor[56∈3]"}}:::plan
    PgSelectSingle54{{"PgSelectSingle[54∈3]<br />ᐸmessagesᐳ"}}:::plan
    Access55{{"Access[55∈3]<br />ᐸ97.cursorDetailsᐳ"}}:::plan
    PgSelectSingle54 & Access55 --> PgCursor56
    PgCursor59{{"PgCursor[59∈3]"}}:::plan
    PgSelectSingle58{{"PgSelectSingle[58∈3]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle58 & Access55 --> PgCursor59
    ConnectionItems34[["ConnectionItems[34∈3]"]]:::plan
    Connection28 --> ConnectionItems34
    PageInfo39{{"PageInfo[39∈3]"}}:::plan
    Connection28 --> PageInfo39
    Access41{{"Access[41∈3]<br />ᐸ101.itemsᐳ"}}:::plan
    Lambda101 --> Access41
    First42[["First[42∈3]"]]:::plan
    Access41 --> First42
    PgSelectSingle43{{"PgSelectSingle[43∈3]<br />ᐸmessagesᐳ"}}:::plan
    First42 --> PgSelectSingle43
    PgClassExpression44{{"PgClassExpression[44∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression44
    __CloneStream45[["__CloneStream[45∈3]"]]:::plan
    ConnectionItems34 --> __CloneStream45
    __CloneStream46[["__CloneStream[46∈3]"]]:::plan
    ConnectionItems34 --> __CloneStream46
    First53[["First[53∈3]"]]:::plan
    ConnectionItems34 --> First53
    First53 --> PgSelectSingle54
    Lambda97 --> Access55
    Last57[["Last[57∈3]"]]:::plan
    ConnectionItems34 --> Last57
    Last57 --> PgSelectSingle58
    Access87{{"Access[87∈3]<br />ᐸ97.m.joinDetailsFor65ᐳ"}}:::plan
    Lambda97 --> Access87
    Access91{{"Access[91∈3]<br />ᐸ97.m.joinDetailsFor77ᐳ"}}:::plan
    Lambda97 --> Access91
    __Item47[/"__Item[47∈6]<br />ᐸ45ᐳ"\]:::itemplan
    __CloneStream45 ==> __Item47
    PgSelectSingle48{{"PgSelectSingle[48∈6]<br />ᐸmessagesᐳ"}}:::plan
    __Item47 --> PgSelectSingle48
    __Item49[/"__Item[49∈7]<br />ᐸ46ᐳ"\]:::itemplan
    __CloneStream46 ==> __Item49
    Edge50{{"Edge[50∈7]"}}:::plan
    __Item49 --> Edge50
    List88{{"List[88∈8]<br />ᐸ87,48ᐳ"}}:::plan
    Access87 & PgSelectSingle48 --> List88
    PgClassExpression60{{"PgClassExpression[60∈8]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle48 --> PgClassExpression60
    Access69{{"Access[69∈8]<br />ᐸ89.itemsᐳ"}}:::plan
    Lambda89{{"Lambda[89∈8]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda89 --> Access69
    First70[["First[70∈8]"]]:::plan
    Access69 --> First70
    PgSelectSingle71{{"PgSelectSingle[71∈8]<br />ᐸusersᐳ"}}:::plan
    First70 --> PgSelectSingle71
    List88 --> Lambda89
    PgCursor63{{"PgCursor[63∈9]"}}:::plan
    PgSelectSingle61{{"PgSelectSingle[61∈9]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle61 & Access55 --> PgCursor63
    __Item49 --> PgSelectSingle61
    PgClassExpression73{{"PgClassExpression[73∈10]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression73
    PgClassExpression75{{"PgClassExpression[75∈10]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle71 --> PgClassExpression75
    List92{{"List[92∈11]<br />ᐸ91,61ᐳ"}}:::plan
    Access91 & PgSelectSingle61 --> List92
    PgClassExpression74{{"PgClassExpression[74∈11]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle61 --> PgClassExpression74
    Access81{{"Access[81∈11]<br />ᐸ93.itemsᐳ"}}:::plan
    Lambda93{{"Lambda[93∈11]<br />ᐸpgInlineViaJoinTransformᐳ"}}:::plan
    Lambda93 --> Access81
    First82[["First[82∈11]"]]:::plan
    Access81 --> First82
    PgSelectSingle83{{"PgSelectSingle[83∈11]<br />ᐸusersᐳ"}}:::plan
    First82 --> PgSelectSingle83
    List92 --> Lambda93
    PgClassExpression84{{"PgClassExpression[84∈12]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle83 --> PgClassExpression84
    PgClassExpression85{{"PgClassExpression[85∈12]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle83 --> PgClassExpression85

    %% define steps
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,PgSelect8,Access9,Access10,Object11,Lambda13,PgSelectRows14,__InputObject20,ApplyInput29,Lambda33,PgSelectInlineApply86,PgSelectInlineApply90,PgSelectInlineApply94,Access95,PgSelectInlineApply98,Access99 bucket0
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item16,PgSelectSingle17 bucket1
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression18,Connection28,List96,Lambda97,List100,Lambda101 bucket2
    classDef bucket3 stroke:#ffa500
    class Bucket3,ConnectionItems34,PageInfo39,Access41,First42,PgSelectSingle43,PgClassExpression44,__CloneStream45,__CloneStream46,First53,PgSelectSingle54,Access55,PgCursor56,Last57,PgSelectSingle58,PgCursor59,Access87,Access91 bucket3
    classDef bucket6 stroke:#ff1493
    class Bucket6,__Item47,PgSelectSingle48 bucket6
    classDef bucket7 stroke:#808000
    class Bucket7,__Item49,Edge50 bucket7
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression60,Access69,First70,PgSelectSingle71,List88,Lambda89 bucket8
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgSelectSingle61,PgCursor63 bucket9
    classDef bucket10 stroke:#ffff00
    class Bucket10,PgClassExpression73,PgClassExpression75 bucket10
    classDef bucket11 stroke:#00ffff
    class Bucket11,PgClassExpression74,Access81,First82,PgSelectSingle83,List92,Lambda93 bucket11
    classDef bucket12 stroke:#4169e1
    class Bucket12,PgClassExpression84,PgClassExpression85 bucket12

