%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object11 --> PgSelect8
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    PgSelectRows12[["PgSelectRows[12∈0] ➊"]]:::plan
    PgSelect8 --> PgSelectRows12
    Connection25{{"Connection[25∈0] ➊<br />ᐸ21ᐳ"}}:::plan
    Constant87{{"Constant[87∈0] ➊<br />ᐸ5ᐳ"}}:::plan
    Constant87 --> Connection25
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Constant88{{"Constant[88∈0] ➊<br />ᐸtrueᐳ"}}:::plan
    __Item13[/"__Item[13∈1]<br />ᐸ12ᐳ"\]:::itemplan
    PgSelectRows12 ==> __Item13
    PgSelectSingle14{{"PgSelectSingle[14∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item13 --> PgSelectSingle14
    PgClassExpression15{{"PgClassExpression[15∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle14 --> PgClassExpression15
    PgSelect27[["PgSelect[27∈3]<br />ᐸmessages+1ᐳ"]]:::plan
    PgClassExpression20{{"PgClassExpression[20∈3]<br />ᐸ__forums__.”id”ᐳ"}}:::plan
    PgClassExpression26{{"PgClassExpression[26∈3]<br />ᐸ__forums__...chived_at”ᐳ"}}:::plan
    Object11 & PgClassExpression20 & Constant88 & PgClassExpression26 & Connection25 & Constant87 --> PgSelect27
    PgSelect82[["PgSelect[82∈3]<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object11 & PgClassExpression20 & Constant88 & PgClassExpression26 & Connection25 --> PgSelect82
    Object68{{"Object[68∈3]<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access63{{"Access[63∈3]<br />ᐸ27.hasMoreᐳ"}}:::plan
    Constant87 & Constant6 & Constant6 & Access63 --> Object68
    Object64{{"Object[64∈3]<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant87 & Constant6 & Access63 --> Object64
    PgCursor75{{"PgCursor[75∈3]"}}:::plan
    PgSelectSingle73{{"PgSelectSingle[73∈3]<br />ᐸmessagesᐳ"}}:::plan
    Access46{{"Access[46∈3]<br />ᐸ27.cursorDetailsᐳ"}}:::plan
    PgSelectSingle73 & Access46 --> PgCursor75
    PgCursor81{{"PgCursor[81∈3]"}}:::plan
    PgSelectSingle79{{"PgSelectSingle[79∈3]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle79 & Access46 --> PgCursor81
    PgSelectSingle14 --> PgClassExpression20
    PgSelectSingle14 --> PgClassExpression26
    PgSelectRows28[["PgSelectRows[28∈3]"]]:::plan
    PgSelect27 --> PgSelectRows28
    PgSelectRows43[["PgSelectRows[43∈3]"]]:::plan
    PgSelect27 --> PgSelectRows43
    PgSelect27 --> Access46
    PgPageInfo60{{"PgPageInfo[60∈3] ➊"}}:::plan
    Connection25 --> PgPageInfo60
    PgSelect27 --> Access63
    Lambda65{{"Lambda[65∈3]<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object64 --> Lambda65
    Lambda69{{"Lambda[69∈3]<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object68 --> Lambda69
    First71{{"First[71∈3]"}}:::plan
    PgSelectRows72[["PgSelectRows[72∈3]"]]:::plan
    PgSelectRows72 --> First71
    PgSelect27 --> PgSelectRows72
    First71 --> PgSelectSingle73
    Last77{{"Last[77∈3]"}}:::plan
    PgSelectRows78[["PgSelectRows[78∈3]"]]:::plan
    PgSelectRows78 --> Last77
    PgSelect27 --> PgSelectRows78
    Last77 --> PgSelectSingle79
    First83{{"First[83∈3]"}}:::plan
    PgSelectRows84[["PgSelectRows[84∈3]"]]:::plan
    PgSelectRows84 --> First83
    PgSelect82 --> PgSelectRows84
    PgSelectSingle85{{"PgSelectSingle[85∈3]<br />ᐸmessagesᐳ"}}:::plan
    First83 --> PgSelectSingle85
    PgClassExpression86{{"PgClassExpression[86∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle85 --> PgClassExpression86
    __Item29[/"__Item[29∈4]<br />ᐸ28ᐳ"\]:::itemplan
    PgSelectRows28 ==> __Item29
    PgSelectSingle30{{"PgSelectSingle[30∈4]<br />ᐸmessagesᐳ"}}:::plan
    __Item29 --> PgSelectSingle30
    PgSelect33[["PgSelect[33∈5]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression32{{"PgClassExpression[32∈5]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object11 & PgClassExpression32 --> PgSelect33
    PgClassExpression31{{"PgClassExpression[31∈5]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle30 --> PgClassExpression31
    PgSelectSingle30 --> PgClassExpression32
    First37{{"First[37∈5]"}}:::plan
    PgSelectRows38[["PgSelectRows[38∈5]"]]:::plan
    PgSelectRows38 --> First37
    PgSelect33 --> PgSelectRows38
    PgSelectSingle39{{"PgSelectSingle[39∈5]<br />ᐸusersᐳ"}}:::plan
    First37 --> PgSelectSingle39
    PgClassExpression40{{"PgClassExpression[40∈6]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression40
    PgClassExpression41{{"PgClassExpression[41∈6]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle39 --> PgClassExpression41
    __Item44[/"__Item[44∈7]<br />ᐸ43ᐳ"\]:::itemplan
    PgSelectRows43 ==> __Item44
    PgSelectSingle45{{"PgSelectSingle[45∈7]<br />ᐸmessagesᐳ"}}:::plan
    __Item44 --> PgSelectSingle45
    PgCursor47{{"PgCursor[47∈8]"}}:::plan
    PgSelectSingle45 & Access46 --> PgCursor47
    PgSelect50[["PgSelect[50∈8]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression49{{"PgClassExpression[49∈8]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object11 & PgClassExpression49 --> PgSelect50
    PgClassExpression48{{"PgClassExpression[48∈8]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle45 --> PgClassExpression48
    PgSelectSingle45 --> PgClassExpression49
    First54{{"First[54∈8]"}}:::plan
    PgSelectRows55[["PgSelectRows[55∈8]"]]:::plan
    PgSelectRows55 --> First54
    PgSelect50 --> PgSelectRows55
    PgSelectSingle56{{"PgSelectSingle[56∈8]<br />ᐸusersᐳ"}}:::plan
    First54 --> PgSelectSingle56
    PgClassExpression57{{"PgClassExpression[57∈9]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression57
    PgClassExpression58{{"PgClassExpression[58∈9]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle56 --> PgClassExpression58

    %% define steps

    subgraph "Buckets for queries/conditions/condition-featured-messages"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 9, 10, 87, 88, 11, 25<br />2: PgSelect[8]<br />3: PgSelectRows[12]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,PgSelect8,Access9,Access10,Object11,PgSelectRows12,Connection25,Constant87,Constant88 bucket0
    Bucket1("Bucket 1 (listItem)<br />Deps: 11, 88, 25, 87, 6<br /><br />ROOT __Item{1}ᐸ12ᐳ[13]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item13,PgSelectSingle14 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 14, 11, 88, 25, 87, 6<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[14]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression15 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 14, 11, 88, 25, 87, 6<br /><br />ROOT Connectionᐸ21ᐳ[25]<br />1: <br />ᐳ: 20, 26, 60<br />2: PgSelect[27], PgSelect[82]<br />ᐳ: 46, 63, 64, 65, 68, 69<br />3: 28, 43, 72, 78, 84<br />ᐳ: 71, 73, 75, 77, 79, 81, 83, 85, 86"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression20,PgClassExpression26,PgSelect27,PgSelectRows28,PgSelectRows43,Access46,PgPageInfo60,Access63,Object64,Lambda65,Object68,Lambda69,First71,PgSelectRows72,PgSelectSingle73,PgCursor75,Last77,PgSelectRows78,PgSelectSingle79,PgCursor81,PgSelect82,First83,PgSelectRows84,PgSelectSingle85,PgClassExpression86 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 11<br /><br />ROOT __Item{4}ᐸ28ᐳ[29]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item29,PgSelectSingle30 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 30, 11<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[30]<br />1: <br />ᐳ: 31, 32<br />2: PgSelect[33]<br />3: PgSelectRows[38]<br />ᐳ: First[37], PgSelectSingle[39]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression31,PgClassExpression32,PgSelect33,First37,PgSelectRows38,PgSelectSingle39 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 39<br /><br />ROOT PgSelectSingle{5}ᐸusersᐳ[39]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression40,PgClassExpression41 bucket6
    Bucket7("Bucket 7 (listItem)<br />Deps: 46, 11<br /><br />ROOT __Item{7}ᐸ43ᐳ[44]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,__Item44,PgSelectSingle45 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 45, 46, 11<br /><br />ROOT PgSelectSingle{7}ᐸmessagesᐳ[45]<br />1: <br />ᐳ: 47, 48, 49<br />2: PgSelect[50]<br />3: PgSelectRows[55]<br />ᐳ: First[54], PgSelectSingle[56]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgCursor47,PgClassExpression48,PgClassExpression49,PgSelect50,First54,PgSelectRows55,PgSelectSingle56 bucket8
    Bucket9("Bucket 9 (nullableBoundary)<br />Deps: 56<br /><br />ROOT PgSelectSingle{8}ᐸusersᐳ[56]"):::bucket
    classDef bucket9 stroke:#ff0000
    class Bucket9,PgClassExpression57,PgClassExpression58 bucket9
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4 & Bucket7
    Bucket4 --> Bucket5
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    Bucket8 --> Bucket9
    end
