%%{init: {'themeVariables': { 'fontSize': '12px'}}}%%
graph TD
    classDef path fill:#eee,stroke:#000,color:#000
    classDef plan fill:#fff,stroke-width:1px,color:#000
    classDef itemplan fill:#fff,stroke-width:2px,color:#000
    classDef unbatchedplan fill:#dff,stroke-width:1px,color:#000
    classDef sideeffectplan fill:#fcc,stroke-width:2px,color:#000
    classDef bucket fill:#f6f6f6,color:#000,stroke-width:2px,text-align:left


    %% plan dependencies
    PgSelect8[["PgSelect[8∈0] ➊<br />ᐸforumsᐳ"]]:::plan
    Object11{{"Object[11∈0] ➊<br />ᐸ{pgSettings,withPgClient}ᐳ"}}:::plan
    Constant6{{"Constant[6∈0] ➊<br />ᐸundefinedᐳ"}}:::plan
    Lambda12[["Lambda[12∈0] ➊<br />ᐸincludeArchivedConditionᐳ"]]:::unbatchedplan
    ApplyInput13{{"ApplyInput[13∈0] ➊"}}:::plan
    ApplyInput14{{"ApplyInput[14∈0] ➊"}}:::plan
    Object11 & Constant6 & Lambda12 & ApplyInput13 & ApplyInput14 --> PgSelect8
    Access9{{"Access[9∈0] ➊<br />ᐸ2.pgSettingsᐳ"}}:::plan
    Access10{{"Access[10∈0] ➊<br />ᐸ2.withPgClientᐳ"}}:::plan
    Access9 & Access10 --> Object11
    Connection26{{"Connection[26∈0] ➊<br />ᐸ22ᐳ"}}:::plan
    Constant90{{"Constant[90∈0] ➊<br />ᐸ5ᐳ"}}:::plan
    Constant90 & Constant6 --> Connection26
    __Value2["__Value[2∈0] ➊<br />ᐸcontextᐳ"]:::plan
    __Value2 --> Access9
    __Value2 --> Access10
    Constant89{{"Constant[89∈0] ➊<br />ᐸ'YES'ᐳ"}}:::plan
    Constant89 --> Lambda12
    Constant6 --> ApplyInput13
    Constant6 --> ApplyInput14
    PgSelectRows15[["PgSelectRows[15∈0] ➊"]]:::plan
    PgSelect8 --> PgSelectRows15
    ApplyInput27{{"ApplyInput[27∈0] ➊"}}:::plan
    Constant6 --> ApplyInput27
    ApplyInput28{{"ApplyInput[28∈0] ➊"}}:::plan
    Constant6 --> ApplyInput28
    Lambda30[["Lambda[30∈0] ➊<br />ᐸincludeArchivedConditionᐳ"]]:::unbatchedplan
    Constant91{{"Constant[91∈0] ➊<br />ᐸ'EXCLUSIVELY'ᐳ"}}:::plan
    Constant91 --> Lambda30
    __Value4["__Value[4∈0] ➊<br />ᐸrootValueᐳ"]:::plan
    __Item16[/"__Item[16∈1]<br />ᐸ15ᐳ"\]:::itemplan
    PgSelectRows15 ==> __Item16
    PgSelectSingle17{{"PgSelectSingle[17∈1]<br />ᐸforumsᐳ"}}:::plan
    __Item16 --> PgSelectSingle17
    PgClassExpression18{{"PgClassExpression[18∈2]<br />ᐸ__forums__.”name”ᐳ"}}:::plan
    PgSelectSingle17 --> PgClassExpression18
    PgSelect31[["PgSelect[31∈3]<br />ᐸmessages+1ᐳ"]]:::plan
    PgClassExpression21{{"PgClassExpression[21∈3]<br />ᐸ__forums__.”id”ᐳ"}}:::plan
    PgClassExpression29{{"PgClassExpression[29∈3]<br />ᐸ__forums__...chived_at”ᐳ"}}:::plan
    Object11 & PgClassExpression21 & ApplyInput27 & ApplyInput28 & PgClassExpression29 & Lambda30 & Connection26 & Constant90 & Constant6 --> PgSelect31
    PgSelect84[["PgSelect[84∈3]<br />ᐸmessages(aggregate)ᐳ"]]:::plan
    Object11 & PgClassExpression21 & ApplyInput27 & ApplyInput28 & PgClassExpression29 & Lambda30 & Connection26 --> PgSelect84
    Object70{{"Object[70∈3]<br />ᐸ{first,last,offset,hasMore}ᐳ"}}:::plan
    Access64{{"Access[64∈3]<br />ᐸ31.hasMoreᐳ"}}:::plan
    Constant90 & Constant6 & Constant6 & Access64 --> Object70
    Object65{{"Object[65∈3]<br />ᐸ{first,last,hasMore}ᐳ"}}:::plan
    Constant90 & Constant6 & Access64 --> Object65
    PgCursor77{{"PgCursor[77∈3]"}}:::plan
    PgSelectSingle75{{"PgSelectSingle[75∈3]<br />ᐸmessagesᐳ"}}:::plan
    Access48{{"Access[48∈3]<br />ᐸ31.cursorDetailsᐳ"}}:::plan
    PgSelectSingle75 & Access48 --> PgCursor77
    PgCursor83{{"PgCursor[83∈3]"}}:::plan
    PgSelectSingle81{{"PgSelectSingle[81∈3]<br />ᐸmessagesᐳ"}}:::plan
    PgSelectSingle81 & Access48 --> PgCursor83
    PgSelectSingle17 --> PgClassExpression21
    PgSelectSingle17 --> PgClassExpression29
    PgSelectRows32[["PgSelectRows[32∈3]"]]:::plan
    PgSelect31 --> PgSelectRows32
    PgSelect31 --> Access48
    PgPageInfo62{{"PgPageInfo[62∈3] ➊"}}:::plan
    Connection26 --> PgPageInfo62
    PgSelect31 --> Access64
    Lambda66{{"Lambda[66∈3]<br />ᐸhasNextPageCbᐳ"}}:::plan
    Object65 --> Lambda66
    Lambda71{{"Lambda[71∈3]<br />ᐸhasPreviousPageCbᐳ"}}:::plan
    Object70 --> Lambda71
    First73{{"First[73∈3]"}}:::plan
    PgSelectRows32 --> First73
    First73 --> PgSelectSingle75
    Last79{{"Last[79∈3]"}}:::plan
    PgSelectRows32 --> Last79
    Last79 --> PgSelectSingle81
    First85{{"First[85∈3]"}}:::plan
    PgSelectRows86[["PgSelectRows[86∈3]"]]:::plan
    PgSelectRows86 --> First85
    PgSelect84 --> PgSelectRows86
    PgSelectSingle87{{"PgSelectSingle[87∈3]<br />ᐸmessagesᐳ"}}:::plan
    First85 --> PgSelectSingle87
    PgClassExpression88{{"PgClassExpression[88∈3]<br />ᐸcount(*)ᐳ"}}:::plan
    PgSelectSingle87 --> PgClassExpression88
    __Item33[/"__Item[33∈4]<br />ᐸ32ᐳ"\]:::itemplan
    PgSelectRows32 ==> __Item33
    PgSelectSingle34{{"PgSelectSingle[34∈4]<br />ᐸmessagesᐳ"}}:::plan
    __Item33 --> PgSelectSingle34
    PgSelect37[["PgSelect[37∈5]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression36{{"PgClassExpression[36∈5]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object11 & PgClassExpression36 --> PgSelect37
    PgClassExpression35{{"PgClassExpression[35∈5]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression35
    PgSelectSingle34 --> PgClassExpression36
    First41{{"First[41∈5]"}}:::plan
    PgSelectRows42[["PgSelectRows[42∈5]"]]:::plan
    PgSelectRows42 --> First41
    PgSelect37 --> PgSelectRows42
    PgSelectSingle43{{"PgSelectSingle[43∈5]<br />ᐸusersᐳ"}}:::plan
    First41 --> PgSelectSingle43
    PgClassExpression44{{"PgClassExpression[44∈6]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression44
    PgClassExpression45{{"PgClassExpression[45∈6]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle43 --> PgClassExpression45
    PgCursor49{{"PgCursor[49∈7]"}}:::plan
    PgSelectSingle34 & Access48 --> PgCursor49
    PgSelect52[["PgSelect[52∈7]<br />ᐸusersᐳ"]]:::plan
    PgClassExpression51{{"PgClassExpression[51∈7]<br />ᐸ__messages...author_id”ᐳ"}}:::plan
    Object11 & PgClassExpression51 --> PgSelect52
    PgClassExpression50{{"PgClassExpression[50∈7]<br />ᐸ__messages__.”body”ᐳ"}}:::plan
    PgSelectSingle34 --> PgClassExpression50
    PgSelectSingle34 --> PgClassExpression51
    First56{{"First[56∈7]"}}:::plan
    PgSelectRows57[["PgSelectRows[57∈7]"]]:::plan
    PgSelectRows57 --> First56
    PgSelect52 --> PgSelectRows57
    PgSelectSingle58{{"PgSelectSingle[58∈7]<br />ᐸusersᐳ"}}:::plan
    First56 --> PgSelectSingle58
    PgClassExpression59{{"PgClassExpression[59∈8]<br />ᐸ__users__.”username”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression59
    PgClassExpression60{{"PgClassExpression[60∈8]<br />ᐸ__users__....vatar_url”ᐳ"}}:::plan
    PgSelectSingle58 --> PgClassExpression60

    %% define steps

    subgraph "Buckets for queries/conditions/exclusively-archived-messages"
    Bucket0("Bucket 0 (root)<br /><br />1: <br />ᐳ: 6, 9, 10, 89, 90, 91, 11, 13, 14, 26, 27, 28<br />2: Lambda[12], Lambda[30]<br />3: PgSelect[8]<br />4: PgSelectRows[15]"):::bucket
    classDef bucket0 stroke:#696969
    class Bucket0,__Value2,__Value4,Constant6,PgSelect8,Access9,Access10,Object11,Lambda12,ApplyInput13,ApplyInput14,PgSelectRows15,Connection26,ApplyInput27,ApplyInput28,Lambda30,Constant89,Constant90,Constant91 bucket0
    Bucket1("Bucket 1 (listItem)<br />Deps: 11, 27, 28, 30, 26, 90, 6<br /><br />ROOT __Item{1}ᐸ15ᐳ[16]"):::bucket
    classDef bucket1 stroke:#00bfff
    class Bucket1,__Item16,PgSelectSingle17 bucket1
    Bucket2("Bucket 2 (nullableBoundary)<br />Deps: 17, 11, 27, 28, 30, 26, 90, 6<br /><br />ROOT PgSelectSingle{1}ᐸforumsᐳ[17]"):::bucket
    classDef bucket2 stroke:#7f007f
    class Bucket2,PgClassExpression18 bucket2
    Bucket3("Bucket 3 (nullableBoundary)<br />Deps: 17, 11, 27, 28, 30, 26, 90, 6<br /><br />ROOT Connectionᐸ22ᐳ[26]<br />1: <br />ᐳ: 21, 29, 62<br />2: PgSelect[31], PgSelect[84]<br />ᐳ: 48, 64, 65, 66, 70, 71<br />3: PgSelectRows[32], PgSelectRows[86]<br />ᐳ: 73, 75, 77, 79, 81, 83, 85, 87, 88"):::bucket
    classDef bucket3 stroke:#ffa500
    class Bucket3,PgClassExpression21,PgClassExpression29,PgSelect31,PgSelectRows32,Access48,PgPageInfo62,Access64,Object65,Lambda66,Object70,Lambda71,First73,PgSelectSingle75,PgCursor77,Last79,PgSelectSingle81,PgCursor83,PgSelect84,First85,PgSelectRows86,PgSelectSingle87,PgClassExpression88 bucket3
    Bucket4("Bucket 4 (listItem)<br />Deps: 11, 48<br /><br />ROOT __Item{4}ᐸ32ᐳ[33]"):::bucket
    classDef bucket4 stroke:#0000ff
    class Bucket4,__Item33,PgSelectSingle34 bucket4
    Bucket5("Bucket 5 (nullableBoundary)<br />Deps: 34, 11<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[34]<br />1: <br />ᐳ: 35, 36<br />2: PgSelect[37]<br />3: PgSelectRows[42]<br />ᐳ: First[41], PgSelectSingle[43]"):::bucket
    classDef bucket5 stroke:#7fff00
    class Bucket5,PgClassExpression35,PgClassExpression36,PgSelect37,First41,PgSelectRows42,PgSelectSingle43 bucket5
    Bucket6("Bucket 6 (nullableBoundary)<br />Deps: 43<br /><br />ROOT PgSelectSingle{5}ᐸusersᐳ[43]"):::bucket
    classDef bucket6 stroke:#ff1493
    class Bucket6,PgClassExpression44,PgClassExpression45 bucket6
    Bucket7("Bucket 7 (nullableBoundary)<br />Deps: 34, 48, 11<br /><br />ROOT PgSelectSingle{4}ᐸmessagesᐳ[34]<br />1: <br />ᐳ: 49, 50, 51<br />2: PgSelect[52]<br />3: PgSelectRows[57]<br />ᐳ: First[56], PgSelectSingle[58]"):::bucket
    classDef bucket7 stroke:#808000
    class Bucket7,PgCursor49,PgClassExpression50,PgClassExpression51,PgSelect52,First56,PgSelectRows57,PgSelectSingle58 bucket7
    Bucket8("Bucket 8 (nullableBoundary)<br />Deps: 58<br /><br />ROOT PgSelectSingle{7}ᐸusersᐳ[58]"):::bucket
    classDef bucket8 stroke:#dda0dd
    class Bucket8,PgClassExpression59,PgClassExpression60 bucket8
    Bucket0 --> Bucket1
    Bucket1 --> Bucket2
    Bucket2 --> Bucket3
    Bucket3 --> Bucket4
    Bucket4 --> Bucket5 & Bucket7
    Bucket5 --> Bucket6
    Bucket7 --> Bucket8
    end
