import { exportAsMany } from "grafast";

import {
  domainOfCodec,
  enumCodec,
  getCodecByPgCatalogTypeName,
  getInnerCodec,
  isEnumCodec,
  listOfCodec,
  ObjectFromPgCodecAttributes,
  PgCodecAttribute,
  PgCodecAttributeExtensions,
  PgCodecAttributeVia,
  PgCodecAttributeViaExplicit,
  PgEnumCodecSpec,
  PgRecordTypeCodecSpec,
  rangeOfCodec,
  recordCodec,
  TYPES,
  _AnyPgCodecAttribute,
  DefaultPgCodecAttribute,
  DefaultPgCodecAttributeVia,
  _AnyPgCodecAttributeVia,
  _AnyPgCodecAttributeViaAttribute,
  _AnyPgCodecAttributeViaRelationName,
} from "./codecs.js";
import {
  PgBox,
  PgCircle,
  PgHStore,
  PgInterval,
  PgLine,
  PgLseg,
  PgPath,
  PgPoint,
  PgPolygon,
} from "./codecUtils/index.js";
import {
  makePgResourceOptions,
  makeRegistry,
  makeRegistryBuilder,
  PgCodecRef,
  PgCodecRefExtensions,
  PgCodecRefPath,
  PgCodecRefPathEntry,
  PgCodecRefs,
  PgFunctionResourceOptions,
  PgRegistryBuilder,
  PgResource,
  PgResourceExtensions,
  PgResourceOptions,
  PgResourceParameter,
  PgResourceUnique,
  PgResourceUniqueExtensions,
  _AnyPgRegistryBuilder,
  _AnyPgResource,
  _AnyPgResourceOptions,
  _AnyPgResourceParameter,
  _AnyPgResourceUnique,
  _AnyScalarPgResource,
  DefaultPgResourceOptions,
  DefaultPgResource,
  DefaultPgResourceParameter,
  DefaultPgResourceUnique,
  DefaultRegistryBuilder,
  EmptyRegistryBuilder,
  DefaultPgFunctionResourceOptions,
  _AnyPgFunctionResourceOptions,
} from "./datasource.js";
import {
  PgClient,
  PgClientQuery,
  PgClientResult,
  PgExecutor,
  PgExecutorContext,
  PgExecutorContextPlans,
  PgExecutorInput,
  PgExecutorMutationOptions,
  PgExecutorOptions,
  WithPgClient,
} from "./executor.js";
import { PgBooleanFilterStep } from "./filters/pgBooleanFilter.js";
import { PgClassFilterStep } from "./filters/pgClassFilter.js";
import { PgManyFilterStep } from "./filters/pgManyFilter.js";
import { PgOrFilterStep } from "./filters/pgOrFilter.js";
import {
  PgCodecAttributes,
  GetPgRegistryCodecRelations,
  GetPgRegistryCodecs,
  GetPgRegistrySources,
  GetPgResourceAttributes,
  GetPgResourceCodec,
  GetPgResourceRegistry,
  GetPgResourceRelations,
  GetPgResourceUniques,
  KeysOfType,
  MakePgServiceOptions,
  PgClassSingleStep,
  PgCodec,
  PgCodecAnyScalar,
  PgCodecExtensions,
  PgCodecList,
  PgCodecPolymorphism,
  PgCodecPolymorphismRelational,
  PgCodecPolymorphismRelationalTypeSpec,
  PgCodecPolymorphismSingle,
  PgCodecPolymorphismSingleTypeAttributeSpec,
  PgCodecPolymorphismSingleTypeSpec,
  PgCodecPolymorphismUnion,
  PgRelation,
  PgCodecRelationConfig,
  PgCodecRelationExtensions,
  PgCodecWithAttributes,
  PgConditionLikeStep,
  PgDecode,
  PgEncode,
  PgEnumCodec,
  PgEnumValue,
  PgGroupSpec,
  PgOrderSpec,
  PgRefDefinition,
  PgRefDefinitionExtensions,
  PgRefDefinitions,
  PgRegistry,
  PgTypedExecutableStep,
  PlanByUniques,
  TuplePlanMap,
  _AnyPgCodec,
  _AnyPgCodecAttributesRecord,
  _AnyPgCodecRelationConfig,
  _AnyPgRegistry,
  _AnyPgRegistryConfig,
  _AnyScalarPgCodec,
  PgCodecAttributesRecord,
  PgCodecFromJavaScript,
  PgCodecFromPg,
  PgCodecFromPostgres,
  PgCodecName,
  PgCodecRelationBase,
  PgCodecRelationConfigLocalCodec,
  PgCodecRelationConfigName,
  PgCodecRelationConfigRemoteResourceOptions,
  PgOrderAttributeSpec,
  PgOrderFragmentSpec,
  _AnyPgRangeItemCodec,
  PgRegistryCodecRelations,
  PgRegistryCodecs,
  PgRegistryConfig,
  PgRegistryConfigCodecs,
  PgRegistryConfigRelationConfigs,
  PgRegistryConfigResourceOptions,
  PgRegistryRelationConfigs,
  PgRegistryResourceOptions,
  PgRegistryResources,
  DefaultPgRelation,
  _AnyPgRelation,
  DefaultPgCodec,
  DefaultScalarPgCodec,
  DefaultPgCodecRelationConfig,
  DefaultPgCodecAttributesRecord,
  DefaultPgRangeItemCodec,
  DefaultPgRegistry,
  DefaultPgCodecWithAttributes,
  DefaultPgRegistryConfig,
} from "./interfaces.js";
import { PgLockableParameter, PgLockCallback } from "./pgLocker.js";
import {
  pgClassExpression,
  PgClassExpressionStep,
} from "./steps/pgClassExpression.js";
import {
  PgConditionCapableParentStep,
  PgConditionStep,
  PgConditionStepExtensions,
  PgHavingConditionSpec,
  PgWhereConditionSpec,
  pgWhereConditionSpecListToSQL,
} from "./steps/pgCondition.js";
import { PgCursorStep } from "./steps/pgCursor.js";
import {
  pgDeleteSingle,
  PgDeleteSingleStep,
  DefaultPgDeleteSingleStep,
  _AnyPgDeleteSingleStep,
} from "./steps/pgDeleteSingle.js";
import { pgInsertSingle, PgInsertSingleStep } from "./steps/pgInsertSingle.js";
import { pgPageInfo, PgPageInfoStep } from "./steps/pgPageInfo.js";
import {
  pgPolymorphic,
  PgPolymorphicStep,
  PgPolymorphicTypeMap,
} from "./steps/pgPolymorphic.js";
import {
  digestsFromArgumentSpecs,
  pgSelect,
  PgSelectArgumentDigest,
  PgSelectArgumentSpec,
  pgSelectFromRecords,
  PgSelectIdentifierSpec,
  PgSelectMode,
  PgSelectOptions,
  PgSelectParsedCursorStep,
  PgSelectStep,
  sqlFromArgDigests,
  DefaultPgSelectStep,
  _AnyPgSelectStep,
} from "./steps/pgSelect.js";
import {
  pgSelectFromRecord,
  pgSelectSingleFromRecord,
  PgSelectSinglePlanOptions,
  PgSelectSingleStep,
  _AnyPgSelectSinglePlanOptions,
  _AnyPgSelectSingleStep,
  DefaultPgSelectSingleStep,
} from "./steps/pgSelectSingle.js";
import {
  pgSingleTablePolymorphic,
  PgSingleTablePolymorphicStep,
} from "./steps/pgSingleTablePolymorphic.js";
import { PgTempTableStep } from "./steps/pgTempTable.js";
import {
  pgUnionAll,
  PgUnionAllSingleStep,
  PgUnionAllStep,
  PgUnionAllStepCondition,
  PgUnionAllStepConfig,
  PgUnionAllStepConfigAttributes,
  PgUnionAllStepMember,
  PgUnionAllStepOrder,
} from "./steps/pgUnionAll.js";
import {
  pgUpdateSingle,
  PgUpdateSingleStep,
  DefaultPgUpdateSingleStep,
  _AnyPgUpdateSingleStep,
} from "./steps/pgUpdateSingle.js";
import {
  pgValidateParsedCursor,
  PgValidateParsedCursorStep,
} from "./steps/pgValidateParsedCursor.js";
import { toPg, ToPgStep } from "./steps/toPg.js";
import {
  withPgClient,
  WithPgClientStep,
  WithPgClientStepCallback,
  withPgClientTransaction,
} from "./steps/withPgClient.js";
import { assertPgClassSingleStep } from "./utils.js";

export {
  DefaultPgResourceOptions,
  _AnyPgSelectSinglePlanOptions,
  DefaultPgCodecAttribute,
  DefaultPgCodecAttributeVia,
  _AnyPgSelectSingleStep,
  DefaultPgResource,
  DefaultPgResourceParameter,
  DefaultPgSelectSingleStep,
  DefaultPgRelation,
  _AnyPgRelation,
  DefaultPgCodecWithAttributes,
  DefaultPgResourceUnique,
  DefaultRegistryBuilder,
  EmptyRegistryBuilder,
  DefaultPgUpdateSingleStep,
  _AnyPgUpdateSingleStep,
  DefaultPgDeleteSingleStep,
  _AnyPgDeleteSingleStep,
  DefaultPgCodec,
  _AnyPgRegistryBuilder,
  _AnyPgResource,
  _AnyPgResourceOptions,
  _AnyPgResourceParameter,
  _AnyPgResourceUnique,
  _AnyScalarPgResource,
  _AnyPgCodecAttribute,
  _AnyPgCodecAttributeVia,
  _AnyPgCodecAttributeViaAttribute,
  _AnyPgCodecAttributeViaRelationName,
  _AnyPgCodec,
  _AnyPgCodecAttributesRecord,
  _AnyPgCodecRelationConfig,
  _AnyPgRegistry,
  _AnyPgRegistryConfig,
  _AnyScalarPgCodec,
  PgCodecAttributes,
  PgCodecAttributesRecord,
  PgCodecFromJavaScript,
  PgCodecFromPg,
  PgCodecFromPostgres,
  PgCodecName,
  PgCodecRelationBase,
  PgCodecRelationConfigLocalCodec,
  PgCodecRelationConfigName,
  PgCodecRelationConfigRemoteResourceOptions,
  PgOrderAttributeSpec,
  PgOrderFragmentSpec,
  _AnyPgRangeItemCodec as PgRangeItemCodec,
  PgRegistryCodecRelations,
  PgRegistryCodecs,
  PgRegistryConfig,
  PgRegistryConfigCodecs,
  PgRegistryConfigRelationConfigs,
  PgRegistryConfigResourceOptions,
  PgRegistryRelationConfigs,
  PgRegistryResourceOptions,
  PgRegistryResources,
  PgRelation,
  assertPgClassSingleStep,
  digestsFromArgumentSpecs,
  domainOfCodec,
  enumCodec,
  DefaultPgFunctionResourceOptions,
  _AnyPgFunctionResourceOptions,
  getCodecByPgCatalogTypeName,
  getInnerCodec,
  GetPgRegistryCodecRelations,
  GetPgRegistryCodecs,
  GetPgRegistrySources,
  GetPgResourceAttributes,
  GetPgResourceCodec,
  GetPgResourceRegistry,
  GetPgResourceRelations,
  GetPgResourceUniques,
  DefaultScalarPgCodec,
  DefaultPgCodecRelationConfig,
  DefaultPgCodecAttributesRecord,
  DefaultPgRangeItemCodec,
  DefaultPgRegistry,
  DefaultPgRegistryConfig,
  isEnumCodec,
  KeysOfType,
  listOfCodec,
  makePgResourceOptions,
  MakePgServiceOptions,
  makeRegistry,
  makeRegistryBuilder,
  ObjectFromPgCodecAttributes,
  PgBooleanFilterStep,
  PgBox,
  PgCircle,
  pgClassExpression,
  PgClassExpressionStep,
  PgClassFilterStep,
  PgClassSingleStep,
  PgClient,
  PgClientQuery,
  PgClientResult,
  PgCodec,
  PgCodecAnyScalar,
  PgCodecAttribute,
  PgCodecAttributeExtensions,
  PgCodecAttributeVia,
  PgCodecAttributeViaExplicit,
  PgCodecExtensions,
  PgCodecList,
  PgCodecPolymorphism,
  PgCodecPolymorphismRelational,
  PgCodecPolymorphismRelationalTypeSpec,
  PgCodecPolymorphismSingle,
  PgCodecPolymorphismSingleTypeAttributeSpec,
  PgCodecPolymorphismSingleTypeSpec,
  PgCodecPolymorphismUnion,
  PgCodecRef,
  PgCodecRefExtensions,
  PgCodecRefPath,
  PgCodecRefPathEntry,
  PgCodecRefs,
  PgRelation as PgCodecRelation,
  PgCodecRelationConfig,
  PgCodecRelationExtensions,
  PgCodecWithAttributes,
  PgConditionCapableParentStep,
  PgConditionLikeStep,
  PgConditionStep,
  PgConditionStepExtensions,
  PgCursorStep,
  PgDecode,
  pgDeleteSingle,
  PgDeleteSingleStep,
  PgEncode,
  PgEnumCodec,
  PgEnumCodecSpec,
  PgEnumValue,
  PgExecutor,
  PgExecutorContext,
  _AnyPgSelectStep,
  DefaultPgSelectStep,
  PgExecutorContextPlans,
  PgExecutorInput,
  PgExecutorMutationOptions,
  PgExecutorOptions,
  PgFunctionResourceOptions,
  PgGroupSpec,
  PgHavingConditionSpec,
  PgHStore,
  pgInsertSingle,
  PgInsertSingleStep,
  PgInterval,
  PgLine,
  PgLockableParameter,
  PgLockCallback,
  PgLseg,
  PgManyFilterStep,
  PgOrderSpec,
  PgOrFilterStep,
  pgPageInfo,
  PgPageInfoStep,
  PgPath,
  PgPoint,
  PgPolygon,
  pgPolymorphic,
  PgPolymorphicStep,
  PgPolymorphicTypeMap,
  PgRecordTypeCodecSpec,
  PgRefDefinition,
  PgRefDefinitionExtensions,
  PgRefDefinitions,
  PgRegistry,
  PgRegistryBuilder,
  PgResource,
  PgResourceExtensions,
  PgResourceOptions,
  PgResourceParameter,
  PgResourceUnique,
  PgResourceUniqueExtensions,
  pgSelect,
  PgSelectArgumentDigest,
  PgSelectArgumentSpec,
  pgSelectFromRecord,
  pgSelectFromRecords,
  PgSelectIdentifierSpec,
  PgSelectMode,
  PgSelectOptions,
  PgSelectParsedCursorStep,
  pgSelectSingleFromRecord,
  PgSelectSinglePlanOptions,
  PgSelectSingleStep,
  PgSelectStep,
  pgSingleTablePolymorphic,
  PgSingleTablePolymorphicStep,
  PgTempTableStep,
  PgTypedExecutableStep,
  pgUnionAll,
  PgUnionAllSingleStep,
  PgUnionAllStep,
  PgUnionAllStepCondition,
  PgUnionAllStepConfig,
  PgUnionAllStepConfigAttributes,
  PgUnionAllStepMember,
  PgUnionAllStepOrder,
  pgUpdateSingle,
  PgUpdateSingleStep,
  pgValidateParsedCursor,
  PgValidateParsedCursorStep,
  PgWhereConditionSpec,
  pgWhereConditionSpecListToSQL,
  PlanByUniques,
  rangeOfCodec,
  recordCodec,
  sqlFromArgDigests,
  toPg,
  ToPgStep,
  TuplePlanMap,
  TYPES,
  WithPgClient,
  withPgClient,
  WithPgClientStep,
  WithPgClientStepCallback,
  withPgClientTransaction,
};

exportAsMany("@dataplan/pg", {
  assertPgClassSingleStep,
  domainOfCodec,
  getInnerCodec,
  enumCodec,
  getCodecByPgCatalogTypeName,
  isEnumCodec,
  listOfCodec,
  rangeOfCodec,
  recordCodec,
  makeRegistryBuilder,
  makeRegistry,
  makePgResourceOptions,
  TYPES,
  PgResource,
  PgExecutor,
  PgBooleanFilterStep,
  PgClassFilterStep,
  PgManyFilterStep,
  PgOrFilterStep,
  pgClassExpression,
  PgClassExpressionStep,
  PgConditionStep,
  pgWhereConditionSpecListToSQL,
  PgCursorStep,
  pgDeleteSingle,
  PgDeleteSingleStep,
  pgInsertSingle,
  PgInsertSingleStep,
  pgPageInfo,
  PgPageInfoStep,
  pgPolymorphic,
  PgPolymorphicStep,
  pgSelect,
  digestsFromArgumentSpecs,
  pgSelectFromRecords,
  PgSelectStep,
  sqlFromArgDigests,
  pgSelectFromRecord,
  pgSelectSingleFromRecord,
  PgSelectSingleStep,
  pgSingleTablePolymorphic,
  pgUnionAll,
  PgUnionAllSingleStep,
  PgUnionAllStep,
  PgSingleTablePolymorphicStep,
  pgUpdateSingle,
  PgUpdateSingleStep,
  pgValidateParsedCursor,
  PgValidateParsedCursorStep,
  PgTempTableStep,
  toPg,
  ToPgStep,
  withPgClient,
  withPgClientTransaction,
  WithPgClientStep,
});

export {
  /** @deprecated Use Pg prefix */
  PgBooleanFilterStep as BooleanFilterStep,
  /** @deprecated Use Pg prefix */
  PgClassFilterStep as ClassFilterStep,
  /** @deprecated Use Pg prefix */
  PgManyFilterStep as ManyFilterStep,
  /** @deprecated Use Pg prefix */
  PgOrFilterStep as OrFilterStep,
  /** @deprecated Use Pg prefix */
  PgTempTableStep as TempTableStep,
};

export { version } from "./version.js";
