#!/usr/bin/env bash
export GRAPHILE_ENV="${GRAPHILE_ENV:-development}"
export NODE_ENV="${NODE_ENV:-development}"
export DEBUG="${DEBUG:-graphile-build:warn}"

yarn nodemon \
  --watch "graphile.config.ts" \
  --watch "../../grafast/*/dist/**/*" \
  --watch "../../graphile-build/*/dist/**/*" \
  --watch "../../postgraphile/*/dist/**/*" \
  --watch "../../utils/*/dist/**/*" \
  --watch "../../grafast/ruru/bundle/**/*" \
  --watch "../../contrib/*/dist/**/*" \
  -x "node --enable-source-maps dist/cli-run.js --watch $*"
