name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      # To create a release, and also maybe to push branches:
      contents: write

      # To create/maintain the Changesets pull request
      pull-requests: write

      # PRs are backed by issues; this probably helps with stuff like reading labels/etc
      issues: read

      # To enable trusted publishing
      id-token: write

      ## To publish packages to GitHub Packages
      #packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset-version
          publish: yarn changeset-publish
